### ISSUE TITLE
U.S. Navy Fighters (Gold) (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1007]
has watermark replacementdocs

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual (original scan of the US. Navy Fighters Gold manual)

proof:
![s-l1600](https://github.com/exoscoriae/eXoDOS/assets/67441153/296ca7b7-f53b-4ebf-a1f4-d80842022d47)

**Comment by exoscoriae** [comment]
added
