### ISSUE TITLE
Utopia - The Creation of a Nation (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1018]
has watermark replacementdocs

**Comment by Eulisker** [comment]
found 

- [ ] manual

scanned version. The current manual has a tutorial and additional pc instructions portion that is missing here. I put them up as seperate files. See #2066 

added to the github folder

**Comment by exoscoriae** [comment]
moved final page of manual to the final page. for some reason it was the first page
