### ISSUE TITLE
Alternate Reality - The City (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#102]
pages 8 and 9 together are a map  perhaps they should be joined together as a double page

**Comment by TimberlAndRE-de** [comment]
map pages merged and uploaded to github folder

**Comment by Eulisker** [comment]
I found a later revision of the

- [ ] manual

The current one has a 1986 copyright. The new one 1988. It is fleshed out in a few parts and the font is much more readable.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
