### ISSUE TITLE
Visions of Aftermath - The Boomtown (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1026]
has watermark underdogs.cjb.net
b/w scan with ocr conversion but all readable

**Comment by bigjim161** [comment]
I found another manual (quality upgrade) with splitted extras (not like the current manual): 
-Visions of Aftermath- The Boomtown NewWorldVision (Novel)
-Visions of Aftermath- The Boomtown-EZFISH owner guide

The current manual  has merged extras

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found another quality upgrade for

- [ ] manual
- [ ] EZFISH Owners Manual
- [ ] New World Vision

Added to the github folder.

**Comment by exoscoriae** [comment]
all three rejected and renamed. I don't see a quality improvement. The existing were actually scanned at a higher resolution. So, this seems like a downgrade to me.

**Comment by Eulisker** [comment]
I cropped the manuals and put them back in the github folder. 

I still think the way the EZFISH Manual is scanned looks horrible. The paper is yellow and when there is no text it is just white in the scan.

**Comment by exoscoriae** [comment]
ok. replacing it with your ezfish scan.

updated others with cropped versions
