### ISSUE TITLE
Amberstar (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#103]
pages 2 86 88 104 are missing (and replaced by empty pages in wrong format)

also the replaced page 2 has a watermark (scanned by Thalion)

**Comment by SmilingSpectre** [comment]
Well, the pages _are_ empty after all. I'll upload manual from mocagh, but it's worse (paper is too thin, so shadow text is visible).

**Comment by TimberlAndRE-de** [comment]
it's for commodore/atari but i think it's better than the one currently assigned. it's complete and has no watermark

**Comment by SmilingSpectre** [comment]
Yes, but it's exactly the same us our. But better. :)

**Comment by TimberlAndRE-de** [comment]
That's right, it should replace the current one
I wrote the version thing just to signalize eXo to keep the issue open after replacing it
Maybe someday we'll find a manual for the PC version of the game

**Comment by exoscoriae** [comment]
replaced
