### ISSUE TITLE
Amnesia (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#104]
pages 23 - 36 are upside down

**Comment by TimberlAndRE-de** [comment]
pages turned
(was probably made, because it's about game tips. maybe this is actually the case in the original manual.
Nevertheless I turned the pages correctly, otherwise it's hard to read on screen if you can't turn the manual ;-))

**Comment by exoscoriae** [comment]
I extracted the pages that were upside down, and resaved them as an extra.
