### ISSUE TITLE
Wizard of Id's WizType (1984)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1049]
needs to be cropped

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre found 

- [ ] manual

definitely better quality and more pages, especially more technical information ... but for tandy 
But since all information from the current manual are included in this new one, I would recommend to replace it

added to the github folder

**Comment by exoscoriae** [comment]
replaced
