### ISSUE TITLE
World Circuit (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1054]
has watermark theunderdogs.org
scanned with ocr  font and format changes on some pages
coverpage and pages 2 3 6 7 10 11 18 19 66 are missing

**Comment by TimberlAndRE-de** [comment]
found quality upgrade for the manual with all missing pages and no watermark
also found alternate manual with more technical informations and a reference card in it

**Comment by exoscoriae** [comment]
added
