### ISSUE TITLE
Zak McKracken and the Alien Mindbenders (1988), Maniac Mansion (1987), Zak McKracken and the Alien Mindbenders Enhanced (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1055]
I was browsing around the net and discovered a neat trick that will mean we dont need to dual config these games. The reason we did so was that we would loose mouse support by using tandy mode (in the case of Zak McKracken and the Alien Mindbenders (1988) we didnt dual config it as we didnt have mouse anyway). I read that by pressing Shift+M you get a "Mouse On" message and mouse becomes enabled, I tested and it works. It will require a user message but thats much better than having dual config setup. To be specific we will need to:

Zak McKracken and the Alien Mindbenders (1988): Add a user message explaining Shift+M to enable mouse

Maniac Mansion (1987): Reset the launch bat to the standard template, delete dosbox.conf, and rename tandy.conf to dosbox.conf. Add a user message explaining Shift+M to enable mouse. This does mean we are switching over to the hacked for Tandy sound exe, but that wouldnt be the first time we've used a patched exe.

Zak McKracken and the Alien Mindbenders Enhanced (1988): Reset the launch bat to the standard template, set machine=tandy in dosbox.conf. Add a user message explaining Shift+M to enable mouse.

**Comment by exoscoriae** [comment]
added the note to launches
removed the alternate launch from the game launch file
added the mreset utility to help lock the mouse to the window, as simply clicking in the window wasn't capturing it.

**Comment by Eulisker** [comment]
While checking the german version of Zak Enhanced i found the following.

In the game dir there is a file called PREFS. If you open the file with notepad and set the following.

![image](https://user-images.githubusercontent.com/81642149/126479649-8f23dcd4-ce65-4deb-9547-5d11c6308406.png)

You can start the game with the start.bat and have mouse support enabled from the start. I will try this with the 3 other games and report back if something like this works.

**Comment by exoscoriae** [comment]
@Eulisker what are the "4 games"? Zak and Zak Enhanced make up two of them, what are the other two?

**Comment by exoscoriae** [comment]
Zak, Zak Enhanced, and Maniac Mansion have all been setup this way. For whatever reason, Maniac Enhanced was already set up this way.
