### ISSUE TITLE
Napoleon vs. The Evil Monarchies: Austerlitz 1805 (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1057]
the wrong manual, it is for the game "Austerlitz (1989)" (there's already an open issue for that one)
it was exchanged in WIP (discord: [link](https://discordapp.com/channels/454359114601201666/492422228281917470/723167399704133652))
Please restore the old one from eXoDOS 4.0 until a better one is found (has watermark and is ocr-scan)
Please leave the issue open then

**Comment by exoscoriae** [comment]
replaced old manual

**Comment by TimberlAndRE-de** [comment]
maybe coverpage is missing - no proof found yet

**Comment by Eulisker** [comment]
I found the

- [ ] manual

without the watermark. It is still bad  otherwise.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
