### ISSUE TITLE
Annals of Rome (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#107]
has watermark Taken from Amiga-Manuals-Website
contains reference-card (pages 34/35)
contains map (page 36)

**Comment by exoscoriae** [comment]
split map and reference card from manual.

unable to remove watermark, so I'll leave the issue open

**Comment by bigjim161** [comment]
Found a manual without watermark

**Comment by exoscoriae** [comment]
replaced
