### ISSUE TITLE
Zool (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1071]
has watermark replacementdocs
it's for the amiga-atari version

**Comment by exoscoriae** [comment]
removed existing watermark

**Comment by SmilingSpectre** [comment]
I cannot found DOS manual, but I found better quality of existing one. Uploaded.

**Comment by TimberlAndRE-de** [comment]
strange, i cannot find any sign of atari or amiga in the current version... 
seems i made a mistake while checking this manual?
@SmilingSpectre the one you uploaded doesn't look anything like the one in eXoDOS i think... or am i missing something?

**Comment by SmilingSpectre** [comment]
They are identical. Remove comics (up to the p6), remove mentions of platform and codewheel at p.6, and you'll get manual in the collection. "Digitally recreated".

**Comment by TimberlAndRE-de** [comment]
Ok thx, so I guess it should be replaced :+1:

**Comment by TimberlAndRE-de** [comment]
DOS manual is still missing

**Comment by bigjim161** [comment]
I found an Addentdum for the pc Version

In this video there is a proof a Pc manual
![image](https://user-images.githubusercontent.com/67555221/122653405-7b353d00-d144-11eb-9c6e-c0c6d9c0cdf5.png)


https://www.youtube.com/watch?v=kFTq0F9q6bA

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
Manual in

- English
- French
- German
- Italian
