### ISSUE TITLE
Pete Sampras Tennis '97 (1997) (Capslock key bug)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1078]
This game uses the "capslock" key for "Drop" for "Keyboard 1" . (It works once in 2 two)
Is it Possible to set the Key "S" for "Drop", in the "setup controls" menu, instead of "capslock"?
Then keys the must be: 
Left: X
Right: V
Up: D
Down: C
Strong shot: A
Lob shot: Q
Drop: S
Slice:  TAB

**Comment by exoscoriae** [comment]
done
