### ISSUE TITLE
Star Fleet I - The War Begins! (1985)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1079]
from @SmilingSpectre [discord](https://discordapp.com/channels/454359114601201666/492422228281917470/729289654679109704)
"there are the errors in Star Fleet docs.
1. Star Fleet I The War Begins! Training Manual.pdf and main Star Fleet I - The War Begins! (1985).pdf is the same doc. First one can be removed, I think.
2. Star Fleet I The War Begins! Supplement Manual.pdf is Star Fleet I The War Begins! Officer's Manual Supplement.pdf
3. While I am on that, Star Fleet I The War Begins! - Officers manual.pdf is Star Fleet I The War Begins! - Officer's manual.pdf"

**Comment by exoscoriae** [comment]
Issues 1 and 2 were handled.
Unclear about what issue 3 is.

**Comment by TimberlAndRE-de** [comment]
according to [discord](https://discordapp.com/channels/454359114601201666/492422228281917470/729560224746307657) it seems to be cleared so i closed the issue

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found 
- real manual (current one is "Training Manual")
- quality upgrade for the "Training Manual" as an extra
both added to the github folder

**Comment by exoscoriae** [comment]
what was uploaded as the "real manual" was just a worse quality version of the Officer's manual that we already had in extras. Moved the new training manual over though. decided to switch the official manual to the officer's manual.

**Comment by Eulisker** [comment]
The officers manual is still in there as an extra and the official manual. It can be deleted from the extras.

**Comment by exoscoriae** [comment]
removed
