### ISSUE TITLE
PlayMaker Football (1991) Bug

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1083]
The Exodos version of PlayMaker Football (in the launchbox) is not cracked, and the manual is missing. I found a cracked version here https://www.myabandonware.com/game/playmaker-football-qh

**Comment by exoscoriae** [comment]
cracked existing issue by adding "playfoot" to run,bat

**Comment by bigjim161** [comment]
I found a manual

Added to the Github folder

**Comment by exoscoriae** [comment]
added
