### ISSUE TITLE
Dungeon Master (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1085]
@SmilingSpectre found an upgrade for the extra:
Dungeon Master - Handbook 2 Alt

**Comment by exoscoriae** [comment]
replaced

**Comment by TimberlAndRE-de** [comment]
discord user Eulisker found

- [ ] Quick Start Guide (Reference Card)

added to the github folder

**Comment by Eulisker** [comment]
I found better scans of the

- [ ] Adventurer`s Handbook
- [ ] Adventurer`s Handbook (Alternate)

The current version is omitting a few (blank) pages and i think this one looks better overall.

Also a better scan of the 

- [ ] Reference card

This one was missing a page too.

And finally

- [ ] Poster
- [ ] Hintbook Ad
- [ ] DM Guide
- [ ] DM Guide Spell List
- [ ] a picture of the sound adapter included with the game

All added to the github folder.

**Comment by exoscoriae** [comment]
none of these files are in the github

**Comment by exoscoriae** [comment]
the JPG's included are *incredibly tiny*, which makes them practically useless. The "hintbook ad" is just a very tiny image scan of the front of the Adventurer's Handbook you already found. It is identical? There is nothing to indicate it is an ad.

The DM Guide Spell List needs a higher quality scan. The current image scan is 257x334. On a 4k screen, it is unreadable.

The poster scan is 210x302. This is also unusable.

What about this image as a replacement for the spell guide?
http://gamerwalkthroughs.com/wp-content/uploads/2016/01/Dungeon-Master-Spells.jpg

Closing for now unless higher quality images can be found. Small versions have been relocated to the rejected folder.

**Comment by Eulisker** [comment]
It only took me 2 years to see this. 
I somehow downloaded the preview pictures from mocagh instead of the correct ones. I reuploaded the 4 rejected files to the github folder.


-  Poster
-  Hintbook Ad
-  DM Guide Spell List
-  a picture of the sound adapter included with the game

**Comment by exoscoriae** [comment]
added
