### ISSUE TITLE
Crush, Crumble and Chomp! (1983)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1086]
@SmilingSpectre found quality upgrade for the Monsters extra
(pages for "Mantra" were missing, i added them from the current document)
I copied it to the github folder

**Comment by SmilingSpectre** [comment]
They are all better, not only Mantra. Current project files are extremely low-res.

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre awesome! i updated the manual in the github folder 👍

**Comment by exoscoriae** [comment]
replaced
