### ISSUE TITLE
F-117A Nighthawk Stealth Fighter 2.0 (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1087]
@SmilingSpectre found reference card and keyboard overlay (both were included in the manual)
I uploaded them to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found quality upgrade (higher resolution/colored) for both extras
- keyboard overlay 
- technical supplement
