### ISSUE TITLE
Rebel Charge at Chickamauga (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1089]
@SmilingSpectre found a quality upgrade
I copied it to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I cut the Map and Quick reference out of the 

- [ ] Manual

See #3014

Thanks to discord user remowilliams for scanning.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced manual and added extras
