### ISSUE TITLE
Archipelagos (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#110]
has watermark replacementdocs
is blurry  text is hardly readable

**Comment by TimberlAndRE-de** [comment]
found 
- [ ] quality upgrade without watermark and better scan

added to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
The current manual is the US one. I think the european manual should be added too. It has significant differences in the backstory. 
If you decide to put the US manual in Extras and use the European manual as the main one we can link from the language packs to it.

Added to the github folder.

**Comment by exoscoriae** [comment]
added as an extra
