### ISSUE TITLE
F-19 Stealth Fighter (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1104]
found maps as extra (taken from the current manual, see #311 )
and @SmilingSpectre found official handbook as an extra

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found extras:
- maps (quality upgrade and more maps)
- technical supplement
- keyboard overlay

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] Pete Bonanni - F-19 Stealth Air Combat - unofficial guide

**Comment by exoscoriae** [comment]
added
