### ISSUE TITLE
Gunship (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1105]
@SmilingSpectre found an unofficial guide for Gunship (and other Heli-Sims)
from the foreword: "Although this book was written around Gunship, most of the tactics and overall strategies translate well to other games."
but i think it would be enough to add it to Gunship as an extra?

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found

- [ ] copy protection sheet / password list (different from the one in the collection - can't find proof, which is the right one, so add both maybe?)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre posted in (#4804 ):

Set of extras uploaded by user baloo32.

- [ ] Codes
- [ ] Floppy Disk 3.5"
- [ ] Floppy Disk 5.25" (x2)
- [ ] IBM Keyboard Overlay
- [ ] Tandy Keyboard Overlay
- [ ] Loading Instructions
- [ ] Technical Supplement

Uploaded as Gunship Extras.zip

**Comment by exoscoriae** [comment]
existing technical manual is better

added others
