### ISSUE TITLE
Silent Service (1985)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1106]
@SmilingSpectre found an unofficial guide for Submarine-Simulations.
the preface says:
"Finally, you'll benefit from the experience of many other game players as you read the chapters which give tips and hints for playing:
- Silent Service
- GATO
- Up Periscope!
- Sub Battle Simulator"

so maybe it should be added to all of them as an extra?

**Comment by exoscoriae** [comment]
added to all 4 games
