### ISSUE TITLE
Clash of Steel - World War 2 - Europe 1939-45 (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1112]
found reference card as an extra

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
discord user pochepiller found

- [ ] copy-protection codes ([discord-post](https://discord.com/channels/454359114601201666/492422228281917470/794030184084668416))
- [ ] also an note should be added to the batchfile that the codes are needed

added to the github folder

**Comment by exoscoriae** [comment]
added codes
