### ISSUE TITLE
Demon Stalkers (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1116]
found a code wheel as extra, maybe it can be made "interactive" ?
(it seems to be from the c64 release but i'm not sure if it was also used for the DOS release...)

**Comment by exoscoriae** [comment]
the zip file is missing the pdf. it just has the 4 black and white images

**Comment by exoscoriae** [comment]
sent scans to be converted

**Comment by exoscoriae** [comment]
added
