### ISSUE TITLE
Hong Gildong-jeon 2 (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1120]
Not cracked though we do have a jpg of the necessary codes in extras folder

**Comment by amazzanti** [comment]
[H2.zip](https://github.com/exoscoriae/eXoDOS/files/13772423/H2.zip)

**Comment by exoscoriae** [comment]
thank you @amazzanti !

Crack works great. Still can't figure out the game for the life of me though. lol
