### ISSUE TITLE
Spong (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1121]
This one is separate from the other vgaonly games as the fix is more than just a change to machine=

Currently the game uses ECE and vgaonly to deal with a flicker issue, though even those settings dont do so completely. I discovered that using Daum with output=direct3d combined with changing machine back to machine=svga_s3 removes the flicker the same, if not better.

**Comment by exoscoriae** [comment]
it is identical to me

**Comment by exoscoriae** [comment]
on second look, getting the the paddles the flickering is still constant, but a secondary flicker layer seems to have disappeared
