### ISSUE TITLE
Up Periscope! (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1128]
Another with the flicker issue we resolved in the past with vgaonly. Switch to Daum, output=direct3d, and machine=svga_s3 for better results.

**Comment by exoscoriae** [comment]
changes made

**Comment by exoscoriae** [comment]
however I personally didn't see a difference here. not sure where you are getting flickering. for me it is only the two numbers in the center of the screen during gameplay. however it is identical w/ both setups.

**Comment by Python-Exoproject** [comment]
It depended on the scenario. If you started the game using options D, 2, 1, and C to start the mission then the horizon also flickered. With new settings it doesnt, thanks for the fix.
