### ISSUE TITLE
VGA Jigsaw (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1129]
Two things with this one. Its currently using machine=vesa_nolfb but I completed a puzzle using svga_s3 and didnt have an issue.

The other thing is that the puzzle is currently restricted to the top left of the screen. I ran the config utility and changed to the generic "SVGA VESA 640x480" and the puzzle was much larger. It doesnt make sense to me why they would include an 800x600 mode if the puzzle doesnt fill the screen at that resolution so I think there might be more to this, although I couldnt see what it was.

**Comment by exoscoriae** [comment]
this is likely why I had vesa nolfb set. testing to see if I could solve the issue

dropped it to 640

**Comment by Python-Exoproject** [comment]
Launch command and exit command in dosbox.conf are #'d out

**Comment by exoscoriae** [comment]
was probably better that way, but I went ahead and fixed it. =)

**Comment by Python-Exoproject** [comment]
lol
