### ISSUE TITLE
Wibarm (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1130]
I was testing this one for coming off vgaonly and it had pc speaker. Ive gotten into the habit of always trying a pc speaker game on tandy & pcjr to see if it randomly works. In this case I got a hit, there was Tandy sound. It had a graphics driver complaint though so I had to go back to the original disks and reinstall it. Inside the sync folder \github\bugs\wibarm you will find a zip of the freshly installed game ready for Tandy and the updated conf. I also left the floppy disk images in case anyone ever wants to change modes to something else.

**Comment by exoscoriae** [comment]
great find
