### ISSUE TITLE
Virtual Tennis (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1132]
while searching for german cds on eBay i found a game that isn't in eXoDOS i think (or i missed the alternate titel maybe?) - so i bought it ;-)
It's "Virtual Tennis" (1996) from DDM and it's in English, German, French and Spain (MLI)
It's not listed on Mobygames
It's in TDC (boohyaka checked it) - seems to be a spanish - only rip

i installed it in english and upped it (including the bin/cue) to the drobox if you want to check it (in my personal folder)

**Comment by TimberlAndRE-de** [comment]
![photo1](https://user-images.githubusercontent.com/67441153/86928836-6202ce80-c135-11ea-9442-6ddb7a0c0190.JPG)
![photo2](https://user-images.githubusercontent.com/67441153/86928841-64652880-c135-11ea-9915-ef70c1501a0d.JPG)

**Comment by exoscoriae** [comment]
thank you. added
