### ISSUE TITLE
Zone Raiders (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1134]
This game is using machine=vesa_nolfb so I tried with machine=svga_s3 and game loaded up to a mission fine. 

I also note that there are graphics and resolution settings to change to make the game look much better. In the Graphics menu under video mode 640x480 can be selected and in the detail sub menu Rear View mirror can be turned on, along with texture detail up to high. The catch is that the settings arent saved when you exit the game. There is an alternate way to increase the detail settings, press F4 to turn on the rear view mirror, F6 for high texture detail, but for the res it has to be done via the menu.

This is compounded by the fact cycles need to increase if you increase the resolution. We could handle it like some of those bullfrog games? Instruct the user in a user note what to do to increase the res via menu and the detail via F4 and F6, then pre set the cycles increase so they just press ctrl+f12 once to increase the right amount?

**Comment by exoscoriae** [comment]
seems to run well for for me at 80k cycles in all resolutions or settings.

made svga_s3 changes
added notes at run time
