### ISSUE TITLE
Examination of all current machine=vgaonly games

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1135]
Ok done on this one. You will find in sync \github\bugs\ a folder for each game that I found didnt need vgaonly anymore containing a new dosbox.conf set to either machine=ega or machine=svga_s3 as needed. Im not sure what happened with the rastscan folder but its the same situation as the others. The only folder not to do with this vgaonly issue is that of wibarm which I have raised in a separate issue.

**Comment by exoscoriae** [comment]
thank you. confs applied

**Comment by Python-Exoproject** [comment]
Rasterscan (1988) was missed during the update though the folder on sync was removed. Added again to sync.

**Comment by exoscoriae** [comment]
copied
