### ISSUE TITLE
Snake Bite (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1139]
from sharp_ey in [discord](https://discordapp.com/channels/454359114601201666/620821344891699210/730687492013162507):
https://www.old-games.ru/game/9967.html - can't find this game in your lists. It seems pretty rare, floppy image was uploaded to UG several years ago and pixelatedarcade.com is the only place where I found information about it.

**Comment by exoscoriae** [comment]
added
