### ISSUE TITLE
These games are using Dosbox-X so need fullscreen=desktop

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1140]
Exobius (1995)
Journey to the Center of the Earth (1988)
StarFight III - Within the Darkness (1997)
StarFight IV - Legacy (1998)
StarFight V - Hell's Gate (1999)

**Comment by exoscoriae** [comment]
assuming you meant fullresolution?

That is the change I made

**Comment by Python-Exoproject** [comment]
yes, thanks
