### ISSUE TITLE
Mismatched OPLrate and mixer rate

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1142]
These games have lower values for the mixer rate compared to the oplrate. My understanding is that its not great to have these values mismatched.

2400 AD (1988)
Abandoned Places - A Time for Heroes (1992)
Ishar 3 - The Seven Gates of Infinity (1994)

What im not sure about is whether they would be better with both settings at 22050 or 44100.

There is also Witchaven II - Blood Vengeance (1996) which has oplrate of 44100 and a mixer rate of 49716

**Comment by exoscoriae** [comment]
49716 isn't an in game option for any game that I am aware of.

I changed the top three, but I'm not going to mess with withchaven unless there is a reason to.
