### ISSUE TITLE
No pause after user note

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1143]
No pause after user note in dosbox.conf for these games:

Voyager I - Sabotage of the Robot Ship (1982)
Usurper (1993)
Type Attack (1983)
TetRAM (2000)
Robot Warfare 1 (1999)
Frogger II - ThreeeDeep! (1984)
Dark Queen of Krynn, The (1992)
Disney Presents - The Animation Studio (1990)
Beerworm (1996)

**Comment by exoscoriae** [comment]
all changed except Robot Warfare 1 (1999), as this is a command line game
