### ISSUE TITLE
Conquest 4000 (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1144]
From sharp_ey in [discord](https://discordapp.com/channels/454359114601201666/620821344891699210/731018819455418409) - "Conquest 4000 was uploaded to the Internet two days ago."

https://archive.org/details/conquest-4000

"Conquest 4000, a Trade Wars 2000 style games but with graphics. Navigate and explore the 1000 sectors, collect energy, water, ore, pick colonists and engage in epic battles. Sell your cargos at the Space Station to upgrade or buy new ship."

**Comment by exoscoriae** [comment]
added
