### ISSUE TITLE
TETRIX (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1145]
From sharp_ey in [discord](https://discordapp.com/channels/454359114601201666/620821344891699210/731018819455418409)

https://archive.org/details/TETRIX

"TETRIX is the first game ever released by Martin Bourdages. It is a nice VGA game based on TETRIS, and is fast and very small compared to other games of its kind. This is the registered version of the game with 2 players enabled and an additional game."

This is the registered version according to the comment of the author himself on the archive entry
(for completeness, here is the shareware-version: [archive.org](https://archive.org/details/TETRIX21))

**Comment by exoscoriae** [comment]
added
