### ISSUE TITLE
More pause issues

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1146]
Major Indoor Soccer League (1989): Pause is echoed out
Strip Poker III (1991): Pause is rem'd out

**Comment by exoscoriae** [comment]
I saw no problem at all with the soccer game.
my conf is attached, unedited.
[dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/4907053/dosbox.zip)

fixed poker
