### ISSUE TITLE
Cavern of the Evil Wizard (2020)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1148]
from Jemy Murphy in [discord](https://discordapp.com/channels/454359114601201666/620821344891699210/731135085818019850):

https://gamejolt.com/games/Cavernoftheevilwizard/493137

An oldschool MS-DOS graphical text adventure with 4 color CGA graphics.

**Comment by exoscoriae** [comment]
added
