### ISSUE TITLE
Robot Warfare 1 (1999)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1150]
I had a look at this game after you mentioned it was a command line game as it didnt look like it was to me. If I understand the game correctly you can create your own robots using a windows program "RW1_EDIT.EXE" and duel them in dos with "RW1_DUEL.EXE". I have created a run.bat to assist the user in choosing the robots to compete as the robot creation is a windows program and to load the robots for combat the user would have had to know dos commands. I have attached a zip with the files I made, edited, or need to add.

[Robot Warfare 1.zip](https://github.com/exoscoriae/eXoDOS/files/4904161/Robot.Warfare.1.zip)

If you think its worth it we could also set it up so Robot Warfare 1 (1999).bat would give the option to load the robot creation program. Currently I've just added a note to the user telling them to run "RW1_EDIT.EXE" from windows but not where to find it. If we add this then we should probably also add a user option in run.bat to access debug mode for their creation (see readme.txt in english subfolder for more info).

I am at the edge of my batch file skills here so there are still a couple things I would like to improve if you have any input.

1. A neat way to give the choice for a "fast game" for each current mode. This would mean adding the "-f" flag if chosen for each launch option (see readme.txt in english subfolder for more info).

2. A better way to list all the robot files as currently there are so many that I've had to use dir /w /p but I dont know if its the best way.

3. A way to restructure it so that strings.com doesnt show in the robots folder when the robots are listed.

**Comment by exoscoriae** [comment]
added the ability to choose a fast game or not.
added soundblaster sounds to the matches
moved strings from the robots folder so it no longer displays there
added the ability to play a new match after your fast match concludes
also added the ability to launch the rw1_edit file from the initial launch file

all that is way more than this game ever deserved. enjoy ;)

**Comment by Python-Exoproject** [comment]
The console minimize was left out and the pathing was wrong for the dosbox section in "Robot Warfare 1 (1999).bat". Cahnges needed as follows:

pause
.\util\setconsole.exe /minimize
".\eXoDOS\%GameDir%\RW1_EDIT.EXE"

and

:dosbox
..\..\..\util\setconsole.exe /minimize
cd ..
cd ..
cd ..
cls
".\dosbox\dosbox.exe" -conf "%var%\dosbox.conf" -noconsole -exit

**Comment by exoscoriae** [comment]
if I were to use that pathing, dosbox wouldn't work. the triple cd .. was eliminated in this version.
