### ISSUE TITLE
International Sensible Soccer (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1153]
@SmilingSpectre found quality upgrade (higher resolution, no scan shadows)

**Comment by TimberlAndRE-de** [comment]
From SmilingSpectre on discord: _"Oh, what a mess. there was three almost identical Sensible Soccer games (they honestly named them 1.0, 1.1 and 1.2, actually :) , but only two of them are on PC, and it seems, Sensible didn't bother to issue different manuals.

So every game supposedly issued with the same "Sensible Soccer" manual.

Then over it, "Sensible Soccer - 92/93 edition" and "International Sensible Soccer" got extra addendums.

Problem is, collection is missing main manual altogether for 92/93. It have addendum instead it. "International" is right though.

So I suggest to copy main manual from the version I found, and put current "manual" into "extras"."_

**Comment by exoscoriae** [comment]
ok. next time lets put this under an issue for that exact game. the way this was filed is very confusing.

**Comment by Eulisker** [comment]
Manual in

- English
- French
- German
- Italian
