### ISSUE TITLE
SlipSpeed (2020)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1157]
https://voxel.itch.io/slipspeed

_"Available for DOS and WINDOWS 95 PCs, it is the far future racing event of the 1990s! Race your Slip-craft through 16 exciting locations, from famous EARTH CITIES to the exotic distant dimensional rifts of FARFIELDS in this intense single player drifting speedfest!
This SHAREWARE title is available for free download, with the full game available for a modest fee!"_

![BpfcGv](https://user-images.githubusercontent.com/67441153/87209078-fd9c6680-c310-11ea-99b1-c7b50c5ada53.gif)
![m6wTrs](https://user-images.githubusercontent.com/67441153/87209089-042ade00-c311-11ea-95e0-72161f882568.png)

**Comment by exoscoriae** [comment]
added
