### ISSUE TITLE
Championship Manager: End of Season Edition (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1159]
According to user note not cracked, codes found in extras

**Comment by Python-Exoproject** [comment]
[CMEXE.zip](https://github.com/exoscoriae/eXoDOS/files/5480962/CMEXE.zip)

Crack provided by Discord user Kudgel

**Comment by exoscoriae** [comment]
added

**Comment by Python-Exoproject** [comment]
The user note in run.bat can be removed now that its cracked

**Comment by exoscoriae** [comment]
note removed
