### ISSUE TITLE
Championship Manager (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1160]
According to user note not cracked, codes found in extras

**Comment by Python-Exoproject** [comment]
[EUROPE.zip](https://github.com/exoscoriae/eXoDOS/files/5475499/EUROPE.zip)

Working crack by discord user Kudgel

**Comment by exoscoriae** [comment]
added to next release and updater

**Comment by Python-Exoproject** [comment]
The user note in run.bat can be removed now that its cracked

**Comment by exoscoriae** [comment]
note removed
