### ISSUE TITLE
From Corner to Corner (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1161]
Zip contains the 1992 and 1993 releases, accessible via a user choice. The 1992 is cracked, the 1993 is not. Codes are available in extras.

**Comment by amazzanti** [comment]
[corner57.zip](https://github.com/exoscoriae/eXoDOS/files/13762350/corner57.zip)

1993 version crack

**Comment by exoscoriae** [comment]
awesome!
