### ISSUE TITLE
Lords of the Realm (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1165]
There is a user note saying that you couldnt get sound working on the CD version but when I ran it I had sound. I also went back and reran setup to test all sound choices. All work, Sound Blaster even has the "Welcome to Lords of the Realm" speech when entering the menu.

**Comment by exoscoriae** [comment]
ah, that is because I have done totally new installs since then and forgot to remove the user note. good find

**Comment by exoscoriae** [comment]
good find

**Comment by Python-Exoproject** [comment]
I think you may have missed the bit above where I said that the CD SoundBlaster setting has limited speech, unique amongst all the floppy and CD sound choices. To save you time I have setup the necessary files in the archive below. The CD MT32 and SC dont add anything the floppy version doesnt have sound wise but I figured if I was doing one I might as well do them all. As usual no hard feelings if you dont want to implement, I just figured speech, even a little, is worth setting up.

[lordrealm.zip](https://github.com/exoscoriae/eXoDOS/files/4913921/lordrealm.zip)

**Comment by exoscoriae** [comment]
I don't see anything in your initial post stating that soundblaster has limited speech. You said it did have speech. It wasn't clear to me you meant that it didn't before.

**Comment by exoscoriae** [comment]
added it

**Comment by Python-Exoproject** [comment]
Apologies if I wasnt clear. I have had a look at the version you have synced and I think you forgot to remove the plain "CD" choice from the user menu. As it stands it would just load whatever CD sound choice had last been selected set to a mididevice=fluidsynth. I.E. If I had previously chosen "CD with MT32" and then next load chosen "CD" it would load the MT32 settings file as it is what was last copied into the main folder and use fluidsynth.

Also to clarify it is only the CD with Soundblaster option that gives the limited speech samples, not the CD with MT32 or CD with SC55. The user note you added says all the CD sound options have the speech samples.

**Comment by exoscoriae** [comment]
fixed

**Comment by XavierVelo** [comment]
I have found patch for Lords of The Realm (1994) CD-ROM version 1.03 (it is 1.02 in eXoDOS 5.1). "It contains fixes for all known problems with the game, including disappearing armies."
[lotr103c.zip](https://github.com/exoscoriae/eXoDOS/files/6667418/lotr103c.zip)

**Comment by exoscoriae** [comment]
patched
