### ISSUE TITLE
Theatre of Death (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1171]
In run.bat this section:

:SC55
CONFIG -set "mididevice=fluidsynth"
cls
@echo off
echo.
echo For Creative SoundBlaster music,
echo when asked to choose your Sound Support,
echo choose option 6. Roland SCC1 / SoundBlaster.

Should mention "For Roland Sound Canvas music", not SoundBlaster.

**Comment by exoscoriae** [comment]
fixed
