### ISSUE TITLE
Tennis Cup 2 (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1175]
I cannot select the adlib sound in the pre-menu.
But the intro plays the adlib sound. Weird

**Comment by exoscoriae** [comment]
while the behavior is a bit strange, the game game functions well. The only way to get it to play w/ PC speaker is to disable to soundblaster in the conf. This would require a double selection menu. Once in a batch file to ask what you want and then again when you start the game.

But we don't go out of our way explicitly for pc speaker on other games, so I don't think we ought to here.
