### ISSUE TITLE
The Games: Summer Challenge (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1177]
The game asks for a coded wheel number when I select an event, and back to dos.

**Comment by exoscoriae** [comment]
cracked

**Comment by Python-Exoproject** [comment]
Reopened for same reason as https://github.com/exoscoriae/eXoDOS/issues/1193#issuecomment-801029987 in issue #1193, see there for further information

**Comment by exoscoriae** [comment]
if we have no codewheel, then the game is unplayable if we uncrack it. that seems worse than have it work, but just be more difficult than it should be

**Comment by TimberlAndRE-de** [comment]
found the code wheel (see #3149 )

**Comment by exoscoriae** [comment]
remove crack
