### ISSUE TITLE
Atlantis - The Lost Tales (1997)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1201]
pages 1 and 2 (and maybe coverpage) are missing

**Comment by TimberlAndRE-de** [comment]
found full version with all missing pages (thx to old-games.ru)

**Comment by TimberlAndRE-de** [comment]
Eulisker noted:

Manual is for the Win95 Version

**Comment by SmilingSpectre** [comment]
Try this (but it's not match Windows manual... at all). https://www.old-games.ru/game/download/get.php?fileid=28618&modal=1

**Comment by Eulisker** [comment]
I put both into the github folder. I would set the booklet as manual and the story manual as an extra and delete the DVD manual.
Maybe someone can get rid of the watermarks.

**Comment by exoscoriae** [comment]
done

**Comment by Eulisker** [comment]
I scanned the manual. The current one has watermarks.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
