### ISSUE TITLE
Ishar 3 - The Seven Gates of Infinity (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1211]
quality-upgrade, added cover from mobygames

**Comment by TimberlAndRE-de** [comment]
Eulisker found

- [ ] manual (scanned version, much better quality)

added to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
Manual in

- English
- German
