### ISSUE TITLE
Ishar - Legend of the Fortress (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1212]
coverpage is missing

found one from HOL but with watermark:
![Ishar__Legend_Of_The_Fortress_-_Misc_screenshot_n°1](https://user-images.githubusercontent.com/67441153/87285709-1dda4a00-c4f8-11ea-8158-f7d3fafd51b8.jpg)

**Comment by bigjim161** [comment]
Found a manual with cover and no watermark 
https://www.mocagh.org/miscgame/ishar-manual.pdf

**Comment by TimberlAndRE-de** [comment]
great, thx @bigjim161 
i uploaded it to the github folder
@exoscoriae the current manual without frontcover has some technical information that the "real" manual has not, maybe keep the current one as an extra reference card or alternate manual?

**Comment by exoscoriae** [comment]
replaced. didn't keep old manual
