### ISSUE TITLE
Leisure Suit Larry 6 - Shape Up or Slip Out (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1216]
maybe coverpage is missing?

**Comment by TimberlAndRE-de** [comment]
no, found proof:

![grafik](https://user-images.githubusercontent.com/67441153/87291858-436b5180-c500-11ea-86f0-0f92d2a32a09.png)

**Comment by TimberlAndRE-de** [comment]
found "Sierra Game Manual" as an extra (see #1218)

**Comment by Eulisker** [comment]
I found a better scan of the

- [ ] manual

Added to the github folder.
