### ISSUE TITLE
Sid Meier's Colonization (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1217]
I removed the Tech Supplement and Player Aid Cards from the manual. We dont have the Tech Supplement so ive upped that as an extra, and the Player Aid Cards are better quality text (though faded out icon images)

**Comment by Eulisker** [comment]
found

- [ ] Player Aid Card

sacnned version. Current one is digital. Added to the github folder

**Comment by exoscoriae** [comment]
digital version looks like a master copy.

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Official Strategy Guide

added to the github folder

**Comment by exoscoriae** [comment]
added
