### ISSUE TITLE
Leisure Suit Larry 6 - Shape Up or Slip Out (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1218]
found "Sierra Game Manual" as an extra
(it was part of the big box packaging, see #1216 )

**Comment by TimberlAndRE-de** [comment]
discord user ArkhangelAzrael found an extra:
Game Design Document

(https://allowe.com/games/game-designs.html)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found a better scan of the 

- [ ] Hintbook

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
