### ISSUE TITLE
MechWarrior (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1220]
scanned with ocr (maybe HOTU?) - should be replaced by real scan or digital manual

proof images for manuals:

![20171111_112450](https://user-images.githubusercontent.com/67441153/87294512-318bad80-c504-11ea-9435-9df88cc5b6b2.jpg)
![20171111_112458](https://user-images.githubusercontent.com/67441153/87294497-2df82680-c504-11ea-85b2-0421038e327d.jpg)
![20171111_112519](https://user-images.githubusercontent.com/67441153/87294500-2e90bd00-c504-11ea-8d96-f27ed978a604.jpg)
![20171111_112532](https://user-images.githubusercontent.com/67441153/87294503-2fc1ea00-c504-11ea-9771-c9a0e03648bc.jpg)
![20171111_112549](https://user-images.githubusercontent.com/67441153/87294504-2fc1ea00-c504-11ea-9df9-ec595bd21752.jpg)
![20171111_112618](https://user-images.githubusercontent.com/67441153/87294507-305a8080-c504-11ea-963d-116ab241369d.jpg)

**Comment by SmilingSpectre** [comment]
Uploaded.

**Comment by TimberlAndRE-de** [comment]
added to the github folder
