### ISSUE TITLE
Ravenloft - Stone Prophet (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1224]
added coverpage to manual
but still original manual has to be found for a real scan or as proof that the current (digital) manual is complete

**Comment by exoscoriae** [comment]
replaced. moved back to working

**Comment by TimberlAndRE-de** [comment]
Eulisker found

- [ ] manual (digital but current one is clue book)

added to the github folder

**Comment by exoscoriae** [comment]
I don't know what you guys are talking about. This is *identical* to the version we have right now, ecept this is digitally cleaned up and ours is an actual scan. But they have the exact same cover, pages, etc...

**Comment by exoscoriae** [comment]
ok. replaced our clue book (and fixed the cover).
then used this as the new rule book \ manual
