### ISSUE TITLE
Reach for the Skies (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1225]
found proof that real manual exists, should be replaced (current is selfmade or typed down):

![grafik](https://user-images.githubusercontent.com/67441153/87298534-a7931300-c50a-11ea-99a7-b16c2460027e.png)

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] manual (scan, not a perfect one but ok)

**Comment by exoscoriae** [comment]
replaced
