### ISSUE TITLE
Austerlitz (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#123]
it's a reference-card  not a manual

**Comment by SmilingSpectre** [comment]
Uploaded.

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre 
great, thx. i copied it over to the github-folder and set it to "In Progress" so eXo can add it
the reference card (current manual) can be switched to extras

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre @exoscoriae 
i saw that the Game "Austerlitz 1805 (1989)" has the same manual. it seems it was added to the wrong game then?
so the one for "Austerlitz 1805 (1989)" is missing, i'll open an issue for it

**Comment by exoscoriae** [comment]
added austerliz manual.

no idea what you are on about in regards to the Austerlitz 1805 (1989) manual. Looks right to me. Are you checking the WIP?
