### ISSUE TITLE
Jungle Strike (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1236]
Watermark removed

**Comment by exoscoriae** [comment]
please move to "in progress"

**Comment by TimberlAndRE-de** [comment]
discord user wysiwyg found an alternate manual:
scan of the original one with further informations of floppy and sound installation
I suggest to keep it as an alternate manual in extras
(added to the github)

**Comment by exoscoriae** [comment]
added
