### ISSUE TITLE
Dark Half, The (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1247]
User ArkhangelAzrael posted in discord:

"is it by design that the Dark Half uses a modified cd version when the game is a floopy game? We can get the original disks and install folders here: https://www.old-games.ru/game/download/4733.html"

While I have no idea what hes talking about with us using a CD version I did have a look at the game and noticed that the oldgames version has a complete "Drivers" folder and using setsound I can choose Sound Canvas and it sets up a specific Sound Canvas driver. From what I can see of our current version the Sound Canvas user choice is using the MT32 driver.

I also think the game is running to fast once you get into the gameplay.

**Comment by exoscoriae** [comment]
used the version you found and changed the way drivers are loaded
