### ISSUE TITLE
Mie (1989)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1249]
Genre: | Fighting
Developer: | Softstar Entertainment
Publisher: | DOMO
Released: | 1989
Platform: | DOS
![image](https://user-images.githubusercontent.com/67555221/87331203-e7252380-c539-11ea-995d-3ab9f1ba9cd9.png)
https://www.old-games.ru/game/screenshots/9994.html
https://www.old-games.ru/game/download/get.php?fileid=27452&modal=1
Also added to the "Game Submission" folder

**Comment by exoscoriae** [comment]
added
