### ISSUE TITLE
Total Knockout: Championship Female Boxing (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1250]
In the setup.exe menu, Plr 2 uses the "capslock" key for "Block Hi". Is it possible to define the "tab" key for "Block Hi" (instead of the "capslock" key)?
![image](https://user-images.githubusercontent.com/67555221/87353304-cae6ae00-c55c-11ea-8a38-69b9b067b076.png)

**Comment by exoscoriae** [comment]
done
