### ISSUE TITLE
Syndicate Wars (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1252]
Found an extra (installation & troubleshooting guide)
It explains how to install game under DOS and how to make net game for 8 players (IPX). Also contains detailed keyboard shortcuts and FAQ.

**Comment by Eulisker** [comment]
I found the 

- [ ] Official Strategy Guide

The scan is very bad but its better then nothing.
Added to the github folder.

**Comment by exoscoriae** [comment]
this doesn't belong in networking @Eulisker

**Comment by exoscoriae** [comment]
this probably shouldn't have been added to a networking\ip bug. added the guide for now.
