### ISSUE TITLE
D!Zone 150 (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1257]
@exoscoriae D!Zone 1-3 are included, is there a reason, D!Zone 150 is not?
I don't know these addon packages, maybe it's just an alternate release for D!Zone 1-3 ? On [Mobygames](https://www.mobygames.com/game/dos/dzone-150) it's listed as an own entry and the masterlist says it's missing...

anyways, here is the download link: ;)
[myabandonware download](https://www.myabandonware.com/game/d-zone-150-cg7)
[3D Shooter Legends ISO](https://legendsworld.net/shooter/game/1118)

**Comment by exoscoriae** [comment]
added
