### ISSUE TITLE
Installer downloader

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1259]
I have discovered a flaw in the bat logic of install.bat in the part to do with checking if a download is already running. The actual section that does that is fine and it stops the new download from starting as intended, however the line:

if exist DOWNLOAD rd DOWNLOAD /S /Q

is executed way up at the top of the bat and therefore running the second install wipes the current downloads progress before you even get to checking if aria is already running.

**Comment by exoscoriae** [comment]
ok, want to give this a shot? Seems the best way to handle this is to identify the download folder exists and then warn the user and give them the option of how to continue.

I don't know it can be automated because we have to know whether or not the download folder exists because a download is in progress or if it is an unfinished\interrupted download.

[install.zip](https://github.com/exoscoriae/eXoDOS/files/4968168/install.zip)

**Comment by exoscoriae** [comment]
solved and fixed

**Comment by Python-Exoproject** [comment]
Sorry exo but I did a test and got an issue with the size not showing when its asking if I want to download the game. When I continued anyway I then got the next error. Upon using pauses to find the break I discovered its at the point shown in the third image. Lastly, when I got the "error downloading game" message I continued and instead of exiting the bat it continued with asking me for aspect ratio as if the download had succeeded.

![image](https://user-images.githubusercontent.com/67406191/88389991-e6727400-cdfa-11ea-9e3f-45d0ef3b1b22.png)
![image](https://user-images.githubusercontent.com/67406191/88390120-1b7ec680-cdfb-11ea-8ef7-4708e1c1a531.png)
![image](https://user-images.githubusercontent.com/67406191/88390457-b11a5600-cdfb-11ea-82c3-5b84bdea97b7.png)

**Comment by exoscoriae** [comment]
I'm not having this problem. see staff channel for discussion

**Comment by Python-Exoproject** [comment]
Repeat of my response in staff channel:

Your correct. I did sync but something must have happened as usual with it. Deleted the index and let it sync again, now it works fine. Sorry for the alarm.

I think im still correct about the error message though. If an error does occur instead of going to exit it continues with the aspect ratio setup as if it downloaded without error

**Comment by exoscoriae** [comment]
latest version appears to solve all issues
