### ISSUE TITLE
Davis Cup Complete Tennis (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1266]
This games uses the "capslock" key for plr 2.  It has to be launched with  "Daum svn dosbox".

**Comment by exoscoriae** [comment]
switched to daum

**Comment by Python-Exoproject** [comment]
Now that its Daum it needs "-nomenu" option added in launch bat and "direct3d" set as output.

**Comment by exoscoriae** [comment]
thanks for the reminder. done
