### ISSUE TITLE
Frogger (1983)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1270]
Better with machine=cga as it gives blue water in top half of screen as it should.

Also I couldnt find the control to move frogger right, only up (a), down (z), and left (')

**Comment by SmilingSpectre** [comment]
I bet it's '.' Because it have _arrows_, you know!
...
But I cannot check it now. :| Internet full of _different_ frogger, and the-eye is down. Sorry, later I'll check it.

**Comment by exoscoriae** [comment]
manual shows the right key is "`", the button way up top left on your keyboard next to the number 1.

also says keys can be rebound, but I'm still working on that part.

**Comment by exoscoriae** [comment]
unfortunately the keys have to be re-binded each time. So I'll just set up a mapper.

**Comment by exoscoriae** [comment]
ok. mapped.

also, f6 changes background colors.
f10 at the main screen (before you hit a key to play, you can access the options screen with f10)
