### ISSUE TITLE
American Challenge A Sailing Simulation, The (1986).pdf

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1276]
not a good scan
handwritten note on page 1
pages 2 4 12 are missing (and maybe the coverpage)

**Comment by emanuelepulcidoria** [comment]
@TimberlAndRE-de,
I found this page while looking for the manual of this sailing simulator. From your comments it looks like you have one or you have seen one. Do you know where it can be found or do you have a copy to upload here in some way. 
Your help will be very much appreciated.

**Comment by TimberlAndRE-de** [comment]
@emanuelepulcidoria 
Yes, we have a pdf version with the problems above
It's part of the eXoDOS Collection (www.retro-exo.com)

Here is the manual:
[American Challenge A Sailing Simulation, The (1986).pdf](https://github.com/exoscoriae/eXoDOS/files/6049245/American.Challenge.A.Sailing.Simulation.The.1986.pdf)

Please tell me when you downloaded it, the I can delete it because github has not a lot of space for free ;-)

**Comment by emanuelepulcidoria** [comment]
Thank you very much, I downloaded it.

**Comment by emanuelepulcidoria** [comment]
Do you have by any chance the Two Computer Races booklet mentioned at page 8?

**Comment by TimberlAndRE-de** [comment]
@emanuelepulcidoria 
Unfortunately not
But if you find it, please let me know 👍🏻

**Comment by Eulisker** [comment]
I found a good scan of the

- [ ] Manual

Added to the github folder.

**Comment by emanuelepulcidoria** [comment]
@Eulisker sorry I am not familiar with GitHub folders....where can I find the folder and the file itself?

**Comment by exoscoriae** [comment]
added
