### ISSUE TITLE
Chip 'N Dale Rescue Rangers - The Adventures in Nimnul's Castle (1990).pdf

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1282]
little bit blurry
looks more like a reference card but no proof for real manual is found yet

**Comment by TimberlAndRE-de** [comment]
wyswiyg found

- [ ] manual (quality upgrade)

and proof, that this is the real manual -> https://www.ebay.com/itm/195604833884-

**Comment by exoscoriae** [comment]
replaced
