### ISSUE TITLE
MicroLeague Baseball (1984)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1305]
pages 1 and 2 are boxfront and back - can be deleted
pages 57 - 60 are pictures of the disks - can be deleted

pages 3 - 16 are the Managers Rulebook
pages 17 - 36 are the Team Rosters and Highlights
pages 37 - 52 are the General Managers Owners Disk Instruction Manual
pages 53 - 56 are a reference card

**Comment by Eulisker** [comment]
I cut out everything of the 

- [ ]  Manual

See #3011 

Thanks to discord user remowilliams for scanning.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
