### ISSUE TITLE
Balance of Power The 1990 Edition (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#131]
seems there are images missing because there are several [IMAGE] tags in the doc
i think it's self-made or at least typed-down from the original manual

**Comment by SmilingSpectre** [comment]
Uploaded.

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre 
Thank you, i copied it to the github folder and assigned it to eXo

**Comment by exoscoriae** [comment]
replaced
