### ISSUE TITLE
Wargame Construction Set (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1329]
according to chapter A. Loading it's for the atari version of the game

**Comment by bigjim161** [comment]
the manual is the same for all computers, only the reference card is different ex with the c64 version http://www.c64sets.com/wargame_construction_set.html

**Comment by SmilingSpectre** [comment]
It's the same... Ah, bigjim answered it already. :)

**Comment by TimberlAndRE-de** [comment]
great!
@exoscoriae 
-> the current one is much nicer and seems to be the original one but it's missing the ibm reference card
-> the version from Sprectre is from the Roadwar-collection, not the quality of current one but with the reference card informations

either keep Spectres version as alternate manual as an extra or just keep the extracted pages of the reference card as an extra (I uploaded both into the github folder so you can decide)

**Comment by exoscoriae** [comment]
added reference cards

**Comment by bigjim161** [comment]
I found 2 reference cards (quality upgrade).
We can add them as extras and keep the current refcard (the first page contains information not included in the 2 red cards.

**Comment by exoscoriae** [comment]
existing info is more complete

**Comment by Eulisker** [comment]
I found a better looking

- [ ] manual

Added to the github folder.
