### ISSUE TITLE
Nuclear Bowls (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1336]
![image](https://user-images.githubusercontent.com/67406191/88058753-42dd5580-cba7-11ea-9528-395c0ef4269e.png)

As this image shows there are filenames with characters in the archive that do not extract correctly. Game loads, but with these files not called what they should I would expect an issue further into gameplay.

The game is also capable of CGA composite if use ECE, machine=cga, and add a user note to press f12 if wish to use composite

**Comment by exoscoriae** [comment]
TDC version has changed the characters to standard "n"... odd. I switched to that version for now.  Attempts to rename and fix the cyrillic characters didn't work. dosbox doesn't support them anyways.

**Comment by Python-Exoproject** [comment]
Still needs machine=cga

**Comment by exoscoriae** [comment]
got it
