### ISSUE TITLE
Frogger II - ThreeeDeep! (1984)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1341]
Not sure how but this game detects the composite mode so that you dont need to press f12. Due to this the user message is not needed and may confuse the issue. Composite is such an improvement though over the in game "color hi res monitor" option that it might be worth just changing the user note to suggest choosing the composite option in game instead of removing it altogether.

**Comment by exoscoriae** [comment]
removed message. I'll let the user play around with what they prefer.
