### ISSUE TITLE
M.U.L.E. (1985)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1343]
There is a message when you launch this game that says you need to press f12 to activate composite mode, but it doesn't work.
Here is a video of M.U.L.E. for the IBM PC when played on a composite CGA monitor, where it takes advantage of all 16 colors (as opposed to only 4 colors when run on an RGB monitor).
https://www.youtube.com/watch?v=mrvwjOj09b0

If needed, this experimental patch can be downloaded here:  https://www.vogons.org/viewtopic.php?f=41&t=12319&start=680

**Comment by Python-Exoproject** [comment]
This is what im getting. Current version seems to be working for me, top image is mule without f12 pressed (straight cga), and the bottom image is with f12 pressed (cga composite). Its using ECE which has the cga composite patch built in, the New Rising Sun patch you directed to is the same but also enables PCJR composite which we use in a couple of games (seven cities of gold & below the root)

![Untitled](https://user-images.githubusercontent.com/67406191/88164421-74adf500-cc57-11ea-8051-ab9aa1f00448.png)

**Comment by bigjim161** [comment]
mule without f12 pressed and with f12 pressed  
![image](https://user-images.githubusercontent.com/67555221/88195515-6c968b00-cc40-11ea-84a5-78c9a171c8a6.png)

**Comment by exoscoriae** [comment]
current build works fine for me. Is there any benefit to the pc jr composite mode?
I'd prefer to not have to use a whole new version of dosbox if not necessary.

**Comment by Python-Exoproject** [comment]
No benefit to pcjr for this game, just explaining to bigjim that the only difference for composite between ECE and the dosbox he linked to was that the one he linked also does pcjr composite. No idea why its not working for him

**Comment by exoscoriae** [comment]
/shrug

No clue what to do with this then.
