### ISSUE TITLE
Discworld (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1351]
@SmilingSpectre found a guide as an extra

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
discord user ArkhangelAzrael found an errata page
added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I scanned

- [ ] Hintbook Ad

Added to the github folder.
