### ISSUE TITLE
John Madden Football (1989)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1355]
Found 2 extra:
-John Madden Football defensive playbook
-John Madden Football offensive playbook

proof 
![image](https://user-images.githubusercontent.com/67555221/88361086-2c3a2880-cd78-11ea-8c77-41ba47f41d9f.png)

**Comment by TimberlAndRE-de** [comment]
@bigjim161 i think they're already included (in the WIP) ?

but your proof picture let me find a copy protection wheel, uploaded to the github folder

**Comment by exoscoriae** [comment]
submitted for processing.

**Comment by exoscoriae** [comment]
added
