### ISSUE TITLE
I, Damiano - The Wizard of Partestrada (1985)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1357]
Can do composite. Set ECE, machine=cga, and add user message to press f12 if wish to use composite.

Although the result is not great for this game (and I usually dont bother mentioning games that look no different or terrible in composite), I decided to request composite anyway as its not listed as a composite game in Moby. The only mention I can find online is a brief one liner in vogons and a small mention on nerdly blog, so I figured to add it.

**Comment by exoscoriae** [comment]
changes made. thx
