### ISSUE TITLE
Links LS 1997 (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1358]
User vincehor has noted in bugreports channel that links is running with a black border. Tested and confirmed during gameplay, though menu doesnt share the issue. Fixed with ECE and openglnb. The game will then retest the video mode and set to 800x600 so you need to reset it to 1024 16.7 million colours in game.

As a side note the user note on start is broken up in the wrong places and needs reformatting so that there arent words broken in half etc, and the word "prompted" is currently spelt "promptred"

**Comment by exoscoriae** [comment]
seems to only affect full screen mode.

Applied fixes for that mode.
