### ISSUE TITLE
One Step Beyond (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1362]
@SmilingSpectre found an installation guide (en-fr-de) as an extra
(it has not removable watermark "Le Vieux Manuel")

**Comment by exoscoriae** [comment]
removed embedded links

**Comment by bigjim161** [comment]
I removed the watermak on the Installation Guide. The german and the italian parts are missing.

**Comment by exoscoriae** [comment]
replaced
