### ISSUE TITLE
Sid Meier's Railroad Tycoon Deluxe (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1365]
extracted technical supplement from the current manual to be added as an extra (since manual is going to be replaced by quality upgrade in #546 
added to the github folder

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] aid cards (quality upgrade)

added to the github folder

**Comment by exoscoriae** [comment]
replaced
