### ISSUE TITLE
Destroyer (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1372]
@SmilingSpectre found quality upgrade

**Comment by TimberlAndRE-de** [comment]
@exoscoriae What do you think about original scanned vs. reworked manuals?
I found a scanned one for Destroyer
The current one was scanned but afterwards converted into digital manual

**Comment by exoscoriae** [comment]
i went with the new one because I liked the side by side pages with the ship diagrams
