### ISSUE TITLE
Bard's Tale 3, The - Thief Of Fate (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1377]
@SmilingSpectre found an alternate manual with higher resolution, but it's missing "The Bard's Warning" on page 2
since the current one has no issues (except for lower resolution), i suggest to keep the current one.
uploaded to the github to let you decide, eXo

**Comment by exoscoriae** [comment]
added the missing warning page to the better manual

**Comment by Eulisker** [comment]
I found a better looking version of the

- [ ] manual

including The Bard's Warning.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
