### ISSUE TITLE
Pack Regalo: Gun Stick (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1395]
as mentioned in [discord](https://discordapp.com/channels/454359114601201666/489778086792003604/738620571105099837), found the image on [old-games.ru](https://www.old-games.ru/game/6740.html)

(added to the github folder)

**Comment by exoscoriae** [comment]
added.... however two games were already in, so there is some duplication now. Game required a specific version of dosbox. I used the same from mike Gunner.
