### ISSUE TITLE
Freddy's Rescue Roundup (1984)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1397]
This one is annoying. It has better sound with pcjr, but better graphics with CGA composite. New Rising Suns PCJR composite dosbox build works but gives wrong colours. So choices are:

1. Leave as is with PCJR sound and dont bother with composite mode (loss of better graphics)
2. Switch to CGA and enable composite mode (loss of better sound)
3. Switch to NRS dosbox build and get PCJR sound with composite graphics (colours are off)

I think I tend to lean towards option 2 as there isnt much sound or option 3 and live with the colours until they release a more colour correct PCJR patch (which is being slowly worked on from what I've read)

**Comment by exoscoriae** [comment]
made a split launcher for both

**Comment by Python-Exoproject** [comment]
All good for now. Ill add this to the low priority, on hold pile for keeping track of if the PCJR composite colour emulation ever improves (There is talk about it on VOGONS).

**Comment by Python-Exoproject** [comment]
Solved during recent composite review
