### ISSUE TITLE
Multiple games with same issue

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1398]
These composite capable games:

Gertrude's Secrets (1986)
Gertrude's Puzzles (1984)
Robot Odyssey (1985)
Rocky's Boots (1985)
Think Quick! (1987)

all use the same engine. We have them set up as PCJR as that is the only way the games seem to accept the necessary holding of shift+movement to move slowly. Problem is, as with a couple of other games, the PCJR colour emulation is not great. As we need PCJR for game functionality our choices are to:

1. Leave it as it currently is, 
2. get CGA mode working with shift+movement, 
3. Switch over to NRS composite dosbox to enable composite ability and just live with wrong colours. 

I lean towards 3 as there is an update to the PCJR colour palette being slowly worked on. If it ever gets released we can fix the colour issue then, in the mean time at least its enabled.

**Comment by exoscoriae** [comment]
found solution. use the numeric pad. allows shift to work properly in cga mode. added note to all games
