### ISSUE TITLE
Gettysburg - The Turning Point (1986)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1399]
Composite capable. Switch to ECE, machine=cga, user note to press f12 to switch to composite mode if they wish.

Further point for the user note is that if they want to use composite the need to select it by pressing "g" on the first screen.

**Comment by exoscoriae** [comment]
enabled

**Comment by Python-Exoproject** [comment]
Typo in user comment:  "...you iwsh to use..."

**Comment by exoscoriae** [comment]
fixed
