### ISSUE TITLE
J-Bird (1983)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1402]
This game is capable of composite. The copy we have is broken though and doesnt give choice for selecting RGB or composite. Spectre has found a working copy which I attach here. Will need the usual ECE, machine=cga, and user note about f12

[J-Bird_DC_1983Orion_Software_Inc._Action.zip](https://github.com/exoscoriae/eXoDOS/files/5007958/J-Bird_DC_1983Orion_Software_Inc._Action.zip)

**Comment by exoscoriae** [comment]
enabled and replaced
