### ISSUE TITLE
Battle of Antietam (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#141]
pages 1+2 are the boxfront and back images
pages 3-34 are the manual
pages 35+36 are a map and a reference card on the back
page 37 is an image of the disk

should be split and added as extras

**Comment by Eulisker** [comment]
I cut the extraneous stuff out and added the manual to github. See #3008

**Comment by exoscoriae** [comment]
replaced
