### ISSUE TITLE
Kristal, The (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1416]
@bigjim161 found a reference card as an extra (needed since there is no ibm/pc manual)

**Comment by Eulisker** [comment]
I found 

- [ ] Registration card
- [ ] Offer Card
- [ ] Cinemaware Ticket

They are for the Amiga version but at least the Registration card and Ticket are present in the PC Version. See the photo. I am pretty sure the offer card was part of the PC Release as well (multiple platforms are mentioned on it.)

![s-l1600](https://user-images.githubusercontent.com/81642149/147787383-1d2f2a95-a1ce-41e9-b658-0a31556f5094.jpg)

Added to the github folder.

**Comment by exoscoriae** [comment]
added
