### ISSUE TITLE
Overkill (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1417]
Was checking if the music worked on this one and noticed that there was no music in game. When I went to set the sound config myself the config program crashed. This issue is probably linked to #35 and the game is looking for CD Audio, but as our run.bat is set up was it working at some point and now its not? If it is CD Audio only then we might as well remove the run.bat sound choices as they dont do anything.

**Comment by exoscoriae** [comment]
you can run setsound from the drivers folder just fine. That is where I set up the current options. Until we get a CD, I don't see much point in changing much of anything except maybe just bypassing and defaulting to sb16
