### ISSUE TITLE
Loom (1990) 

### ISSUE THREAD

**Issue by Jono007** [exoscoriae/eXoDOS#1422]
Audio rip of the Audio Drama from the original cassette tape that came in the box (IBM release), shown here: https://pbs.twimg.com/media/DUCSTsbWAAArDMn?format=jpg&name=large
The Audio Drama has some good (useful?) backstory for the game and I believe it is worth including. You have the intro music as an Extra already, but this is something different.

**Comment by TimberlAndRE-de** [comment]
wow, that's a cool thing!

i'll add the proof-picture here for the case the link goes down:
![grafik](https://user-images.githubusercontent.com/67441153/89773310-f204b100-db03-11ea-9d9a-3f1bc62b9f00.png)

**Comment by exoscoriae** [comment]
i have that box set actually, including the audio tape. I was under the impression we already had it in the set... I'm surprised it wasn't.

**Comment by Jono007** [comment]
> i have that box set actually, including the audio tape. I was under the impression we already had it in the set... I'm surprised it wasn't.

I might have been looking at an out-of-date version. Can I get access to your WIP?

**Comment by TimberlAndRE-de** [comment]
discord user wysiwyg found an order card for roland-upgrade as an extra, added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
Glurak found

- [ ] Hint Book - encoded (restored version by Laserschwert) - quality upgrade

**Comment by Eulisker** [comment]
I made a version with visible copy protection of the 

- [ ] Book of Patterns

uploaded to the github folder.
