### ISSUE TITLE
4D Sports Tennis (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1423]
i found a sheet of copy protection codes as extra
has watermark "Le Vieux Manuel"

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual for "Compaq Grand Slam Cup", it's a version of 4D Sports Tennis that was included with Compaq PCs. The Game is identical to 4D Sports Tennis except for digitized photos of real-world courts that make up the Grand Slam (Wimbledon, US Open, and French Open) as well as the trophies. It can be found here: https://www.myabandonware.com/game/compaq-grand-slam-cup-1d8

could be added as an extra,
added to the github folder

**Comment by exoscoriae** [comment]
added as extra to 4d sports tennis
