### ISSUE TITLE
Bedlam (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1426]
has missing pages (other languages)

**Comment by TimberlAndRE-de** [comment]
i found a quality upgrade for the manual with all missing pages for other languages
unfortunatly it has a non-removable watermark "Le Vieux Manuels"

**Comment by TimberlAndRE-de** [comment]
@bigjim161 removed the non-removable watermark ;-) (thx!)
uploaded to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
Manual in 

- English
- German
- French
- Spanish
- Italian
- Dutch
