### ISSUE TITLE
Beneath a Steel Sky (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1427]
manual is for the amiga version

**Comment by TimberlAndRE-de** [comment]
i found an alternate manual for MS-DOS, uploaded to the github

also i found a second one from the soldout-release - maybe good as an extra?

**Comment by exoscoriae** [comment]
added MS-DOS one. I see no benefit to the sold out release version. I have a hatred for budget releases.
