### ISSUE TITLE
Elf (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1436]
i found "Keef Floyds Guide to Elf and Magic" as an extra

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found the technical supplement as an extra

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found 

- [ ] Instruction manual (more like a reference card) as an extra

added to the github folder

**Comment by exoscoriae** [comment]
replaced the existing manual. old one was for the wrong platforms.
