### ISSUE TITLE
Gunship 2000 (CD-ROM Edition) (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1440]
i found some extras:
- additional hints (txt only)
- Addon "Islands and Ice" manual
- an alternate version of the keyboard overlay:
it has two pages / two keyboard layouts but unfortunatly a non-removable watermark
but since it is more complete, i think it should be replaced (or at least tried to crack the copy protection to copy second page over to the other version?)

**Comment by exoscoriae** [comment]
rejected overlay. added everything else

**Comment by TimberlAndRE-de** [comment]
discord user Xavier_Velo found a 
- [ ] better version of the addon-manual (current one is corrupt on some pages)
- [ ] copy protection code sheet 

added to the github folder

**Comment by exoscoriae** [comment]
added/replaced

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre noted on discord that the addon manual is cut or incomplete
The copy protection sheets are missing

**Comment by Eulisker** [comment]
The current technical supplement is a digital version of the full manual. I found the 

- [ ] Technical Supplement

Thanks to discord user remowilliams for scanning.

Added to the github folder.

**Comment by exoscoriae** [comment]
added
