### ISSUE TITLE
Murders in Venice (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1449]
i found a collection document of the items that were in the big box as hints for the game

proof:
![grafik](https://user-images.githubusercontent.com/67441153/89313517-e08d5600-d678-11ea-90a3-169825c7cfb1.png)
![grafik](https://user-images.githubusercontent.com/67441153/89313530-e5520a00-d678-11ea-9a28-805b26ab3d2b.png)

**Comment by TimberlAndRE-de** [comment]
found

- [ ] registration card

added to the github folder

**Comment by exoscoriae** [comment]
added
