### ISSUE TITLE
Night Shift (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1450]
i found the manual

proof:
![grafik](https://user-images.githubusercontent.com/67441153/89313929-5a254400-d679-11ea-8b98-8b79435e07ab.png)

**Comment by TimberlAndRE-de** [comment]
unfortunatly i can't remove the watermark "Le Vieux Manuel"

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found a version without watermarks

- [ ] manual

added to the github folder

**Comment by exoscoriae** [comment]
replaced
