### ISSUE TITLE
Quivering, The (1998)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1454]
found a manual
it has non-removable watermark "Le Vieux Manuel"

**Comment by TimberlAndRE-de** [comment]
@bigjim161 maybe you can remove watermark on this one too?

**Comment by bigjim161** [comment]
I removed the watermark :)

**Comment by exoscoriae** [comment]
replaced. thank you @bigjim161 for all these great watermark removals.
