### ISSUE TITLE
Risky Woods (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1455]
found a copy protection codesheet for Risky Woods

**Comment by exoscoriae** [comment]
nothing in github for this

**Comment by TimberlAndRE-de** [comment]
found it again and uploaded it
but it's selfmade and i tested the game: no copy protection sheet needed (you just have to press space on the copy protection screen - maybe worth a note in the batch-file?)
so i guess the issue can be closed

**Comment by exoscoriae** [comment]
added
