### ISSUE TITLE
Versailles 1685 (1997)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1465]
found a map as an extra

it has watermark "Le Vieux Manuel"

**Comment by bigjim161** [comment]
I removed the watermark

**Comment by exoscoriae** [comment]
seems we already had the map with no water mark? went ahead and used this one as the file size was larger

**Comment by Eulisker** [comment]
I found a better looking 

- [ ] Map

and the 

- [ ] Booklet

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced\added
