### ISSUE TITLE
Alone in the Dark (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1470]
i found an official strategy guide for Alone in the Dark 1 and 2

<s>unfortunatly it has a non-removable watermark "replacementdocs"</s>

**Comment by SmilingSpectre** [comment]
Everything at replacementdocs recently are only ripoff of someone else's scans.

Uploaded.

**Comment by TimberlAndRE-de** [comment]
great! i replaced the file in the github folder and deleted "ok but..."

**Comment by Eulisker** [comment]
I found nicer looking versions of

- [ ] Clue Book
- [ ] Mini Book (Copy Protection)

added to the github folder.

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I found an even nicer version of

- [ ] Mini Book

Added to the github folder.
