### ISSUE TITLE
Azrael's Tear (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1472]
found extras:
- "Colin Scott's Letter"
- "Last Testament"
added to the github

**Quickstart-Guide is already included but the watermark needs to be removed**

proof:
![grafik](https://user-images.githubusercontent.com/67441153/89684883-92d45000-d8fb-11ea-943e-8f54eebd42da.png)

**Comment by exoscoriae** [comment]
added and removed watermark
