### ISSUE TITLE
Drascula - The Vampire Strikes Back (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1476]
i found a text-file... looks like a typed down version from a manual - but since we don't have a manual yet and this one contains some information about the game and controls, maybe it's worth to be added.

since all "releases" of this freeware game came as jewelcase (there was no boxed version) i doubt, real manual exists.
the text file probably is typed down from the booklet of the jewelcase

proof is still to be found, so the issue should stay open

**Comment by exoscoriae** [comment]
unlikely to have a real manual
