### ISSUE TITLE
Indiana Jones and the Last Crusade - The Action Game (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1478]
i found a manual

proof:
![Indiana Jones and the Last Crusade - The Action Game (1989)_proof1](https://user-images.githubusercontent.com/67441153/89688291-20b33980-d902-11ea-86ff-c902b617d4f7.jpg)
![Indiana Jones and the Last Crusade - The Action Game (1989)_proof2](https://user-images.githubusercontent.com/67441153/89688293-214bd000-d902-11ea-95d3-5f83c3414301.jpg)

**Comment by jphdelorme** [comment]
Indiana jones and last crusade problem hard drive B

**Comment by exoscoriae** [comment]
This is a github ticket for the games manual. But a bug report. 

That said, there is not enough information in this report to replicate the issue. 

Please refrain from posting bug reports here and please post them in the discord bug channel. That way they can be vetted by staff and, if necessary, a github ticket can be created.

**Comment by Eulisker** [comment]
Manual in

- English
- German
- French
- Italian
