### ISSUE TITLE
F29 Retaliator (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1481]
i found a readme file - it's definitly selfmade since it contains infos about setting up IPX in dosbox.
also i found the atari/amiga manual in good quality.

since some forum posts claim that you need to have the (missions-)manual to play the game since the informations are not IN the game, i suggest to keep either the selfmade (for dos) or the scanned version (for amiga/atari) to keep the game playable

keep the issue open after processing, maybe someone finds the scanned dos manual

**Comment by SmilingSpectre** [comment]
Moby has reference card and keyboard layout.
https://www.mobygames.com/images/covers/l/661615-f29-retaliator-dos-reference-card.jpg

https://www.mobygames.com/images/covers/l/661617-f29-retaliator-dos-extras.jpg

**Comment by exoscoriae** [comment]
taking atari\amiga manual over selfmade one
