### ISSUE TITLE
Golden Axe (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1487]
manual is missing

proof:
![Golden Axe (1990)_proof1](https://user-images.githubusercontent.com/67441153/89711348-13da2880-d98a-11ea-87d7-33e939b8e325.jpg)
![Golden Axe (1990)_proof2](https://user-images.githubusercontent.com/67441153/89711350-150b5580-d98a-11ea-8bef-d870fde18190.jpg)
![Golden Axe (1990)_proof3](https://user-images.githubusercontent.com/67441153/89711352-15a3ec00-d98a-11ea-9830-d5cb7b9c4c7a.jpg)

**Comment by TimberlAndRE-de** [comment]
found the

- [ ] IBM manual

added to the github folder

**Comment by exoscoriae** [comment]
replaced
