### ISSUE TITLE
Jones in the Fast Lane (Enhanced CD-ROM) (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1499]
i found an alternate version of the reference cards with all different colored pages from the disk release
(current one seems to be from the cd release)

proof:
![grafik](https://user-images.githubusercontent.com/67441153/89712774-5eac6e00-d993-11ea-9dc5-81df79664205.png)

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre found

- [ ] Reference Card (quality upgrade, higher resolution, cleaner images)

added to the github folder

**Comment by exoscoriae** [comment]
replaced
