### ISSUE TITLE
Better Dead Than Alien! (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#150]
it's a comic  not a manual - some pictures on google suggest that there is also a real manual  so this comic should become an extra

**Comment by SmilingSpectre** [comment]
Amiga/Atari manual uploaded. Unfortunately, no PC found.

**Comment by TimberlAndRE-de** [comment]
Thank you, @SmilingSpectre 
i copied it over to github folder
eXo, maybe better than having no manual? (current one - the comic - can be added as extra)

**Comment by exoscoriae** [comment]
replaced and moved comic to extras

**Comment by Eulisker** [comment]
Manual in 

- English
- German
- French
