### ISSUE TITLE
Lethal Weapon (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1501]
found readme, can be used as manual until real manual or proof for non-existance of real manual is found

eXo, please put the issue back to "To do" after processing

**Comment by exoscoriae** [comment]
added

**Comment by bigjim161** [comment]
I found:

- the real manual (It's manual for the ATARI ST/AMIGA
- and the IBM PC loading card (extra)
![image](https://user-images.githubusercontent.com/67555221/114281372-5171e280-9a3e-11eb-904a-ae65960e022d.png)

Added to the github folder

**Comment by exoscoriae** [comment]
added
