### ISSUE TITLE
Nobunaga's Ambition (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1506]
found a typed down manual version
could be used until the real manual is found

proof for real manual and extras:
![grafik](https://user-images.githubusercontent.com/67441153/89713136-01fe8280-d996-11ea-8d9e-1153dc36a128.png)
![grafik](https://user-images.githubusercontent.com/67441153/89713151-2f4b3080-d996-11ea-8eed-08aa74e42551.png)

**Comment by SmilingSpectre** [comment]
Uploaded.

**Comment by TimberlAndRE-de** [comment]
deleted the typed one in the github folder and uploaded the scanned version from @SmilingSpectre 👍
