### ISSUE TITLE
Shannara (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1508]
found a typed down version of the manual - but since we don't have the real one yet i suggest to add it

the issue should stay open until real manual scan is found:
![grafik](https://user-images.githubusercontent.com/67441153/89713386-b9e05f80-d997-11ea-9a51-e676b6a22832.png)

**Comment by SmilingSpectre** [comment]
Uploaded.

**Comment by TimberlAndRE-de** [comment]
cool, added to the github folder (and deleted the typed down version)
