### ISSUE TITLE
Magic Carpet 2 - The Netherworlds (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1517]
the manual is also in the extras folder (Magic Carpet 2 - The Netherworlds Manual.pdf) and can be deleted there

**Comment by Python-Exoproject** [comment]
@TimberlAndRE-de Noticed this on hold in the bugs issues, isnt this sort of thing usually handled in the manuals issues?

**Comment by TimberlAndRE-de** [comment]
Yep, moved ;-)
Thank you

**Comment by exoscoriae** [comment]
changed the labels from bugs to manuals.

I removed the watermark from the one in the folder.

removed the one from extras as well
