### ISSUE TITLE
Links The Challenge of Golf (1990) 

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1519]
found some extras:
- addon-Hyatt-Dorado-Beach-manual
- addon-Hyatt-Dorado-Beach-score-card
- addon-Troon-North-manual
- addon-Troon-North-score-card

**Comment by Eulisker** [comment]
I scanned

- [ ] Firestone Country Club Score Card
- [ ] Firestone Country Club Installation Manual
- [ ] Firestone Country Club Registry Card

Added to the github Folder
