### ISSUE TITLE
Around the World in 80 Days (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1541]
@SmilingSpectre found a manual from creative reader collection (with The Jungle Book and Peter Pan)

**Comment by SmilingSpectre** [comment]
All three are missing. :)

**Comment by TimberlAndRE-de** [comment]
Yes I mentioned them in all three issues ;-)

**Comment by bigjim161** [comment]
I found a manual dedicated only to 'Around the World in 80 Days'.

The current one concerns 2 other games 'The Jungle Book' and 'Peter Pan'

Added to the Github folder

**Comment by exoscoriae** [comment]
I don't see the manual in there.

**Comment by exoscoriae** [comment]
added. thanks for posting it @TimberlAndRE-de
