### ISSUE TITLE
Shannara (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1546]
@SmilingSpectre found a Sword of Shannara book that was in the initial Shannara box.

**Comment by SmilingSpectre** [comment]
Did you try to flip _back_? :)

For some reason, it numbered from page 1 - but my Adobe don't allow to clear this, so better pdf-wizard required.

**Comment by TimberlAndRE-de** [comment]
Yeah I already checked that it opens on first text page instead on coverpage ... I tried to save with acrobat but it makes no difference, seems the numbering needs to be changed... I'll try by printing it to a new PDF...
