### ISSUE TITLE
Secret Weapons of the Luftwaffe (CD-ROM) (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1557]
i found some extras (extracted from the current manual):

- battle maps
- Planes: DO-335-Pfeil
- Planes: HE-162-Volksjäger
- Planes: P-38-Lightning
- Planes: P-80-Shooting Star
- Reference Guide
- Code Wheel (can be converted to interactive wheel i hope)

proof:
![grafik](https://user-images.githubusercontent.com/67441153/89791540-c0034700-db23-11ea-9623-ac1b9106fa29.png)
![grafik](https://user-images.githubusercontent.com/67441153/89791520-ba0d6600-db23-11ea-8cab-29b0c9a8d6df.png)
![grafik](https://user-images.githubusercontent.com/67441153/89791593-cf829000-db23-11ea-9f3a-31603e02457a.png)

**Comment by exoscoriae** [comment]
submitted the files to generate the code wheel

**Comment by exoscoriae** [comment]
added
