### ISSUE TITLE
Quest for Glory III - Wages of War (1992)

### ISSUE THREAD

**Issue by Jono007** [exoscoriae/eXoDOS#1561]
Have you considered/implemented this fan patch?  It's similar to the NRS patches, but this guy has gone to town on QFG3 specifically - https://questforglory.fandom.com/wiki/Quest_for_Glory_3:_Enhanced_Edition
Direct GitHub link:  https://github.com/AshLancer/QFG3-Fan-Patch

**Comment by exoscoriae** [comment]
added. made it compatible with the existing sound options and the save game transfer utility.
