### ISSUE TITLE
Hibernated 1: This Place Is Death (2018)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1564]
It's already in the masterlist (eXo ID 16105)
on moby: http://www.mobygames.com/game/hibernated-1-this-place-is-death

It's a new created text parser adventure for DOS from 2018 and it's free for Download (i uploaded the package to the github folder)
There's also a physical boxed version with some extras.
It's from the same developer as "The Curse of Rabenstein"

here is the boxfront for it:

![Hibernated 1_ This Place Is Death-01](https://user-images.githubusercontent.com/67441153/90124793-422c7f00-dd61-11ea-9331-0e0cab67a054.jpg)

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
with the physical boxed version came an addon called "Eight Feet Under":

[EFU_POND_R6_DOS.zip](https://github.com/exoscoriae/eXoDOS/files/5107707/EFU_POND_R6_DOS.zip)

should be added as an option in the batch menu i think

**Name:** Hibernated 1 - Eight Feet Under
**Author:** Stefan Vogt
**Release:** 2019
**Genre:** Adventure
**Description:**
Have you ever wondered what the robot spider did when it went into the wall to help Olivia? In this Hibernated 1 addon, you will see the events on the stranded alien ship through the eyes of an unusual and rather unexpected protagonist: Vermin Extermination Unit 4 aka Vlad. Eight Feet Under reveals a previously unknown part of the Hibernated 1 events, so it's essential to complete the main game first. The addon takes a less narrative and more puzzle-oriented approach. Even though Eight Feet Under still has a tale to tell, it's Hibernated 2 where Olivia's great story will continue.

For now prepare to return to Vega with Vlad, save Olivia and Io from the eerie dangers and secrets lurking in the depths of the stranded alien ship and experience four exciting chapters:

I. Closer to the Stars
II. The Queen of the Swamp Crawlers
III. Breaking Barriers
IV. Kingdom of the Sting Tail Scourges

**Comment by exoscoriae** [comment]
added
