### ISSUE TITLE
Project Paradise (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1566]
The high res mode is no longer enabled. This is enabled by going into the game and selecting it in the options menu. Now the caveats:

1. high res introduces a flicker
2. when you select start game the screen freezes even though you can hear the game continuing in the background.

I tried other dosbox versions, outputs, machine types, etc with no luck. One thing I did that fixed it was use the tsr version of univesa, it however had its own issues.

1. Although the flicker and screen freeze were fixed it introduced black bars to top and bottom of screen, not a biggie but still a difference.
2. the game took longer to load
3. the intro video was now black and white. To fix this I went into the game setup.exe and you can configure the video driver to use 256 colour instead of truecolour. Made the videos not as good, but at least gave colour.

Im hoping you can find a better solution.

**Comment by exoscoriae** [comment]
et4000 removes interlacing on the videos... which is a nice. However svga mode shits the bed immediatly. But worth noting.

**Comment by exoscoriae** [comment]
vesa_nolfb allows svga mode and works fine for me.  However cycles have to be bumped a bit

**Comment by exoscoriae** [comment]
added options for both lo and hi res from the launch menu. both work fine on my end. hopefully the same for you.

**Comment by Python-Exoproject** [comment]
Didnt think to try non svga_ machine types. That does indeed work, so probably dont need the lo res option.

**Comment by exoscoriae** [comment]
I kept it for people running on pis and shit that don't have a lot of cycles
