### ISSUE TITLE
William Shatner's TekWar (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1568]
Not sure if it matters in the end but for some reason this game is using RAP-10 driver for midi in both MT32 and SC55. The games setup doesnt have a specific driver for SC55 but it does for MT32. Unfortunately though the specific MT32 driver doesnt seem to actually output and music. There is also an MPU-401 driver which is just raw midi data stream for whatever device the MPU-401 port is plugged into, so maybe it would be better to switch both MT32 and SC55 to use this driver? Again, not sure if it matters as somehow both being on RAP-10 is outputting music, I'm assuming even though it says RAP-10 (which shouldnt be working) its actually just a pseudonym for the MPU-401 driver.

**Comment by exoscoriae** [comment]
all good
