### ISSUE TITLE
Virtual Pool (1995) & Virtual Snooker (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1569]
Video related issues and page fault crash as per PM's with exo in discord

**Comment by Python-Exoproject** [comment]
Virtual Pool is working fine for me but at some point the backup cfg for Virtual Snooker got changed. Here is a copy of Snooker.cfg that works, just replace the one in the "backup" folder of Virtual Snooker.
[SNOOKER_cfg.zip](https://github.com/exoscoriae/eXoDOS/files/5084707/SNOOKER_cfg.zip)

**Comment by exoscoriae** [comment]
thank you
