### ISSUE TITLE
Big Red Racing (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1570]
Under the options menu there is a texture distance option that can be increased. Unfortunately it seems to be per user and cant be globally set. Might be worth a user note?

Edit: Further investigation shows that it doesnt seem to even save the details settings for a user though you would expect it too. I also cant seem to save recordings of races even though it asks on race exit "do you want to save recording" so I wonder if something bigger is going on.

Additionally the game can do high res, but again its on a per user basis. Once inside a race press "+" (cant use numpad +, must be the one on the number row) and it will switch modes. Keep pressing it to increase window size. This of course also requires a cycles increase. I have discovered a way to set the higher res as default for all new users, add "screen 640,480" (without quotes) to the bottom of the file "default.cfg". Cycles 100,000 with new res seems ok to me.

**Comment by exoscoriae** [comment]
it creates a file called EXO.CFG when I name my driver eXo, and it reloaded that driver when I went back into the game... so I don't think there is a problem there.

I added notes to the run file for the other stuff

**Comment by Python-Exoproject** [comment]
Seeing the way you handled Project Paradise got me to thinking. We could set this game up the same way. Have a low res option with cycles 50000 and the current "default.cfg", and a high res option with cycles 100,000 using this cfg [DEFAULT_cfg.zip](https://github.com/exoscoriae/eXoDOS/files/5084600/DEFAULT_cfg.zip)

That way the user notes are not needed except for the bit talking about texture distance.

**Comment by exoscoriae** [comment]
implemented this
