### ISSUE TITLE
Heaven and Earth (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1571]
Donarumo discovered that the graphics are better with the VGA 16 colour setting. While confirming this I noticed that there was no sound even though there was a sound.dat file and there where sound on\off options in the game. I found that I had no sound till I correctly entered the password (codes here: https://www.iangilman.com/software/heavenearthanswers.php). This password is only asked once unless you re-run setup and then it will ask once more.

**Comment by exoscoriae** [comment]
I'm getting no sound at all. ever, even with the passwords entered?

**Comment by exoscoriae** [comment]
pushing this to QA so I can get feedback from you.

**Comment by Python-Exoproject** [comment]
I had that problem as well a few times but then it worked everytime after that so I thought I had been stuffing something up. If you have the same problem then my original thought must be true, the crack is stuffing up the sound. I tried the installer version from TDC and used the correct password instead of cracking the game with success, try that.

**Comment by exoscoriae** [comment]
that worked
