### ISSUE TITLE
Space Quest IV - Roger Wilco and the Time Rippers (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1572]
Scummvm choices for MT32 and SC55 are not pointing to the correct folder location.

-p.\eXoDOS\SQ4\ needs to become -p.\eXoDOS\SQ4\SQ4

I have also noticed a file in the exodos\sq4\sq4 folder that doesnt belong. I have the patch archive (SQ4TEXT.ZIP) and in it is a txt file that says "Disk version only! This patch will correct the Text.001 message when throwing something at the sequel police at the mall. " ~~It maybe the cause of a recently reported bug.~~ Turns out v4 release was quite different and didnt have that file so its not the cause of the users issue, but the file still needs removing from our CD version.

I have now also noticed that the gesource.cfg file used by SC55 option is missing along with a couple of needed general midi files. Here are the files needed. The current exodos version does have a GENMIDI.DRV which differs from the one in the attached archive, not sure which you should go with.
[SQ4Midi.zip](https://github.com/exoscoriae/eXoDOS/files/5080947/SQ4Midi.zip)

**Comment by exoscoriae** [comment]
A. I don't see the name of the specific file that 'doesn't belong" that you are referring to. I said it was in a patch archive, but not the decompressed name.

For now, I've fixed the above issues and I'm closing this.

**Comment by Python-Exoproject** [comment]
Sorry, my oversight on the file name. Its Text.001

**Comment by exoscoriae** [comment]
removed it
