### ISSUE TITLE
Convert forced aspect false games

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1573]
Change these from using the launch bat to using the autoexec section of conf file

**Comment by exoscoriae** [comment]
do you have a list?

**Comment by Python-Exoproject** [comment]
I believe its:

Alien Trilogy | (1996)
Amok | (1996)
Archimedean Dynasty | (1996)
Battlerace | (1995)
Carmageddon Max Pack | (1998)
EF2000 (Special Edition) | (1996)
Jump 'n Bump | (1998)
L.A. Blaster | (1996)
Last Man Alive, The | (1997)
Lure of the Temptress | (1992)
Project Paradise | (1997)
Ranadinn | (1988)
Ring Cycle | (1996)
Yo! Joe! Beat the Ghosts | (1993)

**Comment by exoscoriae** [comment]
thanks. done
