### ISSUE TITLE
eXoRLP download-on-demand install.bat issues (might also be relevant for eXoDOS v5)

### ISSUE THREAD

**Issue by Jono007** [exoscoriae/eXoDOS#1581]
When aborting downloads then starting new ones, very occasionally the batch file got confused about its current path and incorrectly deleted the entire !dos or !win3x directory. I wasn't able to reproduce it consistently, and I doubt it will be a common issue, but regardless I recommend implementing a check for the current path before any "rd XXXXX /S /Q" commands - this will prevent the batch file from removing the wrong directory if my issue ever happens to anyone else. e.g. an "IF EXIST" to check for an expected file or directory in the current path.

Whilst I was looking into this I also noticed a couple of probably minor issues with the install.bat:
1. The "rd eXoDOS /S /Q" and "rd eXoWin3x /S /Q" lines (depending on if a DOS or Win3x game) results in "The system cannot find the file specified.".  I'm not sure these lines are even needed, and might be the cause of the occasional issue I mentioned above.
2. The :exit label has a trailing unrecognized character (looks a bit like [] in notepad) which results in a message "The system cannot find the batch label specified - exit" when "goto exit" is triggered in the batch file. Oddly it does still seem to jump to the :exit label anyway, so this is probably just cosmetic and won't be noticed anyway because of the echo off at the start. I think this happens mainly in the DOS install.bat files, but it could happen with the Win3x ones as well. Might be worth removing the unrecognized character to avoid possible confusion in future.

**Comment by exoscoriae** [comment]
I can't see any way it could accidentally erase the wrong folder. It would have to fail the "CD DOWNLOAD" command for that to happen. 

That said, it is redundant as the RD DOWNLOAD command below takes care of it. So I can remove it.

I've removed the character after the :exit as well
