### ISSUE TITLE
Boppie's Great Word Chase (1985)

### ISSUE THREAD

**Issue by Jono007** [exoscoriae/eXoDOS#1586]
Submitted by Python.  https://www.mobygames.com/game/boppies-great-word-chase
File in eXoDropBox (provided by Bookyaka, who mentioned "it's a booter game so "boot boppie.tc" in DosBOX, works fine")
As a side-note, eXo mentioned "I haven't done a PC Booter scan to add to the DB since that time", but this game was still not in the missing games list.

**Comment by exoscoriae** [comment]
no luck booting the game

**Comment by exoscoriae** [comment]
adding you to this @boohyaka so you can tell me what is up

**Comment by exoscoriae** [comment]
added w/ special version of dosbox

**Comment by kcgen** [comment]
Passing along helpful information from @NRS-NewRisingSun:

> Looking at the Kryoflux stream files of the game that are in TDC, the disk is not copy-protected at all, and runs perfectly fine in Vanilla/ECE DOSBox using `BOOT DISK.IMA`.

Thanks, @NRS-NewRisingSun.

**Comment by exoscoriae** [comment]
this appears incorrect.

![image](https://github.com/exoscoriae/eXoDOS/assets/8557582/9bb893c9-8e3f-473c-b13f-eec3489f3a7f)

This has been on my screen for 30 minutes now.
