### ISSUE TITLE
Alien Syndrome (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1589]
@SmilingSpectre found a good manual for atari/commodore/amiga

**Comment by exoscoriae** [comment]
added non IBM version

**Comment by bigjim161** [comment]
The manual found by @SmilingSpectre is the real manual for IBM PC.
Only one sheet is missing : "IBM PC & and compatibles- Loading and playing instructions "
Proof:
![image](https://user-images.githubusercontent.com/67555221/185765432-06576da3-20e9-4a9c-a16e-3c728e771f87.png)
I will try to arrange that in the best possible way with these photo:
![image](https://user-images.githubusercontent.com/67555221/185765449-d600f986-7c5c-4e4f-96e9-c2822ce97262.png)

found at ebay: https://www.ebay.com/itm/225041606713?nordt=true

**Comment by kcgen** [comment]
Here's a bit better quality: 

https://i.ebayimg.com/images/g/S-EAAOSws~xis6-i/s-l1600.png

**Comment by bigjim161** [comment]
Added to the github folder  : 
-Alien Syndrome (1989) IBM PC & and compatibles- Loading and playing instructions (extra)

With this sheet the PC manual is complete.

**Comment by exoscoriae** [comment]
added
