### ISSUE TITLE
Cybergenic Ranger - Secret of the 7th Planet (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1593]
@SmilingSpectre found the manual

proof:
![Cybergenic Ranger - Secret of the 7th Planet (1990)_proof](https://user-images.githubusercontent.com/67441153/90567941-40244f00-e1ab-11ea-82e1-6d7aa867cb46.jpg)

**Comment by exoscoriae** [comment]
added
