### ISSUE TITLE
Juno First (1984)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1598]
Gave this one a go. I found that when I shot one of the spheres that has a person in it the game would take away my control. I tried the using pcjr.exe instead of pc.exe, switched the cycles down to 150, and set machine=pcjr. This gave me much better results, I kept control of the game after shooting a sphere and could rescue the guy that came out of it. Also gets us away from that nasty vgaonly mode

**Comment by exoscoriae** [comment]
in pcjr I can't control the ship, it veers to the left and will never go right again (using joystick mapping assigned to the arrow keys). 

pc mode still veers left, but will go right if I push the key.

**Comment by exoscoriae** [comment]
fixed
