### ISSUE TITLE
Destination Mars! (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1608]
@SmilingSpectre found a manual

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found

- [ ] Manual (Floppy Version)
- [ ] Task Cards
- [ ] Reference Card (Later Floppy Version)
- [ ] Poster 1
- [ ] Poster 2

The manual and Task Cards are from the 1991 floppy version. The reference card is for a later floppy version that is based on the cd version currently in the collection.
All added to the github folder.
