### ISSUE TITLE
The Gate of Destiny (1997)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1613]
Game submission :  The Gate of Destiny (1997)
With its **manual** 

Genre: | Fighting
Developer: | Team Raon Soft
Publisher: | I2 Enterprise
Released: | 1997
Platform: | DOS

Added to the Github folder

Info and screenshot
https://www.old-games.ru/game/download/10084.html

**Comment by exoscoriae** [comment]
added
