### ISSUE TITLE
Nishiran (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1614]
Game submission : Nishiran (1995)

Genre: Adventure
Developer: Legend software
Publisher: Guillaume Lamonoca, Manuel Pires
Released: 1995
Platform: Windows/DOS

Info and screenshot
https://www.old-games.ru/game/screenshots/10115.html
Added the Dos version to the Github folder

**Comment by exoscoriae** [comment]
added
