### ISSUE TITLE
Elf (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1625]
@SmilingSpectre found the manual
although it says "Atari ST CBM Amiga" on coverpage it is the real DOS manual (together with the technical supplement - see #1436)

proof:
![grafik](https://user-images.githubusercontent.com/67441153/90677052-1f1c3680-e25d-11ea-92b4-c749946dbd06.png)

**Comment by exoscoriae** [comment]
added
