### ISSUE TITLE
Block Out (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#163]
it's the manual for Blockout (and already linked there too). it needs to be deleted and marked as missing

**Comment by SmilingSpectre** [comment]
Uploaded.

**Comment by TimberlAndRE-de** [comment]
thx @SmilingSpectre 
copied it to the github folder

**Comment by exoscoriae** [comment]
we already have Block Out (1989).pdf. Why would I want to replace wit with a DOC file?

**Comment by exoscoriae** [comment]
renamed Block Out (1989).pdf to Blockout (1989).pdf

**Comment by exoscoriae** [comment]
added new one

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre wrote in #4803 :

_Better version than ours._

- [ ] Blockout (1989).pdf

**Comment by exoscoriae** [comment]
replaced
