### ISSUE TITLE
F-22 Lightning II (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1658]
When Sound Blaster is selected there is a loud static noise that accompanies the intro music and speech in game.

**Comment by exoscoriae** [comment]
I don't have this issue. I created several videos as reference. Try changing your cycles to 75k and see if that helps? Sometimes max cycles might mess with audio, but usually just skipping..

[f22_003.zip](https://github.com/exoscoriae/eXoDOS/files/5104645/f22_003.zip)
here is a short video that shows in game speech for me.

unfortunately my intro vidoe is too long to attach, suffice to sound it sounded perfectly fine to me.
