### ISSUE TITLE
Dick Tracy - The Crime-Solving Adventure (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1662]
@SmilingSpectre found the code wheel

@exoscoriae is that format ok to convert it to an interactive one?
otherwise i can edit the images like with #1557 if that works better?

**Comment by TimberlAndRE-de** [comment]
found images to build the wheel
added to the github folder

**Comment by exoscoriae** [comment]
replaced pdf version

**Comment by TimberlAndRE-de** [comment]
flyers80 scanned his wheels so I replaced the current images (stiched together) with this "real" scans, so here's the quality upgrade for the

- [ ] code wheel

added to the github folder

**Comment by exoscoriae** [comment]
replaced
