### ISSUE TITLE
Falcon (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1663]
@SmilingSpectre found the code wheel

@exoscoriae is that format ok to convert it to an interactive one?
otherwise i can edit the images like with #1557 if that works better?

**Comment by TimberlAndRE-de** [comment]
I created an interactive code wheel from the images @SmilingSpectre had found (added to the github folder):

![wheel0](https://user-images.githubusercontent.com/67441153/101203494-0ba9a580-366b-11eb-82b4-784e0cb8ffd3.png)
![wheel1](https://user-images.githubusercontent.com/67441153/101203497-0c423c00-366b-11eb-838b-58eb7aadac06.png)

[Falcon (1987)_extra_code-wheel.zip](https://github.com/exoscoriae/eXoDOS/files/5644832/Falcon.1987._extra_code-wheel.zip)

**Comment by exoscoriae** [comment]
replaced pdf code wheel
