### ISSUE TITLE
Premier Manager (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1666]
@SmilingSpectre found the code wheel

@exoscoriae is that format ok to convert it to an interactive one?
otherwise, Spectre said he can recreate it from the informations - but i think it's a lot of image processing work ...

**Comment by TimberlAndRE-de** [comment]
tomwatayan (cgboard) found

- [ ] code wheel

converted to interactive and added to the github folder

**Comment by exoscoriae** [comment]
added
