### ISSUE TITLE
Their Finest Hour The Battle of Britain (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1667]
the code-wheel is already included in extras - could be converted to an interactive version

@exoscoriae is that format ok to convert it to an interactive one?
otherwise i can edit the images like with #1557 if that works better?

**Comment by TimberlAndRE-de** [comment]
tomwatayan (cgboard) found

- [ ] code wheel

converted to interactive and added to the github folder

**Comment by exoscoriae** [comment]
replaced
