### ISSUE TITLE
Hoverforce (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1669]
found the code wheel - could be converted to an interactive one:

![grafik](https://user-images.githubusercontent.com/67441153/90861572-3f96de80-e38c-11ea-9f75-857479314785.png)

**Comment by TimberlAndRE-de** [comment]
proof image for all content of the big box to find:

![grafik](https://user-images.githubusercontent.com/67441153/90861781-9dc3c180-e38c-11ea-8ba9-998fe7d25368.png)

**Comment by exoscoriae** [comment]
added. nice work.
