### ISSUE TITLE
Horror Zombies from the Crypt (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1678]
I found a manual 
- it's for Atari/Amiga
- has watermark "Le Vieux Manuel"
- en,fr,it,de

eXo please leave the issue open since DOS manual is still missing

**Comment by bigjim161** [comment]
I removed the watermarks on the manual

Added to the Github folder

**Comment by TimberlAndRE-de** [comment]
discord user Eulisker found

- [ ] manual (quality upgrade)

added to the github folder

**Comment by exoscoriae** [comment]
replaced
