### ISSUE TITLE
Universal Military Simulator, The (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1683]
found a manual for Atari ST , it has watermark "Le Vieux Manuel"

eXo please leave the issue open since real DOS manual is still missing

**Comment by Eulisker** [comment]
I scanned the 

- [ ] IBM PC User Instructions

Added to the github folder.

**Comment by exoscoriae** [comment]
i don't see any files in the github folder with this game's name

**Comment by exoscoriae** [comment]
excellent. added!
