### ISSUE TITLE
Chase on Tom Sawyer's Island, The (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1689]
This one kept crashing for me during the fireworks on title screen. Tried switching from play.bat to disney.bat and it was better, not sure what the "sc42.com" thats in play.bat does

**Comment by exoscoriae** [comment]
i got no crash on the game

I switched to ece for the pc speaker benefits. Also switch to CGA, however it works for me on both svga and cga modes.

are you getting an error message when it crashed?  without loadfix you will get a memory error there.

**Comment by Python-Exoproject** [comment]
Better on my system now that set to CGA
