### ISSUE TITLE
Blue Force (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#169]
pages 22 and 23 are missing

**Comment by SmilingSpectre** [comment]
Looking on "Notes" at the last scanned page, it was two blank pages. Combined CD booklets ends before this "notes" too. But I cannot found good scanned manual, unfortunately.

**Comment by Eulisker** [comment]
I scanned the

- [ ] Manual

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
