### ISSUE TITLE
Red Baron (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1692]
Get into the air however you like, quickest is probably via dogfighting an ace and press F10. This brings up options menu where you can increase detail level and turn on ground detail. Exit game via pressing esc and aborting mission, then quit game to save. The settings are saved in files that are backed up in our sound folders so once changed they will need to be backed up to the appropriate sound folder again.

**Comment by exoscoriae** [comment]
why would it need to be backed up? Is it getting reset by something?

changes have been made.

**Comment by Python-Exoproject** [comment]
I agree that on the surface it seems strange to backup the preferences file as it means if a user changes a setting such as turning on the joystick, disabling the mouse or adjusting anything else it is overwritten on the next time the game is started. However the sound choices are partly controlled by this file as well and without backing it up with each sound choice you dont get any change to the sound device. For example as the game is set up currently even when choosing MT32 it still plays SB as thats the version of CONTROL.PRF that is in our archive. To re-enable our sound choices here are the needed files with the detail setting maxed: 
[RedBaron_Fix.zip](https://github.com/exoscoriae/eXoDOS/files/5129685/RedBaron_Fix.zip)

**Comment by exoscoriae** [comment]
ok. added these files. thanks.
