### ISSUE TITLE
Aces Over Europe (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1693]
Similar to Red Baron there is an in flight options menu accessed via pressing F10. In this menu there is a high res option called "tall res" which switches the res from 320x200 to 320x400. Exit game properly to save. This setting is kept in one of the files we backup in the sound folders, probably control.prf, so when changed you will need to backup these files into the correct sound folder again to keep the change.

As a side note Aces over the pacific does not backup control.prf, while Aces over Europe and Red Baron do.

**Comment by exoscoriae** [comment]
removed the backup control prf files. it prevents users from making their own control schemes.

changed settings for "tall res". ground deyail was already on.

**Comment by Python-Exoproject** [comment]
This game suffers the same issue as Red Baron so I will just repost here what I wrote for Red Baron:

"I agree that on the surface it seems strange to backup the preferences file as it means if a user changes a setting such as turning on the joystick, disabling the mouse or adjusting anything else it is overwritten on the next time the game is started. However the sound choices are partly controlled by this file as well and without backing it up with each sound choice you dont get any change to the sound device. For example as the game is set up currently even when choosing MT32 it still plays SB as thats the version of CONTROL.PRF that is in our archive. To re-enable our sound choices here are the needed files with the detail setting maxed:
[AcesOverEurope_Fixes.zip](https://github.com/exoscoriae/eXoDOS/files/5129861/AcesOverEurope_Fixes.zip)

**Comment by exoscoriae** [comment]
thanks. added the files.
