### ISSUE TITLE
Prisoner of Ice (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1697]
I found an extra : Prisoner of Ice - Newspaper

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
Micral35 scanned

- [ ] Poster

added to the github folder

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] Rules for the Phone Quiz
- [ ] Registration Card

added to the gihtub folder

**Comment by exoscoriae** [comment]
added
