### ISSUE TITLE
Blue Ice (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#170]
has watermark replacementdocs
cover says English Deutsch Francais Espanol but only english pages are included. So the other languages are missing. English seems to be complete  so it's useful to play the game but not for preservation

**Comment by SmilingSpectre** [comment]
Uploaded. Unfortunately, kind scanners divided it by languages. Need to bind it back. :)

**Comment by TimberlAndRE-de** [comment]
thx @SmilingSpectre 
I merged the language-files (except italia which is a seperate manual - maybe for a future italian language pack ;-) ) and uploaded it to the github folder

**Comment by exoscoriae** [comment]
cut poems out, as we already have them in extras.

**Comment by Eulisker** [comment]
Manual in 

- English
- German 
- French
- Spanish

The manual has an uneven amount of pages. So there is something missing.
