### ISSUE TITLE
Adventures of Willy Beamish, The (1991)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1701]
I found a "The_Adventures_of_Willy_Beamish_Pizzarama_Menu" pdf without watermark. (the current one has a "replacementdocs" watermark)

**Comment by exoscoriae** [comment]
removed watermark

**Comment by bigjim161** [comment]
I found a complete "Install guide" . The current one :  The_Adventures_of_Willy_Beamish_-_Install_Guide is uncomplete

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I found a better looking version of the Pizzarama Menu. The back of the menu is the Reference card already in the collection. For what to do with that see #930

Added to the github folder.
