### ISSUE TITLE
Great Naval Battles Vol. V: Demise of the Dreadnoughts 1914-18 (1996)

### ISSUE THREAD

**Issue by Jono007** [exoscoriae/eXoDOS#1702]
Submitted by SolarExtractor. This was released exclusively on a compilation - "The Complete Great Naval Battles: The Final Fury (1996)" which also included all earlier games and expansions - https://www.mobygames.com/game/complete-great-naval-battles-the-final-fury
The release with all manuals and box art for all volumes is in eXoDropBox but is named with the compilation's title.

**Comment by exoscoriae** [comment]
added
