### ISSUE TITLE
Freddy Pharkas Demo (1993)

### ISSUE THREAD

**Issue by Jono007** [exoscoriae/eXoDOS#1703]
Submitted by ArkhangelAzrael. The Freddy Pharkas: Frontier Pharmacist Demo is a playable demo originally on floppy or on CD with copies of Sierra's demo cd Sneak Peeks.  The game contains two parts - the playable demo, an all original story (not found in the main game), and the Ballad of the Demo of Freddy Pharkas.

It should not be confused with the Freddy Pharkas CD Demo, which is only available on Windows 3.1.

Some in-game images here:  http://sciwiki.sierrahelp.com/index.php?title=Freddy_Pharkas_Demo

**Comment by exoscoriae** [comment]
added to existing freddy pharkas entry
