### ISSUE TITLE
Lucky Seven

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1704]
I think this one is missing even though its been in Moby since 2014. Timber found it here:

https://www.myabandonware.com/game/lucky-seven-7q2

**Comment by exoscoriae** [comment]
If you look at that download link, you'll notice it states you need to be able to run a PCjr Basic emulator. That is why it was not included.

if you guys can figure out how to boot a pc jr basic cartridge and then load this, we can add it.
