### ISSUE TITLE
Yatzy (1984)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1708]
The game is in the masterlist (16163) but not in eXoDOS yet

old-games.ru has it:
https://www.old-games.ru/game/9887.html

**Comment by exoscoriae** [comment]
this isn't english, nor is it easy to start without knowing english.
rejected

**Comment by TimberlAndRE-de** [comment]
Strange, how did I miss that? lol
Maybe I was confused by the many Yatzi variants 😉
