### ISSUE TITLE
Sesame Street: First Writer (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1711]
It's a word processing program ... not sure if it counts as a game for eXoDOS...
![grafik](https://user-images.githubusercontent.com/67441153/91100695-f386bb00-e665-11ea-887a-3c833baa74e4.png)

Adventure Legends has it:
https://www.legendsworld.net/adventure/game/26920

**Comment by exoscoriae** [comment]
added
