### ISSUE TITLE
1001 Nights of DOOM (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1712]
It's just an addon pack for Doom, Doom II and Wolfenstein, but it's on the masterlist and not in eXoDOS yet (or is it included as addon for Doom? I couldn't find it)

old-games.ru has it:
https://www.old-games.ru/game/9151.html

**Comment by exoscoriae** [comment]
it was marked on the master as "Compilation", which means I had decided to omit it.

If you actually look at the CD it is just loads of wads, the user would have to extract and run them all manually. so it doesn't fit the criteria.
