### ISSUE TITLE
Locus (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1714]
Discovered that the screen size during game play can be increased from the small window with a black border all around it by pressing the "+" key along the top of the keyboard (numpad "+" doesnt work). However I have not discovered how to make it stick between play sessions. Maybe a user note informing user of the possibility and informing them to press ctrl-F12 once to increase cycles if they do, just like in Theme Park. A decent speed for max window size is cycles=80000 so the cycleup would need to be cycleup=40000.

**Comment by exoscoriae** [comment]
added note to use + key. Set cycles to 80,000. Seemed to play just fine even in a smaller window with those cycles.

**Comment by Python-Exoproject** [comment]
Typo in user comment, "...the topo of the..."

**Comment by exoscoriae** [comment]
nice catch
