### ISSUE TITLE
Armageddon: Hondon Sog-Euro (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1715]
It's not on the masterlist and not on moby.

Genre | Aktion
Developer | Mirinae Software
Publisher | Pantech
Year | 1995
Language | english

old-games.ru has it (uploaded to the github)
https://www.old-games.ru/game/9128.html

**Comment by exoscoriae** [comment]
this one really walks the line. it is not really english.

added....
