### ISSUE TITLE
Gold Box Companion

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1718]
The author of Gold Box Companion has released a new version but it does not have the changes that were made to be exodos compatible. At some point it might be worth asking if he will modify the new version the same way for us.

**Comment by Python-Exoproject** [comment]
Tested all Gold Box games with new version of GBC. All work except for Unlimited Adventures as the update requires "settings.dat" to be reset for the new GBC version. I have attached a version of Settings.dat that is fixed to work.

[Settings.zip](https://github.com/exoscoriae/eXoDOS/files/5596783/Settings.zip)

**Comment by exoscoriae** [comment]
seems that simply deleting the settings file that existed works fine. Which also suggests to me that it is possible that any issues you had may have been isolated to your settings file.

Unfortunately the updater can not remove old files. It can only replace them. So I suppose putting a new settings file in the GBC.zip is the only solution.

**Comment by Python-Exoproject** [comment]
New settings file is required by the last version of GBC, its in his changelog. Something in the settings file was changed in 2.6 and using the old one with 2.6 caused issues with UA.

What's new in v2.60 (06-August-2020)
- Settings file has changed so it's best to completely remove an existing version of GBC.

Tested all games with the new clean settings file youve added, all working as expected.
