### ISSUE TITLE
Chess Champion 2175 (aka Checkmate) (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1722]
I found the game with its alternate name (Chess Champion 2175) (and its manual in spanish and french) at old-games.ru 
The game appears to be Spanish with a few English words in the game.
Checkmate (aka Chess Champion 2175) is on the dos missing list and is on mobygames (https://www.mobygames.com/game/checkmate) (https://www.mobygames.com/game/checkmate)
It's the sequel of "Chess Player 2150 "(present in eXoDOS)

uploaded to github folder with the spanish manual

**Comment by exoscoriae** [comment]
rejected until we find an english version of the game.
