### ISSUE TITLE
Moto Grand Prix (1990)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1723]
I found this Israeli racing game developed and published by "BUG Multisystem" at oldgames.ru (https://www.old-games.ru/game/screenshots/9573.html). this game is not on mobygames and eXoDOS.

Added to the gihthub folder

According to OG.ru , there is not so much text in this game. The main menu has five items: "התחל משחק" - "start a new game"; "הדגמה" - a non-interactive "demonstration" of the gameplay (it is also automatically launched in case of our short inactivity while on the described screen); "אימון" - "training"; "עזרה" - "help" (there, among other things, you can familiarize yourself with the control keys - but those that are offered are not recommended to be used); the lowest point, as you might guess, is responsible for the exit.

The following keys are used in the control: "4" and "6" on the numeric keypad - tilt the motorcycle body to the left and right, respectively; "5" - alignment of the body (you must use it); "F9" and "F10" - respectively, braking and acceleration (to start moving, you need to press the last of the last pair of named buttons). Notice the presence of six "gears" represented by a scale of numbers from 1 to 6 in the lower right corner of the screen; upon reaching by holding "F10" the maximum speed on the first one, you need to continue to hold the named key to switch to the second and so on....

**Comment by exoscoriae** [comment]
added
