### ISSUE TITLE
Kings of the Beach (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1725]
found the code wheel 
Unfortunately only as single images in every position - so not easily convertible to an interactive one
but maybe it can be added like this for now

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found

- [ ] interactive code wheel

added to the github folder

**Comment by exoscoriae** [comment]
replaced
