### ISSUE TITLE
Vigilante (2003)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1729]
This homebrew is an adaptation of the arcade game of Irem. This game is not on dos the masterlist and mobygames.
According to the eXoDOS Game Submission Sheet: the game requires  CWSDPMI.
Infos and screen: http://vigilante.free.fr/

Genre: Fighting
Publisher : Yves Rizoud
Developer: Yves Rizoud
Release : 2003 

Added to the Github folder: all versions, typed manual, music packs

**Comment by exoscoriae** [comment]
added game. didn't see manuals, music packs, etc...

**Comment by exoscoriae** [comment]
grabbed music packs from main website

**Comment by bigjim161** [comment]
Manual added to to Manuals-Extras Discovery & Upgrade folder

**Comment by exoscoriae** [comment]
added
