### ISSUE TITLE
Strip Poker Professional Volume II (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1730]
This game is not on the "Dos masters list"and on mobygames. (It is not the same game as Strip Poker Professional rev. B (1995))

Genre: Adult, Cards
Publisher : Artworx Software Company, Inc.
Developer: Artworx Software Company, Inc.
Released: 1995

more information on running the game at:  https://www.myabandonware.com/game/strip-poker-professional-volume-ii-7q6

added to the github folder

**Comment by exoscoriae** [comment]
added
