### ISSUE TITLE
Trivial Pursuit (1987)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1731]
This game is not on the Dos masterlist (It is not the same game as Trivial Pursuit (1989)), but it is on moby games https://www.mobygames.com/game/trivial-pursuit.

Genre:  Educational
Developer:  Oxford Digital Enterprises
Publisher:  Domark
Released:  1987
Platform: DOS

Added the game and **its manual** to the Ghithub folder

**Comment by exoscoriae** [comment]
added
