### ISSUE TITLE
Brix II (1988)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1732]
This game is not on the "Dos masters list"and on mobygames. 

Genre: Arcade
Developer: Richard L. Wright
Publisher: Prism Leisure
Released:	1988

info and screenshots: https://www.old-games.ru/game/screenshots/9909.html

added the game and an extra manual(**seems to be for the Tandy 1000**) to the Github folder

**Comment by exoscoriae** [comment]
added

**Comment by bigjim161** [comment]
This game works better with Svn Daum (the current dosbox is Ece).

Reason:
With the Arrowkeys, the movement of the racket is sluggish. The game is unplayable.
With  Up: lalt, left: rshift:  Down: lshift,  right: capslock, the racket goes faster, the game is playable.

But the capslock key needs to be pressed twice with dosbox Ece, not with SvN Daum.

**Comment by exoscoriae** [comment]
seems another solution is to just not use the caps lock key?

I set it to L shift, rshift, ctrl, and alt and it worked fine.

**Comment by bigjim161** [comment]
Ok, but it seems that with your solution you have to define the keys each time you launch the game, not with my solution.

**Comment by Python-Exoproject** [comment]
I had no trouble with the default keys in ECE. Pressing caps lock, left shift, alt, right shift, all worked smooth and with no need to press anything twice

**Comment by exoscoriae** [comment]
confirmed. no need to press capslock twice in ece.
