### ISSUE TITLE
Haebyeon-ui Baegu (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1733]
This game is not on the master list, eXoDOS, and not on mobygames.
Genre:	Arcade
Developer:	Sigma
Publisher:	Sigma
Released:	1996
Platform:	DOS
Screenshots: https://www.old-games.ru/game/screenshots/10061.html
Added to the the github folder (iso and full rip)

**Comment by exoscoriae** [comment]
added
