### ISSUE TITLE
120 Degrees Below Zero (2012)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1736]
This homebrew game is not on the "Dos masters list"and on mobygames. 

Genre: Adventure
Developer:	Jeremiah Nellis
Publisher:	Jeremiah Nellis
Release Date:   2012

more information here http://sciwiki.sierrahelp.com/index.php?title=120_Degrees_Below_Zero#Description
Added to the Github folder

**Comment by exoscoriae** [comment]
added
