### ISSUE TITLE
Adventures of Nikko, The (1994)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1737]
This game is not on the "Dos masters list"and on mobygames.

I found a rip of this game  here https://legendsworld.net/adventure/game/7539
http://www.atomicmall.com/view.php?id=2939551

Genre: Educational
Publisher : Mindscape
Developer: Software Toolworks, The
Released: 1994

Added to the github folder

**Comment by exoscoriae** [comment]
added
