### ISSUE TITLE
Superstar Soccer (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1739]
found the manual:
according to [this](https://retrocollector.org/index.php?page=1&system=58&media=123456789AZ&publisher=1586&title=&release=17059&gameid=13824&ct=1) and [this](http://estadioretro.be/videojuegos/en/superstar-soccer-en/) the game "Superstar Soccer" is the same as "Outdoor Soccer" on DOS. So this should be the correct manual

uploaded to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre wrote in #4305 :

```
As user wysiwyg found, it's a wrong manual we have. This manual is for "Superstar Outdoor Soccer" from Mindscape/Wizardworks. I got both "Indoor" and "Outdoor" Soccers when processed TDC, so they are in the correspondent dir on server. We haven't Indoor Soccer manual, unfortunately.
...
Wait, found it.
```

**Comment by exoscoriae** [comment]
handled
