### ISSUE TITLE
Falcon Gold (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1740]
@SmilingSpectre found a book from the gold package as an extra

proof:
![grafik](https://user-images.githubusercontent.com/67441153/91443270-66b14c80-e873-11ea-9a4a-486ba5742c7d.png)

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Tornado Map War Zone 2
- [ ] Tornado Map War Zone 3
- [ ] Customer Support Question and Answer Booklet
- [ ] Hornet Briefing for MIG-29 Pilots
- [ ] Hornet Naval Strike Fighter Map Bosnia-Hercegovina
- [ ] Hornet Naval Strike Fighter Quick Reference Card (quality upgrade, higher resolution)
- [ ] Hornet Naval Strike Fighter Release Notes
- [ ] Registration Card
- [ ] Spectrum HoloByte Special Offer Order Card

added to the github folder

There are some other extras but they're already added to Falcon 3.0 (see #3091)
I think they should be added here too

**Comment by exoscoriae** [comment]
added
