### ISSUE TITLE
Battle Chopper (1994)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1742]
This game is not on the "Dos masters list"and on mobygames.

Genre: action
Publisher : Game Socket
Developer: Panoramic Software
Released: 1994

info: https://web.archive.org/web/19980613182628/http://www.gamesocket.com/bc.html

 added to the github folder . **If you extract the file using 7-zip the game runs in dosbox**

**Comment by exoscoriae** [comment]
added
