### ISSUE TITLE
Deflector (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1743]
This freeware is not on the "Dos masters list"and on mobygames.

Genre: puzzle
Publisher : 
Developer: Imagination
Released: 1996

added to the Github folder

**Comment by exoscoriae** [comment]
link?

**Comment by exoscoriae** [comment]
seems it was on the dropbox. added

**Comment by exoscoriae** [comment]
![image](https://user-images.githubusercontent.com/8557582/92542802-6750c800-f20f-11ea-8110-9d2582d764f6.png)
protected mode error when launched.

Sending to Bugs

**Comment by exoscoriae** [comment]
fixed and added

**Comment by Python-Exoproject** [comment]
I get this on a pretty regular basis:

![image](https://user-images.githubusercontent.com/67406191/93016713-a1064200-f606-11ea-8be5-dca7a1b5a759.png)

Also once when I actually got to gameplay I found that blue is controlled by the arrow keys, except down arrow does nothing so cant move blues box down.

**Comment by exoscoriae** [comment]
numpad controls the blue box. 5 is down.

**Comment by exoscoriae** [comment]
or you can click "controls" and change it to the down arrow.

**Comment by exoscoriae** [comment]
i played for 5 minutes. no crash. I enabled extended memory again though. maybe that helps.
