### ISSUE TITLE
CyClones (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1747]
found a reference card as extra

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] clue book

not a perfect scan, pages weren't dissambled so theres shadows in the center of the double pages and some small blurry parts. but it has good resolution and all is perfectly readable

added to the github folder

**Comment by exoscoriae** [comment]
added
