### ISSUE TITLE
Godfather, The - The Action Game (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1752]
found a manual, it's a short version of the original one (probably from a later or budget release)
but since we don't have one yet...

proof:
![Godfather, The - The Action Game (1991)_proof](https://user-images.githubusercontent.com/67441153/91457556-c3693300-e884-11ea-94db-27c173dd2b76.jpg)

**Comment by exoscoriae** [comment]
added
