### ISSUE TITLE
Godfather, The - The Action Game (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1753]
found some extras:

- photo of the codewheel
- History-Guide for the movies
- advertisement

proof:
![Godfather, The - The Action Game (1991)_proof](https://user-images.githubusercontent.com/67441153/91457770-0925fb80-e885-11ea-8c8b-81703168ee1c.jpg)

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
tomwatayan (cgboard) found

- [ ] code wheel

converted to interactive and added to the github folder

**Comment by exoscoriae** [comment]
replaced
