### ISSUE TITLE
Into the Eagle's Nest (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1762]
found a manual

there are perforations on it but all is readable

**Comment by exoscoriae** [comment]
added

**Comment by bigjim161** [comment]
I found 2 extras:
- a Quick reference card
- a note "Additional controls & options"

Proof: https://www.youtube.com/watch?v=SdLpcyY7r8w

Added to the Github folder

**Comment by exoscoriae** [comment]
added
