### ISSUE TITLE
MadSpace (1997)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1766]
found the manual (russian)
the game was released in russia only, so there exists no (official) english manual

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
There is a german release with german manual. Maybe There are other language versions also.

![s-l1600](https://user-images.githubusercontent.com/81642149/147859178-121373b9-9f16-4334-9167-c4b4f53f353e.jpg)

It is possibly worth it to look for the german manual. I think it is easier to translate from german.

**Comment by SmilingSpectre** [comment]
European version (listed on redump) marked Eng/Ger, so must have multilanguage manual. At least, I hope for it.

**Comment by exoscoriae** [comment]
why is there a txt manual for this game in the github folder and why has this been marked as "in progress". 

We already hav a pdf of this manual. If there is a multilanguage one, then I am willing to replace it. But I see no advantage to these txt file that is in the folder...?

**Comment by exoscoriae** [comment]
added txt manual. moved russian manual to extras
