### ISSUE TITLE
NetHack: Falcon's Eye (2001)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1768]
This freeware is not on the "Dos masters list". There is some information on mobygames for the windows version.
https://www.mobygames.com/game/windows/nethack-falcons-eye

Genre: action Rpg
Publisher :Jaakko Peltonen
Developer: Jaakko Peltonen
Released: 2001

According to the this website: http://falconseye.sourceforge.net/
You can download, the source code to version 1.9.3 of NetHack - Falcon's Eye for the Windows, DOS and Linux versions, as well as all graphics, sounds or music. If you want to play under DOS, Linux or BeOS, download this package and compile the game. For Linux and BeOS, you also need SDL 1.2, which you can get at www.libsdl.org See also my compilation instructions. (http://falconseye.sourceforge.net/compile.html)

According to the author of this video https://www.youtube.com/watch?v=PxkBsjYCXlk
With some code he added sound support for DOS by using the Allegro game programming library.

Added to the github folder source code to version 1.9.3

**Comment by exoscoriae** [comment]
Unfortunately I don't have the time to compile a DOS version of the game. It would require hours of downloading compiling software and setting up libraries I don't have.

**Comment by exoscoriae** [comment]
added
