### ISSUE TITLE
Leeds United (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1779]
This game is on mobygames under the name: Leeds United Champions!
https://www.mobygames.com/game/amiga/leeds-united-champions

Genre: Strategy
Developer: Strategic Software Design
Publisher: CDS Software
Released: 1992

OG.ru has it https://www.old-games.ru/game/screenshots/10095.html

Added the Github folder

**Comment by exoscoriae** [comment]
added

**Comment by exoscoriae** [comment]
not english. unplayable.

**Comment by exoscoriae** [comment]
was added as english
