### ISSUE TITLE
Patriot (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1790]
there are Field Manual, Training Manual and the installation-quickstart guide already included as extras for this game in eXoDOS.
But since there was no other manual within the package (see proof), either the Training Manual or the Field Manual should be set as manual for the game

proof:
![grafik](https://user-images.githubusercontent.com/67441153/91480500-5d3fd880-e8a3-11ea-88c5-4a1fe029fb95.png)

**Comment by exoscoriae** [comment]
copied training manual as regular manual

our current scans suck and seem to be... backwards?
