### ISSUE TITLE
Network Q RAC Rally Championship (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1801]
found a manual as digital version

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
I suggested the wrong game, the manual was for Network Q RAC Rally (1994)

- [ ] @exoscoriae please set the manual from "Network Q RAC Rally Championship (1996)" to "Network Q RAC Rally (1994)"
- [ ] user Eulisker found the correct manual

added both to the github folder for easier processing

**Comment by exoscoriae** [comment]
renamed.
replaced

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual (quality upgrade - higher resolution for images)

**Comment by exoscoriae** [comment]
replaced
