### ISSUE TITLE
Mickey's Space Adventure (1986)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1828]
There is a suspicion that the current two disk version dump is not complete as the other two disney games released the same year have 3 tone Tandy\PCJR sound and this one does not. Also Tandy mode only works in non vanilla dosbox versions, while PCJR doesnt work at all. @SmilingSpectre has found a Kryoflux copy of the 1 disk version [Pristine_Mickeys_Space_Adventure_720k.zip](https://github.com/exoscoriae/eXoDOS/files/5140390/Pristine_Mickeys_Space_Adventure_720k.zip) which he has asked @boohyaka to look at when he has time to see if its any better.

**Comment by exoscoriae** [comment]
this should be low priority until it is actionable

**Comment by exoscoriae** [comment]
I've reached out to NRS in regards to this

**Comment by Python-Exoproject** [comment]
We have attempted a couple of images found online by @SmilingSpectre that also did not have Tandy sound. Willing to put this one to bed, but it still seems strange to me that the other two games released around the same time (one of them earlier, one later) with the same engine had Tandy sound\graphics while this one only has Tandy graphics. Ill leave final call up to you on whether to leave the issue active @exoscoriae.

**Comment by exoscoriae** [comment]
ripsaw seemed fairly sure this had no tandy sound from looking at the calls in the exe
