### ISSUE TITLE
WING (2000)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1831]
This Freeware is not on the Dos master list. and on mobygames.
Genre: Shooter
Publisher : Adam Hiatt, Anil Shrestra
Developer: Adam Hiatt, Anil Shrestra
Released: 2000

website: http://wing.sourceforge.net/

Added to the Github folder

**Comment by exoscoriae** [comment]
it crashes on launch with traceback issues. Rejected until this bug is fixed.

**Comment by exoscoriae** [comment]
![dosbox_000](https://user-images.githubusercontent.com/8557582/92139393-4afaf880-edd5-11ea-8c65-9c05e3df21a1.png)

**Comment by exoscoriae** [comment]
Moving to bugs

**Comment by exoscoriae** [comment]
looking into this one closer, the game requires long file names and other features that aren't true DOS. The game was designed for late era "Windows" DOS (like 7.0).

I tried DOSBox-X with long file name support, pentium pro, and other features, which handled some of the issues but it still errors out.

I'm closing this game submission for now with a rejection.
