### ISSUE TITLE
Settlers of Catan, The (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1833]
This game is not on the Dos master list and on mobygames.
info here : https://archive.org/details/Siedler_von_Catan
https://www.old-games.ru/game/screenshots/1342.html

Genre: Tabletop
Developer: Kosmos
Publisher: Kosmos
Released:	1996

Added to the  Github folder  with its manual

**Comment by TimberlAndRE-de** [comment]
@bigjim161 it's already added (#1721)

**Comment by exoscoriae** [comment]
seems to be miscatagorized? added
