### ISSUE TITLE
High Octane (2003)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1835]
This game is not on the Dos master list and on mobygames. (submitted by mtoreno)
Genre: Racing
Developer: /
Publisher: /
Released: 2003
It requires 32 MB in DOSBox to run.
![image](https://user-images.githubusercontent.com/67555221/91639208-44573480-ea15-11ea-801a-d0ccbdba8b85.png)
info: http://www.completelyfreesoftware.com/reviews/gg_w31_hioct.html

**Comment by exoscoriae** [comment]
added
