### ISSUE TITLE
Maximum Overdrive (2000)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1836]
This freeware is not on the Dos master list and on mobygames. 
Genre: Racing
Developer: Michael Davies
Publisher: Michael Davies
Released: 2003
info: http://www.caiman.us/scripts/fw/f805.html

Added to the Github Folder

**Comment by exoscoriae** [comment]
![dosbox_000](https://user-images.githubusercontent.com/8557582/92140454-bb564980-edd6-11ea-9472-0b442d19293d.png)

Crashes on launch. Rejecting until this bug can be addressed.

Game is also unfinished. Readme states that the races never end.

**Comment by exoscoriae** [comment]
fixed the error with a modified cwsdpmi.exe. added
