### ISSUE TITLE
Phoenix (2001)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1837]
This game is not on the Dos master list and on mobygames. 
"This is a remake of the arcade game Phoenix.It is a full game. Everything was in the original version is here."
Genre: Arcade
Developer: Raoul Scerra
Publisher: Raoul Scerra
Released: 2001
Website: http://div-arena.co.uk/wips/view/288
According the game submission sheet : Requires DIV32RUN.DLL
Added to the Github Folder

**Comment by exoscoriae** [comment]
added
