### ISSUE TITLE
Quicky: The Computer Game (1994)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1838]
This game is not on the Dos master list and on mobygames.
	
Genre: Arcade
Developer: ARGON Software
Publisher: Nestle
Released:	1994
Screenshots: https://www.old-games.ru/game/screenshots/5828.html

Added to the Github folder

**Comment by exoscoriae** [comment]
already in eXoDOS as "Tricky Quiky Games (1994)"
