### ISSUE TITLE
Bert the Barbarian (2000)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1840]
This game is not on the Dos master list.
mobygames (windows version: https://www.mobygames.com/game/windows/bert-the-barbarian
Genre: Arcade
Developer: Squashy Software
Publisher: Squashy Software
Released: 2000

Dos version: http://div-arena.co.uk/games/view/51

Added to the Github folder

**Comment by exoscoriae** [comment]
added
