### ISSUE TITLE
The Berenstain Bears'  Learning Essentials (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1844]
This game is not on the Dos master list.
Mobygames: https://www.mobygames.com/game/dos/berenstain-bears-learning-essentials 

Genre: Educational
Developer: Compton's New Media
Publisher: Compton's New Media
Released:	1992

Added to the Github Folder

**Comment by TimberlAndRE-de** [comment]
@bigjim161 it's already added: #1716

**Comment by bigjim161** [comment]
Ok thanks Timber
