### ISSUE TITLE
Jet Stream (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1848]
This game is not on the Dos master list and mobygames.
Found Kryoflux RAW Stream here : https://www.gamingalexandria.com/wp/2020/05/14/jet-stream/#5f4b5ddc43478-3
Genre: Simulator
Developer: Aqua system 
Publisher: Aqua system 
Released: 1996

Added to the Github folder (Kryoflux RAW Stream and its 2 manuals in Japanese)

**Comment by exoscoriae** [comment]
added
