### ISSUE TITLE
Bestplay Baseball (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1849]
This Japan baseball game is not on the dos master list and on mobygames
Screenshots: https://www.old-games.ru/game/screenshots/9783.html
Genre: Sports
Developer: ASCii
Publisher: ASCii
Released: 1992

Added to the Github folder

**Comment by exoscoriae** [comment]
can't figure out how to play. clicking at the top causes the game to go blank and do nothing. Seems like it is not playable without an understanding of Japanese. Rejecting for now.
