### ISSUE TITLE
Lunar Lander  (2002)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1850]
This Freeware is not on the dos master list and on mobygames
website :http://div-arena.co.uk/games/view/120
Genre: Arcade
Developer: Claudio Chami
Publisher: Claudio Chami
Released: 2002

Added to the Github folder

**Comment by exoscoriae** [comment]
The game requires divrun32.dll. This is a 323 bit directx file, which suggests this is not a true DOS game. rejected.
