### ISSUE TITLE
Space 1889 (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1851]
user erebus44 informed us that Space 1889 has Adlib ability where it is currently using Speaker.

Change conf from:

cd spac1889
@1889
exit

to

cd spac1889
call adlib.bat
@1889
exit

This has however brought to my attention another issue that is not caused by the above change. When you start a game and get through the intro text the game pauses for a bit and then shows "Covox Init Error" before continuing into the game.

**Comment by Python-Exoproject** [comment]
Traced the Covox issue. Whoever setup the version of the game that is in the wild with the crack has selected Covox via Sound Master for the FX, obviously this is an issue as that card isnt emulated. To fix delete "1889.CFG" and then run the game as usual. It will ask the initial config questions where you can choose VGA etc, along with Covox via PC Speaker. This will then save as a cfg for future launches of the game and correct the issue.

**Comment by exoscoriae** [comment]
great finds
