### ISSUE TITLE
Berenstain Bears, The- Learn About Letters (1991)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1853]
It's not on the masterlist and on mobygames.
Information here: https://www.worldcat.org/title/berenstain-bears-learn-about-letters/oclc/25497778

Genre: Educational
Developer:  Martin Erlandson
Publisher: Britannica Software, ©1991.

Added to the Github folder

**Comment by exoscoriae** [comment]
added
