### ISSUE TITLE
Berenstain Bears, The- Learn About Counting (1991)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1854]
It's not on the masterlist and on mobygames.
Screenshots https://www.myabandonware.com/game/the-berenstain-bears-learn-about-counting-e30#download

Genre: Educational
Publisher: Softprime Inc.
Developer: Britannica Software
Release: 1991
Added to the Github folder

**Comment by exoscoriae** [comment]
added
