### ISSUE TITLE
Waterloo (1989)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1857]
I found:
- a ref card 
- a note.

Added to the Github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found

- [ ] map (quality upgrade)

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found a better scan of the

- [ ] Reference Card

Added to the github folder.
