### ISSUE TITLE
Stunt Driver (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1859]
Found a newer version of Stunt Driver and discovered how to get it to work in VGA 256 with Sound Blaster. Please find attached pre setup copy. The executable is now "stunt_k.exe"
[Stunt.zip](https://github.com/exoscoriae/eXoDOS/files/5156857/Stunt.zip)

Not sure if this would effect network play setup

**Comment by exoscoriae** [comment]
i dislike those _k files. that always means neverlock, which in turn means a shitty screen advertising neverlock everytime you start

**Comment by exoscoriae** [comment]
replaced.


i really dislike neverlock :/
