### ISSUE TITLE
SimCity 2000: CD Collection (1994)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1866]
I found a better SimCity 2000 -Addendum and Quick Start Guide (the current one is too blurry).

**Comment by exoscoriae** [comment]
replaced

**Comment by bigjim161** [comment]
I found an extra  "SimCity 2000  power, politics, and planning, revised edition" - strategy guide"
It covers Dos and Windows versions,

added to the github folder

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] official planning commission handbook
- [ ] unofficial strategy guide

added to the github folder

**Comment by exoscoriae** [comment]
added
