### ISSUE TITLE
Rex Nebular and the Cosmic Gender Bender (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1869]
I found a better "Rex_Nebular_and_the_Cosmic_Gender_Bender_-_UK_Audio_Log_-_PC". pdf

**Comment by exoscoriae** [comment]
replaced

**Comment by TimberlAndRE-de** [comment]
ArkhangelAzrael found
- [ ] Bonus Disk manual

added to the github folder

**Comment by exoscoriae** [comment]
added
