### ISSUE TITLE
Computer Baseball (1983)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1875]
I found one manual (for C64, Atari, and Apple users) and 2 extras:

-Computer baseball - famous world series matchup (extra)
-Computer Baseball - Defense & Offense Options

Like other SSI games there is a refcard / note for IBM PC, this card / note is still missing.
proof
![cover_842-computer-baseball-photo-artwork](https://user-images.githubusercontent.com/67555221/92151263-2298eb80-ee21-11ea-8350-1d416ec2106b.jpg)
![cover_816-computer-baseball-photo-artwork](https://user-images.githubusercontent.com/67555221/92151273-275d9f80-ee21-11ea-97b7-a0e375f7071e.jpg)

Added to the github folder

**Comment by exoscoriae** [comment]
we already had this manual, in a cleaner form, and one of the extras in a cleaner form. added the defense & offense extra
