### ISSUE TITLE
Kampfgruppe (1987)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1878]
I found a manual (for C64, Atari, and Apple users)

Like other SSI games there is maybe a refcard for IBM PC

Added to the github folder

**Comment by exoscoriae** [comment]
added. but the quality is highly questionable.

**Comment by Eulisker** [comment]
I found a better looking

- [ ] manual

Still not great but way better. The last two pages of the manual were a Ratings sheet. both that and the IBM Reference is in #6096.

Added to the github folder.
