### ISSUE TITLE
Spelljammer - Pirates of Realmspace (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1880]
I removed the watermark on the "Spelljammer_-_Pirates_of_Realmspace_-_Quick_Reference_Card_-_PC"

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] quick reference card (quality upgrade)

added to the github folder

**Comment by exoscoriae** [comment]
replaced
