### ISSUE TITLE
California Games II (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#189]
has watermark on page 2 Scanned by Thalion

**Comment by exoscoriae** [comment]
removed

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual (quality upgrade)

added to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
Manual in

- English
- French
- German
- Italian
