### ISSUE TITLE
Legends of Valour (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1891]
1- I found a Data card

2- I removed the watermark on:
__Legends_of_Valour_-_The_Mitteldorf_Post_-_PC_.pdf
-Legends_of_Valour_-_Letter_-_PC .pdf_

**Comment by TimberlAndRE-de** [comment]
- [ ] The code wheel still has one field not transparent (its white), uploaded a corrected version to the github folder

**Comment by TimberlAndRE-de** [comment]
found

- [ ] poster

added to the github folder

**Comment by exoscoriae** [comment]
added
