### ISSUE TITLE
Secret of Monkey Island, The (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1892]
found the original hint-book as an extra

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
ArkhangelAzrael found a better, cleaner vesion of 
- [ ] Hint book

added to the github

**Comment by jphdelorme** [comment]
The Game The Secret of Monkey Island don't work and is written Deutsche (Atari ST)

**Comment by bigjim161** [comment]
I found 3 game design document.
-Monkey Island 1990 Mutiny on Monkey Island - Game Flow
-Monkey Island 1990 The New Monkey Island
-Monkey Island1990 Mutiny on Monkey Island

Added to the Github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
Discord User Burrito78 scanned

- [ ]  CD Version License Agreement
- [ ]  CD Version Registration Card
- [ ]  CD Version Quick Start Card
- [ ]  CD Version Users Guide

Added to the github folder.

**Comment by Eulisker** [comment]
There is a demo with unique content. You have two options. 

You can add the demo by itself to the game entry.
[mi1demo.zip](https://github.com/exoscoriae/eXoDOS/files/9127152/mi1demo.zip)

Or you can add Passport to Advenutre as a separate entry.
[mi1demo2.zip](https://github.com/exoscoriae/eXoDOS/files/9127154/mi1demo2.zip)

This one has demos for Loom and Indiana Jones 3 also but as far as i know these are just excerpts from the game.

**Comment by exoscoriae** [comment]
ok, thanks for this. But it's probably not really a manual/extras ticket?

Added it as it's own entry. I reads the Indy game also has elements not in the full version.

**Comment by TimberlAndRE-de** [comment]
Eulisker scaned his 

- [ ] code wheel (upgrade, the front wheel was cropped too much)

added to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I found a better scan of the

- [ ] Reference Card

The current one seems to be from some budget compilation (it is page 38 and 39 of something). Also it is incomplete. Here is the end of page 38 with the beginning of page 39. There is a whole paragraph missing from the current one.

<img width="414" height="144" alt="Image" src="https://github.com/user-attachments/assets/a6bf4cb6-39c3-424a-a878-b7a749f21b0e" />

Here is what it looks like in the complete version.

<img width="410" height="316" alt="Image" src="https://github.com/user-attachments/assets/fb1a6ed6-225c-4f26-82a7-de911f01be3d" />

Added to the github folder.
