### ISSUE TITLE
Monmalineun Tarokbeom Action (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1899]
This game is not in the dos master list and on mobygames.
The game works.
Genre: Fighting
Developer: Multi-City
Publisher: Taff System
Released:	1996

Added to the Github folder

**Comment by exoscoriae** [comment]
according to old-games.ru:

A South Korean fighting game, literally based on the boss fights from the almost eponymous platforming game Monmalineun Tarokbeom , famous in narrow circles for its complexity. The plot of the plot has been significantly changed: if there the hero was supposed to escape from prison, then here he finds himself in it for spitting on the street (exactly like that) - and is forced to consistently confront seven colorful-looking prisoners, participating in one-on-one fights with them.

More, alas, there is nothing to say: apart from the introductory video, **then there are no differences from the fights with the leaders in the mentioned game-the original source in principle: the locations and models are absolutely the same.**

With that said, I tend to wonder if this should be added as it's own game? Maybe an extra to the existing one? I don't know exactly.

**Comment by exoscoriae** [comment]
added
