### ISSUE TITLE
Battles of Napoleon (1991)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1903]
The current manual is a typed version without cover, and with the game rule and editor rules included.

I found a Game Rule (manual) and an Editor Rules (extra) in black and white. 
Maybe we can keep these two documents as extras

Added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual  (quality upgrade)
- [ ] editor rules (quality upgrade)

added to the github folder

**Comment by exoscoriae** [comment]
added
