### ISSUE TITLE
Oil's Well (1984)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1907]
I was really hoping we could get the PCJR version working to avoid the following as its fiddly but that cant happen so:

Currently the game is set to 500 cycles with a boost of 1000 to get past screen displaying level numbers. 500 cycles is too fast, to have the creatures slow enough and the pipe slow enough to be able to stop while on its backwards path when retracting before its all the way back at the start it needs to be around 150 cycles. 150 makes the intro screen too slow though so my suggestion is to set cycles=1500 as the base rate to get past intro screen and "Level 1" screen and have the cycleup\cycledown=1350 to allow the user to bring the speed down to 150 when gameplay starts. In addition to the flashing "Level 1" screen there are similar screens between all the other levels as well so the user will need to cycleup for each screen and cycledown for each levels gameplay. I would then suggest changing the current user note to something like:

This game currently needs different speeds for the intro\level
screens and actual gameplay. You will have to decrease the cycles
(ctrl+F11) once to slow the game down to a playable speed once
you have started level 1. Whenever you finish a level you will need to 
increase the cycles (ctrl+F12) to get past the flashing level screen,
then back down with ctrl+F11 when the next level starts.

**Comment by exoscoriae** [comment]
added
