### ISSUE TITLE
Campaign (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#192]
pages 58 and 63 are missing
needs to be cropped
fonts change sometimes because it is text-recognized from the original manual

**Comment by SmilingSpectre** [comment]
Uploaded.
Looks just as the collection version, but without recognition problems.

**Comment by TimberlAndRE-de** [comment]
thx, uploaded to the github folder
@exoscoriae it still has the missing pages, but it's not the ocr version, so it's a quality-upgrade
although please leave the issue open

**Comment by exoscoriae** [comment]
added better version. moved back to "to do"

**Comment by SmilingSpectre** [comment]
Ok, here is different one. All pages, but *sigh* slightly cropped text at the beginning.

**Comment by TimberlAndRE-de** [comment]
eXo, difficult decision then ... current one has missing pages but the pages that are in are complete - this one has some letters missing because it's too much cropped on some pages but since it has all missing pages included and even the cropped ones are readable i would suggest to replace the current one with this one
