### ISSUE TITLE
Tunnels of Armageddon (1989)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1921]
I found a complete manual. The current manual has missing pages (ex: pages 2 and 17)

I found a refcard

The code wheel is missing.

![image](https://user-images.githubusercontent.com/67555221/92644023-fb3f9400-f2e2-11ea-9558-4f534b169fc1.png)

**Comment by SmilingSpectre** [comment]
![image](https://user-images.githubusercontent.com/24454178/92654705-e53cce00-f2f8-11ea-9d18-c731fbcbc21b.png)
![image](https://user-images.githubusercontent.com/24454178/92654737-f259bd00-f2f8-11ea-8070-6d25d2d659dd.png)
![image](https://user-images.githubusercontent.com/24454178/92654760-fc7bbb80-f2f8-11ea-9c36-5dabc626400d.png)

**Comment by SmilingSpectre** [comment]
Aw, it seems, Amiga wheel will not work. :( Different colors.

**Comment by TimberlAndRE-de** [comment]
Very cool, I'll create an interactive one from that, thx @bigjim161 and @SmilingSpectre  👍🏻

**Comment by TimberlAndRE-de** [comment]
@exoscoriae uploaded to the github:
- Tunnels of Armageddon (1989)_extra_interactive-code-wheel.HTM
- Tunnels of Armageddon (1989)_extra_code-wheel-color-key.png




here are the code wheel pictures for preservation:

![wheel0](https://user-images.githubusercontent.com/67441153/93016121-2960f480-f5bf-11ea-8158-1840e9ac25fd.png)
![wheel1](https://user-images.githubusercontent.com/67441153/93016126-2ebe3f00-f5bf-11ea-80ab-8b27c5eb8317.png)
![wheel0_back](https://user-images.githubusercontent.com/67441153/93016130-31b92f80-f5bf-11ea-859e-93d5bedc8f91.png)

**Comment by exoscoriae** [comment]
added
