### ISSUE TITLE
games with CGA composite that need CGA pallet switch

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1924]
The following list of games are all capable of CGA composite but need an extra key combo pressed to look correct. Essentially there is two pallets for CGA composite, the one used by most games, and another used my a few. ECE composite mode is able to use the other mode by pressing ctrl+alt+f11 once composite has been enabled with f12. An example of the difference can be seen with Jungle Hunt (1983) which is already setup in exodos for composite, load it up, activate composite with f12, start the gameplay, and press ctrl+alt+f11 to see the difference for the games that need it. 

As far as exodos goes I think all we need to do is setup composite mode as usual (ECE, machine=CGA, user note re f12) for the below list of games with an extra bit to the user note asking them to press ctrl+alt+f11 once they have activated composite with f12 if they choose to do so. Heres the list:

- Conquest (1983)
- Digger (1983)
- Donkey Kong (1983)
- Drakkar (1989)
- Enchanted Pinball (1989)
- Guillermo Tell (1989)
- Jeopardy! Junior Edition (1989)
- Jewels of Darkness (1986)
- Jungle Hunt (1983): Already on composite, just needs note re ctrl+alt+f11
- Knight's of the Desert - The North African Campaign of 1941-43 (1983): User note needs to also tell to select "Television". F12 - not needed as once "Television" selected ECE auto enables composite, but still needs ctrl+alt+f11
- Pearl Harbor (1988)
- Press Your Luck (1988)
- Rollo and the Brush Brothers (1983)
- Spelling Fun One (1988)
- Toi Acid Game (1989): Also running too fast, needs about 600 cycles for voice to be semi understandable.
- Tournament Tennis (1985): Also running too fast, needs about 300 cycles.
- Tut-Busters (1986)

**Comment by exoscoriae** [comment]
changes made

**Comment by Python-Exoproject** [comment]
A couple of the notes I made got overlooked:

- Toi Acid Game (1989): Also running too fast, needs about 600 cycles for voice to be semi understandable.
- Tournament Tennis (1985): Also running too fast, needs about 300 cycles.
- Knight's of the Desert - The North African Campaign of 1941-43 (1983): User note needs to also tell to select "Television" fr. F12 not needed as once "Television" selected from "Monitor Type" menu ECE auto enables composite, but still needs ctrl+alt+f11
- Donkey Kong (1983): Missed completely from above list. As already machine=CGA just needs ECE and user comment with extra ctrl+alt+f11

**Comment by exoscoriae** [comment]
thanks for catching those. changes made.
