### ISSUE TITLE
Might and Magic 4 - Clouds of Xeen (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1925]
I found a better refcard. The current one is blurry.

**Comment by exoscoriae** [comment]
keeping original. doesn't look blurry to me and the scan looks cleaner and less washed out.

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found several maps / map versions, not sure which ones to add

Smiling Spectre says: "Ultimate is better again - but it has black fonts, so not very good for reading, so maybe worth to keep both. Japanese edition is in the middle between this two, so I don't know if it worth to keep it.

added to the github folder

**Comment by exoscoriae** [comment]
added all of them....lol

**Comment by Eulisker** [comment]
I found a scanned version of the

- [ ] Clue Book

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced existing cluebook

**Comment by Eulisker** [comment]
I scanned the

- [ ] Map

It is much clearer then the current one.
Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
