### ISSUE TITLE
Les Manley in: Search for the King (1990)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1926]
I found a copy protection sheet.

Added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found 

- [ ] Copy Protection

This has the copy protection with the red removed, a scan of the original (with red) and a scan of the red glasses needed to look at the copy protection.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
