### ISSUE TITLE
All Dogs Go to Heaven (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1930]
Current sound is via pc speaker and pretty bad. I discovered that the setup for the game hasnt been run and that when you do covox speech thing is a choice. Pick that with LPT1 so get significantly better sound in game. Only issue is the volume is a bit low. 

This game is also another that seems to have varying needs for cycles. In the first minigame, a race, the character is not very responsive until around 3200 cycles, but the next minigame is ridiculously fast until around 1200. Maybe set base cycles as 3200 with a 2000 down step and give a user note saying "This game has varying requirements for cpu cycles. If a particular minigame is running too fast press ctrl+f11 to slow it down and ctrl+f12 to speed up again if required."

**Comment by exoscoriae** [comment]
modified. nice sound find.
