### ISSUE TITLE
CGA composite games that need hue adjustment

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1934]
Ok, the next CGA composite item. Another issue with CGA composite is that for some games the default hue is off making the colours all wrong. Here is an example:

current cga composite results
![image](https://user-images.githubusercontent.com/67406191/93105771-cff9e200-f6f2-11ea-93ce-4ff8dedea5f8.png)

hue adjusted results
![image](https://user-images.githubusercontent.com/67406191/93105842-e30cb200-f6f2-11ea-9541-0280e4e83b03.png)

screenshot from a tsr-80
![418361-the-black-sanctum-trs-80-coco-screenshot-a-cabin-in-the-distance](https://user-images.githubusercontent.com/67406191/93105918-f6b81880-f6f2-11ea-98c8-e9e7fda4015d.png)

To correct the issue the user will need to load the game, make any in game choices for composite mode if needed, press f12 to activate composite mode, and then to hue adjust the right amount press alt-f11 (or f11 as its a 70 setting loop, just depends whether back or forward is less presses) the required number of times depending on the game. I wasnt sure if you wanted to add this as its getting a bit more complicated, though not overly so in my opinion and the improvement is more obvious and certain (Championship Golf even has a screen with the pallet displayed with words saying what each should be so I am certain the setting needs adjusting).

If you wish to implement this then here is the list of games, all of which need machine=cga, ECE, and a user note discussing f12 for composite mode along with alt-f11\f11 the number of times listed below to get accurate colour.

Games that need ALT-F11 pressed 15 times to correct hue:
- Black Sanctum, The (1984)
- Borrowed Time (1985)
- Calixto Island (1984)
- Drag Race Eliminator (1988)
- Sea Search (1984)
- Shenanigans (1984)
- American Challenge A Sailing Simulation, The (1986)
- Trekboer (1985)
- Vortex Factor, The (1985)

Games that need just F11 pressed 10 times to correct hue:
- Championship Golf - The Great Courses of the World - Volume I Pebble Beach (1986)
- Solo Flight (1985)

**Comment by exoscoriae** [comment]
changes made
