### ISSUE TITLE
Plumber No More (2018)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1940]
This freeware is not on the "Dos masters list". There is no information on mobygames.
The game works
Genre: platform
Developer: Jani Nykänen
Publisher: Jani Nykänen
Released: 2018
official website: https://jani-nykanen.itch.io/plumber-no-more
Controls:
Arrow keys: Move
Z: Run
X: Jump
Enter/Esc: Pause

Added to the Github folder

**Comment by exoscoriae** [comment]
added
