### ISSUE TITLE
Mama Soybean's Delicious Oyster Sauce (2018)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1941]
This freeware is not on the "Dos master list". There is no information on mobygames.
The game works
Genre: puzzle
Developer: Jani Nykänen
Publisher: Jani Nykänen
Released: 2018
official website: https://jani-nykanen.itch.io/mama-soybeans-delicious-oyster-sauce
Controls:
Arrow keys: Move
Enter/Space: Select in menu
R: Restart
Escape: Quit stage
"Known bug: If you reach the level 16 without using passwords, the game will crash after the level 15 with message "File not found". Workaround: write down the password of floor 15, reset the game, choose "Password", input the password and now beat the stage 15. Map 16 should load normally now."
Added to the Github folder

**Comment by exoscoriae** [comment]
added
