### ISSUE TITLE
Captain Blood (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#195]
has watermark replacement docs
seems to by scanned and converted by text-recognition. blank pages were ignored so page numbering doesn't fit

**Comment by TimberlAndRE-de** [comment]
found quality upgrade with all pages, scanned and no watermark
also found alternate manual (eu version) with more technical information, maybe worth to be added as an extra

**Comment by exoscoriae** [comment]
replaced old and added new
