### ISSUE TITLE
Cyborgirl (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1950]
seems there was no "real" manual but a general manual from the publisher for these pinball games
found and uploaded to the github folder

proof:
![Cyborgirl (1995)_proof](https://user-images.githubusercontent.com/67441153/93334337-0fc0e680-f825-11ea-8117-934886a4a43b.jpg)

**Comment by exoscoriae** [comment]
added
