### ISSUE TITLE
Space Quest IV - Roger Wilco and the Time Rippers (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1959]
found some extras:
<del>- [x] Space Piston Magazine</del>
- [x] Sierra Game Manual

proof:
![Space Quest IV - Roger Wilco and the Time Rippers (1991)_proof](https://user-images.githubusercontent.com/67441153/93337845-f8382c80-f829-11ea-9178-4ba79ecd4fd5.jpg)

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
I found as an extra:

- [ ] booklet from the later CD-release

added to the github folder

**Comment by exoscoriae** [comment]
added
