### ISSUE TITLE
Autoduel (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1962]
@Python-Exoproject found an addendum for mouse control as an extra

**Comment by TimberlAndRE-de** [comment]
@Python-Exoproject found a reference card for c64
but it contains a lot of infos about keys and menus the current manual is missing so it should be added until we find a DOS version
(marked with "other platform")

@exoscoriae please keep this issue open after processing

**Comment by TimberlAndRE-de** [comment]
files added to github:
- [ ] Autoduel (1988)_extra_addendum.pdf
- [ ] Autoduel (1988)_extra_reference-card-c64.pdf  **("other platform")**

**Comment by exoscoriae** [comment]
added
