### ISSUE TITLE
Demon Stalkers (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1967]
This game can do Tandy sound. It might be worth a user choice for this one as the current music played is not your standard pc speaker, though I cant identify what device it might actually be. I personally still prefer the Tandy, but the current one is def worth preserving.

An additional note for the Tandy option is that the cycles when using machine=tandy need to come down to around 300. For the alt conf remember that we dont need two conf files for different machine types these days, you can just use "-machine tandy" in the dosbox launch command

**Comment by exoscoriae** [comment]
awesome. I love that tandy main menu music.

**Comment by Python-Exoproject** [comment]
the part about tandy cycles was overlooked. I realised that to keep it as one conf file is not possible if we have different cycles so I played around and think that a setting of cycles=400 is satisfactory for both svga and tandy machine modes so switch cycles to 400 in current conf file and all should be good.

**Comment by exoscoriae** [comment]
ok
