### ISSUE TITLE
Final possible CGA Composite overhaul

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1972]
Ok, so now the last big thing we could change for composite. Im on the fence for this one as I'll discuss below.

First the overview. The following link is the ongoing discussion about the CGA composite patch in svn dosbox. Work has continued on the patch since it was included in svn and there is now a version of the composite patch with more accurate colours (this more accurate patch is now used in PCEM). The particular post I linked to is where you can download a special build of dosbox that includes this updated composite patch. https://www.vogons.org/viewtopic.php?p=677941#p677941. They havent updated the current version in dosbox as they are waiting on including the Tandy\PCJR composite improvements they have been discussing. Here is a comparison screenshot to give an example of the difference:

Current ECE composite patch:
![image](https://user-images.githubusercontent.com/67406191/93617480-5f680380-fa19-11ea-989b-ff1c85b94d4d.png)

Updated special build composite patch:
![image](https://user-images.githubusercontent.com/67406191/93617521-6db61f80-fa19-11ea-9b1a-bf60d70cdcf3.png)

As you can see it takes the edge of some of the brighter colours and fixes the bleeding effect that was especially prevalent in text. This is a subtle but significant improvement to most composite games, especially text heavy ones. 

My issues with using the updated patch however are:
- that its a special build so will need to be added to each composite game either in a similar way to daum or directly in each games folder, 
- they have changed the way the hue and alt pallet adjustment is made. Instead of F11\alt+F11 for hue & ctrl+alt+F11 for pallet its now set up so that ctrl+alt+F11 cycles through settings and F11\alt+F11 changes the setting values. For example to change hue for Calixto Island currently you press alt+F11 15 times, with the special build you need to press ctrl+alt+F11 once to be on the hue setting, and then alt+F11 the 15 times. For Rollo and the Brush Brothers to change pallet currently you press ctrl+alt+F11, with the special build you need to press just F11 as its the initial setting in the cycle
- we will also need to make all these games output=openglnb as the special build is done with opengl in mind, and use "scaler=normal2x forced" to make the window stay large.
- at some point (though I dont know when as its been a process over years) they will release it to mainstream svn anyway, maybe with more changes, and they may or may not use the current settings system which would mean rolling back to the way we already have it.

None of the above is overly difficult, just annoying, hence my being on the fence. Your call. If you wish to implement but not do the dirty work I'm willing to slowly work through my list of composite games and make the adjustments once weve decided how to word the user comments.

**Comment by exoscoriae** [comment]
My suggestion is we put a bookmark on this one and wait and see if it enters the main line svn build or gets picked up by ECE.

I don't feel the change is significant enough to warrant rushing out a fix at the expense of either have to create a multi-boot for each game or rely on this experimental build for all of these games.

**Comment by Python-Exoproject** [comment]
agreed

**Comment by Python-Exoproject** [comment]
Solved in recent composite review
