### ISSUE TITLE
Tiger Road (1989)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#1973]
Is it possible to set the game in Tandy mode.
According to this video https://www.youtube.com/watch?v=dt8DiFMRDvo&t=641s  this game has better music with Tandy sound.

**Comment by Python-Exoproject** [comment]
Yes, tested and working. Set machine=tandy and execute game with "@game t" instead of "@game e"

**Comment by exoscoriae** [comment]
sounds *much* better
