### ISSUE TITLE
Rick Dangerous (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1974]
This one can do Tandy sound with machine=tandy, but not sure if its worth the effort. The sound is better but there isnt much of it and the graphics are considerably lower res than the EGA option. If you feel its worth a dual conf (cant use -set machine as tandy mode needs lower cycles) then by all means, otherwise just close this one off.

**Comment by exoscoriae** [comment]
thanks for looking into it. we can leave as is for now.
