### ISSUE TITLE
RoboCop (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1977]
Can do Tandy mode. As you probably saw in chat you will need to delete "Player.fyl". Set machine=tandy, run the game. A choice will be presented to select Tandy graphics, and then Tandy sound. Now a new "Player.fyl" is created the game will launch with those settings from now on.

@bigjim161 has noted that for the Tandy version they took out the stage 1 boss (ED-209) and replaced with multiple baddies. For this reason alone I think a duel boot option instead of full switch might be in order... ;-)

**Comment by exoscoriae** [comment]
dual boot set
