### ISSUE TITLE
Sea Hunt (1987)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1978]
Found a later version with less bugs according to readme.
[Sea Hunt v1.23 [SW] (1988)(HalmaGames) [Strategy].zip](https://github.com/exoscoriae/eXoDOS/files/5251999/Sea.Hunt.v1.23.SW.1988.HalmaGames.Strategy.zip)

**Comment by exoscoriae** [comment]
modified
