### ISSUE TITLE
Ghostbusters II (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1981]
I think Jemmy mentioned this one last year but it got missed. We have offered a Tandy option in the boot but what is being output is not Tandy sound but MIDI. Besides the fact that it just sounds like MT32 being pushed through mididevice=default, you can test by setting tandy=off under [speaker]. The only way I've found to enable the Tandy sound is to set machine=tandy and execute "GBII TANDY MOUSE" instead of "GBII EGA TANDY MOUSE". This means a dual boot as -set machine=tandy wont work due to the different execute commands. As to whether its worth a dual boot, the Tandy is consistent and different but the SB and MT32 are superior, so your call.

**Comment by exoscoriae** [comment]
modified
