### ISSUE TITLE
Grayhound Racer (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1987]
Game sounds are horrific, possibly just running too fast, but even slowed down to cycles=40 dont sound quite right. Also if game is set to cycles=40 then takes waaaay too long to load. Lastly the "New Game" option isnt working.

Note: This is a brooks deforest basic game

**Comment by exoscoriae** [comment]
can't fix "sucks"

**Comment by SmilingSpectre** [comment]
I believe, "new game" simply resets all variables (and game does it on start anyway), so it will be not very much visible. But I didn't try. It's what it tries to do, if looking in code.

**Comment by Python-Exoproject** [comment]
@exoscoriae going by what spectre said above then maybe this one can be salvaged if we can sort something out for cycles\sound? Ill put it back into the action que, but feel free to slap a hold label back on it and put it back in low priority que.

**Comment by exoscoriae** [comment]
the sound sucks no matter what speed it is at. 40 doesn't sound right to me either. it just isn't garbage, but it is still atonal sounds

**Comment by exoscoriae** [comment]
I don't see any suggestions above that make this sound any better than before.
