### ISSUE TITLE
Glabal Thermonuclear War (1985)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1988]
There is an entry for this game on Moby (https://www.mobygames.com/game/dos/global-thermonuclear-war) which is this game (
[Global Thermonuclear War (PCjr or Tandy BASIC) (1985)(PC-SIG) [Strategy].zip](https://github.com/exoscoriae/eXoDOS/files/5255571/Global.Thermonuclear.War.PCjr.or.Tandy.BASIC.1985.PC-SIG.Strategy.zip)) and from what I gather from exodos master list the impression is that we have this game in the collection as exoid 216 
"Global Thermonuclear War (1988).zip" however I believe that the 1988 game is a different game, or at least widely different version of the same game. Maybe add the 1985 one as well? If you agree please note that despite it saying PCJR or Tandy the colours are wrong when those modes are used

**Comment by SmilingSpectre** [comment]
1. It's two totally different games. 1985s version is in TDC, and really BASIC. 
[Global Thermonuclear War (PCjr or Tandy BASIC) (1985)(PC-SIG) [Strategy].zip](https://github.com/exoscoriae/eXoDOS/files/5257149/Global.Thermonuclear.War.PCjr.or.Tandy.BASIC.1985.PC-SIG.Strategy.zip)

**Comment by SmilingSpectre** [comment]
2. 1988 game requires ANSI.SYS to be displayed correct. NNANSI.COM before the game corrects the problem, but only mostly (colors still slightly wrong sometimes, and endgame hiscore table is invisible). Feel free to experiment with NNANSI.
[nnans193.zip](https://github.com/exoscoriae/eXoDOS/files/5257222/nnans193.zip)

**Comment by exoscoriae** [comment]
added pause to current build.

added 1985 build
