### ISSUE TITLE
Breakoff (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1990]
I know you were working on this one, just adding it here for tracking. Bad code currently means that you cant add credits and control the game

**Comment by exoscoriae** [comment]
doesn't register the strig(1) (joystick 1) button push to start the game. I tried changing it to other keys. I was only able to get the game running if I skipped the demo entirely and had it just launch straight into the game, however this doesn't properly run a screen refresh first, so the ball bounces off the leftover garbage from the title screen.

Frankly, I'm not really interested in spending more time editing the basic to try and get this half ass game running.

**Comment by exoscoriae** [comment]
this is something anyone who knows BASIC and wants to screw around with can tackle

**Comment by exoscoriae** [comment]
this was addressed recently, and a fixed basic file was uploaded.
