### ISSUE TITLE
Snakes (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1992]
Entry just for tracking. Wasnt working for me, exo has made a change, will test when synced.

**Comment by Python-Exoproject** [comment]
Working, but user note is probably not very clear. It says use U, D, L, R for movement but that can be interpreted as the actual U, D, L, R buttons. Maybe change to "cursor keys"?

**Comment by exoscoriae** [comment]
changed
