### ISSUE TITLE
007 - Licence to Kill (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1995]
This is weird. The way the intro music interfaces with cycles is difficult to figure out. The gameplay is currently too fast at the default cycles=auto and is much better at cycles=1500, however the intro music is too fast at both settings when set in the conf. The weird thing is that if you use conf cycles=3000 and inside the game manually reduce cycles to 1500 then the intro audio is fine. This also happens with the intro music if you start the game with conf set to cycles=1500 and then inside the game reduce the cycles manually to about 800, audio is ok, set 800 in conf, intro audio is too fast. If you can figure it out great, if not then it can stay fast but for gameplay we need cycles=1500.

As a side note audio sounds better in ECE and our version is hacked to only include the EGA files. TDC has a full copy if you want, but its only for preservation as all we need is the EGA files anyway.

**Comment by SmilingSpectre** [comment]
So it seems, speed of sound detects automatically and half of working speed? How... strange...

Wait, what if you'll change speaker freq to half? (It's PC Speaker, I assume?)

**Comment by Python-Exoproject** [comment]
Tried, just changed pitch, not speed of music

**Comment by SmilingSpectre** [comment]
Ugh. Seems, this bug is omnipresent (all versions and all youtube videos have it), and you are the first who recognized it as bug. Other versions have the same music, but normal speed (I checked video for Amiga, Commodore and Atari). Case for Ripsaw maybe?

**Comment by exoscoriae** [comment]
changed cycles to 1500 for now. Looking into options to fix the sound.

**Comment by exoscoriae** [comment]
launching at 400 cycles with instructions to press ctrl+f12 (with a cycle step of 1000) in order to make the game playable.

**Comment by exoscoriae** [comment]
btw, ripsaw just said it had wonky timing. Seemed to suggest it was inherent to the game's code, and not the way it is being emulated. Without testing it on original hardware, I'm not sure how to dispute that.

**Comment by SmilingSpectre** [comment]
Yes, I expected that game is broken since the beginning. But I hoped ripsaw could do something - on the first glance it's as simple as "make sound twice slower". *shrug* Too bad.

**Comment by exoscoriae** [comment]
I've uploaded a tweaked timing file created by ripsaw.
