### ISSUE TITLE
2400 AD (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1996]
Cycles are currently set to max with unsurprising results. Set cycles to between 300 and 500 depending on how fast you feel a tick (in game time measurement) should be. Also our copy is a cracked scene copy that has had all the files for other modes like Tandy removed. Complete copy found on TDC, though by switching we will loose the crack and it would only be for preservation as we would stick with EGA mode. Lastly, so the user can start a new character at the beginning of the game we should delete saved.gam file as this file is further into the game (true for both our current copy and TDC copy).

**Comment by SmilingSpectre** [comment]
TDC version is hacked too (it not asks for the original disk, as manual suggests). But it's full.

**Comment by exoscoriae** [comment]
updated to TDC version. Added note to use "C" for game disk drive. set cycles to 400.
