### ISSUE TITLE
Grovers Animal Adventures

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1997]
Year: 1987
Lanugage: english

![image](https://user-images.githubusercontent.com/67441153/93940696-3f905280-fd2d-11ea-8f4e-7a3c4fb3285e.png)

Download: https://dosgamezone.com/download/grovers-animal-adventures-1766.html

Moby: not found

**Comment by exoscoriae** [comment]
added
