### ISSUE TITLE
Highlander: Last of the Macleods

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#1998]
Year: 1995
Language: english, german, french
Download: https://archive.org/details/highlander-last-of-the-macleods-pc
Moby: has only the Jaguar version listed: https://www.mobygames.com/game/jaguar/highlander-the-last-of-the-macleods
**It's an alpha of the PC version that was never released** so i'm not sure if it's good enough for the collection

notes:
```
unzip to \HIGH
then mount in dosbox:
mount c .\HIGH\HIGHLAND
mount d .\HIGH -t cdrom
then start using HLAND
```

_it runs , i can even choose language and run around. but if i try to fight it crashes for me
could be because of the alpha-status of the game as mentioned. but maybe just a different dosbox-setting or dosbox-version is needed?_

**Comment by exoscoriae** [comment]
got the fighting to work. added game
