### ISSUE TITLE
Extreme Tennis (1999)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#1999]
The Tie Break Tennis option can be set to 1024x768 in the ingame options menu. To make this smooth add "cycles max" to the :tiebrk section of run.bat.

Also I noticed that in the conf the section under [pci] is empty. As a 3dfx game this should have some values, looking at my old 3dfx notes from when I went through every 3dfx game we used "voodoo=opengl", and "voodoomem=max"

**Comment by exoscoriae** [comment]
I generally find I don't like resolutions above 800x600, as it makes in game text and overlays begin to appear incredibly small, as if the games weren't really designed for that resolution. I also worry about how many people have computers fast enough to actually run games at that resolution, even with max cycles set. 

I went ahead and set it to 1024x768 in this case, as there are not text overlays or anything. However it did feel a little jerky to me, and that is with an i7 and max cycles. I'm debating on bringing it back down to 800x600.
