### ISSUE TITLE
Furcol (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2001]
Needs output=openglnb to allow the game to fullscreen without borders.

**Comment by exoscoriae** [comment]
modified

**Comment by Python-Exoproject** [comment]
Hmmm, looks like we may have to pick what we want for this one or set up a dual boot. We need openglNB due to the old issue of overlay not scaling with some games (usually in FMVs, though in this game the FMVs are fine and its the actual game), however openglNB causes 3DFX mode to freeze when in fullscreen once you hit the main menu. Using overlay means 3DFX works fullscreen fine, but small window & black borders in fullscreen for non-3dfx

**Comment by exoscoriae** [comment]
added launch option

**Comment by Python-Exoproject** [comment]
All good except the outputs have been crossed. dosbox.conf should have output=openglnb & dosbox2.conf should have output=overlay

**Comment by exoscoriae** [comment]
thanks
