### ISSUE TITLE
Wizball (1987)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2005]
Switch to ECE to restore the speech during the intro

**Comment by exoscoriae** [comment]
great find. I love restoring stuff like this!!

**Comment by Python-Exoproject** [comment]
I just remembered X is better at this DAC stuff with some games and sure enough the screeching is reduced if we switch to X. Remember fullresolution=desktop and overlay=openglnb if you switch

**Comment by exoscoriae** [comment]
sounds about the same to me

**Comment by exoscoriae** [comment]
if anything, X seems worse. The volume of the speech is quieter, while the screech is the same volume.
