### ISSUE TITLE
Battle Chess (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2008]
If you use the command line switch /adlib you enable DAC via adlib. As dosbox doesnt emulate this well it doesnt sound great at the moment but its worth noting for future reference.

**Comment by exoscoriae** [comment]
tested the adlib switching with dosbox-x, which does handle dac pretty well. Sounded nearly identical to the way the game sounds normally.

Do we have any evidence that the DAC should sound better? Like from actual recordings taken on original hardware?

**Comment by Python-Exoproject** [comment]
Ok, tried latest staging with all the new audio work they have been doing and the /adlib switch now sounds pretty good.

I suggest possibly offering both as options for nostalgia as most would have played with the harsher PC speaker, but the adlib DAC is the way to go if one choice is all we offer if for no other reason than the pops are gone and the pawn grunts in the battle recorded below are more human sounding

[PCSpeaker.zip](https://github.com/exoscoriae/eXoDOS/files/10839787/PCSpeaker.zip)
[Adlib DAC.zip](https://github.com/exoscoriae/eXoDOS/files/10839793/Adlib.DAC.zip)

**Comment by kcgen** [comment]
For comparison, Staging 0.80.1:

https://user-images.githubusercontent.com/1557255/221626166-8f632ab9-39f0-41fb-b06c-a9b49f8c4f63.mp4

Only `oplmode = opl2` is needed, others optional:

```ini
[sblaster]
sbtype = none
oplmode = opl2
opl_filter = sb1

[mixer]
reverb = on
chorus = on
```

For ref: Staging 0.80.x has default cycle-accurate timing in: Tandy, PS1Audio, Adlib, AdlibGold, CMS/GameBlaster, SB* OPLs, Innovation SSI-2001, PC Speaker (both discrete and impulse), and GUS.

0.81 beta adds cycle-accurate timing for MIDI and MT-32.

What's missing still: cycle-accurate timing for SB DAC.

**Comment by Python-Exoproject** [comment]
Both recordings I posted above were also in staging 80.1, difference between mine and krc's being I dont have the chorus or reverb on

**Comment by exoscoriae** [comment]
done
