### ISSUE TITLE
Purple Saturn Day (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2010]
To enable the sound switch to ECE or X. X removes the high pitched screech, if used remember fullresolution=desktop and output=openglnb

**Comment by exoscoriae** [comment]
switched the ece and changed conf

**Comment by Python-Exoproject** [comment]
See videos of my results in ECE and X, along with comment in Discord.

**Comment by exoscoriae** [comment]
i didn't see any comments in discord.  Or videos?

**Comment by Python-Exoproject** [comment]
I uploaded the videos to ken channel, but accidentally said they were for "purple Rain", not "Purple Saturn Day"

**Comment by exoscoriae** [comment]
ok. I switched it to x. ece was a tad noisier.
