### ISSUE TITLE
Outrun (1989)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2018]
I manage to heard the tandy sound but the game freeze at the selection screen
Set Machine: tandy
outrun
at menu I press 3 for ega/vga and I heard the tandy sound (a big voice + music)  (this is what I heard https://www.youtube.com/watch?v=WrpPW0X2vc8 )

Is it possible to fix it, in order to play in Tandy mode with DAC sound? 

I use this file https://mega.nz/file/qpECiDDB#hJQifbZPIFMa4WttBiezDgIuQ3yb_zuFAkGc8fvMEVM
and this image https://mega.nz/file/j58EUDLL#ISExkcT-_igiSjWVpxQSZJHxxNq8kwqYtOwnvri70hA
with existing file in Exodos

There some info here https://www.vogons.org/viewtopic.php?t=40684

**Comment by SmilingSpectre** [comment]
Aha, Great Hierophant gave the leads there.
Both versions are in TDC
[OutRun [a1] (1989)(SEGA Enterprises Ltd.) [Racing - Driving].zip](https://github.com/exoscoriae/eXoDOS/files/5287068/OutRun.a1.1989.SEGA.Enterprises.Ltd.Racing.-.Driving.zip)
Male voice

[OutRun [a3] (1989)(SEGA Enterprises Ltd.) [Racing - Driving].zip](https://github.com/exoscoriae/eXoDOS/files/5287069/OutRun.a3.1989.SEGA.Enterprises.Ltd.Racing.-.Driving.zip)
Female voice

Both works in vanilla (didn't test them in ECE).

**Comment by bigjim161** [comment]
@SmilingSpectre Thank you. Both versions work in ECE !

**Comment by exoscoriae** [comment]
added both
