### ISSUE TITLE
Gold of the Americas: The Conquest of the New World (1989)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2019]
This game plays sound in PCJR mode but not in tandy mode and vga mode.
(I can't see if the graphics are correct in composite mode)

Is it possible to fix it?

**Comment by Python-Exoproject** [comment]
I got sound in both Tandy and VGA, just had to wait a bit longer at the title screen without pressing anything. Tandy sound can take a bit to start sometimes. In this case though there is little to no difference between sound in Tandy, PCJR, or VGA mode. Additionally the mouse stuffs up in any mode besides VGA and PCJR is only in CGA colour. If your not getting sound in VGA, maybe something else is going on for your setup? I know last time I thought that was happening I had just forgotten to turn my volume up, so it can happen to any of us.

**Comment by bigjim161** [comment]
@Python-Exoproject thanks, If there is no difference ,I close this issue.
