### ISSUE TITLE
Hack (1984)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2022]
For a laugh I decided to look at the game with the oldest archive date in the collection. I noticed when I loaded it up that the controls where all over the place and looked at a file "moves.txt" to figure it out, here they are:

               Y K U
		    \|/	
		   H-+-L	
		    /|\	
	  	   B J N

As you can see that is a bit all over the place on a modern keyboard so I suggest setting up a mapper file.

**Comment by exoscoriae** [comment]
good call. mapped and added the moves.txt file to launchbox extras.
