### ISSUE TITLE
Sentinel Worlds 1 - Future Magic (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2031]
This game is capable of Tandy sound but had been hacked up to allow it to be played (apparently it originally had a weird file structure or something). I found an original copy in TDC and manually completed the actions that it would have run during install on its files, then put those files into the current version we have. This has re-enabled Tandy, just extract the attached tandy archive over our current version. I also did CGA so that all modes are present from a preservation aspect. It might also be worth having the original in a "floppy" folder. All files attached. I didnt do an EGA version as thats our current setups mode.

[Tandy.zip](https://github.com/exoscoriae/eXoDOS/files/5288628/Tandy.zip)
[CGA.zip](https://github.com/exoscoriae/eXoDOS/files/5288629/CGA.zip)
[Sentinel Worlds I- Future Magic (1988)(Electronic Arts, Inc.) [Adventure, Role-Playing (RPG)].zip](https://github.com/exoscoriae/eXoDOS/files/5288630/Sentinel.Worlds.I-.Future.Magic.1988.Electronic.Arts.Inc.Adventure.Role-Playing.RPG.zip)

**Comment by exoscoriae** [comment]
added a launch option. nice work fixing the files.

**Comment by Python-Exoproject** [comment]
Do you think the CGA version is worth setting up? I only gave the files for preservation, although as youve added a copy of the original floppies that probably isnt even necessary. We could probably get away with just the Tandy version, or if you want to give the users the option of the PC speaker (which does seem to have slightly different music at points) then I would stick with EGA for the IBM option. If you agree here is the EGA file, just overwrite the same file in sentw1fn\\sw1\fm and correct the user note to EGA from CGA.
[FM-GRAFX.zip](https://github.com/exoscoriae/eXoDOS/files/5334398/FM-GRAFX.zip)

**Comment by exoscoriae** [comment]
added ega option.

I figure, adding video options for games (cga vs ega vs whatever) is something I'll end up wanting to do eventually. Might as well do it now for games that I have in front of me. Not to say I want to focus on this. Just a, "hey, while the game is open...." situation.

**Comment by Python-Exoproject** [comment]
As per recent bug report the Tandy sound was stuffed. Discovered it was due to the game needing a specific folder structure. Fixed and uploaded here:
[Sentinel Worlds 1.zip](https://github.com/exoscoriae/eXoDOS/files/5371137/Sentinel.Worlds.1.zip)

**Comment by exoscoriae** [comment]
thank you. fixed
