### ISSUE TITLE
Super Zaxxon (1984)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2033]
Currently we are using a CGA composite version of this game bu the attached archive has a pcjr version with better colour for objects on the ground like radar dishes than the CGA composite version
[Super Zaxxon [DC] (1984)(SEGA Enterprises Ltd.) [Action].zip](https://github.com/exoscoriae/eXoDOS/files/5288686/Super.Zaxxon.DC.1984.SEGA.Enterprises.Ltd.Action.zip)

**Comment by exoscoriae** [comment]
modified
