### ISSUE TITLE
Zaxxon (1984)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2034]
Using the PCJR version from this archive gives 3 tone sound. Set machine=pcjr & joysticktype=4axis. The game then asks if you want to use keyboard or joystick which gets past an issue I was having without the joystick setting. It might be worth giving choices between our current copy and this new PCJR version as, at least for me, different FX play in the different versions (for example the laser barrier had no sound in the PCJR version, but in current copy it did).

[Zaxxon [DC] (1984)(SEGA Enterprises, Inc.) [Action].zip](https://github.com/exoscoriae/eXoDOS/files/5290596/Zaxxon.DC.1984.SEGA.Enterprises.Inc.Action.zip)

**Comment by exoscoriae** [comment]
modified with boot choice
