### ISSUE TITLE
Adventures of Willy Beamish, The (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2035]
Munt has been updated to v2.4.0 and has made a change that improves Willy Beamish when using rev0 roms, which we do. When\if Munt 2.4.0 hits dosbox svn we should change Willy to use it as a custom dosbox setup.

**Comment by exoscoriae** [comment]
@Python-Exoproject 
any news on this?

**Comment by Python-Exoproject** [comment]
Just had a look. ECE as of  r4367 uses Munt v2.4.0, while staging uses the latest v2.5.3, the rest are all on older versions

**Comment by exoscoriae** [comment]
switched beamish to ece4460, which should have this in it.
