### ISSUE TITLE
SSG Decisive Battles engine

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2036]
Whoever did these later releases hated these games. There are similar issues with the 3 Decisive Battles of the American Civil War Vol 1-3 as those we had with the Battlefront Games.

Decisive Battles of the American Civil War Vol 1: No music

Decisive Battles of the American Civil War Vol 2: No music, no title screen (file is there but exe is stuffed and wont read it), scenarios that dont belong

Decisive Battles of the American Civil War Vol 3: Similar to Panzer Battles this seems to have been released twice. The first time as a 6 scenario release, the second as a compilation of all the previous games plus some extras.

As Tandy doesnt seem to work for any of them we can skip that with this lot, but for the issues with the first two games I cant find any clean copies online. 

What I've done is similar to my approach to Halls of Montezuma, I've grabbed the working exe from the third game and the relevant scenarios and merged with the title screen files of the other games. This has created "clean" copies of the first two games that have correct working titles screens, scenarios, and music (as the music is part of the exe file its now the same for all three games but as the first two had broken music I think thats ok). I have also setup the third game as we did Panzer Battles with an "original" option with just its 6 scenarios, and a "later" option with all scenarios.

I think this hack should be ok as its just as an original copy would be except for the music, but as it stands now the same music is an improvement over no music. Anyway, here it is for your assessment: [DecisiveBattlesVol1-3_Fixed.zip](https://github.com/exoscoriae/eXoDOS/files/5313295/DecisiveBattlesVol1-3_Fixed.zip)

**Comment by exoscoriae** [comment]
sounds good to me.

I've replaced the files with your copies

**Comment by Python-Exoproject** [comment]
QA'd and all looks good except that the version of Vol 2 that Spectre uploaded was Tandy capable, yet it hadnt been setup. Please find here a setup version.
[DecisiveBattlesVol2_TandyAdded.zip](https://github.com/exoscoriae/eXoDOS/files/5355902/DecisiveBattlesVol2_TandyAdded.zip)

**Comment by exoscoriae** [comment]
modified. thank you.
