### ISSUE TITLE
Blades of Steel (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2037]
Seems I've learned a telltale sign of DAC voices not playing. I was testing this game for something else and heard what has become a telltale clicking at one point on the title screen. Sure enough set to ECE and we have speech. To fix switch to ECE, and if you ever hear that click in an old game that uses pc speaker and vanilla dosbox switch to X or ECE for a quick test (some only work in X).

**Comment by exoscoriae** [comment]
great work
