### ISSUE TITLE
Boot Camp (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2039]
Has tandy sound with machine=tandy, though user has to select Tandy from a presented menu. Already has Adlib, so not sure its worth it, see what you think.

**Comment by exoscoriae** [comment]
added video boot options

**Comment by Python-Exoproject** [comment]
I noticed you set up 3 different conf files, but as the only setting that is changing is the machine setting we can just use the one conf and use the -machine command line option. Here is the bat already setup:
[Boot Camp (1989).zip](https://github.com/exoscoriae/eXoDOS/files/5348764/Boot.Camp.1989.zip)

**Comment by exoscoriae** [comment]
great. thanks
