### ISSUE TITLE
Clue - Master Detective (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2042]
This game has an option for sound in the in game drop down menu but there is no sound coming from the game.

**Comment by exoscoriae** [comment]
interesting. running this in svn or ece, the main menu is garbled. I've reported this to rs.

I got no sound trying different builds or options. I'm finding sites claiming the game has no sound, but the manual specifically mentions it and it is on the menu... so... we'll see I guess.

**Comment by exoscoriae** [comment]
Confirmed there is no sound code in the game.  It is a leftover from the amiga development.
