### ISSUE TITLE
Conflict in Vietnam (1986)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2043]
The game crashes if you just sit at the game screen and do nothing. Eventually (as seen in the capture posted below) the computer moves onto a village and the game crashes. The archive contains 2 videos but that was just dosbox splitting due to different resolution of the game vs the error, in game the error cam as soon as the character went on the house icon. There is a image of the floppy on oldgames but my computer wouldnt read it for me to test.
[capture.zip](https://github.com/exoscoriae/eXoDOS/files/5321970/capture.zip)

**Comment by SmilingSpectre** [comment]
It's totally strange. I totally can play collection version at any of my dosboxes - vanilla, Daum, ECE. But if I run it through collection .bat, it immediately broken! %) I cannot track the broken value. I cannot see it.

**Comment by Python-Exoproject** [comment]
That was the clue I needed. I ran through a few default settings that we overwrite via our dosbox.conf and found its the cycles. Anything between 700 and 2400 cycles causes the error. So pick a cycles less than 700 or higher than 2400 and it works.

**Comment by exoscoriae** [comment]
thanks guys.
