### ISSUE TITLE
Crusade in Europe (1985)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2044]
Similar engine to Conflict in Vietnam and as with Vietnam the in game colours are improved by setting machine=pcjr. Also as with Vietnam the cycles are probably a bit high at 3000 as it speeds up the fx too much. I tested 1000 cycles and it seemed ok, but as Vietnam had that crash with 1000 cycles it might be safer to go with 700 as we did with Vietnam

**Comment by exoscoriae** [comment]
modified
