### ISSUE TITLE
Dive Bomber (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2045]
Current game folder doesnt contain the files from the Tandy disk. Old games has images of all 3 game disks here https://www.old-games.ru/game/download/2803.html, so for at least preservation might be worth a grab. As for if Tandy is better, its subtle but I think the colour is slightly better in tandy mode, the joystick colour is better, the surface areas of the cockpit have a bit of colour, etc. Crosshair isnt as well defined though, and if you do the practice attack run on the bismark in EGA you will see white flashing from the AA fire (though im not sure if thats a good thing or not). Your call.

**Comment by exoscoriae** [comment]
added all three options
