### ISSUE TITLE
Moraffs Mather Extended

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2056]
TDC has shareware version of Mather extended and Mather (not sure is different versions of same game or sequels). @SmilingSpectre uploaded a registered version of one of them, not sure if it was extended or just mather.

**Comment by SmilingSpectre** [comment]
Extended, of course. I woudn't bother with shareware. Same 3.0 as TDC, actually.

**Comment by exoscoriae** [comment]
added
