### ISSUE TITLE
Utopia - The Creation of a Nation (1991)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2066]
I found an extra : the manual for the data disk : Utopia - The New Worlds

Added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I cut out 

- [ ] Additional PC Instructions
- [ ] Tutorial

from the digital manual. They were seperate documents in the original release.

![Utopia](https://user-images.githubusercontent.com/81642149/113510898-4cec8c00-955d-11eb-9f89-c73a24723096.jpg)

added to the github folder

**Comment by exoscoriae** [comment]
added
