### ISSUE TITLE
Death Sword (1988)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2069]
I found a poster of the European release (named Barbarian: The Ultimate Warrior)
![image](https://user-images.githubusercontent.com/67555221/95888346-4553e380-0d81-11eb-934f-b4d4838d52b6.png)

Info here: https://www.mobygames.com/game/death-sword/screenshots

Added to the github folder

**Comment by exoscoriae** [comment]
added
