### ISSUE TITLE
Thunder Strike (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2073]
This game is using machine=vgaonly but I cant find anything on why we might have done so. If you dont know either then we could probably switch it back to svga_s3?

**Comment by exoscoriae** [comment]
With svga it shows a ton of stuff at launch that isn't supposed to appear. Vga only properly emulates this and blanks them out

**Comment by Python-Exoproject** [comment]
But also comes with the negatives associated with vgaonly. If you want to go that way to counter some of those negatives you will need to set at least OpenglNB so it will respect our resolution

**Comment by exoscoriae** [comment]
set openglnb
