### ISSUE TITLE
Kingmaker (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2078]
Another for MT32 enabling. Usual ECE and midi sections. Can also now be added to MT32 playlist.

There is a more recent version available at oldgames, along with a patch for to upgrade that version to an even newer version. Not sure if there is a crack around for it though.

**Comment by exoscoriae** [comment]
updated version shave an error where the speech cuts off during the intro. our current version doesn't do this, so I'll stick w/ it.

**Comment by Python-Exoproject** [comment]
Sound cuts off due to the wrong IRQ. Edit DMA.CFG and change the 5 to a 7 to fix.

**Comment by exoscoriae** [comment]
awesome, thank you!
