### ISSUE TITLE
Nigel's World Adventures in Geography (1991)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2080]
This game is on the master list and on mobygames

"Nigel's World is a fun educational title that fulfills what its subtitle (Adventures in Geography) implies, despite obvious borro-- err-- inspiration from Carmen Sandiego series."

Genre: Educational
Developer: Lawrence Productions 
Publisher: Lawrence Productions
Released:  1991
Platform: Dos

https://www.ebay.com/itm/Nigels-World-Adventures-in-World-Geography-IBM-3-5-Floppy-disk-Learning-game-/124047072609

Added to the github folder

**Comment by exoscoriae** [comment]
added
