### ISSUE TITLE
MicroLeague Baseball IV (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2082]
This one is MT32 capable and looks like at one point it was set up as such. Not sure why it was switched back to SB only. If you cant figure out why either then it can be fixed to work with MT32 again with an edit to run.bat. Can then go on MT32 playlist as well

**Comment by exoscoriae** [comment]
mt32 and sb sounded pretty similar to me?

**Comment by Python-Exoproject** [comment]
Thats because the copy commands in run.bat are wrong. Currently "copy .\sb16\ *.*" & "copy .\mt32\ *.*" when they should be "copy .\sb16\*.* ." & "copy .\mt32\*.* ."

Once thats done you will hear a difference, especially during the national anthem at the beginning of a game

**Comment by exoscoriae** [comment]
fixed
