### ISSUE TITLE
Secret Weapons of the Luftwaffe (CD-ROM) (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2083]
Noticed the game was missing install.exe meaning that if anyone wanted to change the game config to use joysticks for example they couldnt do so easily. Here it is, just put in \swotl folder. I also noticed cia install.exe that memory is detected as a negative, set memory to 16 fixes it.
[INSTALL.zip](https://github.com/exoscoriae/eXoDOS/files/5397436/INSTALL.zip)

**Comment by exoscoriae** [comment]
also added the games original cd image.
