### ISSUE TITLE
Fallout (1990)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2090]
In Launchbox, the manual  for fallout (1990) corresponds to Fallout (1997) from Interplay.

**Comment by exoscoriae** [comment]
That is because it is defaulting to that manual since we don't have one for Fallout (1990). Unfortunately, short of adding a proper manual, there is nothing I can do to fix this as LB defaults to manuals with the same name as the game if one isn't predefined.

**Comment by bigjim161** [comment]
Maybe we can replace the current manual with a print screen for in-game instructions.
![Capture d’écran (30)](https://user-images.githubusercontent.com/67555221/96550795-9b5ce580-12b1-11eb-8d47-32f7f163420c.png)
 added to the github folder

**Comment by exoscoriae** [comment]
added the png to the manuals folder
