### ISSUE TITLE
Mini Prince (2020)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2093]
Mini Prince is a cute fan-made platformer for MS-DOS. It's like Prince of Persia but then completely stripped down to its bare minimum and thrown into a shrinking device.
• One whole level
• Full ASCII Action
• Resolution 104x80
• Sword Fighting
• It even has sound

Download: [DOS-Version](https://annebras.nl/miniprince/download/MiniPrince-DOS.zip)

Link to the Project Website: [Link](https://annebras.nl/miniprince/)

**Comment by TimberlAndRE-de** [comment]
added the download and the HD graphics from PC King to the github folder

**Comment by exoscoriae** [comment]
added
