### ISSUE TITLE
Dungeon Keeper (1997)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2094]
I found an extra: Tales of the Dungeon Keeper

Added to the github folder

found here https://www.old-games.ru/game/download/get.php?fileid=28504&modal=1

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
Eulisker found

- [ ] manual for addon Deeper Dungeons

added to the github folder

**Comment by exoscoriae** [comment]
added
