### ISSUE TITLE
Femme Fatale (1991)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2098]
This game is not on mobygames and on the dos master list.

Publisher: Graphic Expressions
Developer: Graphic Expressions
Genre:  Puzzle/Adult
Date: 1991

I found also the manual 

Added the to Github Folder (Game Submission)

**Comment by bigjim161** [comment]
After playing the game and reading the manual, I think there is no need to crack it.
(load a picture pcx in the folder Femme... (press F10) and press alt+s... )

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I moved the game to staging, added Covers, a better scan of the manual and disk images. 

My version came with three Data Disks. The old version had a bunch of pictures that were not in my version or any of the data disks. I tried to add them all.

My version also seemed to have a few updated pictures. 

<img width="639" height="199" alt="Image" src="https://github.com/user-attachments/assets/2b18ea73-da0e-46c6-988c-421456c04712" />

**Comment by Python-Exoproject** [comment]
@Eulisker whereabouts did you stick the work you did on this?

**Comment by Eulisker** [comment]
It should be in game submissions. Let me check in a bit.

**Comment by Eulisker** [comment]
I uploaded an updated version with 2 small changes.

- ALXNDRA0.PCX is breaking the scramble dialog for some reason. I could not figure out the cause and deleted the picture.

<img width="1424" height="1098" alt="Image" src="https://github.com/user-attachments/assets/33c2a3e1-48db-48d1-8ec0-87b3be9213e0" /> <img width="1424" height="1098" alt="Image" src="https://github.com/user-attachments/assets/881f7efc-3b97-46b0-bf43-de1f02ff3e65" />

I tried most of the others and they work fine.

- I renamed the coverscans from Femme Fatale-00.jpg to -01.jpg. If i remember correctly the -00.jpg suffix was to indicate missing covers where eXo substituted a game logo screen for a cover.

**Comment by Python-Exoproject** [comment]
I left the copy of ALXNDRA0.PCX that was in the previous game files as even though the puzzle scrambler is broken, it still loads for the viewer and came with the release

This ticket is actioned as far as the game data, switch to staging, and manual. The cover images ive moved to the dropbox image submissions folder for later LB metadata update and will move this ticket to that project

**Comment by Eulisker** [comment]
How about naming it ALEXNDRA6.PCX so it’s not the first thing you open and you have no idea what to do?

**Comment by Python-Exoproject** [comment]
done
