### ISSUE TITLE
HardBall 4 (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#21]
We think it should play CD audio in game but cant get it to do so.

**Comment by exoscoriae** [comment]
Vogons thread on the issue

https://www.vogons.org/viewtopic.php?t=64463

**Comment by exoscoriae** [comment]
I spent some time on this issue tonight. I listened to the CD tracks for a bit and I was surprised how close they sound to midi. I then mounted juts the CD's data files to ensure it wasn't actually playing CD audio and that we were confusing it for MIDI (based on the quality of the CD audio). However music did play, which confirmed it was playing MIDI audio.

**Comment by exoscoriae** [comment]
confirmed, via ripsaw, the game lacks any co to actually access and play the CD tracks.
