### ISSUE TITLE
Chaos Control (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#210]
Page order is not correct (8/9 are between 3 and 4  back is on page 3)

**Comment by TimberlAndRE-de** [comment]
sorted the pages and uploaded it  to the github folder

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual (quality upgrade - higher resolution, cleaner scan - especially screenshots are better)

**Comment by bigjim161** [comment]
found an extra manual with Installation Instructions

Added to the github folder

**Comment by exoscoriae** [comment]
replaced\added
