### ISSUE TITLE
Planet of Lust (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2102]
Here is the latest update that Kudgel made for his Planet of Lust fix. Point dosbox at "planetof.bat" and it will now load the VGA version if dosbox is set to a vga mode or the original inverted palette version if its not.

[planlusv.zip](https://github.com/exoscoriae/eXoDOS/files/5504667/planlusv.zip)

**Comment by exoscoriae** [comment]
added
