### ISSUE TITLE
Freak Out (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2103]
It has been noted that the file "freakout.bat" has foreign characters and German in it which is causing trouble with the converter. Possibly clean out or replace with English translation?

**Comment by exoscoriae** [comment]
as that is an original file, I don't necessarily want to edit it.

I added a new file called FO_Eng.bat and now I have the conf file calling it.

I don't know that this benefits the converter though until a v6 comes out, as a typical user needing a linux converter will not have had the ability to run the updater prior to running the converter...
