### ISSUE TITLE
+K (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2107]
@SmilingSpectre has pointed out that +K has a GUS mode. Run game with "maska gus" and enable gus in conf. Also remember to add to GUS playlist.

**Comment by exoscoriae** [comment]
is it just me? I can't hear any difference at all between these?

**Comment by exoscoriae** [comment]
still awaiting follow-up on this one from either @SmilingSpectre or @Python-Exoproject

**Comment by exoscoriae** [comment]
I found this exchange in the discord:

eXo 11/18/2020
@Smiling Spectre +K sounds identical to me w/ GUS enabled
other than it is quieter

Smiling Spectre 11/18/2020
Indeed. I tested on Daum, and there SB is inferior (drums are awful in particular). Default ECE works the same for the both cards. Sorry for the wrong report.

So, with this stated I am going to close this issue and make no changes.
