### ISSUE TITLE
3D Ball Blaster (1992)\3D CyberPuck (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2108]
@SmilingSpectre has discovered that these two games are actually the same game, just 3D CyberPuck (1995) is a later version that got renamed and has network support. If you decide to keep just one then obviously keep the later 3D CyberPuck (1995) and give it an AKA in LB, but if you keep both then here is a shareware version of the initial release 3D Ball Blaster (1992) that he found:

[BLAST10.ZIP](https://github.com/exoscoriae/eXoDOS/files/5504709/BLAST10.ZIP)

If you do keep both then I also suggest an entry for 3D Ball Blaster (1992) in the Shareware Upgrade project list

**Comment by exoscoriae** [comment]
I have both on purpose because of the different name and different title screen. It's not as simple as an AKA due to the changed internal graphics.

That said, why do we want the shareware version of the initial release added? I need some context as to why it is different\better than what we currently have. thanks!

**Comment by Python-Exoproject** [comment]
Because currently both our copies have the title screen for "3D CyberPuck", The one in the CyberPuck folder with no version number on the title screen and the one in the 3D BallBlaster folder with a "v3.0" on the title screen (Implying the copy in 3D BallBlaster" is actually the newer copy). @SmilingSpectre file is the actual 3D BallBlaster, although only a shareware copy.

**Comment by exoscoriae** [comment]
ok. replaced 3D Ball Blaster w/ shareware copy.

**Comment by TimberlAndRE-de** [comment]
user erebus44 reported on discord:
```
3D Ball Blaster seems to have a problem after the 5.1 update. I know the changelog says it was replaced with the correct game so I wanted to see what it was.
When you start the game you can get to the main menu but after you choose New Game and then the dificulty it flashes and goes back to the main menu.
I looked at the files and if you edit the start.bat to change "memtst.exe" to "rem memtst.exe" run start.bat instead of start2.bat in the conf file it seems to work, but I am not an expert on this.
```

I checked the conf file:
in v5   "3D Ball Blaster" dosbox.conf calls "start2.bat"
in v5.1 "3D Ball Blaster" dosbox.conf calls "start2.bat"
in WIP  "3D Ball Blaster" dosbox.conf calls "start.bat"

so I guess, the dosbox.conf update is missing in the update.zip ?

Link to the discussion in discord:
https://discord.com/channels/454359114601201666/467028238687010826/799621902217773116

**Comment by Python-Exoproject** [comment]
@SmilingSpectre has also pointed out that the current 4000 cycles in 3D Ball Blaster is slow. 3D Cyber Puck runs at 30000 so maybe go with that for 3D Ball Blaster?

Lastly for both games I have noticed that the option ingame to use sound\music has not been turned on

**Comment by exoscoriae** [comment]
I just tested both games on my end, and they load fine, presumably because my conf is correct
added 3D Ball Blaster (1992) conf file to updater.
turned of FX and Music for both. Enabled mouse for 3d cyberpuck
bumped cycles from 4k to 30k in 3d ball blaster
I hear fx now. still no music though in 3d ball blaster
