### ISSUE TITLE
Constructor (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2111]
Mouse issue is fixed by reinstating the mousex command line that was commented out

**Comment by exoscoriae** [comment]
fixed and added to patch

**Comment by Python-Exoproject** [comment]
Mousex has been reinstated, but at the same time a sensitivity line has been added to the conf with a value of sensitivity=1000 which counteracts the fix. We need to either remove the sensitivity line or set it to sensitivity=200,100 and remove mousex as per ripsaws suggestion. I actually lean towards ripsaws new method of removing mousex and setting sensitivity=200,100 as it seems to be a little smoother.
