### ISSUE TITLE
Suggestion: Modify Aspect Ratio question

### ISSUE THREAD

**Issue by hsellik** [exoscoriae/eXoDOS#2112]
Great release, I really like V5 since I only need a few games, and downloading them separately was quite annoying with V4. Now it was a very convenient experience.

I have one suggestion to make the Aspect Ratio question better. When it asks to turn on Aspect Ratio Y/N, I always consult the manual to see which option enables black bars.

Instead, would it be possible to make it similar as stated in the manual? I found it to be more clear.

```
Would you like to turn on Aspect Ratio? (Y/N)

If set to 'YES', it will put black bars on the side of the game to preserve 
their original format (only in fullscreen mode). 

If you choose 'NO', it will be stretched to fit your monitor.
```

(maybe this is some basic DOS terminology which I am not aware of).

**Comment by exoscoriae** [comment]
I have added details to this question to make it clearer in the project setup file. However I don't plan to change the question as it exists within each individual game's setup. It seems like overkill to explain it every single time.
