### ISSUE TITLE
International Soccer (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2115]
user teknik has found a cd image of International Soccer (1994) and provided a link here: https://www47.zippyshare.com/v/8JytSbwi/file.html

**Comment by exoscoriae** [comment]
we can't use zippy share for files like this. it expires. Going forward, lets please upload stuff to the share drive instead of relying on file sharer's like this. I'll reach out to teknik and see if he still has it.

**Comment by exoscoriae** [comment]
cd image retrieved from teknik. zippyshare is cancer.

Replaced International Soccer w/ cd rom version. Not pushing this to the updater as this is way too large for it.
