### ISSUE TITLE
Leisure Suit Larry 6 - Shape Up or Slip Out (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2117]
It looks like at some point the ScummVM launch option for this game was broken. Its trying to launch the lowres version of LSL6 from the main LSL6CD folder which contains the resource file of the high res version. We usually only offer the "best" option for ScummVM games in eXoDOS so upto you if we fix this to offer both high and low res options, keeping in mind that when eXoScummVM is released we will most likely do a bit of backporting from it into eXoDOS anyway. 

For now setting the scummvm launch commands to use gameid "lsl6hires" will fix it. Two other points to go with this though, 1. the scaler setting in the command line "-g3x" needs to go to "-g2x" as 3x was for the lowres version and, 2. The scummVM wiki says: 

"Leisure Suit Larry 6 hires - If your game comes with a HIRES directory, copy all files from the HIRES directory to the game directory, then copy all files from the AUD and SFX directories to the game directory."

which is currently not so. It seems to have voice and sound but there might be an issue later in the game?

**Comment by exoscoriae** [comment]
fixed.

the resource.aud and resource.fx files do not need to be copied for the version of scummvm we have. their wiki is out of date, and following that advice would cause us to duplicate 420+mb of data, as the resource.aud file would need to reside in the original location for the DOS version and then again in the game folder for scummvm.

Added modified launch.bat file to updater

**Comment by Eulisker** [comment]
The game is currently set to cycles=max. I think it should be around 20000. You can see it in the logo screen. With cylces max the screen flips almost immediately and at 20000 it is somewhat of a smooth scroll.

**Comment by exoscoriae** [comment]
dropped cycles to 20k
removed scummvm launch options from all larry games
