### ISSUE TITLE
Little Big Adventure (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2121]
discord user wysiwyg found an alternate manual:
scan of the original manual, current one is a digital manual
I suggest to replace the current manual

**Comment by exoscoriae** [comment]
replaced

**Comment by SmilingSpectre** [comment]
Our manual is quite low resolution. I found the better one. Uploaded.

Little Big Adventure (1994).pdf

**Comment by exoscoriae** [comment]
replaced
