### ISSUE TITLE
Monkey Island 2 - LeChuck's Revenge (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2122]
discord user wysiwyg found an extra:
- [x] Reference Card
added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I scanned the 

- [ ] Reference Card

the current one is of dubious quality.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
