### ISSUE TITLE
Micro Machines (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2125]
discord user wysiwyg found an image of the disk:

(@exoscoriae i know it's not the right github project / label combination, should we add one for pictures?)

![Micro Machines (1994) disk](https://user-images.githubusercontent.com/67441153/98487138-c5a32280-2221-11eb-9e9a-a66a84417d43.jpg)

**Comment by exoscoriae** [comment]
I think extras is fine for this.

**Comment by exoscoriae** [comment]
added

**Comment by exoscoriae** [comment]
added
