### ISSUE TITLE
Conquests of Camelot - The Search for the Grail (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2126]
Conquests_of_Camelot_-_The_Search_for_the_Grail_-_Map_-_PC.pdf
has watermark "replacementdocs"

**Comment by exoscoriae** [comment]
replaced

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Sierra Catalog
- [ ] Registration Card


added to the github folder

**Comment by exoscoriae** [comment]
added
