### ISSUE TITLE
Legend of Kyrandia Book 2 - The Hand of Fate (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2132]
discord user ArkhangelAzrael found an original manual, scanned version of the cd booklet
(current one is a digital version)
Maybe worth to replace it?

**Comment by exoscoriae** [comment]
not replacing. The existing manual looks better to me, even if it is digital. A full color, full size, manual scan would be worth replacing. Not a b&w cd booklet I don't think.

**Comment by Eulisker** [comment]
I found a scanned

- [ ] manual

It is from the first release where it was just "Fables & Fiends - The Hand of Fate. But it is the same content as the digital one.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
