### ISSUE TITLE
Leisure Suit Larry 5 - Passionate Patti Does a Little Undercover Work (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2133]
discord user ArkhangelAzrael found an extra:
Game Design Document

(https://allowe.com/games/game-designs.html)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by exoscoriae** [comment]
added bedside companion to all 4 games
replaced AeroDork pamphlet
