### ISSUE TITLE
Leisure Suit Larry 7 - Love for Sail (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2136]
discord user ArkhangelAzrael found an extra:
Game Design Document

(https://allowe.com/games/game-designs.html)

added to the github folder

**Comment by Python-Exoproject** [comment]
I've also found the official strategy guide hanging around in the ScummVM project which I've uploaded to the github manuals folder

**Comment by exoscoriae** [comment]
added
