### ISSUE TITLE
Update DOSBox within eXoDOS

### ISSUE THREAD

**Issue by warp16** [exoscoriae/eXoDOS#2137]
eXoDOS 5 contains five DOSBox binaries (listed below) based on version 0.74. When able, please update to version 0.74-3, which resolves a few bugs and security vulnerabilities.

https://sourceforge.net/p/dosbox/news/

\eXo\dosbox\DOSBox.exe
\eXo\dosbox\ece\DOSBox.exe
\eXo\dosbox\ece_svn\DOSBox.exe
\eXo\dosbox\svn\dosbox.exe
\eXo\dosbox\svn2\dosbox.exe

Another instance of DOSBox which is part of LaunchBox (\ThirdParty\DOSBox\DOSBox.exe) was reported on their bug tracker:
https://bitbucket.org/jasondavidcarr/launchbox/issues/5521/update-3rd-party-binaries

**Comment by exoscoriae** [comment]
Versions can not be changed without extensive testing. For example, upgrading ece would cause pixel perfect to be deprecated.
