### ISSUE TITLE
Reach for the Skies (1993)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2138]
This game does not play the intro and has a graphic bug with launchbox

https://www.youtube.com/watch?v=1G-NyURg3Gc&feature=emb_logo

![image](https://user-images.githubusercontent.com/67555221/98797781-512cd700-240d-11eb-8f34-71e653ea0d7f.png)

This game needs also to be cracked:  It has a copy protection who refers to a German manual. 
We have not the manual.

![image](https://user-images.githubusercontent.com/67555221/98797967-9a7d2680-240d-11eb-9f19-f19e4fd63960.png)

**Comment by SmilingSpectre** [comment]
DOSBox is to blame for both problems. Intro corrupted in current (official) version, but not in ECE and Daum. Resident hack works only in Daum.

**Comment by SmilingSpectre** [comment]
Hacked .exe that takes any answer (it doesn't fix intro issue)
[CONTROL.ZIP](https://github.com/exoscoriae/eXoDOS/files/5523978/CONTROL.ZIP)
.

**Comment by exoscoriae** [comment]
great fixes guys. all added
