### ISSUE TITLE
Duke Nukem 3D - Atomic Edition (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2140]
Discord user littlemac noted that Atomic Edition freezes on exit instead of quitting. User config.sys noted that setting memory to 24MB fixes the issue

**Comment by exoscoriae** [comment]
changed and added to updater

**Comment by Python-Exoproject** [comment]
This and Last Express issue havnt synced on my end as yet. As everything else has just checking if its my end or yours.

**Comment by exoscoriae** [comment]
confirmed changed and in updater
