### ISSUE TITLE
Sex Vixens From Space (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2143]
Kudgel has patched this game to correct the horrendous graphics it normally produces, as he did with Planet of Lust. Here is the patch:

[sexvixev.zip](https://github.com/exoscoriae/eXoDOS/files/5534534/sexvixev.zip)

As before point to the new bat, sexvixen.bat, and it will choose which game version to load based on whether VGA is detected or not.

I also note the in Planet of Lust you have a user note telling them the code word that needs to be entered on initial screen. This game has the same need of a code word but no user note. The word is "space" this time around. Lastly for both games it might be worth adding to the user note that when a message is displayed that needs scrolling its PGUP\PGDWN that does this.

**Comment by exoscoriae** [comment]
patch applied. added to updater.

**Comment by Python-Exoproject** [comment]
The dosbox.conf is calling "Sexvixen" but as the exe is also named this it is launching that. Change the call to launch "sexvixen.bat" to fix

**Comment by exoscoriae** [comment]
another example of dosbox not functioning as DOS would. In DOS, there is a heirarchy to commands. If there are multiple files with the same file name, it goes in order from:
.bat
.com
.exe

I, wrongly, assumed dosbox was doing the same thing. good catch.
