### ISSUE TITLE
Spelljammer - Pirates of Realmspace (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2146]
Game isnt cracked and crashed if correct word was given. @SmilingSpectre has fixed it with v1.1 and cracked. Here is archive:

[Spelljammer_-_Pirates_of_Realmspace_1992.zip](https://github.com/exoscoriae/eXoDOS/files/5534529/Spelljammer_-_Pirates_of_Realmspace_1992.zip)

**Comment by exoscoriae** [comment]
replaced updated files. added to updater.
