### ISSUE TITLE
Alone in the Dark 2 (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2156]
ArkhangelAzrael has found
- [x] quality upgrade for "Playing Cards" extra

added to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by TimberlAndRE-de** [comment]
Swizzley found

- [ ] good girl flyer

added to the github folder

**Comment by exoscoriae** [comment]
added
