### ISSUE TITLE
Transylvania (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2157]
I found a Guide: "A Shortcut Through Adventureland (1984)"
It's an hint guide for a lot of (sierra) adventures from the 80s, at least three of them are in eXoDOS (the bold ones). Maybe it's worth to be added to them?

The Games:
**Transylvania (1986)**
Death in the Caribbean
Hi-Res Adventure #0: Mission Asteroid
Hi-Res Adventure #1: Mystery House
**Hi-Res Adventure #2: The Wizard and the Princess / Adventure in Serenia (1982)**
Hi-Res Adventure #3: Cranston Manor
**Hi-Res Adventure #4: Ulysses and the Golden Fleece / Ulysses and the Golden Fleece (1982)**
Time Zone
Hi-Res Adventure #6: The Dark Crystal
The Blade of Blackpoole
Escape from Rungistan
Sherwood Forest
The Mask of the Sun
The Serpent's Star

**Comment by exoscoriae** [comment]
added to the three bold games
