### ISSUE TITLE
Ignition (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2162]
There is a random crash bug in this game. It was reported by discord user DaniGMX and I have experienced it on three occasions. The first time was single race near the end of the last lap on the first track, the second was during a championship, also on the first map, and the last was a single race on the first lap of the second track. DaniGMX believes he has a copy that doesnt have this issue.

**Comment by SmilingSpectre** [comment]
Readme:

[quote]Problem
-------

Ignition crashes in the game at different times and returns to
windows desktop. As it seems, without any reason.

Solution
--------

Turn off the perspective corrected polygons in the gfx menu.
Our perspective polygons routine seems to have problems to work
on some computer systems. If you really want to use perspective
corrected polygons, wait for the 3dfx patch to be released later 
this fall.[/quote]

**Comment by SmilingSpectre** [comment]
So maybe it's updated version later?..

**Comment by exoscoriae** [comment]
As there is not another copy posted here to check, I have to assume he doesn't have a copy that is immune to the issue.

I went ahead and disabled perspective polygons as suggested by the notes @SmilingSpectre found.

Added to updater.
