### ISSUE TITLE
Bandor - The Search for the Storm Giant King (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2163]
These games (there are three titles run from this bat) are crashing during the intro due to issues with soundblaster drivers. To fix use the set sound command before the games execute and point it to the .drv files in Bandor 1 folder. Also need to set "sbtype=sb2" in conf.

**Comment by exoscoriae** [comment]
There are only 2 games, as the third has never been found.

That said, the game no longer crashes and the changes have been rolled over for the updater.
