### ISSUE TITLE
Prehistorik (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2166]
FX are not working in this game when SB is chosen due to the config file for SB not being the correct file. This is causing the SB choice to use the MT32 config file. Put the file included in this archive into the games \sb\ folder.
[Prehistorik_SB.zip](https://github.com/exoscoriae/eXoDOS/files/5570722/Prehistorik_SB.zip)

As for the file that is already in that folder, CRAWAGA.CFG, Im not sure what it does but its not a config file for game sound and doesnt need to be there.

**Comment by exoscoriae** [comment]
changed and added to updater
