### ISSUE TITLE
Elvira - The Arcade Game (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2168]
needs crack

**Comment by TimberlAndRE-de** [comment]
also I noticed that the included code sheet doesn't fit the code questions.
You need to use the manual (english part of it) to find the correct code word

**Comment by exoscoriae** [comment]
cracked

**Comment by Python-Exoproject** [comment]
If we cant crack it and the games standard approach to typing a bad password is the above letting you into the game just to immobilize the character this could be interpreted as a game issue. It might be worth a user note to say the game is not currently cracked and to use the game manual to pass the check.

**Comment by exoscoriae** [comment]
recracked. confirmed it works this time. no password screen pops up at all.
