### ISSUE TITLE
Flash Traffic: City of Angels (1994)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2169]
I found an MPEG REELMAGIC version of this game.
Not tested
Added to the Games Submisions Folder Github Folder

**Comment by bigjim161** [comment]
Ok this is useless, because dosbox does not support the REEL MAGIC card.

**Comment by exoscoriae** [comment]
correct. I do keep a folder full of reelmagic games however. In the event it is ever supported.

I currently have
Dragon's Lair
Entiity
Psychotron
Return to Zork
Space Ace
and The Horde

I added this copy of Flash Traffic to it. Thanks
