### ISSUE TITLE
Civil War Battleset (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#217]
it's not the manual (or readme) for the game but for the CIVILSET v2.4 - EGA Scenario Setup/Editor for CIVILWAR BATTLE SET (an editor for the game). Should be an extra instead of a manual

**Comment by SmilingSpectre** [comment]
Uploaded manual (it's in the game dir, but still!)

**Comment by TimberlAndRE-de** [comment]
thx, uploaded to github-folder
