### ISSUE TITLE
Betrayal at Krondor (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2170]
discord user Loren found as extra:
- [x] Strategy Guide
uploaded to github folder
[link to discord post](https://discordapp.com/channels/454359114601201666/492422228281917470/779182688208027649)

@XavierVelo noted:
- [x] map has removable watermark (replacementdocs)
- [x] reference card has removable watermark (replacementdocs)

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found the original novel series by Raymond Feist

- [ ] Raymond Feist - The Riftwar Legacy 1 - Krondor the Betrayal
- [ ] Raymond Feist - The Riftwar Legacy 2 - Krondor the Assassins
- [ ] Raymond Feist - The Riftwar Legacy 3 - Tear Of The Gods
- [ ] Raymond Feist - The Riftwar Legacy 4 - Jimmy and the Crawler

**Comment by exoscoriae** [comment]
where are these? I don't see them in the synology

**Comment by exoscoriae** [comment]
added
