### ISSUE TITLE
Computer Edition of Risk, The - World Conquest Game (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2177]
discord user Jormungandr89 scanned his original manual from the 1989 version:

[...]I noticed that this release (https://www.mobygames.com/game/dos/computer-edition-of-risk-the-world-conquest-game), Risk by Virgin/Leisure Genius, has the manual from a 1991 release.  It's a good scan, and the content is primarily the same, but it isn't exactly the same as the 1989 manual I have.  It appears the game itself in eXoDOS is the 1989 IBM Compatible/Tandy release.  Is there any interest in having the "most technically correct" manual scanned in?  The current content is perfectly fine, but from a preservation standpoint, I mean?[...] ([link](https://discordapp.com/channels/454359114601201666/492422228281917470/781255744736854056))

added to the github folder

**Comment by exoscoriae** [comment]
added as extra
