### ISSUE TITLE
MegaRace (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2183]
Discord user Ransom discovered that cycles=5000 avoids some speed issues when getting a turbo boost going over a boost arrow in the game. 

He also discovered that to use a joystick successfully in the game requires the conf to use joystick=2axis and timed=false as well as having to calibrate the joystick via game install program.

**Comment by exoscoriae** [comment]
cycles changed, joystick options ignored. That is not something we are currently trying to support out of the box, but it is good to be noted here.

**Comment by exoscoriae** [comment]
added to updater
