### ISSUE TITLE
Computer Edition of Risk, The - World Conquest Game (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2184]
discord user Jormungandr89 scanned the extras of his big box copy:
- [x] registration card
- [x] subscription card
- [x] envelope
- [x] disk-order card
- [x] virgin advertisement catalog
- [x] letter from virgin (insert of advertisement catalog)

all added to the github folder

**Comment by exoscoriae** [comment]
added
