### ISSUE TITLE
Hoyle Classic Card Games (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2185]
Via my work on eXoScummVM I discovered that our copy of this game (which is the same as the version we have in eXoDOS) has a corrupted resource file. Find a good copy for eXoDOS here: https://archive.org/details/CLASSIC_201803

**Comment by exoscoriae** [comment]
replaced files.
Also discovered that in the run.bat, option 8 (soundcanvas) was impossible to select. Fixed.
Added to updater.
