### ISSUE TITLE
Slipstream 5000 (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2186]
Discord user Ransom has detected an issue with Slipstream 5000. When starting a championship race after choosing MT32 the game will freeze on a black screen. Sound Canvas and SB work properly.

**Comment by exoscoriae** [comment]
ripsaw forwarded me this link which shows game's that falsely claim mt-32
https://en.wikipedia.org/wiki/List_of_MT-32-compatible_computer_games

Slipstream is on the list. It is just sending general midi data.

I have disabled mt32 as a launch option.

**Comment by TimberlAndRE-de** [comment]
there's an abandoned run.bat in the game folder under SLIP5000/
it never get's called and also still contains MT-32. I guess it's from the time before the network option was added?

**Comment by exoscoriae** [comment]
MT32 folder removed
extraneous run.bat removed
