### ISSUE TITLE
Screamer (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2187]
Discovered that setup crashes with cycles at max. Set cycles to between 70000 and 80000 seems to avoid this crash and still play the actual game at a reasonable frame rate

**Comment by exoscoriae** [comment]
the user has no normal access to SETUP through the game. It doesn't make sense to throttle back the speed\gameplay for every user in the off chance that one user might go change the conf and run the setup file. Presumably, if they can change the conf for the setup, they can change the cycles as well?

**Comment by Python-Exoproject** [comment]
I mentioned it as 80000 didnt seem to affect gameplay on my system and it may not be obvious to anyone trying to access setup in the future (including us) that its a cycles issue. At least its githubbed now so is noted for future reference. Ill move this back to the que just for a final consideration, but if you still disagree just move it straight to the closed que.

**Comment by exoscoriae** [comment]
80k feels slower on my laptop. but ... I also often don't like relying on max, as systems will only get faster in the future and thought could cause unforeseen problems. 

Also, is there any good reason we have this set to 16mb of ram? that seems incredibly low for a game from 1995 that is 3D. I bumped to 32mb and saw no issues with the race. I didn't see any issues in the github, but maybe you have something in your notes?

**Comment by Python-Exoproject** [comment]
Your call then on the 80k, different systems with different results and all that. As for ram, no I have no notes on that
