### ISSUE TITLE
Cyril Cyberpunk (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2188]
Discord user Xavier_Velo has pointed out that Cyril Cyberpunk saves are broken. You need to create a "SAV" folder in the \CyrilCyb\cyril folder. He has also pointed out that the game is running on so many cycles that when viewing instructions you cant accurately scroll to the last page without skipping right past it. cycles=10000 seems to work better in that regard and gameplay is still fine, though loading a level takes a little longer. Lastly the F3 key is supposed to access the load screen but instead shows a black screen. You can still access load game via pressing esc though so not as big a deal as the other items.

**Comment by exoscoriae** [comment]
added SAV folder. Changed cycles. Rolled changes to updater.

I was unable to locate a clean cd\floppy copy in a brief search. old-games.ru has a hybrid crack copy, but the f3 key still doesn't work. This would be a game that would be nice to find original media for.

**Comment by Python-Exoproject** [comment]
You only went to cycles 60000, not 10000? The instructions still scroll past too fast at 60k for me. The gameplay is ok for me at 10k.

**Comment by exoscoriae** [comment]
Sounds like it didn't sync. Was the file date changed?

**Comment by Python-Exoproject** [comment]
Yeah looks like it, date is 16/06/20. Have you synced since that change?

**Comment by exoscoriae** [comment]
verified it is set to 10k cycles and is in updater as such.
