### ISSUE TITLE
Disciples of Steel (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2189]
discord user jelcynek found an alternate manual
the game isn't cracked yet (kudgel is working on it) so it needs the original manual for codes
the current one is from a cd-release, so the code questions won't fit, but the quality is better.

I suggest to keep the current and add the alternate manual as an extra for protection code until kudgel has cracked the game)

added to the github folder

**Comment by Python-Exoproject** [comment]
Created a separate issue for the fact it needs a crack (issue #2190 )

**Comment by exoscoriae** [comment]
added as an extra
