### ISSUE TITLE
Disciples of Steel (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2190]
Currently not cracked.

There is also a related issue about an alternate manual to add to exodos as the manual we have is not the one for our version (issue #2189 ). It has been also suggested we could replace this copy of the game with the CD release to match our current manual as an alternate solution

**Comment by exoscoriae** [comment]
cracked

**Comment by Python-Exoproject** [comment]
Currently using 10k cycles but this is too fast. I used around 5k and it was a reasonable compromise between loading times and movement of characters on map and in encounters

**Comment by exoscoriae** [comment]
loading time seems very long at 5k. framerate during the intro was abysmal.

map seemed ok... guess I'll use 5k.
