### ISSUE TITLE
Advanced Tactical Fighter II

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2192]
From submission channel, proposed by Ganonthegreat. Copy located in dropbox\personal folders\smiling spectre\dos\submission channel.

European version of Airstrike USA. @SmilingSpectre says its similar in game structure and most likely gameplay but files are completely different and it came from a CD vs current Airstrike USA floppy which is under 1mb.

Here is the manual: 
[MANUAL.zip](https://github.com/exoscoriae/eXoDOS/files/5616103/MANUAL.zip)

**Comment by exoscoriae** [comment]
added to airstrike usa as a launch option
