### ISSUE TITLE
Diggers v1.94

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2202]
From submission channel, proposed by Xavier_Velo. Copy located in dropbox\personal folders\smiling spectre\dos\submission channel.

This is a more recent version than our current v1.5

**Comment by XavierVelo** [comment]
Diggers 1.94 is different release not update I belive. I think leaving both version would be better than replace. 1.5 have multi language support which 1.94 lacks for example.

**Comment by exoscoriae** [comment]
game has been updated to v1.94

v1.5 was saved in case it is needed for later language packs
