### ISSUE TITLE
Motor City (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2228]
There is a German CD version (called Oldtimer) and it has been suggested that our English copy is a CD rip when compared. This is partly due to the fact that all .flm files in our copy are the same length, date, and CRC. According to Xavier_Velo in game suggestions channel one temporary fix until we find a copy of the English CD is to copy all the .flm files from the German version of the game. 

There has also been located on Abandonia an alternate copy of the file containing all the Engines. Apparently its an official update. To use it overwrite the GAME.STC file found in the \gfx sub directory with the one found in engine.zip

Copies of the German CD and engine.zip are found in sync\personal folders\smiling spectre\dos\submission channel\motor city - oltimer

**Comment by Python-Exoproject** [comment]
Further information from @SmilingSpectre:

Known English version is some early prototype, it seems, as it have only 25 engines, and so research stopped somewhere in early game. You never able to research anything after that.

German CD version is fine.

So some user analyzed German data file and injected all missing engines into English one. (It's about 100 of them). All you need is to replace original game.stc file with that one. Thus it's not something "extra", it's obligatory patch.
He explained the format, and it seems quite plain and without text (except engine name), so probably replacing file with German CD one can do the same thing, or even better - as German file is bigger. But I am guessing here.

**Comment by exoscoriae** [comment]
replaced the games.stc file and replaced all the flm files. Also added german cd to the CD subfolder.

Added an update file to the updater that replaces the files but does not add the CD
