### ISSUE TITLE
Switch to OpenglNB

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2232]
This issue is to mark the discussion we've had regarding a switch from our default output being overlay to openglnb. The end of the discussion was the decision to write a script using ssr that converts all dosbox confs with output=overlay (which should all be ECE and Vanilla) to output=openglnb which would be rolled out for users to test, if there are no issues after awhile we will consider the move to a permanent change. I will specifically test all custom dosbox games that might be caught up when script is rolled out as they are the most likely to cause any potential issues.

**Comment by exoscoriae** [comment]
[Convert to OpenGLnb.zip](https://github.com/exoscoriae/eXoDOS/files/5788064/Convert.to.OpenGLnb.zip)

Ok, I wrote this script and ran it on a second copy of the files. It appeared to run fine. I figured I'd upload it for you to look at first, and then we can roll it out to the discord channels to see who wants to give it a go over there.  

Worth noting that if they run the updater *after* running this, it will reset at least a handful of these files. So the converter would have to be run again.

**Comment by Python-Exoproject** [comment]
Working ok on my end. I did find one game that still has all the spaces in the conf meaning the change bat fails. Game is Sid Meier's Civilization (1991)

**Comment by exoscoriae** [comment]
ok. well, this is fine for testing purposes then. If we roll the change out to every game, then we just have to remember to change Civ manually.

**Comment by exoscoriae** [comment]
converted the WIP to openglnb

**Comment by exoscoriae** [comment]
worth noting that any FMV based games still need to be converted to ECE as well
