### ISSUE TITLE
Mahjong (1986)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2238]
The keyboard do not response with the vanilla dosbox
It works with the svn dosbox ,but in black and white.

**Comment by SmilingSpectre** [comment]
Current set is unresponsive - confirmed.

SVN dosbox is B/W - unconfirmed. Worked just fine if change run string to ".\dosbox\svn\dosbox.exe" -conf "%var%\dosbox.conf" -noconsole -exit

@bigjim161 game requires CGA (that is in the current conf), without it it's really B/W.

**Comment by bigjim161** [comment]
@SmilingSpectre well done

**Comment by exoscoriae** [comment]
that may be because the version of dosbox in *my* SVN folder is DAUM. Not SVN. So there may have been some confusion here?

I changed it to ECE and it works fine. Thanks guys
