### ISSUE TITLE
Ishido - The Way of the Stones (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2239]
found extras: 
- [x] code wheel (interactive)
- [x] storybook

added to the github folder

proof images:
(from [ebay](https://www.ebay.com/itm/Rare-Ishido-The-Way-of-Stones-Accolade-1990-5-25-3-5-disks-IBM-Tandy-in-Big-Box/264967236435?hash=item3db1472b53:g:dMcAAOSwJ7Bflh7m))
![grafik](https://user-images.githubusercontent.com/67441153/101992565-a120e700-3cb4-11eb-86f4-ce40540265af.png)
![grafik](https://user-images.githubusercontent.com/67441153/101992568-a8e08b80-3cb4-11eb-9596-f1f43715a2ec.png)
![grafik](https://user-images.githubusercontent.com/67441153/101992571-ae3dd600-3cb4-11eb-99df-4942e4e32a0e.png)
![grafik](https://user-images.githubusercontent.com/67441153/101992578-b85fd480-3cb4-11eb-8f6b-4277be4f5b81.png)

**Comment by exoscoriae** [comment]
added
