### ISSUE TITLE
Flashback - The Quest for Identity (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2248]
I found 
- [ ] manual with better quality and more informations/content
Maybe worth to replace the current one?

added to the github folder

**Comment by exoscoriae** [comment]
I'm really not sure how I feel about this one. I really prefer to presentation of the original. It actually looks like a booklet, while the new one is super "white" and not as detailed on each page.

I think the best solution to me is a better scan of the original one. I'll add this one as an extra manual I suppose
