### ISSUE TITLE
King's Quest IV - The Perils of Rosella (1988) (SCI)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2255]
There is an official patch to fix potential lockups at the waterfall scene in the SCI release which is not applied to our version. Please find a copy here: 
[KQ4(KQ4FIX).zip](https://github.com/exoscoriae/eXoDOS/files/5695862/KQ4.KQ4FIX.zip)

**Comment by exoscoriae** [comment]
added and applied to updater
