### ISSUE TITLE
Blue Balls (1991)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2258]
-The game runs too fast (3000 cycles), it's unplayable.  1000 cycles seems to be a good compromise.
(The game uses the numeric keypad)

-The current name of this game in EXODOS is "Blue Balls" while on the first screen, this game is called "Blue Balls III". 
Maybe we can change the name of this game in Exodos.

**Comment by SmilingSpectre** [comment]
Confirmed.

Will add Blue Balls and Blue Balls II later.

**Comment by exoscoriae** [comment]
According to the readme file it is not "Blue Balls III" 
It is Blue Balls version 3.0

A third version is different from a third game. 

After looking at all three versions, it is clear they are very slight updates from the last. Not full blown sequels. I have added an option to launch all three versions, but I believe the game entry should remain named as is.
