### ISSUE TITLE
Last Express, The (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2259]
User note says 2 CD's to swap through but its actually 3 CDs

**Comment by exoscoriae** [comment]
fixed. added to updater

**Comment by Python-Exoproject** [comment]
For me user note still says 2cd's. Maybe a sync issue but everything else has synced ok at this point so would like to confirm if its my end or yours.

**Comment by exoscoriae** [comment]
confirmed it is on my end and in the updater
