### ISSUE TITLE
Commander Keen 1 - Marooned on Mars (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#226]
has watermark replacementdocs
not a manual but a hint sheet for the first three keen episodes

**Comment by exoscoriae** [comment]
removed watermark and moved files to the extras section. 
Keen 1 now has a txt manual that was distributed with a later version of the game. Less of a manual, more of a game desription. But it is the closest thing to a manual that i ama ware of.

Keen 2 no longer has any manual. All versions I checked had no text documents.

Keen 3 no longer has any manual. All versions I checked had no text documents.

Commander Keen 6 is the only game apogee\3d realms claims to actually have a real manual for.
