### ISSUE TITLE
Third Courier, The (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2262]
found

- [ ] code slider

I need to find out how to create an interactive one out of these images. Until then, it could be added as is.
added to the github folder

**Comment by bigjim161** [comment]
I found 
- a map of better quality
- a clue
- an alternative code slider (passcoder)

added to the github folder

**Comment by exoscoriae** [comment]
slider added.

**Comment by exoscoriae** [comment]
added extras

**Comment by Python-Exoproject** [comment]
[Third_Courier_The_-_Passcoder_1989.zip](https://github.com/exoscoriae/eXoDOS/files/14662951/Third_Courier_The_-_Passcoder_1989.zip)

Interactive version created by Digitoxin from discord

**Comment by exoscoriae** [comment]
so cool
