### ISSUE TITLE
Operation Market Garden - Drive on Arnhem, September 1944 (1985)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2264]
found a

- [x] manual

it contains infos about c64, Atari ST and Amiga, but since we already have a reference card, it could be added though
(in addition, many SSI games do not have a separate IBM manual, but only the reference card)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by bigjim161** [comment]
I found a refence card for IBM (extra)

Added to the github Folder

**Comment by exoscoriae** [comment]
added
