### ISSUE TITLE
Gunship 2000 (CD-ROM Edition) (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2270]
Xavier_Velo posted a cracked image of Gunship 2000 to check out. Found here: https://discord.com/channels/454359114601201666/467028238687010826/789197686992666634

**Comment by exoscoriae** [comment]
replaced w/ cracked copy. Added to updater.

**Comment by TimberlAndRE-de** [comment]
agathosdaimon reported in discord:

Gunship 2000 crashes instantly upon a weapon hitting an enemy - has this been reported? the version of GS2000 being used in exodos seems odd too, in that its file size seems much much smaller than that of the vesion of gs2000 i have and an iso of gs2000 is usually around 30 mb i think, whereas the game folder in exo is on 7mb.
i did an uninstall and re-download but stll same file size and the crashes and closes dosbox as soon as i hit anything with a weapon , also the map function which is F10 doesnt work.

**Comment by SmilingSpectre** [comment]
Seems, something broke during hack (or maybe it was broken before that?). Anyway, I uploaded seemingly fine (but maybe not cracked) CD. "30Mb" claim is not confirmed: I found 3 discs, one is uploaded, second, in compilation, is identical, third, German, is more or less the same size.

**Comment by exoscoriae** [comment]
this issue was already fixed with the 5.1 update
