### ISSUE TITLE
Darklands (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2271]
Xavier_Velo found an update for the Roland driver in Darklands. Found here: https://discord.com/channels/454359114601201666/467028238687010826/789210013667033159

**Comment by exoscoriae** [comment]
they don't appear to have been needed as we were not using v7 (as described in the readme). However I added them anyways. I don't plan on adding this one to the updater as I don't think it really changed anything.

**Comment by Python-Exoproject** [comment]
Listening to what Xavier_Velo uploaded with his version of Darklands I can hear the water drips during the intro along with other sound effects. These are not present in the latest synced version of ours with MT32 selected. Ive traced it down to 1 file that makes the difference and it seems that getting SB fx with MT32 music isnt so much down to the patch as it seems to be a hack, albeit a good one that gives fx when using MT32. If you replace one of the SB files (PSOUND.DLC, most likely the music file) with a renamed copy of the roland one (RSOUND.DLC) and set the config for SB you get the desired result.

Here is a zip with the updated files, just extract into the \MT32 folder. [DarklandsMT32&SB.zip](https://github.com/exoscoriae/eXoDOS/files/5782436/DarklandsMT32.SB.zip)

**Comment by exoscoriae** [comment]
replaced and confirmed sounds. updated the updater.
