### ISSUE TITLE
Mad Dog II - The Lost Gold (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2274]
There is an issue with the game giving a sound error message at certain points in the game. Here is a save game just before one of these points provided by Ransom from discord: [STATE.zip](https://github.com/exoscoriae/eXoDOS/files/5762909/STATE.zip)

There is a patch for this issue that I found, one for SB and the other for SB16. Here: [maddog2.zip](https://github.com/exoscoriae/eXoDOS/files/5762911/maddog2.zip) and Here: [maddog2b.zip](https://github.com/exoscoriae/eXoDOS/files/5762912/maddog2b.zip)

The patch removes the error message but the game crashes out after I fight the guy on the Maxim Machine Gun.

There is also a patch on patches scrolls for the first game, not sure if it might be needed or not.

**Comment by Python-Exoproject** [comment]
Played around a bit more with it. I managed to get no crash or error message in ECE by setting "sbtype=sbpro1", 8000 cycles, and using the games setup to change it over to using sound blaster pro. Here is an install with the change made: 
[MADDOG2.zip](https://github.com/exoscoriae/eXoDOS/files/5770075/MADDOG2.zip). You can still use the above savegame for testing but at least for me it seems the patch is unnecessary with these edits made.

**Comment by exoscoriae** [comment]
great work =) fixed and added to updater
