### ISSUE TITLE
Commander Keen 6 - Aliens Ate My Baby Sitter! (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2276]
Not cracked. Start a new game and copy protection asked.

**Comment by Python-Exoproject** [comment]
Discord user Eulisker has uploaded a cracked copy of Keen 6 which I upload here: [keen6.zip](https://github.com/exoscoriae/eXoDOS/files/5893734/keen6.zip). I'm however not so keen ;-) to use it as its v1.0 and ours is v1.4

**Comment by TimberlAndRE-de** [comment]
On AL there is also a v1.5 maybe? https://www.legendsworld.net/adventure/game/3001

**Comment by TimberlAndRE-de** [comment]
found the changelog:

[1.4.7] Aliens Ate My Baby Sitter!

	Complete Title: 
	Commander Keen in "Aliens Ate My Baby Sitter!"

	Original Release Date:
	November 1991 (DOS)

	Known Versions:
	v1.0		-	Initial public release
				Both CGA and EGA versions available

	Special Demo
	Version		-	EGA version only
				Only four levels playable
				Other levels blocked off and have Yorps
				sitting on 'DEMO' signs
				Keen starts with grappling hook
				E+N+D cheat restarts current level
				Added ordering info

	Promotional
	Release	Version	-	Release by Precision Software Applications
				EGA version only
				Only four levels playable
				Other levels blocked off and have Yorps
				sitting on '????' signs
				Keen starts with grappling hook
				Removed E+N+D cheat
				High Score table changed
				Ordering info changed

	v1.4 		-	Second commercial version, changes compared to
				v1.0
				Both CGA and EGA versions available
				Fixed game-ruining bug in which collected gems
				would not be saved
	       			Added bug wherein Molly doesn't stay in her
				cage properly, making the final level easier
				Added "Fix Jerky Motion" option
				Added support for four-button joysticks
				Added B+A+T cheat
				Most cheats now have to be enabled with
				A+2+ENTER
				Changed background color of end sequence
				F10+P cheat no longer freezes game
				Updated copyright date to 1992

	v1.5		-	Third commercial version
				Both CGA and EGA versions available
				Fixed bug where Molly doesn't stay in her cage
				Fixed typo in Bloogfoods, Inc. entrance text
				Fixed flashing arrow in ending sequence (its
				background remained grey in v1.4)
				F10+P cheat once again freezes game

**Comment by TimberlAndRE-de** [comment]
all playable cracked versions on the net are 1.0
there are disc images of 1.5 : 
[CKeen6_v1.5.zip](https://github.com/exoscoriae/eXoDOS/files/5894389/CKeen6_v1.5.zip)

but it's not cracked of course....  maybe Kudgel can help with this ?

**Comment by TimberlAndRE-de** [comment]
Ha! found a crack for all versions: 👍 
[pogo6.zip](https://github.com/exoscoriae/eXoDOS/files/5894833/pogo6.zip)

I tested with our 1.4, worked. But maybe @Python-Exoproject / @exoscoriae you want to use the 1.5 above?

**Comment by exoscoriae** [comment]
ok. v1.5 disks were added, installed, and then pogo6 crack was added on that. conf was then modified for all of this. game tested and works.

next time someone messages me on discord to tell me the have a cracked version of Keen, I will tell them to jump off a cliff (and send them this link).

**Comment by Python-Exoproject** [comment]
Maybe im having a sync issue, but the version that is synced for me is still our original uncracked v1.4, not the v1.5 cracked copy mentioned above

**Comment by exoscoriae** [comment]
repacked it. seems the sync had reverted?
