### ISSUE TITLE
Leisure Suit Larry 7 - Love for Sail (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2277]
Found this patch to update the game. It does:

II: WHAT THE PATCH FIXES

This patch upgrades Leisure Suit Larry 7: Love for Sail! to version 1.2
and corrects the following problems:

* Lockup when passing gas in the casino.
* Crash when typing more than 20 characters in the text box
* Error 48 when saving and restoring games
* Random lockups

Here is a copy: [LSL7(LSL7PAT).zip](https://github.com/exoscoriae/eXoDOS/files/5770232/LSL7.LSL7PAT.zip)

**Comment by exoscoriae** [comment]
applied patch
added to updater
