### ISSUE TITLE
Zoop (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2279]
discord user wysiwyg found front and back covers:

![Zoop (1995)_image_front](https://user-images.githubusercontent.com/67441153/103703759-6b67d900-4fa8-11eb-9e84-a7046f3a171a.jpg)
![Zoop (1995)_image_back](https://user-images.githubusercontent.com/67441153/103703761-6c006f80-4fa8-11eb-9b81-e9c209eef0ab.jpg)

**Comment by exoscoriae** [comment]
added
