### ISSUE TITLE
Eye of the Beholder II - The Legend of Darkmoon (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2285]
Until a sample accurate sound patch has been added to another version of dosbox we need to use dosbox-x to overcome some sampling issues. X doesnt work with the All Seeing Eye tool so that option still needs to be on ECE and as a result still has the sample issue until the patch is added.

For reference here is some videos of the sample issue and a savegame at the point for testing.
[EOB2.sound.issue.zip](https://github.com/exoscoriae/eXoDOS/files/5782713/EOB2.sound.issue.zip)

**Comment by exoscoriae** [comment]
ripsaw discovered this is a timing issue. it has been patched using tsr that forces dosbox to read the files at a slower pace more in line with original hardware.  This is something to keep in mind going forward for other oddball issues like this where we have missing sounds or other asset drop outs.

**Comment by exoscoriae** [comment]
reverted launcher back to using ECE for both versions.

**Comment by kcgen** [comment]
This is great news @exoscoriae - I take it the TSR might be game-agnostic, so could be started up ahead of other problematic games?

I remember when I was looking into this one - I could get Staging to /sometimes/ pass, but not reliably. 
Likewise, about 30% of the time I could also get DOSBox-X to fail - at that point, I didn't have a clear path to solve it, and gave up. ripsaw8080 to the rescue :rocket:
