### ISSUE TITLE
Voyeur (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2287]
discord user SysopGrace found

- [ ] a manual (digital version)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual (booklet but from the original release. contains the same informations as the current one but looks much more official, current one is from a remastered steam version)

added to the github folder

**Comment by exoscoriae** [comment]
replaced, added other to extras
