### ISSUE TITLE
Cyril Cyberpunk (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2290]
Exo has expressed interest in obtaining the originals for this game in this issue: https://github.com/exoscoriae/eXoDOS/issues/2188#issuecomment-754776356

**Comment by TimberlAndRE-de** [comment]
@Python-Exoproject it's the same issue as #10 , right?

**Comment by Python-Exoproject** [comment]
Looks like it might be, whoops
