### ISSUE TITLE
Epic Pinball - The Complete Collection (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2299]
There seems to be a screen tearing issue on some of the tables when output has been set to OpenglNB. With Timber's help we have tried a few different settings to overcome the issue, but any that worked used to much processing and caused choppy sound. Therefore this game is best left on Overlay unless something else is discovered.

**Comment by exoscoriae** [comment]
after running openglnb conversion, this one was set back to overlay
