### ISSUE TITLE
Pro Pinball - Big Race USA (1998)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2301]
Same issues (can do higher audio quality, res, cant use daum due to shift issue, etc) that Timeshock! has so ill just link here: #2297 

Three differences for this game though are:
1. There is no hissing\screeching issue to fix, 
2. We need to set the cycles to match whatever we decide for Timeshock as they are currently only 75000,
3. If you are going to add the higher res I couldnt get both max colours and max res to work together due to "Not enough Memory" despite trying various settings from memsize=32 upto memsize=1024, so we will have to choose with of these to prioritise unless you can get both working.

If you dont do the switch to X (and therefore openglnb) for the res increase then we still need to change this one to openglnb in its current dosbox build to overcome the window size problem that the game shares with many FMV games.

**Comment by exoscoriae** [comment]
cycles increased to 120k
switched to openglnb
changed to X, added vmemzise=8, and fullres=desktop
went to 16 million colors

**Comment by Python-Exoproject** [comment]
Inside the game if you enter the settings menu, select audio, select configuration, you can select custom. From here you can increase audio quality to "Very High" which will increase sound channels and sample rate. Then exit the menus to save

**Comment by exoscoriae** [comment]
modified
