### ISSUE TITLE
Bedlam (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2303]
not sure if its LB fuzzy logic issue or hardcoded wrong but user Eulisker has reported that selecting the manual for Bedlam (1988) is linking to the manual for Bedlam (1996)

**Comment by TimberlAndRE-de** [comment]
It's fuzzy LB logic!
Since there is no manual for Bedlam (1988) set in the MS-DOS.xml and also no manual file named "Bedlam (1988).something", LB automatically fuzzy searches for the next best one
No solution here except finding the manual for Bedlam (1988) I guess ...

**Comment by exoscoriae** [comment]
yea. this is a none issue. nothing we can do about it other than finding the missing manual.
