### ISSUE TITLE
Missing gus=true

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2306]
parric discovered that three games that have a GUS option do not have gus=true set. They are:

Descent II (1996)
Descent II Vertigo Series (1996)
Hi-Octane (1995)

As an FYI with Descent II and Descent II Vertigo GUS makes the intro video stutter, intro is fine with other sound choices. Parricc has noted that the 3dfx versions of both these games have no music when GUS selected. I assume its to do with the 3DFX patch itself.

**Comment by Python-Exoproject** [comment]
@kcgen I was about to close of this issue of ours but thought the points regarding Descent II and Descent II Vertigo might be relevant to you?

We have a stutter during the intro in both games when GUS is selected. Also when using 3DFX GUS plays no music at all once you are past the intro into the game proper.

**Comment by kcgen** [comment]
Thanks for the @Python-Exoproject.
For GUS, a slower system profile is needed - and there's not much wiggle room for the sweet-spot.  Try these:

**`dosbox.conf`** :
``` ini
[cpu]
core = dynamic
cycles = 40000

[dosbox]
machine = vgaonly
memsize = 24
startup_verbosity = quiet

[gus]
gus = true

[dos]
xms = true
ems = false
umb = false

[speaker]
pcspeaker = false
tandy = off
disney = false

[midi]
mididevice = none

[mixer]
rate = 48000
```

**`descent.cfg`**:

``` ini
DigiDeviceID8=0xe024
DigiDeviceID16=0xe026
DigiPort=0x240
DigiIrq=5
DigiDma8=3
DigiDma16=3
DigiVolume=8
MidiDeviceID=0xa00a
MidiPort=0x240
MidiVolume=8
RedbookEnabled=0
RedbookVolume=8
StereoReverse=0
GammaLevel=0
DetailLevel=4
JoystickMin=0,0,0,0
JoystickCen=0,0,0,0
JoystickMax=0,0,0,0
LastPlayer=EXO
LastMission=
VR_type=0
VR_resolution=0
VR_tracking=0
MovieHires=0
```

 - Boosting cycles beyond 40k fixed will throw timings off.
 - Using the auto-scheduler, `cycles = max` and even limiting it to 40k `max 90% limit 40000` will throw things off.
 - Using a VESA mode (machine = .. ) will require more cycles for acceptable gameplay, so `vgaonly` is needed along with low-resolution movies in descent's config. 

I'd say this produces a nice period-correct GUS experience of a fast 486.

When 3dfx came along, games were long past using the GUS. Plus, to get acceptable 3dfx  performance cycles are going to up in Penium 1 and 2 ranges - making it incompatible w/ GUS - but that's probably fine from a preservation perspective.

**Comment by Python-Exoproject** [comment]
Thanks for the input @kcgen. During gameplay the GUS seems to be acceptable with current setup, it looks like its only the intro that is affected. I think given a choice between low res and an intro video that plays fine vs high res and a skipping intro ill choose the high res, you concur @exoscoriae? Shame high res is to sluggish at 40k cycles.

As for the 3DFX not being compatible, makes sense. @exoscoriae do you think we should rework the launch bat to somehow not allow GUS for the 3DFX choice, or just add a user note saying it wont work during gameplay if 3DFX chosen? Whatever we do is applicable to both Descent II and Descent II Vertigo.

**Comment by exoscoriae** [comment]
yes. I would rather keep high res, even if it means the intro video has issues.

I will  add a note about GUS and 3DFX being incompatible.
