### ISSUE TITLE
Galactix (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2307]
Not so much a bug as a request. This game was one of my favs growing up and I gave it a go with my kids recently. Its much better when controlled by the mouse but the option to switch between mouse and keyboard is hidden away in the games install program. I have set up the choice between keyboard and mouse the same way we do sound choices and would like to ask that it be implemented for the next release\update?

Heres the changes: 
[Galactix.zip](https://github.com/exoscoriae/eXoDOS/files/5828333/Galactix.zip)
[dosboxconf.zip](https://github.com/exoscoriae/eXoDOS/files/5828335/dosboxconf.zip)

**Comment by exoscoriae** [comment]
applied
