### ISSUE TITLE
\exo\Update\update.bat fails due to incorrect directory check

### ISSUE THREAD

**Issue by Gardhul** [exoscoriae/eXoDOS#2308]
The following check in exo\Update\update.bat

**if exist .\exo\update\update.zip goto updatenow**

after update.zip download is completed, did fail because we already are in **".\exo\Update\"** folder at that point.

Similarly, the following check would goto to fail:

**if not exist .\exo\update\update.zip goto failed**

I've encountered the problem when updating from 5.0 to 5.1 right now.

**Comment by TimberlAndRE-de** [comment]
Yes, there is already an update for the update.bat ;-)

https://discord.com/channels/454359114601201666/454373903146680333/798225133466681354

just download the bat and replace your current file in \eXo\update\

**Comment by Gardhul** [comment]
Great, thank you!
