### ISSUE TITLE
Oxyd (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2314]
discord user Andrew found

- [x] manual

unfortunately it's german only, but since there exists no official english manual and it contains the code tables it's worth to be added I think

added to github folder

**Comment by SmilingSpectre** [comment]
English version of Oxyd manual uploaded into Github folder.

Oxyd (1992).pdf

**Comment by exoscoriae** [comment]
replaced
