### ISSUE TITLE
Dominium (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2318]
if MT32 is chosen at startup, it stops

I think I found the failure:

in the run.bat, there is a "cd" missing in the :MT32 part
```
:SB16
CONFIG -set "mididevice=default"
CONFIG -set "mpu401=none"
cls
cd Dominium
@call DOMINIUM
goto quit

:MT32
CONFIG -set "mididevice=mt32"
CONFIG -set "sbtype=none"
cls
Dominium
@call DOMINIUM
goto quit
```

**Comment by Python-Exoproject** [comment]
You fixed it, but ended up calling dominium bat twice:

:MT32
CONFIG -set "mididevice=mt32"
CONFIG -set "sbtype=none"
cls
cd Dominium
Dominium
@call DOMINIUM
goto quit

**Comment by exoscoriae** [comment]
i liked the game so much I wanted people to play it twice
