### ISSUE TITLE
Steel Panthers (1995)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#2322]
Found patch 1.2 which fixes 59 bugs. I'm also suggesting to copy current readme (readme from 1.2 will replace it) and put them both 1.1 & 1.2 in right-click menu as they have massive amount of info (manual errata and such).
[Steel Panthers 1.2 patch.zip](https://github.com/exoscoriae/eXoDOS/files/5860221/Steel.Panthers.1.2.patch.zip)
[README 1.1.TXT](https://github.com/exoscoriae/eXoDOS/files/5860222/README.1.1.TXT)
[README 1.2.TXT](https://github.com/exoscoriae/eXoDOS/files/5860223/README.1.2.TXT)

**Comment by exoscoriae** [comment]
patched and extras added
