### ISSUE TITLE
Wing Commander III Heart of the Tiger (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2328]
discord user Eulisker found

- [x] additional troubleshooting guide

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by bigjim161** [comment]
I found a poster

Added to the Github folder

**Comment by Eulisker** [comment]
I found

- [ ] Authorized Combat Guide
- [ ] The Ultimate Strategy Guide
- [ ] Origin's Official Guide

The official Guide is already in the collection but missing the last 9 pages.

Added to the github folder.

**Comment by exoscoriae** [comment]
already had a much higher quality version of the official guide.

added the other 2
