### ISSUE TITLE
Wizardry VI - Bane of the Cosmic Forge (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2330]
discord user Eulisker found

- [x] character sheet

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found

- [ ] Hintguide
- [ ] Hintguide Note
- [ ] Hintguide Map

And a better scan of the

- [ ] Magic Words (Copy Protection)

**Comment by exoscoriae** [comment]
added
