### ISSUE TITLE
Reach for the Stars - The Conquest of the Galaxy (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2331]
@SmilingSpectre found

- [ ] manual for Amiga / Apple II / Mac

also he found an readme with a typed down manual for IBM-PC (see #2329)
I suggest to use the (nicer) manual for Amiga/AppleII/Mac (until correct manual is found) and set the readme as an extra.

I added both to the github folder

**Comment by exoscoriae** [comment]
done
