### ISSUE TITLE
Fallout (1997)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#2334]
I found 2 unofficial patches (by TeamX). I think it is worth adding cause they don't add stuff or alter gameplay just fix HUGE amount of bugs. It is 1.2 & 1.3.5 (in-game version number will change after installing 1.2 but not after 1.3.5) They have to be installed one after another.

[Fallout patch 1.2.zip](https://github.com/exoscoriae/eXoDOS/files/5873143/Fallout.patch.1.2.zip)
[Fallout patch 1.3.5.zip](https://github.com/exoscoriae/eXoDOS/files/5873145/Fallout.patch.1.3.5.zip)

**Comment by exoscoriae** [comment]
applied
