### ISSUE TITLE
Descent to Undermountain (1998)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2335]
reported in discord by "hunvagy / Rigoberto Brightman" is that DTU skips throughout the intro and crashes or freezes after character creation. 

To fix the crash we need to do a complete fresh reinstall of the game from the cd image. Not sure specifically what the issue is with the current install but just redoing the sound setup or installing over the current copy doesnt seem to be enough.

To fix the skipping intro vids it looks like Daum is the answer. I tried ECE and X but both still had the same issue on my system. Remember output=direct3d when switching to Daum.

I also found a 1.3 patch that has an extensive bug fix list: 
[dtu_v13.zip](https://github.com/exoscoriae/eXoDOS/files/5873265/dtu_v13.zip)

**Comment by kcgen** [comment]
Very interesting.  And just so I'm understanding right - Daum only fixes the skipping of intro videos, and doesn't fix the freeze after character creation?

**Comment by Python-Exoproject** [comment]
Yeah, the freeze was a game related problem



Sent from my Galaxy



-------- Original message --------

**Comment by exoscoriae** [comment]
reinstalled the game
changed to daum
patched
repacked

**Comment by exoscoriae** [comment]
replaced iso with bin/cue. The iso had dosbox and other crap inserted, meaning it was not original.

bin/cue is an older version, but doesn't matter with the patch applied.
