### ISSUE TITLE
Thunderstrike (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2336]
@SmilingSpectre and discord user "br33ch" have pointed out that our copy of Thunderstrike is not a full version. The copy below is a more complete version that has been found.

[Thunderstrike [a1] (1990)(LIVE Studios, Inc.) [Action].zip](https://github.com/exoscoriae/eXoDOS/files/5873300/Thunderstrike.a1.1990.LIVE.Studios.Inc.Action.zip)

**Comment by exoscoriae** [comment]
replaced
