### ISSUE TITLE
I-Bert V1.0 Arcade Style Action Game 1986

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2337]
Making this record to track the suggested ebay item:

Game is not in exodos. Found on ebay by @bigjim161 & @SmilingSpectre. eXo put a bid on the copy found here https://www.ebay.com/itm/184603740914?ViewItem=&item=184603740914 and im assuming won as there is only 1 bid.

**Comment by exoscoriae** [comment]
got it added & running
