### ISSUE TITLE
Sesame Street Storybook "Me Look For Cookies"

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2342]
This suggestion is for an ebay item not found elsewhere. The item has now been purchased but im adding the issue to keep track of the game itself for future attempts at finding another copy.

https://www.ebay.com/itm/Sesame-Street-Storybook-034-Me-Look-For-Cookies-034-Floppy-Discs-5-1-4-034-1991-Rare-/193515992789?nordt=true&nma=true&si=9UxQ40pyQGZY%252FtA0LGqNzDmlFMg%253D&orig_cvip=true&rt=nc&_trksid=p2047675.l2557

**Comment by Python-Exoproject** [comment]
Located and offered by discord user slamo here: https://discord.com/channels/454359114601201666/620821344891699210/810630890584932352

@SmilingSpectre Have you put this one on the sync? It wasnt marked or commented on by you

**Comment by exoscoriae** [comment]
added
