### ISSUE TITLE
Tracon II (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2343]
Travis has combined the game demo with the tape audio. Should probably be added as an extra @TimberlAndRE-de ?

**Comment by TimberlAndRE-de** [comment]
@Python-Exoproject 
sorry, seems I totally missed this :-(
I just stumbled across it when adding the manual for the game

I searched discord and found this
https://discord.com/channels/454359114601201666/620821344891699210/800144265031712768

But the link's dead... did you download it back then by any chance?

**Comment by TimberlAndRE-de** [comment]
FrozoGrabbins uploaded it to archive: https://archive.org/details/tracon-demonstration-tape

[ ] demonstration tape

added to the github folder

**Comment by exoscoriae** [comment]
added
