### ISSUE TITLE
Strike Commander (CD-ROM Edition) (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2345]
Tservo2049 requested the floppy version be added https://discord.com/channels/454359114601201666/620821344891699210/800744144296607744

https://www.old-games.ru/game/download/1407.html has a copy of the floppy version of the base game, Tactical Ops expansion, and the speech pack (not the same as the "wall to wall voices" of the CD version as mentioned here: https://www.gog.com/forum/strike_commander/any_chance_of_getting_the_floppy_version)

**Comment by exoscoriae** [comment]
added floppy version as it's own entry
