### ISSUE TITLE
Caesar (1992) & Cohort 2 (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2355]
These two games can be combined so that when you have a battle in Caesar it loads Cohort 2 to have the battle then goes back to Caesar. 

To do so though I needed to use an older less featured release of Caesar 1 so I suggest if we add this its definitely a launch option and not a replacement for the current game.

To use just extract this archive [Combined.zip](https://github.com/exoscoriae/eXoDOS/files/5893263/Combined.zip) to wherever you want it and launch with Caesar.bat, the game handles the rest by giving an option at the start of a battle to launch the battle with Cohort 2. It then exits Caesar and loads Cohort 2 for the battle. Once the battle is over it exits Cohort 2 and goes back to your Caesar game.

I havent tested it as I havent progressed a game far enough to have a battle but from everything ive read and running manually the commands found in caesar.bat it should be all good. Hopefully someone better than I am at this game will run through to at least a battle and test it, but otherwise im 99% confident.

**Comment by exoscoriae** [comment]
added combined folder. tried playing for nearly 20 min. never got a battle. so, I'll just assume it works for now.
