### ISSUE TITLE
Alien Trilogy (1996)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2361]
Metadata contains special characters which are not displaying properly in Launchbox. It doesn't like the superscript in Alien 3 references. Suggestion for change "Notes" field to this for proper formatting:

`Alien Trilogy is a first-person shooter based on the first three Alien movies. You control Lt. Ripley in three sections, each based on one film: The colony complex on LV426 (from Aliens), the prison planet (from Alien-3) and the derelict spaceship (from Alien). Each section consists of about 10 missions. In every mission, certain goals must be accomplished to continue. These include killing a certain number of enemies, finding items or activating switches.

Enemies include everything the alien life cycle provides: facehuggers, chestbursters, warrior aliens, dog aliens (from Alien-3) and alien queens, one of which waits in the final mission of every section. In addition to the Aliens, you also have to fight employees of the Company, who have either been infected by the aliens and are beyond saving or who actively want to obstruct your mission.`

**Comment by exoscoriae** [comment]
replaced
