### ISSUE TITLE
Animated Multiplication and Division (1993)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2362]
Metadata contains special characters which are not displaying properly in Launchbox. It doesn't like the division symbol being used in the example. Suggestion for change "Notes" paragraph to this for proper formatting:

`Animated Multiplication and Division is a shareware educational title that aims to teach mental arithmetic to American school children in first, second and third grades

The pupil chooses between either multiplication questions or division questions and selects the presentation style that suits them best. They then choose to answer questions either based on a specific number in the range 1-10 or a mixture of these numbers.
Once the configuration questions have been answered the game asks a series of questions in the form 8 x ? = 16, or 16 / ? = 2, leaving the player to enter the appropriate number. When all questions have been answered the player is rewarded with a mini game.`

**Comment by exoscoriae** [comment]
replaced
