### ISSUE TITLE
The Ball Game (1991)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2363]
Metadata contains special characters which are not displaying properly in Launchbox. It doesn't like the dash character. Suggestion for change "Notes" field to this for proper formatting:

`This puzzle game features four players, any number of which can be human or computer, and is viewed from an isometric perspective. The basic gameplay is very similar to Virgin's Spot license. Your aim is to take control of the largest area of the board, which is done by moving your pieces so as for them to be next to pieces of another colour, which will then become your colour. There are three types of moves - short moves which also see you retain the square you were in, jumps in which you lose the previous square, and moves using the teleporting device to move a larger distance. There are over 100 levels, which needn't be played in sequence. The board layouts feature gaps in, which must be incorporated into your strategy, to ensure that you don't leave a space next to a large number of your pieces, which would allow an opponent to swallow them up.`

**Comment by exoscoriae** [comment]
replaced
