### ISSUE TITLE
Bedlam (1988)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2365]
Metadata contains special characters which are not displaying properly in Launchbox. It doesn't like the apostrophe's. Suggestion to change "Notes" field to this for proper formatting:

`Bedlam is a vertically scrolling space shoot'em-up. Space fighter shoots patterns of swirling aliens and stationary cannons, collects extras and fights boss ships - Bedlam is ordinary shoot'em-up material, stretched out over 16 short levels and spiced up with your standard two-player option.While ZX Spectrum and C64 see a genuine space shooter with full-screen backgrounds and level variations, CPC and DOS get bare-bone versions stripped down to Galaga level.`

**Comment by exoscoriae** [comment]
done
