### ISSUE TITLE
Better Dead Than Alien! (1988)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2369]
Metadata contains special characters which are not displaying properly in Launchbox. It doesn't like the quotations. Suggestion to change "Notes" field to this for proper formatting:

`Brad Zoom takes on the Brain Eaters from the Purple Planet, in this homage to vintage action games, primarily Galaxians. There are 75 levels, accessed via passcodes. You control a spaceship at the bottom of the screen facing upwards, firing at arrangements of aliens. You can move up and down as well as left and right as you shoot them. At set intervals an alien will emerge from the main pack and sweep down towards you. Other levels feature Asteroids which split when shot, or a single "boss" alien. Aliens with green eyeballs release power-ups, such as improved weapons, shields and bombs. You have a single life with which to survive the carnage. You get points for surviving as well as scoring, so slow but cautious play is more rewarding.`

**Comment by exoscoriae** [comment]
done
