### ISSUE TITLE
Big Rig (1987)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2370]
Metadata contains special characters which are not displaying properly in Launchbox. It doesn't like the apostrophe's and some quotes and I fixed some spelling. Suggestion to change "Notes" field to this for proper formatting.... I've included the full thing for easy replacement:

`Big Rig is a simulation that lets you experience the life of a long-distance trucker. Your task is to safely drive a 18-wheel tractor-trailer combination from coast to coast in time, trying to make a profitable trip.

The gameplay and user interface are pretty basic. The game is played in text mode only, with your choice made by typing the right letter at the prompt. At the beginning of your trip, you can choose between three types of cargo (with or without time limit, perishable or not) and three routes -- each with different characteristics, like length or chances for bad weather etc. After these preliminaries, you begin your trip.

Gameplay is turnwise. At each turn, you choose your travelling speed (go too fast, and you may be stopped by the police -- too slow and you may not arrive in time). You'll have to keep an eye on your fitness and your gasometer - driving tired can result in deadly accidents, and running out of gas will cost you time and money. Gas and sleep can be replenished at truck stops.

You'll also be slowed down by roadworks, flat tires, accidents, traffic jams, bad weather -- all those little things that make trucking fun! To get to New York in time, you'll need strategical planning, and a small amount of luck, too. And you'll get to learn a bit about the daily chores of your average trucker.`

**Comment by exoscoriae** [comment]
done
