### ISSUE TITLE
Bionic Commando (1988)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2372]
Metadata contains special characters which are not displaying properly in Launchbox. It doesn't like the dash. Suggestion to change "Notes" field to this for proper formatting:

`In Bionic Commando, the player takes control of a soldier with a bionic arm that extends and contracts.  The bionic arm allows the soldier to grab onto fixed objects and swing around and climb up levels - no jumping allowed! The arm also grabs opponents and pulls them towards the protagonist. The player's mission is to infiltrate the enemy fortress, find a missing comrade, "Super Joe", and take out the evil leader, "Generalissimo Kilt", of the invading force that has been attacking for the last two years.`

**Comment by exoscoriae** [comment]
done
