### ISSUE TITLE
Blasteroids (1989)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2373]
Metadata contains special characters which are not displaying properly in Launchbox. It doesn't like the apostrophe's. Suggestion to change "Notes" field to this for proper formatting:

`As the name suggests, this arcade conversion updates the basic Asteroids gameplay. That means to say that the main gameplay consists of flying through single-screen wrap-around levels shooting at rocks, which split into smaller rocks when hit, eventually becoming small enough to disappear. In this case the Asteroids are protecting Mukor, an evil being who is poisoning planets under the Colonising Corp's control. Each level is split into either 9 or 16 sub-levels, which are chosen through a square in which any remaining level which is adjacent to the last level completed can be selected. There are 3 different ships (Speeder, Fighter and Warrior), which can be switched between at any time. Power-ups (including improved weapons, shield recharges and a faster thrust) can be collected by flying into them.`

**Comment by exoscoriae** [comment]
done
