### ISSUE TITLE
Bloxinies (2013)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2374]
Metadata contains special characters which are not displaying properly in Launchbox. It doesn't like the apostrophe's. Suggestion to change "Notes" field to this for proper formatting:

--snip--
Bloxinies is a little character with ever smiling face. In this game he went out for a walk and entered an odd looking gate, which led him into a puzzle world. He can only escape by collecting all the diamonds which open the door.

The goal is to pick up all the diamonds. Once you've collected all the diamonds the door will open. Enter the door to advance to the next level. You can use the arrow keys to move Bloxinies around.
--snip--

**Comment by exoscoriae** [comment]
done
