### ISSUE TITLE
Booly (1991)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2375]
Metadata contains special characters which are not displaying properly in Launchbox. It doesn't like the apostrophe's. Suggestion to change "Notes" field to this for proper formatting:

`Booly is a puzzle game with a similar concept to Gem'X in some ways. You are presented with a top-down view of an array of inter-connected blocks, which are shown in a variety of colours. The aim is to turn them all to grey, but clicking on them (using the pointer you are in control of) will often cause a pattern of other squares to change to the next colour in the sequence as well. You are doing all this with a time limit for each of the 300 levels. A level designer allows you to create your own sequence of up to 1000 levels.`

**Comment by exoscoriae** [comment]
done
