### ISSUE TITLE
Brokeout (1989)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2376]
Description contains some HTML specific codes in the notes. Suggestion to change "Notes" field to this for proper formatting:

`Brokeout is a simplistic and small (>5 KB) break-out game. Knock out the blocks with the ball and paddle. You have only one ball, there are no bonus items, only one level and no scoring. An accompanying program allows you to adjust the game speed.`

**Comment by exoscoriae** [comment]
done
