### ISSUE TITLE
Bug Bomber (1992)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2378]
Metadata contains special characters which are not displaying properly in Launchbox. Suggestion to change "Notes" field to this for proper formatting:

`A computer's mazelike circuitry is infected with bugs, and you have been sent in to destroy them. You are armed with bombs, mines, blockades, and various types of hatchlings, which when released will track the bugs and hopefully stop them.The basic gameplay is inspired by Dynablaster, but it differs because there is more than one way to kill the foes off. Depending on which way you push the joystick as you press fire, you will either release a quick-exploding bomb, a proximity mine, or a hatchling. Collecting "EN" symbols will restore your energy, and "IQ" symbols increase the ability of your hatchlings to track and hit your foes. Be careful when placing blocks; it is possible to shut yourself in.The single-player game gives you three lives, plus another when you complete each of the 50 levels. The multi-player game can be played in 2 different ways - co-operative (work together to clear the computer of bugs) or competitive (Dynablaster-style free-for-all destruction).`

**Comment by exoscoriae** [comment]
done
