### ISSUE TITLE
Wargame Construction Set III: Age of Rifles 1846-1905 (1996)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#2380]
I found official Campaign Disk Expansion which also changes game v. from 1.01 (current in eXoDOS v5.1) to 1.3
There are also patches:
1.4
1.4b
1.402
Patches are zipped in game folder in eXoDOS but not applied. Fixes a lot of things, including game crashes.
Add-on is here:
https://www.old-games.ru/game/download/get.php?fileid=11491&modal=1

**Comment by exoscoriae** [comment]
patched to 1.4 (did not apply 1.402 unofficial patch. Readme explicitly states it was not tested much)
added campaign disk
