### ISSUE TITLE
Robot Odyssey (1985)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2383]
Discord user BayBuilder has reported that our version of Robot Odyssey has copy protection. He has linked to two methods for fixing the issue.

https://discord.com/channels/454359114601201666/467028238687010826/805890193013211186 Here Fifth Horseman has posted at the bottom a zip with cracked exes for the main game exe and the lab exe.

https://github.com/houtianze/robot_odyssey_patcher/blob/master/robot_odyssey_patcher.py Here is a patcher that does the above and also patches the tutorials.

**Comment by exoscoriae** [comment]
game.exe and lab.exe replaced.
no luck with the python script. seems that python 3.7 was too new and it required 2.9 and a module called "NASM"
