### ISSUE TITLE
NHL '94 (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2387]
@SmilingSpectre has reported the below in discord:

NHL '94 (1993) never was named as that. There is NHL '94, but it's for consoles. Our game is simply "NHL Hockey".

**Comment by exoscoriae** [comment]
changed file names and other dependencies

**Comment by Python-Exoproject** [comment]
The original NHL '94 zip and launch bat are still in the collection

**Comment by Python-Exoproject** [comment]
Im going to assume this is a sync issue as well, and if its not exotool will pick it up at some point
