### ISSUE TITLE
Hellfire - Journey to Hell (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2391]
from discord user gschmidl:

Edward M. Kruse's "Hellfire - Journey to Hell". From the README: "HELLFIRE,  the adventure game that takes you on a journey to HELL with all the devil's treasures at your finger tips.  Of course their [sic] is the fact that you can get killed VERY easy, so best take care."

added to the github folder

**Comment by exoscoriae** [comment]
added
