### ISSUE TITLE
Hicktown (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2392]
from discord user gschmidl:

Text adventure with crude CGA graphics. Text adventure, FlaccidWare 1990.
"You are standing smack dab in the middle of downtown Rhondale Circle. Rhondale Circle is a town in the middle of nowhere. Population: 4,936. The town's High School football logo, the hornet, is below you. It is about 6:25 on a friday night. All the stores are open, and all the hicks are a-hooperin' and a-hollerin'. It's going to be one of those nights. This is where your adventure in HICK TOWN begins!"

added to github folder

**Comment by exoscoriae** [comment]
added
