### ISSUE TITLE
Caddiehack (1994)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2394]
Metadata contains special characters which are not displaying properly in Launchbox. Suggestion to change "Notes" field to this for supported formatting:

`Caddiehack is shareware golf game for up to ten players, each player gets a different coloured ball. This game is the sequel to Caddiehack CGA Tour. It has been developed to use improved EGA/VGA graphics. Both games come with ARCH - a course architect program that allows players to design their own courses. Courses developed for use with the earlier game can be used with Caddiehack but not vice versa.After the game setup screens, how many players, skill level, and sound effects to be turned on or off etc. the player is presented with an overhead view of the first hole. At the press of a key this switches to the view from the pin. There is a caddy system which automatically selects the appropriate club based on distance to the pin, this can be changed by the player to allow for hazards and weather conditions. The game is entirely keyboard controlled. Aiming the shot is controlled by the left/right arrow keys and the power of the shot is controlled by using the space bar to set the power meter. There is a save game feature.`

**Comment by exoscoriae** [comment]
done
