### ISSUE TITLE
Silverball (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2399]
@XavierVelo and @TimberlAndRE-de have discovered an issue and solution with Silverball. The current cycles are causing random issues with keyboard lockups, if you set the cycles to 20000 it looks like it fixes the issue.

Has anyone seen similar effects in Epic Pinball which uses the same engine? I did limited testing and didnt.

I also note that the game is GUS capable and as Epic Pinball was one of the "Highlight" GUS games, I assume as this game is using the same engine it might be worth adding it here as well?

Lastly @SmilingSpectre has found an exe [PIN3.zip](https://github.com/exoscoriae/eXoDOS/files/5929138/PIN3.zip) for the Nova table in second release. It enables the table (which was already in the list of playabel tables, it just didnt work) and seems to run fine. Using this it looks like the "Original release" option may not be needed anymore?

**Comment by exoscoriae** [comment]
cycles set to 20k
added GUS options to both versions

**Comment by Python-Exoproject** [comment]
You didnt action the final point regarding the Nova table? Extract this [PIN3.zip](https://github.com/exoscoriae/eXoDOS/files/6604345/PIN3.zip) into \eXoDOS\Silverba and it fixes the Nova table being broken in version 2. 

Once thats done we can remove the "original" option from the launcher and just launch version 2 as the only reason we included version 1 was that the Nova table worked in it but not in version 2.

**Comment by exoscoriae** [comment]
fixed

**Comment by exoscoriae** [comment]
but we already have silverball 2 as it's own game in the set. I don't even understand why it is a launch option here. Why fix this one to beconme silverball 2 + when we have silverball 2 + in the set?

**Comment by exoscoriae** [comment]
struck the sb2+ options from Silverball (1993)
