### ISSUE TITLE
Cool Spot (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#240]
on the cover it says english  deutsch  francais  espanol  italiano  but only english is included. so maybe the pages are missing.

**Comment by SmilingSpectre** [comment]
Uploaded.

**Comment by TimberlAndRE-de** [comment]
added to the github folder

**Comment by Eulisker** [comment]
Manual in

- English
- German
- French
- Spanish
- Italian

The scan is still very bad and 13/14 are in the wrong order.
