### ISSUE TITLE
Ultima IV - Quest of the Avatar (1985)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2401]
While looking at Ultima VII I had another look at the other Ultimas to see if there where any updates to their upgrade patches. In Ultima IV I noticed three things.

1. A note in the music upgrade readme that says "NOTE: ULTIMA.COM is being replaced because the size of LARGE.XMI is hard-coded within the binary.". This implies that using the Ultima.com from the U4 upgrade with the music upgrade will cause issues which is what we are currently doing. There is an alternate com file included in the music upgrade patch which we didnt have in our game zip. Ive attached an updated U4 zip below with the needed ultima.com files in the necessary folders. 

There is another music choice that uses the music from Apple and C64 versions of Ultima IV, im not sure if the same issue applies and I couldnt find a copy of this music patch to see if it came with its own ultima.com. For now ive given it the original upgrade project com that we already had it using.

2. The description for the music upgrade says "A set of alternative musical arrangements for Ultima IV and xu4, and includes an endgame bugfix for the latest U4 Upgrade.". Further research has confirmed that there is "A bug in the endgame code of the U4 Upgrade introduced by the patch causing the endgame to hang.". This issue is fixed by the music upgrade but implies if the user chooses to play Ultima IV Upgrade and select either the Apple\C64 music or Original music they will not be able to complete the game. I assume the fix is in the ultima.com file included with the music patch, but as per the first point above I'm not confident on using this com for the original or apple\C64 options. Your thoughts?

3. I discovered a patch for one of the dungeons to make it work properly (https://ultima4.ultimacodex.com/ultima-4-hythloth-fix/). I have added that to the U4 upgrade version but left it out of the original release. If you feel it should be applied to the original release as well just copy ultima4\upgrade\hythloth.dng to ultima4\hythloth.dng

[Ultima IV - Quest of the Avatar (1985).zip](https://github.com/exoscoriae/eXoDOS/files/5929534/Ultima.IV.-.Quest.of.the.Avatar.1985.zip)

**Comment by exoscoriae** [comment]
i swear to god. a month doesn't go by that I don't see a fucking ultima game listed here. these are problem children and between them and richard garriot being a shit nugget, I am about to make a NO ULTIMA rule for eXoDOS.

**Comment by exoscoriae** [comment]
ok. reading through this, here are my thoughts:

1. So we don't know that it causes issues, but the wording of the note makes you suspect it might? Just want to be clear on that. Doesn't seem to hurt anything though, so I'll add your files.

2. Our current note states that the midi music in the upgrade version is from the Apple and Commodore versions. Is there a *different* music upgrade patch? Honestly, none of this makes sense to me. As far as I can tell, there is NO midi music for Ultima 4 that *DIDN'T* originate from Apple or C64. So what is this music upgrade that is being discussed that is somehow sourced from a different place? Isn't the only music in the PC version pc speaker?

3. good find. no thoughts though on if it needs to go in the original.

Honestly, this series kind of got janked from me when dama hamara got involved. She started adding all these bloody patches and "upgrades" and I honestly have no idea what anything does anymore. You are welcome to make the call on these damn ultima games... I don't have patience for the constant tinkering. All my patience for these games is worn through. Pack them up however you please and I'll add them as is.

**Comment by exoscoriae** [comment]
to be clear, I added the files you listed above

**Comment by exoscoriae** [comment]
also - I appreciate your time on this. my frustration is solely with the ultima titles, not you!
