### ISSUE TITLE
Ultima Underworld 2 - Labyrinth of Worlds (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2406]
It has been suggested we apply this patch: https://github.com/JohnGlassmyer/UltimaHacks, there is also a website that applies the patch for you at https://johnglassmyer.github.io/UltimaHacks/

I am not familiar enough to advise on if this should be added as an alternate option or overwrite the base game. From people that have responded to my queries they all say they use it.

**Comment by exoscoriae** [comment]
patched

**Comment by Python-Exoproject** [comment]
Voices cant be heard over music during intro without "sbmixer=false". 

As there is no obvious way to tell, we should probably add a user note to the launch bat informing that UltimaHacks has been installed for the quality of life improvements. There is no in game shortcut to list these like there is for U7, so maybe we could either point out the most important new featuers\commands from here https://github.com/JohnGlassmyer/UltimaHacks like mouselook. Or make a text file with the additions and add it as an extra?

**Comment by exoscoriae** [comment]
noted

**Comment by Python-Exoproject** [comment]
Hi Exo, you made the note regarding ultima hacks but you missed this bit of my note:

"There is no in game shortcut to list these like there is for U7, so maybe we could either point out the most important new features\commands from here https://github.com/JohnGlassmyer/UltimaHacks like mouselook. Or make a text file with the additions and add it as an extra?"

Youve copied the note you made for U7 which (rightly so for Ultima 7, just not Underworld) informs the user to press Alt-K to see the features and commands without adjusting it for this game.

**Comment by exoscoriae** [comment]
added a full note to the launcher
