### ISSUE TITLE
Albion (1995)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#2407]
Game has reversed stereo on SB. Ripsaw8080 made fix for this. 
First if you want to check it, the easiest way is: start new game, go out of your room, after quick chit-chat with a girlfriend go left and up, there's a console of some sort with beeping noises which clearly shows that stereo is f^&($#.

There's readme cut from Vogons forum with instructions.
[Readme.txt](https://github.com/exoscoriae/eXoDOS/files/5932717/Readme.txt)
[swapfix.zip](https://github.com/exoscoriae/eXoDOS/files/5932721/swapfix.zip)

**Comment by exoscoriae** [comment]
fix applied
