### ISSUE TITLE
Fade to Black (1995)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#2409]
Game has reversed stereo on SB. Ripsaw8080 made fix for this.
First if you want to check it, the easiest way is: go to game setup. In sound FX there is test for each channel.

There's readme cut from Vogons forum with instructions.
[Readme.txt](https://github.com/exoscoriae/eXoDOS/files/5932832/Readme.txt)
[swapfix.zip](https://github.com/exoscoriae/eXoDOS/files/5932833/swapfix.zip)

**Comment by exoscoriae** [comment]
patched
