### ISSUE TITLE
Super Fighter (1993)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2410]
I found an English version named "Fatal Encounter" (the current version isn't in English)

Maybe we can change the name of the game to Fatal Encounter.

Added to the Github folder/Bugs

**Comment by exoscoriae** [comment]
renamed archive to Fatal Encounter (1993).zip

Removed MT32 and SC55 options for both game. I noticed there was actually no music in either Fatal Encounter or Super Fighter when those options were set.
