### ISSUE TITLE
Terminator, The (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2414]
Eulisker found

- [x] Reference Card (typed down - but helpful to play the games because of the contained keymappings)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
scanned

- [ ] Map
- [ ] Reference Card
- [ ] Security Chart
- [ ] Technical Note

added to the github folder


The security chart is already in the collection in high quality. This is just the one from my box.

**Comment by exoscoriae** [comment]
added! thanks
