### ISSUE TITLE
Girlfriend Tracy (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2415]
This game is on the dos missing list.
Mobygames: https://www.mobygames.com/game/girlfriend-tracy
Found here: https://www.myabandonware.com/game/girlfriend-tracy-dyp#download
Genre: Adult, Interactive Movie
Publisher: AIVR Corp
Developer: AIVR Corp
Released: 1995

Added to the Github folder

**Comment by exoscoriae** [comment]
added
