### ISSUE TITLE
Girlfriend Terri (1994)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2416]
This game is not on the dos master list and on Mobygames 
Found here: https://www.myabandonware.com/game/girlfriend-terri-9yr
Genre: Adult, Interactive Movie
Publisher: AIVR Corp
Developer: AIVR Corp
Released: 1994

Added to the Github folder
(maybe it can be added to Girlfriend Tracy 1995)

**Comment by exoscoriae** [comment]
added
