### ISSUE TITLE
Ultima VI (1990)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#2418]
I found a map without watermark, same quality as in v5 and photo of included "moon stone". Also this is worth considering to add:
https://wiki.ultimacodex.com/wiki/Ultima_VI_audio_tape
[Map.pdf](https://github.com/exoscoriae/eXoDOS/files/5938973/Map.pdf)
![Moonstone](https://user-images.githubusercontent.com/66518085/107146571-79af6900-6949-11eb-9963-c918f457057d.jpg)

**Comment by exoscoriae** [comment]
removed watermark
