### ISSUE TITLE
Ultima VIII (1994)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#2421]
I found scanned map & "pentagram coin" extra
[Map.pdf](https://github.com/exoscoriae/eXoDOS/files/5939047/Map.pdf)
![Pentagram Coin](https://user-images.githubusercontent.com/66518085/107147605-3d7f0700-694f-11eb-90ef-2d2b17b832c0.jpg)

**Comment by exoscoriae** [comment]
added
