### ISSUE TITLE
SimCity (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2425]
@SmilingSpectre has discovered that our copy and all copies on the net for this game have some of the graphics files in the wrong folders. It only affects if the user wants to select CGA or Tandy as the other files are in the right locations, but broken is broken. I understand that you have the originals for this game? If that is the case then maybe the original installer is responsible for this situation? Either way Spectre has put all the files in the correct location using our copy as a base so now all user selected graphics choices work. He has uploaded this to his sync folder. If it truly was installed this way by the games installer, then this is fixed for the first time, yay!

**Comment by SmilingSpectre** [comment]
Installer (I mean, SETTINGS.EXE, I don't know how original one worked) simply put on HDD required mode, and nothing else. So if you want all modes, you need to choose every one in order. And no one did that, it seems (other version simply missing all this files altogether). Our version is matching no other I could found online, so it's only full "E1.X" version ever, it seems.

**Comment by exoscoriae** [comment]
replaced with reconstructed version

**Comment by TimberlAndRE-de** [comment]
Small issue: the "run.bat" is called "pick.bat" 
Should be renamed for consistency

**Comment by exoscoriae** [comment]
ok
