### ISSUE TITLE
Launchbox Plugin doesn't keep installed game in playlist

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2426]
- a game was installed before the plugin or outside of LB
- then you start LB and you start the game by clicking "Play"
- it shows up on installed playlist and has the flag set
- but after restarting LB it's gone again and is "Installed" = false

It seems, it doesn't update the xml when closing

**BUT**: if you use "Configure" instead of "Play", it works as expected - restart LB and it's still installed

I think, as soon as eXo has time for this, we need to contact Jason and CBeatt13 ... this seems more to be a problem of LB then of the plugin

**Comment by TimberlAndRE-de** [comment]
more behavior found out by @Python-Exoproject :
if you "Play" for a bit longer in the game (say through to getting in the cockpit in Comanche, then quit comanche via pressing esc, quit to dos) it will perform as expected and keep the flag
also, if you set the "Installed" flag manually by editing it keeps the flag after restarting LB

**Comment by TimberlAndRE-de** [comment]
after some more testing by Python it seems the time, the game (or batch) window opens is the key.
If a small game like .386 Spys is installed it has the same effect (Install flag dissappears after restarting LB)
LB needs to have the dosbox window open a certain amount of time before the flag will stick past a reboot

**Comment by TimberlAndRE-de** [comment]
so that it doesn't get lost in the discord:
here's the current version (2.2) of the plugin included with the eXoWin3x release:
[eXoplugin_v2.2.zip](https://github.com/exoscoriae/eXoDOS/files/5950150/eXoplugin_v2.2.zip)

Tested with 
- [ ] eXoDOS v5
- [ ] eXoWin3x
- [ ] LB 11.6 (stable)
- [ ] 11.9 (stable)

**Comment by exoscoriae** [comment]
plugin added to eXoDOS
