### ISSUE TITLE
Dinotopia (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2430]
I found:

- a manual
- a Ref card (extra)
- card game (extra)

added to the GitHub folder

**Comment by TimberlAndRE-de** [comment]
ToxicFrog found

- [ ] A Traveler's Guide

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] official strategy guide

added to the github folder

**Comment by exoscoriae** [comment]
added
