### ISSUE TITLE
Mixed-Up Mother Goose (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2431]
Well probably get around to fixing this when we go over all ScummVM games in exodos once exoscummvm is done but ive noticed that the game that runs when you select scummvm option for Mixed-Up Mother Goose (1991) is actually Mixed-Up Mother Goose Deluxe which is a win3x title

**Comment by exoscoriae** [comment]
fixed the files. switched the launcher to use the proper game tag. now scummvm crashes though when I start with this message:
![image](https://user-images.githubusercontent.com/8557582/111201713-0eccff80-8591-11eb-8e77-d61d73aab59a.png)

**Comment by exoscoriae** [comment]
I just noticed you skipped setting up this particular CD version in ScummVM, did you have an issue as well?

**Comment by exoscoriae** [comment]
opened a thread at their forums on it:
https://forums.scummvm.org/viewtopic.php?f=2&t=16236

**Comment by exoscoriae** [comment]
github ticket on scummvm:
https://bugs.scummvm.org/ticket/12431#ticket

**Comment by exoscoriae** [comment]
confirmed fix in latest svn. Added it as an svn option under the stable release we are using, so as to not mess up any games that the SVN may cause issues with.
