### ISSUE TITLE
Star Trek - The Next Generation - Trivia (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2435]
discord user haxman noted:

_I have a question regarding the game Star Trek: The Next Generation - Trivia that is included in exodos. The description mentions 3 volumes of the game  (different questions in each volume). When you launch the game only Volume 1 is available. Is this a bug that the entry in launchbox only opens Volume 1 (and not the others) or was only Volume 1 found and added to Exodos?_

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found the full version

added to the github folder for game submissions

**Comment by exoscoriae** [comment]
fixed.
