### ISSUE TITLE
Sid Meier's Civilization (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2438]
Eulisker found

- [x] technical supplement
- [x] advances chart (official one - the current one marked as "original" seems more like a selfmade too?)

added to the github folder

**Comment by exoscoriae** [comment]
replaced\added

**Comment by Eulisker** [comment]
I found

- [ ] The Official Guide to Sid Meier's Civilization

Added to the github folder.
