### ISSUE TITLE
Picture Perfect Golf (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2439]
Currently the game exits out without starting as its pointing to run.bat which looks like its a leftover from possible attempt during network project as there are extip text files as well. Point the game to \pp_golf\front9.bat to fix.

I have also discovered that although the game is supposed to have sound, it is not currently working. Due to the .voc files I tried ct-voice.dll with sound variable and a few other things but no luck so far.

It also looks like this game is a cut down 9 hole version of the full "Harbour Town" course. I will create a separate issue to deal with this at #2440.

**Comment by exoscoriae** [comment]
fixed launch
fixed sound via cycles
purchased full version of the game (4 courses on 4 cd's), however they are all windows versions.

**Comment by Python-Exoproject** [comment]
Timber purchased and uploaded the DOS versions, the ones you purchased were intended for win3.1

**Comment by TimberlAndRE-de** [comment]
Yea I guess I wrote to the wrong issue: #2440 😉

**Comment by exoscoriae** [comment]
replaced old version with the 2 disc images provided by @TimberlAndRE-de 

Harbor Town Golf Links (full 18) and Coeur d'Alene are now both playable. Not sure if the other two courses we have for win3x were ever created for DOS.
