### ISSUE TITLE
Picture Perfect Golf (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2440]
Our version is actually called "Front 9 of Harbour Town" and has a splash page saying "ring for 18 hole version" note. There is also a screenshot as below:

![unknown](https://user-images.githubusercontent.com/67406191/107854145-1dc77180-6e6e-11eb-9391-c05e444acd7d.png)

This obviously implies that our version is not the full game. @SmilingSpectre Has found these three copies on ebay.

https://www.ebay.com/itm/Picture-Perfect-Golf-1994-PC-Computer-CD-ROM-The-Front-Nine-At-Harbour-Town/184385552948?epid=170202671&hash=item2aee3c4234:g:h4UAAOSwWJ5fJmxW

https://www.ebay.com/itm/PC-Based-Game-Picture-Perfect-Golf-Harbour-Town-City-Limits/114671894767

https://www.ebay.com/itm/1994-Picture-PERFECT-GOLF-CD-ROM-action-so-real-you-can-almost-smell-the-grass/392932701476?hash=item5b7c9d3524:g:ndAAAOSwj5xfN0j3

While the screenshot above show two other courses we have not yet seen proof that they were released for DOS, but they were released for Win3.1 and I will make an issue there.

**Comment by Python-Exoproject** [comment]
@SmilingSpectre has now located a copy of Harbour Town for DOS that includes Coeur D'Alene here: https://www.ebay.de/itm/Picture-Perfect-Golf-DOS-PC-Spiel-auf-CD-ROM-2-Disk-Original-1995-PC-Spiel-/313036844401?_trksid=p2349624.m46890.l49292

**Comment by SmilingSpectre** [comment]
Last one is **Eulisker** find. I only re-translated it.

**Comment by exoscoriae** [comment]
purchased

**Comment by TimberlAndRE-de** [comment]
PPG arrived here from ebay
I ripped the discs and uploaded them to my personal folder

**Comment by exoscoriae** [comment]
added your discs
