### ISSUE TITLE
DOOM II (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2443]
found an

- [x] manual addendum (from floppy version)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found

- [ ] survival guide

added to the github folder

**Comment by TimberlAndRE-de** [comment]
mgoddard found

- [ ] comic

_The Doom comic is a sixteen-page comic book, written in 1996 by [Steve Behling](http://en.wikipedia.org/wiki/Steven_Dehling) and [Michael Stewart](http://en.wikipedia.org/wiki/Michael_Stewart), with art and color design by [Tom Grindberg](http://en.wikipedia.org/wiki/Ton_Grindberg), all credited with purposely gory nicknames for the occasion. It was produced by Dana Moreshead, for [Marvel Comics](http://en.wikipedia.org/wiki/Marvel_Comics), as a giveaway for a video game convention_ (DoomWiki)

It seems it's missing the back pack because it's only 17 pages, not 18

added to the github folder

**Comment by exoscoriae** [comment]
added
