### ISSUE TITLE
James Bond 007 - The Stealth Affair (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2445]
During my ScummVM work I've discovered that there are 4 DOS versions of this game. An EGA and a VGA release of the European Operation Stealth and the same for the US James Bond - The Stealth Affair. Main difference between Operation Stealth and James Bond versions is that you are a CIA agent in Operation Stealth and James Bond in the US version.

The version in eXoDOS is currently the EGA US version. If you wanted to switch to or add the VGA version there is a copy in "Operation Stealth (Multi-Platform).zip" of the ScummVM work ive been syncing. Both Operation Stealth versions are also there if you wanted to add that as well.

**Comment by exoscoriae** [comment]
your VGA version has scene rip BS in front of it. Would be nice to find a clean version.

**Comment by exoscoriae** [comment]
there seem to be other issues at play here.  Both my original cop-y and the VGA copy you have look identical. I'm not seeing EGA in either

**Comment by exoscoriae** [comment]
![image](https://user-images.githubusercontent.com/8557582/110843622-2133fa00-826e-11eb-9392-cd4df8ad5cbf.png)

**Comment by exoscoriae** [comment]
TDC version allows VGA, EGA, CGA, TANDY.

Replacing the two US copies with this one

**Comment by exoscoriae** [comment]
Found TDC OpStealth version as well.

Used MCGA for VGA, as this eliminate flickering.
throttled EGA version to 1200 cycles to eliminate flickering

Both US and Uk versions now available. In EGA and VGA w/ SB or MT32 options.

**Comment by Python-Exoproject** [comment]
Flicker is still present on my end for EGA choice, tried reducing cycles down to 800 and it improved but still was present (especially during the intro when the guy has the mask come down). 

However using Daum eliminates the flicker completely at 1200 cycles. If we switch to Daum remember to use direct3d and that to use MT32 we need to move the roms temporarily, see Frontier - First Encounters (1995) launch bat for example if needed.

@kcgen You maybe interested in this example of Daum handling EGA flicker better than other forks?

**Comment by exoscoriae** [comment]
switched to daum.

modified files as needed.

verified flicker had stopped and mt32 still worked.

**Comment by exoscoriae** [comment]
actually, there is still slight flickering,. but it is much better.
