### ISSUE TITLE
Air Warrior (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2447]
From @SmilingSpectre:

Smiling Spectre Today at 20:50
@eXo @Python Regardless of Mobi ideas, there are at least two distinct Air Warrior versions exists. One is simply Air Warrior (or Kesmai Air Warrior), that is in collection and (c) 1990. And second is SVGA Air Warrior or Air Warrior Plus - it have SVGA resolution (duh) and different file structure - that was re-issued in 1992. I uploaded ISO of latter one.

**Comment by exoscoriae** [comment]
re filing this under a game submission

**Comment by TimberlAndRE-de** [comment]
discord user agathosdaimon also suggested to add SVGA version 1.5
and says there's also a version 1.14 for the non SVGA version

discussion is here: [discord](https://discord.com/channels/454359114601201666/620821344891699210/858953336584536084)

agathosdaimon uploaded the SVGA version too, not sure if it's different from Smiling Spectre's version so I added it to the github folder too

**Comment by exoscoriae** [comment]
updated SVGA version to 1.50e
updated EGA to 1.4
