### ISSUE TITLE
3D Dinosaur Adventure (1993) and Dinosaur Adventure (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2449]
From @SmilingSpectre:

Both "3-D Dinosaur Adventure" and "Dinosaur Adventure" are the same game - Dinosaur Adventure.

The real 3D Dinosaur Adventure can be get from CD in archive "Kid's Zoo - A Baby Animal Adventure (1993)". (Actually, it's 400MB of Dinosaurs, and only 100+ - Baby Animal)

**Comment by exoscoriae** [comment]
great work @SmilingSpectre 

replaced the proper game
