### ISSUE TITLE
Cyberia 2 - Resurrection (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#245]
pages 30 and 31 are missing

**Comment by Eulisker** [comment]
Manual in

- English
- French
- German
- Italian
- Spanish

**Comment by TimberlAndRE-de** [comment]
Swizzle found

- [ ] manual (better scan and it's the UK (US?) version, current one ist the European manual)

added to the github folder

**Comment by exoscoriae** [comment]
replaced
