### ISSUE TITLE
Billy the Kid Returns (1994)

### ISSUE THREAD

**Issue by TheKins** [exoscoriae/eXoDOS#2452]
Game is the shareware version, limited to three of the ten scenarios. Full version claims to still be sold through the developer's website in the "Arcade Bundle".

**Comment by exoscoriae** [comment]
Link to the developers site?

**Comment by TheKins** [comment]
https://alivesoft.com/index.php/legacy-game-downloads/

**Comment by SmilingSpectre** [comment]
Wow, it's Alive!

**Comment by Python-Exoproject** [comment]
From Kinsie:

A full version of the game has been found here as a floppy disk image.

[002732_billy_the_kid_returns.zip](https://github.com/exoscoriae/eXoDOS/files/13327806/002732_billy_the_kid_returns.zip)

Use 7zip to crack open the IMG file _and_ the DISK1.BCF file inside to get the game install. Substituting the original eXoDOS v6 install with these files works fine.

This full version actually seems to be an older version than the shareware version in eXoDOS so far - v1.0 (August 1st 1993) compared to the shareware's v1.10 (May 1st 1994). Worth keeping in mind.

**Comment by SmilingSpectre** [comment]
You can simply install from the floppy (or extract files, _then_ install them. Works if install is on A: though). Confirmed: game is full.
