### ISSUE TITLE
Grand Slam Bridge II (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2454]
TServo2049 discovered that this game is running on PC Speaker but has options for SB, Tandy, and MT32. To select these modes you need to do so during the install so you will need a copy of the installer, TDC has this.

**Comment by exoscoriae** [comment]
added sb16 and mt32 launch options

**Comment by Python-Exoproject** [comment]
I dont think this made it onto the eXoDOS MT32 playlist

**Comment by exoscoriae** [comment]
thanks. added
