### ISSUE TITLE
Might and Magic 2 - Gates to Another World (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2457]
@SmilingSpectre found

- [x] several maps / map versions - we weren't sure about which versions to add...

from Smiling Spectre: "As I see, "original" is more balanced, but "Ultimate archives" doubles resolution"

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I scanned the

- [ ] Map

The current ones are not very good.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I found the

- [ ] IBM Reference Card

Added to the github folder.

**Comment by exoscoriae** [comment]
added
