### ISSUE TITLE
Might and Magic 5 - Darkside of Xeen (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2463]
@SmilingSpectre found several maps / map versions, not sure which ones to add

Smiling Spectre says: "Ultimate is bigger and better, but too dark and with black font. Maybe worth to tune, and keep both maps too"

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found a scanned version of the

- [ ] Clue Book

It contains the solution for World of Xeen and should be added there too.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced existing clue book

**Comment by Eulisker** [comment]
I scanned the 

- [ ] map

The current one is not as clear.
Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
