### ISSUE TITLE
Might and Magic 4+5 - World of Xeen (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2464]
maps from MM4 and MM5 are missing as extras here

- [x] maps

should be added from the MM4/MM5 game folders

**Comment by exoscoriae** [comment]
copied and added

**Comment by Eulisker** [comment]
I scanned the 

- [ ] Maps

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
