### ISSUE TITLE
Might and Magic 3 - Isles of Terra (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2465]
@SmilingSpectre found several maps / map versions, not sure which ones to add

Smiling Spectre says: "Ultimate is double size again, so I suggest put it as replacement. Also, Japanese version is interesting, as it features significantly different art. I recommend it as extra"

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found a 

- [ ] Completion Certificate

Once you finished the game you could send your stats to NWC and get a certificate back. 
![image](https://user-images.githubusercontent.com/81642149/180947700-7f9be25f-872f-4acc-adff-97aea3eea8de.png)

This one is from the mocagh.org dude. I am not sure if you feel comfortable putting it in with his name on it. 
Added it to the github folder.

**Comment by SmilingSpectre** [comment]
It's not a real doc. It's generated by game after _your_ completion. Not needed.

**Comment by Eulisker** [comment]
That is what i assume at least. I can not find anything else about it but something had to happen when you send your score to NWC and the document looks legit.

**Comment by TimberlAndRE-de** [comment]
I edited the document and deleted the name and numbers (saved as `Might and Magic 3 - Isles of Terra (1991) Completion Certificate_cleaned.jpg`)

**Comment by exoscoriae** [comment]
added clean version. thanks guys
