### ISSUE TITLE
Capone (1988)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2466]
Metadata contains special characters which are not displaying properly in Launchbox. Suggestion to change "Notes" field to this for the supported formatting:

`This is the first light-gun game for the Commodore Amiga.  The action takes place in the Capone era of 1920s Chicago.  The player is a lone gunman battling Capone's men down the streets and alleys of the city.  The game plays much like Operation Wolf. As the game progresses, the screen scrolls sideways and evil gangsters pop up from behind windows and buildings.  The player must take care not to hit innocent bystanders, including women, children, and pets strolling down the street.  There are also two indoor scenes, including a warehouse filled with TNT and the finale that takes place inside a bank.  Capone was released in the early years of the Amiga, and had a very unique look for its time. Although the major selling point of Capone was it was the first light-gun game available for the Amiga, players could also play entirely with a mouse.  During mouse play, a cross-hair cursor appears on screen.  Firing is accomplished simply by hitting the mouse button, or trigger on the light-gun.`

**Comment by exoscoriae** [comment]
done
