### ISSUE TITLE
The Chase on Tom Sawyer's Island (1988)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2468]
Metadata contains special characters which are not displaying properly in Launchbox. Suggestion to change "Notes" field to this for the supported formatting:

`This Pac-Man inspired maze game is based upon the Tom Sawyer's Island attraction at Disneyland.  Players maneuver Tom Sawyer along the island's paths in his quest to gather berries.  However, Aunt Polly, Injun Joe, and after the third level, a bear, chase after Tom.  He can avoid them by ducking into escape routes such as a water wheel, a teeter-totter, a raft and two caves.  If Tom survives all five levels, the player wins.`

**Comment by exoscoriae** [comment]
done
