### ISSUE TITLE
Betrayal at Krondor (1993)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#2472]
I found:

- [ ] map has removable watermark (replacementdocs)
- [ ] reference card has removable watermark (replacementdocs)
- [ ] strategy guide (added to the github folder)

**Comment by TimberlAndRE-de** [comment]
thx @XavierVelo I added the files to the github folder 👍

**Comment by TimberlAndRE-de** [comment]
there is already an extras-issue for this game (see #2170 )
copied it to the other issue and closed this one 👍
