### ISSUE TITLE
Protostar - War on the Frontier (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2476]
from Eulisker:

- [ ] CD audio tracks (as mp3)

_The audio tracks on the cd version of protostar seem to be just for playing in a CD player. As seen on mobygames_
![grafik](https://user-images.githubusercontent.com/67441153/108379910-a6dfff00-7206-11eb-9b97-bdd57fb866e6.png)

_Maybe you can offer them as mp3 as an extra?_

added the audio files as mp3 to the github folder

**Comment by exoscoriae** [comment]
added
