### ISSUE TITLE
Ultima Underworld - The Stygian Abyss (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2478]
Eulisker found

- [x] map (higher resolution)

added to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I scanned

- [ ] Mysteries of the Abyss (Clue Book)

and found

- [ ] Clue Book Ad
- [ ] Runes

The runes were included in the first release of the game. (This is the european one but it should be the same in the US)

![image](https://user-images.githubusercontent.com/81642149/167402398-072b5bc7-b2ce-46ff-8c38-89db38a7c22f.png)

All added to the github folder.

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I uploaded a new version of the hintbook with a higher contrast. I think it looks much better. If you would like the contrast even higher it is an easy fix.

**Comment by exoscoriae** [comment]
replaced clue book
