### ISSUE TITLE
Light Corridor, The (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2480]
Not an issue for Windows users, but Linux is having trouble with the accented characters in "tatou.bat"

**Comment by exoscoriae** [comment]
I have to way to test this.

I saved the original tatou to tatou_original.bat
I modified the new tatou.bat to remove accented characters, but retain the spacing

it works in DOSbox, just doesn't look as fancy as before. 

I'm surprised dosbox behaves differently in linux. maybe an ascii driver isn't getting loaded?
