### ISSUE TITLE
Police Quest 2 - The Vengeance (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2481]
This surprised me, game not cracked

**Comment by TimberlAndRE-de** [comment]
Not tested but old-games.ru has a cracked image
(And also a copy protection sheet)
https://www.old-games.ru/game/download/661.html

**Comment by exoscoriae** [comment]
tested. works.

**Comment by exoscoriae** [comment]
copy protection sheet already included
