### ISSUE TITLE
Dungeon Hack (1993)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#2483]
I found unofficial patch for Dungeon Hack  which "corrects cleric wisdom spell bonuses beyond a wisdom of 19 in the game & nullifies the password protection scheme"
[hackfix.zip](https://github.com/exoscoriae/eXoDOS/files/6018140/hackfix.zip)
[readme.txt](https://github.com/exoscoriae/eXoDOS/files/6018141/readme.txt)

**Comment by exoscoriae** [comment]
applied
