### ISSUE TITLE
Theatre of War (1992)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#2484]
Wrong manual in 5.1 (it's for Theatre of Death). Here's correct one.
[Theatre of War manual.pdf](https://github.com/exoscoriae/eXoDOS/files/6038342/Theatre.of.War.manual.pdf)

**Comment by XavierVelo** [comment]
Also this Theatre of Death manual can be moved to correct place as ToD has none ATM.

**Comment by bigjim161** [comment]
I found:
- a manual with cover
- a trouble shooting guide (extra)
- a command tiles (extra) 
- an installation instructions (extra)

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found

- [ ] addendum

added to the github folder
