### ISSUE TITLE
Radix - Beyond the Void (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2486]
According to Discord user BenMcLean:

the version of Radix: Beyond the Void included in the eXoDOS collection is the November 1995 version when the really definitive version of this game is the patched version 2.0 from November 1996 that fixes the bad controls.

Here is a copy of the registered version 2.0 patch: [radr20p.zip](https://github.com/exoscoriae/eXoDOS/files/6039911/radr20p.zip)

**Comment by exoscoriae** [comment]
would not work on our existing version. Worked on a  floppy install however.

**Comment by exoscoriae** [comment]
no music on the new version. this 2.0 patch is highly problematic

**Comment by exoscoriae** [comment]
got sound in sb16. no music in GUS though. just effects.

**Comment by exoscoriae** [comment]
well shit. looks like GUS music was busted in our old version as well??

**Comment by exoscoriae** [comment]
fixed uses NRS patch located here:
https://www.vogons.org/viewtopic.php?t=41353
