### ISSUE TITLE
Secondary conf for Eye of the Beholder games

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2492]
As with GBC games and Ultima 5 where we have "gbc.conf" being called to set the window size and fullscreen when GBC or Ultimapper is selected, we need to create an "ase.conf" to set fullscreen=false for all three Eye of the Beholder games for when the All Seeing Eye option is selected.

**Comment by exoscoriae** [comment]
could probably just use the gbc.conf, right? same options?

added      -conf ".\dosbox\gbc.conf"     to the ASE launch lines.

Let me know if for some reason you think they need a specific ASE.conf file.

**Comment by Python-Exoproject** [comment]
Separate ASE.conf has now been setup as some needed settings were different to those in GBC.conf.
