### ISSUE TITLE
Gabriel Knight 1 - Sins of the Fathers (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2497]
gschmidl found

- [x] official novel / book
- [x] Game Design Bible Book 1
- [x] Game Design Bible Book 2

added to the github folder

**Comment by Eulisker** [comment]
gschmidl converted the novel to .pdf. that should make it more usable in the pack.

added to the github folder.

**Comment by exoscoriae** [comment]
replaced

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre found

- [ ] Novel (scanned version, it contains more information than our current "OCR" version... but the OCR version is easier to read? not sure, which one to keep, I tend towards the scanned version, it looks more "original")

**Comment by exoscoriae** [comment]
added both
