### ISSUE TITLE
Shadow Sorcerer (1991)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2502]
I found a quickstart guide

Proof: https://youtu.be/VjwGdZ01HKo?t=268

Added to the Github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found

- [ ] interactive code wheel
(I found a real scan of it but it's like black letters on black ground ... I needed to lighten it with photoshop so it's readable but it's not looking like the original any longer so maybe the non-interactive picture of the wheel should be added too, it's included in the zip)

added to the github folder

**Comment by exoscoriae** [comment]
added
