### ISSUE TITLE
La Corona Mágica (1990)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2504]
Metadata contains special characters which are not displaying properly in Launchbox. Suggestion to change "Notes" field to this for the supported formatting that shows correctly:

`This game is based on the Spanish animation series of the same name, broadcast on Televisión Española during the late eighties, so as in the TV series, the action will take place in the System of the Double Sun, composed of seven planets (some inhabited and some not) and twelve moons; but the planet we should take care of is the third, where our friends live, ruled by King Brigal and his son, Prince Zalk.Rahman, the all-powerful wizard of the kingdom, is in possession of the Magic Crown, a mysterious crown with far-reaching powers which keeps the balance of forces between him and the wicked witch Idun and her armies, led by the sinister Zohak, the witch's vizier. They live on the last three planets in the System, the Lost Planets, and you, throughout six arcade levels, must try to recover the crown, for it, you will have to deal with fantastic creatures, evil wizards and witches, helped by your strength and magical powers, until arriving at the final encounter with Rahman.`

**Comment by exoscoriae** [comment]
done
