### ISSUE TITLE
Feud (1988)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2508]
Metadata contains special characters which are not displaying properly in Launchbox. Suggestion to change "Notes" field to this for the supported formatting that shows correctly:

`Wizards Learic and Leanoric have a long-standing feud, and would do anything to see off their rival. As Learic, this is your task. Collecting herbs to cast spells is the main basis of the game. There are 24 herbs and flowers to be collected, which are used to make one of 12 spells (the herbs are only used for 1 spell, so there's no need to decide which spell you'd prefer to have access to). You can use a combination of the spells (including a teleporter, invisibility and a fireball, which you must work our how to use). Leanoric's direction relative to yourself is indicated by a compass.`

**Comment by exoscoriae** [comment]
done
