### ISSUE TITLE
Jahangir Khan World Championship Squash (1991)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2513]
Metadata contains special characters which are not displaying properly in Launchbox. Suggestion to change "Notes" field to this for the supported formatting that shows correctly:

`Squash simulations are something of a rarity, and it was this niché that Krisalis aimed one of their many sports simulations into. The rules of squash are accurately recreated, with a realistic court layout (viewed isometrically) and a need to hit legal shots. Three different ball speeds, variable match lengths and an 'easy' mode are on offer. Different tournament types are on offer, at 'club' and 'tournament' levels, with a customizable ladder system of multiple divisions to rise up. There is a full roster of opponents to play in one-off or tournament modes.`

**Comment by exoscoriae** [comment]
done
