### ISSUE TITLE
Madman (1995)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2516]
Metadata contains special characters which are not displaying properly in Launchbox. Suggestion to change "Notes" field to this for the supported formatting that shows correctly:

`Dr. Dungeon seems to have been (or still is?) a prolific creator of classic-style RPG games. In his own words, his games are intended to "retain the classic flavor of games like Ultima 7, Fallout and Baldur's Gate." So if you like those games, you may like this. Madman is an isometric perspective RPG with decidedly retro graphics and PC beeper sound effects. If you yearn for the days of yore (PC RPG days of yore that is) then you may want to play this.`

**Comment by exoscoriae** [comment]
done
