### ISSUE TITLE
El Capitán Trueno (1990)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2517]
Metadata contains special characters which are not displaying properly in Launchbox. Suggestion to change "Notes" field to this for the supported formatting that shows correctly:

`El Capitán Trueno (Captain Thunder) is the name of a famous Spanish comic book which tells the ongoing story of the eponymous 12th-century hero.  This is the first game dealing with the character, released to all of the Spanish-speaking world's most vital computing platforms at the time: ZX Spectrum, Amstrad CPC, MSX and MS-DOS; all  ports except for the PC version contain two different segments, the first a calmer adventure portion followed by some frenetic arcade action. The final mission is to rescue Sigrid, Trueno's beloved, from the monastery of his friend Abbot Estanislao de Castiglione. Along the way, the Capitán will have to face giant spiders, skeleton soldiers, enormous rats and a plethora of imaginative creatures such as the Abbot transformed into a demonic goat. The Capitán strives to triumph over all these opponents with the assistance of his friends sturdy Goliath, who though immobile can lash out with meaty fists and jump in place to cause earthquakes, and nimble Capitán, a man who can shimmy up a rope of any length.`

**Comment by exoscoriae** [comment]
done
