### ISSUE TITLE
Gore Galore: The Breakout (1995)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2518]
Metadata contains special characters which are not displaying properly in Launchbox. Suggestion to change "Notes" field to this for the supported formatting that shows correctly:

`One of the many undistinguished Wolfenstein 3D clones that tried to make it commercially as shareware. It used the Pie 3D Game Creation System. An escaped homicidal maniac "BLOODY BOB", satisfies your sickest fantasies in a splatter fest of blood & gore. In addition to Ninjas, you'll also fight guys in green uniforms that strangely resemble Hank Williams Jr. and Maytag repairmen donned in blue jumpsuits. In your HUD's health display, you'll get crayon scribbles of red on an image of your character as you get injured. As your health whittles down, your flesh will become bones until you turn into a skeleton. Firearms include a shotgun, rocket launcher, a fire extinguisher, and grenades. Setting itself apart from the rest of your weapons is what could only be considered the most inspired weapon of all time - the poo gun, which acts as a hose allowing you to spray gobs of semi-liquefied shit to bury your enemies under. Sure, the game may call it the "goo gun", but the game's documentation explicitly refers to it as the poo gun.`

**Comment by exoscoriae** [comment]
done
