### ISSUE TITLE
Dawn Patrol (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#254]
pages 8 28 29 32 39 44 52 53 58 and 59 are missing

**Comment by TimberlAndRE-de** [comment]
found full manual with quality upgrade

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
The manual is currently in

- English
- German
- French

However i would vote for keeping the different languages seperate. This is a digital version of the manual with all 3 languages put in the same pdf. The original german releases i could find only ever had a single language. 

Here is the original release:
![image](https://user-images.githubusercontent.com/81642149/146674494-0e73f396-cbed-49ad-9cbf-ed54b731071d.png)

And her is the white label budget release. 
![image](https://user-images.githubusercontent.com/81642149/146674514-1fe31349-5fcb-42ba-bc83-16b707164138.png)

It says "Anleitung" on both so i am pretty sure there is only german in there.

**Comment by TimberlAndRE-de** [comment]
according to Euliskers suggestion I found the scan of the original english 

- [ ] manual.

Added to the github folder.
