### ISSUE TITLE
Exobius (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2543]
You cannot move the ship with the mouse.

In EXOBIUS.cfg, if you change :  "50 2 3 2" to  "50 1 3 2",  you can move the ship with the keys of the numeric keypad.

The Keys are:
Movements:  Numpad (8426)	  Fire: space	Secondary weapon: kp_5 (if available )

**Comment by exoscoriae** [comment]
modified
