### ISSUE TITLE
Ravenloft - Stone Prophet (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2547]
1. There is a problem with the Cutscenes in this game. To fix most of the issues scenes we need to switch to the oldgames image file found here: https://www.old-games.ru/game/download/528.html

2. For the remaining issue cutscene there doesnt seem to be a know fix, though there has been some work on tracking down the issue. Version 1.0 game release works, but Version 1.1 (which has other needed bug fixes) does not. It seems to be an issue with the cutscenes audio which is not part of the video files themselves from what ive read. Here is what ive found online so far:

"Best I have so far is a 1.1 version that is only missing one movie, the one with the little boy talking to you. By bypassing that cinema, I've been able to make the game go right from him running up to the party entering the portal. Something in Code.2 is making an invalid call, I believe to URCHSPK.DFA, which is the animation for him talking. I'm unable to make any sense out of much of the hex for Code.2, I believe it's compiled."

"One idea is to get a debug build of DOSBox and set a breakpoint whenever the game calls DOS to open a file, check the filename being opened, and see when the file containing the video is opened. Once you reach that point, you can try stepping through the machine code to try to figure out what's going on."

And heres some info on the DFA file format: https://wiki.multimedia.cx/index.php/DFA

Here is a screenshot of the error in game: 
![unknown](https://user-images.githubusercontent.com/67406191/110307895-91b2ff00-8053-11eb-9414-9f44cc3b723b.png)

**Comment by Python-Exoproject** [comment]
Im thinking this might be one for ripsaw but failing that the solutions seem to be either turning sound off as that avoids the issue or having the v1 and v1.1 files backed up with a user choice setup to swap versions by swapping the files near the end of the game.

**Comment by exoscoriae** [comment]
replaced the cd image.

I'm holding off on some of these more extreme fixes for now. We'll see what other options come up before the next release.

**Comment by exoscoriae** [comment]
solved via fix from ripsaw
