### ISSUE TITLE
NFL Pro League Football (1989)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2555]
I found:

- [x] a manual
- [x] a  sheet with codes
- [x] an audible card
- [x] a note

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
agathosdaimon scanned his

- [ ] audible cards (=> quality upgrade)

added to the github folder

**Comment by exoscoriae** [comment]
replaced
