### ISSUE TITLE
Ultima Worlds of Adventure 2 - Martian Dreams (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2558]
Just discovered this isnt cracked, the copy protection occurs when you try to exit the spaceship. To do this you must:

1. Talk to the guy sitting the the far top left seat and say "need" so that he offers a prybar. 
2. Go over to the door at the bottom of the area you are in that leads outside. 
3. Click the character image of yourself in the top right of the screen to show your inventory. 
4. Now press "u" to use, select the prybar and click it on the door. 
5. You will then be brought into a conversation that ends with the copy protection.

Hopefully any cracks we find dont cause the issues that the crack for Savage Empire did with skipping the conversation all together. If this happens though Kudgel maybe able to help as he did with Savage Empire.

**Comment by exoscoriae** [comment]
cracked the game using patcher

**Comment by Python-Exoproject** [comment]
Your crack broke the game, you can no longer exit a conversation once its started. To restore you will need to replace game.exe with an original.

Guess this one will require kudgel

**Comment by exoscoriae** [comment]
restored the original files.

**Comment by exoscoriae** [comment]
cracked
