### ISSUE TITLE
Deep II - The Center of the Earth (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#256]
confused symbols  probably damaged or badly converted. a few lines of text are readable between the special characters.

**Comment by SmilingSpectre** [comment]
It's ANSI. I'll upload what it _must_ look like, if you can read ANSI. ;)

**Comment by TimberlAndRE-de** [comment]
cool, thx! converted to pdf and added to the github folder
