### ISSUE TITLE
Taso (1998)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2563]
This game use capslock keys for player 2 (red).
You need to press this key twice with vanilla dosbox, not with SVN Daum

Keys for Plr 2 (red): Movement: WASD  Fire: capslock    Bomb: tab 

Plr1 (blue): Movement: Arrowkeys  Fire: lctrl  Bomb: lshift
Plr 3 (yellow): Movement: i,j,k,l  Fire: m     Bomb: n    
Plr 4 (pink): Movement: kp_5,p_2,kp_3,kp_6  Fire: kp_period     Bomb: kp_0

This  game does not keep changes when you set new keys in the options menu.

**Comment by exoscoriae** [comment]
is the right shift key used at all?

**Comment by exoscoriae** [comment]
not confirmed. no need to press capslock twice. Make sure you are using the same version of ece we are using in the project.
