### ISSUE TITLE
Wrong image extensions

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#2564]
It seems, LaunchBox cannot display in the interface the most pictures that have internal format different from advertized (like JPG named PNG, for example). I made the list with all (hopefully) such images, and marked what type they actually are. 851 images.

**Comment by SmilingSpectre** [comment]
Somehow I duplicated the first part of "back" list. Maybe copied twice *shrug*. Cleared it up now, hopefully. So it' only 841 picture after all.
[Exodos - wrong picture extensions.xlsx](https://github.com/exoscoriae/eXoDOS/files/6152449/Exodos.-.wrong.picture.extensions.xlsx)

**Comment by SmilingSpectre** [comment]
Reuploaded with different output format. Hopefully, it's more useful
[Exodos.-.wrong.picture.extensions.xlsx](https://github.com/exoscoriae/eXoDOS/files/6157207/Exodos.-.wrong.picture.extensions.xlsx)

**Comment by exoscoriae** [comment]
all files have been renamed

**Comment by exoscoriae** [comment]
Running the attached txt file as a bat file from the main exodos folder (where launchbox.exe is found) will rename your image files as well. This is for anyone who wants to do it before the next release.

[rename_images.txt](https://github.com/exoscoriae/eXoDOS/files/6157646/rename_images.txt)
