### ISSUE TITLE
DragonStrike (1990)

### ISSUE THREAD

**Issue by TheKins** [exoscoriae/eXoDOS#2567]
I was having a frankly bizarre amount of trouble with the "Enter Word X of Paragraph Y on Page Z" copy-protection, nothing seemed to work, so I did some Googling and found some instructions on how to crack this game using a hex editor. I put the instructions to practice, and it seems to work after having played a few early missions. (The copy protection prompt still pops up, but you can just type anything in and it seems to work fine)

The instructions:
```
CRACK> Dragon Strike
File: Main.exe
Search for:   8A 05 2E 3A 04 74
Replace with: -- -- -- -- -- EB
Note: There are two occurences of this search pattern replace both.
```

For some reason, I can't attach the modified file, so I've thrown it on the Discord. Sorry for the inconvenience.

**Comment by Python-Exoproject** [comment]
Thanks for the effort Kinsie but did you try just pressing enter? The game is already cracked, but it only works if you type nothing but enter

**Comment by TheKins** [comment]
...huh. Well, I'm dumb. Thanks for the heads-up.
