### ISSUE TITLE
F-15 Strike Eagle II (Deluxe Edition) (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2572]
Eulisker found

- [ ] technical supplement

added to the github folder

**Comment by Eulisker** [comment]
I found a higher quality version of 

- [ ] Maps
- [ ] Reference Card

The Reference Card is currently split into 2 files but it is front and back of the same card.

Thanks to discord user remowilliams for scanning.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
