### ISSUE TITLE
Aliens - A Comic Book Adventure (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2578]
Eulisker found

- [ ] manual (US-Version and quality upgrade)

added to the github folder

**Comment by exoscoriae** [comment]
the pictures are much worse in this quality upgrade. There are less artifacts, but I don't think it is worth the degradation of the pictures in the manual.

denying this one

**Comment by Eulisker** [comment]
Manual in

- English
- French
- German

**Comment by Eulisker** [comment]
I found a higher quality

- [ ] manual

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
