### ISSUE TITLE
King's Quest V - Absence Makes the Heart Go Yonder (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2583]
Eulisker found

- [x] addendum from the cd-version

added to the github folder

**Comment by Eulisker** [comment]
I found 

- [ ] The official Book of King's Quest - Second Edition

It covers Kings Quest 1-5 and should replace the old version in all 5 games.

**Comment by exoscoriae** [comment]
added addendum
replaced all official book of KQ entries with 2nd edition
