### ISSUE TITLE
Prince of Persia (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2589]
Eulisker found

- [ ] Code Protection Codes (quality upgrade from cd collection)

added to the github folder

**Comment by exoscoriae** [comment]
prefer the original ones.

**Comment by TimberlAndRE-de** [comment]
found

- [ } Poster

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found 

- [ ] Manual (Later Release)

This manual is from the hourglass shaped box of Prince of Persia that was released along side the Macintosh Version in 1992.

<img width="716" height="971" alt="Image" src="https://github.com/user-attachments/assets/80208e9d-a498-43e3-b41d-21cf680ca1db" />

This is the Mac version but the PC Version is the same.

Added to the github folder.
