### ISSUE TITLE
Sol Negro (1988)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2604]
Metadata contains special characters which are not displaying properly in Launchbox. Suggestion to change "Notes" field to this for the supported formatting that shows correctly:

`A millenarian spell, transmitted from parents to children, turned the muscular Bully into a fish and the indomitable Mónica into a hawk. Every full moon one of them suffers a transformation and the other recovers his normal form, which prevents them to be together. Only an extraordinary phenomenon can break the spell, something as extraordinary as a sun eclipse... the Black Sun. In order to break the spell, Bully must free Mónica  (the hawk) of her cage for, turned he in fish, arrive on time together at the sacred submarine temple of the sun, a grotto located beyond the borders of the city submerged of Hidrionis, just at the moment in which the moon is embraced with the sun and a huge shade crosses the planet. The objective in the first stage is to rescue Mónica , turned a hawk, for which you will have to locate the key of the cage on which she is imprisoned and go to rescue her, you will count with the help of a jet pack and a M-92 rifle laser; once done, face together with her all the dangers until arriving at the magical palace. The second stage is developed at the heart of the ocean. Mónica  must protect Bully in his form of fish and together with him arrive at the submarine grotto. Mónica  counts with an aquatic propellent and a hydro leak pistol with which she will have to defended herself against the submarine enemies.`

**Comment by exoscoriae** [comment]
added
