### ISSUE TITLE
Demon Stalkers (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#262]
has watermark theunderdogs.org on page 1
scanned with text-recognition and converted to text  font and text-size changes sometimes
it's for amiga / commodore

**Comment by TimberlAndRE-de** [comment]
i found a quality upgrade (scanned) without watermark
but it's still for c64, @exoscoriae please replace the manual and leave the issue open, hoping someone finds an IBM version of the manual

**Comment by exoscoriae** [comment]
the quality is really blurry... I'd rather keep what we had.

**Comment by exoscoriae** [comment]
removed underdogs watermark from existing manual
