### ISSUE TITLE
Desert Strike - Return to the Gulf (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#266]
has watermark replacementdocs on page 1
first page is not the real cover but the boxfront

**Comment by exoscoriae** [comment]
removed watermark. we should try and find an original manual.

**Comment by SmilingSpectre** [comment]
Uploaded. With "watermarks", unfortunately.

**Comment by TimberlAndRE-de** [comment]
added to the github

**Comment by Eulisker** [comment]
Manual in 

- English
- French
- Italian
