### ISSUE TITLE
Discworld (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#273]
has watermark replacementdocs
pages 1 and 2 are missing

**Comment by TimberlAndRE-de** [comment]
https://www.mobygames.com/game/dos/discworld/cover-art/gameCoverId,388879/
cover can be added from moby

**Comment by SmilingSpectre** [comment]
Page 2 is not missing, as second page marked as "3".

Also, found guide for it. Uploaded.

**Comment by TimberlAndRE-de** [comment]
the manual is password-protected so i can't remove the watermark
also the coverpage from moby doesn't look like it fits to the current manual

@SmilingSpectre 
where did you upload the guide? i can't find it in your folder or the github folder

**Comment by SmilingSpectre** [comment]
Watermark removed. Uploaded in my dropbox.

**Comment by TimberlAndRE-de** [comment]
added to the github folder but coverpage is still missing, please put it back in "To do" after processing

**Comment by TimberlAndRE-de** [comment]
discord user wysiwyg found a quality-upgrade with color and frontpage, added to the github folder

**Comment by exoscoriae** [comment]
replaced
