### ISSUE TITLE
Robix (1993)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2738]
I found front and back covers
![Robix box- Cover front](https://user-images.githubusercontent.com/67555221/113035572-a33f8080-9193-11eb-8ba3-96d772be0b2d.jpg)
![Robix - back cover](https://user-images.githubusercontent.com/67555221/113038012-46919500-9196-11eb-8e72-39a0b477306a.jpg)

**Comment by bigjim161** [comment]
I found media
![Robix media](https://user-images.githubusercontent.com/67555221/113046147-f9b2bc00-919f-11eb-90f1-d1be54200c67.jpg)

**Comment by exoscoriae** [comment]
added
