### ISSUE TITLE
The Dig (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2740]
I found 2 "game design document"

Added to the github folder

**Comment by Eulisker** [comment]
I found the 

- [ ] Inside cover

Maybe it is worth to add this? Here is a photo of the german version for context.

![dig flip cover](https://user-images.githubusercontent.com/81642149/117021441-a4fee580-acf7-11eb-8525-55757042d24f.jpg)


added to the github folder.

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found

- [ ] Novel by Allen Dean Foster

**Comment by exoscoriae** [comment]
added
