### ISSUE TITLE
Grand Theft Auto & GTA: London (1997)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2742]
I found a game design document.
It has working title "Race 'n' Chase" (according to mobygames  : https://www.mobygames.com/game/grand-theft-auto)

Added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
scanned my copy of the

- [ ] maps (quality upgrade)

**Comment by exoscoriae** [comment]
looks awesome. thanks!
