### ISSUE TITLE
Mixed-Up Mother Goose (1987)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2744]
I found three extras:

- [x] Ryhmes
- [x] Map closed flaps
- [x] Map flaps open

Added to the github folder

**Comment by Eulisker** [comment]
I am pretty sure these were in every version of the game and should be added to the 1990 and 1991 version also. I can not find a picture of the complete content unfortunately. But "full color map" is noted on the back cover for every version as far as i can tell.

See [1987 release](https://www.mobygames.com/game/mixed-up-mother-goose/cover-art/gameCoverId,70135/), [1990 rerelease](https://www.mobygames.com/game/mixed-up-mother-goose/cover-art/gameCoverId,62683/), and [1991 CD Releas](https://www.mobygames.com/game/roberta-williams-mixed-up-mother-goose_/cover-art/gameCoverId,171216/)

**Comment by TimberlAndRE-de** [comment]
found

- [ ] registration card

added to the github folder

**Comment by exoscoriae** [comment]
added to 87 and 90 versions. I question the inclusion in the 1991 CD release, as it is a very different game. I will wait for evidence on that

**Comment by Eulisker** [comment]
I found a better version of the

- [ ]  Map (Flaps open)

Added to the github folder.

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre found a different version of the

- [ ] manual / Parent guide

could be added as an extra to the 87 and 90 version

added to the github folder

**Comment by exoscoriae** [comment]
we had the 1990 version on the 87 version. replaced it
