### ISSUE TITLE
Disney's Aladdin (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#275]
has watermark replacementdocs
frontpage says English  Francais  Deutsch  Italiano  Espanol but only the english manual is included. So obviously the other pages are missing!

**Comment by exoscoriae** [comment]
removed watermark

**Comment by exoscoriae** [comment]
replaced with full manual

**Comment by Eulisker** [comment]
I scanned the 

- [ ] manual

The quality of the current manual is not the best. The manual is for the amiga version and you need the PC Instructions for it. See #2985 

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
Manual in

- English 
- German
- French
- Italian
- Spanish
