### ISSUE TITLE
Combat Air Patrol (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2753]
agathosdaimon reported sound and speed issues. Confirmed by spectre. It was reported as having GUS option as well. Options are:

"To set up your soundcard for a SoundBlaster v2 card, use CAP -a 1
To set up for a Gravis Ultrasound card, use CAP -a 2
For a SoundBlaster AWE32, use CAP -a 3
For no sound, use CAP -a 4"

it was reported that 10000 cycles and pentium cputype work better but I have not tested as you said that you were actioning the bug report the same day.

**Comment by exoscoriae** [comment]
switched to gravis. sb sounds horrible

**Comment by Python-Exoproject** [comment]
I dont think this game made it onto the eXoDOS GUS playlist

**Comment by exoscoriae** [comment]
added to playlist. thanks for checking.
