### ISSUE TITLE
Tornado (1993)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2756]
found

- [x] Maps
- [x] Technical Supplement

better quality scan for the maps. Also you dont have to use your imagination to see the full map. 
The technical supplement is a scanned version of the digital one that is at the end of the current manual. It was a seperate document in the original release,

![Tornado](https://user-images.githubusercontent.com/81642149/113510639-09dde900-955c-11eb-9697-d784bd26116c.jpg)

It is the european version in en, fr, it, ger

Added to the github folder.

**Comment by exoscoriae** [comment]
added\replaced

**Comment by exoscoriae** [comment]
added
