### ISSUE TITLE
X-COM - UFO Defense (1994)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2757]
found

- [x] The Official Strategy Guide

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] novel

added to the github folder

**Comment by Eulisker** [comment]
I found

- [ ] Strategies and Secrets

Added to the github folder.

**Comment by exoscoriae** [comment]
added
