### ISSUE TITLE
A320 Airbus (Edition Europa) (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2761]
I found

- an English front cover (the current one is German)
- a back cover'
- a disk image
![Airbus A320 european edition front cover](https://user-images.githubusercontent.com/67555221/113519049-36a8f500-958a-11eb-85cf-7ee0b67308cd.jpg)

![Airbus A 320 european edition back cover](https://user-images.githubusercontent.com/67555221/113515283-d4dd9080-9573-11eb-88b1-9720ce38797e.jpg)

![Airbus A 320 european edition Image](https://user-images.githubusercontent.com/67555221/113515289-dd35cb80-9573-11eb-8e02-c6dd05912f96.jpg)

Proof: https://www.ebay.ca/i/223974230416
https://www.ebay.fr/itm/373495431401?mkevt=1&mkcid=1&mkrid=709-53476-19255-0&campid=5338722076&toolid=10001

**Comment by exoscoriae** [comment]
replaced
