### ISSUE TITLE
Astrorock (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2762]
@SmilingSpectre has noted:

"TServo2049 discovered, we have cd-rip of Astrorock. Most obvious sign is missing "SONG1" in the "MUSIC" folder (we have it, but it's zeroed). TDC has the same, only with intact song - but it not warrants that something else wasn't missed. Disc is quite cheap on ebay. For example: https://www.ebay.com/itm/Astrorock-PC-1996-Near-Mint/174580518029?epid=170191261"

**Comment by exoscoriae** [comment]
Purchased

**Comment by exoscoriae** [comment]
ripped and reinstalled game with original cd media
