### ISSUE TITLE
Champ Ms. Pac-Man (1994) & Champ Ms. Pac-Em (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2763]
Noted by TSerco2049:

"Champ Ms. Pac-Man (1994) in the collection is the same as Champ Ms. Pac-Em (1996). All files are identical. There was indeed a Champ Ms. Pac-Man in 1994 which was a straight DOS remake of the original game, before the revamped CHAMP Ms. Pac-Em, but only the “Lite” shareware version exists online and is in TDC. I have no idea if John Champeau still has the full version (there is a fan site with the history of his stuff, maintained by someone else, they also don’t have it for download) and if so whether he would be willing to share it. So for now we can either replace the CHAMP Ms. Pac-Em duplicate with CHAMP Ms. Pac-Man Lite, or just remove CHAMP Ms. Pac-Man from the collection entirely. I guess if the shareware is all that exists and we already have a collection entry, it wouldn’t hurt to put in?"
"Actually my notes indicate the 1994 shareware one might have been in v4 but was replaced with a duplicate of CMP-Em 1.5 registered in v5."

**Comment by exoscoriae** [comment]
restored to 1994 shareware version
