### ISSUE TITLE
Lurking Horror, The (1987)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2764]
While looking at the infocom stuff I noted that this game is meant to have sound. I have no idea where it is triggered to test it but I did note from a readme:

"Next you should go to the directory which you usually use for playing
The Lurking Horror and create a subdirectory SOUND.  Move all the SND
files from this package to that subdirectory.  As you can see, all the
sound files are called LURKINxx.SND.  If, for instance, you insist on
calling your data file HORROR.DAT, you would have to rename all the
sound files to HORRORxx.SND."

As exodos has the dat as "lurking.dat" and the sound files are lurkinxx.snd it implies according to this that the sound wouldnt work.

**Comment by exoscoriae** [comment]
i think the simple reason it had no sound is that it was being run through frotz

**Comment by exoscoriae** [comment]
confirmed the version we have already works with sound
