### ISSUE TITLE
Airlines (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2766]
TheThirdFall and @SmilingSpectre have discovered that there is a bug in our CD release, it causes a freeze between day cycles along with the mouse cursor disappearing.

They note that the floppy version does not have the same issue. We need to either switch to the floppy version or locate a working CD. Spectre has noted that the only relevant difference is the intro so your call. Here is a copy of the v1.11 floppy: 
[Airlines_1994InteractivisionRev1.11.zip](https://github.com/exoscoriae/eXoDOS/files/6258853/Airlines_1994InteractivisionRev1.11.zip)

If you wish to locate the CD then an issue will need to be added to the missing media project in github.

**Comment by Python-Exoproject** [comment]
More information from @TimberlAndRE-de saying:

"My Airlines disc is a v1.10 and it has the same behaviour with vanishing mouse cursor, but obviously without a crack (it seems to have a simple cdrom disc checking copy protection) ... so I guess the problem is in the game itself, not the crack. It's also DOS, just the disc menu is Win3x (the disc was a coverdisc from a German magazine)."

So this means the issue is with the CD version itself and will need someone like ripsaw to fix if its ever going to be. Probably easier just to stay with floppy version for now?

**Comment by exoscoriae** [comment]
repacked with floppy version.
