### ISSUE TITLE
A.G.E.  (1991)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2767]
I found

an IBM PC front cover (the current one is for Amiga)
a back cover'
![A G E Front cover](https://user-images.githubusercontent.com/67555221/113600790-cdd08400-9640-11eb-9302-35fdc8bc3fcd.jpg)
![A G E back cover](https://user-images.githubusercontent.com/67555221/113600795-d032de00-9640-11eb-9f60-ce86fcde8307.jpg)

**Comment by exoscoriae** [comment]
replaced
