### ISSUE TITLE
Terminator, The (1991)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2768]
I scanned front and back cover for The Terminator. The current ones are not very good.

![Terminator Front](https://user-images.githubusercontent.com/81642149/113890646-a3a7cf00-97c4-11eb-8d82-7422a3fbd627.jpg)
![Terminator Back](https://user-images.githubusercontent.com/81642149/113890652-a4d8fc00-97c4-11eb-9b60-ca2092b9e208.jpg)

**Comment by exoscoriae** [comment]
replaced
