### ISSUE TITLE
Seasons of Sakura (1997)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2771]
1-According to the readme.txt file of the exodos version : _"...Season of the Sakura includes CD-AUDIO tracks which allow you to listen to the music on ANY CD Player, at a party, in your car, anywhere!"_

Exodos version is a CD RIP without audio tracks. The game plays only the standard MIDI-based sound and no stereo CD music.

I found an ISO with corrupted cd audio files. here : https://mega.nz/file/CssQxCYQ#hWAlNQbSNhXFPL3VtiMWCSi7StECtUZ8ntyXYUNlYz4

If necessary, I recreated the audio tracks with the mp3 files from the "JAST USA Memorial Collection" ISO (a compilation which includes Seasons Of Sakura) at https://www.legendsworld.net/adventure/game/4933
Now if we type "SAKU-CD", at the dos prompt, the game uses stereo CD music.
Added to the Github "Bugs" folder (with new covers and cd image)

2- IMO, on the DOS master list and Launchbox, the game can be renamed  in "Seasons of **the** Sakura" instead of "Seasons of Sakura" (see covers and mobygames https://www.mobygames.com/game/season-of-the-sakura )

**Comment by exoscoriae** [comment]
thanks. please place files in the dropbox going forward instead of linking them in the github. Many times these links die before I get to them.

**Comment by exoscoriae** [comment]
ok, so this is corrupted because the person who created that image used linux and doesn't understand how to properly dump a game.

I do not see the mp3 files in the github bugs folder.

**Comment by exoscoriae** [comment]
I tried your "fixed" cd image and I still get blasting static

**Comment by bigjim161** [comment]
You mean you can't listen cd audio music during the game? Or the quality is bad ?

**Comment by exoscoriae** [comment]
seems incompatible with certain versions of dosbox. fixed and closed
