### ISSUE TITLE
Darker (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2775]
Looks like there have been some updates to https://en.wikipedia.org/wiki/List_of_MT-32-compatible_computer_games#Table_of_compatible_games

Here is a new game for both MT32 and SC55. Set darker.bat to:

mus=1 for sb
mus=2 for gm
mus=3 for mt32

Along with other needed changes like ECE, conf\run.bat, and add to LB playlist for SC55 and MT32

**Comment by exoscoriae** [comment]
i guess that other game was meant to be seen *after* this one. which adds some context.

**Comment by exoscoriae** [comment]
setup mt32 and gm. added to playlists and marked in master
