### ISSUE TITLE
Demoniak (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2776]
From https://en.wikipedia.org/wiki/List_of_MT-32-compatible_computer_games#Table_of_compatible_games:

Open file 'D1' in hex editor and change value '0E' to '00' at offset 00000A15, then set 'sbtype=none' in DOSBox config for Roland sound in intro (or change first two bytes of 'D0' file to F9 CB). DOS version has unique intro music

If it works then the usual ECE, run.bat\conf, and add to LB MT32 playlist

**Comment by exoscoriae** [comment]
worked. added to relevant lists\playlists
