### ISSUE TITLE
Discoveries of the Deep (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2777]
For MT32 select '5' instead of '3' in config.exe at the second question for Roland music. Need to type the full "config.exe" at the prompt as dosbox intercepts the call for its own config if you just type "config". Then the usual conf\run.bat and add to MT32 LB playlist. May need to remove the "mpu401=uart" line in conf?

**Comment by exoscoriae** [comment]
this isn't very clear. is this to add mt32 options to the game? As it stands right now, it does not have mt32 enabled. I had to read through this multiple times to figure out what was going on.

A line clarifying what I am reading and the point of a bug report may be useful for me going forward.

**Comment by exoscoriae** [comment]
I re-read the above a few times and was able to get mt32 enabled.

I find it noteworthy that the sound file we have recorded for paly in the launchbox menu sounds different from both of our current sound options.

added to playlist and noted as mt32 enabled in the master db
