### ISSUE TITLE
Universal Warrior (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2783]
We currently have both the gravis and MT32 asking the user to press "2" to select in run.bat

Also when I choose MT32, after the intro it is freezing for me. I tried rerunning setsound (need to set sbtype to none and use autodetect to find the correct base address) and it crashed out instead.

**Comment by exoscoriae** [comment]
our version appears to be a RIP, noticed RAZORCD.exe file in the folder.

I found an installer in TDC, however it locks up on both Gravis and MT32 after the initial intro video.

renaming this to The Machines, as that was the PC release name (Universal Warriors was Amiga).
Passed this over to ripsaw to take a look after spending an hour on it.

**Comment by exoscoriae** [comment]
ripsaw provided fixed files. GUS and MT32 now work, and MT32 also allows sb16 fx now.
