### ISSUE TITLE
Scooter's Magic Castle (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2784]
Another new MT32 title.

If you set mididevice=mt32 and edit scootcd.bat to launch "scootcd.exe /mr /sr /vv /c" instead of "scootcd.exe /ms2 /ss2 /vv /c" you get Roland music and sound. Only setting the music to roland with /mr and keeping sound blaster for sound with /ss2 ignores the roland music switch. 

Usual conf\run.bat and add to LB MT32 playlist.

**Comment by exoscoriae** [comment]
added mt32 support and added to LB playlist
