### ISSUE TITLE
Simon the Sorcerer II - The Lion, the Wizard and the Wardrobe (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2785]
According to https://en.wikipedia.org/wiki/List_of_MT-32-compatible_computer_games#Table_of_compatible_games you need to delete the "midi" file when using SC55 to get proper GM sound. I tested this and to my ear it does sound better. What do you think?

**Comment by exoscoriae** [comment]
sounds *much* better. good find.

**Comment by Python-Exoproject** [comment]
The zip still has the "MIDI" file in the SC55 folder, delete it from the folder so that it doesnt get copied in when selecting SC55 to action this bug

**Comment by exoscoriae** [comment]
removed
