### ISSUE TITLE
Super-VGA Harrier (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2786]
Another MT32 game.

To set this one up you need to install from the original floppies and select Roland so that the roland driver gets installed. I found a copy of the floppies on old-games but when I tried to install it gave a verification error saying unable to read file date\time.

Once you get it successfully installed then usual conf\ece\run.bat and LB MT32 playlist.

**Comment by exoscoriae** [comment]
upgraded to use mt-32

**Comment by Python-Exoproject** [comment]
Sweet, however once the intro finishes it drops to desktop. Used a pause to find this message after fly.bat is executed from inside av8b.bat:

![image](https://user-images.githubusercontent.com/67406191/128633104-6692b5f0-a9ff-43a0-9d24-85c8c6ad7721.png)

**Comment by exoscoriae** [comment]
thanks. fixed by reinstalling with vesa compatible svga instead of s3. I need to playtest this longer!

**Comment by exoscoriae** [comment]
is 3k cycles enough for this game?

**Comment by exoscoriae** [comment]
set it tom10k for now. better than max
