### ISSUE TITLE
The Last Bounty Hunter (1994)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2788]
1- I found a manual

Added to the Github folder

2- I found the real CD image DOS disc (the current one is the CD image Windows xp disc)

![Last Bounty Hunter CD (Front)](https://user-images.githubusercontent.com/67555221/115057785-c16fe500-9ee4-11eb-8966-ed420bfb9030.jpg)

**Comment by exoscoriae** [comment]
replaced
