### ISSUE TITLE
The Elder Scrolls Adventures: Redguard (1998)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2792]
I found the Redguard Companion, the official hint and strategy guide.

Added to the Ghithub folder

**Comment by TimberlAndRE-de** [comment]
found a

- [ ] map (quality upgrade)
- [ ] Redguard Companion - Official Hint and Strategy Guide (from bigjims post above to make sure it isn't missed)

added to the github folder

**Comment by exoscoriae** [comment]
added
