### ISSUE TITLE
Castle Master II - The Crypt (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2793]
discord user sknvndo found
cover (it's atari but it's the same as the IBM version with an Atari Sticker, so it could be added until a real IBM version is found)

- [ ] @SmilingSpectre found a better one without sticker

added to the github folder (but I can't delete the other one for atari, please delete it eXo)

proof:
![grafik](https://user-images.githubusercontent.com/67441153/115503379-9e438d80-a276-11eb-99a2-b83db19ecf15.png)

**Comment by exoscoriae** [comment]
created my own copy to fix the washed out one. added
