### ISSUE TITLE
Where in Europe is Carmen Sandiego (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2805]
Discord user Ricky Derocher noted that by using "carmen ega" and setting machine type back to normal from current cga the game  will use EGA graphics instead of current CGA. 

Not sure if you want to keep current CGA and CGA composite option as well as EGA option (need two .conf file setup) or just switch to EGA but either are viable options.

**Comment by exoscoriae** [comment]
switched it to EGA for now.
