### ISSUE TITLE
Fighter Wing (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2807]
Tservo2049 discovered a patch to upgrade from v1 to v2. According to the patch notes ([FWUPDATE.txt](https://github.com/exoscoriae/eXoDOS/files/6366067/FWUPDATE.txt)) the only real improvement might be to network play. Here is a copy of the patch I located ([fwcd20.zip](https://github.com/exoscoriae/eXoDOS/files/6366076/fwcd20.zip)). I installed it, but I couldnt tell if it worked as none of the new key combinations listed in the patch notes seem to do anything for me.

Additionally, whether you update or not, the graphics detail can be significantly increased by starting a new pilot, selecting options, and clicking on the word "resolution" (not the box next to it with "Low/Adjust") until it says "High/Adjust". Afterwards the pilot file you created can be deleted and the change will stay.

**Comment by exoscoriae** [comment]
I installed the patch manually and confirmed it worked. the bat included in the patch is busted.

I upgraded the resolution for the game

cycles seemed high at max. lower them to 40k. Might still be too high.

I seem to be having no luck getting it to actually match make though. I wouldn't have left the multiplayer as-is if I hadn't gotten it to work before. So I am a bit confused on that front.

**Comment by exoscoriae** [comment]
The patch notes mention each copy must have a unique serial number. This is problematic for multiplayer.


MULTIPLAYER SCENARIOS:

Fighter Wing allows up to 16 players on a network and playing via modem or
serial cable.  In order for this to properly work, you will need to have
different serial numbers, i.e. two copies of the program.  Merit Studios 
has the following multiuser discount.  

Six Players Total     -  $50
Eleven Players Total  -  $75
Sixteen Players Total - $100 

The following steps should help in setting up multiplayer scenarios

1.  Each Player selects MultiPlayer Scenario
2.  On a Network, one player selects HOST, the others select Non-Host.  Via
    Modem, the CALLING PLAYER is the NON HOST!!!!  After these selections are
    made, HOST will control the setup.
3.  Host will select the MultiPlayer Scenario
4.  Host will select TEAMS.  (If needed, teams can be added)  When teams
    are selected correctly, they will appear at the top in GREEN, i.e. TEAM ONE
    VS TEAM TWO
5.  Host and Non-Host will receive the SELECT PILOT SCREEN.  Individuals will
    select a pilot and join a team.
6.  All players will receive the MISSION DESCRIPTION SCREEN.  Press OK when
    finished reading this screen.
7.  All players will receive the SELECT PLANES SCREEN.  When player has
    selected plane, press OK.
8.  All players will receive the SELECT WEAPONS SCREEN.  Select your loadout
    and press OK.
9.  Each player will then show PREPARING TERRAIN.  After the program will
    show the SELECT PILOT SCREEN and will prepare the players for the upcoming
    game.  When each player's name turns RED, the game will begin.

**Comment by exoscoriae** [comment]
fixed it. 

found a second serial number. added a second install to the game folder with the second serial. Was able to get IPX working in this manner.

Not sure what happens if more than 2 people try to play though. Presumably we would need yet another serial # for that unless we found a way to hack that check from the gane.
