### ISSUE TITLE
Ultimate NFL Coaches Club Football (1994) & Ultimate Football '95 (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2808]
From @SmilingSpectre:

1. MPS released one game twice. Ultimate NFL Coaches Club Football in 1994 and Ultimate NFL Coaches Club Football 95 year later, upgraded with different leagues and extras. Second one actually named Ultimate Football '95, except for readme.
2. eXoDOS haven't Ultimate Football '95. It's '94 version instead, twice. (With CD in supposed '95 version, and CD-rip in '94).
3. agathosdaimon uploaded the correct version. I tested and confirmed it. Uploaded to my folder.
4. So we need: 
- get rid of Ultimate NFL Coaches Club Football (1994).zip (it's crippled anyway).
- replace it with Ultimate Football '95 (1995).zip (as it's actually Ultimate NFL Coaches Club Football (1994), tuned and full).
- create Ultimate Football '95 (1995) anew, from the new ISO.

**Comment by exoscoriae** [comment]
all sorted out. added network play to the 95 (added to playlist as well)
