### ISSUE TITLE
Hocus Pocus (1994) & Clyde's Revenge (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2812]
It has been discovered and confirmed by @SmilingSpectre that these two games use a system that puts save games, high scores, etc in the same file as the sound settings get stored. This means whenever you start a game and select your sound device your save game is overwritten by the backed up files from that sound choice.

**Comment by exoscoriae** [comment]
Fixed both games.

Also added GUS to Clyde's Revenge

**Comment by exoscoriae** [comment]
also added Clyde's Revenge to the GUS playlist

**Comment by Python-Exoproject** [comment]
Due to Hocus Pocus GUS mode using a different launch command this wasnt working the second time around if GUS was selected. I have fixed it and attach the updated run.bat:
[HocusRun.zip](https://github.com/exoscoriae/eXoDOS/files/6576049/HocusRun.zip)

For Clydes Revenge there is currently both a GUS.SEL and SB16.SEL which is causing both options to show in the launcher. The game is actually currently setup for GUS, so delete SB16.SEL to fix.

**Comment by exoscoriae** [comment]
added your run.bat to the archive.

removed SB16.sel from clyde's revenge

thanks!
