### ISSUE TITLE
Dune (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#282]
has watermark replacementdocs

**Comment by TimberlAndRE-de** [comment]
Quality Upgrade for the manual
SmilingSpectre found it on scrib'd
https://ru.scribd.com/document/417949862/Dune-CD-ROM-Manual (scan vs OCRed)

**Comment by bigjim161** [comment]
I scanned my own manual of Dune.
It is in several languages: ​​English French German Spanish and Italian.

Added to the Github folder
It can be added as an extra or to replace current manual or for a future language pack.

**Comment by TimberlAndRE-de** [comment]
no matter how eXo decides, I have already secured it for the German language pack, thx ;-)

**Comment by exoscoriae** [comment]
compressed to 15mb. Retains all quality.
