### ISSUE TITLE
Mike Ditka Ultimate Football (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2825]
tomwatayan (cgboard) found

- [x] code wheel

converted to interactive and added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by bigjim161** [comment]
I found a manual with covers and screenshots.

the current one com has only text and no covers

added to the github folder

**Comment by exoscoriae** [comment]
added
