### ISSUE TITLE
Retribution (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2828]
tomwatayan (cgboard) found

- [x] code wheel

converted to interactive and added to the github folder

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] alternate manual from CD version (booklet) with additional (CD-)install guide informations

could be added as an extra alt manual
added to the github folder

**Comment by exoscoriae** [comment]
added
