### ISSUE TITLE
Strike Aces (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2829]
tomwatayan (cgboard) found

- [x] code wheel

converted to interactive and added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I scanned

- [ ] Advertisement
- [ ] Flying Competition
- [ ] Registration Card

These are all from the european release "Fighter Bomber".

Added to the github folder.

**Comment by exoscoriae** [comment]
added
