### ISSUE TITLE
Les Manley in - Lost in LA (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2834]
tomwatayan (cgboard) found

- [x] code wheel

converted to interactive and added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found (on mocagh)

- [ ] registration card
- [ ] poster
- [ ] poster ad card
- [ ] hintbook ad card

**Comment by exoscoriae** [comment]
added
