### ISSUE TITLE
Global Thermonuclear War (1985)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#2837]
Notes section is currently empty. Suggest capturing with a boilerplate entry

`Global Thermonuclear War is a single player strategy video game for MS-DOS, created and published by PC-SIG in 1985.`

If we want to get cheeky we could add:

```
A STRANGE GAME
THE ONLY WINNING MOVE IS
NOT TO PLAY.
```

**Comment by exoscoriae** [comment]
added =)
