### ISSUE TITLE
Ferrari Formula One (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2843]
When the game starts you will have a menu that allows you to configure your game. One of the icons is a trophy and if you click on the trophy it brings up copy protection despite an intro screen on game start saying its cracked. If you use the manual to get past the protection it looks like its the save\load game function, so probably best if we get this properly cracked.

**Comment by SmilingSpectre** [comment]
Here is cracked exe+proper .bat (borrowed from TDC).
[Ferrari Formula One (exe+bat).zip](https://github.com/exoscoriae/eXoDOS/files/6403888/Ferrari.Formula.One.exe%2Bbat.zip)

**Comment by exoscoriae** [comment]
added cracked files
