### ISSUE TITLE
Bard's Tale 1, The - Tales Of The Unknown (1987)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2852]
I found a 

- [ ] manual

for the [PC Version.](https://www.mocagh.org/loadpage.php?getgame=bt1-alt) The current one is abridged and seems to be from the [C64 version.](https://www.mocagh.org/loadpage.php?getgame=bt1uk-alt)

Added to the Github folder.

**Comment by exoscoriae** [comment]
replaced
