### ISSUE TITLE
Castle Master (1990)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2858]
I found a 

- [ ] manual

Added to the github folder.

The current manual is for the compilation of Castle Master 1+2. Maybe it is worth it to keep one of them as an extra in Castle Master 1? The difference is the added part for Castle Master 2, tech info for all the versions and a poem (?) at the end. 
The better version of the Castle Master 2 manual is in #2857

**Comment by exoscoriae** [comment]
replaced
