### ISSUE TITLE
Dig, The (1995)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2866]
I found a better scan of the 

- [ ] manual

Added to the github folder.

**Comment by exoscoriae** [comment]
not seeing this in the github folder

**Comment by Eulisker** [comment]
It is there now.

**Comment by exoscoriae** [comment]
existing copy seems to be much higher quality? rejected

**Comment by Eulisker** [comment]
I cropped the manual and put it in the github folder.

**Comment by exoscoriae** [comment]
thank you! replaced!
