### ISSUE TITLE
Atomino (1990)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2868]
I found a better looking scan of the 

- [x] manual

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced

**Comment by TimberlAndRE-de** [comment]
found a complete 

[ ] manual  (colored scan and with all the missing languages)

added to the github folder

**Comment by Eulisker** [comment]
Manual in 

- English
- French
- Italian

**Comment by exoscoriae** [comment]
replaced
