### ISSUE TITLE
Star Trek The Next Generation - A Final Unity (1995)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2869]
I found a better scan of the

- [x] Install Guide

and a 

- [x] Note

Added to the github folder.

**Comment by exoscoriae** [comment]
existing install guide has no artifacts and is cleaner.

**Comment by exoscoriae** [comment]
added note

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] official strategy guide

added to the github folder

**Comment by exoscoriae** [comment]
added
