### ISSUE TITLE
Gal Pani II (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2872]
This game is on the missing DOS games list
Mobygames: https://www.mobygames.com/game/gal-pani-ii  
Genre: action Puzzle adult   Published by: MYCOM
Developed by: Scio Co., Ltd.
Tested with PCem v.17 msdos mode

Added to the Github folder with: manual, covers, extras, cd image....

**Comment by exoscoriae** [comment]
Added
