### ISSUE TITLE
Gal Pani (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2873]
This game is not on the Dos missing games list and on the Dos master list .  Mobygames has only pc98 version  https://www.mobygames.com/game/pc98/gal-pani  
Genre: action Puzzle adult  
Developer: Kaneko  
Publisher: Creo i
Tested with PCem v.17 msdos mode

Added to the github folder (with the pc98 manual)

**Comment by exoscoriae** [comment]
Added
