### ISSUE TITLE
Hell - A Cyberpunk Thriller (1994)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2874]
I found a 

- [x] Hintbook

Added to the github folder.

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] booklet (water damaged, should be replaced by a clean scan but all is readable - will do for now)
- [ ] registration card
- [ ] Hint Book order card

added to the github folder

**Comment by exoscoriae** [comment]
added
