### ISSUE TITLE
Legend of Kyrandia Book 1 (1992)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2876]
I found

- [x] Hintbook
- [x] Westwood News & Notes 1
- [x] Poster

Added to the github folder.

**Comment by TimberlAndRE-de** [comment]
and in addition:

- [ ] Registration card
- [ ] Addendum
- [ ] Virgin Clothes order card

added to the github folder

**Comment by exoscoriae** [comment]
added
