### ISSUE TITLE
Echelon (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#288]
has watermark undergogs.cjb.net
scan was converted to text and sometimes the font or size changes

**Comment by SmilingSpectre** [comment]
Docs uploaded. They are not PC... but then our version is not too. (LOAD at the start of the manual betrays it). Otherwise, it's mostly identical by content.

**Comment by SmilingSpectre** [comment]
Found better quality maps. Uploaded.

**Comment by TimberlAndRE-de** [comment]
merged map images to one map file and
created an issue for the map (#1271) to be added

**Comment by TimberlAndRE-de** [comment]
created pdf from the manual pictures and uploaded it to the github folder

**Comment by TimberlAndRE-de** [comment]
found 

- [ ] manual (MS-DOS version - current is for C64 / C128)

added to the github folder

**Comment by exoscoriae** [comment]
replaced
