### ISSUE TITLE
Hired Guns (1993)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2884]
I found better scans of

- [x] Copy Protection Codes
- [x] Countdown to Graveyard
- [x] The Luyten System

I also found 

- [x] Reference Card
- [x] Game Instructions

The Game Instructions are currently set as the manual but i also found a game manual. See #2885 

All added to the Github folder.

**Comment by TimberlAndRE-de** [comment]
and

- [ ] Reference card
- [ ] Warranty card

added to the github folder

**Comment by exoscoriae** [comment]
added\replaced
