### ISSUE TITLE
Lands of Lore - The Throne of Chaos (1993)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2889]
I found

- [x] Cover
- [x] Back cover
- [x] Disc

for the US Version of the game. The current images are for the UK version and the front cover is for the german version.

Added to the github folder.

**Comment by exoscoriae** [comment]
I went ahead and made the change, but I don't like it. This is clearly a CD release scan. For games that had original big box versions, those are *always* the preferred scans. I will see what I can find.

**Comment by Eulisker** [comment]
You mean because of the cd sticker? Mobygames has good Scans of the floppy box. 


https://www.mobygames.com/game/lands-of-lore-the-throne-of-chaos/cover-art
