### ISSUE TITLE
Manhunter 2 - San Francisco (1989)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2899]
I found a better scan of the

- [x] Reference Card

Added to the github folder.

**Comment by TimberlAndRE-de** [comment]
@Eulisker the reference card is for Manhunter 1 New York
I found the correct 

- [ ] Quick reference card (DOS, Amiga, Atari ST, Mac, AppleII)

and

- [ ] Sierra 10th anniversary catalog (included with the boxed game)

added to the github folder

**Comment by exoscoriae** [comment]
added
