### ISSUE TITLE
Stargunner (1996)

### ISSUE THREAD

**Issue by TheKins** [exoscoriae/eXoDOS#2903]
This game suffers from bizarre speed issues under the current dosbox.conf settings, where FMVs run too fast and the game itself develops brief bursts of superspeed every few seconds.

These can be fixed by changing the "cycles" option in dosbox.conf from the current "50000" to "30000". This could potentially be lowered further (the 2014 3D Realms Anthology release sets it to "12000"), but 30000 feels like a good value to avoid the speed bug while also maintaining fast load times and non-chunky real-time effects like the Apogee logo sequence and Star Wars-style  text crawls.

**Comment by Python-Exoproject** [comment]
I didnt really notice it on my system, but using 30k didnt hurt anything on my system either. Your call @exoscoriae. I did notice however that there is a detail setting in the game for shrapnel that is not at the highest setting so we can def increase that.

**Comment by exoscoriae** [comment]
This is already fixed in the WIP repository but using univbe

**Comment by Python-Exoproject** [comment]
Ok, but the shrapnel detail is still on medium

**Comment by exoscoriae** [comment]
changed to high
