### ISSUE TITLE
Roland Garros 97 (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2906]
It looks like the French version had CD Audio and the English version did not. We are currently using the French version in the collection. 

@SmilingSpectre and myself have both separately created a hybrid of the English version with the French CD Audio and when installed this hybrid works. Spectre has uploaded his version to his sync folder.

**Comment by exoscoriae** [comment]
replaced cd. does anything need to be changed in the game options?

**Comment by exoscoriae** [comment]
the game doesn't appear to behave correctly using this hybrid image

**Comment by Python-Exoproject** [comment]
Looks good to me, I assume it was a fresh install from Spectres image? With the CD Audio I dont think the sound choices are relevant anymore. If you remove them dont forget to take of the relevant playlists in LB.

**Comment by exoscoriae** [comment]
removed choices and playlist entries.
