### ISSUE TITLE
Spiritual Warfare (1993)

### ISSUE THREAD

**Issue by TheKins** [exoscoriae/eXoDOS#2915]
Since there does not seem to be a cracked version out there (the Steam release [seems to have a larger EXE and a EXE.BAK](https://steamdb.info/depot/624551/), is it cracked?), it'd probably be a good idea in the meantime to link to the password list document in the Launchbox entry's Additional Apps section.

**Comment by SmilingSpectre** [comment]
Funny enough, TDC version _is_ cracked, exactly the same way (.ex_ is original file, .exe is bigger), so maybe they taken this release. :)

Anyway, cracked .exe in TDC is this one: 
[SPIRIT.ZIP](https://github.com/exoscoriae/eXoDOS/files/6485560/SPIRIT.ZIP)

**Comment by exoscoriae** [comment]
cracked
