### ISSUE TITLE
Adventure in Serenia (1982)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2916]
discord user TacoAdventure wrote:

_"I fired up "Adventure in Serenia" and picked the 1984 PCJr option (which is actually called Wizard and the Princess) and is recommended in the screen that comes up. I don't have the ability to save as it tells me the disk isn't formatted for saving the game. I ended up playing the Apple II version in ScummVM because I couldn't get the eXo version to save properly. (A note, the 1982 does seem to save correctly, it is just the 1984 version that isn't working)."_

Smiling Spectre solved it:
_"You need two disks for the Wizard and the Princess. Actually, copying current image (WIZPCJR.IMG) will do. I named this disk "SAVE.IMG". Now you need 
1. Change the command in the RUN.BAT to the @boot WIZPCJR.IMG SAVE.IMG
2. FORMAT DISK inside the game.
That's all. Now the second disk works like the save one.
I formatted it already, so maybe you want this (see attached file)
You don't need to swap, as I realized. Somehow DOSBox recognizes second disk as B.
So you have all needed procedure in hand. Try it! :)"_

(see github folder for file)

**Comment by exoscoriae** [comment]
nice work @SmilingSpectre
