### ISSUE TITLE
Corncob Deluxe (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2919]
@SmilingSpectre wrote
Our version of Corncob Deluxe seems is shareware one. I have no idea what exactly is different in registered version (it's mostly identical, but no nag screen at the end, and most exes are different). Still, I recommend to update it. GOD/Archive has floppy with this version

added to the github folder

**Comment by Python-Exoproject** [comment]
Just beat me to writing this one up @TimberlAndRE-de :-)

I also note that the new registered version is version 3.42 and our current shareware version is 3.40

**Comment by exoscoriae** [comment]
set to DAUM w/ direct3d. 

updated to disk image provided by spectre
