### ISSUE TITLE
Corncob 3-D The Other Worlds Campaign (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2920]
When I loaded this one up I noticed that the default control is Joystick and Music is set to off. To fix, start the game and select the relevant options before exiting again.

**Comment by Python-Exoproject** [comment]
Seems that to remove the flicker on the plane during the intro we need to switch to Daum and use the usual output=Direct3d

**Comment by exoscoriae** [comment]
thanks. all good finds.
