### ISSUE TITLE
Kart Race (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#2922]
The current version in eXoDOS is in Korean (with some English text).

I found a full English version. 
This version must be installed under win 3.1 but works on DOS.

Added to the github folder GitHub\eXoDOS\Bugs

**Comment by exoscoriae** [comment]
renamed files to Kart Race (1996)
replaced game with new image

**Comment by Python-Exoproject** [comment]
The sound cuts out. I found this is caused by the sound card being setup on the wrong IRQ. Run sound.exe to re-setup the games sound config.

**Comment by exoscoriae** [comment]
good catch
