### ISSUE TITLE
MT-32 Revision 0 corrections

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2925]
There has been some updates to https://en.wikipedia.org/wiki/List_of_MT-32-compatible_computer_games which results in some minor changes on our end:

Change mt32.romdir=.\mt32 to mt32.romdir=.\mt32\rev0 :
1. F-117A Nighthawk Stealth Fighter 2.0 (1991)
2. Leisure Suit Larry 6 - Shape Up or Slip Out (1993)
3. Monkey Island 2 - LeChuck's Revenge (1991)
4. Serf City - Life is Feudal (1994)
5. Stunts (1990)
6. Wing Commander (1990)

Change mt32.romdir=.\mt32\rev0 to mt32.romdir=.\mt32 :
1. King's Quest I - Quest for the Crown VGA (1990)
2. King's Quest IV - The Perils of Rosella (1988)
3. Leisure Suit Larry 2 - Goes looking for Love in Several Wrong Places (1988)
4. Rise of the Dragon (1990)

**Comment by exoscoriae** [comment]
all games modified

**Comment by Burrito78** [comment]
> There has been some updates to https://en.wikipedia.org/wiki/List_of_MT-32-compatible_computer_games

List got deleted on Wikipedia, a copy exists here:
https://www.vogonswiki.com/index.php/List_of_MT-32-compatible_computer_games
