### ISSUE TITLE
Frontier - First Encounters (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2928]
Just noticed that the game isnt patched to v1.06 and is currently 1.05. Extract these files into the game folder to patch.
[FIRSTENC.zip](https://github.com/exoscoriae/eXoDOS/files/6523208/FIRSTENC.zip)

**Comment by exoscoriae** [comment]
just extract them?

detail settings in the game have a "super high" setting. But it sems to be related to the commander's save file. I can't figure out how to do *anything* in that game other than shoot my laser and get a $6k fine for doing it. Couldn't validate the patch actually worked just by extracting the files.

**Comment by Python-Exoproject** [comment]
All good, I confirmed patch is installed and working. The graphics settings need to be done each time a user starts a new game as far as I know
