### ISSUE TITLE
Lands of Lore - Guardians of Destiny (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2929]
It seems the 3dfx version was patched to version 1.30 but the non3dfx version is still v1.06. A copy of the patch files is in the lolg3d folder (ll2-130e.exe)

**Comment by exoscoriae** [comment]
it gives error 
eut0008: Internal Error 'table.c(183)'

when trying to apply the patch

looks like Jemy has been through this:
https://www.rpgwatch.com/forums/showthread.php?t=10298

**Comment by exoscoriae** [comment]
both 3dfx and non 3dfx are running 1.30 now
