### ISSUE TITLE
Leisure Suit Larry 6 - Shape Up or Slip Out (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2930]
Found this patch file, your call on if to implement:

[Leisure Suit Larry VI Floppy (LS6PAT).zip](https://github.com/exoscoriae/eXoDOS/files/6523406/Leisure.Suit.Larry.VI.Floppy.LS6PAT.zip)

**Comment by exoscoriae** [comment]
this appears to be for the floppy version. As we have the CD version, I would lean towards avoiding.
