### ISSUE TITLE
Sid Meier's Civilization (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2934]
Discovered not cracked. After playing the game for a number of turns it pops up asking you to select the prerequisite techs required to research a specified tech. If answered wrong it destroys all your built units.

**Comment by TimberlAndRE-de** [comment]
@Python-Exoproject 
did you try the included manual to solve the copy protection? did it at least work so the game is playable or didn't it fit the answers?

**Comment by Python-Exoproject** [comment]
Oh I'm sure that would have worked but I would like to keep it simple for her and find a crack.

**Comment by exoscoriae** [comment]
cracked
