### ISSUE TITLE
Quest for Glory I - So You Want to be a Hero (1989)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2938]
I found the

- [x] manual

The current manual is for the original Version "Hero's Quest". Since it is named Quest for Glory 1 in eXoDOS i suggest setting this as the manual and keeping the other as an extra.

Added to the github folder.

**Comment by exoscoriae** [comment]
added this manual as an alternate. original naming\cover takes precedence. It is simply named that way in the front end to keep the series together.
