### ISSUE TITLE
Quest for Glory I - So You Want to be a Hero (1989)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2939]
I found

- [x] Reference Card
- [x] Famous Adventurers Correspondence School 

The current documents are for the original Version "Hero's Quest". I suggest adding these and keeping the others as extras.

Added to the github folder.

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found a 

- [ ] Hint Book

This one is for Hero's Quest but apart from the name i am not aware of any differences. So it should be good. The currently set Hint Book is for the VGA Remake and should be put there.

**Comment by exoscoriae** [comment]
added. moved old one to proper game
