### ISSUE TITLE
Magic Candle 2, The - The Four and Forty (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2940]
I have located a patch for the game that adds mouse support.

[Magic Candle 2 - mouse.zip](https://github.com/exoscoriae/eXoDOS/files/6528071/Magic.Candle.2.-.mouse.zip)

**Comment by exoscoriae** [comment]
lol. that's not a patch. it's an entire game archive!

added files.

**Comment by Python-Exoproject** [comment]
Not sure if its an issue, but during testing ive noticed that MT32 only plays during the initial logo and not during the intro (after you select "new" and start the game) like the soundblaster does. If you dont think this is an issue feel free to re-close

**Comment by exoscoriae** [comment]
unfortunately we have seen this multiple other times in other games.

The solution is always either than the game lacks the music files for that part of the game (as in it was released that way) OR the game archive we have is missing that file.

as I installed it from a floppy dump, I am inclined to believe we have all files that should be included with that release.

Testing shows the same behavior in the 1.0 release. I've reached out to RS to see if he has any idea.s

**Comment by exoscoriae** [comment]
fixed

**Comment by Python-Exoproject** [comment]
Sorry to bounce this one back again but 3 things of possible note:

1. You have included and used ECE v4459, however you have also added to eXoDOS ECE v4460 for a different reason. I suggest removing 4459 and switching this game to also use 4460?

2. The MT32 has gone from cutting off to never ending. This may not be fixable but I thought I would mention that the SB music plays during the intro and stops when gameplay starts, the MT32 now works in the intro but keeps going during gameplay as well

3. Given the above its probably worth reducing the MT32 volume as its very distracting during gameplay. I suggest starting with "mt32.output.gain=50" in the [midi] section and possibly even reducing from there a bit more.

**Comment by exoscoriae** [comment]
switched to 4460.
Lowered the volume.
Looking into solutions on the music.
