### ISSUE TITLE
Menzoberranzan (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2942]
Found a patch that fixes a few bugs.
[Menzoberranzan - Patchv11.zip](https://github.com/exoscoriae/eXoDOS/files/6528160/Menzoberranzan.-.Patchv11.zip)

**Comment by exoscoriae** [comment]
ok... however typically patching is only done for good cause.

are these known issues in the current build within dosbox? Some patches fix "bugs" with specific hardware, so they are totally unnecessary in the build.

a nice go forward goal for patches would be to notate why they need to be applied, or what they specifically address.

Looking over the included readme, it appears the issues do not happen in all cases. 

I went ahead and applied this patch. Seems like it can't hurt. I just don't want to go down the rabbit hole of applying every patch that people find, regardless of it they actually *need* to be patched

**Comment by Python-Exoproject** [comment]
I didnt notate the things fixed here as it was already in the readme, but I can do so in future. These changes looked to me like game errors that needed patching like in Ravenloft, like crashes caused by giving an item to someone for example.
