### ISSUE TITLE
Pacific Strike (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2943]
Found a patch that fixes a few bugs

[Pacific Strike update patch.zip](https://github.com/exoscoriae/eXoDOS/files/6528220/Pacific.Strike.update.patch.zip)

**Comment by exoscoriae** [comment]
patched

**Comment by Python-Exoproject** [comment]
Patch is all good. However I have noticed that somehow the patch file from the Freddy Pharkas issue has been left in the !dos folder for Pacific Strike and can be removed.

When testing I realised that there are some graphics settings we havnt turned on. Go into flight (instant action will do) and press alt-o to enter options where you can change the default difficulty from Ace to something easier (selections are at bottom of the page) and we can turn on water and sky textures. Not sure about the sky textures as they look like they may make it very hard to see enemy aircraft, your call. To save the changes select save at the bottom of the page.

**Comment by exoscoriae** [comment]
water texture was on already for me?

I turned on Sky and "show weapons"
