### ISSUE TITLE
Police Quest 3 - The Kindred (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2944]
This patch to fix issues with the Pentagram part of the game if using keyboard is in the EGA version folder but not the main PQ3 folder which has the VGA version.

[Police Quest 3 Pentagram patch.ZIP](https://github.com/exoscoriae/eXoDOS/files/6528226/Police.Quest.3.Pentagram.patch.ZIP)

**Comment by exoscoriae** [comment]
patched
