### ISSUE TITLE
Raptor - Call of the Shadows (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2945]
Found two bug fix patches for Raptor. Our version is v1.0, so need to update to 1.1 then 1.2

[Raptor Call of the Shadows 1.1 patch.zip](https://github.com/exoscoriae/eXoDOS/files/6528303/Raptor.Call.of.the.Shadows.1.1.patch.zip)
[Raptor Call of the Shadows 1.2 patch.zip](https://github.com/exoscoriae/eXoDOS/files/6528304/Raptor.Call.of.the.Shadows.1.2.patch.zip)

**Comment by exoscoriae** [comment]
patched

**Comment by Python-Exoproject** [comment]
We now have two copies of the zip file, "Raptor - Call of the Shadows (1994).zip" and "Raptor -  Call of the Shadows (1994).zip" of different sizes. Difference seems to be one has a CD image in it

**Comment by exoscoriae** [comment]
fixed. thank you
