### ISSUE TITLE
Space Quest V - The Next Mutation (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2946]
It seems only some of the 1.03 patch files are present in the game folder. Here is the full patch:

[Space Quest 5 Patch v1.03.ZIP](https://github.com/exoscoriae/eXoDOS/files/6528362/Space.Quest.5.Patch.v1.03.ZIP)

**Comment by exoscoriae** [comment]
added missing patches
