### ISSUE TITLE
Stonekeep (1995)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2953]
I found

- [x] Quick Reference Guide 
- [x] Hintbook

Added to the github folder.

**Comment by exoscoriae** [comment]
nothing in the github folder....

**Comment by Eulisker** [comment]
Both should be there now.

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found the 

- [ ] novel

![image](https://user-images.githubusercontent.com/81642149/128244441-c374acbd-12a6-4f4e-a728-7ada500a4a6d.png)
Yeah right! :)

Added to the github folder.

**Comment by exoscoriae** [comment]
this novel is pretty rough. entire sections are impossible to read because the words go off the page. And for some reason the cover is cut in half?

It doesn't seem like a worthy addition.
