### ISSUE TITLE
Wasteland (1988)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2962]
I found a better scan of the

- [ ] Paragraph book

The old one looks bad and it is 60mb for 28 pages which is just silly.

Added to the github folder.

**Comment by exoscoriae** [comment]
existing seems a lot cleaner?

**Comment by Eulisker** [comment]
I found a

- [ ] Hintbook Ad

Added to the github folder.

**Comment by exoscoriae** [comment]
added
