### ISSUE TITLE
Whale's Voyage (1993)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2963]
I found

- [x] Hints

Added to the github folder.

**Comment by exoscoriae** [comment]
added, along with notepad

**Comment by Eulisker** [comment]
The notepad is from midwinter. It was mislabeled on mocagh and has been removed since then. I thought I deleted it in the GitHub folder but maybe I can’t delete anything there.

**Comment by exoscoriae** [comment]
removed
