### ISSUE TITLE
Sierra GUS drivers

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2966]
Here are a bunch of GUS drivers if you wish to implement:

[Freddy Pharkas (GUSDRV).zip](https://github.com/exoscoriae/eXoDOS/files/6539917/Freddy.Pharkas.GUSDRV.zip)
[Quest for Glory 4 (GUSDRV).zip](https://github.com/exoscoriae/eXoDOS/files/6539924/Quest.for.Glory.4.GUSDRV.zip)
[Leisure Suit Larry 6 CD (GUSDRV).zip](https://github.com/exoscoriae/eXoDOS/files/6539925/Leisure.Suit.Larry.6.CD.GUSDRV.zip)
[Freddy Pharkas (GUSDRV).zip](https://github.com/exoscoriae/eXoDOS/files/6539926/Freddy.Pharkas.GUSDRV.zip)
[Hoyle Classic (GUSDRV).zip](https://github.com/exoscoriae/eXoDOS/files/6539927/Hoyle.Classic.GUSDRV.zip)
[Island of Dr Brain (GUSDRV).zip](https://github.com/exoscoriae/eXoDOS/files/6539928/Island.of.Dr.Brain.GUSDRV.zip)
[Laura Bow 2 Dagger of Amon Ra (GUSDRV).zip](https://github.com/exoscoriae/eXoDOS/files/6539929/Laura.Bow.2.Dagger.of.Amon.Ra.GUSDRV.zip)
[Peppers Adventures in Time (GUSDRV).zip](https://github.com/exoscoriae/eXoDOS/files/6539930/Peppers.Adventures.in.Time.GUSDRV.zip)
[Police Quest 1 VGA (GUSDRV).zip](https://github.com/exoscoriae/eXoDOS/files/6539931/Police.Quest.1.VGA.GUSDRV.zip)
[Slater and Charlie (GUSDRV).zip](https://github.com/exoscoriae/eXoDOS/files/6539932/Slater.and.Charlie.GUSDRV.zip)
[Space Quest 5 (GUSDRV).zip](https://github.com/exoscoriae/eXoDOS/files/6539933/Space.Quest.5.GUSDRV.zip)

EcoQuest 2 has the files but the driver isnt setup as an option.

I realise you dont usually add GUS but as these drivers are only found in these patch files I figured id upload them

**Comment by exoscoriae** [comment]
opting to ignore these for now as they appear to just push general midi through the GUS. It is muffled compared to the same output through the SC-55, which is pure GM.
