### ISSUE TITLE
Freddy Pharkas Frontier Pharmacist (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2967]
I could be wrong but I dont think you used the CD - Speech portion of this patch:

[Freddy Pharkas - Sound Fixes.zip](https://github.com/exoscoriae/eXoDOS/files/6540369/Freddy.Pharkas.-.Sound.Fixes.zip)

**Comment by exoscoriae** [comment]
patched resource.aud

modified cg files to point to it.
