### ISSUE TITLE
Wizardry I - Proving Grounds of the Mad Overlord (1981)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2970]
I found

- [x] Briefing Materials

and also better versions of

- [x] Plotting Aid
- [x] Reference Card
- [x] Spells Reference Card

The spells reference is 2 different documents in the current version but it is just two sides of the same card.

Finally i found

- [x] Map Set
- [x] Wizisystem Hintbook
- [x] Wizisystem Maps

The Wizisystem Hintbook is a newer version of the Hintbook in the current version and contains the solution for the first three games. The Maps are seperate in this version. All 3 documents should be added to Wizardry 1-3

All added to the github folder.

**Comment by exoscoriae** [comment]
added
