### ISSUE TITLE
Monkey Island 2 - LeChuck's Revenge (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2974]
Not sure if this was added:

[Monkey Island 2 Floppy - Sound driver to mix MT-32 & SB.zip](https://github.com/exoscoriae/eXoDOS/files/6546688/Monkey.Island.2.Floppy.-.Sound.driver.to.mix.MT-32.SB.zip)

**Comment by exoscoriae** [comment]
if you look in existing mt32 folder for this game, you will see this patch was previously applied.
