### ISSUE TITLE
Even More Incredible Machine, The (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2976]
I dont think this sound fix was installed:

[The Even More Incredible Machine - Sound driver to mix MT-32 & SB.zip](https://github.com/exoscoriae/eXoDOS/files/6547076/The.Even.More.Incredible.Machine.-.Sound.driver.to.mix.MT-32.SB.zip)

**Comment by exoscoriae** [comment]
as we are running the CD version, this can not be applied without creating a rip of the game.
