### ISSUE TITLE
X-COM - Terror from the Deep (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2977]
We used this path on Enemy Unknown but somehow missed Terror From the Deep. Currently when you select MT32 it actually falls back to SoundBlaster. Using patch makes a significant difference by allowing MT32.

[XCOM - Terror From the Deep v1.4 - MT-32 fix.zip](https://github.com/exoscoriae/eXoDOS/files/6547225/XCOM.-.Terror.From.the.Deep.v1.4.-.MT-32.fix.zip)

**Comment by exoscoriae** [comment]
patched
