### ISSUE TITLE
Wizardry IV - The Return of Werdna (1986)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2979]
I found

- [x] Hint Envelope
- [x] Mordor Charge Card
- [x] Mordor Charge List (Copy Protection)
- [x] Note for New Players
- [x] Reference Card
- [x] Title Page Note
- [x] Tournament Registration Card

The Mordor Charge Card was a card used for discount on merchandise for the game as far as i can tell. It was part of every game.
If you beat the game you could fill out the Tournament Registration Card and get faboulus prizes.

All added to the github folder.

**Comment by exoscoriae** [comment]
added
