### ISSUE TITLE
Wizardry VII - Crusaders of the Dark Savant (1992)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2984]
I found

- [ ] Map
- [x] Cluebook

The map is a photograph but looks much nicer then the current scan, the cluebook is the same scan, slighlty different and much smaller. Again this one is from mocagh.org so i think this is the original and the other one is a copy from somewhere else.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced clue book

interestingly, the maps are different. The jpg actually has locations labeled not mentioned on the pdf copy.
