### ISSUE TITLE
Disney's Aladdin (1994)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2985]
I scanned the 

- [x] PC Manual Addendum

Added to the github folder.

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I made another one of these pictures of the box for the european version. I had made one for Hellcat Ace #3764 a while back. You called it "Images of Original Box & Content.

Added to the github folder.

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found

- [ ] Copy Protection Addendum

Added to the github folder.
