### ISSUE TITLE
Epidemic! (1983)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#299]
seems typed-down from the original manual

**Comment by bigjim161** [comment]
I found:

- a scanned manual -it's an earlier version (1982) without "PLAYER AID CARD, APPLE VERSION" paragraph at the end of the manual
- two extra Remedies and Regions map of better quality (the currents ones are blurry)

Added to the github folder

**Comment by exoscoriae** [comment]
replaced
