### ISSUE TITLE
Defcon 5 (1995)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#2991]
I found the 

- [x] manual

Added to the github folder.

Currently the game shows the manual for Defcon 5 (1987). I think this will resolve itself once you put a manual for the 1995 game in?

**Comment by exoscoriae** [comment]
no file in the github currently

**Comment by Eulisker** [comment]
It should be in the github folder now.

**Comment by exoscoriae** [comment]
added
