### ISSUE TITLE
Kronolog - The Nazi Paradox (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#2997]
Discord user haxman noted and I confirmed that current 20,000 cycles is too fast. I used 10,000 and it seemed ok.

I also note that there are two versions of the game selectable from the launch bat, Nazi Paradox and Red Hell. Might it be worth a user note in the launch bat informing what the difference is?

**Comment by exoscoriae** [comment]
note added to the game for the different release.

changed cycles
