### ISSUE TITLE
Laura Bow 1 - The Colonel's Bequest (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#2998]
found

- [ ] Poster for magnifier glass
- [ ] magnifier glass
- [ ] notebook
- [ ] pencil

added to the github folder

proof pic:
![grafik](https://user-images.githubusercontent.com/67441153/120765514-946da500-c519-11eb-8a09-3c3649e5bbb8.png)

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found a better version of the 

- [ ] Hintbook

and made an interactive version

- [ ] Hintbook Interactive

The old hintbook can be deleted.

Added to the github folder.
