### ISSUE TITLE
Multiple titles running too fast

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3000]
Discord user Scanno noted that Roadwar 2000 and Roadwar Europe are running too fast. I reviewed them and a number of other Composite CGA titles we have. Changes below are recommended due to either play or sound issues with current cycles setting.

Beneath Apple Manor - Cycles=200
Battle of Antietam - Cycles=200
Below the Root - Cycles=200
Adventures of Buckaroo Banzai Across the Eighth Dimension, The - Cycles=200
Gertrude's Secrets - Cycles=200
Gertrude's Puzzles - Cycles=200
Gettysburg - The Turning Point - Cycles=500
Knight's of the Desert - The North African Campaign of 1941-43 - Cycles=200
Night Stalker - Cycles=200
Roadwar 2000 - Cycles=200
Roadwar Europa - Cycles=200
Spy Hunter - Cycles=200

**Comment by kcgen** [comment]
Adding @HW-Scanno

**Comment by exoscoriae** [comment]
changes made.
