### ISSUE TITLE
Fragile Allegiance (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3005]
Scanno pointed out this game doesnt actually utilise the MT32 or SoundCanvass options we have setup. I know there are a few like this in the collection, but I cant remember if we are removing the choices and taking them off the playlist when we discover them.

**Comment by kcgen** [comment]
Adding @HW-Scanno

**Comment by exoscoriae** [comment]
removed from playlists.

removed launch options and extraneous files
