### ISSUE TITLE
Ultima V - Warriors of Destiny (1988)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3016]
I found a higher quality 

- [x] Map

Thanks to discord user remowilliams for scanning.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I found a better looking scan of 

- [ ] Avatar Adventures

It is currently in Ultima 4-6 but there are 30 pages in the back about Ultima 7 - The Black Gate and Ultima Underworld. Maybe it should be added to these 2 games also?

Added to the github folder.

**Comment by exoscoriae** [comment]
I see no file in the github for this

**Comment by Eulisker** [comment]
The Book should be there now.

**Comment by exoscoriae** [comment]
same issue as the other one. This is lower quality than what we currently have.

There is bleed through, spine shadows, and multiple pages are not scanned straight
