### ISSUE TITLE
Batman Forever - The Arcade Game (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3019]
Scanno found that our CD image is corrupt. You can see it in Track 7 around 1:50 min mark as the audio skips and stops. Ive tried the copy on olgames.ru which had the same issue and have now passed over to @SmilingSpectre to see if he has better luck.

**Comment by SmilingSpectre** [comment]
Uploaded.

**Comment by kcgen** [comment]
Adding @HW-Scanno

**Comment by exoscoriae** [comment]
switched image and swotched to ECE. vanilla doesn't recognize the correct cd drive image being loaded
