### ISSUE TITLE
Transport Tycoon (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3027]
Scanno discovered that when we had set the dosbox conf to sbpro1 to allow dual opl2 stereo sound we had forgotten to run the games installer and select the sbpro driver. This was resulting in muted or no sound fx for all sound choices. Here is a zip with the updated files to put in the folder of \eXoDOS\Transpor

[TransportTycoonSound.zip](https://github.com/exoscoriae/eXoDOS/files/6632427/TransportTycoonSound.zip)

**Comment by exoscoriae** [comment]
files replaced
