### ISSUE TITLE
Transport Tycoon Deluxe (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3028]
After #3027 I decided to check Transport Tycoon Deluxe to see if the same issue was present there. It looks like we did the same thing, updated the conf but not the games install config. Here are the files for \eXoDOS\TranTDLX\TTDLX

[TransportDeluxeSound.zip](https://github.com/exoscoriae/eXoDOS/files/6632523/TransportDeluxeSound.zip)

**Comment by exoscoriae** [comment]
files replaced

**Comment by Python-Exoproject** [comment]
Discovered there are Scenarios that come with the CD. They are found on the CD as .ss0 files I believe, according to https://www.tt-forums.net/viewtopic.php?t=51698 and https://www.tt-forums.net/viewtopic.php?t=40327

My problem is Ive tried putting them in the games root folder, creating a subfolder called "scenario", and one called "scenarios". The game refuses to see the scenarios in all three methods. I also tried reading directly from the CD but when you select "Play Scenario" the D: drive is not a choice despite the CD being mounted there.

Bit stumped at this time of the morning on this one, maybe you will have better luck?

**Comment by SmilingSpectre** [comment]
Check the manual. ;)

![image](https://user-images.githubusercontent.com/24454178/128742300-3ddaf077-cb3f-458b-a09d-10a093380c9a.png)

And indeed.

![image](https://user-images.githubusercontent.com/24454178/128742241-5f6d8817-bc42-4ac7-b347-ee6765d860de.png)

**Comment by SmilingSpectre** [comment]
Fun fact: they are scenarios too, it seems.

![image](https://user-images.githubusercontent.com/24454178/128748207-d9f6e365-ee12-4824-a535-4bbdf516069f.png)

Clusterville:

![image](https://user-images.githubusercontent.com/24454178/128748298-479a8738-9e6b-4689-8a8a-e43ed2672cb9.png)

**Comment by SmilingSpectre** [comment]
Silly me! It's selected by the picture under scenario buttons!

![image](https://user-images.githubusercontent.com/24454178/128749283-1215f32d-4ce4-4103-be92-9bcf2212ed72.png)

![image](https://user-images.githubusercontent.com/24454178/128749319-df71b6d9-d109-4683-8604-ad8be922aa99.png)

**Comment by Python-Exoproject** [comment]
Thanks @SmilingSpectre, guess reading the manual can help sometimes :-) Looks like the "Play Scenario" button is only to load scenarios the user themselves has created in the "Create Scenario" section.
