### ISSUE TITLE
Terra Nova - Strike Force Centauri (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3029]
Scanno discovered that the current cycles=max is way to fast and suggested 90,000. Tested and confirmed

**Comment by exoscoriae** [comment]
changed to 90k

**Comment by exoscoriae** [comment]
patched
copied MOVIE folder over
added floppy demo
added cd demo (ended up getting a clean uninstalled copy of the cd demo, as this one was missing files)
