### ISSUE TITLE
Hi-Octane (1995) 

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3032]
found

- [ ] manual

note from the uploader on archive.org:
_The CD-ROM version of "Hi-Octane" included a digital manual using the "Modern Age Books" format. It was a hypertext format intended for screen display, not print-out. I have converted this to PDF and - for the most part - it works fairly well. However, you will see some idiosyncracies, such as overlong pages and links that do not work. These are artifacts from the conversion process._

added to the github folder

**Comment by exoscoriae** [comment]
added
