### ISSUE TITLE
In Pursuit of Greed (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3034]
eXo noted on [discord](https://discord.com/channels/454359114601201666/467028238687010826/854010963783057408)

```
just got this bug report over at PD

I noticed that there is a problem with In Pursuit of Greed as I was playing through the game. It seems that Part 1 is completely missing. When launching the game, it'll ask what part that you want to play, and choosing Part 1 will launch Part 2 (as does choosing part 2). I tried reinstalling the game using the disc image in your collection, but the disc does not seem to include Part 1 either. My thoughts is that since Part 1 was shareware, they never bothered to put it on the retail disk, assuming that anyone who bought the game already had Part 1, and the remaining two parts would install as an addon. There must be some shareware discs out there with Part 1.
needs to be looked into
```

**Comment by SmilingSpectre** [comment]
Strange enough, we have GREED1.EXE (and GREED.EXE too, as it's the same file) messed. Our GREED.EXE, GREED1.EXE and GREED2.EXE are identical, while shareware version uses GREED.EXE, and full one supposedly copy it into GREED1.EXE. So I replaced them with "good" exe, and viola: everything works.

Here you are.

[GREED1.ZIP](https://github.com/exoscoriae/eXoDOS/files/6651117/GREED1.ZIP)

**Comment by exoscoriae** [comment]
thank you @SmilingSpectre 

fixed
