### ISSUE TITLE
Patriot (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3040]
agathosdaimon noted in discord:

"hi - i notice that the version of Patriot you have in exodos is just 1.00 however there is a patch to make it version 1.10 and also there is the verions 1.10 you could buy outright, and you can find the installer for it online too - version 1.1 improves the game somewhat"

[Patriot_v1.10_1993Three-Sixty_Pacific_Inc._Strategy.zip](https://github.com/exoscoriae/eXoDOS/files/6682430/Patriot_v1.10_1993Three-Sixty_Pacific_Inc._Strategy.zip)
[Patriot_1.0_to_1.1_upgrade_patch_1993Three-Sixty_Pacific_Inc._Strategy_Addon.zip](https://github.com/exoscoriae/eXoDOS/files/6682431/Patriot_1.0_to_1.1_upgrade_patch_1993Three-Sixty_Pacific_Inc._Strategy_Addon.zip)

**Comment by exoscoriae** [comment]
replaced. cd only held the manual and acrobat reader. game size was the same.
