### ISSUE TITLE
Heroes of Might and Magic (1995)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#3042]
krc putted GranMinigun fix to clean music from hissing sound.
Just rename HEROES_1.2_16bit_fixed.EXE to Heroes.exe and replace it.
eXoDOS 5.1 has v1.0 but it is ok, patch 1.2 just changed heroes.exe, so game will be updated anyway.

[HEROES_1.2_16bit_fixed.zip](https://github.com/exoscoriae/eXoDOS/files/6696660/HEROES_1.2_16bit_fixed.zip)

**Comment by exoscoriae** [comment]
replaced file
