### ISSUE TITLE
Heroes of Might & Magic II (Deluxe Edition) (1998)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#3070]
Title screens for base game & add-on.
![1](https://user-images.githubusercontent.com/66518085/123933217-7406fe00-d992-11eb-8fce-bff038cbca54.png)
![heroes2_000](https://user-images.githubusercontent.com/66518085/123933234-7701ee80-d992-11eb-95ac-0c30c297a413.png)

**Comment by exoscoriae** [comment]
added
