### ISSUE TITLE
Ebola: Civilian Assault (1994)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#3072]
This game is not on the dos master list, not on mobygames and not on the missing list. 
Genre: Action, shooter
Developer: Digital Addiction
Publisher: Dead Good Software 
Released: 1994
Tested on PCEM v17 DOS
Language: English

Info: https://www.ebay.com/itm/303987179471

Added to the Github folder

**Comment by exoscoriae** [comment]
added
