### ISSUE TITLE
Blaster! (1998)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#3074]
Game don't work with openglnb. Game menu is ok, but starting a game results in game kick out. Changing this to overlay fixes this.

**Comment by Python-Exoproject** [comment]
Sorry but I have no issue with playing this game in the current setup, except I did find it needed to be switched to ECE to allow the FMV to be larger.

Guess you will have to test of your setup @exoscoriae and see what happens for you

**Comment by exoscoriae** [comment]
ran fine for me under current setup.

switched to ECE for FMV

**Comment by TimberlAndRE-de** [comment]
I found an english patch for the game (current version is German v1.1) - added to the github folder for eXoDOS bugs.
just overwrite the files with the ones in this zip should work (tested with WIP version)

I'll include the current German version to the GLP then.

**Comment by exoscoriae** [comment]
great find @TimberlAndRE-de 
thank you
