### ISSUE TITLE
Jack Orlando (1997)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#3075]
Game freezes after starting New Game. Solution is changing machine: svga_s3 to vesa_oldvbe. Also ddraw seems only option for correct scaling.

**Comment by Python-Exoproject** [comment]
While I did get the freeze in our current setup, I switched to using ECE to overcome the small window size as per the usual issue with FMV games even though its not FMV and not only did it increase the window size, it also let the game run without freezing while still using svga_s3 and openglnb.

**Comment by exoscoriae** [comment]
switched game to ECE
