### ISSUE TITLE
One Must Fall 2097 (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3078]
It has been requested that we add GUS support to this game.

**Comment by exoscoriae** [comment]
enabled. barely sounds different to me

**Comment by TimberlAndRE-de** [comment]
the network.bat calls OMF directly but to allow the sound options for networking too, it should call the second run.bat I think (although I also don't hear a difference between SB and GUS ;-) )

**Comment by exoscoriae** [comment]
sound and networking options are separate. there are games, like DOOM, that require the same file to be modified twice. This is impossible using our current method. So currently network games default to sound blaster or cd audio generally, and do not have mt32 or sc55 options.
