### ISSUE TITLE
Hoosier City (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3087]
From @SmilingSpectre:

Hoosier City trilogy is a mess for me. It seems, all three parts was randomly installed over "installer" directory (as each part contains installer files for all three) and sometimes over each other (part 2 definitely was installed over part 1, for example). I recommend to extract original installer to the separate directory, and make clean install of the all three parts separately.

Installer files:
README
FCINSTALL.COM
HCINSTALL.COM
OCINSTALL.COM
HC1ARC.EXE
HC2ARC.EXE
HC3ARC.EXE

**Comment by exoscoriae** [comment]
repacked
