### ISSUE TITLE
Mike Read's Computer Pop Quiz (1988)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#3089]
Old-Games.ru has Mike Read's Computer Pop Quiz (1998) This game is on the missing list and on mobygames https://www.mobygames.com/game/mike-reads-computer-pop-quiz
Genre:     Trivia / quiz
Developer:    Elite Systems, MPC Games
Publisher:    Elite Systems
Released:    1988
Language:  English
Tested under svn Daum  dosbox

Added to the Github folder: Game Submission (with its manual)

**Comment by exoscoriae** [comment]
added
