### ISSUE TITLE
F-117A Nighthawk Stealth Fighter 2.0 (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#309]
missing pages 1 2 (between 8/9) and 4-14 (between 10/11)

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found a better version
I copied it to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found another quality upgrade with colored parts
