### ISSUE TITLE
Falcon 3.0 (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3091]
found

- [x] disk exchange coupon
- [x] manual addendum
- [x] registration card
- [x] release notes and communications handbook
- [x] quick reference card
- [x] maps (Israel, Korea-Kashmir, Kurile Islands, Kuwait, Nellis AfB, Panama)

added to the github folder

**Comment by myron0815** [comment]
![PXL_20210729_204659223](https://user-images.githubusercontent.com/1846737/127564074-241fc29b-58d8-4e31-9737-a3e3e0f8717e.jpg)
Anything still needed here?  
Have the original Falcon 3.0 (intl) and AddOn Operation Fighting Tiger (german) right in front of me.
Complete w/ all disks, manual, cards, maps, ...

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] The Art of Kill (book included with the Falcon 3.0 box)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] Strategy Guide Air Combat

**Comment by exoscoriae** [comment]
added
