### ISSUE TITLE
HardBall II (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3092]
@SmilingSpectre found an issue with more than 3 teams showing up despite having files for more. He fixed it with:

[HardBall2Teams.zip](https://github.com/exoscoriae/eXoDOS/files/6836530/HardBall2Teams.zip)

His comment: Replace existing HB2 files with this ones. Restores all "proper" teams, and adds all teams from All Stars Teams add-on.

**Comment by exoscoriae** [comment]
filesd replaced
