### ISSUE TITLE
Biing!: Sex, Intrigue and Scalpels (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#3095]
I found a German version with audio files.
The current version in Exodos has not audio files.

Maybe the current version can be fixed. 

added to the Github folder /bug

**Comment by exoscoriae** [comment]
it worked! =)

**Comment by TimberlAndRE-de** [comment]
the run.bat has an empty DEL entry:

```
:SB16
CONFIG -set "mididevice=default"
del
copy .\sb16\*.*
D:
cls
@B
goto quit
```

I think it's missing the filename: 
`DEL SOUND.CFG`

**Comment by exoscoriae** [comment]
fixed
