### ISSUE TITLE
Wayne Gretzky and the NHLPA All-Stars (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3096]
agathosdaimon noted in [discord](https://discord.com/channels/454359114601201666/467028238687010826/866641990921224194):

`Okay i have found a legit bug this time, - Wayne Gretzky and the NHLPA All stars, there is a scrapbook button in the view/edit stats secton and that is supposed to be an album of images from Wayne Gretzky's career, but if when i click on it the screen goes black some garbled small version of the screen appears and then it crashes`

I can confirm the bug (tested with eXoDOS 5.1)

**Comment by SmilingSpectre** [comment]
machine=vesa_oldvbe

(At least, this one activates univbe driver. S3 isn't.)

**Comment by exoscoriae** [comment]
excellent @SmilingSpectre 

conf changed
