### ISSUE TITLE
Maniac Mansion Enhanced (1988)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3100]
I found

- [ ] Codebook
- [ ] Hintbook Ad
- [ ] Registry Card

Added to the github folder.

Here is a picture of the content of the later release. Looks to be the codebook although this one is out of a budget release according to mocagh. See #1893 for a photo of the earlier release.

![imageview](https://user-images.githubusercontent.com/81642149/126308244-716d186f-314a-457e-bd51-b5d93cb47de7.jpg)
[source](https://ogdb.eu/index.php?section=game&gameid=2921)

E: Looking through ebay it should rather be [this one](https://www.mocagh.org/lucasfilm/maniac-codebook.pdf). But i don't know if you prefer the usable one.

![image](https://user-images.githubusercontent.com/81642149/126310368-27403dd8-ce56-46fe-b152-a919fe0742c4.png)
![image](https://user-images.githubusercontent.com/81642149/126310426-5551a6b2-e0d9-4166-a396-a4ed86b08440.png)

**Comment by exoscoriae** [comment]
our code book we already have is much more legible
replaced QRC
added registration card and hintbook ad

**Comment by Eulisker** [comment]
I scanned (or rather someone scanned for me) the Hintbook and i put it together to a bunch of pdfs:


- [ ] Hintbook
- [ ] Hintbook (revealed)
- [ ] Hintbook Map

The map is in the middle of the book but in the wrong orientation to read it. This was the best way to have it in a readable form and still part of the hintbook.
I played with the contrast and brightness of the revealed version to make it more readable and left the not revealed version as is. If you want to change something there please tell me.

A bunch of notes for the extras of this version:

- The Codebook is Codebook.pdf here and Code Book.pdf in the original version.
- Game Design Notes.pdf is missing an e 
- As said in the other issue; The video of the Demo should probably be moved to the Enhanced Version since it shows the Enhanced Version.
- I think all the Extras in the original version missing from here should be moved here also. That is: the posters and painting and the bulletin board.
