### ISSUE TITLE
Tornado (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3103]
Game: Tornado (1993)
Bug: can't start a mission or test flight, it just returns to the preferences menu with error message System error - sound card not present.
I can hear sound in the menu and it doesn't matter what sound card I chose in the setup on startup - error is always the same...

**Comment by TimberlAndRE-de** [comment]
![unknown](https://user-images.githubusercontent.com/67441153/126366159-0334d65f-68b1-499c-a863-06a8e709f46b.png)

**Comment by SmilingSpectre** [comment]
It's a speed issue.

It works sometimes. But very rarely.

Going 5 000 down, I went to 15 000. 20 000 still fails. 15 000 works always. Or almost always (I ran it trice in row).

**Comment by exoscoriae** [comment]
dropped to 15k for now. Looking into other solutions as well.

**Comment by exoscoriae** [comment]
ok. so, here is what is going on.

The CD image at old-games works fine at 25k cycles.
The CD images we have here does not. It has to be reduced.

When I initially set-up multiplayer for this game, it was on the old image - which explains why everything worked.

My thought is to take the files from the ISO dump and combine them with the audio tracks from the other dump, and see if we can't get both. 

Granted, at this point it is unclear if the game can even use the audio tracks. I have seen nothing in the setup files that suggests they are used in game.

**Comment by exoscoriae** [comment]
created new hybrid image
cleaned up the folder
everything appears to work now
still not sure why audio tracks exist, but maybe they are just "extras"

**Comment by Python-Exoproject** [comment]
Preferences menu needs re-setting up for music and device choices, as per below:

![image](https://user-images.githubusercontent.com/67406191/128535369-2f3f0fd7-6e11-4dda-a19f-d861c1be6394.png)

To get the "Game On" option to show select both Roland and SB sound cards. Im not sure about the "Contour Interval (Feet)" setting so not sure which end of the scale is better.
 
 There may still be an issue though. Whenever I select quickstart nothing launches, though a proper combat mission loads.

**Comment by exoscoriae** [comment]
fixed cycles, settings, and the load for desert storm

**Comment by SmilingSpectre** [comment]
Desert Storm is upgraded Tornado. Must add some new missions/campaign to the base game.

**Comment by Python-Exoproject** [comment]
I understand that, but when you load both games in the collection they seem to both have the Desert Storm missions and splash screen

**Comment by SmilingSpectre** [comment]
*blink*
I just tried v5, and it have cd-audio and no Desert Storm splash for simple Tornado. Someone upgraded it to Desert Storm maybe? %)

**Comment by exoscoriae** [comment]
looking at my files, Tornado is a full 485mb cd image, where as desert storm is only 33mb. So... seems the base game has a LOT more content?

When desert storm starts, it briefly states "integrating desert storm extensions". So does the base game now.

I wonder if when you guys had me patch the base game, it added the extensions.

I am leaning towards only having the base game if it is already upgraded. We don't offer other games with and without their expansions, iirc.
