### ISSUE TITLE
F-19 Stealth Fighter (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#311]
first two pages are boxfront and boxback  last page is an image of the disks (can be deleted from  the manual)
pages 199 - 218 are a technical supplement for atari st & amiga manual
pages 219/220 are keyboard overlays for Atari & Amiga
pages 221-224 are Maps

**Comment by TimberlAndRE-de** [comment]
I deleted the amiga/atari pages and the maps (uploaded as extra) and uploaded the new version

**Comment by exoscoriae** [comment]
replaced

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found a quality upgrade with higher resolution and (red) colored pages
