### ISSUE TITLE
Sensible Golf (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3116]
found

- [ ] manual 

it's the amiga manual but there is no other one - the PC version had this one too but with an additional PC user addendum
proof:
![grafik](https://user-images.githubusercontent.com/67441153/127059556-fc70fc46-e0ba-47f2-bf74-e0bd5154777d.png)
![grafik](https://user-images.githubusercontent.com/67441153/127059586-ee452dea-4599-4d0d-9fa5-aa8cffd94129.png)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
Manual in

- English
- French
- German
- Italian
