### ISSUE TITLE
Abaron (1995) 

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3118]
When it starts it says it found a mouse, the cursor can be seen in the ingame menu 
But the mouse doesn't seem to work
You can switch to Keyboard ("Tastatur") in the menu, then the game is playable, but no mouse support.
CTRL-F10 doesn't work

EDIT:
todo:
- [ ] change of dosbox conf in second comment
- [ ] change of disc image in third comment

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre has figured out that you need 
SERIAL1=serialmouse
in the dosbox conf

confirmed, it works

**Comment by TimberlAndRE-de** [comment]
@exoscoriae
I have the original big box version
the current disc is ISO and from a later budget re-release but it includes the same game version (v1.5)
I made a bin/cue from my original disc, so if you want, you could replace it in eXoDOS (added to the github)
(no change for the game but maybe for preservation reasons? otherwise, just delete my upload ;-) )

**Comment by exoscoriae** [comment]
replaced cd image
made conf changes
