### ISSUE TITLE
Oh No! More Lemmings

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3119]
The manual for Lemmings and Oh No! More Lemmings is the same.

You can see the datadisk mentioned in the copyrights at the beginning and there are loading instructions for the disk inside.

![image](https://user-images.githubusercontent.com/81642149/127776699-13e9f86b-b959-4c5f-b77d-0ad700f186ea.png)

I also have the european version of both games and the manual is the same. You can just copy the Lemmings manual and set it for Oh No! More Lemmings.

E: Pictures of the contents can be found [here](https://ogdb.eu/index.php?section=game&gameid=5540) and [here](https://ogdb.eu/index.php?section=game&gameid=5541).

**Comment by exoscoriae** [comment]
copied
