### ISSUE TITLE
Reader Rabbit 1 (1991) & Reader Rabbit 2 (1991) Roland MT32

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3129]
These games both have Roland MT32 capability. We need the original install media to enable it. Exo has located copies for purchase and will setup MT32 when they have arrived. 

Once added they will also need to be added to the MT32 Playlist

**Comment by exoscoriae** [comment]
ordered original copies

**Comment by exoscoriae** [comment]
enabled roland in both games. added to playlist
