### ISSUE TITLE
Quake (1996)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3139]
I scanned the

- [x] Readme Text

The european box had the readme text printed in different languages in the box. Maybe worth it to add?

Added to the github folder.

**Comment by exoscoriae** [comment]
added as an extra

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] unauthorized prima guide for the shareware levels
- [ ] unauthorized map guide
- [ ] official strategy guide

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre found

- [ ] Strategy Guide Unauthorized (Prima)

**Comment by exoscoriae** [comment]
added
