### ISSUE TITLE
Tricky Quiky Games: Die Suche nach den verschollenen Seiten II (1995)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3142]
I scanned the 

- [ ] manual

It is german only. There is a [version](https://www.mobygames.com/game/dos/tricky-quiky-games-die-suche-nach-den-verschollenen-seiten-ii/cover-art/gameCoverId,592843/) with some french in it but i doubt there is anything in english.

Added to the github folder.

**Comment by exoscoriae** [comment]
added
