### ISSUE TITLE
Falcon 3.0 (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#315]
has watermark replacementdocs

**Comment by TimberlAndRE-de** [comment]
current manual is digital and incomplete (254 pages), maybe from a later digital re-release or GOG ?
I found

- [ ] manual (scanned, 356 pages - not a perfect scan but it's at least complete)

added to the github folder

**Comment by exoscoriae** [comment]
replaced. strange quality.
