### ISSUE TITLE
AV8B Harrier Assault (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3162]
Just found out that #2786 Super-VGA Harrier is just a resolution upgrade of this game so I thought I would check it for similar issues.

According to https://www.mobygames.com/game/av-8b-harrier-assault/cover-art/gameCoverId,230715/ it has Roland, and when testing I had the same issue regarding speed as I did with Super-VGA Harrier (https://github.com/exoscoriae/eXoDOS/issues/2786#issuecomment-897709699)

**Comment by exoscoriae** [comment]
set to 10k cycles.

to set roland it needs to be installed from floppies.
added roland and sb options.
added to playlist

**Comment by exoscoriae** [comment]
I hear no music in the game...l ever.
I also got into the plane and heard nothing. come to find out engine noise defaults to off
I am unable to find a way to turn it on and save that option.
I tried turning it on and the doing a clean exit
I tried turning it on, then going to options and saving my control preferences.
no luck so far

**Comment by exoscoriae** [comment]
added a launch note
