### ISSUE TITLE
Gunship (1986)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3163]
Found out this game has better sound when in Tandy mode, especially during the intro. Current vanilla dosbox craps out for the game in Tandy mode so we need to switch to ECE. 

For the EGA mode the games uses that weird DAC method for the intro music so vanilla dosbox doesnt handle that well either. ECE seems to be ok with it. 

Not sure if you prefer to switch completely to the Tandy option or keep both and offer a choice, there is no graphical difference. If you keep both, the other conf settings dont need to change so there is no need for an alt conf, just launch with -machine tandy.

Possibly need user note that if Tandy chosen then select option 3 from games graphics choice menu. Things like this make me look forward to dosbox forks that use autotype. We can then have the launch choose the graphics option from the in game graphics menu for the user.

**Comment by exoscoriae** [comment]
tandy graphics were heavily corrupted after the intro.
switching to our default ece fixed this.

added note to use tandy version and switched it over.
