### ISSUE TITLE
Crime Wave (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3174]
found

- [x] manual (us version en, current is the european US Gold release manual en,fr,de,it)

added to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by TimberlAndRE-de** [comment]
The manual was replaced again in #4452 because of the better quality of the EU manual.
But for the copy protection of the game the US manual is needed.

wysiwyg found a better quality version of the 

- [ ] US manual

**Comment by exoscoriae** [comment]
replaced
