### ISSUE TITLE
J.R.R. Tolkien's The Lord of the Rings Vol 1 (1990)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3192]
When choosing to run the CD version from the .BAT launcher first, and then choosing the "Demo" option from the main menu of the game, it gives an error saying "Install Demo and make sure that CD is in drive to watch video". :) 

When choosing to start a new game it plays the videos just fine.

Smiling Spectre has identified it needs the "Demo installation. (It drops two files in root - LORDDEMO.BAT and LORD.CFG). After installation, Demo works indeed."

**Comment by exoscoriae** [comment]
fixed
