### ISSUE TITLE
Sci-Fi Channel Trivia Game (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#3220]
This game is not on the "Win3x Archived and Found",  not on the missing list, and not on mobygames.
Genre:    Trivia
Developer:  Byron Preiss Multimedia Company
Publisher:    Byron Preiss Multimedia Company
Released:    1996
Language: English

Added to the Github folder

**Comment by exoscoriae** [comment]
win3x? this is in the wrong project then

**Comment by bigjim161** [comment]
Sorry, I re-submit this issue in the win3x github
