### ISSUE TITLE
UEFA Champions League 1996-97 (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3222]
agathosdaimon has reported:

I have been playing UEFA Champions League 96-97 and it is definitely the case that the game is running too fast on the max cycles setting that its by default set to. I tried Auto but that gives the same result. If i put the cycles at around 100,000  that seems to bring the game into moving at a more realistic and playable speed. The game though will here and there just suddenly speed up though, - i dont know what this games speed is tied to

**Comment by exoscoriae** [comment]
modified. however we prob need 2 tests for any speed changes due to different machines and different expectations.
