### ISSUE TITLE
NFL Pro League Football (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3227]
agathosdaimon says:

"NFL Pro League Football (1995) is missing sound - there is an option to turn on sound in game, but attempting to do so bring ups a message saying that a soundblaster compatible card is needed"

@SmilingSpectre confirmed and between the two of them came up with a solution of using 12,000 cycles

**Comment by exoscoriae** [comment]
changed cycles
