### ISSUE TITLE
A320 Airbus (both versions)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3233]
agathosdaimon reports:

A320 Airbus - the runway graphics are all messed up. I changed the core to dynamic for A320 Airbus and the in flight 3d graphics are back to normal so definitely change it to that for a future update

**Comment by exoscoriae** [comment]
per ripsaw:
See this thread: Airbus A320 from Thalion (Grafik Glitch in VectorGFX))
Dynamic core depends on the host processors for flag behavior of divide instructions, and it's evidently not the same for all -- it's the dyn_x86 core's price for performance, and also why Chasm: The Rift crashes for some but not all unless it is patched.

The better solution for A320 is to use normal core in an SVN build where the expected flag behavior is emulated, and ECE should have the fix as well.
