### ISSUE TITLE
Dragon's Lair III - The Curse of Mordread (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3235]
mgoddard reported:

I am not able to proceed past the first few screens where it asks to insert Disk 2. I can't find the key combination to perform this task and cannot find it referenced. The standard CTRL+F4 doesn't seem to work. At install time choosing to install to "c" also gives the same error of not being able to find disk 2.
Since these games are brutal, if you type "TIME" during the title animation, then press fire the game will play automatically. Makes it easier to create the issue

Spectre responded with:

Seems, our version is broken. Twice. It haven't disk identifier files, and it totally missing DL3DISK5.DAT. @eXo take the correct one in TDC.
Also, we are missing SENTERJS.EXE, but I am not sure it's necessary. Maybe it is, for playing with joystick.
And there is severe discrepancy between our DISK7, and TDC. And I fear, there it's they are wrong: our file is more or less "random", where TDC is suspiciously regular closer to the end of file.

**Comment by exoscoriae** [comment]
unable to get past the first screen to test...?

made changes though
