### ISSUE TITLE
Street Fighter (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3238]
from agathosdaimon:

hi! I was trying Streetfighter  and there seems to be something wrong with menu - one is supposed to be able to select from each of the four locations at the start to pick who to fight against, but the game just automatically goes to Japan, and failing htat round, and going back to main menu it just does it again 
you can see however from recordings on youtube that you are supposed to be able to select the opponent.

Spectre replied:

Street Fighter requires something below 1000 cycles to work right - otherwise it's too fast. @agathosdaimon even couldn't select stage, as "press fire" works for selection too. 500 cycles maybe?

agathosdaimon:

yes i put it  800 cycles and the menu option is there now - issue fixed!

**Comment by exoscoriae** [comment]
set to 500cycles
