### ISSUE TITLE
Omnicron Conspiracy (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3239]
hungavy said:

huh, interesting. Omicron Conspiracy Game says press enter to start, enter doesn't start the game :smile: Tried both the normal enter and the numpad enter, can't get past this screen.

Spectre responded:

Error confirmed. Solution: get loader. 
[Omnicron_Conspiracy_dosbox_int16_fix.zip](https://github.com/exoscoriae/eXoDOS/files/7136220/Omnicron_Conspiracy_dosbox_int16_fix.zip)

Issue exists in ece, vanilla, staging without fix

**Comment by exoscoriae** [comment]
fixed w/ loader
