### ISSUE TITLE
YAB! Baseball (1992)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3245]
Description incorrectly identifies one of the teams (Toronto Blue Jays) as Toronto Blue Jets. Change to the following:

`YAB Baseball! is a German-made baseball game with a rather simple gameplay, reminiscent of older, arcade-oriented approach to baseball simulations, such as RealSports Baseball. The player is able to control two real MLB (Major League Baseball) teams: the Boston Red Sox and the Toronto Blue Jays, represented by the corresponding colors.
`

**Comment by exoscoriae** [comment]
fixed
