### ISSUE TITLE
Brzdąc (1995)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#3249]
When selecting crayons there's high-pitched noise. Switching to ECE solves the problem. 

Also game's alt name isn't Brzdac. This was only released in Poland and has no alt names. Brzdąc is "little kid", Brzdac makes no sense.

**Comment by SmilingSpectre** [comment]
"Alternate name" field is needed to find the game, if it have other name. "Brzdac" can have no meaning as Polish word - but it have a whole meaning for anyone who cannot type ą. I think, it worth to keep. It's _alternate_ name after all. :)

**Comment by exoscoriae** [comment]
it already had an alternate field with the value of "Brzdąc"

you guys need to check this stuff before you make a ticket
