### ISSUE TITLE
Legacy - Realm of Terror (1993)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#3251]
Game has terrible sound popping noise on SB (while opening doors for ex.).
Here's solution:
https://www.gog.com/forum/the_legacy_realm_of_terror/sound_popping_fix

Please check this thread till the end as there are some changes made regarding this line "mixer SB 200:200"

Here's the file for your convenience.
[resample.zip](https://github.com/exoscoriae/eXoDOS/files/7177220/resample.zip)

**Comment by exoscoriae** [comment]
done. thanks!
