### ISSUE TITLE
3DCube (1994)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3252]
The game is not cracked and interrupts gameplay pausing it to present a scrolling message about registering the software. Game is still playable and continues after the pausing so file under annoyance.

**Comment by exoscoriae** [comment]
@matthew-goddard there is nothing that can be done about this unless someone has the time and expertise to crack it.

**Comment by matthew-goddard** [comment]
@exoscoriae Understood, and especially since it is still playable. Was not sure if you tracked these issues for future potentials. Feel free to close and re-open at a later time if it makes sense.

**Comment by exoscoriae** [comment]
essentially, that is what the "low priority" category is for. Issues we are aware of, but have no current fix for.

**Comment by xmarksthespot81** [comment]
Fixed: 

https://archive.org/details/3dcube-1994-shareware-patch

You are welcome to use my modification.

Cheers!

**Comment by exoscoriae** [comment]
thank you so much @xmarksthespot81 

I have integrated your patch. I am excited by the prospect of future patchs for other games =)
