### ISSUE TITLE
Armored Fist 2

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3253]
agathosdaimon reported issues with crashing. He started a VOGONs thread about it and corresponded with Ripsaw. Link here https://www.vogons.org/viewtopic.php?f=33&t=83578&p=1001011#p1001011

On discord the last comment was:

agathosdaimon — Yesterday at 12:54
okay something that has been brought up by Ripsaw was setting memsize to 31 instead of 63, - i have tried it at 31 and had no crash for an entire mission, using SVN build r4465 and using the program he made that he  suggested: FFClose.com

**Comment by exoscoriae** [comment]
changed memsize to 31
set game to use ece r4460
added ffclose

current cycles are 30k

closing unless something else pops up about this

**Comment by Python-Exoproject** [comment]
Hmmm, looks like this is a rare double miss by us @exoscoriae. The bug report was referring to Armored Fist 2, not Armored Fist 1 which is the game you modified. I then missed this fact during the QA.

Not sure if any of the changes you accidentally made will adversely affect AF1, I dont think they will. But AF2 needs this actioned. 

Additionally the cycles are probably low in AF2. Too high though and the game starts randomly crashing. 100000 seems ok in limited testing.

**Comment by exoscoriae** [comment]
modified armored fist 2 with the above settings and set cycles to 100k.
