### ISSUE TITLE
Ports of Call (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3254]
Seems there has been an issue with this one for awhile:

Jono — 04/04/2019
Ports of Call- runs really slowly when Soundblaster is enabled - for example, at the start when showing the globe, then the map, in the shipyard when showing the elevator, and most importantly when trying to steer out of the port (makes it near impossible).  Choosing no sound 'fixes' the delay in all cases.  Increasing the cycles did not seem to help. I made a note on the spreadsheet, but this one seemed weird enough that I though it was worth mentioning here as well.

At this point you gave it a heman emoji implying it was fixed. Back then we didnt really have the QA setup we have now so I probably never double checked it. Since then we have had:

Daskepeder — 05/11/2020
A quick question. I just insstalled and played Ports of Call. There are two options there with sound cards, but both made all loading in the game horrible. Unplayable I would say. Plays nice and smooth without sound. Is this to be expected?

Flay — 08/08/2021
Ports of Call has got some speed issues: there are 30 second delays when starting a new game and entering your name and such, the elevator sequence when visiting the shipbroker should only take 3-4 seconds instead of a minute, and the action sequences (entering or leaving a port manually, or rescuing survivors) are unplayable

Flay — Yesterday at 02:52
This is still a thing for me (Ports of Call with sound), and I'm running the game from an external HD...anyone else have trouble with unplayable lag on starting a game, or when steering a ship manually?

Smiling Spectre — Yesterday at 03:53
@eXo @Python @Flay problem with Ports of Call confirmed. Starting game is practically impossible when any of two sounds is selected. I taken v2.0 from TDC, and it haven't this problem (we have 2.01). Maybe replace it?

**Comment by exoscoriae** [comment]
fixed
