### ISSUE TITLE
Korean Dungeon Boy (1991)

### ISSUE THREAD

**Issue by TheKins** [exoscoriae/eXoDOS#3271]
The black-and-white Hercules mode shown in the screenshots does not function with the default dosbox.conf, the "machine" setting under [dosbox] has to be explicitly set to "hercules". Without this, you can only use the CGA mode, which appears to be some kind of weird boxy composite thing. A batch file like those used for selecting sound card for many games may need to be implemented.

For reference to how they look:
Hercules Mode (with "hercules" specified, without it's just a black screen):
![cwsgame_000](https://user-images.githubusercontent.com/2977232/133895239-ecc928bd-4322-4006-b6fd-957665a1f511.png)

CGA Mode (with default conf, doesn't work with "hercules" specified):
![cwsgame_001](https://user-images.githubusercontent.com/2977232/133895276-6c72506d-11c6-461f-bc6c-622eeb4c3142.png)

**Comment by exoscoriae** [comment]
added hercules mode launch option

**Comment by Python-Exoproject** [comment]
Staging has done some work on Hercules and presents corrected aspect for Hercules amongst other things. Please use the provided confs and switch to Staging.

I have also added CGA composite user option and Hercules colour choice. Lastly I also added autotype to select the correct graphics mode in game for the user.

[Korean.zip](https://github.com/user-attachments/files/16488178/Korean.zip)

**Comment by exoscoriae** [comment]
done

**Comment by parricc** [comment]
When choosing quit in both the Hercules and CGA menus, DOSBox remains open.
![kdb-hquit](https://github.com/user-attachments/assets/6a7d4809-6142-4ef8-8977-f9c134a992df)

**Comment by exoscoriae** [comment]
@Python-Exoproject it isn't easy, is it? lol

**Comment by exoscoriae** [comment]
fixed by adding a "call run" instead of direct invocation of the run.bat.

this allows it to return to the autosec portion, and run the "exit" command. Otherwise the batch file superceedes the order of commands.
