### ISSUE TITLE
Budō: The Art of Ninja Combat! (1993)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3274]
Tested in eXoDOS release v5.1.
Currently images, include the front image are not appearing in Launchbox due to non matching (I'm assuming). Current images are present in folders but following the naming convention of "Budo_ The Art of Ninja Combat!-01.jpg" but that does not load properly.

Changing the prefix of the image names to "Budo - The Art of Ninja Combat! (1993)-01.jpg" appeared to work and have the front image get loaded. ie replacing the underscore and adding the year had the images load.

**Comment by exoscoriae** [comment]
hmm.. works for me. I can see the front image currently. No change made, as it may have been fixed by an updated launchbox or something else.
