### ISSUE TITLE
Wing Commander IV The Price of Freedom (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3329]
adding start option to enable cheating:

Start the game with "wc4 -chicken" at the command line
⮚ Enters debug mode. You should see the message "Chicken mode: [ON] Boc Boc!" during game start-up.
⮚ Ctrl-W destroys your target.
⮚ Ctrl-Alt-W destroys all enemies on the radar.
⮚ Alt-F displays framerate.

Start the game with "wc4 -mitchell" at the command line
⮚ Get the message "Mitchell don't work here no more. He work for Bazooka Joe now." during game start-up.

Start the game with "wc4 -mitchell2" at the command line
⮚ Get the message "I told you he don't work here no more! You call Bazooka Joe! during game start-up."

Start the game with "wc4 -test" at the command line
⮚ Get the message "Test okay!!!" during game start-up. The game then crashes

In flight, press Alt-O.
⮚ Select invincibility.

**Comment by exoscoriae** [comment]
enabled
