### ISSUE TITLE
Voyager (1989)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3331]
I uploaded Voyager

Genre: Action
Developer: Ocean Software Ltd.
Conversion by: Binary Systems
Publisher: Ocean Software Ltd.
Released: 1989 (The copyright in the PC Reference says 1990)
Language: English, German, French
Works on DOS

The upload includes

- Scans of the box, disk and casette Tape
- Manuals
- The tape as mp3 and wav
- Screenshots
- The disk .img (probably unusable due to copy protection) and raw kryoflux streams
- The cracked game taken from SmillingSpectres TDC Folder

Uploaded to the github folder.

**Comment by Eulisker** [comment]
The game does not seem to be added. At least i can not find it in the WIP folder. The manual is there.

**Comment by exoscoriae** [comment]
it was added. however I haven't uploaded any new games to the syno
