### ISSUE TITLE
Trivial Pursuit - CD-ROM Edition (Europe) (2001)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#3355]
Submitted by @SmilingSpectre
This game is not on the Win3x Archived and Found list,  not on the missing list and not on mobygames. 
This version has improved graphics compared to the original version:
https://www.mobygames.com/game/windows/trivial-pursuit-cd-rom-edition/screenshots
Genre:  Board game/trivia/quiz
Developer: Adrenalin Entertainment
Publisher:  Hasbro Interactive Ltd.
Released:  2001
Language: English
Tested on PCEMv17 Windows 3.11 
![image](https://user-images.githubusercontent.com/67555221/139543780-fca37727-02d3-436c-957e-7190e56d0cac.png)

Added to the github folder

**Comment by exoscoriae** [comment]
this is in the wrong project then. this is eXoDOS. This issue should have been filed under the eXoWin3x project. Please create a new ticket under the proper project and close this one @bigjim161

thank you

**Comment by bigjim161** [comment]
I created a new ticket under the eXoWin3x project
