### ISSUE TITLE
Amazing Art Corner (1998)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#3356]
Submitted by @SmilingSpectre
This game is not on the Win3x Archived and Found list, not on the missing list, and not on mobygames. 
Genre:  Educational
Developer: Ohio Distinctive Software
Publisher:  Ohio Distinctive Software
Released:  1998
Language: English
Tested on PCEMv17 Windows 3.11

Added to the github folder

**Comment by exoscoriae** [comment]
this is in the wrong project then. this is eXoDOS. This issue should have been filed under the eXoWin3x project. Please create a new ticket under the proper project and close this one @bigjim161

thank you

**Comment by bigjim161** [comment]
I created a new ticket under the eXoWin3x project
