### ISSUE TITLE
Front Page Sports Baseball '94 (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#336]
page 1 (probably coverpage) is missing
scan is b/w  images are hard to see

**Comment by SmilingSpectre** [comment]
Got a great copy from abandonware-france. That is heavily damaged with "watermarks" added to every image. Uploaded.

**Comment by TimberlAndRE-de** [comment]
thx, copied to the github directory
and changed "bad" label to "ok but..."

**Comment by exoscoriae** [comment]
added
