### ISSUE TITLE
[optimization] use common install.bat

### ISSUE THREAD

**Issue by ToxicFrog** [exoscoriae/eXoDOS#3362]
`install.bat` is the same for every¹ game in eXoDOS, since it's a general purpose setup script with no game-specific code; moving it to a common location and `call`ing it from there, if possible, would both reduce the number of files involved in an eXoDOS install by ~7200, and mean it only needs to updated in a single place when it changes.

¹ `dbotacw2` has a variant `install.bat`, but the only difference is that it lacks the code to apply updates for that title, which is probably an error.

**Comment by Eulisker** [comment]
Not to make you even more grumpy but you should really check the v6 changelog in discord. :)

**Comment by exoscoriae** [comment]
either way, this can't be moved to a common place. 

It relies on the folder it is being run from to know which game to install.
