### ISSUE TITLE
[optimization] pull configurable settings (fullscreen, aspect, etc) into a shared config file

### ISSUE THREAD

**Issue by ToxicFrog** [exoscoriae/eXoDOS#3363]
Updating the defaults is very slow because it has to edit thousands of configuration files. However, dosbox supports loading multiple configuration files, by using the `-conf` flag multiple times. Proposal:
- remove the `fullscreen`, `output`, `aspect`, and `scaler` settings from game-specific configuration files
- add a `defaults.conf` that contains the default values of those settings
- update the installer to write to `defaults.conf` rather than the individual game configs
- update the per-game launcher scripts to load `defaults.conf` in addition to (and before) the game-specific configuration file(s)
The per-game launcher scripts will still write to the game-specific config files, which will override the settings in `defaults.conf`.

**Comment by Eulisker** [comment]
See #3362
