### ISSUE TITLE
Multiple Magnetic Scrolls games

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3364]
[Magnetic Scrolls games.zip](https://github.com/exoscoriae/eXoDOS/files/7487192/Magnetic.Scrolls.games.zip)

I found our magnetic scrolls games were all over the place, some had both the origianl DOS and the hires interpreter versions as choices, some only had the DOS version, other only the hires. Another didnt have the graphics switch on, etc.

I found a site that has all the magnetic scrolls games and a more up to date version of the hires interpreter so Ive gone over all of them and set them up properly. I have an archive with it all, where would you like it?

There are two things I couldnt solve, one was that the crack included with original DOS "Myth" makes the text scroll right past in the start of the game so you have no idea what happening, and the other is that the hires interpreter version of "Wonderland" should be working with its intro music (its the .snd file), but its not.

Source of the files and hires interpreter: https://msmemorial.if-legends.org/magnetic.php
I chose the 32bit DOS release as it was faster

**Comment by exoscoriae** [comment]
the conf file for PAWN launches Fish!

Fish! (original interp) refused to start, as it couldn't find disk2.
DISK1.PIX and DISK2.PIX were missing from the folder.

I added those back and fixed the pawn conf file.
