### ISSUE TITLE
Oddworld - Abe's Oddysee (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3367]
Read this note in the discord chat:

epoxxy — Yesterday at 05:27
Is there anyone else that have trouble with saving in Oddworld - Abe's Oddysee ? I press "enter" or "X" and it just makes a sound, but no save. To back out of the save-menu, I have to press escape once and then press enter to get out. I've tried vanilla dosbox, ece, svn, svn2 but no luck.
Any idéas?

Smiling Spectre — Yesterday at 17:35
Seems, known bug. Saves doesn't work under dos. https://www.vogons.org/viewtopic.php?t=40563

I tested out in exodos and confirmed the issue for us as well. Its odd that I couldnt find much online about an issue that I thought would have been a big deal so im unsure about what the real problem might be.

**Comment by SmilingSpectre** [comment]
The both versions (win and DOS) uses the same procedures for name-generation, it seems. But for DOS it means non-usable name (as it's always more than 8 characters, and have spaces). Problem is heightened with weird keyboard reaction: it works only sometimes, and delete doesn't work at all. I believe, last bits could be fixed quite easily... but no one did that, it seems.

**Comment by TimberlAndRE-de** [comment]
doesn't seem to break anything, but in case it creates a problem with you DB scripts, this should be fixed:

the ba1 file in the game folder has a blank in the filename before "Abe":
`Oddworld -  Abe's Oddysee (1997).ba1`
should be
`Oddworld - Abe's Oddysee (1997).ba1`

**Comment by exoscoriae** [comment]
some ba1 files have those left over spaces. They don't hurt anything.

**Comment by exoscoriae** [comment]
updated to DOS32/A

Tried it using dosbox-x with LFN enabled. Was hoping LFN would fix the issue. No luck.

**Comment by exoscoriae** [comment]
tried launching it in real DOS. same issue.
Tried real dos 7.0 with lfn support. same issue.

This can be chalked up to an issue with the actual DOS release.

**Comment by exoscoriae** [comment]
there is nothing we can do about this.

**Comment by SmilingSpectre** [comment]
@ripsaw8080 made makeshift fix for me, basing on (working) Spanish version.

Tested it, and while it still generates too long name (and so save not what you see, if you don't edit it) - you _can_ edit the name, and you _can_ save/load the game.

Also, in my setup game has crackling sound in intros, and not exactly right work with stereo (it definitely tries, but I have impression it may do more). Changing SB to "SB2 New" seems makes issue better, but not totally eliminates it. Maybe worth tinkering with other dosboxes and SB settings.

Duplicated the fix here and in github/bugs.
[abefix.zip](https://github.com/user-attachments/files/18013998/abefix.zip)
