### ISSUE TITLE
Alternate Reality - The City (1988)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3369]
I found the 

- [x] The official Adventurers Survival Handbook (Hintbook)

Added to the github folder.

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found

- [ ] IBM PC Reference Card

Added to the github folder.

**Comment by SmilingSpectre** [comment]
I uploaded the greyscale scan of the same. It's now ten times bigger, and takes the whole 5Mb.
Alternate Reality - The City (1988) Reference Card (Greyscale).pdf

**Comment by exoscoriae** [comment]
added specter's version
