### ISSUE TITLE
Master of Orion II - Battle at Antares (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3370]
there's a huge fanpatch for MoOII:
https://moo2mod.com/

current version is 1.50.18.3
latest original game patch was 1.40

it's easy to install, just download the patch zip file, copy the files and folders from inside the "patch" folder to the Master of Orion II installation folder.
After that you can start the Mod-Patch with "ORION150.exe" instead of "ORION2.exe", but the 1.40 still works. So it can be added to a run.bat as another start option.

The Fanpatch brings a lot of bonus:
* Fixes 10 critical crash bugs
* 6 networked multiplayer bugs 
* About 30 interface bugs 
* Over 100 game-rule bugs.
* Play against a random number of opponents
* Play with auto designed ships
* 6th ship design slot
* Greatly improved build queue management
* Unbuy function
* New hotkeys
* Integrated mapgen functionality

Supports English, German, French, Spanish and Italian DOS editions of MOO2. -- Installing the 1.50 patch does not break your current version 1.31 or 1.40 installation. No original files are overwritten.

**Comment by exoscoriae** [comment]
added. shifted multiplayer to use this build as well.
