### ISSUE TITLE
Gamma Force in Pit of a Thousand Screams (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3383]
wysiwyg found

- [x] manual

it's not a real manual but a mix of key reference card and registration card but there is no other manual
(the rest of the extras can be found here: #3382 )

proof:
![grafik](https://user-images.githubusercontent.com/67441153/141076597-70253c69-7be0-4fec-aba9-687b1e2f30b6.png)
![grafik](https://user-images.githubusercontent.com/67441153/141076578-754d37a9-55ee-4eb5-a359-0e55fae9f598.png)
![grafik](https://user-images.githubusercontent.com/67441153/141076610-d400ed29-45f6-4a12-a024-44297a9638c4.png)

**Comment by exoscoriae** [comment]
added
