### ISSUE TITLE
Super Winnie the Pooh (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3393]
From discord @matthew-goddard  reported:

Super Winnie the Pooh (1996) has a PC speaker sounds that just plays constantly through the level and the demo from the menu.

@SmilingSpectre then discovered that the game can give stereo music by running SETPOOH.EXE and set first two settings to 486 DX2 and SB 240H then select the last item (that is Exit + Save).

I added: Dont know if it was originally supposed to have speaker sound fx but for now we can set pcspeaker=false to remove the beep.

**Comment by exoscoriae** [comment]
fixed
