### ISSUE TITLE
GLP: changing the way to recognize language pack versions in the eXoDOS base package

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3394]
**the current way it works:**

the eXoDOS launch.bat checks if the folder 
`eXo\eXoDOS\!dos\!German\%GameDir%`
exists.
It then calls the "Game Name (YEAR).bat" in this folder to switch to the German batch files

this works for all Games in the language pack as long as the %GameDir% has the same name as in the original eXoDOS base package ("lemm2" for Lemmings 2 - The Tribes for example)

**but** if we only add Extras to a game that is already in eXoDOS we have the %GameDir% folder (because there are the extras files) but not the "Game Name (YEAR).bat". So the eXoDOS batch offerst the "Press G for German" option and then tries to call a batch file that doesn't exist.

<del>**solution A:**
We provide a "Game Name (YEAR).bat" for every game we only add extras too, which gives the user the info that there is no German version and sends him back to the english version.</del>

**solution B:**
eXo changes the way the language pack version is recognized:
Instead of checking for the folder 
`eXo\eXoDOS\!dos\!German\%GameDir%`
the eXoDOS launch.bat should check for the file:
`eXo\eXoDOS\!dos\!German\%GameDir%\Game Name (YEAR).bat`

_Solution B is preferred I (Timber) think, it also makes sure, the game name batch file for the language pack exists befor offering the option for the user_

_eXo says he can set it up to generally search for a "*).bat" file so that alternate game titles in the language pack will work._

**Comment by exoscoriae** [comment]
I have modified the script to search for
`eXo\eXoDOS\!dos\!German\%GameDir%\Game Name (YEAR).bat`

**Comment by exoscoriae** [comment]
nevermind, I solved the issue easily. Now it searches for any bat file that ends with ").bat"

**Comment by exoscoriae** [comment]
this means more changes must be made.

When it goes to launch currently, it attempts to launch %GameName%.bat, which is the original english name only. This will need to be modified to be able to call an alternate file as well, such as "*).bat"

I Will begin testing solutions.

**Comment by exoscoriae** [comment]
everything now works. will resync the WIP copy soon with these new files.
