### ISSUE TITLE
E.S.S. (1989)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3397]
I scanned

- [x] Front
- [x] Back
- [x] Disk

of the german version.

**Comment by exoscoriae** [comment]
media upgrade project should denote games that have the actual install media (floppy, cd, etc) missing or in need of a better version.

This appears to be documentation scans? German at that?

So should this be changed to the GLP & Manuals tag?
@Eulisker @TimberlAndRE-de

**Comment by exoscoriae** [comment]
added
