### ISSUE TITLE
Dungeon Master (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3398]
while adding the German version I found out you can start Dungeon Master with parameters to avoid the questions on startup

To start Dungeon Master in VGA with Mouse Support and Sound Blaster you can use:
`@dm VGA IBMIO FIRES -pm -sb -*e`

So you could save the eXoDOS user from the annoying questions at the beginning 
(or, if desired, add a run.bat to choose between EGA and VGA)

(source: http://dmweb.free.fr/?q=node/206)

**Comment by TimberlAndRE-de** [comment]
Seems EGA / VGA isn't working (for me?) ... but at least the parameters lead to a direct launch of the game without the questions on startup

**Comment by exoscoriae** [comment]
thank you

**Comment by Python-Exoproject** [comment]
The conf autoexec section still has the original launch command of "dm" before the new launch command and therefore the above change is currently skipped.

**Comment by exoscoriae** [comment]
good catch
