### ISSUE TITLE
Bloodwych (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3400]
Flay from discord reported:

There is an old game breaking bug in Bloodwych (never happened when I played it on Amiga 500 back in the day, apparently it's only in DOS). They call it the "welcome back bug" (it's also present in the GOG and Steam versions): http://crpgaddict.blogspot.com/2012/08/bloodwych-dead-ends.html
https://www.gog.com/forum/bloodwych/bloodwych_welcome_back_fix

Someone made a program(actually two files, CWSDPMI.EXE and WBFIX.EXE) to fix a savegame, which you can download here as a zip file: https://community.pcgamingwiki.com/files/file/946-bloodwych-welcome-back-fix/

When I tried it, there was an error message (wrong Windows version) but the savegame DID get fixed.
Maybe someone can find a way to make this easier to fix. Or just include the program in the collection along with instructions?
If you want to reproduce it, I've made a backup of my savegame (savegame slot 1) in it's broken state:
[BWYSAVE.zip](https://github.com/exoscoriae/eXoDOS/files/7560902/BWYSAVE.zip)
 I'm standing in front of the "Welcome back" sign(you can click on it on the wall to read the sign). Behind me is a staircase to the lower level.

This site has maps for the entire game: http://www.alanchapman.org/bloodwych/maps.html
The staircase is on the "Main Tower 2" map, labeled "D" on the right side: http://www.alanchapman.org/bloodwych/maps/main_2.png

If you descend the stairs, there is just this small corridor(http://www.alanchapman.org/bloodwych/maps/main_1.png) with 2 trap tiles which turn you around for confusion(I've placed a few items on the floor so you don't get confused when you get turned by 180 degrees).

At the end of the corridor, there should be a staircase up, which is missing due to the bug and it's just a dead end, and you can't progress anymore (if you see a staircase, you made a mistake with the trap tiles, and you're back at the staircase leading up to the "welcome back" sign). To fix the savegame, you place the two programs (wbfix.exe, cwsdpmi.exe) into the game folder, and in dosbox use the savegame's name as a command parameter "WBFIX BWYSAVE.1".

**Comment by exoscoriae** [comment]
created patching script for the modification of save files.

**Comment by Python-Exoproject** [comment]
The note on what the savegame fix is is located under the menu option to select it. Might this note be better on the initial screen so users know why they might need to use the fix option?

**Comment by exoscoriae** [comment]
moved note.
