### ISSUE TITLE
Breakline (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3401]
mgoddard reported:

Loud crackling found in Breakline (1994). Tested on both 5.1 and WIP and both exhibit the same issue. I don't see any audio options in game to to to adjust to fix.

**Comment by SmilingSpectre** [comment]
SB16 have the problem. SB2 or GUS isn't.

I got the sound with GUS=true (and sblaster=none), but maybe it can be more fine-tuned? Or not worth it?

**Comment by exoscoriae** [comment]
nice work @SmilingSpectre 
fixed

**Comment by exoscoriae** [comment]
added
