### ISSUE TITLE
Leisure Suit Larry 5 - Passionate Patti Does a Little Undercover Work (1991)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3402]
Leisure Suit Larry 5 - Passionate Patti Does a Little Undercover Work (1991) is missing the added "Playspy" document that was included in the game. Scan can be found here: http://larrylaffer.net/exxxtras/larry-game-materials/manuals-hint-books/playspy

**Comment by Eulisker** [comment]
Playspy is set as the manual.
