### ISSUE TITLE
Baby Jo in - Going Home (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3408]
Found a new game to add to MT32 list. 

After setting up conf for MT32 and switching to ECE, launch with "Baby 3" instead of "Baby 2". 
Add to LB MT32 list

**Comment by exoscoriae** [comment]
added

**Comment by Python-Exoproject** [comment]
Currently the run.bat middevice is set to fluidsynth when it should be MT32

Looks like this either changed somewhere after the ticket was closed or you used the wrong midi device and I missed it when QAing.

**Comment by exoscoriae** [comment]
fixed
