### ISSUE TITLE
Dungeon Master II - The Legend of Skullkeep (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3409]
Two issues for this one.

First, sound fx are not working. To fix goto the cd, open the patch folder, run "install" to install the patch. Once the files are copied over run "setup" and select the sb16 for fx and midi with correct irq if needed to change. FX now work, yay!

Second, this game can do GM. Switch to ECE, setup the conf\run.bat for sb and fluidsynth, run "setup". In the midi menu select "Ensoniq Soundscape" with port 330. If you try "test" it wont play music, but also wont fail. Run the game and you will have Midi. Add to LB SoundCanvas list.

**Comment by exoscoriae** [comment]
fixed and added to list
