### ISSUE TITLE
KGB (1992) & KGB Conspiracy (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3412]
I believe our copy of these two games are identical. From what I understand there was an original release called KGB and a later CD release with Donald Sutherland clips called Conspiracy, which might explain why we have both entries. However both of these games in our collection are CD based and if you open the CD image they are identical despite one being an ISO and the other being an IMG.

We need to remove one of these to get rid of the duplicate and then if its decided to keep both versions we will need to locate a copy of the actual original non CD game, KGB. We will then also need to decide if its worth its own entry or if we should move it to a launch option under Conspiracy and change Conspiracy LB title to something like KGB (Conspiracy).

@SmilingSpectre you able to help with locating the original?

**Comment by Eulisker** [comment]
The disk images for KGB are here. 

https://archive.org/details/001536-Kgb

**Comment by exoscoriae** [comment]
reverted to floppy image. setup for both sb and mt-32.

changed cover in LB to floppy version. replaced disk image as well.
