### ISSUE TITLE
Omar Sharif on Bridge (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3413]
Another game for MT32 setup.

To select MT32 you need to reinstall the game, or you can use this cfg file
[INTRPLAY.zip](https://github.com/exoscoriae/eXoDOS/files/7574636/INTRPLAY.zip)

Other than that, setup the usual run.bat sound choices and add to LB MT32 list

**Comment by exoscoriae** [comment]
just using that cfg file does not work. the installation also places an mt32 driver file in the sound folder that is missing.

reinstalled and got it working
