### ISSUE TITLE
Aces of the Deep (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3414]
I discovered that this game is currently setup so that the SoundCanvas option uses fluidsynth as it should, but the resource.cfg is using the MT32 driver. This needs to be changed to the Genmidi.drv

Also the game does support MT32 so that option can be added and the game put on the LB MT32 list

**Comment by exoscoriae** [comment]
added to mt32. fixed genmidi driver. nice catches
