### ISSUE TITLE
Archer Maclean's Pool (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3416]
Found this game can do MT32. As its a dosbox X game you will need to copy in exception.bat from another X MT32 game like Golden Eagle, add the midi lines to the conf, setup the user options with a run.bat, and add it to the LB MT32 list.

To enable the game option edit cdgo.bat and change "M1" to "M2"

**Comment by exoscoriae** [comment]
added
