### ISSUE TITLE
Dawn Patrol (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3420]
Two things with this game.

First, we have two entries, Dawn Patrol (1994) & Dawn Patrol Head to Head (1995). I believe that Head to Head is just an update patch to the base game and that we can remove the base game entry.

Second, the game can do MT32. Switch to ECE, add lines to conf, setup user choice run.bat, add to LB MT32 list. To set the game up for MT32 delete Patrol.cfg and the game will go through the options again on next start

**Comment by exoscoriae** [comment]
keeping both versions. was two different releases from what I can tell.

added mt32 to both
