### ISSUE TITLE
Lords of the Realm II (1998)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3431]
This one might be a matter of personal preference as it doesnt seem to make a major difference in game, but currently the game is running at max cycles. Being a Sierra game that always makes me nervous but also, when you are in game the flags wave and cow heads bob way to fast. I tried cycles 50000 and it was better, but no idea if this might have other side effects further in the game.

**Comment by exoscoriae** [comment]
went with 75,000. Which is my goto for 1997/1998 games. Cow heads seemed normal at this speed.
