### ISSUE TITLE
Star Wars Chess (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3432]
Another game for MT32

Switch to ECE, add lines to the conf, setup user run.bat options, add to MT32 list.

To get the game running MT32 copy the two files in this zip [SWarsChs.zip](https://github.com/exoscoriae/eXoDOS/files/7576401/SWarsChs.zip) over the current ones.

There is also another option we can offer the user, a choice of chess board. Currently its set to "throneroom" as default, but if you run the game with "swc spaceboard" you can access the other option.

**Comment by exoscoriae** [comment]
added sound options and chess board choice
