### ISSUE TITLE
Time Riders in American History (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3433]
Another MT32 game.

Switch to ECE, add the conf lines, setup user run.bat choice, add to LB MT32 list.

This game autodetects so will run MT32 as soon as the above is done. The current settings are theoretically SB with mididevice=default, but it sounds terrible so im not sold on the fact this game has a proper SB option.

**Comment by exoscoriae** [comment]
added mt32

not sure about sb either, but leaving it for now

**Comment by exoscoriae** [comment]
fixed sb\adlib sounds by adding mpu401=none to run.bat
