### ISSUE TITLE
Trump Castle II (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3434]
Another MT32 game.

Switch to ECE, add lines to conf, setup run.bat user options, add to LB MT32 list

This is another autodetect game, mididevice=mt32 for mt32 and mididevice=default for SB

**Comment by exoscoriae** [comment]
added

**Comment by exoscoriae** [comment]
went and added "mpu401=none" to this game and it made a HUGE difference for the sb\adlib sounds
