### ISSUE TITLE
Fallen Heroes (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3438]
This game crashes when you try to start actual gameplay with MT32 selected. Ive read this is an issue, so might be best to remove MT32 user option and take it off the LB MT32 list

**Comment by exoscoriae** [comment]
it runs like ass (during the intro at least) no matter what sound I select.

midi stutters on the main menu as well.

Seems to run ok with soundblaster in 0.74.  Do you not get issues in ECE?

**Comment by exoscoriae** [comment]
removing all alternate sound options. 

set to run in 0.74

this game really sucks
