### ISSUE TITLE
Alien Olympics (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3439]
The midi output by the game as MT32 is reportedly GM in reality. I listened with mididevice=fluidsynth and it does sound better.

We can either switch the MT32 option over to SoundCanvas and update both LB lists, or set the game up with a SoundCanvas option in addition to the MT32 option using the same game config folder but setting fluidsynth.

I lean towards the later option as then we are then covering if the information is right or wrong, the user has the final say on which they prefer.

**Comment by exoscoriae** [comment]
add sc-55
