### ISSUE TITLE
Gemfire (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#344]
very blurry
it's for the NES version of the game!

**Comment by SmilingSpectre** [comment]
Found SNES and SEGA. Found also low-quality scan of map poster. No PC in sight. :| Uploaded everything found - at least they are higher quality.

**Comment by TimberlAndRE-de** [comment]
added map to the github folder (#1346 )

**Comment by exoscoriae** [comment]
@TimberlAndRE-de 
I only saw an SNES manual in the folder....? deleted and rejected. Saw no map
