### ISSUE TITLE
Fatal Encounter (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3441]
This game is on both the LB MT32 and SC lists, however the option is disabled in run.bat

Im not sure if it was disabled as you got no sound, or if it was because it sounds wrong and is probably broken. If its the former, to get the midi outptut you need to set mpu401=uart. If its the later then we also need to remove it from the LB lists

**Comment by exoscoriae** [comment]
fixed launching.
