### ISSUE TITLE
Theme Park (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3445]
Theme Park was removed from MT32 due to a crash after the intro, but it still needs to be taken off the LB MT32 list

**Comment by exoscoriae** [comment]
done

**Comment by Python-Exoproject** [comment]
Noticed the game has a copy of ece in the zip archive. Doesnt look like its used so should be good to remove

**Comment by exoscoriae** [comment]
thanks!
