### ISSUE TITLE
Delta V (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3447]
This game does MT32 and Sound Canvas.

Switch to ECE, add lines to conf, setup user run.bat options, add to both LB MT32 and SC lists.

To get game running either sound mode extract [DELTAV.zip](https://github.com/exoscoriae/eXoDOS/files/7581108/DELTAV.zip) into the \Deltav_c\ folder and point the MT32 option to launch deltavmt.bat and the SC option to launch deltavsc.bat

**Comment by exoscoriae** [comment]
added mt32, sc55, and gus. added to all 3 playlists.

didn't use the included zip file, as I set them up manually.

**Comment by Python-Exoproject** [comment]
Not sure why I didnt notice this the first time but the sound is not balanced between fx and music. To fix globally for all sound options set:

[sblaster]
sbmixer=false

[autoexec]
mixer sb 60

Also, the cycles are set to max and are way too fast. Try something around between 15 to 20k?

**Comment by exoscoriae** [comment]
thanks!
