### ISSUE TITLE
Leisure Suit Larry 1 - Land of the Lounge Lizards VGA (1991)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3471]
The manual currently set is [from this budget release](https://www.mocagh.org/loadpage.php?getgame=lslvgauk). According to mocagh and several eBay auctions there is no specific manual for Larry 1. Only the standard Sierra Game Manual [(see here)](https://www.mocagh.org/loadpage.php?getgame=lslvga)
Here is some ebay pictures of the contents.

![image](https://user-images.githubusercontent.com/81642149/144575023-9ba48c6f-41d0-4407-9c4b-64f208deef87.png)
![image](https://user-images.githubusercontent.com/81642149/144575051-aaeacffb-7757-4592-98fb-d165c1a6a073.png)
![image](https://user-images.githubusercontent.com/81642149/144575076-013e6d0b-d672-40fc-a587-e6a6445e901f.png)

I would set the Sierra Game Manual as the manual and delete the other one.

**Comment by exoscoriae** [comment]
denied. budget release manual is still better than a generic manual that is just for any sierra game
