### ISSUE TITLE
Millionaire - The Stock Market Simulation (1982)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3480]
wysiwyg found

- [x] manual  (b/w scan, should be added but issue has to stay open until we find a better scan)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] manual (quality improvement and additional pages - and DOS instructions)

added to the github folder

**Comment by exoscoriae** [comment]
added
