### ISSUE TITLE
Fantasy Manager - The Computer Game (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3485]
mr_bogus scanned the

- [ ] box and disk

"The Game is not added yet, mr_bogus sent the disks to Boohyaka since they weren't readable without kryoflux"

added to the github folder

**Comment by exoscoriae** [comment]
closing issue as it is already open under 
https://github.com/exoscoriae/eXoDOS/issues/3484
