### ISSUE TITLE
Gobliiins 1 (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#351]
needs to be cropped

**Comment by TimberlAndRE-de** [comment]
discord user ArkhangelAzrael found a better copy (higher resolution, clean)

https://discordapp.com/channels/454359114601201666/492422228281917470/775621981722247199

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I scanned the

- [ ] Copy protection

Added to the github folder.
