### ISSUE TITLE
Goblins 3 (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3511]
In the current WIP:

The floppy version was added. It seems to be installed in the subfolder `/f/...` . The directory is also mounted as drive `e:`.

The CD version seems to be installed in the `/COKTEL/...` subfolder, which is also mounted as drive `c:`.

But in the new `run.bat` the drive `e:` is called for both floppy and CD version... so it's always the floppy version that is called

The part for the CD version needs to be changed to:
```
:C
cd COKTEL
cls
@call GOB3
goto quit
```

**Comment by exoscoriae** [comment]
great catch. fixed
