### ISSUE TITLE
Gunship 2000 (CD-ROM Edition) (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#361]
first two pages are boxfront and back
last page contains image of the disks
Keyboard overlay on page 137

**Comment by Eulisker** [comment]
I cut all the extra stuff out of the 

- [ ] manual

Thanks to Discord user remowilliams for scanning.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
