### ISSUE TITLE
Charly the Clown (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#3615]
We have a cracked shareware version (v1.30).

I found a registered version (v1.30) here: 
https://www.old-games.ru/game/download/4294.html

added to the github "bugs" folder

**Comment by exoscoriae** [comment]
upgraded

**Comment by Python-Exoproject** [comment]
The game launch and exit in dosbox.conf are #'shd out, also the game is too fast at 25k cycles. I used 10k and seemed better

**Comment by exoscoriae** [comment]
dropped cycles and made changes
