### ISSUE TITLE
Hacker (1985)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#363]
not for the DOS/IBM PC Platform

**Comment by SmilingSpectre** [comment]
Game purposely haven't any manual. Except loading instructions and box itself. I uploaded box covers from Moby - looks quite manual-ish for me.

**Comment by TimberlAndRE-de** [comment]
thx, converted to pdf and uploaded to the github folder

**Comment by exoscoriae** [comment]
i think what we had is more of an actual insert than a box scan. if there is no manual, then that is fine - but this insert is closer. I don't think it is consequential that it doesn't specifically list IBM on the list of platforms
