### ISSUE TITLE
Pinball Illusions (1995)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3646]
Manual in

- English
- German
- French
- Italian

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] manual 

it has more technical information and the right keyboard settings (current one seems to be for amiga version)
still has the four languages

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by exoscoriae** [comment]
added (again) lol
