### ISSUE TITLE
Hammer of the Gods (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#365]
has watermark theunderdogs.org
needs to be cropped
scanned with shadows  some parts on some pages are hardly or not readable

**Comment by TimberlAndRE-de** [comment]
found the original scanned version on [oldgames.sk](https://www.oldgames.sk/en/game/hammer-of-the-gods/download/4853/)
but it's too blurry and not pressed on scanner so many words are not readable...

**Comment by SmilingSpectre** [comment]
Uploaded.

**Comment by TimberlAndRE-de** [comment]
uploaded the manual to the github folder
added issue (#1347) for the extra "unit guide" as quality upgrade

**Comment by exoscoriae** [comment]
replaced
