### ISSUE TITLE
Sensible Soccer - European Champions - 92-93 Edition (1993)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3661]
The manual should be correct (It should be the same as #1153 ([see here](https://www.mobygames.com/game/sensible-soccer-european-champions-9293-edition/cover-art/gameCoverId,642996/))

But the scan with International Sensible Soccer is much better. I uploaded it to the github folder. 

Manual in

- English
- French
- German
- Italian

**Comment by exoscoriae** [comment]
replaced
