### ISSUE TITLE
Family Feud (1987): Error installing when eXoDOS folder is on a network server (Windows)

### ISSUE THREAD

**Issue by stansalvador** [exoscoriae/eXoDOS#3674]
Reproducing:
- Game:  Family Feud (1987)
- Running in Launchbox (1st run to install)
- Windows 11 Home
- The "local" eXoDOS folder is a symbolic link (made with "mklink \D")

When the game is run the first time to install the following error message very briefly appears in the console window before disappearing:
```
'\\Brainiac\Multimedia\games\Dos\eXoDOS\!dos\famifeud'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

All other games that I've tried to run so far have installed and run without issues.

I was able to get the game working by modifying this section of dosbox.conf from:
```
[autoexec]
cd ..
@cd ..
@mount c .\eXoDOS\
c:
cls
@cd famifeud
@menu
exit
```

to (mounting one directory down from the symbolically linked directory):
```
[autoexec]
cd ..
@cd ..
@mount c .\eXoDOS\famifeud
@c:
cls
@cd famifeud
@menu
exit
```

**Comment by SmilingSpectre** [comment]
It's basically wrong, as you eliminated for DOSBox the path "famifeud" altogether (so last '@cd famifeud' do nothing). You can do that successfully sometimes, but usually directory matters. To save initial fuctionality I recommend to make another, same named subdir. (Thus game from eXoDOS\famifeud must be moved to eXoDOS\famifeud\famifeud.)

**Comment by exoscoriae** [comment]
This isn't a big with eXoDOS. Nor would it fix this particular issue for all users who have it.

Ultimately, running on a network drive is not something we support.
