### ISSUE TITLE
Pinball Wizard 2000 (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#37]
Missing CD

**Comment by exoscoriae** [comment]
no response

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found a redump disc image:

https://ia601501.us.archive.org/view_archive.php?archive=/11/items/redump_pc_P/Pinball%20Wizard%202000%20%28Germany%29.7z

**Comment by exoscoriae** [comment]
deadlink.....

**Comment by exoscoriae** [comment]
added CD.
