### ISSUE TITLE
Apache (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3703]
Message from TServo2049 in discord:

The version of Apache (1995) in eXoDOS is a French release. While the menus and HUD are in English, campaign mission briefing text, speech, and the in-game manual are all in French. (Strangely, we also have campaign mission briefing text in Spanish in the archive - I think they come from the PATCH.EXE archive - but no English.) There are English versions out there, of course, but the patch notes make reference to mission crashes being fixed, among other things, so we should make sure we find the newer version. There’s at least a USA, Europe and Europe (Rerelease) in Redump. 

Apache Longbow (Europe) (Rerelease) in the Redump PC Compatible Assembly on Archive.org mostly matches the CD we have in eXo but it’s all in English. It’s the newest EXE, and it has a 1998 date on launch. ( It also seems to have 3DFX support though it may only be for Win95) I’d say switch to that.

**Comment by exoscoriae** [comment]
version replaced

**Comment by exoscoriae** [comment]
done
