### ISSUE TITLE
Worms - Reinforcements (1995)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3709]
Manual in

- English
- French
- German

The manual is the PowerPlus Budget version. We should maybe look for the official manual.

**Comment by TimberlAndRE-de** [comment]
wysiwyg found 

- [ ] manual

it's the manual of the original "Worms" game. "Worms - Reinforcements" is the addon, original "Worms" is required to play it.
There was also a "Worms United" release, combining both ("Worms" and "Worms - Reinforcements")
In LB it's listed as "Worms United", while it's "Worms Reinforcements" in the files ... 
I guess it should be named "Worms United" in the files too

anyway, this manual should be set as manual for "Worms United" and the current (budget release of Worms United) one as an extra manual until we find either the original "Worms - Reinforcements" or the original "Worms United" manual

added to the github folder
