### ISSUE TITLE
Hero Quest (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#371]
has watermark manuels.adandonware-france.org on last page

**Comment by exoscoriae** [comment]
removed

**Comment by Eulisker** [comment]
Manual in

- English
- French

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre found

- [ ] manual (quality upgrade and more pages)

added to the github folder

**Comment by exoscoriae** [comment]
replaced
