### ISSUE TITLE
Winter Supersports 92 (1996)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3714]
The game has a 1996 release date but it should be 1992 like the other versions. There are severatl things backing this up.

- The manual is for Amiga/Atari/C64 and PC. I doubt they would print the PC instructions if the game was to release 4 years later.
- [OGDB](https://ogdb.eu/index.php?section=title&titleid=27927) lists the release year as 1992
- It makes no sense to release a game with 92 in the Title in 96
- There is a review in the german magazine ["Play Time" Issue 8/9 ´92 ](https://www.kultmags.com/mags.php?folder=UGxheSBUaW1lLzE5OTI=)
![winter super 2](https://user-images.githubusercontent.com/81642149/151157741-ff9ca070-02af-4685-9406-b25c429c14a0.png)

- The game is seen in several game listings around the time. This one is from Play Time 7 ´92

![winter super](https://user-images.githubusercontent.com/81642149/151157971-ce82cd29-bb79-4c5e-8083-e9a2318020ec.png)

The 1996 release date comes from a [1996 budget rerelease](https://www.mobygames.com/game/winter-supersports-92/cover-art/gameCoverId,539182/).

**Comment by exoscoriae** [comment]
changed date
