### ISSUE TITLE
Alien (1982)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3738]
Tested on 5.1 and WIP branch.

The game runs however after the introduction it dumps to the command prompt with the message "File not found in 450". When you list the steps line 450 makes reference to "alien.SPC" which is missing from the installed folder. The doc file makes reference to the three files needed and alien.spc is one of them:

PROGRAM NAME: ALIEN.BAS
OTHER FILES NEEDED: **ALIEN.SPC**, A2.SPC, A5.SPC

**Comment by SmilingSpectre** [comment]
Confirmed. We have the version that is Alien v2b [a1] (1982)(Anonymous) [Adventure, Interactive Fiction] for TDC. Here is it
[Alien v2b [a1] (1982)(Anonymous) [Adventure, Interactive Fiction].zip](https://github.com/exoscoriae/eXoDOS/files/8008769/Alien.v2b.a1.1982.Anonymous.Adventure.Interactive.Fiction.zip)
.

**Comment by exoscoriae** [comment]
repaired
