### ISSUE TITLE
Shattered Steel (1996)

### ISSUE THREAD

**Issue by Voron3DD** [exoscoriae/eXoDOS#3743]
Сurrent version has corrupted files. In folder "Shattere\INTRPLAY\SSTEEL\WORLD_2\MISS2\" files "1BOT.DAT" through "9BOT.DAT" are corrupted and have zero size. A similar situation in folders "MISS8" and "MISS11". Because of this, some missions on the second planet cannot be completed. 
Archive.org contains an "redump" image of this game with intact files of correct size. https://archive.org/details/shattered-steel-usa-rerelease.-7z
Correct files can also be found in GOG version. 

Sorry for my English and message format. This is my first activity in this environment.

**Comment by SmilingSpectre** [comment]
eXo, confirmed: installed files for WORLD_2 is zero size for several missions (namely, 2, 8, 11, 13 and 15). and our disk is the same. No other files affected.

**Comment by Voron3DD** [comment]
I hope that these files will be corrected in future updates.

**Comment by exoscoriae** [comment]
This was processed on Nov. 8th, 2023.
