### ISSUE TITLE
 X-COM - Terror from the Deep (1995)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3746]
I found

- [x] Primas Official Strategy Guide

Added to the github folder.

**Comment by exoscoriae** [comment]
added.

for some reason the back cover was the first page. Moved it to the end. reset the initial page view to the first page.

**Comment by Eulisker** [comment]
I found

- [ ] The Ultimate Guide to Alien Destruction
- [ ] The Ultimate Guide to Alien Destruction Addendum

Added to the github folder.

**Comment by exoscoriae** [comment]
added
