### ISSUE TITLE
Populous (1989)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3747]
You can play the Levels in conquest mode (or maybe a new set of levels?) with the new Tilesets. See here:

![unknown](https://user-images.githubusercontent.com/81642149/155201658-ab72eb63-b421-423f-a1c1-cad544d5fccd.png)

If you delete the level0.dat you will play the conquest mode with the new graphics. You could make a new launch option for this.

**Comment by exoscoriae** [comment]
I set all of this up, but I am not seeing any new graphics

**Comment by Eulisker** [comment]
What you should see is this. In the first level it is not that obvious,

Original:
![Screenshot 2022-05-19 094418](https://user-images.githubusercontent.com/81642149/169241567-52cc02c1-2416-488e-96e0-734876bdd06c.jpg)

Promised Lands:
![Screenshot 2022-05-19 094608](https://user-images.githubusercontent.com/81642149/169241594-20392f1f-f135-4290-887f-bfe2ea75819d.jpg)

This is the french revolution tileset. Notice the little french flags on the houses.
In later levels it is ovious. With the code TIMEER you get level 259.

Original:
![Screenshot 2022-05-19 094958](https://user-images.githubusercontent.com/81642149/169241974-76175305-b431-44a9-a6b7-baa2b39e3709.jpg)

Promised Lands:
![Screenshot 2022-05-19 094958](https://user-images.githubusercontent.com/81642149/169242005-8c37e007-c6cb-4f47-b3c1-416d8a0dd71f.jpg)

**Comment by TimberlAndRE-de** [comment]
The Code ist TIMBER ?? 😜 
Ahh, close ...

**Comment by exoscoriae** [comment]
great. seems to be working now then.
