### ISSUE TITLE
Super Huey UH-IX (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3757]
found

- [x] flight instructions card

added to the github folder

**Comment by 19MBAW18** [comment]
Nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnjnnnnnnnn

**Comment by TimberlAndRE-de** [comment]
bless you 😜

**Comment by exoscoriae** [comment]
added

@19MBAW18 wtf?
