### ISSUE TITLE
BarneySplat (1993)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3762]
Meta data notes have a truncated description in the 5.X and WIP branch. Suggest changing to the following (From Moby with some spelling and grammar corrections):

--snip--
In an adaptation certainly not endorsed by PBS, this game puts the player in the shoes of a sociopathic Beavis and Butthead-style radical stoner anarchist (of the ~1992 variety), hopped up on H/P/A t-files and prepared to vent his disgust at all the problems of the world on one moronic purple dinosaur and the other participants on his show, through doping with narcotics to sabotage and booby-traps to, most of all, cartoonish stylized (more Bakshi than WB) and couldn't-care typo-ridden ultraviolence.

The game plays almost as a multiple-choice test on the Jolly Roger's Cookbook, with player input restricted to selecting from a psychedelically-coloured text list how he or she intends to ruin various innocuous activities associated with the show, such as snack time (by injecting the orange with vodka, perhaps?), singing a song together (while substituting in obscene new lines) or visiting the zoo (and selling kids into slavery or feeding Baby Bop to an alligator while there.) (While taking the kids to a GWAR concert is undeniably subversive, it does strain the suspension of disbelief.)

The player is given regular status reports on the current state (of health and sobriety) of all the kids on the show; the ultimate goal is to render the entire cast unfit to perform further by the end of a week's worth of infiltrated episodes, following which the player may get to gather huge bonus points in an endgame sequence where Barney is fought to the death in a shopping mall.

Though the gameplay is single-player, as a BBS door game callers would compete with each other for showings on the high-score table; in later versions of the software, dedicated fans were also granted the opportunity to submit scripted modules consisting of new, further deranged anti-social activities to run the kids through.
--snip--

**Comment by exoscoriae** [comment]
done
