### ISSUE TITLE
WarWizard (1994)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3766]
If you choose anything but none or Sound Blaster 16 at startup, the game crashes. 

I am not sure there is anything you can do to prevent that but i think you should tell the user to select SB16 when you launch the game.

**Comment by exoscoriae** [comment]
added note.

this is one of the games that currently requires DAUM

It crashes when creating a save file in any version of ECE as well as staging. It does however work with X. So I have switched it over.

**Comment by Python-Exoproject** [comment]
Now that this uses X dont forget to change fullresolution=0x0 to fullresolution=desktop

**Comment by exoscoriae** [comment]
done
