### ISSUE TITLE
Bob the Hamster (1994)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3768]
The Moment you collect the last carrot of the level DOSbox crashes hard. Reported by @stickyeye and reproduced in version 5.1 and WIP branch.

Video of it in action:
https://user-images.githubusercontent.com/52749806/160491254-98747cdd-e25a-4b0c-9dec-8559be220f56.mp4

**Comment by SmilingSpectre** [comment]
Actually, it have a chance to hang on any voice playing. I managed to hang it in the options and in "how to play" window too.

Changing DOSBox to ECE seemingly fixing problem.

**Comment by exoscoriae** [comment]
changed version. confirmed fix
