### ISSUE TITLE
Rebel Chess games (Rebel Century (2001), Rebel Decade (2004))

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3769]
This may have been sorted but I am adding it in case its still pending:

Conversation between exo and @SmilingSpectre in discord:

Smiling Spectre — 11/02/2022
@eXo There is a problem with the "Rebel" chess game nomenclature.

There are three parallel chess series of Shroeder: Rebel, Rebel Decade and Rebel Century. With its own numeration and games.

You merged all of them in one entry (that's fine) and named all of them "Decade" (That is not fine).
Moreover, you are totally missing exactly "Decade" games. There is only one Decade - numbered 1.0. Everything else is a simple "Rebel".
Also, I bet that it will not work as intended for Decade. It have wrong paths in the config. checking
Confirmed.

eXo — 11/02/2022
Ok. These will be split then
Unless it's very to just call it Rebel Chess
And create launch options for the different types under it

Smiling Spectre — 11/02/2022
You have Rebel Century as different entry. :)
Split it.
I'll pad Decade with v2 and v3 from TDC.
Funny enough, TDC haven't full 1.0 of Decade at all. sigh

Smiling Spectre — 11/02/2022
Ah, no, they have 1.0. It's 1.2 that is broken.

Smiling Spectre — 11/02/2022
@eXo Also you can add that Rebel 11 is not exist (it is disc with 4 chess engine, and only one of them is Rebel. Rebel Century 3.0, namely). Rebel Century 2.0 isn't exist too (it's engine for other chess program). What a complicated person this Shroeder...

Smiling Spectre — 12/02/2022
@eXo update about "Rebel" chess programs: if delete .CFG, it recreates it in relation to installed dir. So fix is as easy as "delete CFG, run the game through eXoDOS, save config, exit".

**Comment by exoscoriae** [comment]
so rebel decade is just a limited version of rebel 6? that is dumb.

**Comment by exoscoriae** [comment]
renamed entry to just "rebel chess"

in the run menu, set rebel decade as the name of v1

set others to just rebel

found XP doesn't run because no CD is mounted.
v12 complains a required file is missing, even though it is in the folder. I deleted it's rebel.cfg file and verified the new one pointed to the right folders. Still claims file is missing.

**Comment by exoscoriae** [comment]
moved it to staging, and now v12 no longer complains about the missing file.
moutned the rebel century 4 files as a cd, and now the XP versions detects a present CD-ROM and works.

Closing ticket.
