### ISSUE TITLE
Lost in Time (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3771]
Spectre noted in discord:

Smiling Spectre — 13/03/2022
User pyronic  plays Lost in Time in DOSBox and noted that video is somewhat slow. 
For what it's worth the game plays fine on 3000 except when you click on the edge of the screen to walk from area to area. Then it's kinda slow.
Game has cycles=auto, and plays on 3000 cycles. I didn't see much slowing at the start of the game, but it have to be slow in any stressful situation, I think. Maybe set cycles=10000 or something?

**Comment by exoscoriae** [comment]
1993 is 486 territory. set to 20k.
