### ISSUE TITLE
VR Slingshot (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3774]
Ticket created for tracking purposes as the change hadnt come through last I checked.

Eulisker — 20/03/2022
If i see it correctly VR Slingshot (1994) can only be played with a joystick. I don't know if there is anything to be done to fix this.
As of right now you can only listen to a nice (?) midi rendition of Beethovens 5th in the menus
and some mozart in gameplay. but you cant do anything
There is a readme in the files that could be set as the manual though.

eXo — 21/03/2022
can the joystick not be remapped to controls? I have done that several times in the past

Eulisker — 21/03/2022
Not that I have seen.

eXo — 22/03/2022
I meant using the dosbox control mapper.
there should be no reason it can't be done. 

Eulisker — 22/03/2022
Sure. I have never used the mapper.

eXo — 22/03/2022
ok.
i can get it to roll and fire
haven't figured out the thrust\acceleration key yet
ok
got it

Eulisker — 22/03/2022
There is a readme in the game folder with all the keys.
👍

eXo — 22/03/2022
yea, you have to set throttle to mouse
and move the mouse forward or backwards
you can technically move the rudder to it as well
n/m. just pedels are supported
either way
I can fly around now
shoot shit
etc..

**Comment by exoscoriae** [comment]
confirmed file date of 3/21/2022 on my end.
