### ISSUE TITLE
Dudley Dilemma, A (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3775]
Erebus44 noted on discord:

erebus44 — 28/03/2022
Possible bug with A Dudley Dilemma. When I run it, it says sound card found then it black screens. If I comment out "call dudley.bat" and "exit" in the conf file and then manually run the dudley.bat instead the game runs just fine.

Smiling Spectre — 28/03/2022
Confirmed. Looks like a very exotic dosbox bug for me. %)

erebus44 — 29/03/2022
I looked at it again and it just needs a delay before starting. Since dosbox doesn't have a Sleep function I downloaded this one (the sleep.exe is in the bin folder), http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/repos/pkg-html/sleep.html and put it in the games folder, then added "sleep 1" to the conf file just before it runs the batch file and it worked for me.

eXo — 29/03/2022
That isn't the first time I've seen that issue. Nice catch
Dosbox seems to try to start executing batch files too quickly sometimes

**Comment by SmilingSpectre** [comment]
Also, @krc solved it different way: disabling ems seems work too (it's in ken channel).

**Comment by exoscoriae** [comment]
disabled ems
