### ISSUE TITLE
Incredible Machine, The (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3779]
the ba1 file is named `The Incredible Machine (1993)` while the zip file and the bat file are called `Incredible Machine, The (1993)`

I guess it's not a big issue but maybe it's necessary for the eXoTool ?

**Comment by exoscoriae** [comment]
left over from when games did not have "the" proceeding them. The ba1 file name makes no difference. It is just there as a marker.

I fix them if I am already repacking a game. But I don't often repack a game just to modify this file.
