### ISSUE TITLE
Normality (1996)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3781]
The game has two completely different voice casts for the US and UK version. See [here for the game start of the UK version](https://www.youtube.com/watch?v=ez0kEHHICRs&t=210s) and [here for the same part in the US version](https://www.youtube.com/watch?v=ez0kEHHICRs&t=430s).

The version currently in the collection is the UK version. I uploaded the US version to the github folder.

**Comment by exoscoriae** [comment]
both versions now added

**Comment by exoscoriae** [comment]
fixed

**Comment by Python-Exoproject** [comment]
The line:
imgmount d ".\eXoDOS\NORMAL\CD\Normality (USA).cue" -t cdrom

still needs to be removed from the games dosbox.conf as the images are mounted in run.bat for this game but the line in dosbox.conf is screwing it up for the UK version

**Comment by exoscoriae** [comment]
done
