### ISSUE TITLE
wrong path in crt.conf

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#3783]
Another good language pack testing find from Xavier_Velo , but this time it's a bug in the base package:
in the `eXo\emulators\dosbox\crt.conf`
the dosbox path needs to be changed to the new structure:
`glshader=.\dosbox\ece_svn\crt\crt-lottes-fast.subtle+gain.glsl`
to 
`glshader=.\emulators\dosbox\ece_svn\crt\crt-lottes-fast.subtle+gain.glsl`

**Comment by exoscoriae** [comment]
on my end this is already changed.
![image](https://user-images.githubusercontent.com/8557582/163198882-f22a9f55-7275-4e09-ad5c-b67761898a03.png)

Seems you need to do a forced resync
