### ISSUE TITLE
Sid Meier's Colonization (1994)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3786]
The game currently comes with the CD Image of the Windows 3.x version. It is also mounted in DosBox. I think it is for the audio tracks which as far as i know only work with the Windows 3.x version. 
I think you can delete the Image and put these [verified Floppy Images](https://archive.org/details/001981-SidMeiersColonization) instead in there.
Further supporting my theory is the back of the [Windows 3.x Box](https://www.mobygames.com/game/win3x/sid-meiers-colonization/cover-art/gameCoverId,620822/)
![image](https://user-images.githubusercontent.com/81642149/163727818-63cbf961-c782-46c4-b926-2c0e4a707398.png)
SVGA is definitely a Windows only feature and this leads me to believe that the audio tracks are too.

**Comment by SmilingSpectre** [comment]
Well, it's easy to check: remove CD, start the game (and yes, it works).

Another case is that I see no real reason to remove CD. Game installed from it after all, and we hardly lack of space to save it on floppies.

**Comment by Eulisker** [comment]
The reason is: It is the wrong version of the game. Sure the windows cd has the dos version on it. But it still is the wrong version of the game. 
Also you are wasting 300mb for a game that takes 3.

**Comment by exoscoriae** [comment]
It's not the wrong version, it is simple _A_ version of the game.

I went ahead and added the floppies and removed the CD though since it is also in eXoWin3x.
