### ISSUE TITLE
Ski Jump International (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3793]
From user sebdul:

sebdul — 14/04/2022
Hi! Not sure if this is even worth mentioning, but the game called Ski Jump International (1994) has its name subtly wrong and the year definitely wrong. It's rather Ski Jump International v3, also known as sj3. I used to play sj2 (v2) a lot and I considered sj3 a different game when it came out. There's the version history in the file SkiJump/UPDATE.TXT for reference. Strictly the version shipped is from 2011, but as the first version of sj3 is from 2000 I'd suggest changing the game name to Ski Jump International v3 (2000).
I also think sj2 is worth including. It's available at the developer's homepage: https://www.nomasi.com/sj3/pro/index.html#:~:text=SJ2%20v2.10%20Full%20Version!
(note that I didn't try it in dosbox, yet)

eXo — 14/04/2022
Smiling Spectre hasn't this come up before? I swear I've read a breakdown about the various Ski Jump games from you before.

Smiling Spectre — 14/04/2022
I think, I missed it. Because I added Sky Jump International 2 (SWR) and Sky Jump International 3 (SW). But if we have 3 already, then at least last one is obsolete. Let me check.
Yes, TDC has only 2 and 3. So I will remove 3 from uploads. And you, eXo, need to rename collection version to Ski Jump 3. 
And looking on pictures, game you remember most probably is Super Ski.
Super Ski (that is actually Super Ski II) I corrected, indeed.

**Comment by exoscoriae** [comment]
created dual launch for both games. modified the year
