### ISSUE TITLE
Word Rescue (1992) & Word Rescue Plus (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3795]
Smiling Spectre — 11/04/2022
In eXoDOS we have Word Rescue (1,2,3,Plus) and Word Rescue Plus (The same as in batch). Maybe worth either remove it from the trilogy, or remove the separate entry. 

eXo — 11/04/2022
Thanks for catching that

**Comment by exoscoriae** [comment]
removed word rescue plus entry
