### ISSUE TITLE
Sign of the Sun (1997)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3799]
I made an

- [x] Exposé

I am still not sure about the name or any of the text inside it. I am open for suggestions.

Added to the github folder.

**Comment by exoscoriae** [comment]
looks pretty good. I like the idea of it.

I renamed it to remove the special character, as I wasn't sure if the zip program would throw a fit about the accent over the 'e'.

Within LB I decided to call it< "Images of Original Box & Contents"
