### ISSUE TITLE
Archipelagos (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3802]
Note from Spectre:

Our (and TDC) version of Archipelagos (1989) can be crippled. There are four versions of the game - CGA, EGA, Tandy and VGA - and while three former ones are known as floppy, VGA isn't. Also, first three have matching list of files in .exe, and VGA - isn't. In VGA exe there are A.BIN, B.BIN, C, D, F, G, I, K, L,  M, N. In reality we have A, B, C, D, F, G, I. No good version is found though. :(

**Comment by exoscoriae** [comment]
added all versions and a menu to select between them. I'm not entirely sure how the game is crippled though. To file a proper bug report, we need more information that this.

@SmilingSpectre can you add anything to this to make it meaningful?

**Comment by exoscoriae** [comment]
will file this to a low priority report until more info comes along.

**Comment by SmilingSpectre** [comment]
Unfortunately, I have no idea what _could_ be in the presumably full version. I only see discrepancy: every version has the same set of files that are in the .exe. Except VGA that have twice the amount of files listed in .exe than in reality and also have unknown origin (only known version is matching single warez release). Maybe it's something skippable like logo or intro. Maybe different graphic mode. Maybe it's tileset for later levels. Or sound. Or maybe it's nothing, and mere an artifact of the conversion from some Amiga. :( No idea, but case looks fishy.

**Comment by exoscoriae** [comment]
ok. thanks. Lets put this into low priority and keep an eye out for an original disk image.

**Comment by Eulisker** [comment]
I found the images and uploaded them to the github folder. They have the same content as they are currently in the collection. I am pretty sure they are complete.

**Comment by exoscoriae** [comment]
ok. that tells me there is no change to be made? except maybe add the original images for archiving purposes.

@SmilingSpectre you are welcome to look at the images closer to determine if you think something is still crippled.
