### ISSUE TITLE
Soltys (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3803]
From Xavier_Velo:

Soltys (1995) kicks to DOS after changing location few times (usually 4-6). To recreate this just use a bone on the bowl, some numbers will appear in left-down part of screen. These number are used to change location, do this few times and then boom, black screen and "Bad VBM [various numbers or names here]" message appears. Tried this on many versions (floppy, CD, Polish & English) & few DOSBox forks - all the same. ScummVM version works fine btw. Can anybody confirm this?

Python — 24/04/2022
Confirmed issue. Ive tried a number of things for this one including no sound, the original Polish version instead of the English translation, and various dosbox conf settings, all with no luck. Quickest way to get the issue is to go to room 5, then 6, then back to 5 - crashes every time. I looked online and in the few mentions of it it seems even real DOS machines have given this error. Maybe one for Ripsaw eXo?

I also note eXo that while we present the user with a sound choice on every launch and instructions on how to set the card up once inside the game, after the first time the game saves the selection and it cannot be changed again.

**Comment by exoscoriae** [comment]
this is due to copy protection. replaced cge.exe with a deprotected version ripsaw created a while back.
