### ISSUE TITLE
Space MAX (1992)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3804]
The version in eXoDOS has a few corrupted files resulting in glitches like this:

![Screenshot_2022-04-28_112453](https://user-images.githubusercontent.com/81642149/165749100-52fe55cd-80e4-4218-9b78-968654b2e5ed.jpg)

@SmilingSpectre found a working version in TDC. I made the following 2 adjustments to the run.bat and uploaded the game to the github folder. (eXoDropBox\GitHub\eXoDOS\Bugs)

- You can change the audio configuration in config.dat with an echo command directly from run.bat.
`ECHO 01---- > CONFIG.DAT` for Soundblaster and `ECHO 02---- > CONFIG.DAT` for MT32.
There is no need for the sb16 or mt32 folders and copying from there anymore.
- The run.bat now calls the .exe with the appropriate parameters instead of another .bat. This allows us to just exchange the run.bat to get a german version of the game.

I also deleted the floppy folder since it is just the content of the floppies and not images. It is currently mounted in the .conf but not needed for the game.

**Comment by exoscoriae** [comment]
great changes. kept the floppy folder though. Even though it is not the images, it is an installer. Which could be useful in the future.
