### ISSUE TITLE
Starglider 2 (1989)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3805]
I found an 

- [ ] Audio Tape

It was included [in the box](https://www.mobygames.com/game/dos/starglider-ii/cover-art/gameCoverId,235856/) and is a nice recorded version of the Main Theme. The mp3 is from [Zophar's Domain](https://www.zophar.net/music/atari-st/starglider-2).

Added to the github folder.

**Comment by exoscoriae** [comment]
added
