### ISSUE TITLE
Fox Ranger (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3806]
Another game fixed for Roland sound. Noticed this game should have working midi but had no luck, Spectre discovered that our and TDCs copies were incomplete. He located a new copy that works as it should.

[Fox_Ranger.zip](https://github.com/exoscoriae/eXoDOS/files/8596934/Fox_Ranger.zip)

Needs the usual, switch to ECE, setup user options, add to both LB playlists.

Current launch command is "fox a v" where a is adlib. Change to "fox s v" for soundcanvas or "fox m v" for MT32

**Comment by exoscoriae** [comment]
great finds on these.
