### ISSUE TITLE
International Open Golf Championship (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3807]
This is an interesting one. 

I found out that while the newer version (included in eXoDOS) has a file named "LAPC1.DEV" the MT32 wiki said (and I confirmed, at least using the same command line argument to activate MT32 as the older version does) that only the older version of the game works with MT32 activated without crashing. 

I found a copy in TDC of the older version for us to add to exodos if you wish to include the older release in order to allow the MT32 option. Older version looks a bit different as well so could be worth adding for that reason alone.
[International Open Golf Championship (Installer) (1993)(Ocean Software Ltd.) [Action, Sports].zip](https://github.com/exoscoriae/eXoDOS/files/8597019/International.Open.Golf.Championship.Installer.1993.Ocean.Software.Ltd.Action.Sports.zip)

The second point of interest is that for the older release of the game, I couldnt get either of the ECE versions, X, or daum to load it without crashing. Vanilla dosbox worked but doesnt have Munt. Staging also worked so if this matches your results and staging is what you need to use then there is a small change to the conf for MT32 to work:

activating is still the same:

[midi]
mididevice=mt32

but the romdir path is now:

[mt32]
romdir=.\mt32

Other than that, the usual user options setup and adding to MT32 LB playlist.

**Comment by exoscoriae** [comment]
not sure what the issue with crashing for you was? I am able to play the older version with mt32 or SB with no issues.

I'll be interested to hear if it works for you after the sync

**Comment by Python-Exoproject** [comment]
Not sure what the crashing was either as your synced version worked with a proviso, I had to edit run.bat to fix two errors:

1) The :SB16 section has "cd GOLD" when it should be "cd GOLF"
2) The :MT32 section should also cd into the same folder but currently does not

As an aside, these two versions are so different its like they are different games. I know they were both published by Ocean and have the same game name, but thats where the similarities seem to stop. Your user note says the "alt" version has different intro and menus but its more than that, the gameplay looks completely different (just start a practice in both and you will see), the interface is different, and the older version (the one marketing "Pringles of Scotland" and has MT32) has no sound fx.

**Comment by exoscoriae** [comment]
made changes to run.bat.
