### ISSUE TITLE
Rally Championships (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3809]
Currently we have the CD version with CD Audio tracks. Discovered that the floppy release has MT32 and SC55 capability. If you wish to add the floppy release as an option for this reason then here is a copy, complete with crack:
[Rally Championships (Installer) (En)(De)(Fr)(It)(Es)(Nl)(Pl)(Pt) (1994)(Flair Software Ltd.) [Action, Racing - Driving].zip](https://github.com/exoscoriae/eXoDOS/files/8597211/Rally.Championships.Installer.En.De.Fr.It.Es.Nl.Pl.Pt.1994.Flair.Software.Ltd.Action.Racing.-.Driving.zip)

Game is already on ECE so just user options and both LB playlists

**Comment by exoscoriae** [comment]
done. added floppy sb16 as well, as it was not represented on the cd version.
