### ISSUE TITLE
Arrakis (2000)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3813]
It looks like there is a file called arrmore.bat that gives a different set of missions, it might be worth setting it up as a user option? 

I also noticed that the music only plays successfully a small percentage of the times the game is started, though I think this might be an issue of the game itself.

**Comment by exoscoriae** [comment]
highly confused by this.

arrakis's launch file was the old type, pre-universal launcher.  This is the first time I have come across a file that wasn't converted yet.

Searched and found several other files that had never been upgraded properly. This stuns me
Fourth Generation, The (1996)
Arrakis (2000)
Dismal Passages - Part I - The Wicked Curse (1995)
Spear End of Destiny (2004)

All required updating. The commonality? All DAUM games.
