### ISSUE TITLE
Day of the Viper (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3819]
The new run.bat has a typo. In the ADLIB section it has "sound/com" instead of "sound.com"

We are also considering buying an original copy as the MT32 sound choice fails, along with the in game sound being stuck on PC Speaker. This maybe as the game was released but we are unsure enough to want to check.

**Comment by SmilingSpectre** [comment]
It also creates subfolder "MAZES" in folder "MAZES" and don't write anything in it. But seeks for non-existing MAZE[X].WK in MAZES before start. Sounds quite suspicious for me, but maybe only sloppy programming, of course.

**Comment by exoscoriae** [comment]
if an affordable copy ever pops up, I am willing to purchase it.

**Comment by Python-Exoproject** [comment]
Moved to Media Upgrade project as we wait for a copy to become available for purchase. This is in the hope that a verified clean copy will not have issues with MT32, for the reasons noted above.

**Comment by exoscoriae** [comment]
implemented a fix from ripsaw that dumps the midi channels properly to the mt32
