### ISSUE TITLE
The Game of Harmony (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3821]
This game can do CMS\GB and doesnt sound to bad doing so. To activate set sbtype=gb and use this NRS archive for the exe file:
[Game of Harmony, The (1990).zip](https://github.com/exoscoriae/eXoDOS/files/8621535/Game.of.Harmony.The.1990.zip)

**Comment by exoscoriae** [comment]
added sound and video options

**Comment by Python-Exoproject** [comment]
Couple things with this one:

First it looks like the game actually needs sb-sound.com to use the soundblaster option with actual soundblaster output. This is not included in the game folder currently. sb-sound.com is actually creatives driver for adlib sound and is not as good as the official sound.com driver. Here is a copy of sound.com to put in the game folder: [SOUND.zip](https://github.com/exoscoriae/eXoDOS/files/9035056/SOUND.zip), extract to the game folder and update "sb-sound" in the run.bat to "sound"
 
Second, the execution of "sound" is currently under the ":SB16" section in run.bat which is a problem. If you choose the soundblaster option to start the game manually then it works fine as this part of the code is executed, but if the settings are ok with the user and not changed then the code goes straight to launch and skips the running of "sound" which results in pc speaker instead.

Third, regarding the setup for changing the user options this game must have predated our discussion to list the other options that are possible like we do for most of the Sierra games (Police Quest 1 SCI as an example)

**Comment by Python-Exoproject** [comment]
Ok, heres a kicker. That second point is a big issue for all the games setup using this method. It not only means programs like sound.com are not executed if the user doesnt change any options and just accepts the previous choices, it also means that no "CONFIG" settings are changed. This results in all Game Blaster choices in all these games not working for example as "CONFIG -set "sbtype=gb"" isnt executed. Im going to raise a separate issue for this as it will cover multiple games.

**Comment by exoscoriae** [comment]
fixed

**Comment by Python-Exoproject** [comment]
You didnt address this point?

Third, regarding the setup for changing the user options this game must have predated our discussion to list the other options that are possible like we do for most of the Sierra games (Police Quest 1 SCI as an example)

**Comment by exoscoriae** [comment]
added
