### ISSUE TITLE
Laura Bow 1 - The Colonel's Bequest (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3827]
Game can do CMS\GB. Set sbtype=gb and setup sierra resource file to use cms.drv

**Comment by exoscoriae** [comment]
done.

also cracked the game. I'm surprised it hadn't been previously.

**Comment by exoscoriae** [comment]
fwiw, I can't find sound in the game at all? How long do you have to play until you hear something?
