### ISSUE TITLE
Leisure Suit Larry 2 - Goes looking for Love in Several Wrong Places (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3828]
This game can do CMS\GB. Set sbtype=gb, setup the sierra resource file, and use the below driver
[Leisure Suit Larry Goes Looking for Love (In Several Wrong Places) v2.000 (1988).zip](https://github.com/exoscoriae/eXoDOS/files/8639963/Leisure.Suit.Larry.Goes.Looking.for.Love.In.Several.Wrong.Places.v2.000.1988.zip)

**Comment by exoscoriae** [comment]
added
