### ISSUE TITLE
I Have No Mouth and I Must Scream (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#383]
has watermark replacementdocs
coverpage is missing

proof:
![x720](https://user-images.githubusercontent.com/67441153/87283394-8bd14200-c4f5-11ea-898d-4a3967ef763c.jpg)

**Comment by SmilingSpectre** [comment]
Found French manual. Extracted from En-Fr-Ge-It version. :| So will not work too.

**Comment by ArkhangelAzrael** [comment]
Found a good scan of the manual: https://mysterymanor.net/gamemanuals/I%20Have%20No%20mouth%20And%20I%20Must%20Scream%20Manual.pdf

**Comment by TimberlAndRE-de** [comment]
wysiwyg found 

- [ ] manual (scanned double sided - still much better then the current version)

added to the github folder

**Comment by exoscoriae** [comment]
replaced
