### ISSUE TITLE
Silpheed (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3835]
Couple things with this one.

First, I noticed that when you choose from the in game menu to play the intro or play the game there is a screen asking to insert the floppy. This can be avoided if you change the last line of the resource.cfg files from "3 1/2 FLOPPY" to "HARD DISK"

Second, This game can do CMS\GB. To enable set sbtype=gb, add the below driver to the game folder, and set the resource file to use cms.drv
[CMS.zip](https://github.com/exoscoriae/eXoDOS/files/8641720/CMS.zip)

There is one drawback to the CMS option, it has no sound FX and the small intro bit with the face of the bad guy comes up and then skips his speech. This is due to the fact we are using a NRS hacked copy of the game that fixed the bad guys speech so that it can actually be understood but to do this the sbtype must be a sound blaster card as it uses the audblast driver.

**Comment by exoscoriae** [comment]
made the changes in the initial post.

Opting to not make the changes in the second post unless there is significant benefits to doing so.

**Comment by Python-Exoproject** [comment]
Ok, so using staging 80.1 everything has come together in one fork to allow the original game files to be used instead of the NRS hack, Game Blaster, the usual sound options, and PS/1 Audio.

Use [Silpheed.zip](https://github.com/exoscoriae/eXoDOS/files/10848296/Silpheed.zip). This includes the unhacked files for the game, a conf setup for staging (some options are different from the other forks), and a run.bat that offers the sound choices. I did the sound choices in a two tier menu to avoid having a list of combinations 7 long.
