### ISSUE TITLE
Sorcerian (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3836]
This game can do CMS\GB. Set sbtype=gb. It looks like you have attempted this previously looking at the gesource.cfg file but I assume you hit the same issue I did with it giving no sound. I kept playing with it and somehow managed to get it to work using this cms.drv file and this specific resource.cfg. I cant see what is different between this attached cfg file and just changing one to use the cms.drv but it only worked for me when using the attached one.
[CMS.zip](https://github.com/exoscoriae/eXoDOS/files/8641922/CMS.zip)

**Comment by exoscoriae** [comment]
added game blaster option
