### ISSUE TITLE
Stormovik - SU-25 Soviet Attack Fighter (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3838]
Couple things for this one.

To create a new pilot you first have to delete the file "su25.cfg", so might need to set that up as a user choice

Add "hi" to the command line to play in high detail (IE "su25 hi adlib")

CMS is a valid sound option with sbtype=gb and using "su25 hi cms"

Tandy is a valid sound option with tandy=on and using "su25 hi tandy"

**Comment by exoscoriae** [comment]
options added.
