### ISSUE TITLE
Windwalker (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3841]
This game can add Tandy, CMS\GB, and Innovation. Setup user choices and use:

sbtype=gb for CMS. Run game with "wind cms"

tandy=on for Tandy. Run game with "wind tsnd"

For Innovation you will need to switch to Daum or Staging if you wish to add the option. Run game with "wind innov" and in dosbox.conf:

Staging:
[innovation]
sidmodel=auto

Daum:
[innova]
innova=true

**Comment by exoscoriae** [comment]
sound for cms sounds wrong using the staging build I have

**Comment by exoscoriae** [comment]
daum seems to work
