### ISSUE TITLE
Dr. Jummybummy's Space Adventure 2 (2010)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3848]
This uses the SCI engine so has all that engines sound choices. Currently the games resource.cfg is set to use the MPU-401 driver while the dosbox.conf is set to use sb16 so it doesnt sound great. Options to add for the user are:

MT32: set the conf for mididevice=mt32, add to LB playlist. For the games resource.cfg file I actually suggest using MPUMIDI.DRV as the MT32.drv doesnt sound right.

SC55: set conf for mididevice=fluidsnyth, add to LB playlist. For the games resource.cfg use gm.drv

CMS\GB: Despite having the cms.drv in the game files and hints of it working found on the web I couldnt get this to give sound when setup with sbtype=gb

ADL\SB: I had no sound when using the adl.drv file either.

Im thinking that the creators of the game only implemented GM & MT32 which is why other sound modes have nothing

**Comment by exoscoriae** [comment]
setup sc55 and mt32 options.

went ahead and left soundblaster as an option using mpumidi. the drums sounded right in the beginning. and while parts of it are odd.... it is def adlib type sounds. 

No luck with cms.drv either. Didn't spend much time with it though.

**Comment by exoscoriae** [comment]
added to playlists

sc55 sounds like shit to me.

it's a shitty fanmake game though. so who knows what is going on with it.
