### ISSUE TITLE
Hound of Shadow, The (1989)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3852]
Aspect Ratio is off for the game when globally set to "yes". Changing to aspect=false in the dosbox settings corrected the issue. Reproduced the issue in both 5.1 and WIP branch.

**Comment by Python-Exoproject** [comment]
Our standard method for doing this is to add "ASPECT FALSE" to the conf autoexec section

**Comment by exoscoriae** [comment]
fixed
