### ISSUE TITLE
Quest for Glory I - So You Want to be a Hero (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3853]
The CGA and EGA Game Blaster cfg files have been swapped for the Hero Quest option. IE when you select CGA with Game Blaster you get EGA and vice versa. Need to either redirect run.bat or change the video drivers around between \HQ\ CGSOURCE.CFG & GESOURCE.CFG

**Comment by exoscoriae** [comment]
ah. so this is the game I created the way over complex menu system for....lol

fixed the issue with the cfg files. good catch
