### ISSUE TITLE
Freddy Pharkas Frontier Pharmacist (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3859]
The included demo has only been setup for VGA with SoundBlaster. Not sure if its worth the effort of adding other options as its just a demo with unique puzzles, but if you want to we can add:

General Midi using genmidi.drv instead of adl.drv
MT32 using genmidi.drv instead of adl.drv
EGA using ega640.drv

**Comment by exoscoriae** [comment]
interesting. the full game had no ega driver. but copying the one from the demo over actually allows the full game to be played with EGA
