### ISSUE TITLE
Gunboat (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3862]
The game has cms.drv and according to page 61 of the manual the game can do CMS and Tandy sound.

For CMS use in the run.bat section you create for the choice:
CONFIG -set "sbtype=gb"
CONFIG -set "mpu401=none"
CONFIG -set "mididevice=default"

For Tandy use in the run.bat section you create for the choice:
CONFIG -set "sbtype=none"
CONFIG -set "mpu401=none"
CONFIG -set "mididevice=default"

For Tandy you will also need to create a separate gunboat.cfg set to use Tandy from setup.exe and use machine=tandy

**Comment by exoscoriae** [comment]
skipping tandy then, as that means moving that option to an exception file.
