### ISSUE TITLE
Quest for Glory I - So You Want to be a Hero VGA (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3863]
Game can do CMS\GB. Set sbtype=gb and disney=true. In sierra resource.cfg use cms.drv and auddisny.drv

**Comment by exoscoriae** [comment]
done

**Comment by exoscoriae** [comment]
renamed to Quest for Glory I - So You Want to be a Hero SCI (1992)
