### ISSUE TITLE
Multiple Sierra Game Driver Issues\Posibilities

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3866]
I did a couple of checks over the drivers being utilised in all the sierra .cfg files throughout the collection. I found:

-----------------------------------------------------------------------------

**Games using adl.drv instead of sndblast.drv or sbpro.drv**. 

Usually it seems this is due to the generic sierra and dynamix bug that meant faster systems didnt init the soundblaster driver in the correct time and the game froze. Good to fix as fx like Betrayal at Krondor intro lightning sound better under sound blaster driver. Ive noted the games that need addressing below and provided patched drivers where needed.

_Betrayal at Krondor_: update the resource.cfg files in \sb16 & \cda, and the sesource.cfg in \floppy to use sndblast.drv instead of adl.drv, then copy this file ([Betrayal_at_Krondor_SX.zip](https://github.com/exoscoriae/eXoDOS/files/8717257/Betrayal_at_Krondor_SX.zip)) into the same folders.

_Hoyle Classic Card Games_: update sesource.cfg and egasb.cfg to use sbpro.drv instead of adl.drv.

_Kings Quest V_: update sesource.cfg in \floppy to use sndblast.drv instead of adl.drv. In the user choice menu you are calling the EGA selection for "SB16" "Adlib". Also we are only offering the CMS choice for the EGA version when it can also be offered in the floppy vga version if we wish to do so. Lastly tandy can be setup for EGA qnd Floppy modes as there is a tandy.drv driver to use, just set tandy=on and setup the resource file.

_Kings Quest VII_: update resource.cfg in \kq7\kq7dos\sb16 to use sbpro.drv instead of adl.drv.

_Leisure Suit Larry 1 VGA 1991_: update sesource.cfg in \ega to use sndblast.drv instead of adl.drv, then copy this file ([LSL1_1991_EGA_SNDBLAST.zip](https://github.com/exoscoriae/eXoDOS/files/8717266/LSL1_1991_EGA_SNDBLAST.zip)) into the same folder.

_Leisure Suit Larry 6_: update sesource.cfg in \lsl6cd\lsl6 to use sbpro.drv instead of adl.drv

_Mega Math_: update resource.cfg in \sb16 to use sbpro.drv instead of adl.drv.

_Quest for Glory I - So You Want to be a Hero VGA (1992)_: no changes needed here, just a bit of cleanup. This 1992 version of the game didnt have a sndblast.drv file, however when we added the patched version of sndblast.drv to the 1989 release it was also added here in the \qg1new folder. This file can safely be deleted. Looks like the same thing happened for the mtblast.drv, this file was for (and is correctly included in) the 1989 release. It serves no purpose here in the 1992 release and is misleading when looking at potential drivers for the game. It can also be safely deleted.

-------------------------------------------------------------------------------------------------------------

**Games with an sbpro.drv that are using a different driver in soundblaster user option resource.cfg**

_Aces of the Deep (1994)_: For some reason the resource.cfg in \sb16\ is currently using MT32.drv, change to sbpro.drv

_Phantasmagoria (1995)_: For some reason the sesource.cfg is currently using genmidi.drv, change to sbpro.drv. Mesource.cfg for the MT32 choice is also using genmidi.drv instead of mt32.drv

-------------------------------------------------------------------------------------------------------

**Sierra games that can do EGA with the ega640.drv driver but arent setup to do so**

Crazy Nick's Software Picks (1993): All the games in the pack can do this, not sure if its worth it though
EcoQuest 2 - Lost Secret of the Rainforest (1993)
Island of Dr. Brain (1992)
King's Quest VI - Heir Today Gone Tomorrow (1992)
Pepper's Adventures in Time (1993)
Police Quest 1 - In Pursuit of the Death Angel VGA (1990)
Quest for Glory I - So You Want to be a Hero VGA (1992)
Quest for Glory III - Wages of War (1992)
Slater and Charlie Go Camping (1993)
Space Quest V - The Next Mutation (1993)

-------------------------------------------------------------------------------------------------------------

**Games with a tandy\jr .drv file not setup with a tandy sound option.**

_Mixed-Up Mother Goose (1990)_: This game can do tandy sound option with either jr.drv or tandy.drv (not sure if there is any difference via dosbox (I didnt hear one) but in real hardware there apparently is a slight one: https://www.brutman.com/forums/viewtopic.php?t=168)

_Bloodwych (1989)_: Can do Tandy sound. Choice is made inside the game menu system so add tandy=on to conf and update run.bat user note.

_Hero Quest (1992)_: This one can do Tandy sound but needs machine=tandy to do so. As the conf is identical between the two game modes this can be achieved by setting the "-machine tandy" command line argument in exception.bat (like Blue Angels for example) and moving the run.bat sound choices into the exception as well. Then the dosbox conf can still point to run.bat which would now only be the Intro\Gameplay choice. I already made the games tandy cfg file for putting in a \tandy folder ([HeroQuest_Tandy_Cfg.zip](https://github.com/exoscoriae/eXoDOS/files/8717299/HeroQuest_Tandy_Cfg.zip))

_Low Blow (1990)_: Can do Tandy sound but needs machine=tandy to do so. Unfortunately as this game has a different command line argument per sound choice I believe you will have to go the seperate tandy dosbox conf route. To start the game in Tandy mode use "BOX TANDY"

_Oil's Well (1990)_: Can do Tandy sound. Set tandy=on in conf. Use install.exe to select the tandy sound option and generate the needed OWCONFIG.dat file.

_Space Quest IV - Roger Wilco and the Time Rippers (1991):_ This game can do tandy sound option with tandy.drv in the EGA version. Set tandy=on and setup the sierra resource file.

--------------------------------------------------------------------------------------------------------------------

**Games using audnone.drv will use default pc speaker fx.** 

This is usually done for CMS configs as the CMS cant work at the same time as soundblaster, but a better solution is to use the auddisny.drv and enable disney sound source in the conf as this provides significantly better fx in game.

_Conquests of the Longbow_: update cms.cfg files in \longbow & \longbow\ega to use auddisny.drv instead of audnone.drv, then add disney=true to conf

_Hoyle Classic Card Games_: update egatandy.cfg file in \hoylec & resource.cfg in \hoylec\tandy to use auddisny.drv or audblast.drv instead of audnone.drv. If choose disney fx with auddisny.drv then add disney=true to conf, if choose sb fx with audblast.drv then you will need to add CONFIG -set "sbtype=sb16" to :tandy and :egatandy sections of run.bat as the current dosbox.conf setting is sbtype=none

_Mixed-Up Fairy Tales (1991)_: update cms.cfg file in \mufairy\ega to use auddisny.drv instead of audnone.drv, then add disney=true to dosbox conf. The same also applies to cms.cfg in \mufairy but only matters if we have added the CMS audio choice to the user for the VGA version of the game (currently its only offered for the EGA version)

**Comment by exoscoriae** [comment]
changes above made with the following exceptions:
KQ6 has EGA options already. Maybe they weren't present when you wrote this up?
PQ1 SCI had EGA options added recently
QFG1 SCI had EGA options added recently

Unfortunately you are incorrect about Hero Quest. While Tandy can share the sb16 conf file, the game would still require 2 confs due to the midi default settings for mt-32 versus sb16. As there is no longer a choice to pick sound type in the run.bat (as it was shifted to the exception.bat), the default midi device and the copying of the proper quest.cfg files still has not taken place.

That said.....

I devised a new method for multiple machine types that does not require extra conf files. I rolled it ot for both HeroQuest and Low Blow. This method allows us to have multiple machine types with a single conf file, even if the executable for the game changes or other changes to the default midi must be made.

I'm surprised I hadn't thought about this method before, but it is an evolution of our SEL files.

Essentially, the exception.bat records the game type you want to play and writes an SEL file to the game's data folder. Then passes to a launch stub. The launch stub checks the game's folder for an SEL file. If there is one named TANDY, it applies the -machine tandy call.

In the case of lowblow, I still have it call the run.bat file within dosbox. But now, it is noninteractive. It simply scans the folder for an SEL file, and based on what it finds it knows what settings to apply to the sound options and what command line to call to execute the game.  I'm quite happy with this, and I think we should go back and use it in any case where we have multiple conf files.

Thanks for researching all of this. This was quite a boat load.

**Comment by Python-Exoproject** [comment]
Issues still to address:

Betrayal at Krondor: You forgot to extract the file in [Betrayal_at_Krondor_SX.zip](https://github.com/exoscoriae/eXoDOS/files/9029249/Betrayal_at_Krondor_SX.zip) into the \krondor\cda & \krondor\sb16. Without doing so the game freezes when these sound choices are selected.

Hero Quest (1992): With the new method that uses exception.bat to do the sound choice so that we can pass the machine type for Tandy, it looks like the setting of mididevice and mpu401 for MT32 that used to happen in the run.bat is being skipped? The other game you mentioned, Low Blow (1990), handles this problem in run.bat well.

**Comment by exoscoriae** [comment]
added file to krondor

great catch on hero quest. fixed
