### ISSUE TITLE
Legacy of the Necromancer - Part II - The Palace of the Necromancer (1989)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3868]
The author of "Legacy of the Necromancer - Part II - The Palace of the Necromancer (1989)" and part 3 "Legacy of the Necromancer - Part III - The Dark Tower (1989)" should be changed from Unknown to "Lee Chapel" to sync with the Part 1 entry. He authored all three of the parts.

**Comment by exoscoriae** [comment]
done
