### ISSUE TITLE
Last Half of Darkness (1989)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3869]
Found an issue when running Last Half of Darkness (1989) in the VGA remake 1991 option (option 3 at launch). When I try to examine anything using the magnifying glass it seems to crash to the setup choices and then dos prompt. Tested in WIP branch. 

Video found here: https://discord.com/channels/454359114601201666/467028238687010826/976545337235869797

SmilingSpectre confirmed and believes it is to do with the way it is loading.

**Comment by exoscoriae** [comment]
fixed
