### ISSUE TITLE
Star Control (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3870]
Our Game Blaster choice for this game is not setup correctly and is still playing midi music/fx due to auto detection. To get it working properly add to the run.bat :CMS section:
 
CONFIG -set "mpu401=none"

Same goes for the SoundBlaster choice, add the same line to :SB16 section to fix.

**Comment by exoscoriae** [comment]
changes made. great catch

**Comment by Python-Exoproject** [comment]
No issues with the above, QA all good but can I add a request for this game?

I always liked the copy protection page for this game (nostalgia is weird :-) ) and ive found a crack that allows the page to come up but pass on any input instead of skipping it completely. To do this you just need to delete starcon.com and replace starcon.ovl with this one: [STARCON.zip](https://github.com/exoscoriae/eXoDOS/files/9034866/STARCON.zip)

Only draw back I can see is that some users might think they need to use the codewheel and enter the correct code, but it wouldnt be the only game to do this and if you really want you could just add a user note saying to just press enter.

**Comment by Python-Exoproject** [comment]
Another improvement to the game could be to add edit.exe and\or keys.exe to the run.bat as launch options. Edit allows you to create your own scenarios or edit existing ones and keys allows you to redefine the keyboard controls if you find the default ones difficult (and they are weird, Heirachy keys are 1\2\3\4\5 and Alliance are m\,\.\/)

**Comment by Python-Exoproject** [comment]
Still need to delete starcon.com which is the official crack that came on the game CD. If you dont wish to delete the file then you will need to point the run.bat at starcon.exe specifically to avoid running the com file

**Comment by exoscoriae** [comment]
ok. removed the .com file
