### ISSUE TITLE
Hard Drivin' II (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3872]
Intro for both games sounds better using ECE due to better speaker emulation (and maybe with cycles 2000?), but the gameplay sound is not quite right to my ears. What do you think?

**Comment by exoscoriae** [comment]
looking at youtube videos of the game, they all seem to sound about the same to me. Not sure if they are using dosbox to capture though. The only way to tell would be to see a recording we know was captured on real hardware. But considering this is pc speaker, I doubt it can sound much better?
