### ISSUE TITLE
Three Stooges, The (1987)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3873]
Another game that suffers from vanilla dosbox bad speaker emulation. Switch to ECE and reduce cycles to 1000 to get speech via speaker added back to the game.

Another issue is a graphical glitch that is present in all dosbox forks:
![image](https://user-images.githubusercontent.com/67406191/169323982-bfee6760-9794-452b-b88a-a119f0fa1214.png)

Any thoughts on this one @kcgen or @SmilingSpectre?

**Comment by SmilingSpectre** [comment]
There is also initial countdown broken (on "3")
Corrupted resource files. Three Stooges, The [a1] (1987)(Cinemaware Corporation) [Action] and Three Stooges, The (1991)(Mirror Image) [Action] from TDC both are fine. There is also Kryoflux image, but I didn't test it.

**Comment by SmilingSpectre** [comment]
[Three Stooges, The (1991)(Mirror Image) [Action].zip](https://github.com/exoscoriae/eXoDOS/files/8732375/Three.Stooges.The.1991.Mirror.Image.Action.zip)
[Three Stooges, The [a1] (1987)(Cinemaware Corporation) [Action].zip](https://github.com/exoscoriae/eXoDOS/files/8732377/Three.Stooges.The.a1.1987.Cinemaware.Corporation.Action.zip)

**Comment by exoscoriae** [comment]
made sound changes.

I was able to fix the corrupt files. The kryoflux images are copyprotected, which prevents them from being used to install and run the game. I was however able to extract the art files from those images, and replace the ones we had on disk. This removed the corruption from the countdown and the eveil man in the first scene.

![image](https://user-images.githubusercontent.com/8557582/169576936-dcf94484-3f94-443b-9c9f-a46d254c42cf.png)
