### ISSUE TITLE
Suggestion to use different compression algorithm instead of zip

### ISSUE THREAD

**Issue by erazortt** [exoscoriae/eXoDOS#3877]
I would like to suggest replacing the compression algorithm used from zip to zstd. zstd is a much much superior compression algorithm and its compressions levels 5 or 6 are compressing better than the maximal level of zip while being faster to compress and decompress than the lowest compression level of zip. The higher the compression level the slower the compression but the decompression stays fast independently. This would decrease the total file size while increasing the speed of decompressions for the users.

The command line tool can be found here:
https://github.com/facebook/zstd/releases

The usage is very simillar to the usage to the currently used unzip.exe.

**Comment by exoscoriae** [comment]
Repacking the entire project using this method would require thousands of users to have to do the same thing, or face redownloading the entire project from scratch.

That said, I will have to do some tests to see exactly how much it increases compression by and how the time is affected.

**Comment by exoscoriae** [comment]
Ok. So zstd is not an archiver. It can not archive an entire folder into a single folder:
https://github.com/facebook/zstd/issues/1526

So, to use this, I would have to run it on every file in the games folder, which can be done recursively from a single command. But, that also means, I then have to use zip or tar or something anyways to compress the entire folder into a single file *after* I have already used zstd.

This will clearly be slower than just using zip by itself, as it requires extracting everything twice. Once to populate the folder with zstd files, and then I have to run a recursive decompression loop to extract every zstd file in the folder.

This is a preservation project. The number one problem with this approach, is it renders the files unusable for anyone who downloads this project that doesn't understand zstd. It is not like a zip file, which anyone running windows can simply double click and easily view\manipulate the contents.

This does not fit the goals of the project.

**Comment by erazortt** [comment]
Well, yes. That would only be an idea for a future release, long term.

**Comment by exoscoriae** [comment]
We could get around part of the issue by using tar first to archive the folder, and then zstd the tar file. This would prevent me from having thousands of nested zstd files.

But this still creates a scenario where end users can not access the files.

**Comment by exoscoriae** [comment]
it is key to remember that unzip is something that is native to windows explorer. anyone can open a zip file by simply double clicking it.

Also, from what I saw, I wasn't getting humungous space savings. I tried it on phantasmagoria 2, and the zstd file, and default #3 compression, was actually *larger* than a zip file.
