### ISSUE TITLE
Legend Lives!, The (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3878]
mgoddard reported on discord:

Trying to run Legend Lives!, The (1994) in WIP branch and it starts to display some information and then dosbox seems to crash. I'm not sure how to help troubleshoot further.

Ive confirmed the issue, it happens after you get through a couple of screens of text. It freezes and then a minute later crashes out of tr.exe into dosbox and exits

**Comment by exoscoriae** [comment]
fixed
