### ISSUE TITLE
Lexi-Cross (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3879]
Discord discussion:

LordVig — Yesterday at 09:59
anyone else had an issue with Lexi-Cross where even when you choose Living vs Living, you end up with robot players and don't get to trigger the Pristine Mint build your own player mode?  Not sure what I'm missing here.  Running Exo through launchbox of course.

eXo — Yesterday at 13:39
I'll have to test it next time I sit down with the pack

LordVig — Yesterday at 15:04
figured it out... it's the start.bat resident TSR crack that is causing the problem.  The crack is skipping the opening section entirely.  While it bypasses the copy protection, italso bypasses the opportunity to create players.  Since you kindly included the manual, when I edit your run.bat to not run the start.bat and just run lexicros.exe instead, the game works fine, we use the manual to complete the copy protection, and everything runs smoothly.  Maybe look for a different crack... just what I figured out... hope it helps!  Love that you put this set together Exo! 🙂

eXo — Today at 05:27
Excellent. Thank you for looking further into it
I'll try to recrack it in a proper way

**Comment by exoscoriae** [comment]
repaired.

confirmed living vs living now allows one to build a player
