### ISSUE TITLE
Infiltrator (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#388]
three pages are missing  probably empty pages or wrong pagenumbering - but needs to be proofed

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found a better version without missing pages
I copied it over to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
The current manual has box front and back and an atari reference card included. I cut everything out of the

- [ ] manual

Thanks to Discord user remowilliams for scanning.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced
