### ISSUE TITLE
Spellcasting 101 - Sorcerers Get All the Girls (1990)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3883]
I found a better looking 

- [x] map

The Map is an actual scan instead of the photo currently in the collection. You can see the seems where the final document was put together out of a few different scans. But i still think it is of overall higher quality than the current version.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I found higher quality scans of

- [ ] Map
- [ ] Errata, Addenda, & Miscellanea

and 

- [ ] Catalog
- [ ] Ad
- [ ] Registration Card

Added to the github folder.

**Comment by exoscoriae** [comment]
added
