### ISSUE TITLE
Clonk (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3897]
Another game with sound issues. This time we need to:

Set cycles lower, I used cycles=20000. The current cycles=max prevents sound initialising even when the other steps are done.

Set sbtype=sb2

Move a copy of ct-voice.drv specific to the sound card and irq used into the game folder and rerun the games setup. Ive found the needed driver and done the setup if you extract this zip into the game folder [clonk.zip](https://github.com/exoscoriae/eXoDOS/files/8798429/clonk.zip).

**Comment by exoscoriae** [comment]
made changes above. did not test
