### ISSUE TITLE
Clonk 3 - Radikal (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3899]
This game has sound, but according to the games internal documentation there is better quality with the "ct-voice.drv" method vs the current "timer" method. There is also the ability to have svga title screen which is not currently enabled. To action:

Set sbtype=sb2

Move a copy of ct-voice.drv specific to the sound card and irq used into the game folder and rerun the games setup. Ive found the needed driver and done the setup (including the svga title screen option) if you extract this zip into the game folder [clonk3.zip](https://github.com/exoscoriae/eXoDOS/files/8798714/clonk3.zip)

**Comment by exoscoriae** [comment]
suggested changes made
