### ISSUE TITLE
Clonk APE (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3900]
This game has sound, but according to the games internal documentation there is better quality with the "ct-voice.drv" method vs the current "timer" method. The game cycles are also too fast in gameplay. To action:

Set sbtype=sb2

Set cycles=10000

Move a copy of ct-voice.drv specific to the sound card and irq used into the game folder and rerun the games setup. Ive found the needed driver and done the setup if you extract this zip into the game folder [clonkape.zip](https://github.com/exoscoriae/eXoDOS/files/8798670/clonkape.zip)

**Comment by exoscoriae** [comment]
I am hearing nothing after making the above changes.

however if I go to options it plays the test sound and shows everything correctly.
![image](https://user-images.githubusercontent.com/8557582/171234902-e2ccb1e0-4587-45bc-ab17-5a391dee65ae.png)

I assume I just didn't play long enough to get a sound and there is no music?
