### ISSUE TITLE
Columns (1993) (Kernick Mock)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3902]
This game isnt in the pack yet but is part of the TDC collection so will probably be added soon. It was on the list of ct-voice.drv games Im looking over so I gave it a go. 

Found that besides running setup.exe to configure the sound card you need to set cycles around 15000 or the sbfmdrv.com will fail to initialise properly.

**Comment by exoscoriae** [comment]
added

**Comment by Python-Exoproject** [comment]
Music still not working. You need to execute columns.bat instead of colgame.exe

**Comment by exoscoriae** [comment]
thanks!
