### ISSUE TITLE
Conquest of Japan (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3903]
Stumbled upon another that uses what I think is Adlib DAC. Switch to X to get correct sounds when battles start. As switching to X also set fullresolution=desktop

**Comment by exoscoriae** [comment]
done

**Comment by Python-Exoproject** [comment]
You've accidentally changed fullscreen=false to fullscreen=desktop. Change this back and instead set fullresolution=0x0 to fullresolution=desktop

**Comment by exoscoriae** [comment]
fixed
