### ISSUE TITLE
Diamond Peter (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3906]
Game was defaulting to Adlib with PC Speaker for some fx instead of Sound Blaster due to CT-VOICE.DRV issue.

I couldnt get the drv file that came with the game working, but if you use the one in this zip ([CT-VOICE.zip](https://github.com/exoscoriae/eXoDOS/files/8806250/CT-VOICE.zip)) to replace the games copy and add to the conf sbtype=sb2 it will work as it should.

Also the games cycles are too fast, you cant help but blow yourself up when you drop a stick of dynamite. I reduced to 700 and it was ok, though the intro is a bit slow

**Comment by exoscoriae** [comment]
set to 900 for now. not sure how to handle it.

**Comment by Python-Exoproject** [comment]
I see what you mean about the water. Seems to be another of those games that needs one speed for one section of gameplay and another speed for the rest. Might be worth setting up a cycleup\cycledown value that increases\decreases to a usable speed when needed and add a user note to press ctrl-f12 when the game seems slow and ctrl-f11 when it seems fast?

**Comment by exoscoriae** [comment]
added note and cycle definitions
