### ISSUE TITLE
Dragon Ball (1993) (Agustinus Nalwan)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3907]
This game isnt in the pack yet but is part of the TDC collection so will probably be added soon. It was on the list of ct-voice.drv games Im looking over so I gave it a go.

Found that for sound to work in the game instead of causing a freeze you need to add "set sound=." after the mount and drive change in autoexec of conf, IE:

mount c .\eXoDOS\DBall
c:
set sound=.

**Comment by exoscoriae** [comment]
added
