### ISSUE TITLE
Night with Beverely, A (2000)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3911]
I believe the title of the game Night with Beverely, A (2000) is incorrect. According to the screenshots her name is spelt Beverly without the extra "e" and according to the game intro page seen here:
![2022-05-30 19_08_39-Window](https://user-images.githubusercontent.com/52749806/171416154-99a33ceb-c8b1-4d7a-9011-fb30be077a34.png)

**Comment by exoscoriae** [comment]
fixed
