### ISSUE TITLE
Blake Stone -  Aliens of Gold (1993) & Blake Stone - Planet Strike (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3920]
User Syntax_X has requested\suggested we add the debug flag to the games launch so that debug codes are usable in the game. To do this all we need to do is change the launch to "@call bstone powerball" or "@call planet powerball". This would have no effect on players who do not wish to use the debug mode as in addition to launching with the flag you need to press both shift keys at the correct moment during game boot. More info can be found here: https://legacy.3drealms.com/cheat/blakestone.html

**Comment by exoscoriae** [comment]
added command line parameter.

also added the cheat information from the above URL as an extra for both games
