### ISSUE TITLE
Walls of Bratock, The (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3921]
FX in this game are not currently working.

There are currently two different versions of CT-VOICE in three different locations in the game folders. I couldnt get sound working properly with these, but did manage to do so with the files in [Bratock.zip](https://github.com/exoscoriae/eXoDOS/files/8825333/Bratock.zip). Extract these into the \exodos\bratock\bratock folder. Delete the \exodos\bratock\sb folder and the .com and .drv file in the root \exodos\bratock\ folder as they are not used in my setup and just confuse things.

Edit the conf to have sbtype=sbpro2 and in autoexec change it to:

cd ..
cd ..
mount c .\eXoDOS\bratock
c:
cls
cd bratock
SBFMDRV
set sound=c:\bratock
bratock

Now that the SB folder and files in the root \bratock folder are gone you could actually move the game up one level and get rid of the \bratock\bratock\ subfolder. If you do so dont forget to tweak the conf autoexec to "set sound=c:\" and delete the "cd bratock" line.

**Comment by exoscoriae** [comment]
I did what was mentioned above.

Made a guy and walked around. Never heard any fx though. Maybe I didn't play long enough or know how to play it correctly.
