### ISSUE TITLE
Flame Storm (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3922]
This game can import characters from the first game, "Walls of Bratock, The (1993)". The instructions according to the "transfer character" screen:

![image](https://user-images.githubusercontent.com/67406191/171667894-96d94587-196a-4439-a1d3-a4fc5a698eeb.png)

I changed the mount for Flame Storm to "mount c .\eXoDOS\" so that if Bratock was installed you can access the folder from c:\, created a character in Bratock, and ran transfer from Flame Storm. It defaults as c:\Bratock as the search path to find a savegame (which is convenient if youve actioned #3921 and moved the game up a level) and worked with no problems. Ran Flame Storm and used Journey Onward to confirm my character successfully transferred.

**Comment by exoscoriae** [comment]
added save game transfer option

**Comment by Python-Exoproject** [comment]
![image](https://user-images.githubusercontent.com/67406191/176698965-7beec5e4-cbb7-4e4e-99c0-1a89292abe75.png)

Type in the sentance "...you may start Flame Storm and choose *Jounrey* Onward."

**Comment by exoscoriae** [comment]
fixed
