### ISSUE TITLE
JimBall v1.5 (1994) (New Wave Media)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3929]
This game isnt in the pack yet but is part of the TDC collection so will probably be added soon. It was on the list of ct-voice.drv games Im looking over so I gave it a go.

Found that the CT-VOICE.DRV file included with the game is a v3.x copy which I couldnt get working. This copy ([CT-VOICE.zip](https://github.com/exoscoriae/eXoDOS/files/8838232/CT-VOICE.zip)) works, extract to game folder and set sbtype=sb2

**Comment by exoscoriae** [comment]
added
