### ISSUE TITLE
Kahjar - The Bratockian Saga Part III (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3930]
Two things with this one:

First, is it called "Kahjar - The Bratockian Saga Part III" or "The First City of Alliance"? All title screens in the game and online presence I found named it the later?

Second, this game is a prototype and is barely playable. The intro works, but you cant complete creating a character to start a game. You can press "Resume Your Quest" to start with the default character with no name though. But when you get into the game its obviously a developers level with armour and weapons all over the place and console info at the top of the screen. Most of the buttons on the right interface dont actually do anything either. Might be worth at least a user warning?

**Comment by SmilingSpectre** [comment]
Both names are right. Kahjar is initial name, changed during development to the First City. And it seems it was never finished.

**Comment by exoscoriae** [comment]
added not. filed it as "unreleased"
