### ISSUE TITLE
Labrynth (1994) (Nathan Cope, Lunatic Fringe)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3932]
This game isnt in the pack yet but is part of the TDC collection so will probably be added soon. It was on the list of ct-voice.drv games Im looking over so I gave it a go.

Found that to get sound working properly in this game you need to set sbtype=sbpro1

Cycles will also need to be reduced so that you have time to react to change your characters movement around the maze

**Comment by exoscoriae** [comment]
added and set up
