### ISSUE TITLE
Legend of the Silver Talisman (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3933]
Cycles are set to 8000 but I think thats too fast. Menus can sometimes skip the intended option due to speed of selector movement and in game the fx are more consistent at lower speeds and the bad guys move at a more reasonable pace.

**Comment by exoscoriae** [comment]
as the game is 1996, I am reluctant to go too low. I tried 4k and it seemed good. also switched to ece and I am getting less flickering.
