### ISSUE TITLE
Living Ball (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3936]
Found another game that has a bad CD rip with no CD Audio in our collection. Good copy can be found: https://www.old-games.ru/game/download/3412.html

Not sure how it was missed when we went over all these as oldgames has it clearly marked as "CD Audio" and I checked over every game marked as such. Maybe a new update to their entry? Makes me wonder how many more are hidden away in the collection like this.

Once fixed I think the CD Audio overpowers the fx too much and that we should add "mixer cdaudio 40" to the autoexec section of the conf. For this game this also necessitates adding "sbmixer=false" under [sblaster]

One other point to consider is that once the CD music is in you can no longer hear the SB\MT32 bits of music that play when a table opens or the ball goes out. I feel we cant just raise the volume of these to be heard as they play at the same time as the CD track is still playing and clash. Im thinking we can either:

1. Run setsound.exe, kill the FM sound choice so there is no clash, and remove all user sound choices, or
2. Do as above but as a CD Audio third sound choice?

Or something else you come up with?

**Comment by SmilingSpectre** [comment]
It says "Added from TDC in 03.05.2020". Of course, there can be more like this. And I'll check TDC for them. But later. :)
