### ISSUE TITLE
Match Day Manager (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3937]
Two things for this one.

1. The mouse wont lock unless you do it manually with ctrl-f10
2. It has a copy of ctvoice and some .voc files so I know it has sound, all be it minor as the voc files are just the sound of a crowd cheer and the ball getting kicked, but I cant get it working with my usual methods. I think the place to hear the sounds is after you cycle through the week and get to match day where a snippet of a game is shown.

**Comment by exoscoriae** [comment]
fixed mouse issue

**Comment by Python-Exoproject** [comment]
There is a game that looks to use the same engine, "Match of the Day Bundesliga (1994)", that also has the same Audio folder with the same named driver and has sound (including music even though its dated with a year earlier, could our copy of Match Day Manager (1995) be incomplete?). I tried using that copy of ctvoice with the sbtype from the Match of the Day Bundesliga (1994) conf, but still no joy.

**Comment by exoscoriae** [comment]
no luck.

tried every sbtype
tried different ct-voice drivers
placed them in various folders (c:\, audio) and then used SET SOUND to point to them.

The fact the game doesn't even ask about audio up front is concerning.

**Comment by exoscoriae** [comment]
the game has been fixed thanks to a fixed exe from ripsaw
