### ISSUE TITLE
NASCAR Racing (1994)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3941]
I found a 

- [ ] manual

This one is the original manual from when it was published by Virgin Interactive. It has much more content then the current one, which is  from a Sierra published version. The quality is not the best so it might be useful to keep both.

Added to the github folder.

**Comment by SmilingSpectre** [comment]
I uploaded the better scans of that.

**Comment by exoscoriae** [comment]
used scans to generate a pdf
