### ISSUE TITLE
NASCAR Racing (1994)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3942]
I found a

- [x] Keyboard Reference Guide

It is only a photo unfortunately but better than nothing.

Added to the github folder.

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] Installation guide
- [ ] Keyboard Reference Guide (quality upgrade, current is a photo)
- [ ] Addendum
- [ ] Technical and Customer Support Note
- [ ] Track Pack manual

**Comment by exoscoriae** [comment]
added. except keyboard reference guide. existing one is smoother and larger.
