### ISSUE TITLE
Shadows of Mordor (1987)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3948]
Playing Shadows of Mordor (1987) the cycles seem to be set too high. You are supposed to be able to "hit smeagol with sword" when he shows up (seen in the screenshot as well) but at the 3000 cycles it's so fast you cannot perform the action. Dropping cycles to about 900 seemed to be at a speed which seems "normal"

**Comment by exoscoriae** [comment]
dropped to 900. thankj
