### ISSUE TITLE
Snooper Troopers Case 2 (1982)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3949]
Snooper Troopers Case 2 (1982) gets a file not found error message when trying to start the game and selecting the agent #.

https://discord.com/channels/454359114601201666/467028238687010826/985590396744773682
@SmilingSpectre discovered that the agent files in the directory need to be renamed without a space. ie "AGENT1" AND "AGENT2"

**Comment by exoscoriae** [comment]
bumped part 1 to 33 cycles. seemed ok?

Part 2 was set to 900 cycles, and it ran way too fast for me. dropped it to 600. still seems a bit fast, but playable.

Decided to set both to 500

Renamed agent files.

**Comment by Python-Exoproject** [comment]
Something screwy seems to be going on then. For me 500 is fine for Case 1, but Case 2 runs like a snail in the car. Text seems fine though. Here is a zip with capture of both case 1 & 2 running at 500 cycles for me.
[capture.zip](https://github.com/exoscoriae/eXoDOS/files/10084433/capture.zip)

**Comment by exoscoriae** [comment]
set case 2 to 750.
