### ISSUE TITLE
Midway (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3952]
This game allows selection of SB or SB Pro on startup. SB works fine, but if you select SB Pro it gives a message about "no auxiliary driver". 

I didnt figure out how to get around the issue so posted it here, but as the original SB option kicks in once the error has happened its not a major issue if we cant solve it.

**Comment by SmilingSpectre** [comment]
Our version is crippled, just as TDC (it's mostly identical - we have CT-VOICE.DRV, they aren't). Too many files seems missing (I counted at least three), and game in whole works suspiciously. For example, it have 2 title files, TITLE16.PCX and TITLE256.PCX, but only first is activated always.

File that is missing is AUXDRV.DRV, but I have no idea where you must place it and if game touch it anyway.

**Comment by Python-Exoproject** [comment]
Thanks @SmilingSpectre that was the clue I needed. To get SB Pro sound working add [AUXDRV.zip](https://github.com/exoscoriae/eXoDOS/files/8909019/AUXDRV.zip) to the game folder.

In regards to spectres suspicion of an incomplete game, I agree and also think we should track this one down. Having a 256 colour title screen file that isnt used needs investigating.

**Comment by Python-Exoproject** [comment]
Here is a copy of the game provided by agathosdaimon: [MIDWAY.zip](https://github.com/exoscoriae/eXoDOS/files/8909840/MIDWAY.zip). Add the ct-voice.drv from our current copy and the auxdrv from the above post and all should be good to go. This CD version doesnt even need cracking

**Comment by exoscoriae** [comment]
replaced with clean version. added recommended files. confirmed sound
