### ISSUE TITLE
Search for Freedom (1994) (Howard Feldman)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3960]
This game isnt in the pack yet but is part of the TDC collection so will probably be added soon. It was on the list of ct-voice.drv games Im looking over so I gave it a go.

Found that to get sound fx working properly in this game you first need to run "sound" and setup the soundblaster option. Then replace the games copy of CT-VOICE with this one [CT-VOICE.zip](https://github.com/exoscoriae/eXoDOS/files/8919890/CT-VOICE.zip), and set the conf to use sbtype=sbpro2.

Another issue with the copy of the game I tested from TDC 18 was that the game isnt fully cracked yet. The main exe "TMAIN.EXE" seems to be cracked ok, but the combat exe "CMBT.EXE" crashes out with a copy protection warning when its called. Ive pinged @SmilingSpectre about this so hopefully he can either find a fully cracked copy or ping someone at TDC to finish the game crack.

**Comment by exoscoriae** [comment]
added v1.3

author is still selling the game though
