### ISSUE TITLE
Solder Runner (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3961]
To get SB sound working (title screen voice etc) replace current ct-voice with this one [CT-VOICE.zip](https://github.com/exoscoriae/eXoDOS/files/8927673/CT-VOICE.zip) and set conf to use irq=5 and sbtype=sbpro2

This game is also set to max cycles which is way to fast, you cant even see shots go across the screen. Auto or a bit faster seems to work

**Comment by exoscoriae** [comment]
fixed
