### ISSUE TITLE
Space Havoc 2 (1996) (Nicholas Turner)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3962]
This game isnt in the pack yet but is part of the TDC collection so will probably be added soon. It was on the list of ct-voice.drv games Im looking over so I gave it a go.

To get SB sound working replace current ct-voice with this one [CT-VOICE.zip](https://github.com/exoscoriae/eXoDOS/files/8927775/CT-VOICE.zip) and set conf to use irq=5 and sbtype=sbpro2

**Comment by exoscoriae** [comment]
added
