### ISSUE TITLE
Tank For Two (1994) (Steven Atkinson, David Leadbetter)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3963]
This game isnt in the pack yet but is part of the TDC collection so will probably be added soon. It was on the list of ct-voice.drv games Im looking over so I gave it a go.

To get SB working properly run setup, select sound dropdown, select enable, select save from the first dropdown. Now set the conf for sbtype=sb2

**Comment by exoscoriae** [comment]
added game
