### ISSUE TITLE
Tank Regime (1995) (Roger Rhudy)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3964]
This game is on my list of CT-VOICE.DRV games to investigate but isnt in the collection or TDC 18. I found a copy at https://archive.org/details/tank-regime-pc which I have also brought to Spectres attention.

For the sound to work you will need to add [CT-VOICE.zip](https://github.com/exoscoriae/eXoDOS/files/8928477/CT-VOICE.zip) to the game folder and add sbtype=sbpro2 to the conf

**Comment by exoscoriae** [comment]
added

**Comment by Python-Exoproject** [comment]
Found a file I hadnt seen before in the !dos\TankRegi\ folder called "eXoLBpm.exe"?
