### ISSUE TITLE
Descent (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3974]
Ive just noticed that this version of the game (not the anniversary edition) has been setup to use irq 5 in the games SB16 and SC55 setups even though the conf is still using the default irq7. Doesnt seem to be causing any issues but its not great to have the game setup to use an irq different to the one actually being used by dosbox. I suggest rerunning game setup for both SC55 and SB16 to fix the IRQ selected.

**Comment by exoscoriae** [comment]
edited the cfg files by hand.
