### ISSUE TITLE
Amazon - Guardians of Eden (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3976]
From @SmilingSpectre:

1. SB sound has two options in the selection: FM and OPL. While producing identical sound for almost all SB cards, it strikingly different for SBPRO1. Namely, OPL gives you stereo. 
2. There are hint levels that tuned in .CFG. And our version is sealed for Level 1 (from 3). I recommend to set it for 3 for both sound options - you can skip the hints if you want, and you are not forced to get L2 and L3 ones - but you cannot get what isn't available.

**Comment by exoscoriae** [comment]
great work spectre. thanks
