### ISSUE TITLE
Aliens (1996) (Christoph Roeschter)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3977]
This game isnt in the pack yet but is part of the TDC collection so will probably be added soon. It was on the list of ct-voice.drv games Im looking over so I gave it a go.

To get sound in this game you need to choose between music or fx. Run game with music by using "amusic.bat" to start, for fx use "aliens sound".

As the amusic.bat is just a bat to run the mod player "DMP", select the mod to be played, and launch the game, im thinking if we can find a mod player that will play the games mod as a TSR program we could then run "aliens sound" and get both. I tried using DMP but it couldnt handle the space. I also tried using a new bat file that runs "aliens sound" and calling that from amusic.bat but as soon as the new bat was executed it killed the mod playing.

**Comment by exoscoriae** [comment]
added game. bleh

I played around with trying to convert a batch file that called "aliens sound" into a exe file, but I couldn't find an old utility that could keep the new exe as dos compatible.

Ultimately, this game blows and I'm not super interested in spending a lot of time trying to solve something the authot should have done originally. I put in a choice for sound or music.
