### ISSUE TITLE
Operation Cleaner (1998)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3978]
This game is supposed to have explosion sounds when you blow the dynamite but all the things ive tried to get CT-VOICE.DRV working have failed.

To get the where I think the explosions take place, Begin Game and follow allsteps required to get into gameplay. When you have a big blue screen click the button with all the icons of money, bulldozers, etc. Now select Customers, then accept offer. Use the minimap in the top right to view where the building is to blow up, select the button with the green arrow on the same line that says "1/50", Select the button with a plus on it a number of times, Click a few places on the building to place explosives, and lastly click the button with the green tick a number of times until the explosives go off.

**Comment by SmilingSpectre** [comment]
IRQ=5

**Comment by Python-Exoproject** [comment]
What setup you using? Is it the WIP version in exodos? Trying IRQ=5 is the first thing I did, and it didnt work for me

**Comment by SmilingSpectre** [comment]
Hmm. Actually, I used daum, as it's simplest with changing settings on the fly. But let's see...

Hmm, results are weird.

1. Even with Daum current CT-VOICE.DRV v3.07 works once in a blue moon. I wasn't able to decipher how to activate it reliably.
2. v3.05 works always. With any cycles. In Daum.
3. After some testing I discovered that I cannot repeat it in eXoDOS. Ok, I mimic my daum setting - success!
4. But not in the default dosbox *sigh* ECE seems working. As anything else too.

So conclusions:

1. You need IRQ=5.
2. You need CT-VOICE.DRV v.3.05 (uploaded) [CT-VOICE3.05.ZIP](https://github.com/exoscoriae/eXoDOS/files/8974340/CT-VOICE3.05.ZIP)
3. You need ECE.
4. You need to mount the dir as root. When data path in main menu looks like \DATA, sound works (there is croaking right at the newspaper page after start). If it's \OPCLEANR\DATA it isn't.

**Comment by Python-Exoproject** [comment]
Thanks @SmilingSpectre youve helped me isolate the issue. Ok @exoscoriae whats happening here is that the game requires SB16 and a CT-VOICE.DRV for that card. Only v3 and higher of CT-VOICE.DRV are from the era of SB16. There is however an issue with vanilla dosbox and v3 drivers so I have been sticking to v2 as until now there had been no reason to use v3. ECE and Daum do not share this issue with v3 drivers though so now that Spectre has identified the issue the solution is simple.

Switch to ECE and either use the driver Spectre attached above with IRQ=5 or use this one which I patched to work with IRQ 7
[CT-VOICE.zip](https://github.com/exoscoriae/eXoDOS/files/8976629/CT-VOICE.zip). Then run the games setup again, if successful you should here a croak sound when the sound setup is completed. I did not need to change the mount, for me it worked as it currently is.

Another suggestion I have while the game is being worked on is to change cycles=max to cycles=10000

**Comment by exoscoriae** [comment]
nice work guys

**Comment by Python-Exoproject** [comment]
dosbox.txt has a space in the path for this game

**Comment by exoscoriae** [comment]
repaired
