### ISSUE TITLE
Trials of Odysseus Kent, The (2002)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3980]
Aspect ratio is off when you run and have chosen to have it corrected. Please add "ASPECT FALSE" to the conf autoexec section.

In addition once it is corrected the playable window is very small even if I've chosen to have it at large/medium. Something else might be off?

**Comment by exoscoriae** [comment]
window scales ok for me in the wip. maybe it was an issue with the old setup?

added aspect false to the conf
