### ISSUE TITLE
Cardinal of the Kremlin, The (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3984]
Currently the game uses PC Speaker but it can do Adlib\SB. Just add "sound.com" to the autoexec section before the game launches. There is also a cok.bat that executes "key.com" and "ck s". Didnt seem to change anything if I used this or the current ck.exe in the dosbox conf but might be worth switching just in case?

**Comment by exoscoriae** [comment]
modified. nice catch
