### ISSUE TITLE
Universe (1987)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3985]
Universe (1987) description notes are a copy from Universe (1994) which are incorrect. Suggest changing to the following for Universe (1987) (borrowed from Moby)....

Universe is a complex space exploration game, reminiscent of the original Traveller hard science fiction pen-and-paper role-playing game. It is based in the same fictional universe as Omnitrend's later Breach and Rules of Engagement series. Running in the same vein as games like Elite, Starflight, and SunDog: Frozen Legacy, its gameplay involves freelance space exploration, trading, space combat, planetary mining, and other economic activities.

In Universe, you are a new independent starship captain in the Local Group, a cluster of stars colonized by Earth in the relatively near future. Mankind has had the hyperdrive for almost four hundred years, but hyperdrives have ship size and range limitations that effectively prevented exploration and colonization beyond a 40-light-year radius. However, in distant orbit around Tau Ceti, an exploration ship found an enormous alien artifact called the hyperspace booster, which allowed one-way travel at a distance of thousands, rather than tens, of light years. The discovery of the hyperspace booster allowed a great Second Interstellar Expansion, and Axia, a star system specially noted in the hyperspace booster's starmaps, was colonized. The Local Group is the cluster of stars surrounding Axia.

For over two hundred years, Axia has received regular packages from Earth via the hyperspace booster, but the packages mysteriously ceased arriving four months ago. The Local Group, considerably behind Earth technologically, is dependent upon the packages and has its own political and economic problems, so this is a grave problem. Panic is spreading as rumors fly about what happened to Earth.

Recently, Axian Central Educational Institute announced that there is evidence of a second hyperspace booster in the Local Group. You, with your new ship and your enormous new debt, are one of those who hope to find the hyperspace booster and collect on the large reward for it. However, operating a starship is expensive, and you will receive no funding. Thus, you must make your own way however you see fit.

When you begin the game, you must choose the terms of your 300,000-credit mortgage and select a starship hull from various models that differ in size, layout, visibility to other ships (and therefore the likelihood of receiving undesirable attention) and sturdiness. Then, after a copious bit of disk-swapping, you proceed to drydock, where you can equip your ship and place all your ship's parts (hyperdrive, bridge, crew quarters, weapons, shuttles, cryogenic storage, et cetera) in its different sections (each of which has differing capacity and visibility -- this matters when a hostile starship hits you and the game must determine where you got hit and what got damaged).

From there, the Local Group is wide open. Trading, passenger transport, ore mining, smuggling, contract cargo transport, and even piracy (or pirate-hunting) are all lucrative options. The game's complexity shows in the example of mining: you must first equip your ship with ore processors, and, if you want to mine low-tech populated planets, assault capsules. You must also hire sufficient crew to run them all. Then, you must find a planet rich in resources and go into a low orbit around it (plotting an efficient orbit by hand can save energy resources); start the computer's Resource and Amphib Assault software packages (which may necessitate turning off Hyper Navigation or Sub-C Navigation to make space); convert Ore IV to energy to charge up the assault capsules; and launch them. When you have done this, an abstract isometric grid representing the landscape is displayed, with each assault capsule shown with a vertical line extending from it to the landscape representing its altitude. Here, you give them orders as they go down to the planetary surface to secure the area, being careful to scan the landing surface repeatedly to ensure it will support the ore processors (the scanners aren't 100% accurate, and you don't want your landers to sink into a swamp, fall into a thermal vent or tip over on jagged landscape).

Combat is conducted abstractly, in a manner vaguely similar to a strategic board game. If you win this fight and secure the landing sites, you then charge up, crew and launch the ore processors. Once they land (assuming they landed safely), choose which type of ore each one mines, and then let them rip until they run low on energy or until they are too damaged to continue, at which time you launch them and they return to the ship with their valuable cargo. If you've done well, you've got a substantial load of precious ore you can sell at the next starport.

**Comment by exoscoriae** [comment]
this was already fixed in the WIP....
