### ISSUE TITLE
Fiendish Freddy's Big Top O' Fun (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3986]
This game is on PC Speaker at the moment but can support adlib\sb. Put this copy of sound.com into the game folder [SOUND.zip](https://github.com/exoscoriae/eXoDOS/files/8977234/SOUND.zip), load sound.com in the autoexec section of the conf before launching the game and use "freddy -adlib" to start the game.

Also it looks like TDC have a cleaner version of the crack that doesnt pop up the "cracked by" screen

**Comment by exoscoriae** [comment]
replaced with cleaner copy. added sound stuff.
