### ISSUE TITLE
Gunblaze (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3987]
Not sure how this one got set to 30000 cycles but its way to fast. I think 2500 works well

**Comment by exoscoriae** [comment]
switched to 2,500.

why is this game even in the pack... a chinese rpg???

**Comment by exoscoriae** [comment]
eh. it was a bit sluggish. bumping to at least 3000, the normal amount. 1994 is usually closer to 12k

**Comment by Python-Exoproject** [comment]
I agree, feel free to remove this one and mark it foreign, no idea what is happening in it

**Comment by exoscoriae** [comment]
really not sure what to do here.

I hate to remove a commercial game. If we had a chinese pack in the works it would be an easy decision to kick it over to that. Guess I'll leave it alone for now. especially since it is a moby games list.
