### ISSUE TITLE
Inter-Stellar Wars (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3988]
This game currently has no sound but does have an option to activate it. Run the bat file "iswa" or "iswh" (one tries to load the sound file into high memory) to activate.

The issue is though that while this gets sound working, once you start a game and select the bottom left icon of the command bar (titled Comm) the game dumps out with an insufficient memory error. Ive tried variations on loadfix, ems, memory allocated in conf, and the new dosbox x version that allows loadhigh to actually work - all with no luck. Thinking it might need true DOS? Hope you have better luck

**Comment by exoscoriae** [comment]
fixed
