### ISSUE TITLE
Once Upon a Time... Volume I\II\III

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#3992]
These games install with digipak sound drivers and the installer asks you to run setdig to setup sound, but the game seems to always give pc speaker when loaded no matter the sound driver selected.

**Comment by exoscoriae** [comment]
setdig or for digital sound.  the music is only in pc speaker, but if you go into the game and "draw" an object, you can press F2 to hear it said. If you don't have a digital card setup, you won't hear anything.

So it is working as it should
