### ISSUE TITLE
Midwinter (1990)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#3997]
I found a Version with added CGA and EGA support. (The Floppys are from [Good Old Days](https://archive.org/details/001622-Midwinter))
I took the cracked .exe from the version in eXoDOS and it seems to work fine.

[Midwinter.zip](https://github.com/exoscoriae/eXoDOS/files/9014287/Midwinter.zip)

**Comment by exoscoriae** [comment]
this shouldn't be in this project. This should be filed with bugs.

**Comment by exoscoriae** [comment]
replaced the old copy

**Comment by Python-Exoproject** [comment]
Bad crack. 

Any time I click on the icon with a picture of the island I just get a black screen. Replaced the cracked exe with the original and the map appeared as it should.

**Comment by exoscoriae** [comment]
ok. so it still needs to be cracked then?

**Comment by exoscoriae** [comment]
fresh crack applied. I was able to click the island and ski around

**Comment by Python-Exoproject** [comment]
Now that I can get into gameplay, does it seem a bit fast to you? I tried "Snipe" mode where (I think) you need to shoot the missiles down and at 3000 cycles it was to fast. I tried 1500 and it seemed reasonable, though I still sucked

**Comment by exoscoriae** [comment]
dropped it to 1500. did not test, as this isn't really my kind of game
