### ISSUE TITLE
Treehouse Truants (1994)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#3999]
Trying to play Treehouse Truants (1994) BBS game but when I try to "(E)nter the game" it quits noting that "Player Data File NOT Found". I had to manually launch THTEDIT.EXE first and choose the option to Reset the Game which recreates this file. That then allowed me to run and enter the game as expected. I believe our archived version should be replaced with one where the game has been reset already through the editor.

Reproduced in 5.1 and WIP branch.

**Comment by exoscoriae** [comment]
fixed

**Comment by Python-Exoproject** [comment]
According to the user note:

"You may need to ruin setup the first..."

Might need to correct the typo unless we really do need to ruin the setup :-)

**Comment by exoscoriae** [comment]
thanks =)
