### ISSUE TITLE
Issue with new user choice method

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4000]
As mentioned in #3821:

There is a big issue for all the games setup using the new user choice method. When the user agrees with the existing choices instead of going through the process of selecting them and commands contained in the code for these choices are not executed. This means programs like sound.com are not executed and also means that no "CONFIG" settings are changed. This results in all SC55 not using mididevice=fluidsnyth, or as another example Game Blaster choices in all these games not working as "CONFIG -set "sbtype=gb"" isnt executed. Some extra "If Exist" lines should fix it up. 

Games that look to be affected are:

Freddy Pharkas Frontier Pharmacist (1993)
Game of Harmony, The (1990)
King's Quest I - Quest for the Crown SCI (1990)
Police Quest 1 - In Pursuit of the Death Angel SCI (1990)
Quest for Glory I - So You Want to be a Hero SCI (1992)
Space Quest I - The Sarien Encounter SCI (1991)

While looking at the games using a system with .SEL files I also noticed that for Clyde's Revenge (1995): 

In the ":same" section the GUS.SEL line is setting mididevice=fluidsynth. 

Also this game uses this method for the same reason Hocus Pocus does, but doesnt have a comment to explain why a user might want to pick the "Same" option like Hocus Pocus. Might be worth adding?

**Comment by exoscoriae** [comment]
this should be super easy to fix. just redirect :launch to check the sel of the sound card and point it to that sections launcher.

eg: if %sound% = MT-32 goto :mt32

**Comment by exoscoriae** [comment]
Freddy Pharkas Frontier Pharmacist (1993)
Game of Harmony, The (1990)
King's Quest I - Quest for the Crown SCI (1990)
Police Quest 1 - In Pursuit of the Death Angel SCI (1990)
Quest for Glory I - So You Want to be a Hero SCI (1992)
Space Quest I - The Sarien Encounter SCI (1991)

have all been fixed

Clyde's Revenge was also fixed with a note added.
