### ISSUE TITLE
Bridge Olympiad (1994)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#4003]
After the round of "betting" as soon as you click continue the game crashes to the DOS prompt. Removing the "exit" command reveals no further information.
Tested on 5.1 and WIP branch.

https://user-images.githubusercontent.com/52749806/177362740-77166edc-72fa-4cfb-8845-d0157331a0e0.mp4

**Comment by SmilingSpectre** [comment]
Hm. What was _before_ that? Because I played both tournament and some "rubber" game, without problems. It asked once the protection question, but "enter" totally worked.

**Comment by matthew-goddard** [comment]
Seems to be related to copy protection. Hitting only enter at the prompt plays normally. Providing any other answer seems to quit the game at the described time. As hitting only enter is a standard bypass for the copy protection marking as not fixing and closing.
