### ISSUE TITLE
Fluid.Gain value

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4004]
We noticed years ago that ECE uses a default fluid.gain of .6 and that at the time other forks did as well. After numerous games having fluidsynth output being way to high compared to the SB FX I did some research and found that fluidsynth itself actually uses a default of .2 for the gain and noticed that some forks had changed to this value as well. We discussed and decided to use .2 as our default value from that point on.

It seems however that at some point this setting was lost from our conf template and as a result many of our games that use fluidsynth are using that .6 ECE default value still.

Here is a list of all confs in exodos that do have a fluid.gain line and the value that it currently has: [Confs_with_current_FluidGain_setting.xlsx](https://github.com/exoscoriae/eXoDOS/files/9047650/Confs_with_current_FluidGain_setting.xlsx)

To fix this we will need to change any in this list that have a value of .6 to .2 and then do a mass insert to all confs in exodos that have a [midi] line to add the line "fluid.gain=.2". After that we will have those listed 72 confs with two fluid.gain lines so as a last step we will need to clean up those 72 to remove the new entry.

**Comment by exoscoriae** [comment]
why not just set it in the options conf, which will override the individual game conf files?

Should any games *not* obey the default value? If so, we obviously can't use that approach. I see Jurassic Park is set to 4.5 and Dark Legions is set to 3. These are odd values. Are these purposeful values from our side? If so, we wouldn't want to over write them.

But what you are proposing above is that *any* conf that has a midi section be set to .2.... in which case, we should just set it in the global options were it will be the defacto value.

**Comment by Python-Exoproject** [comment]
We only want to change the games that are using .6 to .2, so like you pointed out yourself we cant use the options.conf as that would overwrite games that we have set values for like Jurassic Park.

Maybe we could set the default value in options.conf, and for any in the list I provided that arent on manually set values (IE any that arent .2 or .6) we set the value in the games run.bat like we do for "mididevice"?

**Comment by exoscoriae** [comment]
changed games that were set to 0.6 down to 0.2

added 
`[midi]
fluid.gain            = .2`

To options.conf
