### ISSUE TITLE
Superhero League of Hoboken (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4006]
Issue discoverd with Superhero League of Hoboken (1994) songs on vogons (https://www.vogons.org/viewtopic.php?f=33&t=88797) reported on discord by RealNC. Ripsaw has a fix which RealNC has implemented for the version of the game we have in the collection along with his own fix for the third song ([HOBO_01.zip](https://github.com/exoscoriae/eXoDOS/files/9077474/HOBO_01.zip)). Some information below:

Ripsaw: 
The size of the MUS file, and therefore the offsets where changes are to be made, vary from one version to another. So, instead of mentioning specific offsets, I will describe how to locate the offsets using a hex editor. But first, some description of what the hacking actually does.

The three affected MID files are named "Fight 1", "Fight 2", and "Fight 3". The first two have 12 tracks, the third has 13 tracks. There are four tracks of copyrite (sic) message at the end of the MID files which can be effectively discarded by reducing the track count in the MID file header by four. Reducing the first two MID files to 8 tracks brings them just under the limit of what the game will play. However, the third MID file with 9 tracks will still have one track too many, and if you go ahead and reduce the track count to 8 then the percussion track will not be played. In order to fully fix the third MID file, it would be necessary to merge at least two of its tracks together, which does not appear to be a trivial hack.

To perform the hack, search for the word "Fight" in the .MUS file, for which only three instances should be found. If you go backward 15 bytes from the "F" you will find an 0Ch byte (0Dh for "Fight 3") that you can change to 08h in order to fix that MID file; but as I mentioned above, fixing "Fight 3" in the described manner will lose the drum track.

RealNC:
[ripsaw] hex edit that discards the extra tracks works.
I'm currently trying a different method of fixing the third track.

Success! The game now doesn't hang and it plays that music track.

You won't believe the hoops I had to jump through. I've been at it for like 4 hours
Here is the updated version. All music tracks now work.

The way I fixed it is by merging the MIDI events from track 8, which contains only 3 notes and 16 events, into track 6, which didn't play any notes at the time the other track did. So track 6 now switches the instrument to what track 8 wanted, plays the note, then switches back to the instrument track 6 normally plays. I then deleted track 8. I kept the copyright tracks intact instead of removing them and simply hex edited the track count to 8 so they get ignored.

It sounds exactly the same as when playing the original MIDI file in Munt's MIDI player.

BUT, the resulting midi file was too large, because I had to use another MIDI editor to do it instead of QTractor. And that other editor generated MIDI data that is too large. It doesn't optimize the MIDI data. So I had to find and download an old DOS utility called MIDCOMPR.EXE, and run it in dosbox on the MIDI file. This reduced the size so it fits into the HOBO_01.MUS file.
QTractor couldn't cope with the instrument switching of track 6.

**Comment by realnc** [comment]
Please delete this. I don't want to share this file anymore with you people. You're horrible, banning others for no reason whatsoever.
