### ISSUE TITLE
Legend Entertainment MT32 Issue

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4008]
RealNC has brought to our attention that for most Legend Entertainment games using MT-32 there is an issue with the tempo.

It was discussed in full here https://www.vogons.org/viewtopic.php?f=33&t=46178 and here is a copy of ripsaws TSR [LEGMPU.zip](https://github.com/exoscoriae/eXoDOS/files/9079368/LEGMPU.zip). Four of the exodos games already have the file included but I list below the others from the vogons post that need to be modified.

Games that need to have this TSR loaded in the MT32 section of the run.bat are:

Spellcasting 101 - Sorcerers Get All the Girls (1990)
Spellcasting 201 - The Sorcerers Appliance (1991)
Spellcasting 301 - Spring Break (1992)
Timequest (1991)
Companions of Xanth (1993)

**Comment by exoscoriae** [comment]
added to the above games and their run.bat files

**Comment by Python-Exoproject** [comment]
Turns out there is a second step to this fix, according to ripsaw8080 on his original post these games need at least cycles=10000 in order for MT32 tempo to be correct. Some people have recommended 15000 in order to give ripsaws tsr a "safety margin". Your call on which cycles to use, but all the following games need the tweak:

Companions of Xanth (1993)
Eric the Unready (1993)
Gateway (1992)
Gateway 2 - Homeworld (1993)
Spellcasting 101 - Sorcerers Get All the Girls (1990)
Spellcasting 201 - The Sorcerers Appliance (1991)
Spellcasting 301 - Spring Break (1992)
Superhero League of Hoboken (1994)
Timequest (1991)

**Comment by exoscoriae** [comment]
done. thank you

**Comment by Python-Exoproject** [comment]
I think Eric the Unready was missed for cycle fix?

**Comment by exoscoriae** [comment]
set to 12500
