### ISSUE TITLE
Action Fighter (1989) 

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4010]
Smiling Spectre found 

- [x] manual 

it's from kixx release but it has the same content as our current one which is very blurry.
but the current one includes the Poster
I suggest to switch it to extras and set the kixx one as manual 
Smiling Spectre also found a 
- [x] manual (quality upgrade)
for the current version

added both to the github folder

**Comment by exoscoriae** [comment]
added kixx manual as extra.
