### ISSUE TITLE
Ferrari Formula One (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4015]
Smiling Spectre found

- [x] manual

as far as I can tell from ebay the current one is from the atari box, this one is the real DOS manual.

added to the github folder

current Atari manual:
![grafik](https://user-images.githubusercontent.com/67441153/178683679-17aa6b15-b4e7-43da-a599-3f6d11f4f668.png)

new IBM manual:
![grafik](https://user-images.githubusercontent.com/67441153/178683853-c68eecbb-5452-4d11-b00a-aae826cf2f94.png)

**Comment by exoscoriae** [comment]
replaced
