### ISSUE TITLE
Major League Manager (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4024]
not sure about this one ...

Smiling Spectre found

- [x] manual 

for "Pro Manager", a 1984 Avalon Hill Game for DOS. But this one _isn't_ in eXoDOS. according to moby, Spinnaker did a re-release called "Major League Manager" in 1986 which _is_ in eXoDOS.

Not sure if we add an entry for the Avalon Hill version to add the game as it's own game in eXoDOS or if we should add this manual to the Spinnaker game in eXoDOS 
... since I didn't find comparing screenshots and all sources talk about the "same game" with "different publisher" I tend to the latter

added to the github folder

**Comment by SmilingSpectre** [comment]
It's in TDC, and I'll add it then.

**Comment by exoscoriae** [comment]
added
