### ISSUE TITLE
James Clavell's Shogun (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#403]
boxfront and back on page 1 and 2
english manual on pages 5 - 20
carte de garantie (fr) on pages 21 / 22
registration-card on pages 23/24
map on last page

maybe split and add them as extras?

**Comment by Eulisker** [comment]
I split just the manual out of all that. The map and the soul of the samurai is already in and the rest is in french so i opted to leave it out.

Added to the github folder.

**Comment by exoscoriae** [comment]
done
