### ISSUE TITLE
Jinxter (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#405]
it's not the manual but a fake newspaper The Independent Guardian  should be changed to extras

**Comment by SmilingSpectre** [comment]
Wrong. It _is_ manual. Quite plain from p.8 and on.

Still there are some extras too. Uploaded.

**Comment by TimberlAndRE-de** [comment]
added the extra to #725  (memo is already added)
thx for correcting, the issue can be closed then.
