### ISSUE TITLE
DOOM (1993)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4051]
I found the book

- [x] 3D Game Alchemy

It is a guide for editors for the game and has some general info about them. It also contains stuff for Doom II, Heretic and Hexen and should be added to them too.
Added to the github folder.

**Comment by exoscoriae** [comment]
this appears to have had a CD that was distributed with it. Without that CD, is this useful?

**Comment by exoscoriae** [comment]
added as a new game entry
3D Game Alchemy (1996)
