### ISSUE TITLE
Synnergist (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4058]
There is a freeze that happens when the box is opened by the letter opener in the tower block. If you wish to test heres is a save
[Save_-_use_ty_game.zip](https://github.com/exoscoriae/eXoDOS/files/9151804/Save_-_use_ty_game.zip), restore the game names "ty".

Discord user TacoAdventure reported the problem and stated that cycles being reduced to 8500 seems to fix it though they still had intermittent freezes. I tried 5000 and didnt get any freezes in my limited testing.

**Comment by exoscoriae** [comment]
ok, dropped to 5k. hope it isn't too slow.
