### ISSUE TITLE
MechWarrior 2 - Official Mech Warrior 2 - 31st Century Combat - Battle Guide

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4067]
MechWarrior 2 - Official Mech Warrior 2 - 31st Century Combat - Battle Guide - scanned book added.

**Comment by exoscoriae** [comment]
created pdf from files. added to 
MechWarrior 2 (Limited Edition) (1996)

Please name the ticket after the game entry it is to be associated with, rather than ther document you are uploading. thank you.
