### ISSUE TITLE
SimCity 2000 - CD Collection (1994)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4070]
SimCity 2000 - CD Collection (1994). Regardless of what Moby says "CD Collection (1994)" and "Special Edition" are two different releases, and "CD Collection" is inferior (less maps and scenarios at least). What is in the collection is the "Special Edition" (1996) anyway.

It's also ISO. I uploaded CUE/BIN of re-release (identical in DOS and Win3.1 part, has pdf docs on disc).

**Comment by exoscoriae** [comment]
replaced image in the cd folder and changed the mount.
