### ISSUE TITLE
Su-27 Flanker - Squadron Commander's Edition (1997) Manual

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4074]
Su-27 Flanker - Squadron Commander's Edition (1997) Manual is actually pdf'ed help file of the game. Can be nice as extra, but not actual manual.

**Comment by exoscoriae** [comment]
we don't have a "commander's edition" in exodos? I have no idea what this is referencing.

**Comment by SmilingSpectre** [comment]
We have exactly this disk. But we use only DOS part of it, so this manual is obsolete, probably.
