### ISSUE TITLE
Gun Boat Duck Hunt (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4078]
Dosgamert found

- [x] Gun Boat Duck Hunt (1995)

Developer: Mike Vanfleet & Nate Goudle
Publisher: Loco Ware
Year: 1995
https://archive.org/details/DUCKHUNT

It's Shareware

![grafik](https://user-images.githubusercontent.com/67441153/183282035-692eb319-4afc-47be-a6db-1a421dd65ce0.png)

![grafik](https://user-images.githubusercontent.com/67441153/183282030-2ec3477d-d525-4a6c-bc53-bc0132640c2f.png)

![grafik](https://user-images.githubusercontent.com/67441153/183282043-8b0eeed3-fe07-462f-b884-e975d456b2de.png)

**Comment by exoscoriae** [comment]
added
