### ISSUE TITLE
Fallen Heroes (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4080]
Shareware version. More army types unlocked along with CD version if registered

**Comment by SmilingSpectre** [comment]
Oh. _This_ game. :D

**Comment by exoscoriae** [comment]
Unfortunately, even the author didn't have a registered copy. So if one is out there, it is going to be hard to find

**Comment by Python-Exoproject** [comment]
Epic search fail, didnt realise this was already noted in a separate issue
