### ISSUE TITLE
11th Hour, The (1995)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4082]
You can eliminate disk swapping by giving each disk its own drive like this:

> imgmount d ".\discs\1.cue" -t iso
imgmount e ".\discs\2.cue" -t iso
imgmount f ".\discs\3.cue" -t iso
imgmount g ".\discs\4.cue" -t iso

I have not tested all 4 discs but i was able to get to disc 2 without any swapping on my end.

**Comment by exoscoriae** [comment]
ok. changed and removed disc swap message
