### ISSUE TITLE
Might and Magic - Book 1 (1986)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4084]
I scanned the

- [x] map

The current one is low quality.
Added to the github folder.

**Comment by exoscoriae** [comment]
existing is higher quality.

**Comment by Eulisker** [comment]
I found a bunch of 

- [ ] Annotated Maps

on [here](https://addictedgamewise.com/guides/might-magic-series/might-and-magic-book-one-maps/). I put them into a .pdf and uploaded it to the github folder.

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found the

- [ ] IBM Reference Card

Added to the github folder.

**Comment by exoscoriae** [comment]
added
