### ISSUE TITLE
Metal Force (NewSoft) (1998)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#4091]
This spanish fighting game is not on dos master list, not on moby games, not in the TDC, not on the missing list.  
https://www.old-games.ru/game/12621.html 

Genre: Fighting
Developer: NewSoft
Publisher: NewSoft
Released:	1998
Language: Spanish
Format: bin+cue

Added to the github folder with manual in spanish, serial and covers

**Comment by exoscoriae** [comment]
what a shit show!
lol
added
