### ISSUE TITLE
Zephyr (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4097]
can do IPX (netbios) and modem but freezes (for me) after connecting...
not sure what to do with this one, any further ideas? I don't have experience with netbios ... are there any further params for it?

**Comment by TimberlAndRE-de** [comment]
works now, wasn't netbios but just my fault ;-)
works with default IPX settings and netbios call

**Comment by exoscoriae** [comment]
added
