### ISSUE TITLE
Journey - The Quest Begins (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#410]
contains image of the extras on page 12
contains map on page 13

**Comment by Eulisker** [comment]
I found a scanned version of the 

- [ ] manual

The current one is a digital version with some extras in the same document.

Added  to the github folder.

**Comment by TimberlAndRE-de** [comment]
@Eulisker 
did you extract the extras too?
So eXo can replace the manual without loosing the extras?

**Comment by Eulisker** [comment]
Yes I did. They are here #3470

**Comment by exoscoriae** [comment]
replaced manual
