### ISSUE TITLE
Quest for Glory III - Wages of War (1992)

### ISSUE THREAD

**Issue by kcgen** [exoscoriae/eXoDOS#4100]
The QFG3 fixup patch, added in ticket: https://github.com/exoscoriae/eXoDOS/issues/1561, was just updated (now version 1.3.1) with a small fix:

> Fixed the "Salim forgets Dispel Potion ingredients" bug.

https://github.com/AshLancer/QFG3-Fan-Patch/releases/tag/v1.3.1

**Comment by exoscoriae** [comment]
updated patched\enhanced copy
