### ISSUE TITLE
Red Baron, The (1986)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4101]
It is in the collection as the separate entry. Also, it's on Moby where it's claimed "it's very similar, but different".

It is not. I compared SOPWITH.EXE with BARON.EXE, and there are exactly two differences: "M - Multiple players" text entry removed from the Red Baron (but key still works, the same way as in Sopwith), and "SOPWITH BRB Compuscience" text replaced with "The Red Baron" text.

No other differences.

So maybe it worth to be added as sub-entry into Sopwith game, but not worth keeping as the separate entry.

**Comment by exoscoriae** [comment]
removed The Red Baron (1986)
merged it into the Sopwith (1985) entry.
Added as an alternate name as well
