### ISSUE TITLE
Player of the Year (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4102]
agathosdaimon bought, scanned and ripped:

**Game:** Player of the Year
**Genre:** Sports / Simulation
**Developer:** Krisalis
**Publisher:** Philips Media
**Year:** 1996

Description: Player of the Year is a football package that can be played as a full arcade simulation or as a simple management game.

**Installation infos:**
Sound: SB16 and CD-Audio (no MT32 or SC55)  
Two start options in run.bat : POY.exe for the game itself,  MULTIMDA.exe for a Multimedia Show of the PFA Awards History
I also added the cover scans and the manual from agathosdaimon, it's all in the `Player of the Year (1996).zip` in the github games submission folder (original upload RAW CD image is also in PLAYER OF THE YEAR.ZIP)

**Comment by exoscoriae** [comment]
added
