### ISSUE TITLE
Keypunch Software compilations

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4111]
There are 5 Keypunch compilations in the eXoDOS now:

Arcade Bonanza (1987)
Club Casino (1990)
Space Battles (1993)
Space Games (1986)
Sports Spectacular (1987)

I recommend to remove all of them from the collection.

I analyzed all of them and taken everything that isn't at our or TDC collections as separate entries. There are 6 games, 3 are missing, 3 are existing under the different names. I'll log them separately.

**Comment by Python-Exoproject** [comment]
Those entries are #4112 #4113 #4114
