### ISSUE TITLE
Meteor (1981)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4112]
Keypunch version found, under the name "Meteor Shower". I suggest to add it as alternative to the existing entry. Uploaded to Ginhub/Game Submissions as "Meteor (Meteor Shower) (1981).zip"

**Comment by exoscoriae** [comment]
added

**Comment by Python-Exoproject** [comment]
500 cycles is too much for the keypunch version. Both versions seem to do ok around 300 if you'd prefer to keep them both at the same cycles for simplicity sake.

**Comment by exoscoriae** [comment]
ok. dropped to 300
