### ISSUE TITLE
[Language Packs] install.bat needs language switch

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4124]
Because the install.bat is linked to the "Configure..." item in Launchbox game's context menu, it needs the same language switch as the Launch.bat. Otherwise the Language Pack games can't be uninstalled since their install.bat is never called (or it has to be an additional context menu item but that will confuse people I think)

**Comment by exoscoriae** [comment]
ok. I backed up the old installer and created a new one. please test it with your language pack and let me know if it works for you.

**Comment by Python-Exoproject** [comment]
@TimberlAndRE-de can you confirm that this is good for me to close?

**Comment by TimberlAndRE-de** [comment]
@Python-Exoproject 
Ah,yes works perfect, thanks 👍
