### ISSUE TITLE
Ishar 2 - Messengers of Doom (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4125]
from user Perotin in discord (https://discord.com/channels/454359114601201666/467028238687010826/1022082984083464303):
There is an impassable protection check early in the game.
Although it's still possible to click "EXIT" and go back you can't type anything but also the requested information is not visible

here's a savegame, just walk "up" to enter the room with the copy protection check
[ISHAR2.zip](https://github.com/exoscoriae/eXoDOS/files/9615782/ISHAR2.zip)

**Comment by Python-Exoproject** [comment]
In relation to Timbers note that the text of the protection check is glitched, @SmilingSpectre located the culprit files that have the bad crack and offered these to replace them:
[OriginalFiles.zip](https://github.com/exoscoriae/eXoDOS/files/9657429/OriginalFiles.zip). He wasnt sure if one or both need replacing. Once done the game is uncracked but the protection question is readable and can be answered from the manual.

**Comment by Python-Exoproject** [comment]
For reference when attempting to crack in the future Perotin noted its working when:

You enter the building to initiate the dialogue (monologue actually) with the local lord. You have to pass the security check to make the dialogue to appear. When you enter the correct word, it doesn't confirm anything but the words from that lord appear so you can continue the game.
He basically allows you to use the ship to leave the island
Without that you cannot make any progress
If I remember correctly, it's not the only security check in the game

**Comment by exoscoriae** [comment]
restored original files.

did not attempt to crack.

**Comment by amazzanti** [comment]
[ishar2.zip](https://github.com/exoscoriae/eXoDOS/files/13759177/ishar2.zip)

**Comment by amazzanti** [comment]
[START.zip](https://github.com/exoscoriae/eXoDOS/files/13759945/START.zip)

Crack for the eXoDos version. Mine was not multilanguage.

**Comment by exoscoriae** [comment]
just awesome. thank you.
