### ISSUE TITLE
Might and Magic 4 - Clouds of Xeen (1992), Might and Magic 5 - Darkside of Xeen (1993), & Might and Magic - Swords of Xeen (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4127]
Perotin on discord said:

small but annoying bug. When browsing hero stats and moving mouse cursor above some invisible line, the cursor starts to disappear - first partially, then entirely. You can still click icons above with now invisible cursor so it's not a game-breaking issue.

Eulisker found its fixed by setting cycles to 30k

**Comment by exoscoriae** [comment]
set all cycles to 30k for these games
