### ISSUE TITLE
Arnie 2 (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4128]
Xavier_Velo noted:

Annoying sound on mission description screen (on SB), switching to ECE fixes this. Also, according to manual, "Esc" key should work ingame as mission abort. It doesn't work this way, to quit you have to press "H" for pause first, then "Esc", maybe worth to add info about it?

I have tested and confirmed sound issue.

**Comment by exoscoriae** [comment]
switched to ECE.

noted the description in the front end. doesn't seem major enough to pop up before every single launch
