### ISSUE TITLE
Khalaan (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#413]
No English language 
Language(s): fr
page 2 is missing (probably blank page)

**Comment by SmilingSpectre** [comment]
Uploaded. But french manual is _much_ nicer. Maybe worth to keep as extra?

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre i cropped it, looks much better now
uploaded to github folder

**Comment by exoscoriae** [comment]
replaced
