### ISSUE TITLE
Leisure Suit Larry 1 - In The Land of the Lounge Lizards (1987)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4134]
5.1 (also WIP) has wrongly titled files (zip, etc.) for Larry 1: "Leisure Suit Larry 1 - Land of the Lounge Lizards (1987)", this should be: "Leisure Suit Larry 1 - **In The** Land of the Lounge Lizards (1987)"

**Comment by exoscoriae** [comment]
fixed
