### ISSUE TITLE
Leisure Suit Larry 1 - In The Land of the Lounge Lizards SCI (1991)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4135]
5.1 (also WIP) has wrongly titled files (zip, etc.) for Larry 1: "Leisure Suit Larry 1 - Land of the Lounge Lizards (1991) SCI", this should be: "Leisure Suit Larry 1 - **In The** Land of the Lounge Lizards (1991) SCI"

**Comment by exoscoriae** [comment]
fixed
