### ISSUE TITLE
KKND - Krush, Kill 'N' Destroy (1997)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4138]
I've found patch 1.2 which adds some improvements, for ex.: "When recalling a stored group, pressing [ALT]+# will centre the screen on the group.". This function isn't available in our version, so I presume we have 1.00. Tested, works after installing 1.2 patch.
[KKnD_Patch_12.zip](https://github.com/exoscoriae/eXoDOS/files/9748038/KKnD_Patch_12.zip)

**Comment by exoscoriae** [comment]
patched
