### ISSUE TITLE
Power F1 (1997)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4142]
the dosbox.conf calls the `/powerf1/run.bat` in the root folder (which let's you chose between single and network game)
the sound options are in a second `run.bat` in the subfolder "POWERF1" (=/powerf1/POWERF1/run.bat). 
but it's never called, neither in the first run.bat nor in the network.bat

the `/powerf1/run.bat` should be changed to call "run" instead of "f1", same for the network.bat

**Comment by exoscoriae** [comment]
i believe these sound options are meaningless
it plays CD audio, and never appears to actually use any of the midi options.
