### ISSUE TITLE
Dynatech (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4147]
**Dynatech: 30th Anniversary Edition**
https://sketchy.work/dynatech

It's an unofficial remaster for Dynatech for (the Amiga and) DOS version

_Fully localised in English, including manuals_
_Carefully remastered graphics and UI_
_The MS-DOS version is only provided pre-installed. It will run on any fairly standard IBM PC/DOS environment with Adlib compatible sound, VGA graphics and 2+ MB RAM. If you're trying to run the game on a modern system I recommend DOSBox_

The original game is German and therefore not added to eXoDOS yet (but it will be in the GLP ;-) )
But this one is completely in English so could be added as "fan translated version" to eXoDOS

**Comment by exoscoriae** [comment]
added
