### ISSUE TITLE
City Beneath the Surface (1998)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4148]
mgoddard noted:

When I run (the game) and choose to load the example set 1. I move around a little bit with the arrow keys and Dosbox crashes hard and I have to kill the process. If someone else can verify isn't not just my system.

Spectre replied:

The game needs to be run with the loadfix -25 parameter

Spectre also provided a registered version ([Cbs21f.zip](https://github.com/exoscoriae/eXoDOS/files/9810040/Cbs21f.zip)), although I couldnt find a sound setting that gave sound in game with the registered version. In the current freeware version you hear grunts when you run into a wall.

**Comment by SmilingSpectre** [comment]
Found ripsaw notes about the issue.
[SETSOUND.TXT](https://github.com/exoscoriae/eXoDOS/files/9811801/SETSOUND.TXT)

There is set .dat too, but it's simpler to modify the exe, I believe.

**Comment by SmilingSpectre** [comment]
[SOUND.txt](https://github.com/exoscoriae/eXoDOS/files/9811882/SOUND.txt)

Oh, great, Github refuses to take zips. TXT above is actually .zip with modified setsound.dat and modified .exe.
