### ISSUE TITLE
Might & Magic 2 spells

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4155]
M&M2 features the new spell system: now you are not granted all spells when you get the level, but only fraction of them, and must buy the remained ones. So it's good idea to track them manually.

I went to the idea "print out the spell tables at the end of the manual and check them manually". Unfortunately, in our scan (from the Mocagh) someone already used this idea, so their table is totally checked and unusable. Fortunately, Moby has a clear scan. Uploaded to the Github folder and added here, just in case.
![Might   Magic II Spell Tables](https://user-images.githubusercontent.com/24454178/199982278-3ff900cd-ef51-4b39-b54e-820c24b26ad9.jpg)

**Comment by exoscoriae** [comment]
added
