### ISSUE TITLE
Ascendancy (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4159]
If you put a file named `NOUGAT.LF` into the game folder, cheats will be activated:

- mouse over on a ship shows stats and infos
- on the star map you can switch to any race by pressing keys 1 - 7
- pressing 8 on the star map you can see what all other players can see
- steal a technology from other players every round by pressing ALT-E
- while showing the planet screen press O to reach the max population
- pressing I finishes every building immediately
- in the research screen you can press D to reveal all science fields

Also you can put a file named `FLASH.POP` into the game folder to activate the "continous advance" button. this starts a game where you can watch the computer play against itself

**Comment by exoscoriae** [comment]
added launch options for all of this
