### ISSUE TITLE
Might & Magic 2 graphic mode

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4160]
By default (now) M&M2 works with EGA graphics. And looks like that:

![image](https://user-images.githubusercontent.com/24454178/201216571-75202eb3-405a-4a43-86c6-b761049191d1.png)

Actually, with keys you can use any graphic card, from Hercules to VGA. And while dungeons looks the same in VGA, NPCs are much more prettier:

![image](https://user-images.githubusercontent.com/24454178/201216919-f71f8ebc-1cd7-478f-9986-445c2a9ffdc6.png)

To activate, use "mm2 m" on start instead simple "mm2".

**Comment by exoscoriae** [comment]
changed launch to "mm2 m"
