### ISSUE TITLE
Might & Magic 3 - Cluebook

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4161]
For some mysterious reason, original M&M3 Cluebook never made it into collection (all others was replaced from Mocagh). I added Cluebook from Mocagh to the github folder.

**Comment by Eulisker** [comment]
It has the usual problems with readability in the middle of the book. See page 28 for example.

**Comment by SmilingSpectre** [comment]
Oh. You are right. Ok, thank you for the info.

**Comment by exoscoriae** [comment]
currently added, but it looks like shit

i believe this was one of the books I was asked to order for eulisker?

**Comment by Eulisker** [comment]
Yes it should be in the stack of books for me. I think this has some markings i would have to clean up but I will make a new scan of this eventually.
