### ISSUE TITLE
Land of Devastation resolution

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4168]
Land of Devastation works in 800x600 VGA mode. But game is forced to work in the windowresolution=1280x960. Result is not very pretty.

![image](https://user-images.githubusercontent.com/24454178/202918493-a9b550cd-a18a-445a-b563-b6d4ef26d55c.png)

Suggestion #1: Use windowresolution=800x600. It's too little, but readable.

![image](https://user-images.githubusercontent.com/24454178/202918589-70f4bc8f-9393-4d04-98ac-9bc56e74c1cc.png)

Suggestion #2: Permanently put it to the pixel perfect mode.

**Comment by exoscoriae** [comment]
window resolution is not reliable as it will be over ridden by the global resolution setting.

set to use ece w/ pixel perfect.
