### ISSUE TITLE
King's Table - The Legend of Ragnarok (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#417]
has watermark Le Vieux Manuel

**Comment by bigjim161** [comment]
I found:
- a manual without watermark
-an extra (manual Addendum - Game Characters & Controls )
added to the Github Folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
Manual in

- English
- French
- German
- Italian
