### ISSUE TITLE
Marco Polo (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#4171]
This game has 2 manuals :

- a "Technical Manual" (already in the collection) 

- a "Travel Journal"
Discord user Swizzle scanned the "Travel Journal" 
-> added to the github folder

Maybe we can add the "Travel Journal" as a manual, and add the current one as an extra

**Comment by exoscoriae** [comment]
they are both cd booklet manuals. I don't necessarily know that one is better than the other. I'm happy to add both, but why is the newer one better than the older one?

**Comment by bigjim161** [comment]
I think the "Travel Journal" is more important for the player because it contain information how to play the game. the other manual contains only information to install the game and star up.
