### ISSUE TITLE
Cheesy Invaders (1994)

### ISSUE THREAD

**Issue by TheKins** [exoscoriae/eXoDOS#4177]
The high score table is a corrupt mess. This can be fixed by just deleting INV.SCO.

There is also a different version available from the author's old website (https://cheesysoftware.net/cheesy/index.html) that appears to be the registered version - the registration form is missing from INV.DOC and there is no registration nag screen on startup. (Also, START.COM, the mouse warning screen, causes the Doom-style loading startup to not display text? Weird. Anyway, the author's release doesn't have that either.)

**Comment by exoscoriae** [comment]
replaced version and fixed score. thanks!
