### ISSUE TITLE
Draughts (1991)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#4178]
The game seems to have incorrect details logged for the description. Currently talking about cribbage in the 5.1 and WIp branch because I think the original version was released as a pack.

Suggest changing to the following (from Moby):

<pre>
Draughts is a single player, shareware, implementation of the classic board game. This implementation is for player vs the computer, it can be played with keyboard or mouse and in either colour of monochrome.
</pre>

**Comment by exoscoriae** [comment]
fixed
