### ISSUE TITLE
Espionage (1988)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#4181]
When playing Espionage (1988) the mouse driver is missing and cause the game to be unplayable if you happen to move your mouse or try to play with it. Attached mouse driver works and I was able to play when it was loaded.
[MOUSE.zip](https://github.com/exoscoriae/eXoDOS/files/10218671/MOUSE.zip)

https://discord.com/channels/454359114601201666/467028238687010826/1051977891916820542

**Comment by SmilingSpectre** [comment]
Also, game works in svga_s3 mode, but intended to be played in CGA. It change the used palette. SVGA:

![esp_000](https://user-images.githubusercontent.com/24454178/207361364-e3b9a19b-73fb-4db0-b83b-be1dcf023a64.png)

CGA:

![esp_001](https://user-images.githubusercontent.com/24454178/207361636-c6ec2efc-b35a-412a-841a-774369fdc100.png)

I recommend to change machine to CGA then.

**Comment by exoscoriae** [comment]
great finds. fixed and changed machine type.
