### ISSUE TITLE
Journey to the Promised Land (1992)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#4184]
Journey to the Promised Land (1992) has incorrect description for the game entry in 5.1 and WIP.

Suggest updating to the following:
<pre>
In 1992, Ark Multimedia Publishing published Journey to the Promised Land on DOS. This biblical race game is for 1 to 4 players and asks the player a series of questions based on the bible. If the players get the question right they progress on their journey.
</pre>

**Comment by exoscoriae** [comment]
fixed!
