### ISSUE TITLE
Across the Rhine (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4191]
This game is setup in the games installer to use the res 1024x768 but after a recent question by agathosdaimon I looked at it again and that res is probably making the in game elements to small. We might be better at a res of 800x600.

I also noticed that the games installer was complaining about amounts of memory. It probably doesnt matter as the game is running, but to get rid of these warnings you can change the conf memsize to 32 and change the -freesize setting in the mount command also to 32 (according to the readme at least 20mb is a good idea).

Lastly, the game suffers from the issue where moving the mouse stutters the sound with the current dosbox version the game is using. I tested staging 0.80 and its working without the stutter.

**Comment by exoscoriae** [comment]
tried using 80.1 and it refuses to launch properly using our conf files. the screen is WAY too large. The way staging handles scaling is causing it to read our windows resolutions and create window sizes that are way too large.

**Comment by exoscoriae** [comment]
set freesize to 100 and did a full install

moved to 79.1 staging. 80.1 uses DPI scaling that is incompatible with my current setup. @kcgen mentioned adding a toggle to disable this in a future release. We will want to revisit this at that time if 79.1 does not address the mouse stuttering.
