### ISSUE TITLE
Mario is Missing! (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4193]
the floppy version has SB and MT32 support, current installed version in eXoDOS only has SoundBlaster
I uploaded the floppy images to the github folder ("Bugs") so you can reinstall and add run.bat for SB / MT32 switch

@Python-Exoproject as an info to add to your list of MT32 games

**Comment by exoscoriae** [comment]
installed using the 1.04 floppies, as the 1.08 floppies give fatal errors.

added to mt32 playlist.
