### ISSUE TITLE
Lemmings (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4194]
soulctcher and @SmilingSpectre found a bug in Lemmings, the exe file seems damaged / broken.
see [discord](https://discord.com/channels/454359114601201666/467028238687010826/1058598281275527220)

exe from Lemmings CD seems to work, maybe reinstallation is necessary?

**Comment by Python-Exoproject** [comment]
I dont want to be too quick to dismis this issue, but when testing I could not confirm any problem. The issue was reported to happen in the floppy version (our "Adlib" choice) on level 16 (code CIOLMDLQCR).

If someone else can confirm no issue then feel free to close

**Comment by exoscoriae** [comment]
i specifically remember addressing this at some point.

![image](https://user-images.githubusercontent.com/8557582/211349646-caa3f350-2ca1-4608-a9ad-ee2b5e797716.png)
no issue.

closing
