### ISSUE TITLE
Mario is Missing! Deluxe (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4196]
According to discord user Resulka the game crashes when going through certain doors. The fix looks to be setting EMS=false

**Comment by exoscoriae** [comment]
change conf

**Comment by Python-Exoproject** [comment]
You applied this change to the base game version, it still needs to be applied to the Deluxe version (in folder !dos\MarioMD). Probably a good idea to have added it to the base version as well though as the problem most likely existed in both releases.

As an aside, should the base version and deluxe version be merged into one with user menu choice? I know this can vary from game to game and even depends on the day its mentioned so im just putting it out there.

**Comment by exoscoriae** [comment]
2 different release covers, so it can be two different launch options.
