### ISSUE TITLE
Screamer (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4197]
User Dosgamert has reported that screamer crashes as certain points, usually around checkpoints. He has provided a save game and screenshot.

![image](https://user-images.githubusercontent.com/67406191/211314931-34350a0f-3a49-41f9-8ddb-236f2fbb742c.png)

![image](https://user-images.githubusercontent.com/67406191/211314594-9cb311cd-f2b7-4c88-aef7-7c9aa10e45da.png)

[CHOICE.zip](https://github.com/exoscoriae/eXoDOS/files/10373349/CHOICE.zip) (put this is \Screamer\Screamer\Config).

Its been confirmed by both Timber and myself. Timber tried changing memsize to 64 from the current 32 and said he finished the race but myself and Dosgamert still had issues with that setting. Ive also tried memsize=16, ECE, and staging. memsize=16 gave a similar DOS/4GW error with exception code 0dh and both Staging and ECE just closed abruptly.

**Comment by TimberlAndRE-de** [comment]
I tested the redump version: It doesn't crash at the same point but the whole dosbox closes a bit later before the first round finishes

I reinstalled the current WIP version and it crashes as described above in the second screenshot. If I change the memsize to 64 it runs without problems for me. I can finish the whole race (although I'm not good at it and crossed the finish line as 4th place :-P)

**Comment by Eulisker** [comment]
It looks like even the original version used to crash a lot in svga mode. There is a workaround for the 5th track ([see here](https://www.dosbox.com/comp_list.php?showID=723&letter=S)) though i think that is a different one from the one on top. [Here](https://www.vogons.org/viewtopic.php?t=35353) is a vogons thread with more info. Maybe it is best to set the game in VGA mode?

**Comment by kcgen** [comment]
Some test results with the current WIP version and its settings (SVGA, SB16 Stereo). Repro steps:
1. Copy [:file_folder: **`CHOICE.DAT`**](https://github.com/exoscoriae/eXoDOS/files/10383907/CHOICE.DAT.ZIP) into `SCREAMER/CONFIG/`
2. Launch, then _Championship_ -> _Resume_ -> _enter, enter, enter

Tried a bunch of things, but results were all bad:
- Memory sizes: 8, 12, 16, 24, 32, 48, 63, and 64: crashed w/ DOSBox reporting memory corruption (MCB chain corruption or the dynamic core being asked to execute a non-executable page)
- `core = normal`: crashed w/ IRET error, freeze, dos4/gw detecting a problem, or garbage text written overtop the graphics. 
- Replaced DOS4/gw w/ [:file_folder: **`dos4gw-2.60`**](https://github.com/exoscoriae/eXoDOS/files/10384180/dos4gw-2.60.zip) : crash
- Replaced DOS4/gw w/ DOS32a: crash
- Used JEMMEX as the memory manager: crash (both 2.60 and DOS32a) 
- Tried DOSBox Staging's MCB repair strategy: doesn't help; the game continues to try to write out of bounds, as opposed to being a small "off-by-one" type bug.
    
This course exposes some memory management bugs in the game, causing it to corrupt huge chunks of its own memory.

**Comment by kcgen** [comment]
If Screamer 2 was a bug-fixed build of Screamer 1 ("Virgin management: _"we'll sell them the bug fix as a new game"_ :money_mouth_face:), maybe there's hope that someone can patch-in the bug-fixed memory handling code.. 

Another option (without renaming the files) is to manually select low detail in-game, just for that level:

![starth_001](https://user-images.githubusercontent.com/1557255/211601530-9bfb9cc3-14bb-4595-8e6b-a68e0515db7e.png)
 
Produces:


https://user-images.githubusercontent.com/1557255/211601704-a0f5a2eb-58f4-4669-86c1-64be59ae0ed9.mp4

**Comment by exoscoriae** [comment]
ok. so there seem to be a few options here (both mentioned in the thread linked my @Eulisker above):
1: just use lo res mode for the launch and ignore SVGA
2: use SVGA, but for track 5, rename the high res track file and instead copy the lo res track file over with the high res name. This essentially plays a lo res version of just track 5, which supposedly works for most folks.

@kcgen 's work above is beneficial to understanding the over all, but ultimately it is a variation of option one, which uses the low res files (if I read it correctly)

I saw one person in a thread mention that turning sound off also helped... but that seems unecessary.

**Comment by kcgen** [comment]
Unfortunately even the file-rename approach isn't reliable - I was still able to get a crash after a handful of wins. Same with my suggestions above.. I think I just got lucky; after more attempts, I was still able to get a crash on the resumed championship course.

The odds of avoiding the corruption improve considerably using the low-resolution (files and settings) -- I think that's the best best, and just let users know to try a couple times to get past it.
(or maybe offer a save game for them to slip to level 6?)

**Comment by Eulisker** [comment]
Maybe we can offer the vga mode as an option and have a note that warns of the svga mode being prone to crashing?

**Comment by exoscoriae** [comment]
![image](https://user-images.githubusercontent.com/8557582/212725689-3ddcb54f-c327-4315-9bdd-8d01e4e742c9.png)

**Comment by kcgen** [comment]
@grapeli has found an in-game driving path that avoids the bug: https://github.com/joncampbell123/dosbox-x/issues/3939#issuecomment-1387146638 !
