### ISSUE TITLE
MechWarrior 2 (Limited Edition) (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4204]
I scanned

- [x] reference card (current one is low res and missing pages)
- [x] install guide
- [x] letter
- [x] wolf clan flyer

from the UK Big Box

added to the github folder

**Comment by exoscoriae** [comment]
removed old QRC
added the above

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] strategy guide

added to the github folder
