### ISSUE TITLE
Runners (1998)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4205]
Author: Rafał Zieliński (YesMan)

There is READ_ME.exe file in DOCS folder after installation, worth including in starting menu (it is manual in English & Polish).
To turn sound on, edit RUNNERS.cfg (SFX=off -> on).

[RUNNERS.zip](https://github.com/exoscoriae/eXoDOS/files/10460729/RUNNERS.zip)

**Comment by exoscoriae** [comment]
added
