### ISSUE TITLE
Demoniak (1990)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4206]
I found

- [x] Pure Fiction Club Invitation
- [x] Disk Exchange
- [x] Comic

The comic has nothing to do with the game. It is just a Judge Dredd comic as advertised on the front of the box. They seem to have just put a bunch of different comics into these boxes. This one is different from the one on mobygames which is different from one i found on ebay.

Added to the github folder. 

As a side note: I am not sure about the 1990 release date. The copyrights on the box, manual and disks all say 1991.

**Comment by exoscoriae** [comment]
Added documents.

date in the metadata is 1991 currently. renamed game to match
