### ISSUE TITLE
Silent Steel (1995) Sigma Designs Edition

### ISSUE THREAD

**Issue by kcgen** [exoscoriae/eXoDOS#4215]
### Suggested settings

- Win 3.1: S3 640x480 @ 16M color mode

- [MCI] Driver:
    - Install with https://archive.org/details/xingmpegplayer
    - Xing's `XMDRIVER.DLL` will generate an error when Windows exits; but it can be ignored.

- **`dosbox.conf`**:

    ```ini
    [cpu]
    cputype = pentium_slow
    cycles  = 100000
    ```

### Video comparison vs AVI version

The MPEG-1 video retains more color and a higher frame-rate (29.97 fps) than Indeo3 (which runs at 15 fps) and runs at, unfortunately the MPEG video has more  compression artifacts than than Indeo3.

#### Snap 1 MPEG (upper) vs. AVI (lower)

![snap1-mpeg](https://user-images.githubusercontent.com/1557255/217336234-c12026e2-39d2-43e6-9728-a4a71128dc07.png)

![snap1-avi](https://user-images.githubusercontent.com/1557255/217336230-52572864-0048-485b-b1bc-59f632596439.png)

#### Snap 2 MPEG (upper) vs. AVI (lower)

![snap2-mpeg](https://user-images.githubusercontent.com/1557255/217336223-2387913e-8fa0-4de5-a378-2df0471f175e.png)

![snap2-avi](https://user-images.githubusercontent.com/1557255/217336227-dfe1b8ab-a4ae-4c4d-ae56-896aadaa18d0.png)

### Audio comparison vs AVI version

The MPEG audio is higher fidelity (16-bit, 44.1 KHz, stereo) and has more frequency range (AVI is upper, MPEG is lower):

![spectrum-avi-5-KHz_mpeg-14-KHz](https://user-images.githubusercontent.com/1557255/217335003-5f7650f5-486d-4ac8-a237-93582de04554.png)

But suffers from periodic clipping:

![waveform-mpeg-clipping_blunders](https://user-images.githubusercontent.com/1557255/217335013-d1ca2ff5-f329-4459-8902-4acfdc399fd3.png)

#### MPEG waveform

(Look at all those clipped waveforms :disappointed: )

![waveform-mpeg-16-bit-44 1-KHz-stereo](https://user-images.githubusercontent.com/1557255/217335010-7ff158e2-bc55-4fd7-99c2-d74d94c8b1d4.png)

#### AVI waveform

![waveform-avi-8-bit-11-KHz-mono](https://user-images.githubusercontent.com/1557255/217335012-62eca6f7-3ce5-4f4f-a97c-7834d5aba984.png)

#### MPEG codecs

```
Format                                   : MPEG Video
Format version                           : Version 1
Format settings                          : BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Default
Format settings, GOP                     : M=3, N=15

Width                                    : 352 pixels
Height                                   : 240 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 29.970 (30000/1001) FPS
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive

Audio
Format                                   : MPEG Audio
Format profile                           : Layer 2
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
```

#### AVI codecs

```
Format                                   : Indeo 3
Codec ID                                 : IV32
Codec ID/Info                            : Intel Indeo Video 3.2

Width                                    : 316 pixels
Height                                   : 236 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 15.000 FPS

Audio
Format                                   : PCM
Bit rate mode                            : Constant
Bit rate                                 : 88.2 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 11.025 kHz
Bit depth                                : 8 bits
```

**Comment by Python-Exoproject** [comment]
Closing this @kcgen as it is an eXowin3x game, not eXoDOS. I created a new ticket in the eXoWin3x page though and linked to this post from there
