### ISSUE TITLE
Albion (1995)

### ISSUE THREAD

**Issue by kcgen** [exoscoriae/eXoDOS#4217]
It can use GUS:
 - Only needs `ultrasnd` present with MIDI patches
     It doesn't use UltraMID or UltraINIT
 - It can be unstable across scene transitions -> using DOS32a fixes it
     Replace DOS4GW in the top-level dir and inside DRIVERS.
 - For GUS, the game plays smooth and stable at 18k cycles. Nothing more needed.

Works great with all DOSBoxes.

Here's a zip that adds GUS: [Albion (1995)-eXoDOS v6 [WIP]-GUS-Add.zip](https://github.com/exoscoriae/eXoDOS/files/10715445/Albion.1995.-eXoDOS.v6.WIP.-GUS-Add.zip)

**Contents:**

```
  Length      Date    Time    Name
---------  ---------- -----   ----
     1057  2023-02-11 22:32   run.bat
      691  2023-02-11 16:53   run.bak

    27504  2023-02-11 12:28   DOS4GW.EXE
   265420  1996-12-24 21:32   DOS4GW.BAK

    27504  2023-02-11 12:28   DRIVERS/DOS4GW.EXE
   265420  2023-02-11 16:46   DRIVERS/DOS4GW.BAK

        0  2023-02-11 11:22   DRIVERS/GUS/
      265  2023-02-11 11:22   DRIVERS/GUS/1024.GUS
      193  2023-02-11 11:22   DRIVERS/GUS/MDI.INI
      182  2023-02-11 11:22   DRIVERS/GUS/DIG.INI

        0  2023-02-11 16:05   ultrasnd/
     5476  2020-09-07 08:43   ultrasnd/ultrasnd.ini
  6000000  2023-02-11 13:02   ultrasnd/midi/*.PAT
```

Here's how GUS was added to `run.bat`:

```bat
:menu
@echo off
cls
echo.
echo Press 1 for Albion w/ SoundBlaster
echo Press 2 for Albion w/ MT-32
echo Press 3 for Albion w/ Sound Canvas
echo Press 4 for Albion w/ Gravis UltraSound
echo Press 5 to Quit
echo.
choice /C:12345 /N Please Choose:

if errorlevel = 5 goto quit
if errorlevel = 4 goto GUS
if errorlevel = 3 goto SC55
if errorlevel = 2 goto MT32
if errorlevel = 1 goto SB16

:GUS
CONFIG -set "mididevice=none"
CONFIG -set "sbtype=none"
CONFIG -set "ultradir=c:\ultrasnd"
CONFIG -set "gus=true"
CONFIG -set "cycles=18000"
CONFIG -set "core=dynamic"
mixer gus 250 /noshow
mixer gus r70 c40 /noshow
cd DRIVERS
copy gus\*.*
cd ..
cls
ALBION
goto quit

(others as-is below)
```

The second mixer line for GUS enables reverb and chorus in Staging, for a tad more ambience inside the Albion world (suggest headphones):

https://user-images.githubusercontent.com/1557255/218297435-cb11ba11-f4e4-4860-ad68-afffaa23f471.mp4

**Comment by exoscoriae** [comment]
@kcgen 
there is no music during the intro video using these configuration files?

**Comment by exoscoriae** [comment]
for whatever reason, I went and set them to GUS myself, and now it has sound in the intro.

I went back and checked settings. It is the "sbtype=none". Doing this kills sound for the game's intro movie. It appears this is digital audio? and not working through GUS?

added game to the GUS playlist in LB.
