### ISSUE TITLE
Color Lines (1992)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4226]
Our version doesn't have any sound. I've found 2 versions with sound in TDC.
[Color Lines [a1] (1992)(GAMOS Ltd.) [Strategy].zip](https://github.com/exoscoriae/eXoDOS/files/10797866/Color.Lines.a1.1992.GAMOS.Ltd.Strategy.zip)
[Color Lines (1992)(GAMOS Ltd.) [Strategy].zip](https://github.com/exoscoriae/eXoDOS/files/10797867/Color.Lines.1992.GAMOS.Ltd.Strategy.zip)

**Comment by exoscoriae** [comment]
replaced and confirmed sound
