### ISSUE TITLE
Update with recent entries from Game Maps

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4227]
Update with recent entries from Game Maps:

[Alone in the Dark.zip](https://github.com/exoscoriae/eXoDOS/files/10833704/Alone.in.the.Dark.zip)
[Dune II.zip](https://github.com/exoscoriae/eXoDOS/files/10833706/Dune.II.zip)
[PowerMonger.zip](https://github.com/exoscoriae/eXoDOS/files/10833707/PowerMonger.zip)

**Comment by exoscoriae** [comment]
added
