### ISSUE TITLE
Pizza Quest I - Cruisin for a Bruisin (198x)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4228]
PabOu-486dx2 — 16/02/2023 20:54

I found a small issue with Pizza Quest 1 : I guess I died or lost the game or something because the dosbox window closed. I suppose the game told me something and just exited to DOS and Dosbox closed. I didn't get to read the text telling me what happened.

Python — 16/02/2023 23:56
Confirmed @eXo, we need to enable a pause before the game exits so the last message can be read. To test, the quickest way is to start the game and type (in caps):

S
GET IN
PUSH LEVER
PRESS BUTTON
159.100.320
FASTEN SEAT BELT

and after a few screens of "press enter to continue" you will loose the game because you forgot the pizza and the last paragraph cant be read due to dosbox exit

**Comment by Python-Exoproject** [comment]
eXo added pause to conf autoexec section on 17/2/23, however the pause has no effect and the game still immediately exits dosbox when you die.

**Comment by exoscoriae** [comment]
fixed.

added a second pause.
