### ISSUE TITLE
Ultima I - The First Age of Darkness (1986)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4231]
OMG, we have another enhancement for an Ultima game! Im so excited, and I know you are as well!

DrakeRaider has updated the graphics for the game, just setup a user choice (Can you believe this Ultima doesnt have one yet?) to select between original graphics and the mod. Files are here:

[Ultima1GFX.zip](https://github.com/exoscoriae/eXoDOS/files/10846027/Ultima1GFX.zip)

**Comment by exoscoriae** [comment]
updated
