### ISSUE TITLE
Dune (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4233]
Staging has now implemented a better emulation of the Adlib Gold which has improved that sound choice for Dune.

Switch game to staging and use this staging friendly conf [dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/10856598/dosbox.zip). The actual setting to adlib gold is done in run.bat but there are other staging specific conf tweaks needed which ive made in that conf

**Comment by exoscoriae** [comment]
changes made

**Comment by johnnovak** [comment]
Nice to see my work ended up in eXoDOS! 😎🤘🏻(I added the AdLib Gold support to Staging)
