### ISSUE TITLE
Entity (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4235]
The sound is really quiet at the moment. I found that if we switch to "sbtype=sbpro2" it improves considerably.

There is still a bit of a pop after each effect plays in game, but I didnt find a way to mitigate that. 

One other annoying thing in the game I found that is out of our control is that as you move along you come across scrolls which give little cut scenes. If you quickly press down arrow you see the scene but if you press even for a slightly extended time it starts and immediately exits the scene.

**Comment by exoscoriae** [comment]
looks like conf change was made.

the game itself was never officially released. so, there are many bugs we don't have a lot of control over.

**Comment by Python-Exoproject** [comment]
I think you may be confusing this with the Reel Magic version where I made the change when I submitted the updated conf?

This ticket is referring to the original release in the folder \!dos\Entity\ which shares the same problem

**Comment by exoscoriae** [comment]
me? confused? pshh. never.
