### ISSUE TITLE
Leisure Suit Larry 1 - In The Land of the Lounge Lizards (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4252]
wysiwyg found

- [ ] official book of larry (guide)

it's for Larry 1 - 6 and could be added to all this games

added to the github folder

**Comment by exoscoriae** [comment]
rejected. we already had a higher quality version in the pack

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] sierra reference card

added to the github folder

**Comment by exoscoriae** [comment]
added
