### ISSUE TITLE
Links 386 CD (1995)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4261]
I uploaded a .zip containing flybys and 4 updated courses. Just unzip the content of the file into the LINKSPRO folder in your .zip.

The most significant upgrade in the 4 courses is Barton creek:

old
![Screenshot 2023-03-13 165540](https://user-images.githubusercontent.com/81642149/224761977-01c8742b-fe05-4e83-b2a6-6cad4f0e4b6f.png)

new
![Screenshot 2023-03-13 165825](https://user-images.githubusercontent.com/81642149/224762041-375da702-49f2-4e62-8db5-6e54009fc185.png)

https://user-images.githubusercontent.com/81642149/224762264-e5887447-5497-4ebc-9efc-2843426b48d9.mp4

These 18 courses now have flybys when you click the button

```
Banff Springs
Bountiful Golf Club
Castle Pines
Cog Hill Golf & Country Club
Congressional
Devils Island Fantasy Course
Firestone Country Club
Harbour Town
Mauna Kea
Oakland Hills
Pebble Beach
Pelican Hill
Prairie Dunes Country Club
Riviera Country Club
The Belfry
Troon North
Valderrama
Valhalla Golf Club
```

Thanks to discord user wysiwyg for collecting all this.

**Comment by exoscoriae** [comment]
added
