### ISSUE TITLE
Mad Mix Game (1988)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#4265]
1-IMO the current name in the collection: "Mad Mix Game**s**"  is not correct .
![image](https://user-images.githubusercontent.com/67555221/226126041-6b0d9e5e-f819-4419-8e2e-4515f07277d5.png)
"Mad Mix Game" is correct (see manual and cover)
https://www.old-games.ru/game/3880.html
https://www.cpc-power.com/index.php?page=detail&onglet=package&num=1327
2-Found a manual in spanish (it's a spanish game)

Added to the github folder

**Comment by exoscoriae** [comment]
fixed game name and add
