### ISSUE TITLE
Duke!ZONE II (1997)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#4275]
Discord user wysiwyg found:

a manual for Duke!ZONE 

maybe we could add it because:
- we haven't a manual for Duke!ZONE II.
- and Duke!ZONE II has the 500 levels from Duke!Zone

@exoscoriae if you agree, can you set the issue back to "To do" after processing the manual?

Added to the github folder

**Comment by exoscoriae** [comment]
i don't see this manual in the folder @bigjim161
