### ISSUE TITLE
Pro League Baseball (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4284]
wysiwyg found

- [ ] manual (not a good scan, wasn't disassembled and not pressed on the glass but all is readable)

added to the github folder

**Comment by TimberlAndRE-de** [comment]
nope, it's for the 1994 version 1.1 of the game,
bigjim already found it here: #2845

**Comment by parricc** [comment]
The xml file refers to `Manuals\MS-DOS\Pro League Baseball (1992).pdf`, which does not exist.

Is there a 1992 manual available that should be uploaded to WIP? Or was this manual entry added in error?

**Comment by parricc** [comment]
Proposed change attached to https://github.com/exoscoriae/eXoDOS/issues/5333
Will wait for eXo to approve that change before resolving this ticket.

**Comment by parricc** [comment]
eXo prefers handling the above kind of xml issue on a case-by-case basis rather than as part of a bulk change. As such, he'll need to make the xml correction in this ticket.
