### ISSUE TITLE
IBM Music Feature Card (New sound option)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4286]
On hold until next official staging release

This card has a unique sound and is being added in the next official Staging release. They added Loris Chiocca's IBM Music Feature Card (IMFC) patch. It will be controlled by a new section in the conf so we will need to update the template we use for staging based games once we add it in.

Only Sierra games used the card, and at that it was only some of their earlier games. @kcgen has done the legwork and created an archive of games he has gotten working with the card that includes the driver files and patch files needed.
[IBM Music Feature Card - Part1.zip](https://github.com/exoscoriae/eXoDOS/files/11131045/IBM.Music.Feature.Card.-.Part1.zip)
[IBM Music Feature - Part2.zip](https://github.com/exoscoriae/eXoDOS/files/11131046/IBM.Music.Feature.-.Part2.zip)

**Comment by exoscoriae** [comment]
what is the staging release we are waiting for for this one?

**Comment by kcgen** [comment]
0.81 will have IMFC (to take it for a spin, devs builds have it: https://dosbox-staging.github.io/downloads/development-builds/)

**Comment by exoscoriae** [comment]
added

**Comment by Python-Exoproject** [comment]
Silpheed (1988): still needs switching to the staging81.0a build in dosbox.txt

King's Quest IV - The Perils of Rosella (1988): Oversight on my part. Now that the game is using Staging 81.0a for IBM MFC the tandy option which uses a conf I didnt need to touch for IBM MFC also needs updating to the staging framework. Please use this conf: [KQ4_tandyconf.zip](https://github.com/exoscoriae/eXoDOS/files/12599524/KQ4_tandyconf.zip)

King's Quest I - Quest for the Crown SCI (1990): As the game uses IBMMFC the setting in the new "dosbox2.conf" imfc=false needs to be imfc=true

**Comment by exoscoriae** [comment]
all done!
