### ISSUE TITLE
World Class Leader Board (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4287]
@SmilingSpectre found

- [x] real sound instructions
- [x] World Class Leader Board - The Series instructions (including alternative loading instructions for PC and descriptions for the addon courses)

wysiwyg found

- [x] famous courses addons 1-3 instructions (they contain C64 loading instructions but also additional infos about the courses and colored maps - I would add them until we find the PC version (if there is one, maybe they were included as is with the IBM version together with the instructions listed above from Smiling Spectre)

all added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found the IBM version of the first addon instructions. It is from a photo and not a scan but everything is readable.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I scanned the 

- [ ] Club & Power Snap Indicator

Added to the github folder.
