### ISSUE TITLE
Command and Conquer - Red Alert (1997)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4297]
wyswisyg found

- [x] official strategy guide

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] unauthorized strategy guide
- [ ] unauthorized strategy guide for Counterstrike (Addon)

added to the github folder

**Comment by exoscoriae** [comment]
added
