### ISSUE TITLE
Star Wars - Rebel Assault (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4303]
wysiwyg found

- [x] official insider's guide

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
Smiling Sprecte wrote in #4916 :

_600-dpi scans of the Reference card and also box (unfortunately, with German labels here and there)_

- [ ] Star Wars - Rebel Assault (1993) Reference Card.pdf
- [ ] Star Wars - Rebel Assault (1993) Coverscans.zip

**Comment by Eulisker** [comment]
I added an alternate version. Somebody else decide :)
