### ISSUE TITLE
Superstar Soccer

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4305]
As user wysiwyg found, it's a wrong manual we have. This manual is for "Superstar Outdoor Soccer" from Mindscape/Wizardworks. I got both "Indoor" and "Outdoor" Soccers when processed TDC, so they are in the correspondent dir on server. We haven't Indoor Soccer manual, unfortunately.
...
Wait, found it.

**Comment by TimberlAndRE-de** [comment]
we already have an issue for the manual of this game:

#1739 

closed this one, added your post to the other issue entry
