### ISSUE TITLE
Superstar Indoor Soccer

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4306]
Got manual for this game and uploaded. Game itself can be found in my TDC dir.

**Comment by TimberlAndRE-de** [comment]
It's an Option for Superstar Soccer (1988), right?
(you can choose between indoor and outdoor soccer)

so I would add it as an additional manual to the game?

**Comment by SmilingSpectre** [comment]
Yes, we talked over that. Game somehow has three manuals - one is better, but HOTU-scanned and talks about Outdoor version only, and two separate, but much less detailed for Indoor and Outdoor, that will go into extras, I think.
