### ISSUE TITLE
Millionaire - The Stock Market Simulation (Release 2) (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4312]
Smiling Spectre found

- [x] manual

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found a better looking 

- [ ] manual.

The current one is squished and has white borders around every page. 

Added to the  github folder.

**Comment by SmilingSpectre** [comment]
Objected this. White borders are Timber's fault (and can be easily deleted, I believe), but quality of suggested revision is sub-par.
Hm, "Squished" part is a real though. No idea how. %)

![image](https://user-images.githubusercontent.com/24454178/233341830-adcc84a1-66fc-420e-a7bd-a24e38d86f12.png)

![image](https://user-images.githubusercontent.com/24454178/233342559-ba65250f-d4cf-4d3a-bbe2-0c02f31beab2.png)

**Comment by SmilingSpectre** [comment]
Hmm, actually, it's a weird thing. The first Millionaire had square manual. Just as the "squashed" one. But the second definitely was released in standard A4 dimensions. No idea if the first is "original" then or not, as I cannot find any photos, except A4, but I cannot imagine someone who will purposedly squish the scan to the square format for nothing. %)

![image](https://user-images.githubusercontent.com/24454178/233344148-78aefdf8-ec81-4df0-839b-35edff9f4c15.png)

**Comment by Eulisker** [comment]
What do you mean by Timbers fault? Do you still have the original pages somewhere? 

I generally agree with you. Let me see if I can unsquish them and see where that gets us. 
It is also way too big. 80mb for 36 pages is too much.

**Comment by SmilingSpectre** [comment]
Found it. It's crazy DPI (someone set it to the resolution, so "print size" is 1 square inch). I fixed it to "real" 600 dpi and also cropped white part. Need additional cropping, but I haven't tools or experience to do that. Feel free to tidying it. Millionaire - The Stock Market Simulation (Release 2) (1987) Manual.zip in Github.

**Comment by Eulisker** [comment]
I reuploaded it. Much better now. The .jpgs were already in the correct aspect ratio. Strange what happened to the manual we have right now.
On another note. Maybe we should rename the game to Millionaire II?

**Comment by SmilingSpectre** [comment]
JPGs was broken before I changed DPI. It became fine as soon as I set every one to 600x600 instead some 3450x5611 as it was for every picture. See, numbers each time was equal to the picture resolutions, so each picture in result displayed as square, and PDF also treated them as 1 inch x 1 inch (so manual in result had crazy 800% or about that to see anything).

On the box and in manual game named Millionaire II, but in-game it's "release 2". For some time I considered that it's two different games, but screenshots of the box surely have the same "release 2", so... I don't know.

**Comment by exoscoriae** [comment]
the github folder has both Millionaire - The Stock Market Simulation (Release 2) (1987) Manual.pdf and Millionaire - The Stock Market Simulation (Release 2) (1987) Manual.zip.

Which are you nominating to be the replacement?

@Eulisker @SmilingSpectre

**Comment by Eulisker** [comment]
I made the .pdf out of the pictures in the .zip. So the .pdf is my nomination.

**Comment by SmilingSpectre** [comment]
Yes, it's fine now in PDF. Even if could benefit from some edge trimming and size normalizing. *sigh* I dream of someone/something with framework for this...

**Comment by exoscoriae** [comment]
replaced
