### ISSUE TITLE
I Have No Mouth and I Must Scream (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4314]
wysiwyg found

- [ ] addendum
- [ ] order card
- [ ] registration card
- [ ] mouse pad
- [ ] h.r. giger flyer
- [ ] cyberdreams flyer
- [ ] comic book
_Harlan Ellison's classic short story "I Have No Mouth And I Must Scream" received a graphic novel adaptation by comics artist John Byrne. It was printed in issues 1-4 of Harlan Ellison's Dream Corridor by Dark Horse; however, it was removed from future copies of the comic collection_

added to the gihtub folder

**Comment by exoscoriae** [comment]
added
