### ISSUE TITLE
Cartooners (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4318]
Found another game that was only using PC Speaker but could do Sound Blaster and MT32.

The game needed sound to be setup from the installer where it would extract the selected sound driver. The only copy of the game complete with installer I could find was the Spanish one from TDC so I used that to install each sound option, copied the driver into our English version and hey presto, we have sound.

The game was also in a bit of a file structure mess with all the files in the correct subfolders and again in the actors folder. Using the Spanish version as a guide I fixed our version up so that its laid out how it should be. Extract the below zip for the corrected structure and sound drivers\run.bat

[Cartooners (1989).zip](https://github.com/exoscoriae/eXoDOS/files/11223507/Cartooners.1989.zip)

To get the Sound Blaster option working the game couldnt use higher than SB2, so that needs to be set in the conf along with adding the usual midi lines and changing the autoexec to load run.bat

Other than that the usual switch to ECE and add to the MT32 playlist

There were also printer drivers available to install so that you can print from in the game (not exactly sure what its printing, maybe a scene you created). I wasnt sure what printer driver dosbox may need to I added two Epson drivers (currently in the game root folder) for you to play around with if you want to add the printer option. The game only installed one at a time so they will probably conflict if left together.

**Comment by exoscoriae** [comment]
left printing alone for now

sound options added
