### ISSUE TITLE
Monte Carlo Baccarat (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4320]
Another for MT32.

I actually think its always been playing Midi as it currently sounds off and if you kill the SB and FM channels you still get the same off sound. It could be one of those games that needs the sound set during install but the only version I found was preinstalled, maybe @SmilingSpectre might have better luck?

Anyway, to fix our version up set the game to ECE, add the conf lines, and add to the MT32 playlist.

**Comment by SmilingSpectre** [comment]
baccarat.exe /?

**Comment by Python-Exoproject** [comment]
lol, well there you go. Thanks Spectre, its always the obvious that gets overlooked

**Comment by exoscoriae** [comment]
added to mt32
