### ISSUE TITLE
JetFighter III Platinum (1999)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4328]
This game can do both SC and MT32.

Go into the jtf3 or jtf3x folder and run install to select the music card. Sound Canvas works fine, but the actual MT32 driver crashes the game when you start a briefing. We can either skip MT32 or use the mpu-401 option which doesnt have this problem.

Game is already on ECE for the 3DFX option, so just the run.bat\conf\playlist changes.

**Comment by exoscoriae** [comment]
done
