### ISSUE TITLE
Superstar Soccer (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4335]
@SmilingSpectre in discord:

- There are, it seems, two releases of Outdoor Soccer. Both are from Wizardworks, and marked 1.0 and 1.1 inside. And both are named "Superstar Soccer" inside anyway!
- We have the third release (TDC has it too), and it seems tinkered here and there. Wrong palette. Chinese (or maybe Arabic?) autoexec. Wrong name inside DORY-DOR SOCCER (and the same name in the FAST.COM that seems does nothing - Programmed by AMIR KADURI-DORY-DOR. 

I recommend to replace it with 1.0 version, because I wasn't able to run 1.1 as intended.
This also has an impact on the manual question in #1739 

added to the github folder

**Comment by exoscoriae** [comment]
replaced
