### ISSUE TITLE
Star Wars X-Wing (Collector's CD-ROM) (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4336]
Started doing a playthrough of this one and found that the in game graphics details were turned down. Replace options.cfg with the one in this file and everything will be maxed:

[OPTIONS.zip](https://github.com/exoscoriae/eXoDOS/files/11242571/OPTIONS.zip)

**Comment by exoscoriae** [comment]
replaced file
