### ISSUE TITLE
Lightspeed (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#434]
has watermark theunderdogs.org

**Comment by TimberlAndRE-de** [comment]
and it is just a reference card, not a manual (thx, @Python-Exoproject), needs to be switched to extras
a real manual exists:
![grafik](https://user-images.githubusercontent.com/67441153/87252992-ab298a00-c477-11ea-864a-0a440bdfa735.png)

**Comment by exoscoriae** [comment]
still seeking color manual

**Comment by exoscoriae** [comment]
replaced
