### ISSUE TITLE
Revolution '76 (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4351]
wysiwyg found

- [x] manual

it's OCRd HOTU version, needs to be replaced by a real scan someday
added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by SmilingSpectre** [comment]
Too fast. :)

Uploaded full set of Apple 2 docs (that is the same as HotU, minus PC reference).

Revolution '76 - Historical Perspective Scanned.zip
Revolution '76 - Player's Reference - Scanned.zip
Revolution '76 - Scans.zip

**Comment by exoscoriae** [comment]
added
