### ISSUE TITLE
Trump Castle II (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4355]
wysiwyg found

- [x] reference card (ok, but not a good scan)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found a good scan of the

- [ ] Reference Card 

and the 

- [ ] Gaming Guide

Added to the github folder.

**Comment by exoscoriae** [comment]
added
