### ISSUE TITLE
SimIsle - Missions in the Rainforest (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4356]
wysiwyg found 

- [ ] manual

it's HOTU OCR one but will do until we find a good scan

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by SmilingSpectre** [comment]
SimClassics - Maxis Collections 3 Scanned.zip uploaded. Three full scanned manuals mechanically glued together: SimCity Classics, SimTower and SimIsle.

**Comment by exoscoriae** [comment]
would like only the manual for the game, not a compilation manual.
