### ISSUE TITLE
The Haunted Manor

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4362]
User Burrito78 bring attention to the small shareware game "The Haunted Manor" that was covered in the July issue of PC Review, 1993. This one (page 10) https://archive.org/details/pc-review-21/page/10/mode/2up

As I cannot find this game anywhere else, I uploaded it to Github.

The Haunted Manor (1991).ZIP

**Comment by exoscoriae** [comment]
added
