### ISSUE TITLE
Warhammer 40000 - Dark Crusaders (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4364]
A (nearly) finished game that was never officially released
https://www.old-games.ru/game/12518.html

Title : Warhammer 40000 - Dark Crusaders (1996)
Genre : Action
Developer : Leaping Lizard Software
Publisher : (Mindscape)
Description : 
This game was completed in 1996, but its publisher, Mindscape, decided to cancel Dark Crusaders before it was released. PC Gamer Online, however, received a copy of the game to review and gave it a 65% on their rating scale. In June/2022, the game was made available to the public. Initially, the gameplay bears a strong resemblance to another squad-based shooter - Terra Nova. But unlike the sleek, efficient commands and diverse missions in TN, Dark Crusaders doesn’t let you make the most of your squad, and the missions don’t really require you to either. During each of the 15 missions, which range from kill-’em-all scenarios to more specific reconnaissance missions, there are commands to order your troops to explore, follow, and teleport to and fro. But regardless of which command you choose, the results seem to be the same as if you left your brethren at home. When ordered to explore, troops merely bump around walls shooting any enemies they encounter, then bump around some more often getting stuck in tight passages or wandering about aimlessly, leaving any and all mission-related work for you. The weak command interface is so disappointing that during most missions it hardly seems worth the effort to even add units to the roster, since you’ll end up doing all the work yourself. The FMV sequences used in here were later recycled for Warhammer: Final Liberation, a turn-based tactics game published for PCs in 1997. (source: https://www.legendsworld.net/shooter/game/31295)

CD image added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by parricc** [comment]
I'm getting an error when attempting to launch this.
`UVBLib: ./univbe.drv is not a valid UniVBE driver file!`
![w4kdc-error](https://github.com/user-attachments/assets/9925156e-a3a5-4a3d-88ba-d2ff1486b1d8)

**Comment by Python-Exoproject** [comment]
Yeah looks like every time the game exits setup it corrupts the univbe.drv file. Here is a working copy to put in the DARKCRUS subfolder: [UNIVBE.zip](https://github.com/user-attachments/files/16661856/UNIVBE.zip)

As an aside exo, it might be worth upping the cycles since when you turn off helmet mode via the menu the game view increases and the game slows down as a result with current setting

Weird there is no pickup sound effect but I played around a bit and couldnt find any sound card config that provided one

**Comment by exoscoriae** [comment]
set to max

added fixed driver. 

thanks guys
