### ISSUE TITLE
Piece of Cake (1984)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4368]
I believe we have a duplicate in the collection. I found:

Piece of Cake (1984), and
Early Games - Piece of Cake (1984)

I found it by trying to change the dosbox fork that Piece of Cake (1984) was using but the launch bat kept using the same dosbox fork. I checked the variables and sure enough the %dosindex% variable in launch.bat was set to that of the other copy, Early Games - Piece of Cake (1984). Im assuming your string search found it as it is first in the list, saw a match for the phrase and wouldnt go further down the list to get the correct values.

In this particular instance we just need to pick a copy to keep and ditch the other from dosbox.txt as well as the files, but do you think this is happening for any other games?

**Comment by exoscoriae** [comment]
removed dupe.

seems this got in twice due to spectres TDC scan and not catching that they were the same.

the new change to the search string in the index file should eliminate the false match. however, if we can find a way to locate any potential dupes, that would be good.
