### ISSUE TITLE
Pac-in-Time (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4383]
wysiwyg found

- [x] manual

it's the european version ("Fury of the Furries") and it's only the english part of the manual (other language pages are missing.

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by exoscoriae** [comment]
we already had fury of the furries in the collection as it's own game. doesn't make sense to add that manual to this entry.
