### ISSUE TITLE
SimCity (1989)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4396]
I found 

- [ ] Architecture - System Card
- [ ] Architecture 1 - Manual
- [ ] Terrrain Editor - Manual

They all are for the Infogrames published european version but it should not make a difference.

Added to the github folder.

**Comment by exoscoriae** [comment]
added. going to scan mine and likely replace

**Comment by TimberlAndRE-de** [comment]
there's already an issue for this game / extras: #4600

so this one here's shut down ;-)
