### ISSUE TITLE
Lost Files of Sherlock Holmes, The - The Case of the Serrated Scalpel (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4410]
found

- [x] Lithographie (from the limited edition)
- [x] Registration Card
- [x] Disk Offer Card
- [x] EA Advert Flyer
- [x] EA Hint Line Number
- [x] Prodigy Advert Flyer

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found

- [ ] UK Reference Card

The differences to the US one aren't that amazing but there is some info about Technical support in the end. 

I also found

- [ ] UK Manual

Currently there is a budget manual set as an alternate manual. This one is the same but does not have the ugly budget cover.

Added to the github folder.

**Comment by exoscoriae** [comment]
added
