### ISSUE TITLE
Vlak (1993)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4412]
We currently have v1.0 of Vlak in 5.1. There's v2.01 of this game (from TDC) with added sound among other things.
Note that 1.0 is 1993 & 2.01 is 1995.

[Vlak v2.01 (Cs) [FW] (1995)(GEMA Soft) [Action, Strategy].zip](https://github.com/exoscoriae/eXoDOS/files/11602951/Vlak.v2.01.Cs.FW.1995.GEMA.Soft.Action.Strategy.zip)

**Comment by exoscoriae** [comment]
replaced
