### ISSUE TITLE
Robot Rascals (1987)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4413]
I found better

- [x] Luck Cards
- [ ] Item Cards

The scan is marginally better but they are in english (as opposed to the german ones in the collection) and they have the correct amount.  (some cards are needed more than once)

I also found the

- [x] Reference Card

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced... but none of this got set "to do", so I didn't see it here.
