### ISSUE TITLE
Aftershock for Quake (1996)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4418]
Enhancements:

Aftershock for Quake (1996).zip - CUE/BIN version (we have ISO). It's also slightly newer than our version, and has different installer, and missing RATING.TXT (ratings of included levels). Otherwise, it's the same.

Aftershock for Quake (1996) (Deluxe Edition).zip - truncated version of our disc, but it has two dozens of maps in SINGLES dir that isn't in our version.

**Comment by exoscoriae** [comment]
replaced with bin\cue

the maps in the singles folder do not show up in the front end. so unless I build a launcher for them, they aren't useful.
