### ISSUE TITLE
Jack Nicklaus Golf and Course Design - Signature Edition (1992)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4427]
We have installed floppy or hacked CD-version, without sources.

I uploaded CUE/BIN as Jack Nicklaus Golf and Course Design - Signature Edition (1992).zip.

Warning: resources are mostly the same, but all EXEs are different, so it worth to reinstall, probably.

**Comment by exoscoriae** [comment]
replaced game
