### ISSUE TITLE
NFL Challenge (1985)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4430]
I found fan-version of it, dubbed "The Complete Edition". It's mostly identical to our version - only has a _metric ton_ of commands and leagues meticulously added, from 1946 to 2020.

Uploaded as NFL Challenge (1985) The Complete Edition.zip.

**Comment by exoscoriae** [comment]
added as a launch option

**Comment by exoscoriae** [comment]
unable to get it running properly. fan disk are expected to have a pbp.nfl, pls.nfl, and plyb.nfl file.

most of the folders that are here as add on disks do not have these.

even when I load them, it shows the same nfl team names every time. even if I try to load ncaa teams. clearly I don't understand how to use these team disks, but there is no documentation in the file that i see.

@SmilingSpectre
