### ISSUE TITLE
Elder Scrolls Legend, An - Battlespire (1997) Guidebook

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4446]
This book, counter-intuitive, named "Battlespire Athenaeum". But it's walkthru, anyway.

Battlespire Athenaeum.pdf uploaded.

**Comment by Eulisker** [comment]
I found

- [ ] Letter
- [ ] Reference Card

Added to the github folder.

**Comment by exoscoriae** [comment]
added
