### ISSUE TITLE
Pac Man (1982)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4471]
How to Win at Pac-Man.pdf

Strategy guide for winning Pac-Man techniques!

**Comment by Eulisker** [comment]
I found

- [ ] Pac-Man Fever - Sheet Music

It is a bit unusual but maybe worth adding. :)

Added to the github folder.

**Comment by exoscoriae** [comment]
This should be on Pac-Man (1993)
moved
