### ISSUE TITLE
Mad TV (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#448]
No English language 
Language(s): de
page 2 is missing
has watermark Taken from Amiga-Manuals-Website

**Comment by exoscoriae** [comment]
I don't believe there ever was an english version.

Watermark was not removeable.

**Comment by TimberlAndRE-de** [comment]
@exoscoriae now you become a believer ;-)
i found an english (&german) version of the manual and without the watermark
still the 2nd page is missing (blank page) and pages 45-65 are missing (probably spanish language)
but at least we have an english manual now (of course uploaded to dropbox)

**Comment by exoscoriae** [comment]
how is there an english manual for a game that isn't in English?? is there an english version of MAD TV?

**Comment by TimberlAndRE-de** [comment]
what do you mean? the eXoDOS version is already MLA english/german?

![Unbenannt](https://user-images.githubusercontent.com/67441153/86209048-030beb00-bb72-11ea-8d21-25611f987b7d.JPG)

![Unbenannt2](https://user-images.githubusercontent.com/67441153/86209061-069f7200-bb72-11ea-8ba0-f1abfeb68f50.JPG)

**Comment by exoscoriae** [comment]
crazy. I could have sworn it was german only.

Added manual.

**Comment by Eulisker** [comment]
Manual in 

- English
- German
