### ISSUE TITLE
Fallout (1997) Official Survival Guide

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4509]
Our version is awful, but has a good readable text. I cropped it and cleared. It's

- William H. Keith, Jr., Nina Barton - Fallout - Official Survival Guide (Greyscale, warped, but good text).zip

I found much the guide with much better quality. With one, but significant problem: it was scanned without disassembling, so edges of the pages sometimes are curved and unreadable. It's

- William H. Keith, Jr., Nina Barton - Fallout - Official Survival Guide (Good, but pages curved).zip

Select yourself. Or keep both.

**Comment by exoscoriae** [comment]
replaced
