### ISSUE TITLE
Burntime (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4513]
As discussed by smiling spectre and flay on discord. To summarise:

There are a number of bugs in our current exodos version.

1. The time to travel between locations in the English version is always 1 day, which is a bug and makes the game too easy. In the German version, every route has a specific travel time between 1 to 4 days
2. Broken animation when entering the monastery. There is a screen rip and the lips of the priest aren't moving, as you can see here: https://youtu.be/_XEoJIMRUsQ?t=2524
3. At the victory screen there are 1-2 lines of text missing. The English version starts with "..gain control of all the..", as you can see here: https://youtu.be/q18e9XW4vKM?t=1682. The text should really start with something like "After a hard-fought battle.."->"PLAYERNAME managed to.." like in the German version here: https://youtu.be/qnXThHPyOV0?t=2860

Smiling Spectre has navigated a way to fix all the above issues. Use the files in this zip [BURNTIME_FIXED.ZIP](https://github.com/exoscoriae/eXoDOS/files/11706441/BURNTIME_FIXED.ZIP)

He has fixed the translation files to correct the bugged text but due to various native bugs in the English exe files he has used the German version exe. A summary of the three available exes and their issues is:

1. Hacked English exe (current in exodos): No voiceovers, all distances are 1 day apart bug.
2. CD English exe: Occasional voiceovers (in German as all versions, English or German, only have German .voc files). Right travel times, but a new bug where no water is replenished which is a game breaking bug: you simply will not be able to support your army.
3. CD German exe: Voiceovers always play where they are expected, right travel times, right water replenishment.

One other thing with Spectres files is it uses a different CT-Voice file which requires using irq 5 in the conf (which he provided in his zip). You could probably use the current CT-Voice file we have and keep the current [sblaster] settings from our current conf if you prefer.

**Comment by exoscoriae** [comment]
files replaced. thank you.

**Comment by Python-Exoproject** [comment]
For this game to work the files need to be in the folder BURN, so \eXo\eXoDOS\burntime\BURN.

**Comment by exoscoriae** [comment]
moved the files.

however I had tested it and it worked prior?
