### ISSUE TITLE
Space Commanders II (1985)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4519]
Game needs ASPECT FALSE added to autoexec

**Comment by exoscoriae** [comment]
done

**Comment by Python-Exoproject** [comment]
I think you made this change to Space Commanders (1983) instead of Space Commanders II (1985).

As Space Commanders II (1985) is now part of the work ive done on CGA composite and has a new conf ive made as a result there is no longer a need for this to be actioned on Space Commanders II (1985), however we should probably undo the change made to Space Commanders (1983)
