### ISSUE TITLE
Biing! Sex, Intrigue and Scalpels (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4520]
The installer for this game contains a playable Space Invaders clone called "Attack of the Mutant Hospital Equipment".

![grafik](https://github.com/exoscoriae/eXoDOS/assets/67441153/fa333482-528b-45d7-8aab-c1740eeb96d4)

It could be added as an additional option in the run.bat by using "kpush.com" (it's in my personal upload folder under "tools":

```
:AOTMHE
cls
kpush "9"
D:
@INSTALL
goto quit
```

**Comment by exoscoriae** [comment]
nice find. added
