### ISSUE TITLE
Destination Mars! (1991)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4521]
I found

- [x]  Manual (Floppy Version)
- [x]  Task Cards
- [x]  Reference Card (Later Floppy Version)
- [x]  Poster 1
- [x]  Poster 2

The manual and Task Cards are from the 1991 floppy version. The reference card is for a later floppy version that is based on the cd version currently in the collection.
All added to the github folder.

**Comment by exoscoriae** [comment]
added as needed.
