### ISSUE TITLE
mistakes in run.bat files

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4522]
- [x] Caesar (1993): a typo in "Caes**e**r can be combined...", should be "Caes**a**r can be combined..."

**Comment by TimberlAndRE-de** [comment]
Ah
Important information for the language packs too
(at least if they added the games too)

@Eulisker we need to rename the folders in the GLP too
I added this to the GLP project so I won't forget this when I'm back home ;-)

**Comment by exoscoriae** [comment]
yea, that is why I noted it. I rarely, if ever, make changes to the folder names. But since I did it here, I wanted to note.

**Comment by TimberlAndRE-de** [comment]
Yes, that's perfect, thank you
I usually read all the GitHub issues if they get closed 👍🏻
