### ISSUE TITLE
Call of Cthulu - Shadow of the Comet (1993)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4523]
As I accidentally noticed on Moby, CD-version includes "Museum" extra. Checked, and it's true.

To activate it, start "MUSEUM.EXE" instead "SHADOW.EXE". I recommend to add it to the start options.

**Comment by TimberlAndRE-de** [comment]
should be already in v6 according to this github entry: #3366 
?

**Comment by SmilingSpectre** [comment]
Ah, it already was done. Sorry.
