### ISSUE TITLE
Disney Presents - The Animation Studio (1990)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#4576]
Discovered the copy protection for Disney Presents - The Animation Studio (1990) was still active and could not find any reference to the codes in the v5 or WIP branch. I found an outline of the proper "mickey" codes on archive.org to be included as the copy protection codes.

![Disney Presents - The Animation Studio (1990) codes](https://github.com/exoscoriae/eXoDOS/assets/52749806/2fa606dd-7598-4d81-90a9-13eb11dc9f68)

**Comment by SmilingSpectre** [comment]
I can get amiga docs. Unfortunately, they haven't copy-protection, and somewhat tuned to Amiga. :(
