### ISSUE TITLE
Soccer Superstars

### ISSUE THREAD

**Issue by bmanbdaman** [exoscoriae/eXoDOS#4577]
It looks like the BIN is missing some sectors so the TRACK 10 CDDA is bad. CRC should be 9AA32786. CDDA is used for Oscar.

Get file from original published that match the date but someone maybe broke in transit.

https://www.abandonsocios.org/foro/index.php?topic=7809

This is also a compilation CD and Soccer Superstars could be broken out.

**Comment by SmilingSpectre** [comment]
Redump has the disk too.
https://myrient.erista.me/files/Redump/IBM%20-%20PC%20compatible/Leo%20the%20Lion%20(Spain)%20(En,De)%20(Covermount).zip

**Comment by exoscoriae** [comment]
replaced cd with new image.

not going to break the game out, as that would go against the preservation of the original media.
