### ISSUE TITLE
Mega Tetris (1994)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4588]
Mega Tetris
Year: 1994
Author: Tomasz Zawalski (TOMco.)
Shareware, unregistered version
For sound, there is in-game configuration, choose option 4 (only one working, for me at least)

[MT.zip](https://github.com/exoscoriae/eXoDOS/files/12072765/MT.zip)

**Comment by SmilingSpectre** [comment]
As it's "send me $5" type of the game, "unregistered" isn't necessary. I doubt there is any _registered_ version.

**Comment by exoscoriae** [comment]
added. disabled sound, as it caused controls to freeze
