### ISSUE TITLE
Spectre Towers (1989) Manual

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4590]
There are two Spectre Towers (1989) manuals. One is correct .doc, second is erroneous .txt. It needs to delete the second.

**Comment by exoscoriae** [comment]
not seeing this in the WIP

**Comment by Python-Exoproject** [comment]
I also had the extra file present, however it was just a file the sync was reluctant to clear from my system. Deleted manually on my end and it didnt come back
