### ISSUE TITLE
Perfect General II (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4596]
wysiwyg found

- [x] map book 1
- [x] map book 2

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
the maps were added to the wrong game, they're in the extras folder for `Perfect General, The (1991)` instead of `Perfect General II (1994)`

needs to be moved

**Comment by exoscoriae** [comment]
moved. good catch
