### ISSUE TITLE
Marrs (1996)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4608]
Title: Marrs
Year: 1996
Author: Rafał Zieliński (YesMan)

Game can be started with music or with sound. I've made quick setup with both options. Recommended ECE & Cycles=10000.
[Marrs (1996).zip](https://github.com/exoscoriae/eXoDOS/files/12148356/Marrs.1996.zip)

**Comment by exoscoriae** [comment]
added:
Marrs (1996).zip

Thank you for prepacking the game. I made slight modifications to it however. There was no need to have the game in there twice. Rather, just creating a copy of the config file and having the run file copy that config over at launch allows the game to switch between music and sound fx.
