### ISSUE TITLE
Krkal 1 (1997)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4609]
There is error message when starting game for a first time about damaged player file. Just delete PLAYERS.INF file. It will remove created gamer profile & make "clean install".

**Comment by exoscoriae** [comment]
I found this ticket in the game submissions project. Moved it to bugs and processed it.

**Comment by Python-Exoproject** [comment]
The game zip in the WIP still has this issue. 

Hope its not because of the sync rrollback we did and that there arent other fixes that have been lost?

**Comment by XavierVelo** [comment]
No idea why I putted this in game submission, obvious error, sorry.

**Comment by exoscoriae** [comment]
deleted it again.

This one is old enough that it *should* have predated the sync.

maybe I didn't delete the original file? So when I rezipped it, it just added the files back to the original zip and retained the INF file?
