### ISSUE TITLE
Striker '95 (1995) CD and Floppy

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4613]
Friend from Abandonia passed me the CD of Striker '95. 90Mb, mostly animation and sound that are missed in our version.

But our version doesn't use this extra animation (and use the sound actually). So I conclude that our version is a floppy, and also badly ripped.

After some search, I found another version, very similar to ours, but with all missing sound and one change in the team list (ours has "Portugal" replaced with "Little fish", it seems).

Uploaded both as "Striker '95 (1995) Floppy.zip" and "Striker '95 (1995) CD.zip"

**Comment by exoscoriae** [comment]
cleared old files out. added both cd and floppy versions with menu and sound options.
