### ISSUE TITLE
Skiing (1984)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4614]
I feel this is running too fast to be able to doge the trees, though this could be subjective

**Comment by exoscoriae** [comment]
I tried 200, which is better in the beginning. But as more and more trees show up, there is significant slowdown.

I survived long enough at speed 300 to see the slowdown as well. At some point, the trees get so thick that it is basically impossible to keep playing, as there is no where to go.

I guess I'll set it to 250
