### ISSUE TITLE
F-15 Strike Eagle (1985)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4615]
The autoexec section of the conf for this game is:

cd ..
cd ..
imgmount a .\eXoDOS\f15se\floppy\ega.img -t floppy
c:
cls
@boot -l a
exit

This works in vanilla dosbox, but not ECE or staging. So that the game runs using the alt launcher change the autoexec to:

mount c .\eXoDOS\f15se\floppy
c:
cls
@boot ega.img -l a
exit

This will work in all forks including vanilla

**Comment by exoscoriae** [comment]
great work. thank you. fixed
