### ISSUE TITLE
SimCity 2000 (1994) Simcity 2000 - Power, Politics and Planning -Nick Dargahi, Michael Bremer

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4628]
SimCity 2000 (1994) Simcity 2000 - Power, Politics and Planning -Nick Dargahi, Michael Bremer.pdf uploaded.

**Comment by exoscoriae** [comment]
already in pack

our version does not have archive.org watermark
![image](https://github.com/exoscoriae/eXoDOS/assets/8557582/d6e792ae-5b4d-4650-a8f1-0e9ed7ec1dbd)
