### ISSUE TITLE
Alternate Reality - The City (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4631]
Copy of the game is not complete. 

It has two graphics options on game start, "Color Graphics" and "Enhanced Color Graphics". Enhanced is EGA and works, but the other option which I assume is CGA says the game is missing the graphics files. Looking at the folder structure there is an EGA folder with ega resources but thats all.

**Comment by Eulisker** [comment]
trixter dumped and uploaded the missing CGA portion of the game. I uploaded the whole thing to the github folder.

**Comment by exoscoriae** [comment]
added cga folder. tested and worked.
