### ISSUE TITLE
Silly Master Blaster (1985), Black Box (1987), Star Chamber (1987) & Rain (1985)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4634]
Four more Pinball Construction Set creations. As per the original, the colour palette is considerably better using machine=tandy for both these games. They also need to be switched to ECE or Staging for the colours to be accurate in Tandy mode

**Comment by exoscoriae** [comment]
are these game submissions or bug reports?

**Comment by Python-Exoproject** [comment]
Bug reports, all these games exist in exodos WIP

**Comment by exoscoriae** [comment]
thank you. changes made
