### ISSUE TITLE
Math Rabbit (1986)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4637]
This is currently the 1993 version 2 release which is quite different to the 1986 version 1 release.

Spectre has provided a copy of the actual 1986 release: 
[Math_Rabbit_v1.1_1986Learning_Co._Inc._The_Educational.zip](https://github.com/exoscoriae/eXoDOS/files/12304059/Math_Rabbit_v1.1_1986Learning_Co._Inc._The_Educational.zip)

**Comment by exoscoriae** [comment]
Fixed metadata for 86 version
added "math rabbit deluxe", as this was the name for the 93' version

![image](https://github.com/exoscoriae/eXoDOS/assets/8557582/62fce057-3751-4145-908d-f3a193f41e97)
