### ISSUE TITLE
Gorillas - The Deluxe Edition (2007)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4642]
Here's the file from TDC
[GORILLAS- The Deluxe Edition v2.2 (2007)(Daniel Beardsmore) [Strategy].zip](https://github.com/exoscoriae/eXoDOS/files/12328927/GORILLAS-.The.Deluxe.Edition.v2.2.2007.Daniel.Beardsmore.Strategy.zip)

**Comment by exoscoriae** [comment]
added as:
Gorillas - The Deluxe Edition (2007)
