### ISSUE TITLE
Assorted game companies' catalogs

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4648]
Added in Books/Catalogs

- [ ]  3DO Company, The - Product Catalog 1997
- [ ] Access Software Incorporated - Catalog (1990)
- [ ] Accolade Catalog '90
- [ ] Accolade Catalog '90-91
- [ ] Accolade Catalog '91
- [ ] Accolade in Motion (1992)
- [ ] Accolade Product Catalog 1992
- [ ] Action Sixteen Catalog
- [ ] Activision Catalog (1986)
- [ ] American Educational Computer - An Educational Catalog of Educational Software
- [ ] Avalon Hill 1988 Catalog
- [ ] Avalon Hill Catalog Fall-Xmas '82
- [ ] Britannica Software - Presenting Our Family To Your Family (1987)
- [ ] Broderbund Software -  Catalog (1987)
- [ ] Broderbund Software - 10th Anniversary Catalog (1990)
- [ ] Broderbund Software - 1988 Catalog
- [ ] Broderbund Software - Software Catalog
- [ ] CBS Software Catalog (1983-1984)
- [ ] CBS Software Catalog (1984)
- [ ] Cinemaware - Product Catalogue (1989-1)
- [ ] Cinemaware - Product Catalogue (1989-2)
- [ ] Classic Quests Catalog
- [ ] ComputerEasy - Catalog (1990)
- [ ] Data East - Catalog Of Games - 1989
- [ ] Data East - Catalog Of Games - 1990
- [ ] Datasoft - Catalog (1983)
- [ ] Datasoft - Catalog (1985)
- [ ] Electronic Arts -  Computer Games 1990-91
- [ ] Electronic Arts -  Winter 1989 Catalog
- [ ] Electronic Arts - 1987-88 Catalog
- [ ] Electronic Arts - 1992-93 Catalog
- [ ] Electronic Arts - 1993-1994 - The Catalog
- [ ] Electronic Arts - 1997 Catalog
- [ ] Electronic Arts - CD-ROM Classics Catalog (1995)
- [ ] Electronic Arts - CD-ROM Titles Catalog (1994)
- [ ] Electronic Arts - The Electronic Arts and Affiliated Labels Price List (1989)
- [ ] Electronic Arts Catalog (1992)
- [ ] Electronic Zoo - Catalog '90
- [ ] Epic Megagames Catalog (1995)
- [ ] Epyx - Computer Software Catalog (1983)
- [ ] Epyx - Consumer Software Catalog - Spring 1985
- [ ] Epyx - Consumer Software Catalog - Spring 1986
- [ ] Epyx - Consumer Software Catalog - Winter 1985
- [ ] Epyx - Product Catalog (1987)
- [ ] Epyx - Product Catalog (1988)
- [ ] Epyx - Software Catalog - Spring-Summer 1989
- [ ] Epyx - Software Selection (1986)
- [ ] Epyx - Summer Catalog of Games (1982)
- [ ] Epyx Catalog (1982)
- [ ] Epyx Catalog (1986)
- [ ] Epyx Catalog (1987)
- [ ] Hatful of Hitsquad, A
- [ ] Hit Squad 1993 Catalog
- [ ] Impressions Catalog (1992)
- [ ] Infocom - Games and Accessories Catalog
- [ ] Infocom - Interactive Fiction
- [ ] Infocom - Passport to the Unified Products of infocom (1986)
- [ ] Infocom - The Incomplete Works of Infocom, Inc (1985)
- [ ] Infocom - The Master Story Tellers - Interactive Fiction Product Catalog - 1987
- [ ] Infocom Catalog (1983)
- [ ] Infocom Catalog (1988)
- [ ] Infogrames - New Age Catalog (1989)
- [ ] Infogrames - The Art of European Software Catalog (1990)
- [ ] Intracorp Inc. - 1993 Product Line
- [ ] Intracorp Inc. - 1995 Product Catalog
- [ ] Kixx-The Complete Range Catalog (1992)
- [ ] Legend Entertainment Catalog (1993)
- [ ] Legend Entertainment Catalog (1994)
- [ ] Legend Entertainment Product Catalog (1995)
- [ ] Legent Entertainment - Great Plays (1993)
- [ ] Level 9 Catalog (1985-1)
- [ ] Level 9 Catalog (1985-2)
- [ ] Level 9 Catalog (1985-3)
- [ ] Level 9 Catalog (1985-4)
- [ ] Level 9 Catalog (1986-1)
- [ ] Level 9 Catalog (1986-2)
- [ ] Level 9 Catalog (1988)
- [ ] Level 9 Catalog (1989-1)
- [ ] Level 9 Catalog (1989-2)
- [ ] Level 9 History (1986)
- [ ] Maxis - The Software Toys Catalog (1993)
- [ ] Microdeal - Autumn-Winter 85 Catalog
- [ ] Microprose - Catalog (1986)
- [ ] Microprose - Entertainment Software (1992)
- [ ] Microprose - Just for Fun! (1989)
- [ ] Microprose - Power Plus (1992)
- [ ] Microprose - Product Catalog (1988)
- [ ] Microprose - The Best of Times (1990)
- [ ] Mindscape - Catalog (1985)
- [ ] Mindscape - Catalog (1988)
- [ ] Mindscape Inc - Product Catalog (1987)
- [ ] Mindscape Inc - Sale Catalog (1988)
- [ ] Molimerx Ltd. - Software for the IBM PC (1985)
- [ ] New World Computing, Inc. - Computer Games (1992)
- [ ] New World Computing, Inc. - Computer Games Deals (1990)
- [ ] New World Computing, Inc. - Great Plays (1994)
- [ ] New World Computing, Inc. - Product Catalog 1996
- [ ] Ocean - Ride the Ocean Wave! (1992)
- [ ] Origin - 1989 Product Catalog
- [ ] Origin - 1990 Product Catalog-1
- [ ] Origin - 1990 Product Catalog-2
- [ ] Origin - 1990-91 Product Catalog
- [ ] Origin - 1991-92 Product Catalog
- [ ] Origin - Catalog (1987)
- [ ] Origin - New Products - 1989-90 Fall-Winter Update
- [ ] Origin - New Releases (1993)
- [ ] Origin - New Releases (1994)
- [ ] Origin - Product Catalog (1993)
- [ ] Penguin Software - Catalog (1984)
- [ ] Polarware Catalog (1985)
- [ ] Polarware News (1988)
- [ ] Polarware News Spring-Summer 1987 Edition
- [ ] Psygnosis 1993-1994
- [ ] QQP Catalog (1992)
- [ ] Scholastic Product Catalog Fall-Winter 1984-85
- [ ] Sierra - 15 - Winter Catalog 94-95
- [ ] Sierra - 1995-96 - The Games Catalog
- [ ] Sierra - Buyer's Guide - Fall 1998
- [ ] Sierra - Buyer's Guide - Fall '96
- [ ] Sierra - Buyer's Guide - Holiday 1998
- [ ] Sierra - Buyer's Guide - Spring 1998
- [ ] Sierra - Buyer's Guide - Spring 1999
- [ ] Sierra - Buyer's Guide - Spring '96
- [ ] Sierra - Buyer's Guide - Summer 1998
- [ ] Sierra - Buyer's Guide - Summer '96
- [ ] Sierra - Buyer's Guide - Summer '97
- [ ] Sierra - Buyer's Guide - Winter 1999
- [ ] Sierra - Buyer's Guide - Winter '97
- [ ] Sierra - Catalog (1988)
- [ ] Sierra - Catalog (1991)
- [ ] Sierra - Catalog (1992)
- [ ] Sierra - Catalog 1987
- [ ] Sierra - Catalogue - Games 96-97
- [ ] Sierra - Discover The Many Worlds Of Sierra (1992)
- [ ] Sierra - Discoveries in Learning (1984)
- [ ] Sierra - Edutainment Catalogue - 1995-1996
- [ ] Sierra - Edutainment Catalogue - 96-97
- [ ] Sierra - Fall 1988
- [ ] Sierra - Hi-Res Adventures (1983)
- [ ] Sierra - Late-Breaking Game News (1993)
- [ ] Sierra - Multimedia Catalogue - 1994-1995
- [ ] Sierra - On CD - Sierra's Multimedia Line-up (1992)
- [ ] Sierra - Summer '88
- [ ] Sierra - The CD-ROM Catalogue - 1994
- [ ] Sierra - The Games Catalogue - 1995-96
- [ ] Sierra Originals - Catalogue - 1995-1996
- [ ] Sierra Originals - Play The Game (1997)
- [ ] Sirius - Product Catalog - Summer 1983
- [ ] Software Catalog for Your IBM PC or 100% Compatible Computer (1988)
- [ ] Software Toolworks Catalog (1991)
- [ ] Spinnaker - Catalog (1983)
- [ ] Spinnaker - Catalog (1984)
- [ ] Spinnaker - The Spinnaker Catalog (1986-1)
- [ ] Spinnaker - The Spinnaker Catalog (1986-2)
- [ ] SSI - 1989-1990 Catalog
- [ ] SSI - 1991 Catalog
- [ ] SSI - 1992 Catalog
- [ ] SSI - 1993 Spring Catalog
- [ ] SSI - 1993 Winter Catalog
- [ ] SSI - 1994 Summer Catalog
- [ ] SSI - Fall 1984 Catalog
- [ ] SSI - Fall 1988 - Winter 1989 Catalog
- [ ] SSI - Fall '85 - Winter '86 Catalog
- [ ] SSI - Fall '86 - Winter '87 Catalog
- [ ] SSI - Fall '87 - Winter '88 Catalog
- [ ] SSI - Spring 1984 Catalog
- [ ] SSI - Spring 1986 Catalog
- [ ] SSI - Spring 1987 Catalog
- [ ] SSI - Spring Catalog 1985
- [ ] SSI - Spring-Summer 1990 Catalog Supplement
- [ ] SSI - Spring-Summer 1991 Catalog Supplement
- [ ] SSI - Summer 1986 Catalog
- [ ] SSI - Summer 1987 Catalog
- [ ] SSI - Summer 1988 Catalog
- [ ] SSI - Summer 1992 Catalog Update
- [ ] SSI - Summer 1993 Update
- [ ] SSI - Winter 1985 Catalog
- [ ] SSI Catalog - 1996-1997
- [ ] SSI Catalog - First Half 1995
- [ ] SSI Catalog - Second Half 1995
- [ ] SSI Catalog - Second Half 1996
- [ ] Strategic Studies Group - 1988-1989 Catalog
- [ ] Sublogic - Software Guide (1982)
- [ ] Tiger Software - The 1989 Tiger Software Entertainment Review
- [ ] Topologika Software Catalogue (1988)
- [ ] US Gold - Catalog (1985)
- [ ] US Gold - Catalog (1987)
- [ ] US Gold - Gold in the City (1990)
- [ ] Virgin - Catalog (1993)
- [ ] Virgin - Spring 1994 Releases
- [ ] Virgin Mastertronic - Catalog (1989)
- [ ] Westwood Studios Catalog, The (1996)
- [ ] Westwood Studios Catalog, The (1998)
- [ ] Zenobi - Adventures Catalog

**Comment by exoscoriae** [comment]
all of this was added as it's own platform

**Comment by Eulisker** [comment]
I have scanned:

- [ ] Infogrames - The Art of European Software Catalog (1990)
- [ ] SSI - 1993 Winter Catalog
- [ ] SSI - 1994 Summer Catalog
- [ ] SSI - 1992 Catalog
- [ ] SSI - Catalog 1996-1997

All are quality improvements over the ones already there.

Is there a way to sort the catalogues chronologically? The SSI ones especially are all over the place right now.
