### ISSUE TITLE
Altered Destiny (1990) Amiga Clue Book

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4650]
I believe, game is identical, but it has "Amiga Clue Book" in the title.

It's also with "invisible clues", so, well, quite invisible.

I am uploading the text version of the book too. With quite plain clues, but without pictures then.

Altered Destiny (1990) Amiga Clue Book.pdf
Altered Destiny (1990) Amiga Clue Book.rtf

**Comment by exoscoriae** [comment]
added
