### ISSUE TITLE
BAT 2 - The Koshan Conspiracy (1992) Manual

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4653]
The "Real" manual. (We have now the CD-booklet instead).

BAT 2 - The Koshan Conspiracy (1992).pdf

Thinking about it, maybe it worth to replace CD manual too - this one is much more comprehensive. At least, worth to add as extra.

**Comment by Eulisker** [comment]
I found a better scan of the

- [ ] manual

Added to the github folder.
