### ISSUE TITLE
BAT 2 - The Koshan Conspiracy (1992) Scenario

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4654]
We haven't it at all
Will do for CD version too, I suppose.

BAT 2 - The Koshan Conspiracy (1992) Scenario.pdf

**Comment by exoscoriae** [comment]
added

**Comment by Eulisker** [comment]
I found a better scan of the 

- [ ] Scenario

Added to the github folder.
