### ISSUE TITLE
Chamber of the Sci-Fi Mutant Priestess (1989) Manual

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4659]
Better version. It has more pictures, and 3 languages. Too bad the scan is slightly worse.

Chamber of the Sci-Fi Mutant Priestess (1989).pdf

**Comment by exoscoriae** [comment]
prefer existing version. @TimberlAndRE-de I'll put it in the rejected folder in case you want it for the german manual
