### ISSUE TITLE
Doomdark's Revenge (1995) The Story. Audio version

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4665]
The audio-version of the story (written in manual) that was supplied on audiocassette for Amstrad.

- [x] Doomdark's Revenge (1995) The Story, Chapter 1 (Audio Tape).mp3
- [x] Doomdark's Revenge (1995) The Story, Chapter 2 (Audio Tape).mp3
- [x] Doomdark's Revenge (1995) The Story, Chapter 3 (Audio Tape).mp3
- [x] Doomdark's Revenge (1995) The Story, Chapter 4 (Audio Tape).mp3
- [x] Doomdark's Revenge (1995) The Story, Chapter 5 (Audio Tape).mp3

**Comment by exoscoriae** [comment]
added
