### ISSUE TITLE
VR Soccer '96 (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4668]
currently the game is setup with SB sound

but it can MT-32 and SC55 too

- rename README.TXT to READ.ME (otherwise setup won't start)
- start INSTALL.EXE
- when the sound setup asks if you want to use the soundcard for music too, choose no
- no you can chose between SB, MT32, SC55 ...

**Comment by TimberlAndRE-de** [comment]
...but they all sound very similar. But maybe it's worth to give the options anyway.

**Comment by exoscoriae** [comment]
pretty sure I looked into this at one point, and didn't offer the choice because it felt like it was just playing digital music? Not cd tracks.

**Comment by exoscoriae** [comment]
confirmed identical menu music.

leaving this out.
