### ISSUE TITLE
Earthworm Jim 2 (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4671]
on CD there are two additional features:

- [x] MOVIE.EXE - shows a short comic movie about Earthworm Jim
- [x] ToyShow.EXE - shows a slideshow of Earthworm Jim toys with a short description from the designers

worth to be added as options for a run.bat

**Comment by exoscoriae** [comment]
great finds.

added both.

switched to ece
changed from max cycles to 40k
