### ISSUE TITLE
Space School Simulator - The Academy (1987)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4675]
Interesting one here. Vanilla dosbox plays this game, but as it is now ECE and Staging do not. 

After a bit of poking and prodding I discovered that if you mount the folder as a: instead of c: then all three forks work fine which will allow the alt launcher to play the game. 

Weird that Vanilla will allow the game to run as c: but the others require a:, but it is what it is.

**Comment by exoscoriae** [comment]
fixed and switched to ece
