### ISSUE TITLE
Shultz's Treasure (1987) Manual

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4698]
Better version.

Shultz's Treasure (1987).pdf

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I found

- [ ] Manual 1982
- [ ] Manual 1987

The 1987 version is a different version of the budget manual we currently have. The 1982 version is the original version. The game seems to have been sold in a plastic bag so maybe the cover and back page of the manual should be set as front and back cover for the game. The current cover is for a budget rerelease by Computer Easy.

Here is a picture of the game in a plastic bag.
![1a81315a13fc071d22ecfe1b525df0b8](https://github.com/exoscoriae/eXoDOS/assets/81642149/dc3c55b0-9ef2-43dc-83e0-a3974e26ce2e)

**Comment by exoscoriae** [comment]
done
