### ISSUE TITLE
Robinson's Requiem (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#47]
found real manual
current one is text-version from underdogs

**Comment by bigjim161** [comment]
I found an extra -"The AWE White Booklet" 
![image](https://user-images.githubusercontent.com/67555221/107792066-fe88f100-6d54-11eb-9cbc-e670dadcc10f.png)

Added to the Github Folder

**Comment by exoscoriae** [comment]
added
