### ISSUE TITLE
Waterloo (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4711]
wysiwyg found

- [x] manual (it's also a typed down txt version, but current one is for Archimedes Systems, this new one contains IBM)

**Comment by exoscoriae** [comment]
replaced

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual (PSS version)

not a great scan, but it's better than the current typed down one - still need to find a good scan of the PSS or SSI version of the manual
the current typed down contains some further IBM install instructions not in the PSS manual or the PSS reference card we have because it's typed down from the SSI version of the manual - maybe keep this as an extra than until we find a scan of the SSI version too?

**Comment by exoscoriae** [comment]
replaced

**Comment by parricc** [comment]
xml file refers to: `Manuals\MS-DOS\Waterloo (1989).txt`
Actual file present in WIP is: `Manuals\MS-DOS\Waterloo (1989).pdf`

Looking at the above, I can see that eXo desired it to be the pdf version. I can push out a substitution along with my case corrections to make it pdf in the xml file.

**Comment by parricc** [comment]
Proposed change attached to https://github.com/exoscoriae/eXoDOS/issues/5333

**Comment by parricc** [comment]
Reopening as eXo prefers handling non-case xml issues on a case-by-case basis rather than as part of bulk set of changes.

**Comment by exoscoriae** [comment]
fixed earlier
