### ISSUE TITLE
688 Attack Sub (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4714]
There were a few tweaks to the words in 688 attack subs network.bat I have made. Mostly around some testing I did that cleared up what happens when the players are selecting colour, an extra line in the client section that must have been a left over from something else as it was out of place, and some words that were for the host in the client section and vice versa. 

Here is my version: [network.zip](https://github.com/exoscoriae/eXoDOS/files/12409181/network.zip)

Lastly, during testing it seemed that a good connection only happened if the host selected "auto-answer" before the client has selected "originate". Makes sense as the host machine needs to be waiting the incoming call. Do you think its worth adding as a note in the network.bat?

**Comment by exoscoriae** [comment]
added your network file and added the note you mentioned.
