### ISSUE TITLE
Dark Legions (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4717]
Now that we have fixed the overall packs default fluidsynth volume level we need to fix the exceptions. 

For Dark Legions add to run.bat in the :sc55 section
CONFIG -set "fluid.gain=2"

Also, while retesting that this is the appropriate setting I noticed that the scroll speed is ridiculous due to cycles=max. I tried cycles=20000 and it seemed much better. Lastly the game seems a bit unstable as it hung during movement of the characters 1 out of every 5 test runs, but not much we can do on that I think

**Comment by exoscoriae** [comment]
cycles were not set to max. they were set to auto, which was assuming max.

set them to 20k.
