### ISSUE TITLE
Boom (1994)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4720]
Discord user Viliam wrote: When I quit Boom (1994) by pressing the Esc key, I get the black DOS screen with prompt "A:". Typing "exit" does not help, I need to close the black screen by pressing Ctrl+F9.

Game starts with booting disk image, also starts without sound. One solution is: unpacking ima file, make setup & start from unpacked folder.

**Comment by exoscoriae** [comment]
Did you actually test this?

I wouldn't have set a game to boot from an image, if it wasn't necessary.

**Comment by exoscoriae** [comment]
great fix @XavierVelo
