### ISSUE TITLE
Millie's Math House(1994)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#4721]
This game is not on the Dos masterlist",  not on the missing list, and not in TDC 
Mobygames : https://www.mobygames.com/game/34976/millies-math-house/
Genre:  Educational
Developer:  Theatrix Interactive, Inc.
Publisher:  Edmark Corporation
Released:  1994
Language: English 
Format: bin+cue

Added to the github folder with covers and manual

**Comment by exoscoriae** [comment]
added
