### ISSUE TITLE
Final Assault (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4722]
This may not actually be an issue, but the game loads with a menu that offers graphics mode for EGA. If chosen, the displayed graphics are still CGA. According to Mobygames the EGA mode still only utilises the 4 colour CGA palatte, but this makes no sense to me as why have the option if its the same as the CGA output?

I think we should keep an eye out for physical copies to purchase and confirm if bad online dump, but open to opinions. @SmilingSpectre Do you have any thoughts?

**Comment by SmilingSpectre** [comment]
Actually, this game has exactly the same mechanism as SideWalk before - and moreover, it's the same company. You can select anything, but system either goes "CGA" way for the most of the cards, or "Hercules" way for monochrome. So I am starting to think that it's one and only version... just as the SideWalk. But it's always hope. :/

TDC has kryoflux version (the same as the file version of ours), so it looks not a hack, at least.

**Comment by exoscoriae** [comment]
Sidewalk is corrupted. No doubt about it.

**Comment by exoscoriae** [comment]
moving this to low priority.
