### ISSUE TITLE
Firezone (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4723]
This game is capable of EGA according to Mobygames screenshots and an image of the box front I found at https://www.ebay.com/itm/175671320993

Not sure if the copy available online is a bad dump that doesnt include the EGA files or its a setting I havent discovered, but I lean towards needing to install from the original and choosing EGA at that point.

TLDR: I think we need to locate a physical copy or alternate dump. @SmilingSpectre Know of any different dumps to the one we have?

**Comment by exoscoriae** [comment]
![image](https://github.com/exoscoriae/eXoDOS/assets/8557582/2a7b278f-17ca-44f1-a6d6-e8b2530cab48)
A physical copy would be great, but I'm not spending that much on it.

I agree though, it would be good to keep an eye out for another dump

**Comment by SmilingSpectre** [comment]
Exo, try this: 
https://www.ebay.com/itm/334391426828
or at least this:
https://www.ebay.com/itm/195343352207

**Comment by exoscoriae** [comment]
neither of those auctions panned out @SmilingSpectre

**Comment by exoscoriae** [comment]
just purchased a copy for $28 after shipping.

**Comment by exoscoriae** [comment]
ega is now available
