### ISSUE TITLE
Frank Bruno's Boxing (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4724]
Not that I want to move more games to X, but this game allows colour if set to machine=amstrad and only X allows that setting. If swapping to X remember to change fullresolution=0x0 to fullresolution=desktop

**Comment by exoscoriae** [comment]
it may look better, but it's not how it looked on DOS.

At this point, isn't this the same thing as deciding he Amiga version of a game looks better, so using that instead of the DOS one?

**Comment by Python-Exoproject** [comment]
Now that im back at my PC, as per discord messages this is the same as using machine=tandy. Information as per http://nerdlypleasures.blogspot.com/2016/04/the-amstrad-pc-1512-affordable-pc-for.html?m=1

**Comment by exoscoriae** [comment]
changed to X and set to amstrad

**Comment by Python-Exoproject** [comment]
Fullresolution is still 0x0, needs to be switched to fullresolution=desktop

**Comment by exoscoriae** [comment]
good catch. done
