### ISSUE TITLE
Kristor (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4731]
Couple things for this one:

1. Its all in French and I have no idea what is going on or what the buttons do
2. It should be changed to machine=cga as this makes the game screen (one your finally in to the game) easier to read and the status screen doesnt get squished
3. There is an audio tape that is supposed to be played in sync with the intro graphics. The French paragraphs at the start that contain the words "ESC" and "musique" are referring to it and when to play it. Here is a copy of the music: [Kristor - Cassette.zip](https://github.com/exoscoriae/eXoDOS/files/12464831/Kristor.-.Cassette.zip). Not sure how we can set this up to play at the right time though
4. I believe it maybe running to fast but its hard to tell. The manual when translated says something about the bar that keeps ticking through being days that pass and if that the case they go by pretty fast

**Comment by Eulisker** [comment]
For 3. the only thing that comes to mind is making a video of the intro, syncing it with the tape and adding it as an extra.

**Comment by Python-Exoproject** [comment]
I wonder of Boohyaka might do it, he could understand the prompts and by them know when it should be queued up

**Comment by exoscoriae** [comment]
switched to CGA
dropped to 1500 cycles
added mp3
added note to start it with the game
