### ISSUE TITLE
Pro Pinball - The Web (1995)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4734]
Patch upgrading from 1.00E -> 1.52p.
List of changes here:
http://www.pinball.org/rules/theweb.html#Changes

Note from readme: "If you are using UNIVBE you will need to run UVCONFIG.EXE before running the
new version of the game."

I'm not sure if step above in necessary, I did upgrade without it :/

Edit: backglass picture is changing after upgrade, maybe worth keeping old one as screenshot (included)
![frontend_000](https://github.com/exoscoriae/eXoDOS/assets/66518085/83ce4494-06f5-4141-9386-b9a131e57fd6)

[web152pb.zip](https://github.com/exoscoriae/eXoDOS/files/12472420/web152pb.zip)

**Comment by exoscoriae** [comment]
patched
