### ISSUE TITLE
Udoiana Raunes 3 - In Search for Indiana Jones 4 (2003)

### ISSUE THREAD

**Issue by nikeymikey** [exoscoriae/eXoDOS#4738]
Game plays but user is unable to select any action, "Walk To" is permanently selected. this stops progress form being made into the game.

**Comment by Python-Exoproject** [comment]
Confirmed, everytime you click on one of the other interaction options it flicks straight back to walk

**Comment by exoscoriae** [comment]
nice fix @Eulisker 

I changed the name in LB to "3"... was there ever a 2?
