### ISSUE TITLE
Planetfall (1983)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#4740]
Found the Infocom Book of Planetfall written by Arthur Byron Cover.

[Planetfall - Arthur Byron Cover.pdf](https://github.com/exoscoriae/eXoDOS/files/12501768/Planetfall.-.Arthur.Byron.Cover.pdf)

**Comment by exoscoriae** [comment]
it is damaged and won't let me open it

**Comment by matthew-goddard** [comment]
Try this link instead: https://www.dropbox.com/scl/fi/5855ax7dvmrh5qgg9wtob/Planetfall.-.Arthur.Byron.Cover.pdf?rlkey=uohu1bmeloegesatk8qth18sa&dl=0

**Comment by exoscoriae** [comment]
![image](https://github.com/exoscoriae/eXoDOS/assets/8557582/ce5d6848-9624-4af0-9ac0-928f633e2066)

**Comment by matthew-goddard** [comment]
Looking at the PDF this seems to have been a .cbr originally and I think got renamed. The default images for contents makes me think that. Assuming it was I went to convert the original file through an online service and it spit out a 143MB file!

There is also a version on archive if someone can login and borrow? https://archive.org/details/planetfall00cove/mode/2up

**Comment by exoscoriae** [comment]
thank you for all of that.

it has been added

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre found

- [ ] Novel (better clean scanned and not edited version) - quality upgrade

**Comment by exoscoriae** [comment]
replaced
