### ISSUE TITLE
Brix II (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4741]
This game has a mapper file, but it doesnt look like its doing anything as all the keys are default assignments. If you remap the keys:

right shift (move left) > left arrow
left shift (move down) > down arrow
alt (move up) > up arrow
caps lock (move right) > right arrow

The responsiveness in game to the direction keys improves significantly. 

I dont think ive ever seen more weird ass default controls

**Comment by exoscoriae** [comment]
there was no mapper file in that folder for me.

Created one with the above designations.
