### ISSUE TITLE
Lurid Land (1997)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#4742]
Title: Lurid Land
Year: 1997
Dev: Illusion Softworks
Publisher: Abadion Arts

[Lurid Land (1997)(Illusion Softworks) [Action, Puzzle].zip](https://github.com/exoscoriae/eXoDOS/files/12503826/Lurid.Land.1997.Illusion.Softworks.Action.Puzzle.zip)

**Comment by exoscoriae** [comment]
added
