### ISSUE TITLE
Astro-Dodge (1982)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4747]
Game is squished.

Only fork I found that would run it correctly is the staging alpha build.

If you go ahead with the change to this build for the game you will also need to delete the existing mapper file and recreate inside staging it or you will be unable to interact with the game.

**Comment by kcgen** [comment]
Recording by Trixter on original '82 hardware: https://www.youtube.com/watch?v=YG4Ew8njw6I

> "This footage was recorded from an IBM PC (8088 CPU running at 4.77MHz) with a ("new-style") CGA card.  The audio was tapped from the PC speaker and the video was recorded from the CGA composite output.  The result was post-processed from 30i to 60p; all source frames are intact.  This video can be considered a reference for how this game performs on this platform.  The original game has no sound, so this video is also silent."

**Comment by Python-Exoproject** [comment]
Due to use of staging 81 alpha please switch to this conf 
[conf.zip](https://github.com/exoscoriae/eXoDOS/files/12572572/conf.zip) in order to not force the auto shader

**Comment by exoscoriae** [comment]
replaced
