### ISSUE TITLE
Demon Attack (1983)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4748]
Two things for this one.

1. Why do we offer both the tandy and the pcjr options? They seem to me to be the same game except for the title screen for the Tandy version, so why offer the pcjr version at all?

2. This game is using the new staging alpha and you arent using the staging template I created. As a result the game is defaulting to the new auto crt shader for the main launch option. Use this [dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/12551337/dosbox.zip) (this is only a tandy conf as per point 1)

**Comment by exoscoriae** [comment]
1. Why Not. (actual answer is originally the Tandy version was acting up, but PCjr worked fine. Eventually we got both working)

2. changed template

**Comment by Python-Exoproject** [comment]
You updated the PCJR conf to work with staging 81 alpha (dosbox.conf) but not the Tandy one (dosbox2.conf) so the Tandy still defaults to the auto crt shader.

The conf I posted in the opening comment of this ticket is the Tandy one so just use that to replace dosbox2.conf
