### ISSUE TITLE
Olympic Soccer (1996) - Game does not start

### ISSUE THREAD

**Issue by nikeymikey** [exoscoriae/eXoDOS#4752]
Upon launching the game dosbox opens but the game does not start, just a black screen.

**Comment by Python-Exoproject** [comment]
Confirmed @exoscoriae. I fixed it by using setup to reconfigure the game

Thanks @nikeymikey

**Comment by nikeymikey** [comment]
No worries :)  Turns out its a terrible game anyway lol. Played enough to record a video for the project and gave up lol

**Comment by exoscoriae** [comment]
fixed
