### ISSUE TITLE
World Class Soccer (1990) alternate game

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4755]
As manual clearly shown, the game was reissued as Italy 1990. It has minor gameplay differences: in particular, I noticed the different title screen and streamlined gameplay (in World Class Soccer you always select the team formation and players, in Italy 1990 it's reserved for World Cup, while in friendly matches it's country selection only).

Maybe worth to add as the alternative? It's in TDC as Italy 1990 (1989)(U.S. Gold Ltd.) [Sports].

**Comment by exoscoriae** [comment]
added as alternate launch within game
