### ISSUE TITLE
Rick Davis's World Trophy Soccer (1989) alternate manual

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4756]
There is specific "Rick Davis" manual, significantly different from the "Italia" one. Unfortunately, only one I found is lowres and with watermark. Uploaded it anyway.

Rick Davis's World Trophy Soccer (1989).pdf

**Comment by TimberlAndRE-de** [comment]
double entry, added to the first one (#559)
