### ISSUE TITLE
Space Commanders II (1985)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4758]
In normal vid modes it is black and white with vertical lines which is a tell tale of a CGA composite game and sure enough CGA composite works, however its monochrome composite which is unusual considering the first game was colour. 

Possibly game needs a better dump that would allow colour CGA composite. Thoughts @SmilingSpectre?

**Comment by SmilingSpectre** [comment]
We already discussed it, @Python-Exoproject . I didn't found another version. For some time I even thought that SCII is unofficial conversion... but then discover that both have the same author. *shrug* I haven't any explanation for that.

**Comment by exoscoriae** [comment]
this ticket is speculation. And we have no proof that there is anything beyond what we currently have, Closing
