### ISSUE TITLE
Blockout (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4760]
John Novak has noticed that our copy of the files is incomplete.

He has provided a complete copy
[Blockout.zip](https://github.com/exoscoriae/eXoDOS/files/12572505/Blockout.zip)

The difference is graphics options

**Comment by exoscoriae** [comment]
replaced files with files from "drive\c" folder

added note to uninstall and reinstall game if the user wishes to change their graphics selection
