### ISSUE TITLE
King's Quest I - Quest for the Crown SCI (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4762]
This game offers CGA option and currently CGA choice gives this:

![image](https://github.com/exoscoriae/eXoDOS/assets/67406191/78365c4d-8525-4900-ba30-671b4d8d6bbd)
![image](https://github.com/exoscoriae/eXoDOS/assets/67406191/01b450b5-7110-4407-b971-fda964669253)

This is an obvious composite CGA picture, and sure enough if you turn composite on you get a monochrome composite CGA image:

![image](https://github.com/exoscoriae/eXoDOS/assets/67406191/90483aba-a969-48b8-a75b-a1e9d767e9b1)
![image](https://github.com/exoscoriae/eXoDOS/assets/67406191/e5521461-269c-439f-aa7e-2f33ebcbdd77)

But to do this you need machine=cga which is going to necessitate using exception.bat to switch machine type which is already doing the dosbox\scummvm choice.

We can either remove the monochrome CGA option or you can set the game up to allow the needed machine switch. If you keep it, once its setup however you decide to do it I can look into adapting it to use the same composite choice setup ive given all the other composite games

**Comment by exoscoriae** [comment]
ok. added option for both.  exception allows composite CGA or EGA (shitty CGA).
