### ISSUE TITLE
"NCAA - Road to the Final Four" Gameplay issue

### ISSUE THREAD

**Issue by nikeymikey** [exoscoriae/eXoDOS#4763]
Game starts and you can get into the actual game but.. The basketball either goes missing form the screen or does it's own thing. Match seems to play on as the commentary says things like "out of bounds" etc but the ball is nowhere to be seen. 
Computer team runs around like they are super hot S%@t because they know where the ball is :)

**Comment by matthew-goddard** [comment]
I believe this was already fixed in #3950, in the WIP branch the game seems to run "better" but there still looks to be graphical artifacts and only what I can refer to as "tearing"?

**Comment by matthew-goddard** [comment]
Confirmed this is already fixed in WIP.
