### ISSUE TITLE
CJ's Elephant Antics (1993)

### ISSUE THREAD

**Issue by thethirdfall** [exoscoriae/eXoDOS#4773]
_Tested on eXoDOS 5.1 and Windows 10_

Two separate issues for the same game:

**1)** When you load the game, it asks you if you are using a joystick. If you select yes, you have to press fire while pressing in three separate directions - centered, top left and bottom right. After that, you get to the start screen, but the game does not react to pressing fire, or any keyboard buttons. The game is recognising the fire button when you configure the joystick, but not afterwards. 

Tested using a Xbox One controller on PC, connected by USB cable. 

**2)** If you do not select joystick, but keyboard, you get to the start screen. The game offers a choice of 1 or 2 players, but it seems impossible to select two players. I've tried every key, but nothing allows you to select two players.

**Comment by SmilingSpectre** [comment]
@thethirdfall Try to report issues in the forum. It's better to discuss here. Github is reserved for known issues that can be solved.

@exoscoriae problem confirmed. Right now CJ uses Vanilla, and joystick doesn't work (actually, game hangs after calibrating it). Switch to ECE to fix it.

Also, you can use 2 players (with button "2") if you have two controllers. Joystick+keyboard will do.

**Comment by exoscoriae** [comment]
switched to ece

**Comment by Python-Exoproject** [comment]
Spectre also suggested moving forks for the other CJ game, I think he meant `CJ in the USA (1993)`

**Comment by exoscoriae** [comment]
ok. moved CJ int he USA.

now he is in Mexico
