### ISSUE TITLE
Fussball Coach (1997) 

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4774]
game crashes at title screen if soundblaster is active.

when "KEINE SOUNDKARTE" was chosen at startup the game runs without problems - but also without sound ;-)

**Comment by TimberlAndRE-de** [comment]
added note to the dosbox.conf
until we find a solution, "KEINE SOUNDKARTE" has to be used at startup

**Comment by SmilingSpectre** [comment]
Change the card. sbtype=sbpro2 works for me.

**Comment by TimberlAndRE-de** [comment]
Great! works perfectly
Thanks a lot @SmilingSpectre
