### ISSUE TITLE
3D Hero (1997)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#4777]
ArkhangelAzrael found an english patch (the current version in exodos is in taiwanese).

Information here:

https://www.doomworld.com/forum/topic/132055-3d-hero-and-tao-obscure-taiwanese-ms-dos-games-with-custom-doom-based-engine-get-an-english-translation-patch/

added english patch to the github bugs folder

**Comment by exoscoriae** [comment]
patched to English version
