### ISSUE TITLE
Jagged Alliance - Deadly Games (1996)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4780]
The game is not patched to the newest version.

Here is the patch file. [dg113.zip](https://github.com/exoscoriae/eXoDOS/files/12776602/dg113.zip)

For some reason the patch .zip is included in the game zip (in jaggalld/cd/). That can be deleted.

Thanks to HoboHandsome on discord!

**Comment by exoscoriae** [comment]
patched
