### ISSUE TITLE
Sid Meier's Civilization (1991)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#4781]
Sid Meier's Civilization (1991) has a typo in the game name in WIP and the new builds. Saw on a youtube video post by @gemedetvideo on https://www.youtube.com/watch?v=Mpo_-pq347o 
The game Sid Meier's Civilization (1991) label in Launchbox is coming up as "Si Meier's Civilization" and confirmed on my local copy.

<img width="759" alt="2023-10-02 14_49_24-LaunchBox" src="https://github.com/exoscoriae/eXoDOS/assets/52749806/f11c199f-cdaa-4b5d-8a9b-15df8c87e93f">

**Comment by exoscoriae** [comment]
fixed
