### ISSUE TITLE
Locomotion (1992)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4782]
Currently there is a choice at the beginning to start the game in german or english and VGA or EGA. If you always want to start the game in english and vga you can start the game by calling "loco 2" instead of start.bat. You can use "loco 4" for english EGA if you want to give the choice.

![image](https://github.com/exoscoriae/eXoDOS/assets/81642149/f5f97dac-80e8-4b8a-9aa7-cd32e0497f8e)

E: This is not 100% true because you have to call the sound driver before starting the game. Otherwise you don't hear the music on the startup screen. You can either call it from the .conf or just edit the start.bat in the game folder.

**Comment by exoscoriae** [comment]
it seems to work fine as is. I'll leave it be. Thank you though
