### ISSUE TITLE
Think Quick! (1987) Manual and extras

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4784]
Think Quick! (1987) The Guide for Players.pdf - manual.
Think Quick! (1987) A Knight's Guide to the Castle of Mystikar.pdf - quickstart guide.
Think Quick! (1987) A Guide for Parents and Teachers.pdf

In Github

**Comment by TimberlAndRE-de** [comment]
They are all already included
(A Guide for Parents and Teachers is the current manual and the other two are extras)
