### ISSUE TITLE
BassTour

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4786]
We have v4.9s in the collection, and I believe "s" means some "special" edition, because while it seems registered, it haven't promised "ten lakes" in the batch.

I uploaded another version (marked simply v4.9, but the same v4.9s inside). It's mostly the same, but contains original records for the first 6 lakes and 12 more maps.

I uploaded also 50 maps from the different instances of Bass games of Dick Olsen. I believe, they can be simply dumped into game dir to be recognized.

BassTour v4.9 registered (1992).zip
BassTour Lakes.zip

**Comment by exoscoriae** [comment]
i added your 12 new maps.

the "50 maps" is hard to know what to do with it.  The game can only load 20 maps at a time. Anything more than that is ignored.

So to make the 50 useful, we would need some kind of menu system that copies maps in and out of the folder.

I have stored them in a MAPS folder with the game for now... but they are inaccessible
