### ISSUE TITLE
Leisure Suit Larry 2 Goes Looking for Love (in Several Wrong Places)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4791]
most sound options in run.bat are missing the "goto quit" line. Discovered by Flay and reported in discord. You fixed the run.bat and posted it in discord but on my end at least the game zip still has the incorrect run.bat file in it

Here the one you posted: 
[run.zip](https://github.com/exoscoriae/eXoDOS/files/12845149/run.zip)

**Comment by exoscoriae** [comment]
fixed
