### ISSUE TITLE
Hyperspeed (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4793]
Thorogin posted in discord that when you start a new game in the Hyades cluster, kill the initial ship that appears, and use the spindrive (press 'S'), the game freezes.

Spectre confirmed and reports its a bad crack

**Comment by Python-Exoproject** [comment]
[Crack.zip](https://github.com/exoscoriae/eXoDOS/files/14322896/Crack.zip)

Found this crack which works

**Comment by exoscoriae** [comment]
patched.

would be nice if we had a clean patch with no raw copy bs on it.

oh well.
