### ISSUE TITLE
Once Upon A Time - Abracadabra (1991)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4795]
The game is currently uncracked. I uploaded a cracked version to the github folder.

E: It also had a bug that causes the german version to not work. The other versions might crash somewhere else to. This version is fixed thanks to ripsaw8080

![image](https://github.com/exoscoriae/eXoDOS/assets/81642149/6354333a-5070-450c-9a71-8f5511a70d09)

**Comment by exoscoriae** [comment]
replaced. if we get bug reports, I'll reset it
