### ISSUE TITLE
Gunship (1986) Extra materials

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4804]
Set of extras uploaded by user baloo32.

- [ ] Codes
- [ ] Floppy Disk 3.5"
- [ ] Floppy Disk 5.25" (x2)
- [ ] IBM Keyboard Overlay
- [ ] Tandy Keyboard Overlay
- [ ] Loading Instructions
- [ ] Technical Supplement

Uploaded as Gunship Extras.zip

**Comment by TimberlAndRE-de** [comment]
added to #1105
