### ISSUE TITLE
ElfLand (1992)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4807]
Uses wrong CT-VOICE.DRV, so freezes in random moments and sounds wrong. Both parts. Experimenting shown it works good only with 1.x variation (I tried 1.13 and 1.14). Unfortunately, Github doesn't allow me to include it. :|

Maybe try to set SB to 1.0 too? No idea if it make it better or not.

**Comment by Python-Exoproject** [comment]
Is this in v6 WIP? I thought this was sorted with #3913. When I can get to my PC again ill have a look

**Comment by SmilingSpectre** [comment]
Aw. You are right then. Case closed.
