### ISSUE TITLE
Beneath a Steel Sky (1994)

### ISSUE THREAD

**Issue by boohyaka** [exoscoriae/eXoDOS#4808]
Few issues with BASS- game currently has 5 launch options: 
- Dosbox/SB
- Dosbox/MT32
- ScummVM/SB
- ScummVM/MT32
- ScummVM/James Woodcock's enhanced soundtrack

All versions but the Dosbox/MT32 seem to be the later CD release with the 5 minutes cartoon Intro. Dosbox/MT32 looks like the earlier floppy version, that has a short intro but an iconic theme song, that does not play at all. I have confirmed on real hardware that the MT32 intro has music on the floppy version. 

Also, both "ScummVM/MT32" and "ScummVM/James Woodcock's enhanced soundtrack" gives a MT32 error on launch. Game runs, but no sound plays.

Finally this brings the question to add both options of the floppy and CD releases like other games? The floppy has the different intro with the nice music, and obviously no voiceover.

**Comment by exoscoriae** [comment]
all versions are CD version. Roland does not support speech, and therefor the intro is cut.

All three ScummVM versions launch fine for me.
