### ISSUE TITLE
Grand Prix Circuit (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4810]
Discord user liuk reported crashing when selecting options other than EGA. @SmilingSpectre investigated and confirmed that our copy is a rip missing the required exe files for other graphics modes. Files provided: 

[Grand_Prix_Circuit_1988Accolade_Inc._Racing_-_Driving_Simulation.zip](https://github.com/exoscoriae/eXoDOS/files/13161891/Grand_Prix_Circuit_1988Accolade_Inc._Racing_-_Driving_Simulation.zip)

**Comment by SmilingSpectre** [comment]
It is a part of TDC additions actually... but, well, actually I want to ask: how do you insert .zips?! I never was able to do that.

**Comment by Python-Exoproject** [comment]
Just drag and drop. Wont take every file type but it does take zips

**Comment by SmilingSpectre** [comment]
Weird. Works at work, doesn't work at home. Same Opera. Same Windows. And it takes _some_ of the files, so it's not a general fault (gif, jpg or pdf inserted without a hitch). *shrug* Personal problem then. Ok, thank you.

**Comment by exoscoriae** [comment]
fixed
