### ISSUE TITLE
Space Quest II - Vohauls Revenge (1987)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4812]
Exodos scummvm version not working after we updated it to a newer version (2.0F) due to scummvm not detecting it. 

Simplest solution is to replace our exodos copy of the game with the files from our exoscummvm WIP as these are a different release of 2.0F which scummvm will detect

**Comment by exoscoriae** [comment]
fixed

**Comment by Python-Exoproject** [comment]
This was actioned but instead of replacing the existing version completely you copied the files into the folder. This has worked but left files behind that means the game folder is not very preservation friendly.

@boohyaka has provided a clean copy of the most recent 2.5" floppy version of the game which is what we were trying to copy into the folder in the first place: [SQ2 2.0F.zip](https://github.com/user-attachments/files/16414651/SQ2.2.0F.zip)

**Comment by exoscoriae** [comment]
repacked

**Comment by exoscoriae** [comment]
the issue is that even thoughy i delted the old files when I set it up,. when I zipped it it decided to update the existing zip file.
