### ISSUE TITLE
Star Command (1988) - Game Saving copy protection

### ISSUE THREAD

**Issue by chiefnewo** [exoscoriae/eXoDOS#4815]
Star Command won't accept the correct copy protection codes from the manual.

I found online that typing all A's for the passwords will work. 

I suggest putting an echo in the launch config if possible mentioning this.

**Comment by SmilingSpectre** [comment]
Confirmed. Both version in TDC are hacked like this. One is identical to ours, second has all passwords replaced with x.

**Comment by SmilingSpectre** [comment]
One of GOD floppy sets is fine though (second is identical to ours). It also v1.2, unlike ours 1.0.
[002841_star_command.zip](https://github.com/exoscoriae/eXoDOS/files/13185134/002841_star_command.zip)

**Comment by exoscoriae** [comment]
by "fine" do you mean it takes the copy protection codes from the manual? 
Or do you mean it is hacked to accept any input.

**Comment by exoscoriae** [comment]
replaced and noted

**Comment by Python-Exoproject** [comment]
It might also be worth adding to the user note that they should press '3' on the initial menu until it says "Hard Disk Drive". If they dont set that option they will be asked for a non existent disk 2 when the try to leave base
