### ISSUE TITLE
Various metadata issues and an enhancement for Raptor

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4825]
These are all reports by FistyDollars in discord

-------------------------------------------------

No icon for Retro Learning Pack playlist:

This almost doesn't qualify as a bug, but I think it's easily fixable. There's currently no icon for the Retro Learning Pack playlist, but I think if you copy and renamed the Education.png in Platform Icons/Playlists, that would be an adequate substitute.

-------------------------------------------------

Typo in Daggerfall name:

In v6, "The Elder Scrolls:  Daggerfall" has two spaces between Scrolls: and Daggerfall, when there should be only one in keeping with the naming conventions of the rest of the release.

---------------------------------------------------

White Death Front Box Art:

 It's currently tilted the wrong way, should be rotated 90 degrees

-----------------------------------------------------

Where in the USA is Carmen Sandiego Deluxe release year confusion:

the v6 metadata has it listed as 1991, but the bat file has it listed as 1994, and mobygames has the DOS version coming out in 1993

Also the enhanced edition came out in 1990 according to mobygames, but it's listed as 1991 in the metadata and 1992 in the bat file

------------------------------------------------------

Raptor: Call of the Shadows:

 changing controls gets overridden by sound card selection every time.

So I guess this is kind of two bugs in one -

1) There's no option to run setup.exe for the game, which is the only way (for some reason) to change whether you're going to use a keyboard, mouse, or joystick for the game. This can be bypassed by editing setup.ini and changing "control=0" to "control=1" for mouse, or "control=2" for joystick. Now that should solve the problem, except for...

2) Every time you start the game launcher in v6, it has you select a sound card, and it seems that no matter what you select, even if it's a card you used previously, this overrides setup.ini. Normally that wouldn't be a problem, but it doesn't just change the Music/SoundFX values in the ini file, it seems to revert "control=1/2" back to "control=0", making it effectively impossible to use the version in v6 with a mouse / joystick, no matter what.

(Similar solution to DOOM should fix)

----------------------------------------------------------

Soko-Ban box:

There are two box front images for this game, one of which should be obviously reclassified as box - back.

-------------------------------------------------------

Smuś:

Images won't show because of typo. Every image for the game "Smuś" is named "Smus" which Launchbox won't display due to the different letter at the end.

the same seems to be true for the game "Solidarność" . I would recommend checking every game with a special variation of a letter in their name.

----------------------------------------------------------

Heretic OST:

As MJY71 helpfully mentioned, the soundtrack for Heretic, despite the setting, wasn't actually composed in the Middle Ages, so the release year should probably be updated accordingly, from 0993 to 1993.

-----------------------------------------------------------

**Comment by exoscoriae** [comment]
all issues on this last have been addressed

**Comment by Python-Exoproject** [comment]
Updated the run.bat for Raptor to delete the previous sel files if changing options as it wasnt doing so and added the same warning we give in all the other games with this issue about the user needing to select their sound choice before trying to change anything in setup

[Raptor.zip](https://github.com/user-attachments/files/16180149/Raptor.zip)
