### ISSUE TITLE
Shattered Steel (1996)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4826]
Our copy is corrupted. Various text files are zeroed through missions (found it in World_2 only though). Mission 8 probably suffered most of all, as it even miss the "Win" text.

I uploaded the fine version.

Note: our version is international: English, German, French. I didn't found second like that - all versions on Myrient and Archive are strictly English.

**Comment by Eulisker** [comment]
We had it before in #3743 by the way but no project, no participant :)

I am adding timber here since I am sure we are using the base pack .iso for this game. 

I am also pretty sure I own the German version of this game. Maybe we can still change it before the GLP release.

**Comment by exoscoriae** [comment]
replaced cd image
reinstalled game
