### ISSUE TITLE
Phantasmagoria (1995)

### ISSUE THREAD

**Issue by matthew-goddard** [exoscoriae/eXoDOS#4831]
discord user miwa submitted a better quality version of the special featurette video "Gamesmaster - Gore Special - Feature - Phantasmagoria".

Can be grabbed from my dropbox: 
https://www.dropbox.com/scl/fi/cg54l7cayon6u04t6hz2x/Gamesmaster-Gore-Special-Feature-Phantasmagoria.mp4?rlkey=afw1crfxuyjtwtj2fs4q5qedl&dl=0

**Comment by exoscoriae** [comment]
replaced
