### ISSUE TITLE
Under a Killing Moon (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4833]
Discord user Aldranis has noted that the conf is set to use sbpro1 with opl2 mode. I didnt find any notes on why this might have been done.

Unless you can remember why that was done:

Delete the sblaster section lines from the conf to return to default sb16 settings, reset up the game for each sound mode to use sb16, and copy the new ini files into the relevant sound sub folders

**Comment by exoscoriae** [comment]
fixed
