### ISSUE TITLE
Father World (1994)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#4834]
English patch for Father World submitted by ArkhangelAzrael (The game is in Korean). **added to the github bugs folder**

Information from https://gamedevjeff.itch.io/fweng 

Latest version: **20231106 (Nov 6th, 2023)**   **Check here  https://gamedevjeff.itch.io/fweng for a newer version**

Download either the ENGPATCH.EXE or ENGPATCH.ZIP (the latter contains the former).  

Requires a copy of the game.   Put ENGPATCH.EXE in the main folder next to FW.EXE and run ENGPATCH.EXE under DOSBox/DOS.     Then read through readme.txt for the backstory and notes.

Note: The game does reward exploration to find who you need to meet and where to go, through reading dialogue.   

P.S.  About the save game slots.    Save names use Korean characters for letters but not numbers.   I may patch that later.  For now use numbers instead of letters, e.g. just keep incrementing the number for your save game 1,2,3..21,22,23...33..50,51,52...._ 

Requires a copy of the game.   Put ENGPATCH.EXE in the main folder next to FW.EXE and run ENGPATCH.EXE under DOSBox/DOS.     Then read through readme.txt use "more.exe readme.txt" for the backstory and notes.

If you need hints, there are 5 hint files to avoid spoiling too much:

HINT1.TXT, HINT2.TXT, HINT3.TXT, HINT4.TXT, HINT5.TXT

If you've never played the game before run FWSETUP.EXE to choose your soundcard (Sound Blaster) and if you have MT-32/SCC (midi) setup choose that option.  If you select no midi, the game will default to Adlib music which has its own charm.

**Comment by exoscoriae** [comment]
great find. patched
