### ISSUE TITLE
Super Angelo (2001)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4840]
[REGISTER.zip](https://github.com/exoscoriae/eXoDOS/files/13325574/REGISTER.zip)

This game is unregistered. danifunker found this key back in June 2021 but we must have missed adding it in and Kinsie has just rediscovered the issue and danifunkers key.

**Comment by exoscoriae** [comment]
registered... a knock copyright game needs registration...lol
