### ISSUE TITLE
Backup save doesn't work in eXoDOS 6

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4844]
Install tries to save the game when you prompted and decided to backup it, all right.

Problem is, it tries to save into !save dir, and this dir doesn't exist initially. After you created it once, it's all right. But it had to be here from the start.

Also, I noticed that accompanied text isn't totally true. it says:

> echo NOTE: If you choose yes, then the next time you install this game, it will ask if you
> echo would like to restore your saves and settings. These files are stored in your !save
> echo folder, in the game directory.

Actually, it stored in !save/-gamename-.zip, not in a separate directory.

**Comment by exoscoriae** [comment]
this was fixed in a prior release
