### ISSUE TITLE
Synnergist (1996)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4845]
There are 2 modes of difficulty for the game. According to discord user hunvagy / Rigoberto Brightman: (no idea where he found it)

`"There are two difficulty levels for playing the game, Challenging or Novice. The default mode is Challenging. During the first half of Chapter one (there are five chapters in the game) you can press the F1 key to switch between difficulty levels. The Novice mode will provide you with extra tips when viewing an object or trying a specific action on what you should do next. I found the game to be quite challenging even in novice mode because it was not always evident on how you should perform your next move. There are a few puzzles in the game that don't have the most obvious solutions, and some items are there to throw you off a little. It will also help if you can read some Latin as some clues are given in that language."`

The game is currently set to novice mode. You can also change the difficulty in the installer or by changing the 0 at the end of the .cfg file to a 1.
![image](https://github.com/exoscoriae/eXoDOS/assets/81642149/8b27eb43-a7bd-4c0c-89a9-b45f442bf843)

I don`t know what is the best option here. Either have 2 more config files with the choice of difficulty, include a note with the (untested) tip to press F1 in the beginning if you want to change or  just change it to challenging and tell nobody.

**Comment by exoscoriae** [comment]
thank you.  I added a note at startup
