### ISSUE TITLE
Tomb Raider Gold (1998)

### ISSUE THREAD

**Issue by gorbatiiivan** [exoscoriae/eXoDOS#4847]
Tomb Raiden Gold when run ONLY from "Pixel Perfect & Shader Options" the game menu rotates without stopping, is not playable. (All Tomb Raiden games from Pixel Perfect & Shader Options menu)

https://github.com/exoscoriae/eXoDOS/assets/84850541/452c440d-167f-425e-8fe3-4a7e94b6e7c5

**Comment by Python-Exoproject** [comment]
Confirmed, cycles=max is killing the alt launcher which uses staging. Set cycles=200000 to fix

**Comment by exoscoriae** [comment]
this was already done
