### ISSUE TITLE
Red Alert : a Johnny Walker Production (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#4848]
Submitted by KyaeroSaber
This game is not on the Dos master list" not on the missing list, not in the TDC and not on mobygames
Genre: Adventure
Developer:  Brad Hinchliffe
Publisher: United Distillers Pty Ltd
Released:   1996
Language: English
Format: zip 
**the whisky barcode number password is required to begin the game: 5000267014203**

Added to the github folder with covers and manual

**Comment by exoscoriae** [comment]
added

**Comment by parricc** [comment]
The `ManualPath` tag still needs to point to the manual for this game.

**Comment by parricc** [comment]
Python noted the eXoTool fixes manual paths.
