### ISSUE TITLE
Commander Keen 4 - Secret of the Oracle (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4850]
Game is very jerky when using the alt launcher. This is a known issue with Keen 4 and in vanilla dosbox we solved it with machine=ega, however staging requires machine=svga_s3 to remove the jerkiness. To save having two confs, one for main launch and one for alt launch, ive converted the game to use staging for both.

Here is the conf converted to use our staging template: [dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/13401845/dosbox.zip)

Switch to that and flick the game to staging 81.0a in dosbox.txt to resolve

**Comment by exoscoriae** [comment]
done =) thank you
