### ISSUE TITLE
Al-Qadim - The Genie's Curse (1994) [dosbox.txt\launch.bat findstr issue]

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4852]
Discord user growlerpig has reported this game doesnt start using the main launcher.

The reason is that when launch.bat uses findstr it is currently case sensitive. This is a problem for Al-Qadim as the game name is 'Al-Qadim - The Genie's Curse (1994)' while the entry in dosbox.txt is 'Al-Qadim - the Genie's Curse (1994)'

Solution is either fix the game name in dosbox.txt to match the case of the actual game name (but there maybe others) or as per a suggestion by discord user Tape_Worm, add the '/i' switch to the findstr command in launch.bat which will make the search ignore case

If you go with the ignore case switch it might be worth also updating the findstr commands that have been added to exoscummvm and anywhere else we use this method like maybe language packs? or when searching the multiplayer.txt (which also doesnt have the '/b' switch at the moment)?

**Comment by exoscoriae** [comment]
fixed the dosbox.txt file and added the /i
