### ISSUE TITLE
Kings of the Beach (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4853]
Discord user RomKnight found that the alt launcher is not running this game. Traced it to staging not liking the exe being run as just "vball". As the tandy=on issue was also present in the conf and the game has better sound in tandy mode ive also fixed those issues while I was here. 

Please find a replacement conf in this zip: [dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/13414868/dosbox.zip)

**Comment by exoscoriae** [comment]
sound is massively different between the alt launcher and regular launch versions. interesting.

**Comment by Python-Exoproject** [comment]
Yeah, we should probably just convert the game to Staging now. Switch to Staging and here is a conf: [dosbox.zip](https://github.com/user-attachments/files/15910374/dosbox.zip)

**Comment by exoscoriae** [comment]
done

**Comment by interloper98** [comment]
The intro tune can be AdLib or Tandy; the game will prefer AdLib if the card is present.

Once in-game, the registration desk tune and sound effects come from the Tandy 3-voice.

You can get 
```ini
[dosbox]
machine=tandy

[sblaster]
sbtype=none
oplmode=none

[speaker]
tandy=on
```

https://github.com/exoscoriae/eXoDOS/assets/165201780/bb0b1468-1716-4148-9c6f-dd3770a917e0


To add the AdLib, at runtime:

```ini
[autoexec]
@echo off
mount c .
c:
config -set oplmode=opl2
vball.exe
```


https://github.com/exoscoriae/eXoDOS/assets/165201780/105b8f33-d20c-4857-9edd-e09094f6c0bb


The game skips the "press enter when you hear a tone" when the AdLib is present, so the `autotype` isn't needed.

**Comment by Python-Exoproject** [comment]
Your call @exoscoriae on implementing this. To clarify above its the same Tandy machine mode game with Tandy throughout the game, just the intro is made Adlib.

If you wish to add this option it will need an alternate conf. The difference is in the [autoexec[ section where you would remove the autotype line and add `config -set oplmode=opl2` just before the game executable. Just changing the conf setting `oplmode=auto` to `oplmode=opl2` doesnt work

**Comment by exoscoriae** [comment]
added run.bat

**Comment by Python-Exoproject** [comment]
Found during QA that we also need to set sbtype=none in the conf for the Tandy in game sound to work for the adlib intro option. This has no effect on the Tandy intro option and is a safe change.

**Comment by exoscoriae** [comment]
done. hopefully that puts this game to bed.
