### ISSUE TITLE
Isaac Asimov - Science Adventure 2 (1994) CUE file

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4860]
We have CUE/IMG pair for Isaac Asimov - Science Adventure 2. Unfortunately, CUE was MIA somehow. I uploaded it.

Isaac Asimov - Science Adventure 2 (1994) CUE file.zip

**Comment by Python-Exoproject** [comment]
Theres another thing, at least for me. When I tried to run the minigame in the window immediately to the left of the door you face when you start I get an error and the game crashes
