### ISSUE TITLE
Raiden (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4863]
FistyDollars requested the ability to access the installer to change controls. The same situation as with Build engine games where the sound and controls are both saved in the same config file existed so I took the work done there and adapted it. Please find new run.bat: 
[Raiden.zip](https://github.com/exoscoriae/eXoDOS/files/13458687/Raiden.zip)

He also reported variable speed issues where the game is too fast in the beginning and things slow down when more objects appear on screen. This might be a good example game if @johnnovak \ @kcgen \ @nofunk proceed on testing out the average cycle cost approach to speed

**Comment by exoscoriae** [comment]
added your run.bat file.

I'd like to close this out, but I want to ensure if there is any benefit to the staging team, it isn't lost.
