### ISSUE TITLE
Elder Scrolls Adventures, The - Redguard (1998)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4864]
Using Dosbox Staging and some collaboration with kcgen I have this game setup so that it doesnt need multiple confs or exception.bat anymore.

1. Use the files in this zip ([RedGuard.zip](https://github.com/exoscoriae/eXoDOS/files/13459791/RedGuard.zip)),
2. Delete the extra conf (dosbox_ece.conf) and exception.bat
3. Switch to staging 81.1 in dosbox.txt

**Comment by exoscoriae** [comment]
moved to staging with above files
