### ISSUE TITLE
OutRun (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4865]
Discord user Tazman discovered that vanilla dosbox and other forks were not handling the tandy sound very well. After trying the alt launcher to see if it was better we discovered that while staging was playing the sound it did play better it was also missing some. @kcgen investigated and got everything fixed on stagings side and now it plays all sound and better than the other forks.

1. Wait until official staging 81 release
2. Switch game to new stable 81 staging in dosbox.txt
3. Switch game to this conf: [outrun.zip](https://github.com/exoscoriae/eXoDOS/files/13460006/outrun.zip)

**Comment by exoscoriae** [comment]
moved to staging
