### ISSUE TITLE
Soldiers of Fortune (1994) Extras

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4869]
1. Soldiers of Fortune requires protection code after L1. Codes was hosted on Abandonia, found by @RomKnight. Uploaded.

Soldiers of Fortune (1994) Protection Codes.jpg

2. Character cards are with watermark of Abandonware France. I uploaded clear version (with slightly different layout).

Soldiers of Fortune (1994) Character Cards.pdf

**Comment by exoscoriae** [comment]
added
