### ISSUE TITLE
ScummVM launch option fullscreen

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4870]
We overlooked the scummvm laucnh option in exception.bat for the relevant games when it comes to setting fullscreen or window mode in the new centralised system for exodos that uses options.conf. We create a file (FULL\WIN.SEL) based on the users choice so easiest way would probably be to update the exception.bat files to set the value (-f or -F) based on which sel file is present and change the launch command to use the variable (Or get rid of the scummvm launch option\advertise eXoScummVM for a better experience...)

**Comment by exoscoriae** [comment]
yep, scummvm has been removed
