### ISSUE TITLE
Beyond Wolfenstein 2 - Special Edition v3.0 (2001)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4872]
There seems to be a bug in the game regarding obtaining a required key that only presents in the DOS running of the game. Apparently exactly the same version played with a windows exe doesnt share the bug so it seems its in the exe code or an emulation issue. Rather than typing it all out, heres a link to the discussion: https://discord.com/channels/454359114601201666/1175013282629828638

**Comment by exoscoriae** [comment]
clever fix =) nice work
