### ISSUE TITLE
Football (1983) & Football (1986)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4876]
These two games were mixed up in dosbox.txt when Football (1986) was being switched for the CGA composite update. Currently its:

Football (1983):staging0.81.0a\dosbox.exe
Football (1986):ece4230\dosbox.exe

When it should be:

Football (1983):dosbox.exe
Football (1986):staging0.81.0a\dosbox.exe

**Comment by exoscoriae** [comment]
switched 86 to staging
swotched 83 to ece (rather than the above suggested vanilla)
