### ISSUE TITLE
New Print Shop Companion, The (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4878]
- The conf is mounting a few disk images that dont exist in the location given (conf path is \NewPS\floppy when the floppies are actually in \NewPSC\floppy)

- Also, there are 9 images in that folder but only three are in the mount command? The related game "New Print Shop, The (1989)" has the same images but doesnt mount them all either.

- The conf is setup for printing but the program is set to run using ECE in dosbox.txt when it needs to be X.

- I also noticed that the conf files for this and the related program "New Print Shop" both use output=software, not sure where that came from but as X games they should be output=openglnb and fullresolution=desktop

**Comment by exoscoriae** [comment]
* fixed mount commands, but it doesn't matter as they were already installed

* doesn't matter as rthey are already installed

* switched to X

* verified conf settings
