### ISSUE TITLE
Murders in Space (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#488]
page 2 is missing (probably a blank page)
contains copy-protection codes on page 13

**Comment by SmilingSpectre** [comment]
It's not manual, but Logbook. Uploaded.

Manual is missing (mocagh have it, but for Amiga/Atari. Uploaded).

Extra data borrowed from Mocagh, but then found at old-games.ru. Uploaded.

**Comment by TimberlAndRE-de** [comment]
- current manual is a logbook, real manual is missing
- eXo you can just delete the manual since Spectre has found a better version for the logbook
- for it and the other extra i made another issue: #1361

**Comment by bigjim161** [comment]
@exoscoriae @TimberlAndRE-de the current manual is the real manual.

I found an addendum/extra for PC.
![image](https://user-images.githubusercontent.com/67555221/114039975-7837e980-9883-11eb-8c00-f87404c8bbc4.png)


added to the GitHub folder

**Comment by Eulisker** [comment]
Manual in

- English
- French
- German
- Italian
