### ISSUE TITLE
DREAMS to Reality (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4881]
Currently this game is split between dosbox ECE and Daum depending on if launching the 3DFX or non3DFX version. There has been a graphical glitch that has affected every fork except Daum, however the Staging guys have gotten to the bottom of it and we can now simplify this game into one conf using one fork and no exception.bat

We need to:

1. switch the game to "DREAMS to Reality (1997):staging0.81.1\dosbox.exe" in dosbox.txt
2. use these files: [Dreams.zip](https://github.com/exoscoriae/eXoDOS/files/14636549/Dreams.zip)
3. delete from \\!dos\DREAMSto\\: "dosbox_ece.conf" and "exception.bat"

**Comment by Python-Exoproject** [comment]
Thanks for the advice, conf in zip file updated

**Comment by exoscoriae** [comment]
updated
