### ISSUE TITLE
wrong path to *.lang files in /util/Launch.bat

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4883]
We moved the *.lang files (the indicator files for the language packs installed) to the /util folder and renamed them to eXoDOS-German.lang to avoid a mix up with potential indicator files from future language packs for the eXoWin3x collection

In line 14 of the Launch.bat is still the old folder used:
`IF NOT EXIST .\emulators\dosbox\*.lang goto english`
has to be changed to
`IF NOT EXIST .\util\eXoDOS*.lang goto english`

I solved it for the current language packs by placing the lang files in both folders
~~but this will lead to problems as soon as we do a language pack for eXoWin3x~~
By renaming the lang files from e.g. German.lang to eXoDOS-German.lang we solved the problem regarding future language packs. But the folder still should be changed to keep all lang files in the util folder because the plugin should be suitable for all projects and it searchs for the lang files in the util folder.

(the other project language packs might not be affected because dosbox is currently only used in eXoDOS and eXoWin3x)

**Comment by exoscoriae** [comment]
change has been made.
