### ISSUE TITLE
Mystery Master - Felony! (1984)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#489]
has watermark theunderdogs.org
HotU b/w scan

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] manual (quality upgrade)

the current HOTU manual contains clue book and felony card extras - they are separeted and added as extras so the manual can be just replaced by the new one

added to the github folder

**Comment by exoscoriae** [comment]
replaced
