### ISSUE TITLE
Grand Prix Master (1989) Manual

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4890]
Marginally better than ours by quality - but saves more color and less washed out.

Grand Prix Master (1989).pdf

**Comment by exoscoriae** [comment]
rejected. is for the atari st

**Comment by SmilingSpectre** [comment]
Disagree. Yes, it's tailored for Atari ST - on its first page. Otherwise its literally the same as our manual (which simply removed this first page, it seems).

Text on the third page specifically says "AMIGA, Atari and PC (EGA)", so actually manual is universal.

So I still insist on replacing our manual.

Actually, it gave me the idea. I checked, and really - all versions are identical. So I found the best scanned version. For ZX Spectrum. :) Again: it's exactly the same, except page with the loading instructions and credits which is simply omissed in our manual. If you want, you can remove the first page and get the exact copy, but I don't recommend it. I replaced the file on the server.

**Comment by TimberlAndRE-de** [comment]
the current manual we have isn't stripped, it's  from the PC Hits budget release (see moby: https://www.mobygames.com/game/1941/grand-prix-master/covers/) as you can tell from the page numbers that are not there in the Atari or Spectrum manuals.

I agree, that the quality of the Spectrum version is much better and contains the same infos. But from a preservation point of view the current one is much better fitting then one from another platform.
