### ISSUE TITLE
Girlfriend Tracy (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4906]
Currently this game uses the environment to set up a new user, but I noticed that Girlfriend Terri (1994) had a windows tool to do this. I tested and the tool works here as well and may be a better option than the environment setup.

Also, if you start the game with "gf /sb" you get voice

While on the subject of these Girlfriend games I noticed that an error kept happening for Girlfriend Terri (1994) regarding not finding intro.voc, to fix this just put a copy of the file in the Terri.GF folder

I think there is a Girlfriend Suzy and Girlfriend Lisa as well though I couldnt find copies

**Comment by exoscoriae** [comment]
i added the windows utility to Tracy, as well as the exception files and such.

in TDC, they have the girlfriend speaks expansion, so I grbabed all the files for Terri from there. That fixed her voc error, and may have helped a few other areas as well.

there are voc files for lisa and suzy in there as well, but no base file for them.

**Comment by Python-Exoproject** [comment]
For Girlfriend Terri (1994) I am still getting the missing file error (its a line at the bottom of the screen with Terris face) saying its not finding intro.voc. Ive discovered that its because the sound pack in `\gfterri\gf_terri\sound` hasnt been installed completely. As we dont have the other personality packs all that you need to do to complete the install of the voice pack is extract `\gfterri\gf_terri\sound\gfsbteri.lzh`
 into `\gfterri\gf_terri\terri.gf`

If we get the other two personality packs for this game then the same process for each of their voice pack lzh files will need to be done.

@SmilingSpectre Any trace of the mentioned personality kits exo listed above?

**Comment by exoscoriae** [comment]
so this is for GF Terri, not Tracy?

Ok, I did the above for GF Terri.
