### ISSUE TITLE
Infocom Interactive InvisiClues

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#4910]
Digitoxin created interactive versions of the InvisiClue guides for Infocom adventures.

- [ ] Infocom_Interactive_InvisiClues.zip

![grafik](https://github.com/exoscoriae/eXoDOS/assets/67441153/4c7af3f4-f3f9-442f-8235-380c999b0c34)

**Comment by Eulisker** [comment]
I included all these in their respective game folder here #5165. This can be closed.
