### ISSUE TITLE
Missed CDs

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4917]
For some mysterious reason, we lost CDs from v6 that was here in v5. They mounted in configuration, but non-exists in archives.

- Marble Master (1997)
- Kaiser Deluxe (1995)

Also, Sigil (2019) lost 300Mb between versions, but there is no clear CD mounting, so I dunno where it came from.

**Comment by exoscoriae** [comment]
fixed
