### ISSUE TITLE
Hardline (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4918]
This game looks better in Staging.

1. Use this dosbox.conf ([dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/13614478/dosbox.zip))
2. Switch game to staging 81.0a in dosbox.txt
3. delete exception.bat
4. Consider adding user note to launch that suggests using alternate launcher with no interlacing choice

**Comment by exoscoriae** [comment]
I will look into this, but I don't find it to be a particularly useful report as it is.

"Looks better" is entirely subjective, and I can't be expected to enact changes based on that alone.

I would think it would be much more useful to supply screen shots or something tangible.

**Comment by exoscoriae** [comment]
Denied. Thread created in discord with proof

**Comment by Python-Exoproject** [comment]
Badly explained in the ticket, further explanation given in discord.

To sum up, the two images you were comparing were not apples to apples (ECE was using its Pixel Perfect mode and Staging was untouched output), and we were not getting the same results when running the game due to a combination of a deleted file reappearing in the WIP and the synology sync not downloading the reappeared file to my system. 

Once everything is on a level playing field: ECE uses 'Pixel Perfect' for scaling which you discovered is not the best approach while Staging uses Integer Scaling. This is why (to me) Staging 'looks better' for anything that needs adjustment.

As per the Discord posts, if you want to go with: 

Option 3:

1. Use this dosbox.conf ([dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/13656701/dosbox.zip))
2. Switch game to staging 81.0a in dosbox.txt
3. delete exception.bat
4. Consider adding user note to launch that suggests using alternate launcher with no interlacing choice

or

Option 4:

1. Use this dosbox.conf & exception.bat ([Hardline.zip](https://github.com/exoscoriae/eXoDOS/files/13656723/Hardline.zip))
2. Switch game to staging 81.0a in dosbox.txt
3. Consider adding user note to launch that suggests using alternate launcher with no interlacing choice

**Comment by Python-Exoproject** [comment]
This was actioned but not closed
