### ISSUE TITLE
Last Half of Darkness (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4921]
Game was using three different conf files, I think due to ECE and an image boot. All this can be done through Staging now with one conf

1. Replace dosbox.conf and run.bat with these files ([LastHalf.zip](https://github.com/exoscoriae/eXoDOS/files/13622554/LastHalf.zip))
2. delete exception.bat, dosbox2.conf, and dosbox3.conf
3. Switch to dosbox staging 81.0a in dosbox.txt

There are also subfolders 'ega' and 'vga' that have copies of the game that dont seem to be used anymore

**Comment by exoscoriae** [comment]
your zip file has monkey island and defendr of the crown files in it...

**Comment by exoscoriae** [comment]
applied changes directly to last half, ignored other data

**Comment by Python-Exoproject** [comment]
The EGA and VGA subfolders in the game zip need to be kept? I couldnt see where they were being referenced in the run.bat or conf.

**Comment by exoscoriae** [comment]
went ahead and removed them
