### ISSUE TITLE
TeenAgent (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4923]
This is only relevant if you are keeping ScummVM in exodos, if your not it wont matter as you will delete the exception for this game anyway:

The whole scummvm section in the exception.bat has disappeared

**Comment by exoscoriae** [comment]
see. scummvm was deleting itself pre-emptively!

**Comment by exoscoriae** [comment]
removed exception.bat compeltely.
