### ISSUE TITLE
Ultima V - Warriors of Destiny (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4927]
Here is a new exception.bat ([exception.zip](https://github.com/exoscoriae/eXoDOS/files/13662081/exception.zip)) that:

1. Adds resolution to the Ultimapper choice that scale the game up for 4k in window mode
2. Forces ECE to be used for the Ultimapper choice as Staging is incompatible with Ultimapper and therefore was an issue for the alternate launcher

**Comment by exoscoriae** [comment]
also meant to be switched to staging? assumed so

**Comment by exoscoriae** [comment]
haha. thanks

**Comment by Python-Exoproject** [comment]
Not a biggie but dosbox2.conf can be deleted

**Comment by exoscoriae** [comment]
done
