### ISSUE TITLE
Carnage (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4930]
RomKnight has noted that the game slows down when two or more mines are deployed. He suggests cycles around 4k to resolve. I have confirmed the issue and solution.

He also mentions a high pitched engine sound when gameplay starts and suggests using staging and its sound filters to resolve. I think it might be easier to just set sbtype=sb2 which also resolves the sound issue

**Comment by exoscoriae** [comment]
done
