### ISSUE TITLE
SimLife (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4931]
I noticed this ticket on the Staging github: https://github.com/dosbox-staging/dosbox-staging/issues/3212

This sound issue is interesting as like Grounded0 on that ticket said, I couldnt get the digital sound working either. It will be worth watching this ticket to see what they figure out.

The main reason im raising this ticket though is that while looking into it I discovered that our current run.bat has the /s sound flag flipped between the two sound options. /S6 should be the Sound Blaster and /S8 should be the MT32 option

**Comment by kcgen** [comment]
@Python-Exoproject , besides X, have you managed to get SFX working on others,  like 0.74 or ECE?
(I've only tried SVN w/ sbpro2, but not working on my side, just to check if this is inherited or a regression in Staging).

**Comment by Python-Exoproject** [comment]
@kcgen No luck on ECE, 0.74, or X

**Comment by Python-Exoproject** [comment]
All resolved at some point before Staging 81.1 release.

Switch to Staging 81 and use this conf: [conf.zip](https://github.com/user-attachments/files/15866647/conf.zip) remembering to make the above dit to run.bat re /s6 and /s8

**Comment by exoscoriae** [comment]
switched to staging

changed run.bat
