### ISSUE TITLE
Space Quest I - The Sarien Encounter SCI (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4932]
Discord user Byrdman noticed that the MT32 sound option was no longer giving the digital fx, which I have confirmed.

The reason is that the run.bat is pointing to the MT32.DRV instead of MTBLAST.DRV when the user selects MT32 sound. I assume this happened when we changed the method this run.bat uses to handle sound choices.

To fix edit:

if %SOUND%==MT32 echo  soundDrv  = MT32.DRV>>resource.cfg

to

if %SOUND%==MT32 echo  soundDrv  = MTBLAST.DRV>>resource.cfg

This game is also one of the ones that will need 'tandy=on' removed from the conf for Staging to work via the alt launcher for all sound choices. As this particular game does not offer a Tandy sound choice to the user no other action is required in this regard once 'tandy=on' is removed

**Comment by exoscoriae** [comment]
changed run.bat

removed tandy=on
