### ISSUE TITLE
All Seeing Eye Games

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4941]
As with the Gold Box Companion, the All Seeing Eye is not compatible with Staging and wont be for the foreseeable future. These new exception.bat files force ECE when ASE option selected: [ASE.zip](https://github.com/exoscoriae/eXoDOS/files/13723926/ASE.zip)

Ive also tweaked EOB1 so that the Tandy sound choice will work as well

**Comment by Python-Exoproject** [comment]
Some other infor while the Eye of the Beholder games are being looked at from John Novak:

A game bug from back in the day was that the numpad '9' key would only work to move the character half the time. The fix was to make sure numlock was off.

Ive tested and this still affects the game. Maybe a user note is in order? Something like "Ensure Numlock is off to avoid keyboard movement problems"

**Comment by exoscoriae** [comment]
added your exceptions.

removed scummvm launch options

added note for eob2 about numlock

**Comment by Python-Exoproject** [comment]
Loved the note for EOB2, cant miss that :-)
