### ISSUE TITLE
Microsoft Space Simulator (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4942]
Thanks to agathosdaimon we have discovered this game suffers from both a flickering bug and the speed bug that affects games like Privateer 2.

The flicker is ridiculous in the current fork we use, vanilla. It is resolved using Staging 80.1 but the flicker is back in 81.0a. I have not uploaded a conf for 80.1 as im hoping that the Staging guys will be able to resolve this regression by their stable 81 release

As for the speed issue, 50k seems to be fine for when the Earth is on screen but as soon as the Earth is off screen the game whips around at blink and you miss it speed until the Earth appears on the other side. Not much we can do with this but it might be worth a warning if we dont come up with anything to solve it

Edit: Solution in comment dated 25 Dec 2023

**Comment by SmilingSpectre** [comment]
Weird enough, it's totally fine for me on 50K in Staging 80.1, if Earth is on screen, but still flickers if it's off screen. 40K seems fine.

![image](https://github.com/exoscoriae/eXoDOS/assets/24454178/2e5a3172-1cc9-41a5-8ce6-ca33a2be05cd)

Confirming "too fast" issue for 81.0a (but not in 80.1).

**Comment by Python-Exoproject** [comment]
Staging have now fixed the issues in https://github.com/dosbox-staging/dosbox-staging/pull/3250 It will be added to their release candidate 2 so this can be addressed after that point

**Comment by Python-Exoproject** [comment]
@kcgen has discovered a solution to the speed issue for this game. There is an option inside the game under the preferences menu for simulation precision level. If this is set to 8 and cycles are between 50k-60k then enough cycles are eaten by the game that the speed issue doesnt present and you can move around with or without the Earth on screen without issue.

**Comment by exoscoriae** [comment]
converted to staging.

**Comment by exoscoriae** [comment]
done
