### ISSUE TITLE
Future Wars (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4943]
@amazzanti raised that the current crack for this game may make the game unable to be completed. I tested and this has proven to be true as when I was in the maze at the end of the game the character kept glitching when I needed it to go down a ladder on the second maze screen.

He provided an alternate crack which I also tested and it does not have the issue. Please replace the current 'fw.com' with this new one: [FW.zip](https://github.com/exoscoriae/eXoDOS/files/13762274/FW.zip)

**Comment by exoscoriae** [comment]
cracked.

removed leftover scummvm files.
