### ISSUE TITLE
Need for Speed, The - Special Edition (1996)

### ISSUE THREAD

**Issue by gorbatiiivan** [exoscoriae/eXoDOS#4946]
Need for Speed, The - Special Edition (1996) when run ONLY from "Pixel Perfect & Shader Options" the game is not playable.

https://github.com/exoscoriae/eXoDOS/assets/84850541/02f7912f-b504-48ab-98db-46fb61ad10a9

**Comment by Python-Exoproject** [comment]
Its a cycles issue. Currently game is set to cycles=max and vanilla dosbox which the main launch uses currently is a bit more forgiving for that.

Set cycles=100000 in conf fixes it so that both vanilla via main launch and staging via alt launch will work

**Comment by exoscoriae** [comment]
changed cycles. moved to ece
