### ISSUE TITLE
Need for Speed, The (1995)

### ISSUE THREAD

**Issue by gorbatiiivan** [exoscoriae/eXoDOS#4947]
I don't know if it's a bug or not but when run from "Pixel Perfect & Shader Options" it works a perfectly, but only when calibrate joystick it happens like this

https://github.com/exoscoriae/eXoDOS/assets/84850541/87d9079c-7153-4b9d-bb6c-d0c0589f8132

**Comment by Python-Exoproject** [comment]
Its a weird one, even with joystick=none set it shows this screen and jerks all over the place. Its not cycles related either. You can just press esc to skip the calibration and play the game, but I am curious on why its happening. Any thoughts @kcgen? If you think it might be an emulator issue im happy to create a ticket in your github
