### ISSUE TITLE
Might and Magic Xeen titles

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4948]
This affects Clouds of Xeen, Darkside of Xeen, World of Xeen, and Sword of Xeen

This game engine has always been known to be finicky and sensitive to cycles even back on original hardware. Now that Staging has improved emulation some of this original hardware behaviour is popping up. Currently we use ECE with cycles 30000 which has made the game run way to fast during intros (Clouds of Xeen is a good example) and certain animations look like they are on turbo. It was unnoticed as the rest of the gameplay seemed fine. Using the latest version of Staging (81 RC-1) this is also now reintroducing a glitch where the mouse cursor disappears at the top of the screen when on a character status window (reached by clicking on a character portrait in game).

The best approach after testing is to reduce the cycles for all 4 games to between 5500 and 7000. This has minimal impact on gameplay, brings the intros to a more reasonable speed (again, Clouds of Xeen for the example), and fixes the cursor glitch. The current main launch option of ECE also runs fine with cycles at this speed and fixes the speed of the intro for Clouds of Xeen.

Lastly, for Clouds of Xeen there is some sound balance issues for the SB and MT32 launch options during the intro. Easiest fix is to set sbtype=sbpro2 which fixes the SB option and for the MT32 add to run.bat under the MT32 label 'mixer sb 25 mt32 150'

**Comment by Python-Exoproject** [comment]
It has been noted by discord user sherv that when you change CD in World of Xeen by pressing ctrl-f4 when prompted by the game nothing happens further until you also press enter to let the game know the CD has been swapped. Worth an addition to the user note to swap cds?

**Comment by exoscoriae** [comment]
Clouds of xeen - sbtype was changed to sbpro2, and the mixer line in the run.bat was added.

cycles have been dropped to 7000 for the 4 games

are the games ready to be moved to staging 81.1?

**Comment by exoscoriae** [comment]
moved them to staging

**Comment by Python-Exoproject** [comment]
Somehow all the conf files you created for these four games have `irq=3` in them? The original confs didnt have that setting. Unless you changed the sound setup I believe these are here by mistake and should be removed from all four confs

I did a scan of the collection in case its a template issue and two other games also have irq=3 in them so this is possibly the case. Thankfully the setting for those two other games is a valid usage so no other changes outside of the above Xeen games is required. If its a template that you have saved somewhere though it might be worth checking that it doesnt have irq=3 in it.

**Comment by exoscoriae** [comment]
removed irq 3. i likely did a staging search and grabbed a conf from somewhere else. I likely should just have a base template to copy from, that way I can avoid special settings like this
