### ISSUE TITLE
Back to Baghdad (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4949]
This game has two issue as reported by agathosdaimon.

1. When in mission you press esc to bring up the in flight menu. Currently this menu flashes briefly and exits unless the control mode is Joystick. This is a game bug and not cycles related.
2. The game gives a page fault during start unless cycles are at 20k or lower which is to slow to play the game

The fix for both was discovered by Spectre. There is a game patch to upgrade to v1.03 ([B2BPATCH.zip](https://github.com/exoscoriae/eXoDOS/files/13786678/B2BPATCH.zip)) that fixes the in game menu issue. For the page fault replace dos4gw.exe with this one: [DOS4GW.zip](https://github.com/exoscoriae/eXoDOS/files/13786685/DOS4GW.zip)

**Comment by exoscoriae** [comment]
hmm. the patch was alreayd in the games folder

**Comment by exoscoriae** [comment]
seems the patch was already applied as well?

**Comment by Python-Exoproject** [comment]
Previously applied or not the bug existed during testing by Spectre and myself and was fixed by reapplying the patch
