### ISSUE TITLE
Crime Wave (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4951]
Discord user wysiwyg discovered the very bottom of the main menu is corrupted slightly. He found a copy on archive that had no corruption ([Crime Wave (1990).zip](https://github.com/exoscoriae/eXoDOS/files/13788045/Crime.Wave.1990.zip)) which ive added the crack and exo file to

**Comment by exoscoriae** [comment]
replaced
