### ISSUE TITLE
Xmas Lemmings (1991) & Xmas Lemmings 1992 (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4967]
From FistyDollars:

In Launchbox, Xmas Lemmings '91 is named "Xmas Lemmings 1991" but '92 is named "Xmas Lemmings (1992)", which is inconsistent and also means that '92 shows up before '91 due to the way it gets sorted alphabetically.

eXos response:

The sort can be changed. But I am going by the in game title iirc

**Comment by exoscoriae** [comment]
added parenthesis to (1991)
