### ISSUE TITLE
Moonstone - A Hard Days Knight (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4972]
Staging via the alt launcher is not currently working due to the cycles being to high for the game on cycles=auto (Cursor continuously moves down). Set cycles to cycles=2000 to allow alt launcher compatibility with no hinderance to main launch ECE option

**Comment by exoscoriae** [comment]
modifications made.

they chopped my head off when I tested the game.


... cool
