### ISSUE TITLE
BattleTech - The Crescent Hawk's Inception (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4974]
The game itself offers CGA\Tandy\EGA\MCGA as options when loading the game. We have the game running with machine=tandy as this uses the three voice sound. Discord user Sloppymops has requested that we add the ability to use the other modes. We can either use autotype to skip the game menu so that the options arent seen (not my preferred option) or open the game up so that all options will work.

For autotype switch game to staging 81.0 and use this conf: [autotype.zip](https://github.com/exoscoriae/eXoDOS/files/13809588/autotype.zip)

For providing all options switch game to staging 81.0 and use the files here: [AllOptions.zip](https://github.com/exoscoriae/eXoDOS/files/13809636/AllOptions.zip)

**Comment by exoscoriae** [comment]
all options path used. thank you for providing both
