### ISSUE TITLE
Mousehelper Games (Dune 2, Warcraft, Terminator FS\Skynet)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4975]
The mousehelper utility these games use is not very compatible with Dosbox Staging. I noticed a few other issues which ive also noted with some of these games.

It would be nice if we could track the creator down (name of Osprey) and ask if he could fix the tools to work with Staging. He posted them on PCGamingWiki but hasnt been active on there since 2020. He also states in his notes that the program is just a compiled Autohotkey script and provides the ahk files in the src folder of the downloads so maybe someone in the team could solve the issues?

Terminator Skynet & Terminator Future Shock:

1. Both these games are running with vanilla dosbox somehow. They should be on ECE as they are MT32 and SoundCanvas compatible, they are even in the LB playlists for those devices. Not sure how they ended back on vanilla.
2. Both these games are not compatible with the mousehelper at all when using Staging, the weapons keep scrolling through even when not touching the mousewheel. Here are the new exception.bat files for both games that disable mousehelper when using alt launcher but still allow it when using main launch: [FSexception.zip](https://github.com/exoscoriae/eXoDOS/files/13843397/FSexception.zip) & [skyexception.zip](https://github.com/exoscoriae/eXoDOS/files/13843399/skyexception.zip)
3. Can you think of a way to hide the user note about mousehelper when the alt launcher is used? With the above exception.bat you will see the note with all the mousehelper info even if the mousehelper isnt loading due to using the alt launcher

Warcraft:

1. This game also seems to be running on vanilla dosbox when it should be using ECE as it has SoundCanvas option
2. This game is partially compatible with the mousehelper util. With a couple lines added to the conf that only Staging will recognise and use some features will still work. Here is a new exception.bat which makes the launch compatible with Staging while still working in ECE along with a new conf with the extra lines and a new run.bat that informs the user mousehelper is only partially working when Staging is used via Pixel Perfect launch option: [warcraft.zip](https://github.com/exoscoriae/eXoDOS/files/13843461/warcraft.zip)

Dune II:

1. This game is partially compatible with the mousehelper util. As above with Warcraft a slight edit to the conf and exception allows a couple of the features to work. Here are the updated files: [Dune2.zip](https://github.com/exoscoriae/eXoDOS/files/13843475/Dune2.zip)

**Comment by exoscoriae** [comment]
* moved SkyNEt and Future Shock to ECE 4230
* replaced exception files for both Terminator games
* hmm... the user note actually in the run.bat menu? Yea, I came up with a way to do it.

* set WarCraft to ECE. 
* put run.bat in games folder, and replaced exception and conf file in dosbox folder

* Extracted Dune 2 files to their appropriate locations
