### ISSUE TITLE
Tennis Cup 2 (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4978]
Current setup is not actually providing Adlib sound, set MPU401=none to fix. 

When fixed though it sounds terrible outside of Staging. Switch to Staging 81 and use this conf ([TennisC2.zip](https://github.com/exoscoriae/eXoDOS/files/13850032/TennisC2.zip)) to fix

**Comment by exoscoriae** [comment]
sounds great now
