### ISSUE TITLE
Metal Slug: Super Vehicle - 001 (1999)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#4985]
This game is not on the Dos master list, not on the missing list, not in the TDC, and not on mobygames.
Genre: Action 
Developer:  SNK 
Publisher: SNK 
Released:   1999 in South Korea
Language: English
Format: Bin+cue
Tested on Pcemv17 win98 dos mode ( windows installer/ game runs under DOS) 

Add to the github folder with covers and the ripped dos files (needs the CD-ROM to run the game)

**Comment by exoscoriae** [comment]
added

**Comment by parricc** [comment]
The `ManualPath` tag still needs to be pointed to the manual.

**Comment by parricc** [comment]
Python noted the eXoTool fixes manual paths.
