### ISSUE TITLE
FriendlyWare PC Introductory Set (1983)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4986]
This game needs to have machine=tandy set to enable sound. Additionally, using the eye and hearing test inside the game you will notice a limitation of tandy sound emulation in older dosbox versions as the sound never goes out of hearing which it should. Switch to Staging for more accurate sound emulation and the sound does what it should going high enough to go outside human hearing.

Switch to Staging 81 and use this conf: [dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/13976386/dosbox.zip)

**Comment by exoscoriae** [comment]
switched
