### ISSUE TITLE
Ultima Underworld 1 & 2

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4989]
I came across a report that these games have a weirdly laggy mouse issue. I tested and confirmed that the issue exists in our current implementation for the games in exodos. The issue has been corrected in Staging however.

While fixing the mouse issue I also noticed that we have implemented the UltimaHacks without giving users a choice between it and the unhacked game. I have set the run.bat up so that the user can toggle the patch now. I also tweaked the audio balance for MT32 and SC

Switch to Staging 81
Use the files contained in: [eXoDOS.zip](https://github.com/exoscoriae/eXoDOS/files/13940742/eXoDOS.zip)

**Comment by exoscoriae** [comment]
applied changes

removed sc55
