### ISSUE TITLE
Links 386 CD (1995)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#4993]
E: Edited and reuploaded. See last comment.

**Comment by Eulisker** [comment]
I made an error when creating the .pdfs. I deleted them for the time being and will reupload this and even more on the weekend.

Closing this for now.

**Comment by Eulisker** [comment]
I scanned a bunch of mostly score cards for the course addons:

- [ ] Banff Springs - Score Card
- [ ] Barton Creek - Score Card
- [ ] Bighorn - Score Card
- [ ] Castle Pines Golf Club - Score Card
- [ ] Firestone Country Club - Score Card
- [ ] Mauna Kea - Score Card
- [ ] Pebble Beach - Important Notice
- [ ] Pebble Beach - Score Card
- [ ] Pinehurst Resort & Country - Club Score Card
- [ ] Prairie Dunes Country Club - Score Card
- [ ] Riviera Country Club - Additional Course Information
- [ ] Riviera Country Club - Score Card
- [ ] Riviera Country Club - UK Important Notice
- [ ] Troon North - Score Card

There also are (different from the old links addons that all had a specific installation manual) generic:

- [ ] Installation Instructions
- [ ] CD Install Guide
- [ ] Tech Support Note

I again have a few boxes from the US and the rest from the UK. The UK has a different

- [ ] UK Registration Card
- [ ] UK Envelope

and the US has also:

- [ ] US Registration Card
- [ ] Advertisement (The Links Tour)
- [ ] US Envelope

In two of the Boxes (Troon and Riviera) were Access Software Catalogs. I don't know if they have to be here. It is already a crazy amount of extras (and there are still a few score cards missing for now). They definitely need to go to the MS DOS Catalog section of exodos.

- [ ] Access Software Catalog 1995
- [ ] Access Software 1995 Fall Catalog


All added to the github folder.

**Comment by exoscoriae** [comment]
adde catalogs to catalog section.

added everything else to the game extras
