### ISSUE TITLE
Game fixes (Mapper) for Alt Launcher compatibility

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#4999]
As discussed I have been working to bring the alt launcher up to being as compatible as it was before switching to Staging. To that end all the games that used a mapper were no longer working as the mapper isnt cross compatible. This requires any mapper game to be switched to Staging for the main launch and have the mapper redone. 

Please find below the required files to do so with a brief note on anything else I found\fixed while testing these games. Even though its not required for the changes, I have included the launch bat in each games !dos folder in my attached archives just for reference so that you can easily identify which game a folder is for.

------------------------------------------------------------------
<ins>Games that dont actually seem to need a mapper</ins>

For these games I found in my testing that either the game didnt need a mapper or offered the user a choice on start for keyboard control. This means that once the mapper.map file has been deleted there is no need to convert to Staging or do any further action. If you feel any of these should actually keep the mapper let me know and ill create the needed conf\mapper

**Arcade 2 (1992)** - Delete mapper as not needed. Game uses keyboard controls. Still convert to staging as screen ratio fixed vs vanilla
**Battlestorm (1990)** - Delete mapper as not needed. Game uses keyboard controls. 
**Commander Keen 1 - Marooned on Mars (1990)** - Delete mapper as not needed
**Cosmic Spacehead (1993)** - Delete mapper as not needed. Game asks if want to joystick connected during start, uses keyboard if no
**Monster Bash (1993)** - Delete mapper as not needed. Game uses keyboard controls. The conf also has an invalid line for joystick that can be deleted (has joystick=2axis when the flag is actually jotsticktype=2axis)
**NetWars (1993)** - Delete mapper as not needed. Game uses mouse
**Pit-Fighter (1991)** - Delete mapper as not needed. Game has keyboard controls for both players, listed in the addendum pdf in the extras folder
**Qbert (1984)** - Delete mapper as not needed, the numpad diagonals (7,9,1,3) work for keyboard
**Storm (1987)** - Delete mapper as not needed. Game has a keyboard option during game start
**Stryx (1990)** - Delete mapper as not needed. Game has a keyboard option during game start
**Total Carnage (1994)** - Delete mapper as not needed. Currently has a mapper file as P1 was set to use Joystick. I swapped the in game control scheme so that P1 now uses Keyboard and P2 uses Joystick. This way no mapper is needed and if a user plugs in a joystick they can play as P2. Sound needs sbmixer=false added to [sblaster] section
**Winter Challenge - World Class Competition (1988)** - Delete mapper as not needed. Game asks if want to use joystick during start. Current mapper.map isnt even being used as conf doesn’t have joysticktype=2axis

Heres the zip with the tweaked files for Arcade 2 and Total Carnage: [Tweaks.zip](https://github.com/exoscoriae/eXoDOS/files/14085610/Tweaks.zip)

----------------------------------------------------------------------------------
<ins>Games already on staging that needed a tweak</ins>

**Freddy Hardest (1988)** - Game was already on staging but I noticed the game didn’t like right arrow being mapped for joystick right. Issue now fixed.

New mapper file included here: [Tweaks.zip](https://github.com/exoscoriae/eXoDOS/files/14085903/Tweaks.zip)

-----------------------------------------------------------------------------
<ins>Games converted to Staging and tweaked a little</ins>

These games need to be switched to Staging in dosbox.txt. 

While testing and redoing each of these games mappers I discovered the below noted issues and have provided fixes as well as the mapper & conf

**Brix II (1988)** - As well as converting and resetting mapper I removed an unneeded image mount line
**Breakoff (1989)** - This game was previously unplayable. As well as converting and resetting mapper I have provided a user choice via exception.bat between the original released version and the one fixed by you that makes the game playable (game files also provided)
**Ghosts 'N Goblins (1987)** - Our version was hacked and corrupted a little at the bottom of the loading data screen. As well as converting and resetting mapper I have provided a whole new copy of the game I found that is not corrupted. New version doesnt look hacked but works in the testing I gave it so not sure what was hacked in the current exodos version.
**Hack (1984)** - As well as converting and resetting mapper I have provided as a user choice two other versions (the first and last PC releases) to represent the full evolution of PC Hack.
**HardBall! (1987)** - Mouse control was borked. Spectre found that only one DOS era mouse driver allowed it to work properly. Also had to reduce mouse sensitivity. As well as converting and resetting mapper I have provided the mouse driver and set the game to use it as well as the virtual joystick.
**Helter Skelter (1989)** - Game is currently unplayable in exodos as you cant move left. As well as converting and resetting mapper I have fixed the issue using Stagings joystick calibration options. 
**Player Manager 2 (1995)** - Game currently has a warning that there is no sound when using the CD version. I fixed the issue. As well as converting and resetting mapper I have provided the new files to implement the fix and removed the user note
**Quasar (1990)** - Game currently has a note about being hard to control. Using Staging I was able to tweak the joystick calibration so this issue is fixed. As well as converting and resetting mapper I removed the warning message as its no longer relevant. Cycles may need some better tweaking though
**Soldiers of Fortune (1994)** - I read the manual and found the controls in the provided text file to not be correct. As well as converting and resetting mapper I have updated the text file.
**Star Rangers (1995)** - As well as converting and resetting mapper I fixed a conflict that the previous mapper had with one of the controls between the mapped joystick and the games keyboard controls. I also updated the user note to highlight the more convenient keyboard controls for shooting and rolling. Lastly, I provided a new game file that saves the calibrated joystick settings.
**VR Slingshot (1994)** - As well as converting and resetting mapper I have provided a new game file that saves the calibrated joystick settings
**Star Destroyer - Episode I (1986)** - This game is currently unplayable in ECE\Vanilla\etc as the targeting reticule is stuck in the top left. Using Staging I have fixed this with is joystick calibration settings and provide the converted conf and mapper. The game now has use of the full game window for the targeting reticule, however is fundamentally unplayable with keyboard as the mapped controls have only two states, min\max, and therefore you cant aim at anything between the centre point and the edge of the screen. I am creating a ticket to see if Staging might allow mapping of the virtual joystick to the mouse which would fix the few games where this is an issue.
**Last Warrior, The (1985)** - Same issue as above game regarding the mapping to keyboard and controls only having two states, min\max

Heres the zip with the converted files and tweaks: [Converted&Tweaked.zip](https://github.com/exoscoriae/eXoDOS/files/14097854/Converted.Tweaked.zip)

----------------------------------------------------------------------------------------------
<ins>Games converted to Staging</ins>

These games need to be switched to Staging in dosbox.txt.

The only actions taken were the conversion of the conf and mapper.

Avoid the Awful Thing that Vaguely Resembles a Banana!! (1987)
Action Fighter (1989)
Bit-Bat (1982)
Bruce Lee (1987)
Calamari Cubes 2 (1998)
Fluf! (1989)
Frogger (1983)
Ghostbusters (1986)
Goal! (1993)
Gremlins 2 - The New Batch (1990)
Kick Off 3 - European Challenge (1994)
Kick Off 3 (1994)
Legends (1996)
Lost Tomb (1982)
Mega Man 3 - The Robots are Revolting (1992)
Microsurgeon (1984)
Mighty Bombjack (1990)
Mirage Thunder (1993)
Novastorm (1994)
River Raid (1984)
Snakes (1988)
Space Miner (1983)
Street Football (1988)
Star Ship Attack (1982)
Toad Road (1990)
Trojan (1986)
Uridium (1988)
World Golf 2 (1990)
Wrecking Ball (1984)

Heres the zip with the converted files: [Converted.zip](https://github.com/exoscoriae/eXoDOS/files/14097954/Converted.zip)

**Comment by Python-Exoproject** [comment]
To put them all in one list, the games needing moving to Staging from the above are:

Arcade 2 (1992)
Avoid the Awful Thing that Vaguely Resembles a Banana!! (1987)
Action Fighter (1989)
Bit-Bat (1982)
Brix II (1988)
Breakoff (1989)
Bruce Lee (1987)
Calamari Cubes 2 (1998)
Fluf! (1989)
Frogger (1983)
Ghostbusters (1986)
Ghosts 'N Goblins (1987)
Goal! (1993)
Gremlins 2 - The New Batch (1990)
Hack (1984)
HardBall! (1987)
Helter Skelter (1989)
Kick Off 3 - European Challenge (1994)
Kick Off 3 (1994)
Last Warrior, The (1985)
Legends (1996)
Lost Tomb (1982)
Mega Man 3 - The Robots are Revolting (1992)
Microsurgeon (1984)
Mighty Bombjack (1990)
Mirage Thunder (1993)
Novastorm (1994)
Player Manager 2 (1995)
Quasar (1990)
River Raid (1984)
Snakes (1988)
Soldiers of Fortune (1994)
Space Miner (1983)
Star Destroyer - Episode I (1986)
Star Rangers (1995)
Street Football (1988)
Star Ship Attack (1982)
Toad Road (1990)
Trojan (1986)
Uridium (1988)
VR Slingshot (1994)
World Golf 2 (1990)
Wrecking Ball (1984)

**Comment by exoscoriae** [comment]
hmm... I had previouslty edited breakoff and fixed it so you could start it and play it. I'm not sure if your edit has undone my work.

I am going through every game, one by one, because many of these already had fixed applied this week. And I don't want these changes to undo anything.

**Comment by exoscoriae** [comment]
player manager 2, you removed the part of the note that says the CD has higher resolution..

restored this.

**Comment by exoscoriae** [comment]
everything should be converted now. I wasn't entirely clear on *why* we converted them. So if you wouldn't mind PMing me on discord, I am just curious. I'm def glad to get them moved over, I just wasn't sure if it was a joystick thing, a sound thing, etc...

**Comment by Python-Exoproject** [comment]
Actions missed:

Battlestorm (1990) - Delete mapper as not needed. Game uses keyboard controls.
Monster Bash (1993) - The conf also has an invalid line for joystick that can be deleted as its not even used currently (has joystick=2axis when the flag is actually joysticktype=2axis)
Total Carnage (1994) - Sound needs sbmixer=false added to [sblaster] section

**Comment by exoscoriae** [comment]
mapper deleted
joystick=2axis deleted
sbmixer=false added
updated controls.txt
