### ISSUE TITLE
The Lost World (1993)

### ISSUE THREAD

**Issue by Resulka** [exoscoriae/eXoDOS#5004]
This game is not in the current project, the master list, nor on the missing list, not in the TDC or archive.org and not on mobygames.
Genre: Educational/Adventure
Developer:  Satchel Software
Publisher: Department of Education and Children's Services South Australia
Released:   1993
Language: English
Format: Disk Install images and Installed ready to play in DOS version.
Tested in DOSBOX ECE

Added to Github folder including screenshots and Manual/Teacher's Guide

**Comment by exoscoriae** [comment]
added

@Resulka I didn't see any teacher's guide or manual in here?

**Comment by Resulka** [comment]
There should have been a manual in there. My PC's currently out of commission, the CPU died and I'm waiting for a new one to come in. As soon as I'm back up and running I'll check it out.
