### ISSUE TITLE
Chess (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5008]
Couple things with this one.

1. The game is meant to have sound, however its currently not working. To fix this we need to update the conf to remove the tandy=on line and add a new file to the game folder. Here is an archive with the updates: [chessKS.zip](https://github.com/exoscoriae/eXoDOS/files/14208985/chessKS.zip)

2. Using command line we can choose the difficulty of the opponent, what colour you play, and allow two human players on same pc. It might be worth implementing this somehow for the exodos users? Here is the excerpt:

COMMAND LINE OPTIONS:
`Chess [whiteplayer] [blackplayer]`

Meanings of whiteplayer and blackplayer values:
	0: human controlled
	1: Extremely stupid computer           (Thinks 1 move  ahead: Me)
	2: Pretty stupid computer              (Thinks 2 moves ahead: Me,You)
	3: Stupid computer                     (Thinks 3 moves ahead: Me,You,Me)
	4: Ok, I guess computer                (Thinks 4 moves ahead: Me,You,Me,You)
	5: Good computer, but takes a long time
 6-8: Congratulations - you found a new way to lock up your computer (unless
		 of course you have a Pentium VII running at 100 Gigahertz.)

If you negate the first option, then the 2nd option is a time-out
	length (120 per second)  When the timer runs out, the computer selects
	a move for you.  Of course the computer uses "extremely stupid" mode as
	a way of punishing you for taking too long.

Examples:
	"chess 0 4": the default, where you (white) play a 4-move ahead computer
	"chess 3 4": Watch the white computer lose to the smarter black computer.
	"chess -2 600": A timed game against a pretty stupid computer where
		 you have 5 seconds to move before the computer picks a really stupid
		 move for you.

**Comment by exoscoriae** [comment]
added your files and created a menu system

**Comment by Python-Exoproject** [comment]
In your run.bat under :single2 you have missed a word, the line currently says:

echo Press 2 for a Pretty Computer Partner (Thinks 2 move ahead)

when it should say

echo Press 2 for a Pretty Stupid Computer Partner (Thinks 2 move ahead)

unless we are commenting on the looks of the computer player :-)

**Comment by exoscoriae** [comment]
how dare you question my taste in AI opponents!
