### ISSUE TITLE
Battle Tetris (1994)

### ISSUE THREAD

**Issue by TS2049** [exoscoriae/eXoDOS#5011]
The EXE for Battle Tetris (1994) [aka Double Tetris] has some kind of hack where the confirmation menu when you click Esc says:

![ftf_vga_001](https://github.com/exoscoriae/eXoDOS/assets/73913715/812ba227-038c-4df2-9f48-c2ed7ff02a53)

when it originally said:

![ftf_vga_000](https://github.com/exoscoriae/eXoDOS/assets/73913715/d920106c-de83-4971-8aa3-325707b3470f)

The second image comes from the Total DOS Collection archive "Double Tetris (1990)(Soft-World) [Action, Strategy].zip". That archive's FTF_VGA.EXE is compressed using PKLITE; when it is decompressed using a program like UNP, the result almost completely matches the FTF_VGA.EXE in eXoDOS when the two are opened in a hex comparison utility. The only differences are these three strings being changed. (The high score screen titles are _not_ different due to any differences in the EXE code; there's a game config option to toggle between what I assume to be Simplified or Traditional Chinese, TDC's config is set to one option and eXoDOS's config is set to the other.)

**Comment by SmilingSpectre** [comment]
Did you read high score table? Obviously, not only menu changed. :)

**Comment by TS2049** [comment]
> Did you read high score table? Obviously, not only menu changed. :)

The high score table is not contained in the EXE file.

**Comment by exoscoriae** [comment]
fixed
