### ISSUE TITLE
Library of the Future (1994)

### ISSUE THREAD

**Issue by Resulka** [exoscoriae/eXoDOS#5017]
Added to Github Submissions folder

Submission Title: Library of the Future - 3rd Edition
This game is not in the current project, the found list, nor on the missing list, archive.org and not on mobygames.
Genre: Referance
Developer:  World Library, Inc
Publisher: World Library, Inc
Released:   1994
Language: English
Format: Bin/Cue
Tested on DOSBOX ece

Screenshots included in zip.

note: This is the DOS equivalent included with the 3.1 CD version.

**Comment by exoscoriae** [comment]
added
