### ISSUE TITLE
Space Quest - The Lost Chapter (2001)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5018]
Discord user Jer reported that the game gives a "Stack Blown" error on a specific screen in the game. He provided a save game and said if you exit to the right you will trigger the error. Here is the save: [SG.zip](https://github.com/exoscoriae/eXoDOS/files/14279574/SG.zip)

Investigating the issue showed that this is a known issue with some AGI fan games including this one. The solutions provided online included fixing the art, using a pre patched copy of the game, or applying the patch yourself.

I tried the prepatched copy of the game I located online, however it created a separate issue. If you edit the AGI interpreter to allow more room for the stack so it doesnt overflow then you are reducing the amount of memory left for the interpreter to use for the game. The pre patched copy must have told the interpreter to use too much for the stack as the intro gave an out of memory error. This is all hard coded and limited in the interpreter so I couldnt just use loadfix or adjust dosbox memory to compensate.

I eventually located a copy of the patch program using wayback machine and found a value that allows both enough room for the stack and enough memory for the intro.

Here is the edited AGI file that is needed, just replace the existing one in the game folder: [AGI_fixed.zip](https://github.com/exoscoriae/eXoDOS/files/14279695/AGI_fixed.zip)

As some of these tools were difficult to find I am attaching them here as well in case other fan AGI games we add to the pack have this sort of error:
[AGI_Version_Detection_(AGINFO).zip](https://github.com/exoscoriae/eXoDOS/files/14279710/AGI_Version_Detection_.AGINFO.zip)
[AGI_Stack_Overflow_Patch_(STACKPATCH10).zip](https://github.com/exoscoriae/eXoDOS/files/14279711/AGI_Stack_Overflow_Patch_.STACKPATCH10.zip)

**Comment by exoscoriae** [comment]
thank you
