### ISSUE TITLE
JimBall (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5020]
This game is supposed to have a sound effect whenever the ball bounces. The CT-VOICE file I previously provided allowed the game to start but it wasnt allowing the effect to play. Spectre has found a copy of CT-VOICE that works fully with the game allowing all effects to play.

Add this CT-VOICE file to the game folder and use this conf: [jimball.zip](https://github.com/exoscoriae/eXoDOS/files/14290904/jimball.zip)

**Comment by exoscoriae** [comment]
yay... now the ball farts
