### ISSUE TITLE
Last Mission, The (1987)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5021]
Discord user 4rioch_22 reported that the game is corrupted.

"When I access level 2 and pass the first two screens, the third screen freezes the game and glitches appear."

@SmilingSpectre confirmed the issue.

I have found alternate versions at https://www.old-games.ru/game/download/2294.html

**Comment by SmilingSpectre** [comment]
1. old-games.ru says "Внимание! Испанская версия игры - единственная работоспособная, поэтому выложена именно она."
"Warning: Spanish version of the game is only one working, so we upload only it".
2. We already has working Spanish version, in the same archive. You need only to change English version "Lastmiss.exe" to Spanish "LMISION.EXE" right in the run.bat.

**Comment by exoscoriae** [comment]
well, sucks we can't have an english version. but it looks like the english version is unofficial anyways. tdc has it marked as a hack translation.

**Comment by exoscoriae** [comment]
I can't get to the second damn level. But I added a language option as well as a hacked file from TDC that was a different english version.  Maybe that one will work. It has a warning it may be buggy
