### ISSUE TITLE
Their Finest Hour The Battle of Britain (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5022]
Game not cracked.

Protection hits when you go to fly a mission. Once your in the plane you are asked to "tune your radio" before you can get flight info. Following the instructions to do so leads to the protection which uses the code wheel.

**Comment by exoscoriae** [comment]
cracked

**Comment by Python-Exoproject** [comment]
While technically the game is cracked and you can play, the flight information is listed as "unavailable" since the radio has been bypassed instead of tuned.

Screenshot is after mission start, press m to open map screen, press "Tune Radio" and attempt made to tune:



![Image](https://github.com/exoscoriae/eXoDOS/assets/67406191/597f8324-b5f2-4f6a-af92-187c923ffcdf)

**Comment by exoscoriae** [comment]
so what is the suggestion? a new crack that tunes the radio?

**Comment by exoscoriae** [comment]
i can't get this screen. it appears to work fine for me.

**Comment by Python-Exoproject** [comment]
Well looks like its my end then if you arent having issues. 

Heres RF1911s patch that he made anyway: [BOB.zip](https://github.com/user-attachments/files/16478116/BOB.zip)

He said "im not sure th0 if the rest is ok as the answer is actually checked many times even during the mission..." so your call on which crack to use. What was the source of the first crack attempt? Considering RF1911s experience id trust his "not sure" and that fact that he noticed that it was checked many times (which may explain why I had a different experience with the first crack?) over many other crack sources

**Comment by exoscoriae** [comment]
I am relucant to patch things that are working...

**Comment by exoscoriae** [comment]
ultimately I don't have the bandwidth to debate all of these little things. I pushed it into the pack with his crack.
