### ISSUE TITLE
Lagaf - Les Aventures de Moktar - Vol 1 - La Zoubida (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5029]
Discord user pbuyle has suggested that this game needs its cycles bumped to cycles=1500. Its seems to be another game that is variable in the game speed depending on how much is happening on screen and at the current 1200 cycles if 3 or more enemies are on screen the game slowsdown

**Comment by exoscoriae** [comment]
cycles shifted to 1500
