### ISSUE TITLE
Once Upon A Time - Abracadabra (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#503]
has watermark Le Vieux Manuel

**Comment by Eulisker** [comment]
Manual in

- French
- English

**Comment by Eulisker** [comment]
I found the english portion of the manual with the watermark removed.

Added to the github folder.

**Comment by Eulisker** [comment]
And i found the complete manual in 

- French
- English
- German
- Italian

I can not say if the spanish portion is missing or if they got another manual.

Also added to the github folder.
