### ISSUE TITLE
Gertrude's Puzzles, Gertrude's Secrets, Robot Odyssey, Rocky's Boots, and Think Quick!

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5030]
Discord user Viliam has pointed out that for the character to be able to make small steps you must use the numpad arrows and have numlock set to off, otherwise the character can only move in big steps.

The current user note on launch just mentions "Use the arrow keys on your numeric pad" so we should expand on this to inform the user that numlock must be off as well

**Comment by exoscoriae** [comment]
notes added
