### ISSUE TITLE
HIND The Russian Combat Helicopter Simulation (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5034]
Discord user Sektor Buzmelic has reported that the game is running a bit slow and that the patch we have in the cd folder doesnt work.

This incompatible version of the 1.2 patch is predominant online and doesnt work from any source. He located a copy of the 1.2 patch that has a different byte size that is compatible and works to bring our copy up to date. The patch includes some nice quality of life updates. I have also provided a new prefs file in the update archive that adds all the detail and sound settings. Archive with files: [1.2 Update.zip](https://github.com/exoscoriae/eXoDOS/files/14360229/1.2.Update.zip)

In regards to the game speed, I agree that the cycles are probably a bit low for smooth gameplay. He recommended 300k, but I think even 150k is a much better feel. If you do decide to implement a cycles increase it will probably apply to the sister game "Apache (1995)" as well.

Lastly Sektor also mentioned a better laid out manual regarding the flight controls which he is going to try and locate again and send our way.

**Comment by SmilingSpectre** [comment]
Somehow this archive contains extra content. It doesn't needed (it's a sound bank, identical to one we have, and preferences). I removed them.
[1.2.Update.zip](https://github.com/exoscoriae/eXoDOS/files/14361547/1.2.Update.zip)

**Comment by exoscoriae** [comment]
300k is nuts. anything above about 150 might as well be "max", in that it will cause all kinds of stuttering problems on machines that can't reach that speed.

150k seems like a lot ofr a 1995 game (Apache), and even a 96' game, but I'll take your word for it.

no manual yet it seems
