### ISSUE TITLE
Reader Rabbit 1 (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5035]
The run.bat option for Sound Blaster had the same sound config comand line option for the game as the MT32 option which was pushing the midi through instead of giving the games adlib sound. Updated the flag to the correct one: [ReadRab1_run.zip](https://github.com/exoscoriae/eXoDOS/files/14360912/ReadRab1_run.zip)

**Comment by exoscoriae** [comment]
fixed!
