### ISSUE TITLE
(Noteworthy game mod) NAIS Shell for MechWarrior 2: Mercenaries

### ISSUE THREAD

**Issue by ZenithRev** [exoscoriae/eXoDOS#5037]
(Posted here at, I believe, eXo's suggestion to do so)

I wanted to bring up an interesting mod for 'MechWarrior 2: Mercenaries', in case it's worth adding to eXoDOS. It's called the 'NAIS Shell' and installs over an existing copy of MW2 Mercs, to offer players access to some new playable machines. These ranged from things like adding the popular Marauder battlemech, to letting players control new unit types like hovertanks and infantry power armor. The mod is a pain in the ass to set up, but it did some genuinely fun things for the game and I hope it's worth considering for eXoDOS!

I've heard conflicting reports on what the final version is; some people say it's 2.2, some say 2.02, others say 2.03. In any case, here are some links to the mod's old website plus some forum discussions about it - the forum discussions are the ones with the best download links for NAIS Shell:

http://web.archive.org/web/19970331082916/nais.annex.com/indexf.htm

http://mech2.org/forum/viewtopic.php?t=1996

https://www.localditch.com/mechwarrior/mercs/downloads.html

http://www.mech2.org/forum/viewtopic.php?t=52

My memory on how to use NAIS Shell is very hazy, but if you think it's worth adding to the project and have questions I'll be glad to share what I remember!

**Comment by exoscoriae** [comment]
NAIS shell is 100% manual.

I went and installed 2.02 and after it renamed a ton of files, it made no different in the actual game

* to use a new logo, the user has to go in and manually rename files
* to use a new chasis, the user has to go in and manually rename files
* I was unable to find any functionality in the game that was enabled with the NAIS shell installed that didn't require the user dropping to a command line to rename files.
