### ISSUE TITLE
The Eye of Typhoon (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#5038]
In the current version some Keyboard keys don’t work for the 2nd player, and we can't navigate in the menu.

I found an application "KEYCTRLS" at OG (https://www.old-games.ru/game/download/6576.html) to change the keyboard keys. 
_Note : place the EXE of the appilication in the game folder, run it from DOS, reassign the keys and click "Save and Exit". 
**In order to work, we need to change iso of The Eye of Typhoon (1996).**

I tested the OG.ru's ISO and the appplication KEYCTRLS on PCEM win 3.1 in dos mode :  The keyboard keys work the second player, and we can navigate through the menu.

@exoscoriae can you save the keyboard keys for the 2nd player, with KEYCTRLS, like this (to match the ones of the manual)
![Capture d'écran 2024-02-24 203153](https://github.com/exoscoriae/eXoDOS/assets/67555221/92a83449-de46-43d3-91d1-3f53383b31a4)

Iso and KEYCTRLS added to the Github bug folder **with covers** (Disc & jewel case)

**Comment by exoscoriae** [comment]
hanged keys as requested

also gave user ability to re-define keys if desired
