### ISSUE TITLE
One Step Beyond (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#504]
pages 9 - 25+ are missing (french  german  italian)

**Comment by SmilingSpectre** [comment]
Found it, but it slightly worse (less DPI). Uploaded. Maybe worth to keep both?

**Comment by TimberlAndRE-de** [comment]
true, the resolution is a bit lower. but i think it's good enough, eXo? added to the github folder, i suggest to replace the current one

**Comment by exoscoriae** [comment]
replaced
