### ISSUE TITLE
Hunt for Red October, The (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5040]
I discovered that there are missing files from our copy and all available copies online that @SmilingSpectre or myself could locate. 

According to the manual a file called 'hfro.exe' should be used to start the game as it provides the cga\ega\tga\vga choice to the user. The TGA exe is also missing from available copies.

We will need to purchase a copy when a reasonably priced copy is located

**Comment by SmilingSpectre** [comment]
Seems, it's a problem with manual only. I had my doubts, but after ripsaw8080 fixed Tandy driver, everything works as expected.

Sound for Tandy also quite unique and not match other versions, so worth to include.

Also game seemingly supports CGA composite, but as it's B&W (and composite only makes it with more grey tones), it's not very important.

[hfro_tandy_fix.zip](https://github.com/exoscoriae/eXoDOS/files/14450262/hfro_tandy_fix.zip)

**Comment by Python-Exoproject** [comment]
As this game also had the tandy=on issue I have included the fixed tandy driver in the zip for that ticket (#5045)
