### ISSUE TITLE
Cracky (2024)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#5046]
This Game is not in the current project,not in the dropbox, not in  TDC. https://www.mobygames.com/game/201968/cracky/
Genre:  Arcade / Platform
Developer: Inufuto
Publisher: Inufuto
Released: 2024
Language: English
Format: zip
Tested on dosbox Svn-Daum EGA and CGA versions

Added to the github folder EGA, CGA, and IBM PC Jr (not tested) versions

**Comment by exoscoriae** [comment]
added

**Comment by exoscoriae** [comment]
did not add pc jr version, as I have not worked with d88 files before
