### ISSUE TITLE
Sentient (1997)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#5049]
Das Spiel braucht die angehängte DOS4GW (umbenannte DOS32/A) um zu starten. Eine aktuellere UVCONFIG.EXE habe ich auch noch angehangen für bessere Grafikkarten Unterstützung. 

Zum installieren muss -freesize 1024 gesetzt werden. 

Das Spiel sollte auf cycles=220000 gesetzt werden. siehe #694 

[Sentient.zip](https://github.com/exoscoriae/eXoDOS/files/14507520/Sentient.zip)

**Comment by TimberlAndRE-de** [comment]
transfered to boohyaka's gitea (eXoDOS-GLP issue nr11)
