### ISSUE TITLE
One Must Fall 2097 (1994)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#5050]
Die momentane Version 2.1 funktioniert  nicht auf deutsch. Die angehängte .zip austauschen und das Spiel in multilanguage.txt löschen.

[One Must Fall 2097 (1994).zip](https://github.com/exoscoriae/eXoDOS/files/14507584/One.Must.Fall.2097.1994.zip)

**Comment by TimberlAndRE-de** [comment]
transfered to boohyaka's gitea (eXoDOS-GLP issue nr9)
