### ISSUE TITLE
Galactic Empire (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5052]
Game not cracked.

Copy protection will crash the game when gameplay starts if not entered correctly or bad crack.

Current code sheet is incorrect, Spectre has found the correct one provided here: [Copy Protection Codes.zip](https://github.com/exoscoriae/eXoDOS/files/14518204/Copy.Protection.Codes.zip)

He has also provided floppy images in desired: [Images.zip](https://github.com/exoscoriae/eXoDOS/files/14518226/Images.zip)

**Comment by xmarksthespot81** [comment]
Fixed: 

https://archive.org/details/galactic-empire-1990-international-version-patch

https://archive.org/details/galactic-empire-1990-patch

You are welcome to use my modification.

Cheers!

**Comment by exoscoriae** [comment]
amazing work @xmarksthespot81 
thank you

**Comment by exoscoriae** [comment]
that is because a different ticket in the manuals\extras sections asked me to change the cp codes.

i went ahead and reset it to yours
