### ISSUE TITLE
The Infernal Tome alternate name

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5053]
![image](https://github.com/exoscoriae/eXoDOS/assets/24454178/bcdb3c27-5404-4880-ad1f-c5b3ecfaa51d)

As picture says, full The Infernal Tome is also named "The Infernal Tome Trilogy". And what we have is the trilogy indeed, as it consist of 3 episodes:

![image](https://github.com/exoscoriae/eXoDOS/assets/24454178/94be5106-daba-4483-b85c-a3297c91115a)

Add the alternate name "The Infernal Tome Trilogy", please?

**Comment by exoscoriae** [comment]
renamed it to trilogy, added the old name as an alt name. thaks @SmilingSpectre
