### ISSUE TITLE
Language Packs - central install.bat syntax issue

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#5054]
@boohyaka found a bug in the 
`/eXo/util/!languagepacks/install.bat` (base pack v6)

![grafik](https://github.com/exoscoriae/eXoDOS/assets/67441153/5f9363a8-1275-404a-a87e-fb9a4e1807d6)

don't know where this -d comes from but it's not a del parameter.
del is actually skipping it altogether, but will actually parse and try to delete the other paths in the string

![grafik](https://github.com/exoscoriae/eXoDOS/assets/67441153/bfae874c-746c-45e3-b943-46061c9b5b82)

fix is pretty easy. just need to remove everything starting and including -d in the batch
it should look like this:
`del ".\eXoDOS\%languagefolder%\!save\%GameName%.zip"`

steps to reproduce the bug:
* install Language Pack game
* uninstall Language Pack game, keep save
* reinstall Language Pack game
* when prompted about the save choose the option to delete it

although it only affects the langauge packs (base pack is fine), the central install.bat for the language packs is part of the base pack, so a base pack fix is needed.

**Comment by exoscoriae** [comment]
i don't believe I wrote this file, did I?

The -d is clearly left over from someone copying a line with the unzip utility.

**Comment by exoscoriae** [comment]
fix applied
