### ISSUE TITLE
My Fearless Friend (1995)

### ISSUE THREAD

**Issue by Resulka** [exoscoriae/eXoDOS#5057]
This Game is not in the current project, the missing list, not in  TDC or on Moby games.
Genre: Educational, Adventure
Developer: SCOPS Software \ Makh-Shevet
Publisher: Telstar Electronic Studios
Released: 1995
Tested in DOS on DOSBOX ECE

Has a Windows installer included but program runs only in DOS.

Added to the github folder EXODOS/Game Submission 
Screenshots and Manual included.

Donation from KO.

**Comment by exoscoriae** [comment]
added

**Comment by parricc** [comment]
The `ManualPath` tag still needs to point to the manual for this game.

**Comment by parricc** [comment]
Python noted the eXoTool fixes manual paths.
