### ISSUE TITLE
The Adventures of Max and Millie (1994)

### ISSUE THREAD

**Issue by Resulka** [exoscoriae/eXoDOS#5058]
Found - Not in Moby Games or in the collection.

Year of Release: 1994
Developed: by Satchel Software
Published by Department for Education and Children's Services South Australia.
Platform:  DOS
Tested in DOSBOX ECE

I've included Screen shots, The Box Art and The Game Manual (Called Children's Help Book), the Hint Book (Called the Teachers Guide) and I've copied pre-installed version I made that just needs to be dumped into a C:\ of any DOSBOX - though I have included the disc images too)

**Comment by exoscoriae** [comment]
added

**Comment by parricc** [comment]
The `ManualPath` tag still needs to be pointed to the manual.

**Comment by parricc** [comment]
Python noted the eXoTool fixes manual paths.
