### ISSUE TITLE
1st Chess Tutor (1992)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#5064]
This Game is not in the current project,not in the dropbox.
According to mobygames there is an updated version titled Grand Master Chess: Tutor & Challenge released in 1995 , (or is it the same game ?)  https://www.mobygames.com/game/144510/grand-master-chess-tutor-challenge/ 
It's in the TDC
Genre:  Educational, Chess
Developer: Merit Studios (Europe) Limited
Publisher: Simulmondo
Released: 1992
Language: English, French, German, Spanish, Italian
Format: zip
a CD version exists :  
![image](https://github.com/exoscoriae/eXoDOS/assets/67555221/fd8c391a-e1f9-48c8-819b-1c5f12e242ee)
https://www.ebay.com/itm/324701128293
Tested on dosbox Svn-Daum. the game seems to have no sound 

Added to the french pak folder "1chesstu" and to the github game submission folder

**Comment by exoscoriae** [comment]
it does appear this game was oriignally part of that pack, but it was split. Either by rippers or maybe released as it's own thing. It is unclear. I added it as it's own stub for now.
