### ISSUE TITLE
An American Tail - Fievel Goes West (1993) Issues

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5067]
The game has a whole couple of issues.

- [x] Name is wrong. It's "An American Tail: The Computer Adventures of Fievel and His Friends", just as [url=https://www.mobygames.com/game/9620/an-american-tail-the-computer-adventures-of-fievel-and-his-frien/]Moby[/url] names it. Box and Manual confirms it and says the game combines "An American Tail" and "An American Tail: Fievel Goes West" movies. 
 
- [x] Game has two title screen, for both movies. Probably, we need to add the first one.
An American Tail (Fievel goes to USA from the snowy Russia):
![image](https://github.com/exoscoriae/eXoDOS/assets/24454178/b7cd6159-81b1-419b-a0c1-9e456063dda6)

An American Tail: Fievel Goes West (Fievel goes to the Wild West):
![image](https://github.com/exoscoriae/eXoDOS/assets/24454178/68f5a349-134a-4585-9ba8-918bc5c86776)

- [x] Game has very bad Tandy support. Even ripsaw8080 wasn't able to revive it. But he supplied the exe with working Tandy sound in VGA (supplied below)

- [x] Our version is missing save slot files. They need to be added into game dir. (supplied below)
 
- [x] We are missing installation floppies. You can install the "packed" version of the game from them, but it's not necessary. It also triggers extra level of protection, but it's nothing bad - game tests for the file "__AT__.%%%" in the root dir of the disc or floppy. Floppies supplied below.
 
- [ ] Disk 4 of the floppies contains the alternate "VIGNETTS.ACT" file. It doesn't used anywhere, and I have no idea what is different - but maybe it worth to research. Or maybe not.

[An American Tail Fixes.ZIP](https://github.com/exoscoriae/eXoDOS/files/14623899/An.American.Tail.Fixes.ZIP)

**Comment by Python-Exoproject** [comment]
This game was in my tandy alt launcher compatibility ticket (https://github.com/exoscoriae/eXoDOS/issues/5045) as on top of Spectres notes above it needs the tandy=on moved to run.bat. Ive removed it from that ticket and place my notes and fixed files here: 

[AmericanTaleFiles.zip](https://github.com/exoscoriae/eXoDOS/files/14624141/AmericanTaleFiles.zip)

**An American Tail - Fievel Goes West (1993)** - This game in exodos v6 offered a tandy choice to the user but it was just pcspeaker. The game needs machine=tandy to give the tandy music, however there is a problem as the tandy mode for this game locks up during the intro music. Neither Spectre nor myself have had any luck getting the tandy mode to work however he sent it to the TDC guys and ripsaw came up with the solution mentioned by Spectre

**Comment by exoscoriae** [comment]
* change name of the game in launchbox
* added second title screen
* added missing save slots
* added new exe file
* added install floppies in folder
* added Python's files (conf & run)
