### ISSUE TITLE
Fatman - The Caped Consumer (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5068]
Discovered that after you use the burp weapon in game once or twice the other sound effects like shooting the carrot stop working when using vanilla\ECE. Staging does not share this issue, so here is a conf for switching it over: [conf.zip](https://github.com/exoscoriae/eXoDOS/files/14636088/conf.zip)

**Comment by exoscoriae** [comment]
done
