### ISSUE TITLE
Alex Higgins' World Snooker (1986)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#5069]
Found images for :

front box - real PC version (in the collection we have only the front cover of the Amstrad cassette version)

back box 

disk image 

proof : 
![image](https://github.com/exoscoriae/eXoDOS/assets/67555221/4195fb19-3ae6-4214-a27e-5df2e2dcff2f)

Added to the github folder images folder

**Comment by exoscoriae** [comment]
replaced
