### ISSUE TITLE
Cardinal of the Kremlin, The (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5077]
Discord user GDI Lord has reported that by running the install program (inst.exe) we can activate the mouse.

I would also like to note that the game is running on vanilla dosbox at the moment but if you switch it to ECE or Staging the messages that scroll at the bottom of the game screen provide a notification pc speaker beep

**Comment by exoscoriae** [comment]
moved to ece

activated mouse
