### ISSUE TITLE
Galactic Empire (1990)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#5078]
I scanned the 

- [ ] manual

It is pretty grimy but maybe it is a little bit better then the current one. I will still set it to bad.

Added to the github folder.

**Comment by SmilingSpectre** [comment]
Not "a little", it's much better. But not ideal, indeed. Well, grime is better than low-resolution over-saturated scan we have now. :)

**Comment by exoscoriae** [comment]
i'm not sure why you guys think it is better?

**Comment by exoscoriae** [comment]
rejected
