### ISSUE TITLE
Overlord (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#508]
pages 68 69 are missing

**Comment by SmilingSpectre** [comment]
Found two versions. Uploaded. One is bad, but have two quick reference pages at the start that are missing in the second. Maybe worth to save them?

**Comment by TimberlAndRE-de** [comment]
the first one is from the original us-release for "Overlord", but it's a bit blurry (all readable) and page 95 is very blurry but also readable
the second one is from the european release "supremacy", but with a good resolution, nothing blurry

i suggest to take the original one for "Overlord" as the manual and keep the "Supremacy" one as an alternate version in extras.

(i cutted the reference-cards from the first one since they don't belong to the manual and created another issue for that: #1363)

**Comment by exoscoriae** [comment]
it doesn't make sense to throw out the entire manual because 2 pages are missing and instead go with a shit quality replacement version. Why not take what we already have an edit the missing pages in?

**Comment by exoscoriae** [comment]
I did what I suggested above
