### ISSUE TITLE
William Shatner's TekWar (1995) CD corrected

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5080]
For some reason, both European and American versions of William Shatner's TekWar (1995) has the first track trimmed wrong. It causes about of one second of data "spilled" on the second track (and it's sounds as a loud buzz sound for the first second of the track). Later releases are identical by data - but free from this error.

So I taken the release from redump marked as "Europe Alt 2" - it's fine.

Uploaded to Github as William Shatner's TekWar (1995) Tracks Corrected.zip

**Comment by exoscoriae** [comment]
replaced cd image
changed conf mount
