### ISSUE TITLE
Monika's Tic Tac Toe (2006)

### ISSUE THREAD

**Issue by gorbatiiivan** [exoscoriae/eXoDOS#5085]
Monika's Tic Tac Toe (2006) crashes when it opens, when is running from "Pixel Perfect & Shader Options" works fine.

https://github.com/exoscoriae/eXoDOS/assets/84850541/ba92937c-a11e-4ea8-876f-41d23aa58858

**Comment by Python-Exoproject** [comment]
Just noting that I could not reproduce the issue, both normal and pixel perfect options are working for me

**Comment by gorbatiiivan** [comment]
I looked again, when starting in full screen mode an error appears, when starting in windows mode is running fine, or the problem is only with me. I apologize in advance :) .

**Comment by Python-Exoproject** [comment]
Thanks for the extra detail @gorbatiiivan, after more testing though it still seems the crash is system specific.

eXo, while I cant reproduce the error there is something different about the way this game handles graphics as it forces the window resolution smaller than our setting in vanilla dosbox for both window and fullscreen. Staging doesnt suffer the issue so suggest switching to Staging 81.1 in dosbox.txt and using this conf: [dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/14852792/dosbox.zip)

**Comment by exoscoriae** [comment]
moved to staging
