### ISSUE TITLE
Microsoft Flight Simulator (v5.1) (1993) - Hawaii scenery

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5088]
Our collection has a small issue with Hawaii scenery (in Disk/Hawaii directory). It is the rip of the Microsoft Scenery Pack for Flight Simulator, with three scenaries - Hawaii, Carribbean and Japan. Which are available separately. I uploaded the CD as 

Microsoft Scenery Pack for Flight Simulator ISO.zip

I see two possible courses of actions:

- Remove separate CARIB, HAWAII and JAPAN disks, and put ISO into collection instead of them.
- Remove installer, Caribbean and Japan from the HAWAII dir.

Maybe something else?

**Comment by exoscoriae** [comment]
done
