### ISSUE TITLE
Microsoft Flight Simulator 1.0

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5091]
Looks like I missed this one when I moved composite games over to Staging. To provide the reason ill just post the ECE and Staging screenshots below. Here is the conf for Staging that includes composite and aspect tweaks to make the instruments round: [dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/14885828/dosbox.zip)
 

![image](https://github.com/exoscoriae/eXoDOS/assets/67406191/1aaf0c5c-5642-47a5-8d83-c658c35490dc)
![image](https://github.com/exoscoriae/eXoDOS/assets/67406191/30478138-c047-4829-811e-474bb2e50426)

**Comment by exoscoriae** [comment]
done
