### ISSUE TITLE
Microsoft Flight Simulator 2.0

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5092]
Since I looked at v1.0 I also looked at 2.0 again. Seems the composite for this one is not currently working. As with all other composite games I provide here a conf to switch the game to Staging. I have gone the route of using an exception so that we can use CGA for the composite and PCJR for the RGB. This is because composite under PCJR for this game is not great, but looks fine in CGA mode while the PCJR offers hi and lo res modes for RGB.

[MSFlght2.zip](https://github.com/exoscoriae/eXoDOS/files/14894193/MSFlght2.zip)

**Comment by exoscoriae** [comment]
looks good
