### ISSUE TITLE
LHX Attack Chopper (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5093]
Discord user remowilliams highlighted that this game is defaulting to EGA graphics. With some further info from Eulisker, hunvagy, and Spectre I looked into it.

The Tandy sound option wont work unless the game is running with machine=tandy and vanilla dosbox which is currently running it cant handle it properly so I converted it to Staging. Ive provided the Staging confs\exception.bat to allow a choice between PC and Tandy as well. I did not add choices for CGA or EGA. CGA can be added if felt warranted but will need a run.bat for the pc user choice, EGA didnt add anything when Tandy was already provided as the graphics are the same.

[LHXAttac.zip](https://github.com/exoscoriae/eXoDOS/files/15190796/LHXAttac.zip)

Ive also added mouse flight control as the default when the game is launched. The user can change this in game if desired by pressing esc and changing the option under the control menu

**Comment by r3mowilliams** [comment]
LHX also seems to default to the incorrect axes set (joystick 2) when a multi joy controller is attached.

Examples:

- When starting with an XB1 controller attached - flight control is on the right stick, not the left. 
- When starting with a Logitech Extreme 3D Pro flight stick - flight control is on the rudder/throttle, not the main stick.

Setting the following seems to address this:

[joystick]
2axis

**Comment by exoscoriae** [comment]
added 2axis to the IBM conf. didn't edit the tandy one.

moved to staging
