### ISSUE TITLE
Where in the USA is Carmen Sandiego (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#5095]
found

- [x] manual

I found the manual from the first IBM 5,25" release and a second one from the 3,5"/5,25" re-release.
I think the second one is better as it contains more information then the one from the first release.

The current manual in the collection is the map that was additionally included in the box. it should be switched to "Extras"

Proof:
First release:
![s-l1600](https://github.com/exoscoriae/eXoDOS/assets/67441153/1eab8636-df55-4e8d-a6bc-518f49711870)

re-release (with the "GOLD" sticker on front and thinner big box):
![s-l1600-1](https://github.com/exoscoriae/eXoDOS/assets/67441153/2a5f6e6a-f7f3-44f6-a845-e996ca9aa3b6)
![s-l1600](https://github.com/exoscoriae/eXoDOS/assets/67441153/af05a9c3-d81f-47f0-8637-cc71973d09f7)

**Comment by exoscoriae** [comment]
thanks!
