### ISSUE TITLE
Duke Nukem 3D - Atomic Edition (1996).bat calls @echo on instead of @echo off

### ISSUE THREAD

**Issue by funkno** [exoscoriae/eXoDOS#5098]
This causes some batch file text to not make sense. Also, the second line of the batch should be:
"..\..\..\util\SetConsole.exe /minimize"
instead of the "..\..\..\util\SetConsole.exe /min" currently used.

**Comment by SmilingSpectre** [comment]
Confirmed.

**Comment by Python-Exoproject** [comment]
Thanks guys but already fixed here: #4862
