### ISSUE TITLE
Viper (1998)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5099]
This game is the only one running on Dosbox 0.63 so if we can move it off this then we can remove 0.63 from the emulator folder for eXoDOS. To that end the Staging guys have figured out the issues the game has on later versions and forks of dosbox (https://github.com/dosbox-staging/dosbox-staging/issues/3585) but will not be implementing it as its not worth the complexity to the code for one game.

They also discovered however that dosbox X is compatible with specific settings in the conf, so here is the required conf ([dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/15223596/dosbox.zip))

This requires we use the version of x in the 'X2' folder so switch the game to use that in dosbox.txt

**Comment by exoscoriae** [comment]
mouse isn't capturing in x2

**Comment by exoscoriae** [comment]
seems it was because int33 was disabled in the conf
is there a reason for that?

I have re-enabled it.

moved it to x2 with the mouse re-enabled

**Comment by Python-Exoproject** [comment]
The game is less stable with int33=true and will occasionally give just a black screen. Int33 is dosbox x way of saying internal mouse driver=true.

The reason the mouse didnt work is because I had intended to provide the external mouse driver "amouse.com" which allows the game to have a mouse even with the internal driver disabled with int33=false, however it looks like I added it to the conf but overlooked adding it to the zip archive I posted.

Here is the mouse driver: [AMOUSE.zip](https://github.com/user-attachments/files/15930349/AMOUSE.zip). Put it in the game folder and set int33 back to int33=false. You should still have a fully functioning mouse in the game and it will be more stable

**Comment by exoscoriae** [comment]
cool. done
