### ISSUE TITLE
Hound of the Baskervilles (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5100]
This game is not fully compatible with any version of Dosbox. Under most forks including vanilla, ECE, and Staging there is graphical corruption. In X and Daum it seems at first to play better as the graphical corruption doesnt appear at first, but if you move your cursor to the bottom of the screen when in game the graphics again corrupt. More detail here https://github.com/dosbox-staging/dosbox-staging/issues/2906

As both X and Daum run this game as well as each other and we would rather ditch Daum Im suggesting a change from Daum to X. The conf will need some tweaks as its a Daum conf, here is one with the basics: (replaced by zip two comments down)

**Comment by Python-Exoproject** [comment]
Thanks @SmilingSpectre.

So with that knowledge we can now play the game using X (or Daum) with no corruption as the new mouse driver provided doesnt allow the cursor to go low enough to corrupt the game. Please use this conf with dosbox X and put the mouse driver in the game folder: [dosbox.zip](https://github.com/exoscoriae/eXoDOS/files/14981099/dosbox.zip)

**Comment by SmilingSpectre** [comment]
Python, after comment in Staging Github I found that Cute Mouse can be the better choice than DOS-V above. It's more responsive. But it needs tuning.

1. Activate serial port in config with
[serial]
serial1=serialmouse

2. Run Cute Mouse with 
CTMOUSE.COM /1 /r5
[CTMOUSE.ZIP](https://github.com/exoscoriae/eXoDOS/files/14997454/CTMOUSE.ZIP)

**Comment by exoscoriae** [comment]
staging won't run it yet eh?

moved it to x.

using cutemouse as suggested above by spectre
