### ISSUE TITLE
unzip.exe crashes on Windows Server 2022

### ISSUE THREAD

**Issue by robvdl** [exoscoriae/eXoDOS#5105]
eXoDOS includes a version of unzip.exe that doesn't work on Windows Server 2022, it always crashes.

As a workaround I have tried to:

1. Download eXoDOS lite v6
2. Install it on a Windows 10 machine
3. Copy it over to a Windows Server 2022 machine

That gets it running, but off course the first game you try to install, unzip.exe is run again and crashes.

This makes eXoDOS completely unusable on Windows Server 2002, I am using Standard Evaluation.

![image](https://github.com/exoscoriae/eXoDOS/assets/1018674/c8f594ab-a1a6-4299-b654-6c6a85d8422f)

**Comment by robvdl** [comment]
Where did unzip.exe come from in eXoDOS v6? What source?

**Comment by robvdl** [comment]
I am aware that running on Windows Server 2022 is strange, but I just wanted to try it out of interest.

I am running on a KVM host on a Ryzen 5950x and given it 16 cores. Everything else works but unzip.exe from eXoDOS is crashing. I have no idea where unzip.exe comes from, if it is really old possibly.

**Comment by robvdl** [comment]
The InfoZip project is very old and full of issues. I wonder if going forward relying on such a tool is wise, or if it is possible to just use a Python script to unzip.

**Comment by SmilingSpectre** [comment]
unzip.exe is too new, actually. It was compiled specifically to allow unicode names. All old unzips cannot manage Japanese/Chinese and such things. Affects several extras and one or two games right now, I think. Maybe less. But then under Windows collection one asks for C libraries. No idea if will it work under Windows 2022 at all.

**Comment by robvdl** [comment]
Yeah it doesn't, it crashes.

I've veen that patched version of unzip's source code as well. Makes me wonder how long people are going to keep trying to compile 10+ year software with just minimal fixes to keep it on life-support (this is  not eXo's problem but InfoZip abandoning it over a decade ago. I've done enough Googling that there isn't really much of a solution as nobody is maintaining unzip.exe
