### ISSUE TITLE
Extase (1991)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5114]
Our version is CGA/EGA/VGA and PC Speaker.

old-games.ru has versin which added Tandy and Adlib sound/music.

Uploaded.

**Comment by Python-Exoproject** [comment]
@exoscoriae Worth switching our copy over for the Adlib sound, but no need to setup a Tandy user option as tandy graphics are same as EGA and the game sound when using Tandy is the same as the PC Speaker sound.

Just replace current game files and good to go

**Comment by exoscoriae** [comment]
replaced files
