### ISSUE TITLE
Tony La Russa Baseball II (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5117]
There is an expansion disk that has teams for the 1992 season and pre 1993 season which was highlighted by discord user Samsonite11. They havent provided a disc image but I found out that the copy of the game available on oldgames.ru ([Tony_La_Russa_Baseball_2.zip](https://github.com/exoscoriae/eXoDOS/files/15132439/Tony_La_Russa_Baseball_2.zip)) includes the teams.

Our copy is installed off the CD and still uses the mounted CD so probably only need to copy in the team files

**Comment by exoscoriae** [comment]
added 2 teams folders
