### ISSUE TITLE
Tony La Russa's Ultimate Baseball (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5118]
There are multiple expansion disks for this game which was highlighted by discord user Samsonite11. They havent provided disc images but I found copies of all but one are on oldgames.ru

The ones ive found: 
Fantasy Draft Manager: [Tony_La_Russas_Ultimate_Baseball_Fantasy_Manager.zip](https://github.com/exoscoriae/eXoDOS/files/15132819/Tony_La_Russas_Ultimate_Baseball_Fantasy_Manager.zip)
NL Stadiums: [Tony_La_Russas_Ultimate_Baseball_NL_Stadiums.zip](https://github.com/exoscoriae/eXoDOS/files/15132824/Tony_La_Russas_Ultimate_Baseball_NL_Stadiums.zip)
AL Stadiums: [Tony_La_Russas_Ultimate_Baseball_AL_Stadiums_Disk.zip](https://github.com/exoscoriae/eXoDOS/files/15132829/Tony_La_Russas_Ultimate_Baseball_AL_Stadiums_Disk.zip)
Great Teams: [Tony_La_Russas_Ultimate_Baseball_Great_Teams_1901-1968.zip](https://github.com/exoscoriae/eXoDOS/files/15132832/Tony_La_Russas_Ultimate_Baseball_Great_Teams_1901-1968.zip)

One I cant find: 
Classic Stadiums Disk (maybe @SmilingSpectre might have luck?)

For the installation, the Fantasy disk is basically an update disk that cleans up the game menus a bit and adds an option to launch the Fantasy Draft. One draw back is that the new exe isnt cracked and our current neverlock crack is for the original exe.

The Stadium disks replace a few files but I believe they are fixes and updates so non destructive

The Greatest Teams disk however is completely destructive and replaces the original release teams, so something will need to be setup to handle this.

**Comment by SmilingSpectre** [comment]
Everything is from TDC. They have also 1991 teams. Unfortunately, no Stadiums here. But there is the crack for Fantasy. (I didn't test it).

[Tony La Russa's Ultimate Baseball- Ultimate Expansion Disk - Fantasy Manager Disk (Installer) (1991)(Strategic Simulations, Inc.) [Sports, Addon].zip](https://github.com/exoscoriae/eXoDOS/files/15133390/Tony.La.Russa.s.Ultimate.Baseball-.Ultimate.Expansion.Disk.-.Fantasy.Manager.Disk.Installer.1991.Strategic.Simulations.Inc.Sports.Addon.zip)

[Tony La Russa's Ultimate Baseball- 1991 Teams Expansion Disk (Installer) (1992)(Strategic Simulations, Inc.) [Sports, Addon].zip](https://github.com/exoscoriae/eXoDOS/files/15133369/Tony.La.Russa.s.Ultimate.Baseball-.1991.Teams.Expansion.Disk.Installer.1992.Strategic.Simulations.Inc.Sports.Addon.zip)

Wait, I believe, there is _no_ such thing as "Classic Stadiums addon". See:

![image](https://github.com/exoscoriae/eXoDOS/assets/24454178/6eb7a7b6-93f6-416f-a84b-2904d5b7192c)

It is the same thing.

I tried to install stadiums, and it allows two choices for each stadium indeed - modern and classic.

**Comment by xmarksthespot81** [comment]
Gave it a quick rundown.

Check my patches here: 

https://archive.org/details/tony-la-russas-ultimate-baseball-multi-version-patch

Feel free to use.

Game On!

**Comment by exoscoriae** [comment]
ooo boy. this one was fun.

added a emnu to switch between the greatest teams and the expansion teams, as the GT disk was destructive.

Also used @xmarksthespot81 's crack as well.

**Comment by Python-Exoproject** [comment]
Two thoughts on this one:

1. Do we need the pause when switching teams? I know its to notify the user copy is complete but they probably dont need to know, just press the menu button and it does its thing and returns them to the menu
2. It might be useful to add a variable to the user menu to display the current state (IE if the GT or Original teams are active)

**Comment by exoscoriae** [comment]
if you would like to create the sel approach, you are welcome to.

I personally don't care that much.

I feel a lot more like ripsaw these days. screw sports sims.

**Comment by Python-Exoproject** [comment]
Done:

[eXoDOS.zip](https://github.com/user-attachments/files/16458791/eXoDOS.zip)

**Comment by exoscoriae** [comment]
thank you
