### ISSUE TITLE
X-Men - Children of the Atom (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5121]
A few people have had trouble with this game, especially when launching directly into fullscreen.

With krc's suggestions ive created a conf for use with dosbox Staging that fixes that issue along with another common complaint about tearing. Ive also provided files to reinitialize univbe that was needed. the fixes have been tested by three people that had reported the issues and all confirm fixed. Please convert to Staging and use these files: [Xmen.zip](https://github.com/exoscoriae/eXoDOS/files/15133169/Xmen.zip)

**Comment by exoscoriae** [comment]
done
