### ISSUE TITLE
SimLife (1992)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#5124]
I found

- [x] Bug Report Instructions

Added to the github folder.

**Comment by SmilingSpectre** [comment]
I found the source of all our docs about SimLife. And somehow they are bigger and worse than original (whis is 200DPI).

So everything needs to be replaced (including doc @Eulisker found above)

Uploaded.

[ ] - SimLife (1992) Greetings.pdf (that's the same doc as "Bug report" above)
[ ] - SimLife (1992) Addendum & Quickstart.pdf
[ ] - SimLife (1992) Registration Card.pdf
[ ] - SimLife (1992) Lab Book.pdf
[ ] - SimLife (1992) Manual.pdf

**Comment by exoscoriae** [comment]
replaced and added
