### ISSUE TITLE
Hugo 3 - Jungle of Doom (1992) directory mismatch issue

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5128]
Hugo 3 - Jungle of Doom (1992) has a case inconsistency between its game and conf/batch directories. The game extracts to `hugo3jd`, however the `!dos` directory is called `hugo3Jd` (with a capital `J`). Note that all batch and conf files reference the game directory as `hugo3jd`. However, since the scripts expect the game directory to be the same as the `!dos` one, the game fails to launch with the Linux patch.

We should either change the directory in `!dos` to match that of the actual game directory. Or, alternatively, we could replace the game zip, conf, bat files, and LaunchBox references. The latter method, while more changes, might have a benefit of causing less issues for people upgrading the collection.

**Comment by parricc** [comment]
For directory names are currently as follows:
`hugo3jd` <- Hugo 3 - Jungle of Doom (1992).zip
`hugo3Jd` <- !dos

Fix option 1:
- If `!dos` directory name is changed to `hugo3jd`, the LaunchBox references will need to be changed to match it.

Fix option 2:
If game directory name is changed to `hugo3Jd`, the `dosbox.conf` and `exception.bat` references will need to be changed to match it.

**Comment by exoscoriae** [comment]
this was previously fixed

**Comment by Python-Exoproject** [comment]
Not in the copy I have from the sync? As per Parricc I have `hugo3jd` in the zip and `hugo3Jd` in the !dos folder

**Comment by parricc** [comment]
eXo might be mixing this issue up with the Jeopardy! Junior Edition (1989) one, which had a similar issue. https://github.com/exoscoriae/eXoDOS/issues/5221

**Comment by parricc** [comment]
@exoscoriae After you change the `!dos` directory to `hugo3jd`, please make sure to also do the same in the `MS-DOS.xml` files. There's 3 references in each file.

**Comment by exoscoriae** [comment]
I was referring to an issue where the hugo3 and hugo3jd folders were actually mixed.
