### ISSUE TITLE
John Madden Football II (1991) - TANDY option incorrect

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5130]
Pretty sure the TANDY option has SB16 music. The run.bat file has it defined as follows, but it sounds exactly the same as the SB16 option:

```
:TANDY
CONFIG -set "sbtype=none"
CONFIG -set "mididevice=default"
cls
@MFB2
goto quit
```

**Comment by Python-Exoproject** [comment]
Thanks for the report parricc but I fixed this one when I reviewed all the games that use exception.bat by switching it to Staging, removing the exception.bat, updating the conf, and fixing the run.bat. See #4976
