### ISSUE TITLE
Super Dog Story (1997)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#5135]
We have a CD RIP in the collection, without music in game, and covers of the box are missing.

I found :

- a CD version (bin+cue & audio files) with English, Chinese and Korean languages (tested on dosbox)

- front and back covers 

added to the github _bugs_ folder with front & back covers

**Comment by exoscoriae** [comment]
replaced disk
reinstalled the game
added game speed notes
added cover scans
