### ISSUE TITLE
Low Blow (1990) - MT32 option broken

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5138]
In Low Blow (1990), the `dosbox.conf` file is missing the following line:
`mt32.romdir=.\mt32`

Without that line, no music plays in Linux when selecting the MT32 option, and in Windows, the music isn't correct.

**Comment by Python-Exoproject** [comment]
Awesome find @parricc, makes a big difference on windows if we actually point to the MT32 roms when using MT32 as well :-) I assume when it didnt find the roms it went and used the windows default midi device instead.

I know it might be annoying on your side that Linux is not as forgiving but I think its great as its showing all these games we thought were working but in reality we were getting a fallback option that uses internal windows device. Its especially bad when its an MT32 game as the default windows device is a GM device, not MT32 and it butchers it bad

**Comment by exoscoriae** [comment]
thank you @parricc
