### ISSUE TITLE
A320 Airbus ILS Approach Charts

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5139]
It seems, our version of A320 is missing approach charts. Uploaded.

A320 Airbus ILS Approach Charts.pdf

I also noticed that German manual (available on Archive.org) is mostly the same as our English one, but has two addendums we are missing - hotkey list and airport coordinates. Maybe it worth to be added to extras somehow?

**Comment by exoscoriae** [comment]
going to assume euro

**Comment by SmilingSpectre** [comment]
Indeed. It's all European airports there.
