### ISSUE TITLE
Lure of the Temptress (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5142]
Parric discovered in the course of setting up linux exodos that this game was not actually using SB when the SB choice was selected, instead it was still using midi but sending it to the internal windows midi device.

This happens because the game is still detecting the midi interface and refuses to use the SB when it does so. To fix we simply need to deactivate the interface, so:

add *config -set "mpu401=none"* to the SB16 section of run.bat

**Comment by Python-Exoproject** [comment]
@SmilingSpectre has found an EGA version so I have created a setup that will allow it to be a choice along side the VGA option. This needed the exception.bat as the machine type needed to be ega for that version to work. The game already had an exception for ScummVM so I just hijacked it and removed the ScummVM option as that is our plan going forward. Please find in the archive the extra and replacement files for EGA\VGA which also includes the above midi\sb fix

[Lure.zip](https://github.com/exoscoriae/eXoDOS/files/15209977/Lure.zip)

**Comment by exoscoriae** [comment]
added your files.

also numped the cycles. 3k for a game in 1992 is really slow.

it seems to speed up the loading of the mt32 sounds at least
