### ISSUE TITLE
10 Game Fixes for Silmarils games and some ex-X games

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5146]
The included conf fixes in this archive ([Conf Tweaks.zip](https://github.com/exoscoriae/eXoDOS/files/15231430/Conf.Tweaks.zip)) can be summed up in two groups:

**Games that have the wrong output= mode and\or fullresolution=**

Alfs Party Kit
Chickens
Chrono Quest II
Land of Devastation
Jet Stream - as well as fixing the output I simplified the conf down to what was needed as it was a full X conf before

**Silmarils Games related tweaks with notes on issue**

Transarctica: Not actually running on X but as it has the same intro tone issue as the other Silmaril games, should probably be moved over
Ishar 1: Changed to SBPro2 which removes the warble sound as the card initializes. Increased cycles
Ishar 2: Not actually running on X but as it has the same intro tone issue as the other Silmaril games, should probably be moved over
Bunny Bricks: New game setup file as previously was set to AZERTY keyboard. Changed to SBPro2 which removes the warble sound as the card initializes. Sound FX randomly drop out in all forks
Storm Master: Increased sound using mixer command. Increased cycles a bit so more responsive when click on council members

**Comment by exoscoriae** [comment]
moved Ishar 2 over. it helped it.

Transarctica has the same messed up tones in X though

**Comment by Python-Exoproject** [comment]
Transarctica needs fullresolution=desktop as you moved it to x

**Comment by exoscoriae** [comment]
done
