### ISSUE TITLE
Game fixes (lpt_dac= replacing disney=) for Alt Launcher compatibility

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5147]
As discussed in a number of other places Staging have replaced the vanilla dosbox emulation of disney= which merged two different devices into one (Disney Sound Source and Covox Speech Thing) into two distinct devices that each match the their original hardware closer. The new conf setting of lpt_dac= is used with lpt_dac=covox and lpt_dac=disney as the replacement. This necessitates moving these games to Staging for alt launcher compatibility. Any other discoveries or changes are discussed below.

[eXoDOS.zip](https://github.com/exoscoriae/eXoDOS/files/15236817/eXoDOS.zip)

As usual even though its not required for the changes, I have included the launch bat or .exo file in each games folder in my attached archive just for reference so that you can easily identify which game a folder is for.

---------------------------------------------------------------------------------------------------------
<ins>Games with other changes</ins>

For these games on top of the conf and\or run.bat fix I discovered another issue and fixed it. The files required for the fixes are included in the above zip, the below are just descriptions of what I changed and why.

**Ante-Up at The Friday Night Poker Club (1990)** - Our copy was a scene rip and new copy provided by Spectre includes covox files required to activate speech. Replace all files with the ones in the above zip

**Dick Tracy - The Crime-Solving Adventure (1991)** - This game has an option for either Disney or Tandy sound. One has better music while the other has voices. I have created the needed setup to offer both. The terrible flickering this game suffered on all forks while driving around has also been fixed now in Staging

**Mega Tetris (1994)** - Current game setup was for no sound. Sound Blaster option doesnt work properly but the covox choice is great so setup for covox included

**SimAnt - The Electronic Ant Colony (1991)** - Covox wasnt previously setup as an option but is done well so setup provided to offer choice

**Spell It Plus! (1989)** - Covox speech is now enabled though its only present in the 'Study It' mini game, required files included

**Stunt Island (1992)** - Game wasnt setup for Disney fx so updated to do so.

---------------------------------------------------------------------------------------------------------
<ins>Other things worth noting</ins>

- There are a few Sierra games with included Staging confs for moving over to Staging. This is because the CMS sound option uses the Disney Sound Source for the FX
- Galactic Empire (1990) is either not cracked or the current crack is bad as it doesnt work. The current code sheet in the Extras folder is wrong which means currently you cant get into the game. Spectre found a working code sheet which was added to ticket #5052 though a working crack would be great.

**Comment by exoscoriae** [comment]
@xmarksthespot cracked Galactic Empire for us.

Everything else is done and converted to staging.

thank you!
