### ISSUE TITLE
3D Baller (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5150]
Discord user Waswat reported that this game asks for the sound card address\irq\dma as free text fields on startup but there is no mention of what these should be. User note needs to be added informing what values to use

**Comment by TimberlAndRE-de** [comment]
It can be solved by using "KPUSH.COM" (it's in `\eXoLanguagePacks\eXoDOS\German\tools` on the Syno)

Place the KPUSH.COM file in the game folder and call it in the dosbox.conf:

```
@mount c .\eXoDOS\3DBaller
c:
cls
kpush "1" CR "220" CR "7" CR "1" CR
@baller
exit
```

**Comment by exoscoriae** [comment]
great work. done

**Comment by Python-Exoproject** [comment]
When you die three times and run out of lives the game insta quits so fast its like it crashed. Its legit how the game handles loosing but maybe its worth exiting to a user menu that asks if they want to play again or quit?

**Comment by exoscoriae** [comment]
I created a run.bat to try this, however the game does not run properly the second time

you can test easily by commenting out the exit, and manually restarting the game a second time.

the screen is heavily glitched.

**Comment by Python-Exoproject** [comment]
yeah ok, not great.

We could just add a pause before the exit, then it would at least show it hasnt crashed and display the games exit screen?

**Comment by exoscoriae** [comment]
done
