### ISSUE TITLE
Simplify full conf for two games

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5153]
These two games below still have full conf files somehow. Please find below simplified ones to replace:

Wolf (1994) - [wolf.zip](https://github.com/exoscoriae/eXoDOS/files/15283112/wolf.zip)

Theme Park (1994) - [ThemPrk.zip](https://github.com/exoscoriae/eXoDOS/files/15283114/ThemPrk.zip)

**Comment by exoscoriae** [comment]
theme park is still unstable. hence the full conf. I go in periodically and mess with settings. went ahead and put your simplified one in for now.
