### ISSUE TITLE
MDK (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5157]
Discord user arthur071169 highlighted that there is a patch for this game that enables in game saving using F2 and F3 to restore. Please find the update here: [MDKDOS_E.ZIP](https://github.com/exoscoriae/eXoDOS/files/15337009/MDKDOS_E.ZIP)

**Comment by exoscoriae** [comment]
this was already in the existing file

**Comment by Python-Exoproject** [comment]
Confirmed, must have been a sync issue where the game zip I had was older than the update being applied.

The current zip I have has a different issue though. The conf is looking for `MDK (USA).cue` but only the previous `MDK.iso` in in the zip. Is this another sync issue?

**Comment by parricc** [comment]
The current sync still has the older `MDK.iso` file from eXoDOS 5.

**Comment by exoscoriae** [comment]
very strage.

I was playtesting this one the other day. how could the entire disk be missing now?

i went and located the use release again and repacked it
