### ISSUE TITLE
MadSpace (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5158]
This one is a bit of a mess at the moment. The CD fmvs arent playing, the mouse controls dont work, and the current mixer setting doesnt work for the alt launcher.

Specter investigated it and says its also a hybrid hack job of the Russian CD with an English rip. He has uploaded the official English\German release on the share as Github/Game Submission/MadSpace (1997)(Eng+Ger).zip

1. Reinstall from this image using sb16 for sound and cd for music at 640x480 res. The sound test might sound drowned out by the music but this is fixed in a later step
2. Update the dosbox.conf to remove the mixer setting and add under the [sblaster] tag sbmixer=false. For this game this will fix the sound balance for all forks of dosbox
3. Bring in run.bat and the files needed for network play
4. Decide which patches from the previous copy we had are worth adding. They are found in the current install under \eXoDOS\MadSpace\MADSPACE\madspace\madspace patches\madspace patches. The second patch sounds like it might need some sort of backup\restore user option as it looks like its a destructive install for some extra network levels

**Comment by exoscoriae** [comment]
well, I did the above.

the game seems totally different now.

in the old build, when I started it, I seemed to be in a first person mode.

now I'm in a on-rails shooter that is mouse controlled outside in space.

i added patch1, but not patch 2 or 3

2 sounds destructive, as noted above, and 3 was about modem dialing and demos.... neither of which sound important.
