### ISSUE TITLE
Fix for F-117A Nighthawk and F-19 Stealth Fighter

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5163]
On a tip from one of our users I am looking over some suggested fixes listed on someones blog. One of the fixes is to repair access to a secret mission in these two games. I have no idea if the fixes actually work and even the person who made the fix says that although hes patched a bug in the files that has been there since release and had it working in a test setup he has never triggered the missions in the game during normal play.

Here is the link to the info: https://github.com/debugcom/Hacking-F117A/blob/main/Part2.md

And here is the hex edited files for both games:
[F-117A Nighthawk.zip](https://github.com/exoscoriae/eXoDOS/files/15405351/F-117A.Nighthawk.zip)
[F-19 Stealth Fighter.zip](https://github.com/exoscoriae/eXoDOS/files/15405352/F-19.Stealth.Fighter.zip)

**Comment by exoscoriae** [comment]
backed up the original files, and created a menu option to use the hacked file or the original file. Added a note explaining what the hack does.

**Comment by Python-Exoproject** [comment]
The F-19 Stealth fighter that I have synced has the files in the zip for the hack\orig but the run.bat hasnt been updated to use them.

Since I also noticed that this game has an Innovation SSI sound option that we hadnt enabled I provide here a run.bat and conf so that the game will enable the hack\orig option and allow SSI to be selected. Extract into relevant folders, switch to Staging.

**Comment by exoscoriae** [comment]
added the new run.bat

**Comment by Python-Exoproject** [comment]
The run.bat got added but the conf wasnt changed and the game is still on ECE. This will be an issue for the SSI sound user option

**Comment by exoscoriae** [comment]
done
