### ISSUE TITLE
Subwar 2050 (CD-ROM) (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5164]
We have two copies of the CD in the CD folder (do we need\use both?) and both images have a subfolder called "Scenario" that contains the official scenario campaign for the game. Im 99% positive that this has not been installed in eXoDOS as it is a seperate install to the main game and can easily be overlooked.

Once installed the game will need cracking again, and cycles may be a bit low

**Comment by exoscoriae** [comment]
removed the "original" iso. It was a german copy.
ran the scenario installer
recracked the game using neverlock
bumped cycles to 25k
