### ISSUE TITLE
Infocom Interactive Fiction Extras and Manuals

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#5165]
I spent a bunch of time to go through the extras and manuals for all the Infocom Interactive FIction Games.
I found a bunch of new extras, joined the InvisiClues Maps together, found a bunch of inconsistencies and added the interactive InvisiClues form #4910.
Rather than having an issue for every single game i opted to make a excel sheet and have it all in one github issue.

[Infocom Interactive Fiction Extras and Manuals.xlsx](https://github.com/exoscoriae/eXoDOS/files/15413351/Infocom.Interactive.Fiction.Extras.and.Manuals.xlsx)

The manuals to the games are from a wide range of different releases. I wrote something about that on discord:

> @Retro eXo I recently got down a rabbit hole with all the infocom interactive fiction. Before i put it all on github i have a question about how you would handle the manuals. I guess i am preaching to the choir here but just for completeness sake a short overview about the different sorts of releases. There are 2 major and 2 minor types of releases
> 
> Folio: The first 12 adventures were released as a Folio packaging. All different shapes and sizes (the starcross saucer i.e.) They all had a pretty short and mostly technichal manual. How do you interact with the parser and so on. 
> Grey Box: The standard form of infocom releases. They rereleased the first 12 and up to the final 6 or so in this packaging. They have a more elaborate manual. There is always a part with story related stuff in the beginning and the technical part of the old manual in the end.
> 
> Mastertronic: These were ReReleases in the UK. They lack the feelies and come in a square box. I would include them as extras because people in the UK and europe in general probably have more nostalgia for these releases then the american ones. They also have installation information for IBM. There should be a reference card in the other releases but we mostly are missing these. 
> Solid Gold: Another ReRelease by Infocom. A few of their adventures got a release in this line. Golden Box, different manual and the games are slightly altered in that they have an included hint system for example.
> 
> There is one other type of manual for a few games that comes from the Floppy manufacturer Dysan. Apparently they released a bunch of infocom adventures to promote their new 3.25" floppy disk (which i have never heard of before). These manuals are in a different format to the folio manuals but are content wise identical.
> Currently the manuals are a bit all over the place. Sometimes its folio, sometimes its dysan, sometimes its grey box.
> I would propose to have all the grey box manuals set as manuals and have Folio, Mastertronic and Solid Gold as extra where they are available.

I uploaded the .zip with all the files to the github folder.

**Comment by exoscoriae** [comment]
done!
