### ISSUE TITLE
Montezuma's Revenge (1984)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5167]
Discord user HtheB has provided us with the files for a version of this game that was provided as an easter egg in Montezumas Return. It looks to be the Atari release of the game packaged with a DOS based Atari emulator. Its worth adding as its enhanced over the DOS release, not sure if best as its own entry, with Montezumas Return as thats the game it was released with, or as an alt option for Montezumas Revenge.

[montezumas_revenge.zip](https://github.com/exoscoriae/eXoDOS/files/15418727/montezumas_revenge.zip)

**Comment by Python-Exoproject** [comment]
On the files synced to my end neither Montezuma's Return (1997).zip or Montezuma's Revenge (1984).zip have been updated, where do I look to find the implementation of this?

**Comment by parricc** [comment]
`Montezuma's Revenge (1997).zip` isn't even present on the sync.

**Comment by exoscoriae** [comment]
very strange. all the files to launch it where there. as were the xml entries for the front end.

I've recreated the file.
