### ISSUE TITLE
Stonekeep (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5168]
Jemy found that the very necessary v1.2 patch for Stonekeep isnt actually installed. Extract this zip into the game folder overwriting where required to fix. The new sk.bat also restores the "Do you wish to Register" nag screen so it might be worth removing that line from the bat.

[SK_V12.ZIP](https://github.com/exoscoriae/eXoDOS/files/15418878/SK_V12.ZIP)

**Comment by exoscoriae** [comment]
re-extracted the patch.  not sure why it wasn't working, the files were there.
