### ISSUE TITLE
Phantasmagoria 2 - A Puzzle of the Flesh (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#518]
needs to be cropped

**Comment by TimberlAndRE-de** [comment]
ArkhangelAzrael found a better version also with more pages
added to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by ArkhangelAzrael** [comment]
Might have found a better/alternative version here: https://mysterymanor.net/gamemanuals/Phantasmagoria%20II%20A%20Puzzle%20of%20Flesh%20Manual.pdf
