### ISSUE TITLE
Search for the Titanic (1989) User's Manual

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5185]
We have Player's Guide (game usage). This one is installation guide.

Search for the Titanic (1989) User's Manual.pdf

**Comment by TimberlAndRE-de** [comment]
The Player's Guide as a manual is correct I think because the eXoDOS user doesn't have to install but needs the infos on how to play the game. But the User's Manual is missing as an extra.

there's already an issue for this: #1787

added it there
