### ISSUE TITLE
Descent - Anniversary Edition and Definitive Collection

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5195]
We have a mess here.

There is Descent Anniversary Edition (1996), but we are missing the disc. Our disc is from Definitive collection, and slightly different by levels and texts. It's also ISO.

At the same time, we haven't Definitive Collection at all - and it features different soundtracks for Descent 2.

I uploaded both to untangle the mess.

- [x] Descent Anniversary Edition (1996).zip
- [ ] Descent I and II - The Definitive Collection (1997).zip

**Comment by exoscoriae** [comment]
anniverary edition fixed.  Will do the other one next.

**Comment by exoscoriae** [comment]
debating on the need for the "definitive collection".

**Comment by exoscoriae** [comment]
Working with parric, we co nfirmed there are no differences in the definitive edition. All D1 content was included in Descent: Anniversary and all D2 content was included in Descent 2: Vertigo.
