### ISSUE TITLE
Oregon Trail, The - Classic Edition v3.0.1 (1997)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5205]
Same as our Oregon Trail Deluxe, The (1992), only slightly newer (deluxe is v3.0) and with installer. I recommend to replace our version with this one.

Has text manual on CD (we are missing any one).

Also included extra scans.

- [ ] Oregon Trail, The - Classic Edition v3.0.1 (DOS) (1997).zip
- [ ] Oregon Trail, The - Classic Edition v3.0.1 (DOS) (1997) Installation  Manual.zip
- [ ] Oregon Trail, The - Classic Edition v3.0.1 (DOS) (1997) Scans.zip

**Comment by exoscoriae** [comment]
Went ahead and replaced the files.

threw the scans and manual out. 

I would like the actual 1992 release. Not this 1997 cd release.
