### ISSUE TITLE
F-15 Strike Eagle III (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5206]
Discord user remowilliams noted that in this game you can select joystick during flight or using setup.exe, however this is overwritten whenever you start the game due to the sound config being saved in the same file making you have to change the controller every time you start the game.

Here is a run.bat as a workaround: [run.zip](https://github.com/exoscoriae/eXoDOS/files/15502450/run.zip)

**Comment by Python-Exoproject** [comment]
An additional issue noted by remowilliams. Im posting the whole conversation here, I havent investigated

"The campaign mission generator is not working correctly (at least for the Korea campaign).  All campaign missions generated start from a refueling tanker point, and this is incorrect.  Missions should have more variety and land based start locations.

Steps to reproduce:
Install and run game
Select a Korea campain game
Attend mission briefing, notice mission starts from a tanker and never land bases
Decline mission and attend another mission briefing
Repeat endlessly

Deleting the highlighted files immediately following an install seems to fix this issue.

On a fresh CD install only the second listed set of files should exist in the game directory."

![image](https://github.com/exoscoriae/eXoDOS/assets/67406191/2926ddb2-0b7c-485b-862b-30a8d47c2a40)
![image](https://github.com/exoscoriae/eXoDOS/assets/67406191/e10c456c-8714-4fef-be92-ceec8787039c)

**Comment by exoscoriae** [comment]
checked and done
