### ISSUE TITLE
Crime Patrol (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#5207]
wysiwyg found

- [x] manual (current one is a txt file) - one page a bit blurry but all readable

proof: https://www.ebay.com/itm/155034976868

**Comment by exoscoriae** [comment]
replaced

**Comment by parricc** [comment]
The xml file still refers to the txt version, `Manuals\MS-DOS\Crime Patrol (1994).TXT`, which is no longer present.

I can push out a substitution to along with my xml case corrections to correct the entry to:
`Manuals\MS-DOS\Crime Patrol (1994).pdf`

**Comment by parricc** [comment]
Proposed change attached to https://github.com/exoscoriae/eXoDOS/issues/5333

**Comment by parricc** [comment]
Reopening as eXo prefers handling non-case issues on a case-by-case basis rather than as part of bulk set of changes.

**Comment by exoscoriae** [comment]
fixed earlier
