### ISSUE TITLE
Game zips stuffed by loss of hidden files during repacking of zips

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5215]
As configured, this game does not run in DOSBox nor ScummVM.

**Comment by Python-Exoproject** [comment]
This is connected with issue #1696, it looks like we had a copy of the game with all the floppy files and a fixed com file and PCJR exe at some point but now the files are missing from eXoDOS even though the conf is setup to launch them. @SmilingSpectre Do you still have a copy or able to get another copy of the files that were discussed in the original ticket as they were not uploaded to the ticket?

**Comment by Python-Exoproject** [comment]
As for the scummvm launch option, we are removing it anyway so not going to fix that one

**Comment by SmilingSpectre** [comment]
@Python-Exoproject I never seen it, it seems. Previous issue seemingly indicates that NRS contacted eXo directly. There is no matching games at TDC - only one booter and one cryoflux images. Sorry.

**Comment by SmilingSpectre** [comment]
Ah, wait, I found it in the eXo's discussion.
[WINNIE.zip](https://github.com/user-attachments/files/15525025/WINNIE.zip)

And I see where problem originated. All missed files are hidden. Can we have the same problem anywhere else?! %(

**Comment by Python-Exoproject** [comment]
Im repurposing this ticket to discus the core issue that the above uncovered.

It looks like when we repacked all the zips to switch out all the .ba1 files 15 game zips accidentally had hidden files removed with Winnie the Pooh in the Hundred Acre Wood being one of them.

Boohyaka investigated and found:

4 affected zips dont matter as the lost files are temporary doc files (~$xxx.doc style) or an autoexec.bat
2 affected zips were previously picked up and fixed via another ticket
9 affected zips need to be restored

The 9 games are:

4 Balls Billiards (1993)
B-Clopd (2002)
Cruncher (1991)
Doni's Mazes (1985)
Ein Kmo Bamba (1996)
Mino's Adventure (1997)
Time Runners (1994)
Winnie the Pooh in the Hundred Acre Wood (1985)
Dia Bolo (1997)

@boohyaka has placed a copy of each of the original working zips in the share drive under `eXoDropBox\Personal Folders\Boohyaka\HiddenFix` for use in restoring the games to working order

**Comment by exoscoriae** [comment]
replaced files
