### ISSUE TITLE
Shuttle The Space Flight Simulator (1992) Documents

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5217]
As I discovered, we uses old HOTU B/W scan. It also consist of combined manual and mission guide. So:

- [x] I uploaded scanned manual. Two pages are replaced from HOTU, as they was broken beyond repair. Shuttle The Space Flight Simulator (1992) Manual.pdf.
- [x] I uploaded separated Mission Guide. It's the same as ours (it's "printed" ours), but it miss text layer and much bigger in result. You are welcome to cut it out from the current manual itself. Shuttle The Space Flight Simulator (1992) Mission Guide.pdf.
- [x] We have Mission Guide.txt and Shuttle Docs.txt in extras. They are the same as PDFs, so probably can be safely deleted.

**Comment by exoscoriae** [comment]
thank you
