### ISSUE TITLE
'Nam 1965-1975 (1991)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5218]
Current version is missing CGA.

@Eulisker bought the game, then NewRisingSun deprotected it for us.

Uploaded.

'Nam 1965-1975 (1991).zip

**Comment by exoscoriae** [comment]
added files and launch option

**Comment by Python-Exoproject** [comment]
If we switch the game to Staging and use these files ([nam6575.zip](https://github.com/user-attachments/files/15856058/nam6575.zip)) the black and white CGA looks better. Its even better with the alt launcher using auto-crt shaders as this mitigates a lot of the bleed effect

**Comment by exoscoriae** [comment]
ok, added files
