### ISSUE TITLE
Alchemist (Warp Power Interactive Entertainment Ltd.)(1998)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5219]
@ArkhangelAzrael bring my attention to fact that I never filed Alchemist game into Github. So I shifted it there. Full English/Chinese CD with Chinese missions, which can be totally replaced with Windows version released later. Needed files supplied in the archive.

I included the .txt as reminder too.

Alchemist (Warp Power Interactive Entertainment Ltd.)(1998).zip
Alchemist (Warp Power Interactive Entertainment Ltd.)(1998).txt

**Comment by exoscoriae** [comment]
added.  what a cool game
