### ISSUE TITLE
Jeopardy! Junior Edition (1989) directory mismatch issue

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5221]
Jeopardy! Junior Edition (1989) has a case inconsistency between its game and conf/batch directories. This causes the game to fail to launch in Linux.

For clarification, the directory names are currently as follows:

`JeopJun` <- Jeopardy! Junior Edition (1989).zip
`jeopjun` <- !dos

Fix option 1:
- If `!dos` directory name is changed to `JeopJun`, the LaunchBox references will need to be changed to match it.

Fix option 2:
- If game directory name is changed to `jeopjun`, the `dosbox.conf` references will need to be changed to match it (mount and imgmount lines).

**Comment by exoscoriae** [comment]
changed !dos folder name.

Launchbox isn't in linux. why would it need to be changed? Something to do with the linux launcher borrowing those files?

**Comment by parricc** [comment]
The Linux frontend uses the LaunchBox files.

**Comment by parricc** [comment]
There's three references in each of the `MS-DOS.xml` files that need to be changed to `JeopJun`.

**Comment by exoscoriae** [comment]
i just looked at the xml and they are all fine

![image](https://github.com/user-attachments/assets/7520af34-7465-45d1-9c2a-4f5dc9adc325)
