### ISSUE TITLE
Mortal Kombat (1993)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5225]
The Censored Mortal Kombat German release copy protection screen is not cracked. When attempting to enter the specified words from the manual, I failed to get past the copy protection screen. Perhaps it requires the German manual. Or maybe I'm just not good at following directions. In any case, this should be looked into.

**Comment by parricc** [comment]
To clarify, this is in the base eXoDOS release, not the GLP.

**Comment by xmarksthespot81** [comment]
Fixed: https://archive.org/details/mortal-kombat-1993-german-censored-version-patch

You are welcome to use my modification.

Cheers!

**Comment by exoscoriae** [comment]
patched!
