### ISSUE TITLE
Synthetic Dimensions games

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5229]
Three games by Synthetic Dimensions are affected by a graphics bug that causes some black lines to appear on screen throughout the game.

The affected games are: Chronicles of the Sword (1996), Druid - Daemons of the Mind (1995), and Perfect Assassin (1997)

@interloper98 noted on the Staging discord that ripsaw has made a TSR fix.

As well as the TSR he also noted some cycles fixes for two of the games which I tested and agree with as they reduce the cycles the games run at from max (via auto) which fixes text in one of the games to a readable rate.

Lastly, since ive been looking at mixer settings recently I also took the time to adjust the sound levels for the three games as the current inbalance caused the music to be very quiet. For Perfect Assassin and Chronicles of the Sword this means switching to Staging as in one case the fluidsynth needs adjusting which is done via mixer in Staging instead of fluid.gain and in the other case the required levels were different between ECE and Staging and as Staging is used for Alt Launcher I set the levels for that.

Please find all required files here: [eXoDOS.zip](https://github.com/user-attachments/files/15807449/eXoDOS.zip)

**Comment by Python-Exoproject** [comment]
As an aside it might be worth keeping this open even after the above is implemented as Staging plan on integrating what the TSR does into dosbox code (https://github.com/dosbox-staging/dosbox-staging/issues/3762)

**Comment by johnnovak** [comment]
> As an aside it might be worth keeping this open even after the above is implemented as Staging plan on integrating what the TSR does into dosbox code ([dosbox-staging/dosbox-staging#3762](https://github.com/dosbox-staging/dosbox-staging/issues/3762))



> As an aside it might be worth keeping this open even after the above is implemented as Staging plan on integrating what the TSR does into dosbox code ([dosbox-staging/dosbox-staging#3762](https://github.com/dosbox-staging/dosbox-staging/issues/3762))

Yeah, I'm gonna do that probably tomorrow which will render the TSR unnecessary if all goes well 🤞🏻

**Comment by exoscoriae** [comment]
leaving this open for now and not making any current changes.

We should probably go ahead and transition them to staging 81.1 in prep for whenever a version is released that has this integrated.

**Comment by exoscoriae** [comment]
converted druid conf to a staging compatible one

**Comment by johnnovak** [comment]
Fixed in the latest Staging 0.82-alpha dev build (you no longer need the TSR).

**Comment by Python-Exoproject** [comment]
This ticket is now ready to proceed with Staging 82 now in the pack.

Here is a copy of Staging 82 with all the extra files we use: [Staging0.82.0.zip](https://github.com/user-attachments/files/17647131/Staging0.82.0.zip)

Here are the files needed for Chronicles of the Sword (1996), Druid - Daemons of the Mind (1995), and Perfect Assassin (1997) to be moved to Staging 82 and no longer use the TSR: [eXoDOS.zip](https://github.com/user-attachments/files/17647137/eXoDOS.zip)
