### ISSUE TITLE
Mario's Time Machine (1993)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#5230]
The front cover in the collection is for Mario's Time Machine: Deluxe Edition a windows 3.1 game (according to mobygames https://www.mobygames.com/game/12156/marios-time-machine/covers/)

There is no back cover no media in the collection. 

I found :
- the real covers for Mario's Time Machine (1993), and a CD cover
- an advert of the game

added to the github folder image folder

**Comment by exoscoriae** [comment]
added
