### ISSUE TITLE
Game fixes (fluid.gain & mt32.output.gain) for Alt Launcher compatibility

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5232]
Staging has moved the volume control from the .gain settings into the mixer so that it can be controlled easily and with the same options as the other sound devices. This required updating games that we had set gain for. Please find attached new run.bat and\or confs for the changes. Additional issues found and fixed noted below: [eXoDOS.zip](https://github.com/user-attachments/files/15849111/eXoDOS.zip)

All games are already either on Staging for main launch or should be moved to it. The games are:

**Dark Legions (1994)** - This one is giving me an interesting problem. From a fresh install the game works one or two times but every time after it locks up whenever I try to move a character on the board or black screens when I press next turn. Ive tried many many things but no luck. I asked @SmilingSpectre to try as a confirmation but he could not repeat my issue. Im very curious to see if you have any trouble with it. Just run the game, do a quickstart, and either move a character or end turn, then close the game and try again a few times on both sound choices. Further to this issue I tried the floppy version and it worked no problem for me, so its related to the CD version and seems to be whenever the CD would be accessed. Its in ECE as well as Staging.

I will also note that there is a CD version patch located in the patch folder on the CD which is meant to make the game more stable, though it made no difference to my issue. I was still able to balance the volume though so moving to Staging and the new mixer settings are good to go.

**Hi-Octane (1995)** - Nothing noteworthy, just move to Staging and use provided files for mixer changes

**Jurassic Park (1993)** - Nothing noteworthy, just move to Staging and use provided files for mixer changes

**Legend of Kyrandia Book 2 - The Hand of Fate (1993)** - This one is actually here to remove the previous mixer settings as in staging no volume tweak is needed

**Penthouse - Hot Numbers Deluxe (1993)** - Nothing noteworthy, just move to Staging and use provided files for mixer changes

**Rex Blade - The Apocalypse (1996)** - This one is actually here to remove the previous mixer settings as in staging no volume tweak is needed. I also tweaked the cycles so they dont use 100% cpu

**Sigil (2019)** - Move to Staging for mixer tweaks. Also noted that the sound.cfg for the SC55 choice wasnt setting the mpu port so I fixed that as well

**Sigil II (2023)** - Was already on Staging but volume balance wasnt great, so tweaked them. Also noted that the sound.cfg for both sound choices was set to 22000 instead of 44000 and the SC55 choice had the sb port on 330 instead of 220 with the mpu port not defined

**Comment by exoscoriae** [comment]
above it says all game are already on staging for main launch.... none of them were.

so i moved them over.
