### ISSUE TITLE
Fire and Ice (1993)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5233]
Game isn't cracked, and quite obnoxious with the protection (you need to find the correct word in the manual, then match it with codes page).

If you cannot enter the right code, game continues... only no enemy drops key parts, so you cannot leave the next level.

Neverlock seems able to hack it.

**Comment by Python-Exoproject** [comment]
As you pointed out in discord @SmilingSpectre the sound blaster doesnt work in ECE when VGA is selected. Switch to Staging 81.1 to fix using this conf: [conf.zip](https://github.com/user-attachments/files/15902938/conf.zip)

**Comment by exoscoriae** [comment]
patched and moved to staging

**Comment by Python-Exoproject** [comment]
The wrong game was switched to Staging in dosbox.txt

Fire and Ice (1993) should be on Staging, Fire and Ice (1989) was on vanilla

**Comment by exoscoriae** [comment]
fixed
