### ISSUE TITLE
Campaign (Empire Software)(1992) Extras

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5236]
- I found the manual for CD-version, which is significantly different from the floppy counterpart - mostly in added "multimedia" part though. I recommend to add it as extra.
- There is also the battle map in the same package. Added.

Campaign (Empire Software)(1992) - Enhanced CD-ROM Edition.pdf
Campaign (Empire Software)(1992) D-Day Landings Battlemap.jpg

**Comment by exoscoriae** [comment]
added as extras
