### ISSUE TITLE
Mutanoid Math Challenge, The (1991)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5237]
Game is manual-protected. Protection triggers randomly during game start (and never after that). Unfortunately, we haven't the manual. But fortunately, all answers are stored in the game in plain text, so I extracted them.

[Mutanoid Math Challenge, The (1991).txt](https://github.com/user-attachments/files/15883764/Mutanoid.Math.Challenge.The.1991.txt)

**Comment by xmarksthespot81** [comment]
I´ve fixed the Copy Protection in case you want to include it:

**Comment by exoscoriae** [comment]
patched. thank you
