### ISSUE TITLE
Mutanoid Word Challenge, The (1992)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5238]
There are a couple of issues with this game.

1. It's password-protected too, the same way as its Math counterpart. And the same way it stores passwords in plain text, so here they are.
[Mutanoid Word Challenge, The (1992).txt](https://github.com/user-attachments/files/15883825/Mutanoid.Word.Challenge.The.1992.txt)

2. It stores user data in the same file as the sound data, so our sound selection method eliminates any progress for each re-run. It needs to be changed.

3. The game haven't the way to eliminate the existing users, and have three junk users in a roster already. So I am uploading the clean roster - it still needs at least one "Dummy" user, to save the sound settings though.
[SETUP2.ZIP](https://github.com/user-attachments/files/15883942/SETUP2.ZIP)

4. Infamous ibmpc5150 (he disappeared from betaarchive at 1st March, and I am troubled about it) uploaded the different floppy version for the game, without the protection, it seems. I suspect, the differences are deeper than that, as almost every file is different, but I haven't time and patience to check it thoroughfully. @Resulka checked it though and found zero differences, which is weird too... but who knows. Uploaded into github folder.

Mutanoid Word Challenge, The (1992) Floppies.zip

**Comment by xmarksthespot81** [comment]
Use this copy: https://archive.org/details/003536-MutanoidWordChallenge

Doesn´t seem to trigger the protection, which is weird considering these are supposed to be the Original Disk Images.

All the best!

**Comment by xmarksthespot81** [comment]
Hi!

This Disk Image here has no Copy Protection: https://archive.org/details/003536-MutanoidWordChallenge

It´s weird considering those are supposed to be the Original Image Files.

All the best!

**Comment by exoscoriae** [comment]
@xmarksthespot81 
those files won't mount for me at all, and if I dump their contents to disk it says there is no disk installed

**Comment by exoscoriae** [comment]
for whatever reason staging is able to load these images. ece could not.

reinstalled from images

**Comment by exoscoriae** [comment]
now I am seeing the disk version has no sound

**Comment by exoscoriae** [comment]
@SmilingSpectre seems you and Resulka didn't look super close, because these diska are the same as the ones @xmarksthespot81 linked to on archive. And they are missing MT32 and SC55

**Comment by SmilingSpectre** [comment]
@exoscoriae It's the same disks I uploaded on Github. Game installed from it is significantly different by files everywhere. Weird that I didn't notice sound missing.

**Comment by xmarksthespot81** [comment]
Here is my Fix:

https://archive.org/details/mutanoid-word-challenge-1992-patch

Enjoy!

**Comment by exoscoriae** [comment]
all patched up. thanks!
