### ISSUE TITLE
1942 The Pacific Air War (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5240]
It was suggested here (https://discord.com/channels/454359114601201666/1247212854176649277) that we should start fresh with this game. Current issue is that the digital sound isnt working (press f10 in mission and under sound switch digital sound on, no sound from guns).

remo suggested just copying in the game folder from the CD and it should fix it, while Spectre suggested starting again and gave links to the patched CD version.

Jemmex is currently used and will be needed again if we rinstall along with xms\ems\etc still needing to be false. Remo also suggested higher cycles for running with all the detail settings on as we do.

Also if resinstalling you will need to start the game, get into a mission, and press f10 to setup the sound and also f9 to max all the graphics and viewing distance.

I didnt test as spectre seemed to have it in hand

**Comment by exoscoriae** [comment]
so the cd has the expanion disk already included?

**Comment by exoscoriae** [comment]
mouse seemed fucked for me, but I am currently working remotely through a remote viewer.... so maybe it is my setup. Please test the mouse for me when you QA this.

**Comment by exoscoriae** [comment]
tested network, still works.

had to restore jemmex or it shit the bed
also patched the gold version because the 1942cd.com executable was broken

unsure if the expansion is included. 

the cd has a regular version and a gold version on it. gold is win3x only.

**Comment by Python-Exoproject** [comment]
Expansion is included, mouse worked. Only thing might be to increase mouse sensitivity but ill just leave the note for you to action if you wish to and close out the issue
