### ISSUE TITLE
Rol Crusaders (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5241]
Jemy investigated this one and left notes in discord: https://discord.com/channels/454359114601201666/1250473751317844070

**Comment by exoscoriae** [comment]
ok... got the extra levels added.

also moved it to staging

his notes mention the mouse moving odd and not being able to use fruits. Unfortunately I don't have the free time right now to screw around and see if I can find a solution to a problem that may very well be a part of the game
