### ISSUE TITLE
Newsroom, The (1985) & Newsroom Pro, The (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5243]
These two new printer compatible games have a similar issues to the ones shared by my ticket for New Print Shop Companion, The (1989).

Is the template you use for printer games at fault? Now that the Print Shop confs have been fixed to remove things like output=software it might be worth grabbing one of them and replacing your printer support template if this is the case.

Anyway, for these two games one is on ECE when it needs to be on X for printer support and they both need output=openglnb and fullresolution=desktop

**Comment by exoscoriae** [comment]
both were set to fullresolution=desktop already

just had to move them to openglnb and then the one to x.

very odd. not sure what was going on with that part
