### ISSUE TITLE
J.R.R. Tolkien's The Lord of the Rings Vol 1 (1990) - Staging \ Emulation Bug

### ISSUE THREAD

**Issue by exoscoriae** [exoscoriae/eXoDOS#5244]
@Python-Exoproject Notes:
**The tandy sound option is terrible and I've discovered its because it only sounds as it should when machine=tandy and the game is set for TGA video. If this is implemented then its a significant improvement for the tandy option, however there is a catch. Whenever the actual gameplay starts dosbox crashes with an MCB chain error and even Stagings flags to allow dosbox to continue in the face of these errors wont overcome it. So we can either leave it as it is sounding terrible and not how it would have sounded on hardware, or remove the Tandy choice.**

Seems the primary solution would be to get the actual emulation fixed, or if the issue is inherent to the game's code we can try to find a work around.

**Comment by SmilingSpectre** [comment]
It doesn't crash for me in Staging. And even in the current ECE. Am I need to do something specific to trigger it?

**Comment by exoscoriae** [comment]
10,000 seems high for 1990. I haven't tested it or anything, but we do have the CD version we can compare to.

**Comment by exoscoriae** [comment]
@SmilingSpectre did you actually change the machine type to tandy? Because it immediatly crashed for me.
