### ISSUE TITLE
Bible Adventures (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5246]
Not cracked

**Comment by xmarksthespot81** [comment]
Can you verify a few things for me? 

- You talk about Version v1.5 correct?
- If you start Baby Moses and David and Goliath do you also have bogus gfx?

**Comment by Python-Exoproject** [comment]
Ill leave this with you and @SmilingSpectre since you guys seem on top of it

**Comment by xmarksthespot81** [comment]
Here is my Multi Patcher for Version 1.4 / Version 1.5 and Version 5.0.

Doesn´t solve the problem with the strange files names in 1.4/1.5 only the Manual Copy Protection Removal so far.

https://archive.org/details/bible-adventures-multi-patch

**Comment by exoscoriae** [comment]
crack applied.

still looking for v1.5 cd
