### ISSUE TITLE
Prehistorik 2 (1993)

### ISSUE THREAD

**Issue by XavierVelo** [exoscoriae/eXoDOS#5248]
This game have weird protection system where from level 3 there is discoloration of our caveman (pic. 1). Provided is CD version of this game without protection and looks like pic. 2. Folder must be mounted as CD to work.
![1](https://github.com/exoscoriae/eXoDOS/assets/66518085/87dd26f6-8331-4394-bb79-588437ca9835)
![2](https://github.com/exoscoriae/eXoDOS/assets/66518085/a4f5e739-052e-4404-a7e1-9699c75622b1)
[Prehistorik 2.zip](https://github.com/user-attachments/files/16033379/Prehistorik.2.zip)

**Comment by SmilingSpectre** [comment]
Which one is discolored? I see raspberry red replaced with light brown everywhere on the screenshot, not caveman only. Maybe it's intended to be that?

**Comment by SmilingSpectre** [comment]
The game is from the CD "Ten Great Games". There is unwrapped version of this CD, it's much more handy and portable. Here is the Prehistorik 2 from there (it has 4 levels different from ours - no idea _what_ is different though):
[Prehistorik 2.ZIP](https://github.com/user-attachments/files/16034511/Prehistorik.2.ZIP)

**Comment by XavierVelo** [comment]
Yes, not only caveman. This weird colors are supose to be due to bad crack.
https://www.gog.com/forum/prehistorik_series/prehistorik_2_wrong_colors_on_level_3
This post is from 2022 but I've read about it some 10 years ago, can't find it now :/

**Comment by exoscoriae** [comment]
replaced with spectres version. as far as I could tell, it was the exact same levels as xavier sent.
