### ISSUE TITLE
Drakkhen (1990) VGA version

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#5249]
I found a VGA version
![image](https://github.com/exoscoriae/eXoDOS/assets/67555221/b14d19fc-a9fe-4b35-b008-a81af262a651)

We have an EGA version in the collection
![image](https://github.com/exoscoriae/eXoDOS/assets/67555221/abcda912-6eb2-400b-9ea1-adefec8475fa)

Added to the Gihub bug folder

**Comment by exoscoriae** [comment]
replaced old version with this one
