### ISSUE TITLE
Silmarils games on X

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5250]
These 8 games are on X currently due to the intro tone issue. The team at Staging have now cracked the issue and once Staging 82 is released these games can be looked at for moving over from X to Staging for their main launch:

Transartica (1993)
Ishar 2 (1993)
Ishar 1 (1992)
Bunny Bricks (1993)
Storm Master (1992)
Boston Bomb Club (1991)
Metal Mutant (1991)
Crystals of Arborea (1990)

**Comment by Python-Exoproject** [comment]
Now that Staging 82 is released this can be actioned.

Please find a copy of Staging 82 with all the stuff we use added to the folder here: 
[Staging0.82.0.zip](https://github.com/user-attachments/files/17634956/Staging0.82.0.zip)

Please convert all the above mentioned games to 82 using these files: [eXoDOS.zip](https://github.com/user-attachments/files/17634975/eXoDOS.zip)

**Comment by exoscoriae** [comment]
converted
