### ISSUE TITLE
Prince of Persia 1 & 2 internal cheat codes

### ISSUE THREAD

**Issue by Dutchmagic** [exoscoriae/eXoDOS#5258]
Prince of Persia 1:
Load the game through the DOS prompt, using the command:
PRINCE MEGAHIT

Decrease time	-
Display your Coordinates	Shift+C
Drink small potion	Shift+S
Extra energy bar	Shift+T
Extra life (Max is 10)	Shift+T
Flip screen	Shift+I
Go to next level	Shift+L
Increase time	+
Kill all enimies on the screen	K
Look up	U
Move to bottom of screen	N
Move to left of screen	H
Move to right of screen	J
Move to top of screen	V
New life	R
Show coordinates	C
Show sprites/animations	Shift+B
Slow falls	Shift+W

Prince of Persia2:
prince.exe yippeeyahoo

+ - Increase time left
- (minus) - Decrease time left
K - Kill all enemies on the screen
R - Resurrect you where you last died
F1 - Toggle slow motion mode
F2 - Toggle position display (When pressed in conjunction with F1)
F3 - Player on/off
F6 - Toggle ruler
[Shift]+S - Turn into the shadow/flame
[Shift]+T - Add energy
[Shift]+K - Subtract energy
[Shift]+R - Display room number and jump right
[Shift]+W - Float down and jump left
[Shift]+I - Turn screen upside down
[Shift]+B - Blank out non-animated objects
[Alt]+N - Skip to next level
[Alt]+D - Create a DUMP?.TXT file

Courtesy of: https://popuw.com/cheats2.html

**Comment by exoscoriae** [comment]
these have been enabled via a menu, as well as Prince 4D

**Comment by Python-Exoproject** [comment]
Using the cheats I found that our copy of Prince 4D was the broken one. Here is a fixed copy of the game that lets you exit level 10 into level 11: [4dprince_fixed.zip](https://github.com/user-attachments/files/16324715/4dprince_fixed.zip)

**Comment by Python-Exoproject** [comment]
Also, in POP 2 the run.bat is missing the 'K' in the choice line that allows the keys to show

**Comment by exoscoriae** [comment]
replaced 4d prince files

Fixed missing K. thanks!

**Comment by exoscoriae** [comment]
I also went in and added the ability to launch the dev mode levels for PoP2 using the "gameplay" command line.

**Comment by parricc** [comment]
```
choice /C:123456K /N Please Choose:

if errorlevel = 6 goto keys
if errorlevel = 6 goto quit
if errorlevel = 5 goto GP
if errorlevel = 4 goto cheats
if errorlevel = 3 goto SC55
if errorlevel = 2 goto MT32
if errorlevel = 1 goto SB16
```

The first if should be:
`if errorlevel = 7 goto keys`

**Comment by exoscoriae** [comment]
thanks...

hopefully this is the last damn time this bounces back to me.

**Comment by Python-Exoproject** [comment]
I almost didnt want to post this as I didnt want to bounce it back...

The game is all fine but (at least on my sync) there is a copy of run.bat in the \!dos\PPersia2 folder that needs to be deleted.

Also, not a big thing but since ive already reopened the issue, when I tested the gameplay mode the cheats werent working for my unless I also enabled them using the separate menu option, while the user note says that cheats appear to be enabled when using gameplay mode

**Comment by exoscoriae** [comment]
the cheats that are enabled are level skips, as some levels are impossible in gameplay mode.

i changed the wording...

**Comment by Python-Exoproject** [comment]
Sorry but I have to bounce this one again for a typo:

 `Cheats ahould also be enabled.`

and since ive had to open it again, (at least on my synced copy) that errant run.bat is still in the \!dos\PPersia2 folder

**Comment by exoscoriae** [comment]
i'm done. i don't care anymore

**Comment by exoscoriae** [comment]
![Uploading image.png…]()
and no, it's not

**Comment by exoscoriae** [comment]
there wouldn't be typos if you guys didn't keep asking me to change it voer and over and over and over. seriously, this is such a massive waste of my time.

**Comment by exoscoriae** [comment]
this is closed. no further QA
