### ISSUE TITLE
Breach 2 (1990)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5263]
In the run.bat file, there is a mount line with an invalid directory:

```
mount a .\eXoDOS\breach2\Cam14 -t floppy
```
The game directory contains a `Cam1` folder, but not a `Cam14` folder.
This game also requires a `run_lin.bat` file for it to function correctly in Linux.

Please use the corrected `run.bat` file and the `run_lin.bat` file in the attached zip.
[breach2_fixes.zip](https://github.com/user-attachments/files/16152188/breach2_fixes.zip)

**Comment by exoscoriae** [comment]
good catch.

done
