### ISSUE TITLE
Star Trek - Judgement Rites CD (1993)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5264]
The cycles needs to be changed to 25000 for the game to play smoothly in Linux. Tested 25k in both Windows and Linux.

Please also add the run_lin.bat file from the attached zip to the game archive so that it works correctly in Linux.

[stjudgec_linux_fix.zip](https://github.com/user-attachments/files/16164542/stjudgec_linux_fix.zip)

**Comment by exoscoriae** [comment]
done
