### ISSUE TITLE
Aces games and overwriting controls

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5265]
As per many other games the Aces series games save their sound settings in the same file that saves the users control preferences. Here are the run.bat files needed to overcome the issue using the method previously used on Build games etc

[Aces.of.the.Pacific.zip](https://github.com/user-attachments/files/16164797/Aces.of.the.Pacific.zip)
[Aces.over.Europe.zip](https://github.com/user-attachments/files/16164786/Aces.over.Europe.zip)
[Red.Baron.zip](https://github.com/user-attachments/files/16164776/Red.Baron.zip)
[A10.Tank.Killer.zip](https://github.com/user-attachments/files/16165331/A10.Tank.Killer.zip)

Further for A-10 Tank Killer, the mouse was terrible under ECE so ive provided conf to switch the game to Staging. I also had to allow for greater cycles for the 1991 updated version and come up with a way to only apply this tickets overwriting controls fix to the 1991 release as its not relevant to the 1989 release

**Comment by exoscoriae** [comment]
switched a-10 to staging.
updated run files for other games
