### ISSUE TITLE
Command and Conquer (1995)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5266]
Please add the run_lin.bat file from the attached zip to the game archive so that it works correctly in Linux.
~~<removed old fix>~~

Updated `run_lin.bat` file to reflect eXo's 2024-07-29 changes:
[comcon_linux_fix.zip](https://github.com/user-attachments/files/16447046/comcon_linux_fix.zip)

**Comment by exoscoriae** [comment]
done
