### ISSUE TITLE
Normality (1996)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5271]
Please add the `run_lin.bat` file from the attached zip to the game archive so that it works correctly in Linux.

There is also a `run.bat` file in the fix archive that includes a case correction. Even though case sensitivity issues don't affect Windows, I included it to help prevent future regressions.

[NORMAL_fixes.zip](https://github.com/user-attachments/files/16169293/NORMAL_fixes.zip)

**Comment by parricc** [comment]
The game zip was last modified on 2023-11-09. I assume eXo does not want to change the main zip at this time. In either case, a Linux update zip is required.

Please ensure the Linux update zip only includes the `run_lin.bat` file.

**Comment by exoscoriae** [comment]
created update file
