### ISSUE TITLE
MechWarrior 2 (Limited Edition) (1996)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5275]
Please replace the run.bat file with the one in the attached zip archive. This fixes a Linux mounting issue without needing a separate file.
[MechW2_fix.zip](https://github.com/user-attachments/files/16169956/MechW2_fix.zip)

**Comment by exoscoriae** [comment]
created linux update file

**Comment by parricc** [comment]
The main zip has not been updated since 2023-08-10 so modifying it would have caused people to download a new file.

However, Linux update files need filenames that distinctly associate to the Linux patch. Please rename the bat file in the update zip to `run_lin.bat`

**Comment by exoscoriae** [comment]
done
