### ISSUE TITLE
Cryptic Passage for Blood (1997)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5276]
Please replace the run.bat files with the ones in the attached zip archive. This fixes a Linux mounting issue without needing a separate file.
[CrypticP_fix.zip](https://github.com/user-attachments/files/16170470/CrypticP_fix.zip)

**Comment by Python-Exoproject** [comment]
What 3DFX option? Only the main Blood archive has the 3DFX user choice, we didnt provide the 3DFX choice for the separate instance of Cryptic Passage

**Comment by parricc** [comment]
@Python-Exoproject Agh. I posted that right before going to bed and was remembering wrong. But either way, like Blood, you are making changes to move this to Staging, correct? If so, we should roll out the mount changes along with those.

**Comment by Python-Exoproject** [comment]
Not moving it at the moment, just moving games that need it so for now my mini project is 3DFX games and this isnt one of those. If you have the run.bat from 18 June 24 then you are working on the latest one.

**Comment by parricc** [comment]
Gotcha. In that case, we should go ahead and merge the change in the zip I've attached.

**Comment by exoscoriae** [comment]
changes will be in an update file that affects the linux pack only.

I don't see anything above that explains sufficiently why this change should be pushed to the main pack.

**Comment by parricc** [comment]
@exoscoriae This zip file has already been updated since version 6.02 (last change 2024-06-20), so merging this fix will have no effect on anyone's download. But if you insist we push this change in a Linux update file, it needs to be implemented in a different way.

Here's my reasoning:
- **Under no circumstance should any Linux update file contain a filename that's the same as one in a regular game zip.** Anything in a Linux update file needs to have a different filename.
- As there will not be a separate Linux branch for regular updates that people download between roll-up torrents, regular updates will need to include some Linux files, such as `*._linux.conf` file or `run_lin.bat` file changes. As such, **regular updates must take priority (overwrite) anything with the same filename as one in a Linux update file**.
- We should avoid maintaining two sets of files when possible. This eliminates the risk of regressions and broken substitutions.

**Comment by exoscoriae** [comment]
repacked the game with the changed files and deleted the update file
