### ISSUE TITLE
Player Manager 2 (1995)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5277]
Please replace the run.bat file with the one in the attached zip archive. This fixes a Linux mounting issue without needing a separate file.
[PlayerMa_fix.zip](https://github.com/user-attachments/files/16170718/PlayerMa_fix.zip)

**Comment by exoscoriae** [comment]
created update file

**Comment by parricc** [comment]
Also notable - This zip was last modified 2024-06-19, so merging it into the main zip would not affect how many people download a new zip in the next release. But we either need to merge the change into the main zip, or rename the modified file in the update to `run_lin.bat`. Whichever way you decide to go, let me know so that I can adjust the Linux conf file accordingly.

**Comment by exoscoriae** [comment]
replaed run.bat in player manager 2. deleted update file
