### ISSUE TITLE
Hard Nova (1990)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5282]
Please add the run_lin.bat file from the attached zip to the game archive so that it works correctly in Linux.
[hardnova_Linux_fix.zip](https://github.com/user-attachments/files/16183787/hardnova_Linux_fix.zip)

**Comment by exoscoriae** [comment]
added

**Comment by parricc** [comment]
The `run.bat` file has been altered since the patch file was created. Please update the Linux update file with the `run_lin.bat` file in the attached zip.
[hardnova_Linux_fix.zip](https://github.com/user-attachments/files/16568339/hardnova_Linux_fix.zip)

**Comment by exoscoriae** [comment]
updated
