### ISSUE TITLE
Lemmings 3 - All New World of Lemmings (1994)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5283]
Please add the `run_lin.bat` file from the attached zip to the game archive so that it works correctly in Linux. I have also included a replacement `run.bat` file with case corrections to help avoid future issues.
[lemm3_fix.zip](https://github.com/user-attachments/files/16183888/lemm3_fix.zip)

**Comment by exoscoriae** [comment]
added to main file.
