### ISSUE TITLE
Complete Great Naval Battles, The - The Final Fury (1996)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5291]
Please add the `run_lin.bat` file from the attached zip to the game archive so that it works correctly in Linux. I have also included a replacement `run.bat` file with case corrections to help avoid future issues.
[gnb5dd_fix.zip](https://github.com/user-attachments/files/16197148/gnb5dd_fix.zip)

**Comment by Python-Exoproject** [comment]
I dont think the run.bat file with case corrections went in?

**Comment by exoscoriae** [comment]
it's in the update file. I am not updating the actual games with linux changes.

look in E:\eXoDOS_WIP\eXo\Update\!dos
