### ISSUE TITLE
Beneath a Steel Sky (1994) Roland MT-32 music with SB Speech patch

### ISSUE THREAD

**Issue by interloper98** [exoscoriae/eXoDOS#5297]
[carlostex](https://www.vogons.org/memberlist.php?mode=viewprofile&u=19686) mentioned the game's audio selection _"is either Roland music with no speech or Sound Blaster speech with Adlib music"_, after which [ripsaw8080](https://www.vogons.org/memberlist.php?mode=viewprofile&u=8284) provided a fix allowing simultaneous MT-32 + SB voice dialog. :rocket: :partying_face: 
 
ripsaw's post + TSR: https://www.vogons.org/viewtopic.php?p=1276241#p1276241

**Comment by exoscoriae** [comment]
patched, and notes were changed
