### ISSUE TITLE
Turbo Champions (1989)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5300]
User @rotatorkuf found that game hasn't any sound.

I checked the issue and found that it's not totally right. Game _has_ PC Speaker here and there (easiest way to check it is to witness the crash), but sounds is abrupt and random.

I tried to rise the question at TDC, but ripsaw and Trixter are sure it's broken by default. I disagree, but as I cannot extract this sound by any means, I give up. Oh, I logged the issue at Staging github too, but I don't expect much progress.

Still, game _can_ be enhanced as is.

1. It features quite decent engine sound for Tandy (all other sound still goes as standard PC Speaker - i.e. semi-non-existant). So use Tandy for the sound, please. 
2. It features composite CGA. Maybe worth to be implemented in loader?

**Comment by Python-Exoproject** [comment]
PC Speaker is def weird in this one and is so in all forks of DOSBox. We know that even yet there are issues in PC Speaker emulation as evidenced by a few other games like Starflight and the wrong sound of the wormholes\exiting spacedock. Staging have a ticket open waiting for someone to have a crack at writing a definitive emulation and ive added this game as a possible inclusion for the test cases.

In the meantime as Spectre said, Tandy sound is much improved for this game and as the Tandy graphics are the same we can just set tandy=on in the tandy sound section of the conf for now.

**Comment by exoscoriae** [comment]
tandy audio enabled
