### ISSUE TITLE
DOOM - eXoWAD (2021)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5303]
In `gzrun.bat`:

```
:COMM
cls
echo.
echo               -=[Bonus WADs]=-
echo.
echo Press A for Stauf's Mansion (11th Guest Bonus)
echo Press B for The Atari Corporate Offices
echo Press C for The National Videogame Museum
echo Press D for GZ PT (Recreation of the infamous P.T. demo)
echo Press E for One Humanity (Released to support Ukraine)
echo Press F for ACE Engine Demo
rem echo Press G for 
rem echo Press H for 
rem echo Press I for 
rem echo Press J for 
rem echo Press P for the Next Page
echo Press R to Return to the Main Menu
echo.
echo These are WADs that were included on official game discs as
echo bonuses or extras.
echo.
choice /C:ABCDEFGHIJNR /N

if errorlevel = 7 goto MAIN
rem if errorlevel = 16 goto TOP2
rem if errorlevel = 10 goto WAD10
rem if errorlevel = 9 goto WAD9
rem if errorlevel = 8 goto WAD8
rem if errorlevel = 7 goto WAD7
if errorlevel = 6 goto aceengine
if errorlevel = 5 goto onehumanity
if errorlevel = 4 goto GZPT
if errorlevel = 3 goto NVGM
if errorlevel = 2 goto ATARI
if errorlevel = 1 goto STAUF
```

For this menu option, the `choice /C:ABCDEFGHIJNR /N` line should be `choice /C:ABCDEFR /N`
Otherwise, the `R` option will be associated with `errorlevel = 12`.

Edit: Grabbing this ticket back. Case corrections and explicit paths will need to be added to the `gzrun.bat` file to allow for easy maintainability for the Linux patch. I will also analyze the `run.bat` file to ensure the above error is not present in it as well. After everything has been fully investigated, corrected, tested, and uploaded, I will assign this back to eXo.

**Comment by parricc** [comment]
Pretty much every game has some incorrect case situations. I'm also catching some situations with other typos too, though.

E.g.: H2H XMAS being assigned the title Fistful of Doom, and Fistful of Doom using `FISTIX.WAD` instead of `FISTFIX.WAD`.

In addition to making changes to the `run.bat` and `gzrun.bat` files, I am also updating GZDoom to 4.12.2.

This will take a few days to make and verify the corrections as it means I'll be briefly opening every single option to test that it loads correctly.

**Comment by parricc** [comment]
I have finished going through the files. All typos should be fixed now. GZDoom is now 4.12.2. In addition, I have added the GZDoom compatible version of ZanZan TC (leaving the original files unaltered) and pointed the gzrun.bat file to it so that it plays as originally intended.

This has been uploaded to my personal folder in the eXoDropBox: `DOOM - eXoWAD (2021).zip` as it is 576.2 MiB.

**Comment by parricc** [comment]
Note that I still need to thoroughly test everything. I will assign this ticket back to eXo after I finish doing that.

**Comment by parricc** [comment]
GZDoom 4.12.2 had some issues (some WADs showed a black screen until pressing escape). It's been rolled back to 4.11.3, which works as expected on both Windows and Linux. The zip in my personal folder on the DropBox has been updated with these changes.

**Comment by parricc** [comment]
Added a few more game fixes. Outside of bat typos, the following have been fixed:

- Aliens TC - GZDoom fix implemented (original files unaltered) - `.\100\ALIENTC\ALIENSTC.pk3` and `.\100\ALIENTC\PSXMUSIC.WAD`
- Batman DOOM - GZDoom fix implemented (original files unaltered) - `.\100\batman\BDP+07.pk3`
- Doom Resurrection - GZDoom fix implemented (original files unaltered) - `.\100\doomresg.wad`
- ZanZan TC - GZDoom fix implemented (original files unaltered) - `.\100\zanpack\zanzan_g.pk3`

All games except for Doom Resurrection had sprite issues in GZDoom, which the above fixes. Doom Resurrection had a packaging issue that prevented it from working on anything other than an old version of ZDOOM. Luckily, it was a simple error that was easy to patch.

**Comment by parricc** [comment]
At this point, I have tested all levels and implemented all fixes where I saw problems. The GZDoom version is now 4.11.3. We will also need the same version of GZDoom in Sigil and Sigil2.

Here are the files to fix the Linux version:
[eXoWAD_Linux_fix.zip](https://github.com/user-attachments/files/16328054/eXoWAD_Linux_fix.zip)

Note that the Linux files will not work without the modified main game zip that I have put in my folder in the eXoDropBox.

**Comment by parricc** [comment]
@exoscoriae I have finished my fixes and validations. Please replace the main zip with the one in my eXoDropBox, and then create a Linux update zip for the game directory with the files in [eXoWAD_Linux_fix.zip](https://github.com/user-attachments/files/16328054/eXoWAD_Linux_fix.zip).

**Comment by exoscoriae** [comment]
your first post is not correct. I tested it, and the "press r to return": works perfectly fine in gzrun.bat

I will make different commetns for different posts, as there is a lot to unpack here

**Comment by exoscoriae** [comment]
ok... just going to trust you on this. changes pushed

**Comment by parricc** [comment]
A Linux update file for this still needs to be created.
https://github.com/user-attachments/files/16328054/eXoWAD_Linux_fix.zip

**Comment by exoscoriae** [comment]
done
