### ISSUE TITLE
Sigil (2019)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5304]
Please add the `gzrun.bsh` file from the attached Sigil_Linux_fix.zip file to the game archive so that it works correctly in Linux.

[Sigil_Linux_fix.zip](https://github.com/user-attachments/files/16328638/Sigil_Linux_fix.zip)

Also , an unrelated note: the GZDoom version (4.11.3) cannot be changed without breaking the Linux patch. Any updates need to be coordinated so that a corresponding Linux update can be pushed simultaneously.

**Comment by exoscoriae** [comment]
created update file
