### ISSUE TITLE
Space Strike (1982)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5307]
Here is a copy of the original PC Booter disk that we can replace the current com file with and use the boot command to launch. The com file mentions being cracked but I was able to start and play a bit without issue. Might imply that this image is also cracked and not original but not sure how to tell

[disk1.zip](https://github.com/user-attachments/files/16350315/disk1.zip)

Might be an idea for a future project to replace all the PC Booter com files with actual Booter images (and maybe keeping the com files around in a subfolder)?

**Comment by exoscoriae** [comment]
removed old files and added disk, then changed conf

adding pc booter images would be nice
