### ISSUE TITLE
Game fixes (pcspeaker=impulse) for Alt Launcher compatibility

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5308]
Here are the games that I know of that need pcspeaker=impulse in Staging to give the full benefit of the games sound.

As ive mentioned in a few places there are two methods used in various forks of dosbox for pc speaker emulation with vanilla dosbox using what staging have termed "discrete" and most other forks using a variant of what staging term "impulse". There is no one superior approach in any dosbox fork as yet and some games require "discrete" with other games requiring "impulse" (while still others dont work as they should via either implementation), though Staging have an open ticket to attempt creating a single approach that covers everything. 

Staging decided to provide both approaches so that users can change a conf setting depending on the games requirements instead of having to use multiple forks just for speaker emulation, and for a default Staging elected to use discrete. This means there are some games that require setting pcspeaker=impulse and therefore need converting to staging with staging confs for the alt launcher

Here are Staging confs for the 18 games I know of: [confs.zip](https://github.com/user-attachments/files/16351479/confs.zip), please use these and convert the games to Staging.

Here is the list of the games:

Commander Keen 1 - Marooned on Mars (1990)
Commander Keen 2 - The Earth Explodes (1990)
Commander Keen 3 - Keen Must Die! (1990)
Cosmo's Cosmic Adventure - Forbidden Planet (1992)
Dark Side (1988)
Duke Nukem - Episode 1 - Shrapnel City (1991)
Duke Nukem - Episode 2 - Mission - Moonbase (1991)
Duke Nukem - Episode 3 - Trapped in the Future (1991)
Gauntlet II (1989)
Kristal, The (1989)
Paganitzu (1991)
Pornmania (1994)
SnakeWinder (1990)
Space Station Oblivion (1988)
Speedball (1988)
Toppler (1990)
Total Eclipse (1988)
TV Sports - Football (1989)

**Comment by exoscoriae** [comment]
extratced all the files required and converted them to staging
