### ISSUE TITLE
M1 Tank Platoon (1989)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5310]
The autotype command in `dosbox_tandy.conf` is incorrect, causing the game to get stuck on a "one moment please...." screen.

The autotype line should be `autotype -w .2 3 5 2 N`
See the attached file for the fix: [m1tank_fixed_dosbox_tandy.conf.zip](https://github.com/user-attachments/files/16356268/m1tank_fixed_dosbox_tandy.conf.zip)

Also, in `eXo\util\dosbox.txt`, please take out the extra `\`. It caused a parsing error in the Linux converter.

**Comment by Python-Exoproject** [comment]
Theres more than that going on, but ive covered it all in #5045 so im closing this one
