### ISSUE TITLE
Command and Conquer (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5312]
Discord user Flay has noted that when you start the game the correct CDs are mounted. If you then exit you are given the user choice menu to pick your campaign again, however this time when the game starts the correct CDs are not mounted if you picked a different option.

This is because you would need to dismount the previous images so that d: is available again before mounting the new images. I dont think its worth the hassle and we should just do what we do for most other games (including red alert) and change all the relevant `goto menu` in run.bat to `goto quit`

**Comment by exoscoriae** [comment]
done.
