### ISSUE TITLE
Descent (1995) and Descent Anniversary Edition (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5313]
Discord user flunkhaus noted performance issues on his system and traced it to core=normal. As discussed in the discord post, I believe the use of core=normal is due to the situation with dosbox back in 2005 and no longer relevant as far as my testing shows.

If you agree, please change core=normal to core=auto for both these games

**Comment by exoscoriae** [comment]
done
