### ISSUE TITLE
Wonderland (1990)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5314]
No music plays when choosing Roland MT-32.

**Comment by SmilingSpectre** [comment]
Not confirmed. Works for me.

**Comment by parricc** [comment]
Just resynced and tested again in Windows. While I get music when selecting MT-32 in Windows, there is still no music for the MT-32 option in Linux. Knowing how Linux is picky, I've determined Windows is actually playing the music using its Microsoft GS Wavetable synth. Digging into this more, I found that adding a config line to the `run.bat` file results in the music playing correctly:

```
:epi2
CONFIG -set "mididevice=mt32"
cd wland
cls
game -disp p -roland
goto menu
```

Also note, after doing this, the sound is dramatically different in Windows as well.

**Comment by parricc** [comment]
The corrected `run.bat` file is in the attached zip:
[wland_fix.zip](https://github.com/user-attachments/files/16372073/wland_fix.zip)

**Comment by SmilingSpectre** [comment]
I wonder, how many more games in Windows plays standard midi instead mt32...

**Comment by Python-Exoproject** [comment]
Single greatest benefit of the linux patch in my mind is finding all these, Windows works because of the GS wavetable fallback so its easy to overlook these on a windows environment

**Comment by exoscoriae** [comment]
nice find @parricc
