### ISSUE TITLE
Blue Force (1993) - nonexistent mountpoint

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5315]
The following mount location is in the `dosbox.conf` file, but does not exist:
`mount a .\eXoDOS\bforce\floppy -t floppy`

If this file is not needed, please either comment the line out or remove it to prevent noise during file consistency analysis.

**Comment by exoscoriae** [comment]
these really aren't worth bug reports. they don't hurt anything, and I am frankly too busy with other projects to do vanity cleanup.

**Comment by parricc** [comment]
It is not obvious looking at the conf file whether or not the game needs something from a floppy disk. Launching a game does not necessarily make it obvious either.

But your response confirms it's not needed. If you'd like, I can include removing that line with the bulk case corrections I'm planning to push to you.
