### ISSUE TITLE
Updated Staging confs

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5316]
I found a few games that were on Staging that didnt have Staging conf files so I provide those here. While I was at it I updated all the conf files that were for Staging 80.1 to ones for Staging 81.1 (a few small variations in the template) so that all games are using a release 81 based conf.

Other minor tweaks:

Some of the real magic games were using cycles=max so I gave them a value if you want to look them over. 

The real magic version of lord of the rings vol 1 ive left alone for now but highlight that the normal version is using cycles=10000 (which might be a bit high) while the real magic version is on auto (which might be a bit low).

Ive also tweaked the cd volume for the real magic version of The Horde.

All the above are already on Staging so no need to change anything there with one exception: 

Since I was adding the cdaudio volume setting to the real magic version of The Horde I looked into the normal version as well. It was on vanilla dosbox with max cycles so Ive also included a Staging conf for it with the required settings. Please use this conf and switch the game to Staging in dosbox.txt

[confs.zip](https://github.com/user-attachments/files/16397914/confs.zip)

**Comment by exoscoriae** [comment]
thank you very much for doing all of this
