### ISSUE TITLE
Cruise for a Corpse (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5320]
Two things for this one:

~~1. Ive noticed a bug that might be worth a user note. If you click on the first title screen that eventually shows "Delphine Software" it skips the sequence and the intro starts. During and after the intro you have sound. If you let the first title screen play out then when the intro starts you have no sound here or in the game.~~

2. John Novak has noted that while the game play is ok at the current 3k cycles most of the cutscenes (like the blurry ive been knocked on the head wakeup scene at the start of the game) are to slow. Using the Amiga version as reference he has suggested 8k is closer.

@johnnovak Is point 1 worth a bug report on your github? If so ill create one but if it doesnt sound like emulation issue I wont bother.

Edit: Solved point one with a pointer from Staging team. Please switch game to Staging and use this conf which includes cycles 7k to handle point 2: [dosbox.zip](https://github.com/user-attachments/files/16404168/dosbox.zip)

**Comment by johnnovak** [comment]
> @johnnovak Is point 1 worth a bug report on your github? If so ill create one but if it doesnt sound like emulation issue I wont bother.

It sounds like a game issue to me, but you can never be sure. Probably a good idea to raise a ticket for it because degrades the experience, but we'll need to cross-check in other emulators and/or on hardware to be 100% sure.



> 2\. John Novak has noted that while the game play is ok at the current 3k cycles most of the cutscenes (like the blurry ive been knocked on the head wakeup scene at the start of the game) are to slow. Using the Amiga version as reference he has suggested 8k is closer.

Yeah, that's a funny one. Some Amiga ports are too fast on 3000 cycles, some need 7-8k or more to get the same effecgive speed as on the 7.14 MHz Amiga 500. But, different CPU architecture, different code, different porting teams, so every game needs to be adjusted individually, it kinda makes sense to me.

**Comment by Python-Exoproject** [comment]
@johnnovak Ticket created. I checked against other forks and it seems to be an emulation issue as X and Daum work fine whereas all other forks share Stagings issue

**Comment by interloper98** [comment]
Thanks for the heads up @Python-Exoproject. Will poke around.

**Comment by johnnovak** [comment]
> @johnnovak Ticket created. I checked against other forks and it seems to be an emulation issue as X and Daum work fine whereas all other forks share Stagings issue

Thank you. That's valuable info.

**Comment by exoscoriae** [comment]
added fix.
