### ISSUE TITLE
PowerMonger (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5323]
Note from John Novak:

The launch options mention "Low Res 256 colour" and "High Res 16 colour" options. This is not quite correct as the game only uses the 320x200 VGA mode. The 16-colour option uses the original Amiga in-game graphics and more or less the original Amiga intro, the 256-colour option features a different intro sequence and enhanced 256-colour in-game graphics.

**Comment by exoscoriae** [comment]
changed wording

**Comment by Python-Exoproject** [comment]
Typo in run.bat:

`Amiga graphgics`
