### ISSUE TITLE
Flashback - The Quest for Identity (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5324]
We had noticed a speed issue during the intro of the floppy version a while ago and tried increasing cycles to handle it. It didnt really help though.

John Novak has noted that its an ECE issue and that switching to Staging fixes it.

Here is a Staging conf: [dosbox.zip](https://github.com/user-attachments/files/16392728/dosbox.zip)

**Comment by exoscoriae** [comment]
moved to staging
