### ISSUE TITLE
Magnetic Scrolls games

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5325]
John Novak noted that on his system the high res options for the magnetic scrolls games were not working via the current 0.74 dosbox. Switching to Staging should fix it. Cycles have also been increased to improve graphics load times and scrolling windows in Magnetic Scrolls collection, play is not affected as the games are not real time.

Ive also included in the below zip a default layout file for the Magnetic Scrolls collection like we did for Wonderland

Here are Staging confs for the games: [eXoDOS.zip](https://github.com/user-attachments/files/16393507/eXoDOS.zip)

Specifically the games to switch to Staging in dosbox.txt are:

Corruption (1988)
Fish (1988)
Guild of Thieves (1987)
Jinxter (1988)
Magnetic Scrolls Collection, The (1991)
Myth (1989)
Pawn, The (1986)

**Comment by exoscoriae** [comment]
moved the above to staging and added files
