### ISSUE TITLE
Shanghai II - Dragon's Eye (1990)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5326]
User @Deadeye found that our version is missing two sets of tiles.

I got confirmed img from TDC, and indeed, there are two more .SET files. And two others are different. And Fame file is empty, unlike ours.

I uploaded all different files, plus images itself, to the github.

Shanghai II - Dragon's Eye (1990).zip

**Comment by exoscoriae** [comment]
added missing files and images. thank you
