### ISSUE TITLE
Constructor (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5327]
This game sets mouse sensitivity which was moved in Staging from the [sdl] section to the [mouse] section.

Please switch to Staging and use this conf: [dosbox.zip](https://github.com/user-attachments/files/16404247/dosbox.zip)

Cycles were previously set to max so ive reduced this to 40k and it seems ok, but as a 1997 game feel free to change

**Comment by exoscoriae** [comment]
switched to staging and added conf.
