### ISSUE TITLE
MS-DOS.xml Corrections

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5333]
I have prepared substitutions to fix case problems in the MS-DOS.xml files.

These will be put in their appropriate locations within a zip file to be pushed out by eXo:

```
Data\Platforms\MS-DOS.xml
xml\all\MS-DOS.xml
xml\family\MS-DOS.xml
```

However, there are a couple additional non-case substitutions that I would like to get approval to push along with the above:

https://github.com/exoscoriae/eXoDOS/issues/4711 - changing txt entry to pdf
https://github.com/exoscoriae/eXoDOS/issues/5207 - changing txt entry to pdf
https://github.com/exoscoriae/eXoDOS/issues/5332 - correcting launch file path
https://github.com/exoscoriae/eXoDOS/issues/5208 - changing TXT entry to pdf

Please confirm how this situation should be handled:
https://github.com/exoscoriae/eXoDOS/issues/4284 - Changing entry to `<ManualPath />`?

**Comment by parricc** [comment]
Additional non-case issues in `xml\family\MS-DOS.xml` but not the other files:

```
eXo\eXoDOS\!dos\jeopjun\Jeopardy! Junior Edition (1989).bat
eXo\eXoDOS\!dos\wwcse\Where in the World is Carmen Sandiego Enhanced (1989).bat
eXo\eXoDOS\!dos\wwcscd\Where in the World is Carmen Sandiego CD (1995).bat
Manuals\MS-DOS\Where in the World is Carmen Sandiego Enhanced (1989).pdf
Manuals\MS-DOS\Asylum (1991).pdf
Manuals\MS-DOS\Where in the World is Carmen Sandiego CD (1995).pdf
```

**Comment by parricc** [comment]
[MS-DOS_xml.zip](https://github.com/user-attachments/files/16464371/MS-DOS_xml.zip)

This contains the changes from the first post. Only `Data\Platforms\MS-DOS.xml` since the other files are outdated.
**Make sure to review and approve the non-case changes before merging this.**

Case insensitive diff:
< Pre-change version from WIP (as of 2024-08-01 21:22 CDT)
> Edited version in attached zip
```
275790c275790
<     <ManualPath>Manuals\MS-DOS\Waterloo (1989).txt</ManualPath>
---
>     <ManualPath>Manuals\MS-DOS\Waterloo (1989).pdf</ManualPath>
286148c286148
<     <ManualPath>Manuals\MS-DOS\Pro League Baseball (1992).pdf</ManualPath>
---
>     <ManualPath />
491060c491060
<     <ApplicationPath>eXo\eXoDOS\!dos\ACluSol\A Clue's Solution (1993).bat</ApplicationPath>
---
>     <ApplicationPath>eXo\eXoDOS\!dos\ACluSol\Clue's Solution, A (1993).bat</ApplicationPath>
608488c608488
<     <ManualPath>Manuals\MS-DOS\Crime Patrol (1994).TXT</ManualPath>
---
>     <ManualPath>Manuals\MS-DOS\Crime Patrol (1994).pdf</ManualPath>
672592c672592
<     <ManualPath>Manuals\MS-DOS\Cyclemania (1994).TXT</ManualPath>
---
>     <ManualPath>Manuals\MS-DOS\Cyclemania (1994).pdf</ManualPath>
```

**Comment by exoscoriae** [comment]
I can't push this. too many things have changed. You have to realize I edit this file every single day...

**Comment by exoscoriae** [comment]
I tried running a compare on the files, and they are so absolutely different that it basically showed every single line was changed
for example, your file's first game is Cyber Marine and mine is TMNT II The Arcade Game. 

I let notepad run a compare on them for over 20 minutes, just for it to come back and tell me every single line is different due to the different order of games

**Comment by parricc** [comment]
Wasn't sure how often you edit it. Were the mentioned changes acceptable? If so, we'll need to coordinate a time that I can resync with your current file, push the substitutions, verify, and then send to you again to reverify on your end and push.

**Comment by parricc** [comment]
@exoscoriae An up to date MS-DOS.xml file needs to be uploaded to WIP for me to process the substitutions. We had planned on you pushing the up to date file EOD today, but WIP is still showing an old timestamp. If it's too late for tonight, can you push one EOD tomorrow (Friday)?

**Comment by parricc** [comment]
I've attached the case corrections applied to the MS-DOS.xml file as it existed at `2024-07-31 14:55`:
[MS-DOS.zip](https://github.com/user-attachments/files/16562452/MS-DOS.zip)

**Comment by exoscoriae** [comment]
applied
