### ISSUE TITLE
Setup eXoDOS.bat - duplicate label problem

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5334]
`Setup eXoDOS.bat` contains two labels with the same name, `verified`, which causes the converted Linux script to get stuck in an endless loop.

While Windows reads batch files sequentially, the Linux conversion works through a frame stack. As such, there is no systematic way that duplicate labels can be handled in Linux. There is also no way to correct this issue through substitution commands during the conversion process. Labels need to be unique throughout a file to prevent issues. I believe this is the only incident such a situation has occurred.

The first label instance is for the process of verification, so it makes sense to refer to it as verify. There is only one goto reference to skip ahead to it.

Case insensitive diff of change proposed:

`<` unaltered file on WIP (as of the night of 2024-08-01)
`>` file in attached zip that makes the labels unique
```
269c269
< goto verified
---
> goto verify
301c301
< :verified
---
> :verify
```

I have attached the modified file to this ticket:
[Setup eXoDOS.zip](https://github.com/user-attachments/files/16465326/Setup.eXoDOS.zip)

**Comment by exoscoriae** [comment]
seems you chnaged quite a bit of other things as well

**Comment by exoscoriae** [comment]
all case though, so I'll push it
