### ISSUE TITLE
Beneath a Steel Sky (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5336]
I noticed youve added the recent mod to enable SB speech with MT32 music which is great, although I would like to suggest that instead of replacing the MT32 option with the mod we offer both as a user choice. My reasoning is that while the MT32 + SB mod adds speech (and allows the intro to play as a result) it also replaces the CM32 extended sounds with the SB equivalents. While I personally would rather an intro and speech I feel we shouldnt take away the choice to hear the game as it was originally with MT32 and CM32 effects.

If you agree, ive mocked up a run.bat to encompass the change though I didnt add to the user note (if feel needed to explain why MT32 is still an option): [run.zip](https://github.com/user-attachments/files/16471109/run.zip)

I also highly recommend adding to the conf under [sblaster] `sbtype=sbpro2` as this balances the opl and speech\fx much better in the SB option. Turns out this is actually the solution to most of our volume balance problems we encounter so ill try this for each of these going forward first and maybe go back over the games with mixer settings again in the (far) future to try this better solution. There is also a subtle hum in the SB option on Staging which can be removed by adding a conf setting.

Here is a Staging conf with the above implemented for switching to Staging: [dosbox.zip](https://github.com/user-attachments/files/16487842/dosbox.zip)

**Comment by exoscoriae** [comment]
implemented changes

**Comment by Python-Exoproject** [comment]
Double slash added to dosbox.txt when changed to Staging

**Comment by exoscoriae** [comment]
thank you
