### ISSUE TITLE
Pool Shark (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5339]
Discord user Cryptkeeper has reported:

"Pool Shark has two games installed in the game folder, Archer Maclean's Pool (the alternate title version called Archer Maclean's Pool Shark), and then there is a folder called "POOL" which contains the correct Pool Shark game. The correct Pool Shark is also an older version as I saw one available on the net as high as v2.3, although it is still unregistered shareware like the older version in eXoDOS."

I have confirmed the existence of the Archer Maclean game files in the root folder of the Pool Shark zip mixed in with some Pool Shark install files.

Heres a copy of the v2.3 discussed: [POOLSHARK.ZIP](https://github.com/user-attachments/files/16487868/POOLSHARK.ZIP)

**Comment by exoscoriae** [comment]
done
