### ISSUE TITLE
Chessmaster 2000, The (1986)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5342]
- [ ] As user @sheikhbenredicfyfazan found, game is in CGA, so don't display all CGA palletes in the current settings. "machine=cga" will fix it.

I noticed also that it uses Composite in color and B/W modes, so worth to use DOSBox with supports it.

- [ ] Also, game is missing "100 classical games" library. TDC has good version which I uploaded into "bugs" folder.

Chessmaster 2000, The (1986)(Software Toolworks, Inc., The) [Strategy, Chess].zip

**Comment by exoscoriae** [comment]
processed
