### ISSUE TITLE
Neverwinter Nights (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#5343]
found on mocagh

- [x] America Online instructions
- [ ] America Online getting started
- [ ] America Online advert
- [ ] America Online manual
- [x] America Online members info
- [ ] America Online flyer

two of the docs are for Win3x only but most is for DOS too and it was all included in the DOS floppy version package (as you can see on the cover scans on mocagh) so I would suggest to add them all.

**Comment by exoscoriae** [comment]
I added 2 of the documents, that were related to the game. The rest is generic to AOL, which isn't even DOS compatible as it was a windows program.
