### ISSUE TITLE
Where in America's Past is Carmen Sandiego (1991) Extras and manual

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5347]
It seems Where in America's Past is Carmen Sandiego is missing basically everything extra. :) Uploaded:

- [ ] Where in America's Past Is Carmen Sandiego (1991) - Addendum Card.jpg
- [ ] Where in America's Past Is Carmen Sandiego (1991) - Poster.jpg
- [ ] Where in America's Past Is Carmen Sandiego (1991) - Criminals Cards.pdf
- [ ] Where in America's Past Is Carmen Sandiego (1991) - Postcards.pdf
- [ ] Where in America's Past Is Carmen Sandiego (1991) - What Happened When.pdf

Also, I found and uploaded the better version of the User's Guide.

- [ ] Where in America's Past Is Carmen Sandiego (1991) - User's Guide.pdf

**Comment by exoscoriae** [comment]
replaced and added
