### ISSUE TITLE
Where in Europe is Carmen Sandiego (1988) Atlas

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5348]
Where in Europe is Carmen Sandiego (1988) is missing atlas which used for copy-protection. I found it on Archive, and while it's slightly damaged (about centimeter at the binder isn't scanned which makes all two-pages maps incomplete), it will do for the game.

- [ ] Where in Europe is Carmen Sandiego (1988) - Rand McNally - Concise Atlas of Europe.pdf

**Comment by exoscoriae** [comment]
added and replaced manual
