### ISSUE TITLE
Where in Space is Carmen Sandiego (1993) Manual and extra

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5349]
Game was supplied with  Peterson First Guide to Astronomy, so I uploaded it.

- [ ] Where in Space is Carmen Sandiego (1993) - Peterson First Guides - Astronomy.pdf

I also found the manual with much better resolution.

- [ ] Where in Space is Carmen Sandiego (1993).pdf

**Comment by exoscoriae** [comment]
replaced manual. added extra
