### ISSUE TITLE
Where in the USA is Carmen Sandiego (1986) manual and extras

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5351]
This game has installation guide (named "Operational instructions" as a manual.

And the real manual (named "User's manual) doesn't present at all.

Also, Instructions was scanned on too small scanner, so is divided by stripes and badly glued, so I replaced them.

- [ ] Where in the USA is Carmen Sandiego (1986) - Operating Instructions.pdf
- [ ] Where in the USA is Carmen Sandiego (1986) - User's Manual.pdf

**Comment by exoscoriae** [comment]
we already have this exact manual in the project.

replaced map
