### ISSUE TITLE
Where in the World is Carmen Sandiego  - Soundtracks

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5352]
It seems, the band who made the music for Carmen Sandiego released two albums tied to the "Where in the World is Carmen Sandiego".  First is simply named "Where in the World is Carmen Sandiego", whereas the second is subtitled "Out of This World". I uploaded both, with accompanied booklets.

Seems, eXoDOS is missing "soundtrack" tag, so I added it to "Extras" - but uploaded into "Soundtracks" section.

- [ ] Where in the World is Carmen Sandiego - Out of This World (1993).zip
- [ ] Where in the World is Carmen Sandiego - Soundtrack (1992).zip

**Comment by exoscoriae** [comment]
added
