### ISSUE TITLE
util\dosbox.txt Case Inconsistencies

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5353]
Please fix these 4 case inconsistencies in the `util\dosbox.txt` file:

`Atlantis - The lost Tales (1997)` should be `Atlantis - The Lost Tales (1997)`
`Bluntman and Chronic P.C. version (2003)` should be `Bluntman and Chronic P.C. Version (2003)`
`McGee at the Fun fair (1991)` should be `McGee at the Fun Fair (1991)`
`Pure-stat College Basketball (1987)` should be `Pure-Stat College Basketball (1987)`

The above references are correct in all other files.

**Comment by exoscoriae** [comment]
done
