### ISSUE TITLE
.\eXo\Update\update.bat label needs to be outside of if condition

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5354]
In `.\eXo\Update\update.bat`, the mpskip label needs to be moved outside of an if condition.

```
:mpskip
@del MediaPack.txt
SETLOCAL DISABLEDELAYEDEXPANSION
)
```

Needs to be changed to:

```
)
:mpskip
@del MediaPack.txt
SETLOCAL DISABLEDELAYEDEXPANSION
```

Why: Putting a label within an if condition or a loop causes conversion and parsing problems in Linux because goto commands in Linux work through the use of a frame stack.

Risk: None other than possibly a "MediaPack.txt does not exist" error message which could be silenced by checking for the file's existence. In this particular situation, the ending parenthesis corresponds to the `if exist ..\..\Content\MediaPack.ver (` line at the beginning of the script. If the MediaPack.ver file is not present, there is no risk in attempting to delete `MediaPack.txt` or disabling delayed expansion (which would have already been disabled at the beginning of the script).

**Comment by exoscoriae** [comment]
approved change
