### ISSUE TITLE
Alone in the Dark (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5357]
John Novak noted that the floppy launch option for this game has Sound Blaster Pro options in the game setup but we were using normal Sound Blaster.

Turns out this is because when you use sb pro for the effects choice the game hangs (this happens in ECE and Saging).

I found however that if we set sbtype=sbpro2 and select in the game setup sound blaster pro for music and sound blaster DMA for effects we have success.

Here are the changed files: [eXoDOS.zip](https://github.com/user-attachments/files/16570123/eXoDOS.zip)

**Comment by exoscoriae** [comment]
fix applied
