### ISSUE TITLE
Freddy Pharkas Frontier Pharmacist (1993)

### ISSUE THREAD

**Issue by Eulisker** [exoscoriae/eXoDOS#5358]
Discord user Birdman reported there is no speech in Freddy Pharkas. SmilingSpectre found a wrong path in resource.cfg as the culprit.

The attached file has the correct resource.cfg and run.bat to fix this. 

e: removed. see 4 posts further down.

I also uploaded the .bin/.cue and the floppy version. The floppy has a few differences to the CD version and should be added as well.
https://freddypharkas.fandom.com/wiki/Freddy_Pharkas:_Frontier_Pharmacist_(floppy)#Differences_between_Floppy_and_CD

**Comment by Eulisker** [comment]
I see. This does negate whatever #2967 does. I'll see if i can get it to work.

**Comment by Eulisker** [comment]
Something else is wrong. Closing for now.

**Comment by Eulisker** [comment]
Found it. The path should just be c:\audio because of the way it is mounted in dosbox.

Here are the run.bat and resource.cfg
[Freddy Pharkas.zip](https://github.com/user-attachments/files/16578931/Freddy.Pharkas.zip)

The .bin/.cue and the floppy version should still be added.

**Comment by exoscoriae** [comment]
added your fixes. Thanks for doing that.

Also added floppy version, along with notes on the differences.
