### ISSUE TITLE
Prisoner of Ice (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#536]
has watermark replacementdocs
page missing between 1 - 4

**Comment by SmilingSpectre** [comment]
It's Windows manual.

DOS one uploaded.

**Comment by TimberlAndRE-de** [comment]
added to the github

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] manual (it's the booklet from the US version, current one is european (UK?) version)

added to the github folder

**Comment by exoscoriae** [comment]
replaced
