### ISSUE TITLE
MS-DOS Catalogs.xml / MS-DOS Magazines & Newsletters.xml issues

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5360]
The `MS-DOS Catalogs.xml` file has the following bad references:
`<ApplicationPath>eXo\Catalogs\Ocean Ride the Ocean Wave (1992).pdf</ApplicationPath>`
`<ApplicationPath>eXo\Catalogs\Microprose Just for Fun (1989).pdf</ApplicationPath>`

The actual files for the above contain an `!` character at the end of their title. This issue causes the above two catalogs to fail launching in both Windows and Linux.

The `MS-DOS Magazines & Newsletters.xml` has several references of the following with incorrect case:
`<ApplicationPath>eXo\Magazines\GameBytes.bat</ApplicationPath>`

The actual filename is `Gamebytes.bat`. This issue causes all Game Bytes entries to fail to launch in Linux.

**Comment by parricc** [comment]
Suggestion:

Since this torrent is already released and the media pack does not have a separate setup, add some lines to `eXoDOS Setup.bat` as a makeshift fix. This can be done right after the Media Pack files get extracted:

```
if exist .\Content\*Magazines.zip .\eXo\util\unzip -o .\Content\*Magazines.zip -d .\
if exist .\Content\*Books.zip .\eXo\util\unzip -o .\Content\*Books.zip -d .\
if exist .\Content\*Catalogs.zip .\eXo\util\unzip -o .\Content\*Catalogs.zip -d .\
if exist .\Content\*Soundtracks.zip .\eXo\util\unzip -o .\Content\*Soundtracks.zip -d .\
if exist ".\eXo\Catalogs\Ocean Ride the Ocean Wave! (1992).pdf" ren ".\eXo\Catalogs\Ocean Ride the Ocean Wave! (1992).pdf" "Ocean Ride the Ocean Wave (1992).pdf"
if exist ".\eXo\Catalogs\Microprose Just for Fun! (1989).pdf" ren ".\eXo\Catalogs\Microprose Just for Fun! (1989).pdf" "Microprose Just for Fun (1989).pdf"
if exist ".\eXo\Magazines\Gamebytes.bat" ren ".\eXo\Magazines\Gamebytes.bat" "GameBytes.bat"
```

**Comment by parricc** [comment]
Note the last 3 lines in the above snippet are what's added. Confirmed it works.

**Comment by exoscoriae** [comment]
added the lines

**Comment by parricc** [comment]
This should also be done under the `:mediainstall` label. (For people installing the Media Pack on a copy of eXoDOS that had previously been installed).

**Comment by exoscoriae** [comment]
thinking about it
it doesn't matter if the line are added

because the xml is still wrong in that release.

so renaming the files doesn't fix shit

**Comment by exoscoriae** [comment]
added em' anyways though
