### ISSUE TITLE
007 - Licence to Kill (1989) 

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5361]
Sunie reported that `007 - Licence to Kill (1989)` has several executables that open the game in different video modes, but that eXoDOS only opens it in EGA mode. He's requested to consider creating a menu to run this game in Hercules, CGA, Tandy and EGA graphics.

I haven't looked into this, but going to assign to Python as this might be up his alley.

**Comment by Python-Exoproject** [comment]
Here is a new set of conf files and a run.bat to enable all the options: [007.zip](https://github.com/user-attachments/files/16615086/007.zip). Please switch to staging as well for these to work properly

**Comment by Python-Exoproject** [comment]
Yeah, oops forgot to add that to the zip. Here it is: [exception.zip](https://github.com/user-attachments/files/16873853/exception.zip)

**Comment by exoscoriae** [comment]
done
