### ISSUE TITLE
James Bond 007 - The Stealth Affair (1990)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5363]
Sunie reported that the VGA options of `James Bond 007 - The Stealth Affair (1990)` perform better with the cycles in `dosbox.conf` set to 4000 instead of auto. Otherwise, it runs sluggish in comparison to the EGA version.

**Comment by Python-Exoproject** [comment]
I was concerned the higher cycles might undo the vmem delay setting which is used via dosbox staging to remove the games flicker but ive tested and the increase in cycles is safe.

While I agree the EGA version is running faster than the VGA in our setup, I cant say for certain if compared to real hardware the EGA version is running too fast or the VGA version is running too slow. The cycles have the potential to affect any reaction based puzzles in game. Your thoughts exo?

**Comment by exoscoriae** [comment]
well, this is supported by scummvm... so I think we can safely assume the scummvm version is running at an appropriate speed.

Having run the ScummVM version and comparing it to our setup, the speed of the VGA copy is closer to the speed of the scummvm version.

Bumping it to 4000 cycles makes bond walk a decent bit faster

I am not familiar with the games puzzles, but any timing based puzzle could be heavily affected by speediong things up. Similar to the firecracker in kq7.

I think this will be left alone.  However I do question why the vga copy in our set and the vga copy in scummvm have different graphics.
