### ISSUE TITLE
11th Hour, The (1995)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5365]
Sunie reported that the mouse movement feels too sluggish until about 40,000 cycles.

"This starts to get more apparent when you step into the house. If you crank up the cycles too much, the walking animations go too fast. There is a horse puzzle left of the stairs, when you click into that some other slowdown issues occur, which seemingly can't be fixed by cranking the cycles. With MT-32, the sound started to crackle and that didn't stop even after exiting the puzzle. With Sound Canvas and Sound Blaster, sound effects hitch when they play, which is annoying but not as bad as MT-32. "

**Comment by Python-Exoproject** [comment]
Yep 40k cycles does feel better speed wise.

In relation to the sound issue with MT32 that is present in both ECE and Staging. I also tested if changing the sound blaster driver used for fx when MT32 is selected would help but no luck there either.
