### ISSUE TITLE
bat and conf file case correction dump

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5367]
@exoscoriae We need to coordinate a time to resync so that I can push the bulk case corrections for all of the backend bat and conf files.

Let me know when you're ready, and we can plan a time. This week seems like a good one to get this out of the way.

Plan of action:
- eXo syncs all of his changes to WIP
- We enter a temporary code freeze
- Parricc resyncs, implements the case changes, verifies them against an unaltered sync with a recursive case insensitive diff, and then zips and uploads the bat and conf files to the eXoDropBox.
- eXo verifies the changes against his copy with another recursive case insensitive diff
- If the recursive case insensitive diff confirms nothing outside of case has been changed, eXo pushes the changes to WIP
- Code freeze ends

This entire process should take less than an hour, but let's find a time that works best for you.

**Comment by Python-Exoproject** [comment]
@exoscoriae Good to close?

**Comment by exoscoriae** [comment]
yep
