### ISSUE TITLE
Gabriel Knight 2 - The Beast Within (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5371]
Ive discovered that the game wont launch. The conf is pointing at run.bat but run.bat doesnt exist. It used to exist as it offered sound options but I think you may have removed it when you discovered during the ScummVM work that the sound didnt actually use midi and was pointless?

Either run.bat need to be re-created or the conf needs to be updated to point at the games exe and playlists verified according to the path you take

**Comment by exoscoriae** [comment]
good catch
