### ISSUE TITLE
Premier Manager (1992) - ods replacement for xls file

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5375]
The xls (BIFF8) format was deprecated by Microsoft with the release of Office 2007. We cannot trust that they'll continue to maintain compatibility over the long term. I've converted the spreadsheet to an ods file and also converted the image within it to a png file (instead of the proprietary emf format). This provided the maximum compatibility between all spreadsheet applications I tested (Excel, LibreOffice, Google Sheets, Gnumeric, CalligraSheets). This format is also easy to pick apart (if you decompress it, it's easy to read xml files and the png), which is ideal for preservation.

[Copy Protection Codes (XLS).ods](https://github.com/user-attachments/files/16820780/Copy.Protection.Codes.XLS.ods)

**Comment by exoscoriae** [comment]
replaced file
