### ISSUE TITLE
First Over Germany (1988) - xls to pdf

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5376]
The xls (BIFF8) format was deprecated by Microsoft with the release of Office 2007. We cannot trust that they'll continue to maintain compatibility over the long term. I've converted the spreadsheet to a PDF and added dotted lines between the cells to make it easier to see the rows. If you prefer without the dotted lines, it's easy to convert this one (simply make sure the margins are good and print as pdf).

[Copy Protection Grid.pdf](https://github.com/user-attachments/files/16821180/Copy.Protection.Grid.pdf)

**Comment by exoscoriae** [comment]
replaced
