### ISSUE TITLE
Psi-5 Trading Company (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#538]
has watermark theunderdogs.org
seems typed down from the original manual
it's for the wrong game version: C64/128 and Apple II

**Comment by SmilingSpectre** [comment]
No DOS manual found.

But found online combined manual. Web-archive uploaded.

**Comment by TimberlAndRE-de** [comment]
uploaded to the github folder
@exoscoriae it's a webpage, not sure if needed to be converted to pdf?

**Comment by exoscoriae** [comment]
i see nothing in the github folder

**Comment by TimberlAndRE-de** [comment]
uh oh someone must have deleted it ... or i forgot to upload it ;-)
uploaded to the github (now for real!)

**Comment by exoscoriae** [comment]
saved as pdf and replaced it. thanks
