### ISSUE TITLE
update_installed.bat changes for Linux patch

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5382]
I've gone ahead and designed a solution myself, which I've verified converts correctly. For the Linux patch, two changes will be necessary in the `eXo\Update\update_installed.bat` file.

Change this line:
`if exist .\eXoDOS\%index% .\util\unzip -o ".\Update\!dos\%FileName%" -d .\eXoDOS\`

To the following:

```
if exist .\eXoDOS\%index% (
.\util\unzip -o ".\Update\!dos\%FileName%" -d .\eXoDOS\
if exist ".\Update\!dos\linux\release\%FileName%" .\util\unzip -o ".\Update\!dos\linux\release\%FileName%" -d .\eXoDOS\
if exist ".\Update\!dos\linux\%FileName%" .\util\unzip -o ".\Update\!dos\linux\%FileName%" -d .\eXoDOS\
)
```

Change this line:
`if exist .\eXoDOS\!%lang%\%index% .\util\unzip -o ".\Update\!dos\!%lang%\%FileName%" -d .\eXoDOS\!%lang%\`

To the following:

```
if exist .\eXoDOS\!%lang%\%index% (
.\util\unzip -o ".\Update\!dos\!%lang%\%FileName%" -d .\eXoDOS\!%lang%\
if exist ".\Update\!dos\!%lang%\linux\release\%FileName%" .\util\unzip -o ".\Update\!dos\!%lang%\linux\release\%FileName%" -d .\eXoDOS\!%lang%\
if exist ".\Update\!dos\!%lang%\linux\%FileName%" .\util\unzip -o ".\Update\!dos\!%lang%\linux\%FileName%" -d .\eXoDOS\!%lang%\
)
```

A short explanation of these paths: The `\linux\release\` directories will contain files that are bundled with the Linux patch. Meanwhile, the files in the `\linux\` directory above it will be for Linux specific updates, which will be bundled in the same update files that everyone downloads. Linux updates are always going to be small and simple things: conf files, run.bat files, bash files, and stuff like that. This directory structure will keep everything separated in a sane way that makes it easy to tell what is what.

The `eXo\util\install.bat` and `eXo\util\!languagepacks\install.bat` files will also need corresponding changes. Separate tickets will be created for those. Then, the other collections that have updates (eXoScummVM and eXoWin3x) will need the same kind of solution applied. The same directory structure should presumably work.

**Comment by parricc** [comment]
Just found another language pack reference inconsistency between `!languagepacks\install.bat` and `eXo\Update\update_installed.bat`.

The `eXo\Update\update_installed.bat` file refers to: `".\Update\!dos\!%lang%\%FileName%"`
The `eXo\util\!languagepacks\install.bat` file refers to: `".\Update\%languagefolder%\!dos\%GameName%.zip"`

We'll need to get an answer from @TimberlAndRE-de on which reference has the correct path.

**Comment by exoscoriae** [comment]
changes in the first post have been processed.

**Comment by parricc** [comment]
Timber has confirmed that the language folder should go inside `Update\!dos\`. So the `eXo\util\!languagepacks\install.bat` file will need to be updated to reflect this.

In  `eXo\util\!languagepacks\install.bat`, change this block of code:
```
:unzip2
.\util\unzip -o ".\eXoDOS\%languagefolder%\%GameName%.zip" -d .\eXoDOS\%languagefolder%\
IF %RESTORE%==Y .\util\unzip -o ".\eXoDOS\%languagefolder%\!save\%GameName%.zip" -d .\eXoDOS\%languagefolder%\
set RUNUPDATE=N
IF EXIST ".\Update\%languagefolder%\!dos\%GameName%.zip" set RUNUPDATE=Y
IF EXIST ".\Update\%languagefolder%\!dos\linux\release\%GameName%.zip" set RUNUPDATE=Y
IF EXIST ".\Update\%languagefolder%\!dos\linux\%GameName%.zip" set RUNUPDATE=Y
IF %RUNUPDATE% == N goto config

cls
echo.
echo %line0048%
echo.
pause
IF EXIST ".\Update\%languagefolder%\!dos\%GameName%.zip" .\util\unzip -o ".\Update\%languagefolder%\!dos\%GameName%.zip" -d .\eXoDOS\%languagefolder%\
IF EXIST ".\Update\%languagefolder%\!dos\linux\release\%GameName%.zip" .\util\unzip -o ".\Update\%languagefolder%\!dos\linux\release\%GameName%.zip" -d .\eXoDOS\%languagefolder%\
IF EXIST ".\Update\%languagefolder%\!dos\linux\%GameName%.zip" .\util\unzip -o ".\Update\%languagefolder%\!dos\linux\%GameName%.zip" -d .\eXoDOS\%languagefolder%\
```

To the following:
```
:unzip2
.\util\unzip -o ".\eXoDOS\%languagefolder%\%GameName%.zip" -d .\eXoDOS\%languagefolder%\
IF %RESTORE%==Y .\util\unzip -o ".\eXoDOS\%languagefolder%\!save\%GameName%.zip" -d .\eXoDOS\%languagefolder%\
set RUNUPDATE=N
IF EXIST ".\Update\!dos\%languagefolder%\%GameName%.zip" set RUNUPDATE=Y
IF EXIST ".\Update\!dos\%languagefolder%\linux\release\%GameName%.zip" set RUNUPDATE=Y
IF EXIST ".\Update\!dos\%languagefolder%\linux\%GameName%.zip" set RUNUPDATE=Y
IF %RUNUPDATE% == N goto config

cls
echo.
echo %line0048%
echo.
pause
IF EXIST ".\Update\!dos\%languagefolder%\%GameName%.zip" .\util\unzip -o ".\Update\!dos\%languagefolder%\%GameName%.zip" -d .\eXoDOS\%languagefolder%\
IF EXIST ".\Update\!dos\%languagefolder%\linux\release\%GameName%.zip" .\util\unzip -o ".\Update\!dos\%languagefolder%\linux\release\%GameName%.zip" -d .\eXoDOS\%languagefolder%\
IF EXIST ".\Update\!dos\%languagefolder%\linux\%GameName%.zip" .\util\unzip -o ".\Update\!dos\%languagefolder%\linux\%GameName%.zip" -d .\eXoDOS\%languagefolder%\
```

**Comment by exoscoriae** [comment]
done
