### ISSUE TITLE
eXo\util\install.bat changes for Linux patch

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5383]
I've gone ahead and designed a solution myself, which I've verified converts correctly. For the Linux patch, the code under the `:unzip2` label in the `eXo\util\install.bat` file will need to be changed.

Before change:
```
:unzip2
.\util\setconsole.exe /reset
rem .\util\setconsole.exe /minimize
.\util\unzip ".\eXoDOS\%GameName%.zip" -d .\eXoDOS\
IF %RESTORE% == Y .\util\unzip -o ".\eXoDOS\!save\%GameName%.zip" -d .\eXoDOS\
IF NOT EXIST ".\Update\!dos\%GameName%.zip" goto config

cls
echo.
echo An update for this game has been found. It will now be applied.
echo.
pause
.\util\unzip -o ".\Update\!dos\%GameName%.zip" -d .\eXoDOS\
goto config
```

After change:
```
:unzip2
.\util\setconsole.exe /reset
rem .\util\setconsole.exe /minimize
.\util\unzip ".\eXoDOS\%GameName%.zip" -d .\eXoDOS\
IF %RESTORE% == Y .\util\unzip -o ".\eXoDOS\!save\%GameName%.zip" -d .\eXoDOS\
set RUNUPDATE=N
IF EXIST ".\Update\!dos\%GameName%.zip" set RUNUPDATE=Y
IF EXIST ".\Update\!dos\linux\release\%GameName%.zip" set RUNUPDATE=Y
IF EXIST ".\Update\!dos\linux\%GameName%.zip" set RUNUPDATE=Y
IF %RUNUPDATE% == N goto config

cls
echo.
echo An update for this game has been found. It will now be applied.
echo.
pause
IF EXIST ".\Update\!dos\%GameName%.zip" .\util\unzip -o ".\Update\!dos\%GameName%.zip" -d .\eXoDOS\
IF EXIST ".\Update\!dos\linux\release\%GameName%.zip" .\util\unzip -o ".\Update\!dos\linux\release\%GameName%.zip" -d .\eXoDOS\
IF EXIST ".\Update\!dos\linux\%GameName%.zip" .\util\unzip -o ".\Update\!dos\linux\%GameName%.zip" -d .\eXoDOS\
goto config
```

A short explanation of these paths: The `\linux\release\` directories will contain files that are bundled with the Linux patch. Meanwhile, the files in the `\linux\` directory above it will be for Linux specific updates, which will be bundled in the same update files that everyone downloads. Linux updates are always going to be small and simple things: conf files, run.bat files, bash files, and stuff like that. This directory structure will keep everything separated in a sane way that makes it easy to tell what is what.

The `eXo\Update\update_installed.bat` and `eXo\util\!languagepacks\install.bat` files will also need corresponding changes. Separate tickets will be created for those. Then, the other collections that have updates (eXoScummVM and eXoWin3x) will need the same kind of solution applied. The same directory structure should presumably work.

**Comment by exoscoriae** [comment]
applied. 

backed up original file to "\!\pre_linux_backups" folder in the WIP
