### ISSUE TITLE
Witchaven II - Blood Vengeance (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5389]
Found that anything higher than 120000 cycles and the intro title Capcom screen is a stuttery mess. Currently its on max so reduce to 120000 to fix. Gameplay still seems ok to me at this speed though menus can be sluggish

**Comment by exoscoriae** [comment]
this game is so picky. 

have we tested it with staging yet?

**Comment by Python-Exoproject** [comment]
Tried it with Staging and performs the same. Here is the conf if you want to move it over (had to reduce cycles a further 10k to avoid the chuggy intro but game still plays the same) along with a tweaked run.bat that changes the mididevice=default to mididevice=auto

[witchaven2.zip](https://github.com/user-attachments/files/17174739/witchaven2.zip)

**Comment by exoscoriae** [comment]
if it plays the same, then probably no reason to move it.
