### ISSUE TITLE
Prince of Persia (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5390]
Ive given Prince of Persia a bit of love and added:

Hercules graphics choice
IBM Music Feature Card choice
Tandy choice

Please switch to Staging, use these files ([Prince.zip](https://github.com/user-attachments/files/16919095/Prince.zip)) and add to any relevant Launchbox playlists

**Comment by exoscoriae** [comment]
omg... for a second I thought you re-opened that old ticket!

**Comment by exoscoriae** [comment]
added. looks great

**Comment by parricc** [comment]
Haven't tested this in Windows yet, but the IBM feature card option is not working in Linux.

**Comment by interloper98** [comment]
> Haven't tested this in Windows yet, but the IBM feature card option is not working in Linux.

Hi @parricc,

I've been helping the DOSBox Staging team with odds and ends, and recently tested IMFC only Raspberry Pi OS (Debian 12) Linux box, and it worked OK. 

From what I know of the codebase, IMFC is built-in 100% of the time (so no external MIDI players or alsa pass through stuff needed). 

Happy to help! can you paste (or attach .txt here) your conf and dosbox staging console log output?

**Comment by parricc** [comment]
Thanks, @interloper98. This is with a dosbox Staging 0.81.2 flatpak built using the org.freedesktop.Platform 24.08 runtime, and a filesystem=host finish-arg. Requested details are as follows:

`options_linux.conf` file, which gets called by most games:

```
[sdl]
usescancodes=false
fullscreen=false
fulldouble=false
windowresolution=2560x1920
[render]
aspect=true
[midi]
fluid.gain            = .2
```

Game conf file:
[dosbox_linux.conf.txt](https://github.com/user-attachments/files/16999974/dosbox_linux.conf.txt)

Output from Staging:
[dosboxoutputlog.txt](https://github.com/user-attachments/files/17000018/dosboxoutputlog.txt)

Relevant run.bat section:

```
:IBM
CONFIG -set "mididevice=default"
CONFIG -set "sbtype=none"
cd prince11
cls
if %cheats%==no prince1 ibmg
if %cheats%==yes prince1 ibmg MEGAHIT
cd ..
goto quit
```

**Comment by interloper98** [comment]
You're right @parricc - PoP doesn't seem to support IMFC at all :smile: 
I added some notes above. I think by 'ibm', they actually mean IBM's audio/game Option Card on the PS/1.

**Comment by Python-Exoproject** [comment]
damn, looks like I got the wrong IBM sound device and the default windows win32 midid driver gave a result and threw me. Glad once again Linux doenst do that and fails.

Next question is how to get the PS/1 audio running, time to tinker again. Unless youve already had luck with that @interloper98 ?

**Comment by interloper98** [comment]
> Next question is how to get the PS/1 audio running, time to tinker again. Unless youve already had luck with that @interloper98 ?

Yup. 

First, be sure you've got PoP version 1.3.  This is the one with `SETUP.EXE` and lots of audio drivers available in the list.

Run SETUP.EXE and select the "IBM audio/game PS/1 Option Card" for both music and effects.

Then in `run.bat`, disable SB completely (`sbtype none`) and turn on the ps1audio `ps1audio on` before launching.

**Comment by interloper98** [comment]
After chatting with @Python-Exoproject , he discovered I was getting PC Speaker sound! Thanks @Python-Exoproject , and sorry for the false positive.

I've gone back through the versions and I think have 1.1 working with PS/1 audio and using the SB for sound effects.  The SB synth's OPL is completely disabled.


https://github.com/user-attachments/assets/74d9ea37-e563-4616-af0b-5603fc871910

Conf is:

```ini
[dosbox]
memsize = 1

[cpu]
cycles = 1500

[midi]
mpu401 = off
mididevice = none

[sblaster]
sbtype = sb1
oplmode = none

[speaker]
pcspeaker = off
tandy = off
ps1audio = on

[ipx]
ipx = off

[ethernet]
ne2000 = off

[voodoo]
voodoo = off

[mouse]
mouse_capture = nomouse
dos_mouse_driver = none
ps2_mouse_model = none

[autoexec]
mount c .
c:
prince ibmg
```

**Comment by interloper98** [comment]
Edit - sadly, this is yet another false positive that @Python-Exoproject flagged.
Turns out the game is using CMS, which I hadn't muted/tested (argh!).
So at this point, I think I've tried every version and every possible way to test the PS/1 Audio Card, and I can't get it working.
Would be very interesting to see if people on real hardware can get this working.
Thanks again @Python-Exoproject , and also, sorry for the false positives :man_facepalming:

**Comment by Python-Exoproject** [comment]
Ok, with all this information ive now disabled the option for IBM and reuploaded a fixed zip and conf to the WIP. My sync decided it needs to verify the whole collection so eventually it should send upstream.

When ive confirmed with @parricc its synced ill close the ticket

**Comment by parricc** [comment]
Not sure how long the sync takes, but no new files have appeared for me on the Synology yet.

**Comment by Python-Exoproject** [comment]
As Boohyaka is away and I dont know when the synology access will be sorted here is the fix files for @exoscoriae to implement: [Prince fix.zip](https://github.com/user-attachments/files/17062768/Prince.fix.zip)

**Comment by exoscoriae** [comment]
i am so motherfucking sick of this game.
