### ISSUE TITLE
Jet Stream (1996)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5395]
Two issues with this game have been confirmed on both Linux and Windows:

- The mouse fails to capture in windowed mode. Adding `autolock=true` to the conf fixes this.
- DOSBox-X drops to a Japanese DOS prompt instead of closing after exiting the game.

**Comment by exoscoriae** [comment]
So this is actually a DOS/V game, which was a japanese version of MS-DOS.

It required quite a bit of setup and experimentation to get it running, as I had no prior experience with DOS/V before this game.

Because the game is booted from a VHD, exiting requires ctrl-f9.
