### ISSUE TITLE
Fire Hawk - Thexder - The Second Contact (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5401]
Found a better patch file for the IBM Music Feature card sound choice.

A good number of these IBM MFC games use drivers and patch files from other games to get them working and in the case of Fire Hawk the sound was ok but not great. I found a new patch file that wasnt part of the online collection that I tried out and it gives much better sound.

Still cant get fx in game but I think thats just the way the game is when using IBM MFC

I also fixed some missing cls in the run.bat. Please use these files: [IMF Fixes.zip](https://github.com/user-attachments/files/17002951/IMF.Fixes.zip)

**Comment by interloper98** [comment]
Sounds great @Python-Exoproject. Tested this on my side (only IMFC enabled, everything else off). Track 7 is especially nice using the music tester at the title screen.

**Comment by exoscoriae** [comment]
added
