### ISSUE TITLE
Chex Quest 3 (1996)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5404]
As user @Jipi noticed, game we know as "Chex Quest 3" isn't official. Most probably, it's a fan-made, and described here: https://chexquest.fandom.com/wiki/Chex_Quest_3_(unofficial)

"Official" Chex Quest 3 was made much later, and worked on ZDoom engine. You can take it here, but I am not sure it will fit eXoDOS collection: https://archive.org/details/ChexQuest3_1020

Anyway, at least we must mark Chex Quest 3 appropriately.

**Comment by exoscoriae** [comment]
ok. I've noted the entry in LB
