### ISSUE TITLE
World Circuit (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5406]
Discord user Dutch Retro Junkie reported issues running the game with ECE that were not present when running via Staging.

In order to avoid any other users encountering issues I provide here the conf to convert the game to Staging for main launch: [dosbox.zip](https://github.com/user-attachments/files/17077671/dosbox.zip)

Also of note is that the European release (Formula 1 Grand Prix, located in the \MPS subfolder or the game zip) is not cracked.

**Comment by interloper98** [comment]
Regarding the crack for World Circuit (1992) - this was raised and fixed here: https://github.com/exoscoriae/eXoDOS/issues/5296

**Comment by Python-Exoproject** [comment]
Guess the ticket was overlooked when we were processing them, thanks interloper.

Removing the not cracked label and leaving ticket in place for switching to Staging

**Comment by exoscoriae** [comment]
switched to staging. crack is it's own issue

**Comment by Python-Exoproject** [comment]
Had to reopen this one as in dosbox.txt you added:

World Circuit (1992):staging0.81.0\dosbox.exe

instead of:

World Circuit (1992):staging0.81.1\dosbox.exe


I would have made the change myself as this is a perfect example of the basic changes we discussed but I have had zero success with any changes ive made uploading to the sync for exodos as yet with the file either just sitting on my side or resulting in one of those dupicate out of sync files with the pc name in it. Until I have this working I dont want to touch something as core as dosbox.txt

**Comment by exoscoriae** [comment]
thank you
