### ISSUE TITLE
Improve !languagepacks\install.bat findstr precision

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5408]
`eXo\util\!languagepacks\install.bat` needs the following substitutions:

`for /F "delims=" %%a in ('findstr /C:"GameData/eXoDOS/%GameName%" .\util\aria\index.txt') do set fullindex2=%%a`
should be:
`for /F "delims=" %%a in ('findstr /C:":GameData/eXoDOS/%GameName%" .\util\aria\index.txt') do set fullindex2=%%a`

`for /F "delims=" %%a in ('findstr /C:"%GameName%" .\util\aria\index.txt') do set fullindex=%%a`
should be:
`for /F "delims=" %%a in ('findstr /C:":%GameName%" .\util\aria\index.txt') do set fullindex=%%a`

`for /F "delims=" %%a in ('findstr /C:"%GameName%" .\util\%languagefolder%\multilanguage.txt') do (set mla=yes)`
should be:
`for /F "delims=" %%a in ('findstr /b /C:"%GameName%" .\util\%languagefolder%\multilanguage.txt') do (set mla=yes)`

**Comment by exoscoriae** [comment]
modifications made
