### ISSUE TITLE
Stop eXo\Update\restore.exe from altering special characters

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5409]
@TimberlAndRE-de will need to update the `eXo\Update\restore.exe` file to stop special characters from getting altered before the eXoDOS 6.04 torrent release.

**Comment by parricc** [comment]
Tested the patched exe in in `test3.zip` and confirmed it works correctly. @exoscoriae Please proceed with replacing `restore.exe` file with the one in `test3.zip`.
[test3.zip](https://github.com/user-attachments/files/17212898/test3.zip)

**Comment by exoscoriae** [comment]
replaced
