### ISSUE TITLE
Aspect False review

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5417]
Ive reviewed all games in the collection that used forced ASPECT FALSE setting to see if converting to Staging removed the need for forcing it. In 95% of cases we dont need it, so please use provided confs and switch to Staging:

[eXoDOS.zip](https://github.com/user-attachments/files/17166969/eXoDOS.zip)

For the few that still do require ASPECT FALSE I include the conf to convert them anyway since I had already created it for testing and checked the game works. These games are:

Lure of the Temptress
Jump 'n Bump
Ring Cycle
Project Paradise (also changed to vesa_nolfb for Staging\Alt Launcher compatibility as flickers without)
Yo! Joe! Beat the Ghosts (in ECE it needed vga_only but in Staging can use normal s3_vga so changed that as well)
LA Blaster (also needed a vmemsize and vesa mode setting tweak for alt launcher\staging compatibility)

In addition to using the above confs LA Blaster needs the files "UNIVBE.DRV", "UVCONFIG.DAT", and "UVCONFIG.EXE" deleted from the game folder so that Staging can use its internal univbe driver.

Lastly, I provided Charlie Chaplin (1988) with a composite choice which helped it look a bit better. This can now be added to the composite playlist

Full list of games to switch to Staging in dosbox.txt:

Alien Trilogy (1996)
Amok (1996)
Armored Fist (1994)
Battlerace (1995)
Bluebush Chess (1983)
Charlie Chaplin (1988)
Clearer (1991)
F-16 Early Deployment Airstrike Force (1984)
Final Battle, The (1991)
Hometown, USA (1988)
Hound of Shadow, The (1989)
Jump 'n Bump (1998)
Kamikazi Alien (1982)
L.A. Blaster (1996)
Last Man Alive, The (1997)
Lure of the Temptress (1992)
Moon Mountain Adventure (1987)
Trials of Odysseus Kent, The (2002)
Project Paradise (1997)
Psion Chess (1985)
Ranadinn (1988)
Ring Cycle (1996)
R-Space I - Viktor's Escape (1991)
Spacewar (1985)
Yo! Joe! Beat the Ghosts (1993)
Caverns of Zoarre (1984)

**Comment by exoscoriae** [comment]
lots of work here. thank you. it has been applied
