### ISSUE TITLE
Rogue (1983)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5424]
Something about the path statement in the below extract of the [autoexec] section of the conf we have in Rogue is causing the alt launcher (due to Staging) to ignore all the user questions in run.bat and directly execute the first instance of an executable it comes across in the run.bat

Not sure why and ive noted it for @johnnovak but on our side I think we can just remove the path line completely? Do you know why its there and if it can be removed safely @exoscoriae ?

`@mount c .\eXoDOS\rogue`
`path=c:\`
`c:`
`cls`
`cd` 
`@call run`
`exit`

Also to get the correct CGA palette the game asks for we should switch to machine=cga

**Comment by johnnovak** [comment]
Or use `path=c:\;%path%` to append `c:\` in front of the existing path. IMO this is preferable as it would work with all DOSBox variants.

**Comment by exoscoriae** [comment]
thank you guys. I've applied johnnovak's solution

iirc, when i set this particular game up, it was on a very old version of dosbox that did not have choice.

**Comment by Python-Exoproject** [comment]
Works well. Looks like the note re machine=CGA fix to get the correct CGA palette fix was overlooked though

**Comment by exoscoriae** [comment]
yea, I missed that. changed

**Comment by exoscoriae** [comment]
![image](https://github.com/user-attachments/assets/fd41c98d-12f3-4492-8a46-0a431d67b051)

**Comment by exoscoriae** [comment]
that is weird terminology. I am changing it to be the same
