### ISSUE TITLE
Stargunner (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5425]
As per https://github.com/dosbox-staging/dosbox-staging/issues/3975 there is an issue with the S3 SVGA mode and this game when using the auto shaders.

I found that setting the game to use et4000 and external UnivBE drivers mitigated the issue and provide the files here to move to Staging and implement the et4000 approach for alt launcher compatibility: [Stargunner.zip](https://github.com/user-attachments/files/17272491/Stargunner.zip)

**Comment by exoscoriae** [comment]
processed changes
