### ISSUE TITLE
Even More Incredible Machine, The (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5429]
I decided to get the floppy version of Even More Incredible Machine added so that we could offer the MT32 and SC55 sound options as well as the previous CD Audio option. I also added the fix patches for midi found at VOGONS.

Switch to Staging and use these files: [EMIM.zip](https://github.com/user-attachments/files/17304264/EMIM.zip)

Once actioned the game can also join its IM1 and IM2 brothers in the MT32 and SC55 playlists

**Comment by exoscoriae** [comment]
I removed the pauses from your run.bat file
