### ISSUE TITLE
Little People Main Street (1992)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5433]
Found out that the Tandy sound for this game is only provided when Tandy graphics are enabled.

Please switch to Staging and use these files to fix: [LPMainSt.zip](https://github.com/user-attachments/files/17306565/LPMainSt.zip)

**Comment by exoscoriae** [comment]
your zip file is incorrect.

it has files for Little People Farm in it.

**Comment by exoscoriae** [comment]
the files were for main street, but they were in the LPFarm subfolder. not sure how you managed that.

I untangled things though and got both running.
