### ISSUE TITLE
Porky's Strip Poker (1993) Manual 

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#5441]
I think the name should be changed to **Strip Poker Live**, the real name of the game.
Porky's Strip Poker is in-game title.
proof:
-PC version https://www.ebay.it/itm/286061896186?
-Amiga Strip Poker Live with same covers & screenshots
https://amiga.abime.net/games/view/strip-poker-live#screenshots
-Amiga named Strip Poker Live with same screenshots
https://thecompany.pl/game/Strip+Poker+Live

I found a manual in italian (there is no manual in the collection for these game)

added to the github folder

**Comment by exoscoriae** [comment]
added manual. leaving game name as it causes mass issues across the pack to rename currently, and the name chosen is on the box.

**Comment by exoscoriae** [comment]
an alternate name can be added to the xml
