### ISSUE TITLE
Master Levels for DOOM II (1995)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5444]
The Master Levels tuned wrong right now.

Well, they _was_ tuned wrong initially, so nothing worked, and @Python-Exoproject fixed them there: https://github.com/exoscoriae/eXoDOS/issues/4867, and now they are working - only they does the wrong thing.

See, the disc of Master Levels contains _two_ different collections.

- Collection 1 consists of Maximum DOOM - "The Ultimate WAD Collection For DOOM and DOOM II". It takes 380Mb, and installed into C:\WADS\DOOM1, and C:\WADS\DOOM2. And currently CFG tuned for this collection, but wrong: it takes wads from CD, not from disc C.
- Collection 2 consists of Master Levels for Doom 2. It uses the same config, so essentially is wrong now. It must point to C:\WADS.
- Each config uses also DOOM1.MAP and DOOM2.MAP for file reference.

So, you need to re-write .bat to use different configs for these two collections. I put configs here, for your convenience.

[MasterLe.zip](https://github.com/user-attachments/files/17363020/MasterLe.zip)

**Comment by Python-Exoproject** [comment]
Ive used the files provided by @SmilingSpectre to update the run.bat and have the correct levels launch.

Ive added asking the user which set of levels they wish to access so we can load the correct set for both normal and network play. 

There was an issue in that when selecting the Master Levels and then in the launcher choosing DOOM 1 you could attempt to load the master level wads which wouldnt work, however if you didnt know better youd be none the wiser as there was no error, it just loaded DOOM 1. 

I got around this by tweaking the level list provided by spectre for DOOM 1 that is loaded when Master Levels for DOOM II is selected to list just one option, the original wad for DOOM. I added a note to the user menu and created a description that loads in the launcher for the DOOM 1 wad explaining why its the only option. Hopefully this will tell any users in this situation what they have done wrong.

[MasterLevels.zip](https://github.com/user-attachments/files/17380485/MasterLevels.zip)

**Comment by exoscoriae** [comment]
updated existing zip with these files
