### ISSUE TITLE
Lurid Land (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5447]
Discord user Finbar reported crackling sound in the game that is fixed by using GUS sound option. I tried a few things with the SB option to clear it up (cycles, different SB devices, etc) with no luck.

There doesnt seem to be any difference other than the crackling between the quality of GUS vs SB so I suggest just moving the game over to GUS as the only sound option

Here is a zip with a Staging conf to move over to Staging and the games setup file for using GUS: [LuriLand.zip](https://github.com/user-attachments/files/17390723/LuriLand.zip)

**Comment by exoscoriae** [comment]
updated

**Comment by parricc** [comment]
The conf file was missed. Without it, the game will fail to launch.
