### ISSUE TITLE
Fleet Defender (1994)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5451]
The game uses Alt-F4 for one of the wingman commands which is a default close window command and exits dosbox.

There is a ticket on Staging github which discusses the issue and found a solution setting a windows variable to override the Alt-F4 behaviour.

Please use this exception.bat to action the fix: [exception.zip](https://github.com/user-attachments/files/17408006/exception.zip)

**Comment by exoscoriae** [comment]
added exception.bat
