### ISSUE TITLE
Bridge Olympiad (1994)

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5457]
Sound Blaster is not working for me. Tested in Linux. Make sure this game isn't playing through the GS Wavetable synth.

**Comment by SmilingSpectre** [comment]
Confirmed: even if I set sbtype=none, it still play sound.

**Comment by Python-Exoproject** [comment]
Looks like this is a game that if it detects the mpu401 it auto outputs midi and as the midi isnt set for MT32 when using the SB option it defaults to the synth.

Yet again glad that Linux doesnt do that and highlights these.

Fix here: [run.zip](https://github.com/user-attachments/files/17435159/run.zip)
