### ISSUE TITLE
Sid Meier's Railroad Tycoon Deluxe (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#546]
pages 86 87 88 89 90 91 are missing
pagenumber 109 is double  pages have different content (114/115)

**Comment by SmilingSpectre** [comment]
Unfortunately, I found only HotU copy (mostly the same, but more ugly), and alternate version with totally different layout. Alternate uploaded.

**Comment by TimberlAndRE-de** [comment]
i think the alternate version is good!
i added the missing coverpage and uploaded it to the github folder
also i extracted the technical supplement pages from the current manual and created an extra issue: #1365
