### ISSUE TITLE
Black Cauldron, The (1986)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5465]
As discovered by discord user Crypt1cMayh3m our copy of Black Cauldron (version 2.10) has a bug that means you cant use the magic sword to defeat enemies.

Tested and confirmed by myself and a few others. Solution seems to be to use version 2.00.

Please replace entire game with these files provided by @SmilingSpectre and set conf to load the differently named executable: [Black Cauldron, The v2.00 (1987)(Sierra On-Line, Inc.) [Adventure].zip](https://github.com/user-attachments/files/17534357/Black.Cauldron.The.v2.00.1987.Sierra.On-Line.Inc.Adventure.zip)

**Comment by exoscoriae** [comment]
replaced with version 2, modified conf to call BC.com instead of Sierra
