### ISSUE TITLE
Shufflepuck Cafe Poster+Manual

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5475]
User @eduo drawn my attention to the fact that Shufflepuck Cafe game came with a giant poster.

As it seems, all versions of Shufflepuck Cafe came with that poster which also serves as manual for the game for its backside.

I must note that we have only French version of such manual, and it seems cutted down to size, for better reading in PDF.

Unfortunately, I wasn't able to locate specific PC poster, so I'll upload others. They are very similar, anyway. The best scan quality is Macintosh, so I would recommend it.

- [ ] Shufflepuck Cafe (1989) - Poster Macintosh.jpg - 11500 x 8800 pixels
- [ ] Shufflepuck Cafe (1989) - Poster Atari-Amiga.jpg - 1000 x 853 pixels
- [ ] Shufflepuck Cafe (1989) - Poster CPC.jpg - 3828 x 2872 pixels
- [ ] Shufflepuck Cafe (1989) - Manual Macintosh.jpg - 11500 x 8800 pixels
- [ ] Shufflepuck Cafe (1989) - Original Painting.jpg - 2891 x 1650 pixels

Everything uploaded to "extras".

PC, it seems, exactly the same, only has 4 screens on the face part, and no "special settings" on the back. Unfortunately, no good scans available. Proofs:

![image](https://github.com/user-attachments/assets/7d0fe095-8660-4968-b4af-467623ac1a6c)

![image](https://github.com/user-attachments/assets/db3cd491-acdd-436c-a97e-e10abaaf4717)

**Comment by exoscoriae** [comment]
added
