### ISSUE TITLE
Magic Candle 2, The - The Four and Forty (1991), StarFight IV - Legacy (1998), & Quest for Glory II - Trial by Fire (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5482]
With Staging 82 now in the pack the following issues can now be resolved.

Magic Candle 2, The - The Four and Forty (1991): MT32 was broken in Staging 81.1

Quest for Glory II - Trial by Fire (1990): Until now all forks of dosbox didnt accurately display the transition in the intro where the carpet flies over the desert and moves to space. Staging 82 added a conf setting that restores the smooth transition

StarFight IV - Legacy (1998): Game was on X as it was previously being booted and for some reason only X could boot the image. Staging 82 can handle the game without need of the boot image now.

Please find a copy of Staging 82 with the extra files we use here: [Staging0.82.0.zip](https://github.com/user-attachments/files/17647903/Staging0.82.0.zip)

Please switch these games to Staging 82 and use these files to resolve the ticket: [eXoDOS.zip](https://github.com/user-attachments/files/17664100/eXoDOS.zip)

While I included the conf in the above zip, the game files for StarFight IV were to large to upload to this github ticket. Since you already have the image in eXoDOS I wont bother uploading the extracted files for you, just open `i100_203.img` and copy all the game files from the `sf4` folder in the image to the \eXoDOS\StarFit4 folder, then delete the `i100_203.img` as its no longer needed

**Comment by exoscoriae** [comment]
processed
