### ISSUE TITLE
3DFX transition to Staging

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5484]
Now that Staging 82 is out and the fixes for 3DFX are in this ticket is to move all 3DFX games over to the better performance of the Staging 3DFX implementation.

Here is the list of games to move to Staging 82:

Archimedean Dynasty (1996)
Battle Arena Toshinden (1996)
Burnout Championship Drag Racing (Player's Choice) (1998)
Blood (1997)
Carmageddon Max Pack (1998)
Descent II (1996)
Descent II Vertigo Series (1996)
DREAMS to Reality (1997)
EF2000 (Special Edition) (1996)
Elder Scrolls Adventures, The - Redguard (1998)
Extreme Assault (1997)
Extreme Tennis (1999)
Furcol (1997)
Grand Theft Auto (1997)
JetFighter III Platinum (1999)
JetFighter Full Burn (1998)
Lands of Lore - Guardians of Destiny (1997)
NASCAR Racing 2 (1996)
Prost Grand Prix 1998 (1998)
Pyl (1999)
Screamer 2 (1996)
Screamer Rally (1997)
Shadow Warrior (1997)
Starfighter 3000 (1996)
Tomb Raider Gold (1998)
UEFA Champions League 1996-97 (1997)
VR Soccer '96 (1995)
Whiplash (1995)
XCar Experimental Racing (1997)

Here is a copy of Staging 82 with the extra files we use: [Staging0.82.0.zip](https://github.com/user-attachments/files/17648057/Staging0.82.0.zip)

Here are the files to implement the above: [eXoDOS.zip](https://github.com/user-attachments/files/17648072/eXoDOS.zip)

Below I have listed notes on what I have changed outside of moving the game over to 3DFX. I separate the first two from the rest as they ask for further action or discussion ontop of the above 3DFX update:

- JetFighter III Platinum: Why are we using version 1.3 for the 3dfx choice? The non 3dfx choice is v1.6 and can do 3dfx just as well. I still think it will require separate installs of the game due to the way the game saves the 3dfx choice from the installer but I think we can upgrade the copy the 3dfx choice is using safely. Also, none of the 3dfx user sound options were using conf files setup for 3dfx so it was no different than the non 3dfx version. I have updated the required files and included them. Run.bat also did not include setting up dosbox sound settings for when a user had previously selected a sound device and chose to just launch the game, I have added the required lines using sel files and added ability for user to see current setting. 

- Furcol: Not sure why it was using an excpetion.bat when a run.bat in the game folder can accomplish the same thing and already exists. Once the zipped files have been added please delete exception.bat and dosbox2.conf

From here its just notes on extra changes made:

All games were at Max cycles so I took a stab at setting manual cycles wherever possible

- Archimedean Dynasty: Removed the forced aspect false settings due to evidence of 3dfx image and research from online of original machines running the game

- Battle Arena: Ive edited run.bat as the cycles edits don't seem needed. All sound choices were using Awe32 instead of sb16 in game setup, files to fix provided.

- Blood: removed forced max cycles in run.bat

- Carmageddon: moved forced aspect to run.bat so only active for lo res where it was needed and not other options where it wasn't. Also moved max cycles to run.bat for the hires launch option as the low res and 3dfx didn't need that many cycles

- Descent II & Descent II Vertigo Series: cycles edited in run.bat to use current Staging method for 82

- EF2000 (Special Edition): updated run.bat just to change mididevice=default to mididevice=auto

- Extreme Assault: updated run.bat to change mididevice=default to mididevice=auto and reduce fluidsynth volume

- Extreme Tennis: Issue game as its a slideshow when the score card comes on screen at the bottom after a rally has ended. ECE also shares this issue in both hardware and software mode. Cycles line removed for non3dfx mode as not needed anymore and detail increased for non 3dfx extreme tennis option.

- Grand Theft Auto: The game and its expansions had resolutions set all over the place. I have provided files to set them all to 800x600. Ive edited run.bat to remove all the aspect ratio settings which don't seem needed, at least with Staging. 

- JetFighter Full Burn: The notes in run.bat about bad 3dfx performance are no longer needed, updated file included. 

- Lands of Lore - Guardians of Destiny: updated run.bat to change mididevice=default to mididevice=auto

- Prost Grand Prix 1998: Edited run.bat to separate the non3dfx and 3dfx cycles

- Pyl: Left on max cycles

- Screamer 2: Removed the forced aspect false settings due to evidence of 3dfx image and research from online of original machines running the game

- Screamer Rally: Removed the forced aspect false settings due to evidence of 3dfx image and research from online of original machines running the game. Also added some needed lines to avoid random crashing for 3DFX during gameplay

- Shadow Warrior: Adjusted run.bat to use mididevice=auto and added note about 3dfx brightness.

- Tomb Raider: There are two 3d exes that can work for the game, one adds shadows. We were using the one without shadows so ive provided the other one. The game still has Gamma issues in 3DFX mode, though this is true in all dosbox forks

- UEFA Champions League 1996-97: fixed run.bat cycles setting

- XCar Experimental Racing: Adjusted run.bat to use mididevice=auto

**Comment by Python-Exoproject** [comment]
One warning I should add, in order to get better performance the Staging implementation has used 8 threads as a default setting and on some PCs this can really rev up the fans and in some cases get a laptop hot. The setting can be manually reduced but my feeling is that we see what the reaction is. I also feel that the performance will reduce with lower threads (on a couple I even had to go to 10 threads) so what is the point of reducing it if you are going to get frame skips

**Comment by exoscoriae** [comment]
this has been processed.

turned throttling on for several titles that were giving me issues (whiplash, screamer, screamer rally, jetfighter 3, and I think one or two others.)

**Comment by Python-Exoproject** [comment]
Looks like I missed updating one set of cycles values in a run.bat, I caught all the other instances

For `Screamer Rally (1997)` the run.bat has the line `cycles 140000`, this should now be `cpu_cycles 140000` so that the throttle is guaranteed to work

**Comment by parricc** [comment]
@exoscoriae Please also upload these updated Linux zips to the WIP `eXo\Update\!dos\linux\release\` directory to prevent future regressions:
[Carmageddon Max Pack (1998).zip](https://github.com/user-attachments/files/17683509/Carmageddon.Max.Pack.1998.zip)
[Grand Theft Auto (1997).zip](https://github.com/user-attachments/files/17683512/Grand.Theft.Auto.1997.zip)

**Comment by exoscoriae** [comment]
cycles fixed.

linux files replaced
