### ISSUE TITLE
Mouse Sensitivity Issues

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5485]
These two games need the mouse sensitivity bumped so for alt launcher compatibility I have converted them to Staging 82.

The games are:
Blood Bowl (1995)
NetHack - Falcon's Eye (2001)

In addition Nethack is supposed to have music and fx but the version we have wasnt compiled to do so. I have included new game files to overwrite our current ones that will activate the music and fx.

Please find a copy of Staging 82 with the extra files we use here: [Staging0.82.0.zip](https://github.com/user-attachments/files/17649497/Staging0.82.0.zip)

Please convert to Staging 82 and use these files: [eXoDOS.zip](https://github.com/user-attachments/files/17649480/eXoDOS.zip)

**Comment by exoscoriae** [comment]
processed. great work on adding sound
