### ISSUE TITLE
Staging 82 cms and alt launcher change to Staging 82

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5486]
We will need to update \eXo\util\alt_launch.txt to use Staging 82. 

The reason is that while Staging 82 is backward compatible with old conf files including Staging 81 and will accept old values for settings that have been changed, Staging 81 has no idea what to do with the newer settings in a Staging 82 conf and will just use default settings, breaking Staging 82 games when alt launcher is used unless we update it to Staging 82.

There are also 6 games that are probably better under Staging 82 with the way it does oplmode cms now. I also included BattleTech - The Crescent Hawk's Revenge (1990) here to save on tickets even though its not a cms issue, I just discovered it has PS/1 audio and set it up to use it. 

Please find a copy of Staging 82 with the extra files we use here: [Staging0.82.0.zip](https://github.com/user-attachments/files/17663346/Staging0.82.0.zip)

Please move the below games to Staging 82 and use these files: [eXoDOS.zip](https://github.com/user-attachments/files/17663314/eXoDOS.zip)

BattleTech - The Crescent Hawk's Revenge (1990)
Bubble Bobble (1988)
Budokan The Martial Spirit (1989)
Puzznic (1990)
QIX (1989)
Rambo III (1989)
Rastan (1990)

**Comment by exoscoriae** [comment]
converted alt launch to use staging 82

processed the games
