### ISSUE TITLE
Soundtrack Issues

### ISSUE THREAD

**Issue by parricc** [exoscoriae/eXoDOS#5489]
Some entries erroneously have what should be in the `<CommandLine>` tag in `<ConfigurationPath>` instead.

This includes:
Descent 2 (Soundtrack)
Descent (Soundtrack)
Dungeon Keeper (Soundtrack)

Descent also has the contents of its Title tag misspelled: `<Title>Descet (Soundtrack)</Title>`

**Comment by exoscoriae** [comment]
fixed.

repacking now
