### ISSUE TITLE
Warp Factor, The (1982)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#5492]
Reported by mgoddard via the videos project this one is completely stuffed due to missing files

Spectre investigated and said:

It's dead as mammoth, as it's missed about dozen of files. Also, it seemingly tries to use disk A, and uses BASICA instead GWBASIC.
TDC, seems, fixed it all already though.

[Warp Factor, The [f1] (1982)(Strategic Simulations, Inc.) [Simulation].zip](https://github.com/user-attachments/files/17717916/Warp.Factor.The.f1.1982.Strategic.Simulations.Inc.Simulation.zip)
[Warp Factor, The (1982)(Strategic Simulations, Inc.) [IMA][160k].zip](https://github.com/user-attachments/files/17717918/Warp.Factor.The.1982.Strategic.Simulations.Inc.IMA.160k.zip)

**Comment by exoscoriae** [comment]
repacked. good fix
