### ISSUE TITLE
Rules of Engagement 2 (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#55]
Should be able to link with Breach 3, but even Ripsaw couldn’t get it working

**Comment by Python-Exoproject** [comment]
Potentially fixed, waiting for sync to test

**Comment by exoscoriae** [comment]
just updated the zip. close to send to QA for you

**Comment by Python-Exoproject** [comment]
Working! Thats been on the list for awhile
