### ISSUE TITLE
Mindbender (1990)

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#5503]
We have VGA-rip.

TDC-version seems fine. Uploaded.

Mindbender (1990)(Gremlin Graphics) [Action, Strategy].zip

**Comment by exoscoriae** [comment]
replaced

**Comment by Python-Exoproject** [comment]
Ive added the user options for CGA and Hercules to the game now that we have a complete copy of the game.

**Comment by Crypt1cMayh3m** [comment]
Testing complete for the changes done in this issue. No problems were found. @exoscoriae or @Python-Exoproject , the status of this issue can be changed to Closed.
