### ISSUE TITLE
Krypton Egg (1996)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoDOS#5512]
We have Krypton Egg (1996) v 3.3 with 60 levels, with de,en,fr, languages in the collection

I found a newer version (1997) V 4.0 with 100 levels, with de, en,fr,it languages.

Added to the github **bugs** folder

**Comment by SmilingSpectre** [comment]
Oh?! But I found it already two years ago... %) I wonder, where it fallen through cracks... *shrug*

**Comment by exoscoriae** [comment]
I remember replacing this... i hate not understanding how something regressed

**Comment by SmilingSpectre** [comment]
They both are registered, @exoscoriae . Shareware is 10 levels, our 3.0 - 60 levels, 4.0 - 100 levels. 3.0 is quite common, but 4.0 I found accidentally, in side project, and people on OG.RU hacked it for me, as it was diskette-locked. :) It made it way in TDC, it seems, but somehow not in eXoDOS. It was in pre-github days, so probably was overlooked somewhere in forums.
