### ISSUE TITLE
Rick Davis's World Trophy Soccer (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#559]
it's from the european version  title says World Cup Soccer Italia 90

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre wrote in another issue (#4756):

_There is specific "Rick Davis" manual, significantly different from the "Italia" one. Unfortunately, only one I found is lowres and with watermark. Uploaded it anyway.

- [ ] Rick Davis's World Trophy Soccer (1989).pdf_

**Comment by exoscoriae** [comment]
rejected. is amiga. current manual is better
