### ISSUE TITLE
Rings of Zilfin (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#560]
has watermark underdogs.cjb.net
it's an extract from a HotU manual, so the real scan needs to be found

**Comment by bigjim161** [comment]
@TimberlAndRE-de, I found a labeled manual for Atari (https://mocagh.org/loadpage.php?getgame=zilfin-alt), but like other Strategic Simulations Inc. (SSI) games, in the manual, they only speak of the c64 and Apple users on page 2. (https://mocagh.org/ssi/zilfin-manual.pdf). They just and added a Zilfin Alt Note for Atari St (https://mocagh.org/ssi/zilfin-alt-note.pdf).
The TXT manual of the current Exodos V4 is a typed version from page 3 to 13 of the "Atari st" manual.
I think this manual is for all versions and should be added, we are just missing the note for the IBM PC.

**Comment by TimberlAndRE-de** [comment]
@bigjim161 great, I think you're right 👍🏻

Did you already uploaded it to the github folder?

**Comment by bigjim161** [comment]
Not yet.
Added to the github folder

**Comment by exoscoriae** [comment]
replaced
