### ISSUE TITLE
Roadwar 2000 (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#564]
it's for Apple / Commodore / Atari 800 according to the booting instructions on page 4

**Comment by SmilingSpectre** [comment]
Alternate version found. Less fancy, but with PC mentioned. Uploaded.

**Comment by TimberlAndRE-de** [comment]
added to the github folder
maybe keep both ?

**Comment by exoscoriae** [comment]
keeping original. everything is fine and relevant to the PC version there.
