### ISSUE TITLE
Serf City - Life is Feudal (1994) (AKA The Settlers)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#57]
Not sure if this exists but there is a little evidence for the first German CD release having had CD Audio tracks. We have tried obtaining this CD once before with no luck.

**Comment by exoscoriae** [comment]
I've purchased this game three times in search for CDA.

**Comment by TimberlAndRE-de** [comment]
There is no CDA version!
I did a lot of research now.
First releases were all on floppy
Later CD re-releases all didn't have CDA
There is one "classic" re-release which shows a small big box cover image that says something about CD audio, so I guess that is were the confusion comes from.
But there was no such big box release with CD, they were all on floppy 😎

**Comment by TimberlAndRE-de** [comment]
here is the picture of my CD version (classics re-release) with the "Programm + Audiotracks" note on it.
But on the disc are no audiotracks

![grafik](https://user-images.githubusercontent.com/67441153/128407071-e2520d5f-67f6-4a87-a479-d7e1dc63550d.png)
