### ISSUE TITLE
SDI - Strategic Defense Initiative (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#585]
wrong game  the manual is for the cinemaware game from 1986

**Comment by SmilingSpectre** [comment]
Uploaded Cinemaware one.

Uploaded right one (in DOC).

**Comment by TimberlAndRE-de** [comment]
- added the DOC for SDI - Strategic Defense Initiative (1988) to the github folder to replace the current one (already added to S.D.I. (1987) (Cinemaware) as reference card)
- the S.D.I. (1987) (Cinemaware) manual is already in the WIP

**Comment by exoscoriae** [comment]
renamed to txt file. I don't keep the DOC extension unless it is actually a word document. DOC was a common text extension during DOS era, and should changed as such to make it simple for notepad to open and view.
