### ISSUE TITLE
Sea Legends (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#586]
bad scan  some parts are hardly readable
imagedetails are not visible
coverpage may be missing

**Comment by SmilingSpectre** [comment]
Only Russian, sorry. I can upload it, but it mostly _totally_ different. *shrug* Uploaded, but I doubt it can be useful.

**Comment by bigjim161** [comment]
I found a better manual with the cover page and image details visible. 
Added to the Github folder

**Comment by exoscoriae** [comment]
replaced
