### ISSUE TITLE
Balance (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#6]
Need an original copy to obtain the manual as the game still has active copy protection and we are unable to locate a crack or online manual.

**Comment by TimberlAndRE-de** [comment]
i found a text on myabandonware that mentioned the manual and wrote them
they had a typed down one but it includes the copy-protection, they uploaded it:
https://dl.myabandonware.com/f/pg8/Balance_Manual_DOS_EN.txt
(i also uploaded it to the eXoDropbox)

**Comment by exoscoriae** [comment]
added as a manual. 
@TimberlAndRE-de @Python-Exoproject 
Shall we open a new issue to a manual upgrade on this one?
