### ISSUE TITLE
Shard of Spring (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#600]
wrong version  it's for the Apple II version according to page 3 (A. Loading the game)

but - according to several sources - there is no IBM manual but a reference card with loading instructions as an addendum to the apple manual

**Comment by bigjim161** [comment]
I think the current manual is for PC, because I found 2 extras:
- a reference card for IBM (extra) 
- a note

Added to the Github Folder

**Comment by exoscoriae** [comment]
added reference card
