### ISSUE TITLE
Sherlock Holmes - Another Bow (1985)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#602]
wrong version  it's for the c64 version of the game

**Comment by SmilingSpectre** [comment]
Found (identical) Apple II. Ah, well. At least, I'll upload extras of better quality.

**Comment by TimberlAndRE-de** [comment]
added issue for the extras: #1359

**Comment by exoscoriae** [comment]
replaced with IBM version.
