### ISSUE TITLE
Silent Service II (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#606]
pages 1 and 2 are boxfront and back  pages 145 - 147 are images of the disks - all are not part of the original manual

page 135 is a map

page 136 is a keybord overlay

pages 137 - 144 are a Technical Supplement

all of them can be added as an extra

**Comment by TimberlAndRE-de** [comment]
Eulisker has splitted the documents.

added to the github folder (and added issue for extras: #2477 )

**Comment by exoscoriae** [comment]
replaced manual with new manual
