### ISSUE TITLE
SimCity (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#608]
some pages could use a little bit of cropping

**Comment by Eulisker** [comment]
I found a better looking 

- [ ] manual

It is for the european version but the content seems to be the same. It would still benefit from a bit of cropping.

**Comment by TimberlAndRE-de** [comment]
DFXThomas scanned and uploaded his

- [ ] manual

**Comment by exoscoriae** [comment]
awesome!
