### ISSUE TITLE
Simon the Sorcerer II - The Lion, the Wizard and the Wardrobe (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#610]
has watermark replacementdocs

**Comment by TimberlAndRE-de** [comment]
discord user ArkhangelAzrael found a scanned one (current one is selfmade or digital version)
https://discordapp.com/channels/454359114601201666/492422228281917470/776276202679304242

added to the github folder

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
Manual in

- English
- French
