### ISSUE TITLE
Sons of Liberty (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#613]
pages 1 and 2 are boxfront and back  page 99 is a picture of the discs - all are not part of the original manual

pages 3 - 38 are the Rule Book
pages 39 - 94 are a Historical Reference Guide
pages 95  97 and 98 are maps
page 96 is a reference card

**Comment by TimberlAndRE-de** [comment]
splitted the file

- [ ] manual (=rule book without the other extras)

and in #3739
- [ ] historical reference guide
- [ ] maps / reference tables
- [ ] registration card

added all to the github folder

**Comment by exoscoriae** [comment]
replaced
