### ISSUE TITLE
Space Rogue (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#617]
has watermark replacementdocs

**Comment by bigjim161** [comment]
I removed watermark on:
"Space_Rogue_-_Map_-_PC"
"Space_Rogue_-_Quick_Reference_Card_-_PC"
"Space_Rogue_-_Ship_Models_-_PC" 

I found another "Space_Rogue_-_Stars_of_Opportunity_"-_without watermark

Added to the Github Folder

**Comment by exoscoriae** [comment]
replaced

**Comment by TimberlAndRE-de** [comment]
Eulisker found

- [ ] Hive Advertisement (inlay from big box)

added to the github folder

**Comment by exoscoriae** [comment]
added
