### ISSUE TITLE
European Superleague (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#629]
seems to be for the wrong game version (Spectrum/Amstrad/C64)

**Comment by SmilingSpectre** [comment]
Wrong assumption. Manual is universal. But I cannot found better quality of it.

Check monkeygames, please? They have it, but I don't know what quality is there.

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre you're right, it says "the manual description applies to all formats in relation of the gameplay".
(monkeygames has the same one)
i close the issue 👍
