### ISSUE TITLE
Pole Position (1996) (AKA Team F1)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#649]
In a leftover state from testing. Execute command and exit command are #shd out in conf, its trying to mount a CD that doesnt exist, and there is a second conf file. I know the German version was gotten to a working state, does the English version work with German CD audio or are we still on the hunt for English CD for Team F1 (the games English name)?

**Comment by Python-Exoproject** [comment]
Tested and currently there is no sound in game. Run sndsetup to fix. Also not that there are SB and Midi options in sndsetup so those probably need setting up as well.

**Comment by exoscoriae** [comment]
I'd still rather have a proper English CD eventually.

Added SC-55 options to the launch batch.

**Comment by Python-Exoproject** [comment]
All working so I will close this issue and create one for the missing English CD. 

One more question though @exoscoriae , Do you think its worth adding a user note with instructions on how to activate CD audio. Something like "To activate CD Audio: When in the office right click your mouse to turn around, then click the coffee pot for sound options. From there click the CD button.

**Comment by exoscoriae** [comment]
note added
