### ISSUE TITLE
Moraff's Dungeons of the Unforgiven (1993): Save transfer from Moraff's World

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#67]
"Moving players from Moraff's World to Unforgiven:
1) First make a backup copy of your Moraff's World directory.
2) Get into your Moraff's World directory.
3) Copy Unforgiven on top of your Moraff's World directory.
4) Type 'CONVERT' to run the conversion program from your World directory.

Note: Your character will begin as a 0 level 'I can handle anything' player
with no spell points (Unforgiven is a very unforgiving game!)."

**Comment by exoscoriae** [comment]
this isn't an easy thing to do. Copy an entire game over the top of another game? I don't like it
