### ISSUE TITLE
Star Trek - The Promethean Prophecy (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#670]
wrong version. It's from the Apple II Release

**Comment by SmilingSpectre** [comment]
Oh, come on. It's cover only. And as it _has_ all this "blah, blah, registered trademark" about Commodore and IBMon the fourth page (and zero mentions about it afterwards), I believe, it's support my point of view.

Also, here you are the second one, exactly the same, but with universal loading instruction document attached at the last page. Uploaded.

Cover added if you want to slightly modify the existing version. ;)

**Comment by TimberlAndRE-de** [comment]
So you think I'm too strict. ;-)

i replaced the cover / back with the pc version and uploaded it to the github.
Also created an issue for the reference card #1360
