### ISSUE TITLE
Star Wars - Rebel Assault (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#673]
has watermark replacementdocs

**Comment by TimberlAndRE-de** [comment]
found version without watermark

**Comment by exoscoriae** [comment]
replaced

**Comment by bigjim161** [comment]
I removed the watermark on the Quick_Reference_Card

I found:
- a game design document: "1992 04 10 Star Wars CD (Rebel Assault)"
- an extra: Troubleshooting Guide

Added to the game folder

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre wrote in #4915 :

_Better scanned manual._

- [ ] Star Wars - Rebel Assault (1993).pdf

**Comment by Eulisker** [comment]
I added an alternate version. Somebody else decide.

**Comment by exoscoriae** [comment]
i chose the alternate version
