### ISSUE TITLE
Starflight (1986)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#675]
has watermark replacementdocs

**Comment by Eulisker** [comment]
I found a better looking

- [ ] manual

The current one seems to be from the [european version](https://www.mobygames.com/game/starflight/cover-art/gameCoverId,15790/). This one is out of the original folder packaging. I added the folder and other extras too. See #3036

**Comment by exoscoriae** [comment]
replaced
