### ISSUE TITLE
Steel Thunder (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#683]
found extra: Sentry Password Chart

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] keyboard overlay

added to the gihtub folder

**Comment by exoscoriae** [comment]
added

**Comment by exoscoriae** [comment]
keyboard overlay refused to open. says file is damaged.
@TimberlAndRE-de
