### ISSUE TITLE
Steel Thunder (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#687]
it's not the real manual (and according to ebay pictures there is one) but more like a reference card or keyguide

**Comment by TimberlAndRE-de** [comment]
wysiwyg found

- [ ] manual (scanned, but it's missing front / back cover, marked as bad but still better than the current keyguide/reference card which can be set as an extra)

added to the github folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
the submitted manual isn't complete, it's missing pages
wysiwyg found a better version

- [ ] manual (quality upgrade)

it's still for C64 because no IBM version is found yet. But at least it's a complete and better looking version

**Comment by exoscoriae** [comment]
added
