### ISSUE TITLE
Unlimited Adventures (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#69]
In process of being setup

**Comment by Python-Exoproject** [comment]
OK, Ive uploaded to the sync github\bugs folder the changes for Unlimited Adventures. Keep in mind its only the changes, not the whole game.

Important notes:

I decided not to update to v1.3c as all I could find was that two modules *might* use a feature unique to it, so I figured not worth the effort of having to confirm the rest still work. I did however replace the base game completely with the copy from oldgames. I did this as every other version 1.2 of the game I could find online and including the one in our mods folder match checksum for most of the files, whereas the scene release copy we were using didnt match anything else and wasnt compatible with Gold Box Companion.

Ive updated the bat files and conf files to allow the use of GBC, though it will only work on the base game due to the way we have the mods setup (as per the PM I sent you the other day).

To use my uploaded zip:

I meant for it to be just an extraction and overwrite of the game folder but the 60 modules that didnt work slightly complicate this. If you just extract, then all the modules that I had to fix will end up with two copies in their folders. Its probably best to delete all the affected .dsn folders from the game folder before doing the extraction.

Other tidying up:

- \exodos\unlimadv\run.bat is no longer used and can be deleted.
- There were two copies of the module "crumpton.dsn", one in General Fantasy and one in Other. Going back to the source webpage I noticed that the one in "Other" is the extra copy and have removed it from module list in run.bat, however you will need to delete \other\crumpton.dsn from the game folder.


Ongoing issues:

- I discovered a couple of modules gave errors when loading with a pause after each error. I traced it to a file called "rundsn.bat".  Most can probably get deleted but I know at least with the Grey Hawk module "grh01.dsn" this may cause an issue as its trying to execute a character generator with fails. According to the module readme that generator needs to run to allow the creation of the hacked character classes.

**Comment by exoscoriae** [comment]
where are we with this? The issues above are outdated now. thanks.

**Comment by Python-Exoproject** [comment]
We had moved to the PM for dealing with this last, I will repeat the last relevant messages here:

Python10/08/2020
OK, tonights UA update.
I have restructured and finished all the rundsn (just an fyi the rundsn.bat files are not standardised as a number of modules had documents wrapped up in exe files which I added to the bat) and mod-info items. New archive syncing now. Archive includes the game zip, conf files, launch bat, and two subfolders for GBC. 

You will probably notice that I am still launching the tutorial and original module "Heirs" via uashell even though they are now separate from the other mods. This is because when run via "start.bat" the game wouldnt give me any sound with MT32+SB selected and with SB+SB it would actually output SB+PCSpeaker even though I had the correct ckit.cfg files copying in (confirmed by checking install program). When I launched via UAShell this was not the case and sound was output correctly. I dont think its a big deal as it just means they are loaded the same as all the other mods, but you may feel differently so im highlighting it here.

Python10/08/2020
Here is a list of issues\things still to do\things to decide we arent doing
[Notes.txt](https://github.com/exoscoriae/eXoDOS/files/5079794/Notes.txt)
Heres some exe and html files that probably need to be handled somehow.

The exe files are bard.exe, ghrtrain.exe, and ghrcgen.exe. Details are in the file but essentially bard and ghrtrain need to by run via an option in uashell to increase the non standard character levels instead of in game via normal training. ghrcgen has been mentioned in the above notes.txt

With the html and one pcx file im not sure what to do as these have info that would normally be in the "MOD-INFO.TXT" but I couldnt add it as it was html
[exe_html_issues.txt](https://github.com/exoscoriae/eXoDOS/files/5079796/exe_html_issues.txt)

One last thing, I just discovered the module "arkana1.dsn" isnt working. It might be just because im tired but I couldnt figure out why

**Comment by exoscoriae** [comment]
* fixed the cwsdmpi and 'MORE' issues. MODE is not fiaxable, but also doesn't affect anything.

* Yes, the path in TXTEDIT.CFG is important. Now they are all wrong... ugh. god damnit. all because of GBC.

* I'm totally not interested in transferring characters between relevant modules at this point. Maybe something to consider for a second version of this project. Even the instructions provided show multiple points for failure.... so really the best we can do is just copy relevant files and still rely on the user to make sure the files are ready, make sure names are correct, etc etc etc. I'm thinking the amount of time this will take is not currently worth the limited reward. At least not during the crunch of wrapping v5.

* For the long mod files, the user can just hold down the space bar or enter key or whatever. It will fly through it.

* for the module name, I realized that it is displayed by UAShell when it loads it. So we just need to explain that this design needs to be selected. The drop down list is incredibly long though.... I think we should have kept it with my original setup.....

**Comment by Python-Exoproject** [comment]
OK next update,

Changes:

I have updated OA.zip to remove the two original game dsn folders and to reduce extraction time I have extracted both original and OA DOCS folders into my below changes.zip as they didnt intefere with each other and removed them from the both OA.zip and Original.zip archives. That way they will be extracted once when you extract my update.zip into the mods folder and never have to be worried about again.

To avoid extracting the original.zip everytime the mods are selected I have setup a check file in the OA.zip that is looked for at the beggining of the mods run.bat, if its found the original.zip is extracted, if its not then this step is skipped.

I have set up OA.zip extraction in run.bat for the other mods that needed it. One issue I also fixed was that these mods wont work via uashell and needed to be run via start.bat. To do this you will see a new label at the bottom of the mods run.bat used by these mods. I also tweaked OA.zip and Original.zip so that sound choice would work for the OA mods as well.

All the above changes are found in this archive "Unlimadv_Changes_19Aug.zip" on the sync in github\bugs folder

-------------------------------------------------------------------------
Comments:

Ill add the missed mods when everything else is wrapped on this.

Are you sure txtedit.cfg contents matters? I ask as whenever you load a mod the file \mods\programs\txtedit.cfg is updated and its contents is always "c:\\(modname).dsn" no matter what the txtedit.cfg file that was in the mods folder contained.
-------------------------------------------------------------------------
Outstanding issues:

- Path statement kills GBC character detection same as the variables in bat file did. This means cwsdpmi and more issue is back when the path statement is removed. Put a copy of more.com in every dsn folder and cwsdpmi in the ghr01 & ghr02 dsn folders? 

- When mods folder run.bat removes folders ready for extraction of Original.zip or OA.zip, the deletion of folders ART, DISK1, DISK2, DISK3, and DOCS fails with "Unable to remove".

- The html\pcx and character trainer issues listed in [exe_html_issues.txt](https://github.com/exoscoriae/eXoDOS/files/5091182/exe_html_issues.txt)

**Comment by exoscoriae** [comment]
Great work on the check file. That def helps.

* as one of only three touched files when you install a module with uashell, I assumed txtedit.cfg mattered. If things are working even though it is wrong though, then I guess not.

* ok, gave each DSN it's own copy of more.com and cwsdpmi to the two that needed it. removed the path variable.

* added mode to game folder just in case

* fixed the deletion of folders ART, DISK1, DISK2, DISK3, and DOCS

Setting next comment as reply to the exe_html issues

**Comment by exoscoriae** [comment]
* solved all the html\pcx issues. you'll see next time you try one of those. Rather nice solution I think.

*ghr01 & ghr02 - ghrtrain: the character trainer works if you pass a variable to it to define the save game. eg:
CHRTRAIN A
This will load and edit SAVGAMA.CSV. The file date changed, to prove a change has been made.

Selecting TRAIN from the UASHELL, and then selecting the proper save game file does this the same way. You can also use this menu to generate characters.

So the user must generate characters, start the game, add them to a party, begin, save the game, exit, restart the module, and this time select train and the save game they created. this will level up the party they put together. I have added this note and ability to both ghr01 and ghr01.

*efn01.dsn - user instructions added to this module to explain how to use the train feature

*resizepc - added instructions on this to all of the rundsn.bat files for the listed modules

**Comment by Python-Exoproject** [comment]
Next update:

Nice work on the html stuff!

----------------------------------------------------------------------------------
Fixes:

I have fixed up run.bat to use deltree on all the OA mods as well as during the restoration of Original.zip. I also discovered a mod that was using the wrong label and had to tweak my workaround for sound choice in the OA mods. I have also enabled the use of rundsn for the OA mods as this wasnt happening due to not being launched via uashell. Please find needed changes in this archive: 
[UA_Changes_20Aug.zip](https://github.com/exoscoriae/eXoDOS/files/5097572/UA_Changes_20Aug.zip)

----------------------------------------------------------------------------
Further comments:

- I suggest we add a note to rundsn.bat for ghr01 & ghr02 under the label :no saying something like:

Remember, if you have created an Assassin, Barbarian, Monk,
Thief-Acrobat, Illusionist, or Bard with the character generator
then to level them up you need to use UAShell to train your
characters via the Character menu (Alt-C) and select Train. 
Now select the save game you created.

Maybe not that word for word, but something along those lines.

- The module "arkana1.dsn" isnt working and I cant see why

- I think I wasnt clear on resizepc.exe. All it seems to do when run is show the text "Resizing character icons...." so I am unsure what its actually doing or whether its important to those modules. It is not a character trainer, so unfortunately the edits you did to the rundsn.bat files for the following modules will need to be either removed or changed to reflect the fact we have no actual idea what it does.

disc1.dsn
game00-game50
gamer1-3
gamer10.dsn
hos1.dsn
legacy.dsn

**Comment by exoscoriae** [comment]
* ok, I reset the arkana files to the original ones (but left the rundsn file we created)

* I reset my changes in the run.bat file after applying your updates

moving on to look at the busted modules now...

**Comment by exoscoriae** [comment]
* One Neverwinter Night uses the OA mod hacks. I used debug to see what file it was hanging on, and the switch that file with the one from OA to test. Once verified, I changed the run.bat to load it like the other OA files and it fixed it.

* Worked for Castle Caldwell as well.

**Comment by Python-Exoproject** [comment]
With your idea of using a world hack to solve the issue I looked into it further as according to the mod-info for those two mods they dont use OA world hack, but two other world hacks. I noticed that they both had xmi files so did some googling and discovered a thread where some other people had also experienced the issue while others said there was no issue. The solution for those with the issue was to delete uasound.dat. This led me to thinking it must be a sound issue so I tried both our MT32 and SB choices, lo and behold SB gives the disk error but MT32 worked fine!

Therefore solution is to roll back to my run.bat, add your removal of Arkana, roll back any changes you may have made to the b9.dsn and onenwn.dsn folders and change the following in run.bat:

:b9
copy .\b9.DSN\START.DAT .\
copy .\b9.DSN\TXTEDIT.CFG .\PROGRAMS\
copy .\b9.DSN\UASHELL.DAT .\PROGRAMS\
CONFIG -set "mididevice=mt32"
copy .\DISK1\mt32\*.* .\
copy .\PROGRAMS\mt32\*.* .\PROGRAMS\
goto loading

:onenwn
copy .\onenwn.DSN\START.DAT .\
copy .\onenwn.DSN\TXTEDIT.CFG .\PROGRAMS\
copy .\onenwn.DSN\UASHELL.DAT .\PROGRAMS\
CONFIG -set "mididevice=mt32"
copy .\DISK1\mt32\*.* .\
copy .\PROGRAMS\mt32\*.* .\PROGRAMS\
goto loading


Now that I know whats causing the issue ill target the other possibly affected modules and see if they are also failing. I have already tested TMNT1.dsn and it worked fine with either choice so its not a universal issue

**Comment by Python-Exoproject** [comment]
Got another one, fourevil.dsn. This one freezes on loading when selecting MT32 so changes as per below:

:fourevil
copy .\fourevil.DSN\START.DAT .\
copy .\fourevil.DSN\TXTEDIT.CFG .\PROGRAMS\
copy .\fourevil.DSN\UASHELL.DAT .\PROGRAMS\
CONFIG -set "mididevice=default"
copy .\DISK1\sb16\*.* .\
copy .\PROGRAMS\sb16\*.* .\PROGRAMS\
goto loading

It surprised me as it doesnt give a disc error, just freezes and up until now I had believed all the xmi stuff was for MT32 as it sounds MUCH better via that mode. Anyway, still looking for more

**Comment by Python-Exoproject** [comment]
Just noticed that github had removed all my trailing "\". fixed the above but if you have copied and pasted before I fixed it then you will need to add back the "\" yourself

**Comment by Python-Exoproject** [comment]
While checking dsn folders with xmi files I discovered one that didnt have its uashell dat files. Please find in this archive the needed files to add to the folder liberty.dsn 
[liberty.dsn.zip](https://github.com/exoscoriae/eXoDOS/files/5115941/liberty.dsn.zip)

Still checking the xmi stuff

**Comment by Python-Exoproject** [comment]
Decided due to the above missing start.dat to do a quick check for other missing start.dat files. Found 6, all included in the below zip. I know I made this mistake once so I will bring attention to the fact that one of the involved dsn folders is "gamer2.dsn", not "game02.dsn"
[Needed Files.zip](https://github.com/exoscoriae/eXoDOS/files/5116092/Needed.Files.zip)

**Comment by Python-Exoproject** [comment]
Next one, nocturne.dsn. Freezes when run with MT32, change to below:

:nocturne
copy .\nocturne.DSN\START.DAT .\\
copy .\nocturne.DSN\TXTEDIT.CFG .\PROGRAMS\\
copy .\nocturne.DSN\UASHELL.DAT .\PROGRAMS\
CONFIG -set "mididevice=default"
copy .\DISK1\sb16\*.* .\\
copy .\PROGRAMS\sb16\*.* .\PROGRAMS\\
goto loading

**Comment by Python-Exoproject** [comment]
Next issue I found is a broken label and pathing in run.bat:

:hevoice
copy .\hevoice.DSN\START.DAT .\\
copy .\hevoice.DSN\TXTEDIT.CFG .\PROGRAMS\\
copy .\hevoice.DSN\UASHELL.DAT .\PROGRAMS\\
goto loading

should be:

:thevoice
copy .\thevoice.DSN\START.DAT .\\
copy .\thevoice.DSN\TXTEDIT.CFG .\PROGRAMS\\
copy .\thevoice.DSN\UASHELL.DAT .\PROGRAMS\\
goto loading

**Comment by Python-Exoproject** [comment]
- Ok, Ive finished checking over 100 modules that had xmi files for SB and MT32 issues. There are another 50 odd that are all made by the same guy known as "The Realm" that I just spot checked as Im willing to assume a level of consistency in his work over the span of the modules.

- I also noticed that you left "frame.tlb" in the arkana1.dsn folder but as that was added by us I think we should remove it for now.

Once the above fixes have been made it should be all good (fingers crossed)

**Comment by exoscoriae** [comment]
all changes above applied

**Comment by Python-Exoproject** [comment]
Ok, I think we are there! I had to tweak mods run.bat as I discovered github had removed one of the other backslashes in my posts above that I didnt notice so when you copied it in it didnt work. I also added the backup system to the main game folder as its using uashell as well. I also figured out what was causing the intermittent GBC failure so that is fixed as well.

Uploaded to sync github\bugs folder ready for use.... finally

**Comment by Python-Exoproject** [comment]
For future reference if we ever want to crack this one open again things that are still broken\could be implemented are:

- module Arkana1.dsn does not work and has been rem'd out of run.bat

- Transfer characters between modules (relevant for "The Realm", Realm Compatible, Paladin1 into Paladin2, Batteri2 into Batteri3, Batteri3 into Batteri4 (Batteri 1 into 2 not needed as 2 uses premade party), hwold1 into hwold2, rq1 into ra3, ra3 into ra1, ra1 into ra2, ra2 into rq3, serial01 into serial02, serial02 into serial03, serial03 into serial04, serial04 into serial05, each of the "West" series into each subsequent)

Notes on the process to transfer characters from one of the modules:

"In order to transfer characters from another module, follow these steps.  In 
the other module, go to your latest save game, and "remove" all of the 
characters from the party.  This will update the individual character files on 
the disk, the ones ending in ".CCH", to the state of the characters at the end 
of that adventure.  Leave Unlimited Adventures, and go into the save directory
for the old adventure.  Use the copy command to copy the *.CCH files to the 
/FRUA/PALADIN2.DSN/SAVE directory.  When you restart Unlimited Adventures, 
select the merchant league module.  When you "add" characters, the names of 
those you just transferred should be listed."
