### ISSUE TITLE
Star Wars X-Wing (Collector's CD-ROM) (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#691]
found alternate manual from disk version with copy protection
current one is from cd-release collector's edition
maybe worth to add as an extra because of the copy protecion signs

**Comment by exoscoriae** [comment]
added disk version of the manual to the extras, as the actual game entry is for the cd version, I want too keep that manual associated with it

**Comment by TimberlAndRE-de** [comment]
i found a quality upgrade for the extra "Star Wars X-Wing Disk Copy Manual", since the current one ends with page 17 (new one has 19 pages and more copy protection codes)

**Comment by TimberlAndRE-de** [comment]
Smiling Spectre found

- [ ] Star Wars X-Wing Disk Copy Manual

much better version

added to the github folder

**Comment by exoscoriae** [comment]
added/replaced
