### ISSUE TITLE
Sentient (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#694]
Suffers from the mouse acceleration issue.

Dosbox-X does not suffer the problem but as its Dosbox-X we wont switch over until the game has been fully tested with a successful playthrough.

**Comment by Python-Exoproject** [comment]
With @kcgen help we discovered that the issue with the cursor is not to do with acceleration but cycles. Set cycles to 220000 instead of max and the cursor works properly.

**Comment by exoscoriae** [comment]
set cycles to 220,000
