### ISSUE TITLE
Populous (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#697]
Reference Card and manual addendum as extras
SmilingSpectre found it on scrib'd
https://ru.scribd.com/document/420569084/Populous-Command-Summary-Card
https://ru.scribd.com/document/420569075/Populous-Addendum

**Comment by Eulisker** [comment]
I scanned

- Promised Lands Order Form
- Promised Lands Reference Card

Added to the github folder.

**Comment by exoscoriae** [comment]
added
