### ISSUE TITLE
NeoHunter (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#698]
Registration Card, Troubleshooting Guide, Warranty Card as extras
SmilingSpectre found it on scrib'd
https://ru.scribd.com/document/420568502/NeoHunter-Registration-Card
https://ru.scribd.com/document/420568501/NeoHunter-Help
https://ru.scribd.com/document/420568433/NeoHunter-Warranty-Card

**Comment by TimberlAndRE-de** [comment]
- [ ] Registration card
- [ ] Warranty card

aren't in the wip yet... I added them to the github folder, not sure how the scribd thing above was handled ;-)

**Comment by exoscoriae** [comment]
we can't trust scrib'd links. they often require memberships and shit.

added the 2 docs from the github
