### ISSUE TITLE
The Colony (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#717]
found decoder (copy-protection) as an extra
i found proof, that it came with the mac version of the game. not sure if it was also packed within the box of the DOS version.

**Comment by exoscoriae** [comment]
added

**Comment by Python-Exoproject** [comment]
[Colony_The_-_Decoder_1988.zip](https://github.com/exoscoriae/eXoDOS/files/14663013/Colony_The_-_Decoder_1988.zip)

Discord user Digitoxin has created this interactive version

**Comment by exoscoriae** [comment]
added!
