### ISSUE TITLE
Billy the Kid (1990)

### ISSUE THREAD

**Issue by exoscoriae** [exoscoriae/eXoDOS#731]
Game specs claim there is a Null Modem connection option for this game. The game itself is in German however, and it is unknown if an English copy was ever created for DOS. With my limited German translation ability, I found no evidence of how to enable the Null-Modem connection and actually play the game with it.

**Comment by Python-Exoproject** [comment]
Linked to issue #8

**Comment by TimberlAndRE-de** [comment]
i got it to work with Nullmodem option (but haven't testet the connection yet)
@exoscoriae 
you have to change the HUGE.INI set serial=1 for the first COM-Port
after that you can choose "2 SPIELER"
![grafik](https://user-images.githubusercontent.com/67441153/86092056-346eb300-baad-11ea-9f1e-12b10279f213.png)

**Comment by exoscoriae** [comment]
thanks! fixed
