### ISSUE TITLE
688 Attack Sub (Demo verision)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#744]
Discovered the Maxel demo version of the game. Comes with two missions, both different to the missions in the main release.

https://dosgames.com/game/688-attack-sub/

I also attach to this issue the quick start guide for it.

[688attacksub_quickref.txt](https://github.com/exoscoriae/eXoDOS/files/4849311/688attacksub_quickref.txt)

**Comment by exoscoriae** [comment]
added
