### ISSUE TITLE
688 Attack Sub (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#745]
Located in my random collection of stuff a text file for the sonar IDs of vessels in the game.  Added to github sync folder

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found:

- [ ] code sheet - quality upgrade, scanned version, current one is a text file

added to the github folder

**Comment by exoscoriae** [comment]
added
