### ISSUE TITLE
Eye of the Beholder 1, 2, & 3 (All Seeing Eye automap tool)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#746]
The author of Gold Box Companion also made the All Seeing Eye to do the same thing for the Eye of the Beholder series. We were in contact to ask him to modify the All Seeing Eye to accept relative paths just as he had done for Gold Box Companion, but so far have not had the same luck.

**Comment by Python-Exoproject** [comment]
Ok finally got around to testing this one. Points of interest are:

1. While not necessary I suggest adding an addendum to the user note for all three EOB games saying something like "If you have selected Fullscreen during install you will be unable to see the ASE tool window."

2. To enable to "Manual" and "Cluebook" buttons in the ASE\ASE3 tool like we did in GBC we need to copy each games amnual and cluebook into the games root folder and name it "manual.pdf" and "cluebook.pdf"

3. EOB2 has a sound problem. Jemmy discovered that there is a piece of music supposed to play when all 4 horns are blow to open a secret passage. Very rarely does this music actually play in our copy. He created 2 videos showing the difference which I attach here: [EOB2 sound issue.zip](https://github.com/exoscoriae/eXoDOS/files/5648695/EOB2.sound.issue.zip). Jemmy made a savegame (named ST1) at the relevant point for testing which I included along with the working\broken video.

4. One side effect of the AESOP32 conversion we have done to EOB3 is that it now has a bad popping sound that can be heard at many points during the game. To test you can just start the game and load the quick start save. Wait a little and some spirits attack you. The popping is heard continuously throughout the fight. Every dosbox version (ECE, 0.74, 0.74r3, svn, X, daum, staging, etc) except for vanilla 0.73 have the issue. The quickest solution is to switch back to the unconverted version but I dont think this is the best solution as using AESOP32 makes the game run a lot better in general. Other than that the easiest solution is to switch to a custom dosbox launch for the game using vanilla 0.73 but this will stuff up MT32 and SC, so the best solution is probably to pass it to ripsaw and see if he can figure out why only 0.73 sound is ok. Being a conversion of the game into a new engine though im not sure if he will touch it.

**Comment by exoscoriae** [comment]
1. added user note for full screen.
2. added manual & cluebooks
3. I'm not entirely sure what we are supposed to do about this. I'll dig in.
4. I'll see if he wants to take a look.

**Comment by exoscoriae** [comment]
Looking into EOB2 further. I tried running a debug log, however the game gives no error at that point.
I tried generic conf settings to ensure nothing we were using is causing the issue. 
I tried running that section of the game from both a different copy and from a clean install from floppy disks. The same behavior occurred in all cases.
Tested 0.74, ece, x, and daum. All exhibit this issue as well.

**Comment by exoscoriae** [comment]
Ripsaw has mentioned he knows the issue behind AESOP32, and has a fix laying around for it.

**Comment by exoscoriae** [comment]
Using Sample Accurate in Dosbox-X fixes the sound problem in EOB2, however X is incompatible with ASE. So I have modifed the game to run with X if you run it without ASE. However choosing ASE launches it with ECE instead, which reintroduces this sound issue.

The sample accurate patch is something that has been pushed to be added to the full DOSBox release. Assuming that ever happens, it may solve the issue while also still being compatible with ASE.

**Comment by exoscoriae** [comment]
ripsaw noted that using dos32a fixes the popping noises. I've replaced dos4gw with this and found it worked. adding to updater.

**Comment by Python-Exoproject** [comment]
Dont forget that in EOB2 now that you are using X for the non ASE selection it needs output=openglnb and fullscreen=desktop.

I will make a separate issue to track the need for X until a sample accurate patch has been added to vanilla dosbox. Might be worth mentioning to krc for staging as well?

**Comment by exoscoriae** [comment]
this means we would need an entirely new conf file for non ASE ... damnit

These companion apps are turning into real pains.

And sure, it can be brought up to krc and such.

**Comment by exoscoriae** [comment]
also, isn't it fullresolution=desktop?

**Comment by Python-Exoproject** [comment]
yeah, thats the one - fullresolution. Its late :-). I dont think we need the alt conf as openglnb is preferred anyway and while desktop isnt optimal compared to 0x0 it wont break ECE and anyone using ASE wont be in fullscreen anyway

**Comment by exoscoriae** [comment]
ok
