### ISSUE TITLE
Ultima 5 (Ultimapper automapper tool)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#747]
The author of Gold Box Companion also made Ultimapper to do the same thing for Ultima 5. We were in contact to ask him to modify the Ultimapper to accept relative paths just as he had done for Gold Box Companion, but so far have not had the same luck.

**Comment by Python-Exoproject** [comment]
Points of interest for this one:

1. Inside transfer.bat (both the one in U5 and U%\Upgrade) it might be worth adding the note that to successfully transfer a game from Ultima IV, U4 must be still installed. Something like "To use this function Ultima IV must still need to be installed. To complete the transfer you will need to select "Transfer from Ultima IV" inside the game.". Additionally with the u5 upgrade version once you've selected "Transfer from Ultima IV" you need to enter "a" to select the source drive for the u4 character so that should be noted as well.

2. Also with transfer.bat I noticed that you are only allowing u4 vanilla to u5 vanilla and u4 upgrade to u5 upgrade, not u4 vanilla to u5 upgrade or u4 upgrade to u5 vanilla.

3. As per all the GBC games, Ive edited the launch bat to use ssr to resize the dosbox window when choosing Ultimapper5 as the HUD is offscreen with our standard size and to resize it back if choosing a non Ultimapper option. Here is the new bat: 
[Ultima V - Warriors of Destiny (1988).zip](https://github.com/exoscoriae/eXoDOS/files/5648746/Ultima.V.-.Warriors.of.Destiny.1988.zip)

4. As with the other tools you can access the game documents from the right click menu. For both the original and upgrade versions to access them they will need to be added to both game folders. I have listed below what to name each document so that the tool detects it:

Our File                                                                          New file
u5-refcard-ibm.pdf                                                        Manual.pdf
Ultima V - Warriors of Destiny (1988).pdf                     Ultima 5 The Book of Lore.pdf
Ultima_V_-_Spellbook_-_PC.pdf                                    Ultima 5 Spellbook.pdf
Ultima_V_-_Cluebook_-_PC.pdf                                     Ultima 5 Cluebook.pdf
Ultima_V_-_Quick_Reference_Card_-_PC.pdf                 Ultima 5 Reference Card.pdf

**Comment by exoscoriae** [comment]
1. I hate to have to do this, but sure. At some point though, we can't make this thing any more idiot proof. If someone doesn't fucking understand they have to actually have Ultima 4 installed to transfer a character from it... then I really don't know what to do for them. What's next, "please ensure you don't power off your computer while playing, or you will not be able to complete your game?"

2. I went ahead and added options to transfer from either game into either game.

3. Replaced the launcher.bat with the one you provided

4. These docs sure bloat these games. Adding the docs (twice, once for the base game and once for the upgraded game) bumps the game from like 2mb to 166mb. That seems semi ridiculous.... Especially when the docs are all easy to access right in launchbox.... which is open in a window right below the game.... I'm really not sure how I feel about it. One one hand, 166mb isn't a big deal compared to the size of other games in the pack. But it is a big deal when the game was original 2mb.. so we are blowing it up by some 80x it's original size just so some buttons work on a context menu..? What are your thoughts knowing the size differences?

**Comment by exoscoriae** [comment]
For now I've decided to add the docs for v6, but for the updater they are not being added. I am however updating to the new spell book in the updater for the LB side of things.

**Comment by Python-Exoproject** [comment]
Looks good. My only comment is that in the Ultima 5 Upgrade version after you select "transfer from Ultima IV" It asks you for a drive at this screen:

![image](https://user-images.githubusercontent.com/67406191/104090946-3d4b0780-52ce-11eb-8f77-6edcc506e272.png)

There is no indication that they need to enter "a" to use drive a: to find the save for transfer. Its only relevant for the upgrade version as the original just assumes its "a" and never asks. So for the Upgrade version I suggest adding to the user note that says they need to have U4 currently installed that they will need to press "a" to find their savegame when prompted during the transfer process

**Comment by exoscoriae** [comment]
added a note for the A:.

Also updated the updater, however it will be in the next update, not the first.

**Comment by Python-Exoproject** [comment]
During latest testing I realised that when you select the upgrade option and transfer a character from U4, transfer.bat was not calling run.bat to ask for sound choices. I know your probably over this one so I have done the needed changes here:
[U5_Upg_Transfer_bat.zip](https://github.com/exoscoriae/eXoDOS/files/5795563/U5_Upg_Transfer_bat.zip)

As I was already editing it I also reworded the note about pressing "a" to be the similar to that used in your original \ultima5\run.bat.

**Comment by exoscoriae** [comment]
replaced transfer.bat

Added modified one to next update structure
