### ISSUE TITLE
Nine Princes in Amber (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#755]
found manual-addendum as an extra

**Comment by exoscoriae** [comment]
added

**Comment by bigjim161** [comment]
Discord user wysiwyg found: 

- a manual-addendum (extra) : quality upgrade
- a manual : quality upgrade
- a Catalog
- a Card
- the scanned box of the game
- a sheet "Loading on IBM PC"
- a sheet "Telaruim Sneak Previews"
- an envelope
