### ISSUE TITLE
Prince of Persia (1990)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#758]
User Can noted in discord bug reports channel an issue with loading save games in version 1.3. I have confirmed the issue and attach the fixed exe that corrects it.

I also noticed that run.bat has .| instead of .\ for some weird reason.

Lastly I checked v1.1 and noticed it isnt using a crack at all. The cracked exe is included in the \prince11\ folder though, just switch from using prince.exe to prince1.exe

[Fixed POP13 crack.zip](https://github.com/exoscoriae/eXoDOS/files/4852149/Fixed.POP13.crack.zip)

**Comment by exoscoriae** [comment]
fixed
