### ISSUE TITLE
3 Skulls of the Toltecs (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#77]
pages are missing due to the table of contents, probably the other language versions. The manual is therefore incomplete (but the english pages seem to be all included)

**Comment by SmilingSpectre** [comment]
I didn't check on-site one, as Timber said it's incomplete. *shrug* Nevermind. :)

**Comment by exoscoriae** [comment]
the one we have has every page. So I'm not entirely sure what the original issue was even about. All 31 pages are present and accounted for. page 16 and 24 are blank. However it appears they are intended to be.

**Comment by TimberlAndRE-de** [comment]
yes, my fault. the manual was already updated in the WIP
sorry, Spectre

**Comment by Eulisker** [comment]
Manual in 

- English
- German
- Spanish
- Italian
