### ISSUE TITLE
Grand Prix Circuit (1988)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#793]
No English language 
Language(s): de

**Comment by TimberlAndRE-de** [comment]
wysiwyg ([discord](https://discordapp.com/channels/454359114601201666/492422228281917470/774665100165906494)) found an english manual (Hit Squad, but since we don't have another one yet...)

added to the github folder

**Comment by exoscoriae** [comment]
replaced
