### ISSUE TITLE
7 Colors (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#81]
No English language 
Language(s): fr
pages 2 & 3 are missing
copy protection codes are included

**Comment by Eulisker** [comment]
I scanned the multilanguage

- [ ] manual (en,fr,de,it)

My box has no copy protection codes unfortunately so maybe you should keep the current manual as an extra. Or at least cut out the copy protection codes.

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
Manual in

- English
- French
- German
- Italian
