### ISSUE TITLE
Abandoned Places - A Time for Heroes (1992)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#85]
originated it seems to be an official manual-readme but there are passages added bei VF who cracked the game (see section COPY PROTECTION) 
According to section LOADING INSTRUCTIONS is is for the amiga version only.

**Comment by exoscoriae** [comment]
Replaced with Amiga manual scan.

**Comment by Eulisker** [comment]
I found a better scan of the 

- [ ] manual

Added to the github folder.

It still is for the amiga version but my guess is there only was the one manual. According to OGDB.eu the [amiga version](https://ogdb.eu/index.php?section=game&gameid=54611) does not have the quick start card of the [pc version](https://ogdb.eu/index.php?section=game&gameid=7143). I think it is one of the games that have the amiga manual and the pc loading instructions on a seperate document. 
But until somebody finds the PC Version we can not know for sure.
