### ISSUE TITLE
World Championship Boxing Manager (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#861]
No English language 
Language(s): es 

- [ ] bigjim found english manual

added to the github folder

**Comment by bigjim161** [comment]
I found an English manual

Added to the Github Folder

**Comment by exoscoriae** [comment]
replaced

**Comment by bigjim161** [comment]
I found another manual with platform-specific instructions for IBM PC, Amiga, and Atari ST (the current manual is generic).
It can replace the existing one, which may be retained as an extra.
