### ISSUE TITLE
Whale's Voyage (1993)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#879]
pages 2-26 are missing (german language part)
has watermark replacementdocs

**Comment by TimberlAndRE-de** [comment]
found complete version without watermark

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
I found a nicer scan of the

- [ ] manual

Added to the github folder.

**Comment by exoscoriae** [comment]
replaced

**Comment by Eulisker** [comment]
Manual in 

- German 
- English
