### ISSUE TITLE
Strider (1989)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#887]
it's not a manual but a reference card

**Comment by SmilingSpectre** [comment]
There is nothing better, I fear. Proof: https://i.ebayimg.com/images/g/b8oAAOSws4Fea9tR/s-l1600.jpg

**Comment by TimberlAndRE-de** [comment]
![grafik](https://user-images.githubusercontent.com/67441153/88461516-7a4c4a80-cea4-11ea-95fe-4dfd84e565bf.png)

copied the picture in here for the case ebay deletes it.
issue closed

**Comment by Eulisker** [comment]
Manual in

- English
- French
- German
- Italian
