### ISSUE TITLE
Subwar 2050 (CD-ROM) (1994)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#896]
has watermark replacementdocs

**Comment by exoscoriae** [comment]
removed. also added journal to extras

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre found an alternate manual with colored coverpage an more content (Quick Start Guide)
I think it should replace the current one, since it has more content

**Comment by exoscoriae** [comment]
replaced
