### ISSUE TITLE
Terra Nova - Strike Force Centauri (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#921]
has watermark replacementdocs

**Comment by TimberlAndRE-de** [comment]
found

- [ ] manual (US manual according to [ogdb.eu](https://ogdb.eu/index.php?section=game&gameid=1877), not sure from which release the current version came from, but this one contains same informations (if you add the installation guide I submitted unter extras), looks better and is a much more cleaner scan.

added to the github folder

**Comment by exoscoriae** [comment]
replaced
