### ISSUE TITLE
Test Drive III The Passion (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#924]
found reference card as an extra

**Comment by exoscoriae** [comment]
added

**Comment by TimberlAndRE-de** [comment]
found the code wheel - needs to be converted to an interactive one

![Test-Drive-III-The-Passion_Misc_DOS_EN](https://user-images.githubusercontent.com/67441153/90808902-07a68180-e321-11ea-83e3-407f51071875.png)

**Comment by exoscoriae** [comment]
added code wheel

**Comment by TimberlAndRE-de** [comment]
KrunkTheMadMan scanned the

- [ ] code wheel (upgrade, colored and higher resolution)

added to the github folder

**Comment by exoscoriae** [comment]
added
