### ISSUE TITLE
Final Battle, The (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#946]
wrong manual  it's for the amiga/atari version of the game

**Comment by SmilingSpectre** [comment]
It's taken from the Mocagh, and all other docs are DOS. So I guess, there is no such thing as PC manual.

**Comment by TimberlAndRE-de** [comment]
@SmilingSpectre yes, true. normally mocagh is a trusted source, so i think you're right.
in combination with the ibm-reference card already included in eXoDOS it's fine i guess
issue closed ;-)
