### ISSUE TITLE
Ultima VII Part 2 - Serpent Isle + The Silver Seed (1993)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#952]
I noticed that recently added extra "Ultima_VII_Part_Two_-_Serpent_Isle__The_Silver_Seed-_Beyond_the_Serpent_Pillar_-_A_Journal_Describin.PDF" is a duplicate of manual "Ultima VII Part 2 - Serpent Isle + The Silver Seed (1993).pdf"

"Ultima VII Part 2 - Serpent Isle + The Silver Seed (1993).pdf" manual is the better version

**Comment by exoscoriae** [comment]
removed lower quality extra

**Comment by TimberlAndRE-de** [comment]
i found a q&a sheet for the copy protection (i don't think it's needed for our version, but maybe add it to extras for preservation?)

**Comment by exoscoriae** [comment]
it's a hack extract from something else. not needed.
