### ISSUE TITLE
Hunt for Red October, The (1987)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#959]
- needs to be cropped
- has 
- [x] Mission Document
- [x] Ship Recognition chart
appended, can be split and added to extras

**Comment by Eulisker** [comment]
I found a better scan of the 

- [ ] manual

The two extras have a seperate issue #3728 
Added to the github folder.

**Comment by exoscoriae** [comment]
added\replaced
