### ISSUE TITLE
Multiple games for Tandy sound

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoDOS#982]
Spectre found a list of Tandy sound compatible games [README.txt](https://github.com/exoscoriae/eXoDOS/files/4865857/README.txt). I have gone through the list and enter below the ones that we did not already have set up:

Amazon 1984	TELARIUM

DragonWorld 1984	TELARIUM

Fahrenheit 451 1984 TELARIUM

Perry Mason: The Case of the Mandarin Murder 1985 TELARIUM

The Wizard of Oz 1985 WINDHAM

Treasure Island 1985 WINDHAM

Zak McKracken and the Alien Mindbenders (Not the enhanced one)

Nine Princes in Amber 1985 TELARIUM - This one needs machine=pcjr instead of machine=tandy

King's Quest IV: The Perils of Rosella - The AGI version can use machine=tandy and get much improved sound. This will however entail using the "-machine tandy" command line for the AGI user option.

Thexder - Going over discord logs we got a patch from ripsaw to enable tandy sound with the higher quality graphics. Bigjim then said it didnt load and we went back to non tandy sound. Ive looked again and it seems the issue was that ripsaw gave us a TSR, not a patch. Load thexvga3 before the current exe and it will give both Tandy sound and good graphics.

Maniac Mansion (Not the enhanced one) - This one gives graphics corruption if machine=tandy is chosen. However if you use the hacked exe from the FTP [MODIAC.zip](https://github.com/exoscoriae/eXoDOS/files/4865864/MODIAC.zip) it will work properly. You trade mouse support for better sound, so maybe a user choice?

Zak McKracken and the Alien Mindbenders Enhanced - Switch from running start.bat to zak.exe and set machine=tandy. Like with Maniac Mansion this gives better sound but you loose mouse support.

**Comment by exoscoriae** [comment]
do we have the exe's readily available, or do i need to go and download them>

**Comment by Python-Exoproject** [comment]
I posted in discord but ill also post this to the issue. The only needed exe is the one I mentioned and attached above for Maniac Mansion, the rest are just a change to machine=tandy except where noted.

**Comment by exoscoriae** [comment]
Amazon - changed
Nine Princes in Amber - changed
Dragonworld - changed
Fahrenheit 451 - changed
Perry Mason: The Case of the Mandarin Murder - changed
Treasure Island - changed
Wizard of Oz - changed
Zak McKracken and the Alien Mindbenders - changed

**Comment by exoscoriae** [comment]
KQ4 - This game already has a launch option in the main start up (dosbox vs scummvm) and then 4 more once you get into dosbox (agi, sci sb, sci mt32, and ultimate).

Putting the AGI by itself in the main launch doesn't make any sense, and is confusing for the user. Putting all 4 options in the main launcher means having to give each one it's own conf file, which is incredibly messy and unnecessary. So I'm debating if there is any clean way to add tandy support to the agi build for this one.

Thexder - switching this to Tandy means giving up VGA graphics. That's a heavy loss, so to be integrated into this game it needs a launch menu.

Maniac Mansion - as noted above, we loose mouse support, so this would also have to be a launch menu.

Zak McKraken Enhanced - as noted above, we loose mouse support, so this would also have to be a launch menu.

I generally try to avoid launch menus. So I am debating these changes.

**Comment by exoscoriae** [comment]
Thexder - added menu option
Maniac Mansion (1987) - added menu option and secondary conf (due to change in exe file)
Zak McKracken and the Alien Mindbenders Enhanced (1988) - added menu option

KQ4 still bugs me though. Not sure how or if to proceed there,

**Comment by exoscoriae** [comment]
Came up with splitting the launch batch selection by platform (Tandy, IBM, and ScummVM).
