### ISSUE TITLE
Thunderstrike (1990)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#988]
seems page 2 (probably blank page) is missing

**Comment by SmilingSpectre** [comment]
Found better, but English only manual. I suggest to keep old one as extra.

**Comment by TimberlAndRE-de** [comment]
added to the github folder
maybe the old one (en-fr-de) is useful for the language packs. but since a page is missing, i wouldn't suggest to keep it

**Comment by exoscoriae** [comment]
replaced
