### ISSUE TITLE
Time Commando (1996)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#989]
pages 2 3 6 7 8 9 10 11 29 30 31 32 are missing (and maybe more)

**Comment by TimberlAndRE-de** [comment]
@exoscoriae since you have a scribd account can you check this manual:
https://de.scribd.com/document/420570121/Time-Commando-CD-Manual
in the preview it seems to be complete

**Comment by exoscoriae** [comment]
replaced
