### ISSUE TITLE
All-American College Football (1991)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoDOS#99]
note of www.theunderdogs.org on page 2/3
page 1 is on the last page because it is saved as double paged 
pages 50 51 are missing
page number 55 appears twice with different content  probably already in the original a misprint (second page 55 is obviously page 56)

**Comment by TimberlAndRE-de** [comment]
agathosdaimon scanned

- [ ] manual

added to the github folder

**Comment by exoscoriae** [comment]
replaced
